### ISSUE TITLE
Syntax highlight colors differ between Dark and System modes

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#74416]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Syntax-highlight-colors-differ-between-D/10431662)._

---
Version 17.7.0 Preview 6.0

With Dark theme selected, methods are yellow, while with System setting they are white.

![image.png](https://aka.ms/dc/image?name=B4b55140e15454c92b709f7969520ea0d638268491833012644_20230805-211942-image.png&tid=4b55140e15454c92b709f7969520ea0d638268491833012644)

![image.png](https://aka.ms/dc/image?name=B3e9360cf6102464e86bfe776964efeeb638268491907778881_20230805-211950-image.png&tid=3e9360cf6102464e86bfe776964efeeb638268491907778881)

---
#### Feedback Bot on 8/6/2023, 09:15 PM: 

(private comment, text removed)
#### Feedback Bot on 8/10/2023, 02:31 AM: 

(private comment, text removed)
#### Feedback Bot on 8/16/2023, 03:24 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
@JoeRobich ?

**Comment by JoeRobich** [comment]
My guess is that System mode must use a different theme id than the 4 we support (Light, Blue, Blue (Extra Contrast), and Dark). Since System mode could switch between Light and Dark, we would need to additionally identify if the theme is effectively Light or Dark and be able to listen for changes in order to determine which color scheme to apply.

**Comment by CyrusNajmabadi** [comment]
@JoeRobich I would expect 'system' to not be a special theme itself.  It should just be a chocie for the editor to then itself choose between light/dark.  The languages wouldn't have to listen or care about anything.

**Comment by JoeRobich** [comment]
> I would expect 'system' to not be a special theme itself.

Unfortunately that isn't the case.


![Image](https://github.com/user-attachments/assets/117644a1-7760-470d-9a6c-73aef8578909)
