### ISSUE TITLE
Replacing using System with #include <stdio.h> in Roslyn C# Syntax Tree Rewriter

### ISSUE THREAD

**Issue by dadavadd** [dotnet/roslyn#74426]
I'm working on a C# project using the Roslyn API where I need to transform a C# syntax tree to a pseudo-C++ syntax tree. Specifically, I need to replace using System; with #include <stdio.h>. However, I'm running into issues when trying to manipulate the UsingDirectiveSyntax.

![image](https://github.com/user-attachments/assets/a06be2cb-9424-4862-8017-5b04f3a838ef)

![image](https://github.com/user-attachments/assets/444d539d-130c-4379-86c7-e9affb04e93e)

**Comment by CyrusNajmabadi** [comment]
You're just replacing the namespace portion.  You'd need to replace the rest of it as well

**Comment by dadavadd** [comment]
> You're just replacing the namespace portion. You'd need to replace the rest of it as well

What might this look like?

**Comment by CyrusNajmabadi** [comment]
You'd have to replace the .UsingKeyword part of it.

Note; actually doing a syntax tree transformation isn't helping you at all here.  You're not creating C#, so having a C# syntax tree with bogus nodes in it doesn't enable any scenarios.
