### ISSUE TITLE
C# rename default constructor argument which is used as a property

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#74425]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/C-rename-default-constructor-argument-w/10701487)._

---
[severity:It's more difficult to complete my work]
The refactoring target is a public sealed record with a default constructor:

```
public sealed record RenameTarget (string ArgumentToRename);
```

The _ArgumentToRename_ is used in other classes, as it is publicly available. If a rename (using F2), only the argument name is changed. This immediately causes build errors (of course), because the references are not updated.

---
#### Feedback Bot on 7/12/2024, 01:22 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Cosifne** [comment]
It should be fixed in this https://github.com/dotnet/roslyn/pull/74168
