### ISSUE TITLE
Syntax highlight is half broken in both VS 17.10 and VS 17.11 P3

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/roslyn#74422]
**Version Used**: 17.10.4 and 17.11 P3

**Steps to Reproduce**:

1. Clone https://github.com/Sergio0694/ComputeSharp
2. CTRL + , and jump to `InitVtblForID2D1EffectImplAndID2D1DrawTransform` (in `ComputeSharp.D2D1.Interop.Effects.PixelShaderEffect`)

Other repos seem to work (most of the time), so don't really have a minimal standalone repro.

**Expected Behavior**:

Syntax highlight should work normally.

**Actual Behavior**:

Syntax highlight is half broken, mostly around type names in member access expressions, it looks like:

![image](https://github.com/user-attachments/assets/777e921e-4f44-41b8-9e46-05dcd762e9e1)

You can see syntax highlight is also not working for those `cref` type names in XML docs.

This is VS 17.10.4. In VS 17.11 P3, the effect is kinda even worse, with colors flickering all the time as you scroll:

https://github.com/user-attachments/assets/2dbdcae0-b367-4d85-83c6-89a684613f2f

cc. @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
fixed with https://github.com/dotnet/roslyn/pull/75796
