### ISSUE TITLE
See squigglies in #if'd code but Quick Actions don't work.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#74438]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/See-squigglies-in-ifd-code-but-Quick-A/10703554)._

---
#if NET5_0_OR_GREATER
namespace Foo;

public record File(FileStream f);
#else
using System.IO;

namespace Foo;

public record File(FileStream f);
#endif

I have the top left TFM selection dialog set to "net472", so that the net80 top part of the file is greyed out.

I see squigglies under FileStream, because the using statement is missing. Good. I see there are Quick Actions available. Good.
![image.png](https://aka.ms/dc/image?name=Bc4825977b9034fec996d79f2cc25d88b638566962627149443_20240715-201102-image.png&tid=c4825977b9034fec996d79f2cc25d88b638566962627149443)

I ctrl-. to open the dropdown of actions. Nothing happens; no dropdown. If I change the TFM selection to "net80", ctrl-. works. (Same behaviour using the icon.)

Desired outcome: either I don't see squigglies and so no quick actions, or I see squigglies and I can see and execute the quick actions.

---
#### Feedback Bot on 7/16/2024, 00:09 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Errors that are shown are the combined info about the file, analyzing it for each TFM.  Lightbulbs, however, are for the current TFM.
