### ISSUE TITLE
AddUsing doesn't repond to "CS0428"

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#7443]
Open DoubleKeywordRecommender.cs (in Roslyn.sln) and paste in:
```
        int x()
        {
            System.Collections.Generic.IEnumerable<int> x = null;
            return x.Any
        }
```
Add Using won't try to add System.Linq because there's already some "Any" brought in by the usings, resulting in 
```
CS0428	Cannot convert method group 'Any' to non-delegate type 'int'. Did you intend to invoke the method?
```
AddUsing doesn't list that error as one that it fixes. 

Interestingly, I can't GTD on that Any or get QuickInfo for it. These are the usings in the file.
```
using System.Threading;
using Microsoft.CodeAnalysis.Completion;
using Microsoft.CodeAnalysis.CSharp.Extensions;
using Microsoft.CodeAnalysis.CSharp.Extensions.ContextQuery;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.CSharp.Utilities;
using Microsoft.CodeAnalysis.Shared.Extensions;
```

**Comment by rchande** [comment]
FYI @CyrusNajmabadi

**Comment by Pilchie** [comment]
The existing `Any` extension method is `Microsoft.CodeAnalysis.CSharp.CSharpExtensions.Any`.  However, the root of the problem is that there are no parentheses.

**Comment by rchande** [comment]
@Pilchie Add using definitely works without parens--try the following example.

```
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

class Program
{
    static void Main(string[] args)
    {
        args.Any
    }
}
```

**Comment by Pilchie** [comment]
@rchande: I agree that it does in the absence of the other method, and it does in your case if you add the ().  It's only in the case where you have something which doesn't apply *and* you are missing the () that you run into the reported issue.
