### ISSUE TITLE
Support JavaScript style documentation comments

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#74524]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Support-JavaScript-style-documentation-c/1527220)._

---
It would be helpful if we could write in C#:
	/// Output folder path.
	protected static string _Backup;

Instead of
	///<summary></summary>
	protected static string _Backup;

---
#### Feedback Bot on 9/12/2021, 10:54 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Closing out.  this is a langauge suggestion.  A discussion should be opened at dotnet/csharplang.
