### ISSUE TITLE
typeof(T) and "using OfficeOpenXml.FormulaParsing.Excel.Functions.Text"

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#74528]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/typeofT-and-using-OfficeOpenXmlFormu/10690923)._

---
Hi,

We are constantly bumping into next issue with IntelliSense 

when typed or copy code, which contains 
```
typeof(T)
```

a new using is appended to the file
```
using OfficeOpenXml.FormulaParsing.Excel.Functions.Text;
```

Then the code compiles and does not show any issues.

It crashed in runtime, of course, because this is nonsense. 

Some sort of solution for this would be welcomed, e.g. do not add automatic using for typeof(T)

Thanks,
Regards,
Evgeny

---
#### Feedback Bot on 6/25/2024, 11:50 PM: 

(private comment, text removed)
#### Mika Dumont [MSFT] on 7/23/2024, 02:39 PM: 

(private comment, text removed)
#### evgeny.muryshkin on 7/23/2024, 02:45 PM: 

(private comment, text removed)

**Comment by EvgenyMuryshkin** [comment]
As a potential fix - have a list of exempt types in "Tools > Options > Text Editor > C# > Advanced" settings might be a solution for this - can add “T” in there.

Thanks.

**Comment by CyrusNajmabadi** [comment]
Closing out as no repro.  T shows up in the list when in a generic context.    If it is not showing up, please supply a repro showing where this does not happen.
