### ISSUE TITLE
Code Search should display namespace of types found

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#74521]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Code-Search-should-display-namespace-of-/10665553)._

---
**Code Search** is a really useful feature. Recently, I've been using it to explore a large code base.

Finding where a type is (file name and project) is great, but I often would like to see also the **namespace** where the type resides. With the current implementation, I have to open the source file first and visually search for the occurrence of the `namespace` keyword.

Here is a sample search:

![image.png](https://aka.ms/dc/image?name=B78978a6746ef49019a7d621ac8b909f2638520668038989444_20240523-151323-image.png&tid=78978a6746ef49019a7d621ac8b909f2638520668038989444)

---
#### Feedback Bot on 5/23/2024, 11:11 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback here.
