### ISSUE TITLE
Using directives should be collapsible when placed below a file-scoped namespace declaration.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#74525]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Using-directives-should-be-collapsible-w/1567653)._

---
When using a file-scoped namespace, I like to place the namespace declaration at the top of the file followed by my `using` directives. Visual Studio will give me a weak warning about "misplaced using directives" and will not give me the option to collapse those directives.

Those `using` directives are *not* misplaced; I just want a similar structure to my Java projects.

---
#### Feedback Bot on 10/31/2021, 11:32 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
> Visual Studio will give me a weak warning about "misplaced using directives"

That indicates that that project has stated that usings should only be outside of the namespace.

> and will not give me the option to collapse those directives.

I don't repro this.  They collapse fine locally:

![image](https://github.com/user-attachments/assets/3f1bffe3-aa27-4e63-bd31-c101918738df)
