### ISSUE TITLE
Data annotations on the class makes the visual of the properties very polluted

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#74520]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Data-annotations-on-the-class-makes-the-/10674049)._

---
When creating a new class and it uses data annotations (MaxLength for example), all the properties have data annotations, making the visual very difficult to read.
![image.png](https://aka.ms/dc/image?name=B17370562eeaf4517bf5a29ebc883645b638530150985180795_20240603-093816-image.png&tid=17370562eeaf4517bf5a29ebc883645b638530150985180795)

Maybe if the data annotations has a little less contrast, for example, will be easier to read the properties of the class

---
#### Feedback Bot on 6/3/2024, 10:28 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Closing out.  this is codelens ui.  moved back to editor.
