### ISSUE TITLE
Replacement param for obsolete method

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#74522]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Replacement-param-for-obsolete-method/10687827)._

---
I sometimes encounter old code like this:

```

[Obsolete("Use .NET 4.0 and above IsNullOrWhiteSpace instead")]
public static bool IsNullOrWhiteSpace(this string value)
{
    return string. IsNullOrEmpty(value?. Trim());
}

```

I would like to have the option to specify the new method that should be used somehow in a typed manner, so the IDE can pick it up and automatically suggest a refactor:

```
[Obsolete(replacement: string. IsNullOrWhiteSpace(string))]
public static bool IsNullOrWhiteSpace(this string value)
{
    return string. IsNullOrEmpty(value?. Trim());
}
```

---
#### Feedback Bot on 6/20/2024, 10:24 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Closing out as not planned.
