### ISSUE TITLE
CSharpSemanticModel.GetSymbolInfo returns SymbolInfo with Symbol equal to null

### ISSUE THREAD

**Issue by salaerts** [dotnet/roslyn#74537]
**Version Used**: 4.10.0

**Steps to Reproduce**:

Disclaimer: I ran into this issue at the "hello word" stage of trying something with the Roslyn analyzers. So there's a high chance this is me not understanding the problem instead of this being an actual bug.

1. Create a very trivial 'hello world' style syntax tree containing a single class, with a single method calling Console.WriteLine (example below)
2. Create a compilation and semantic model for that tree
3. Find the InvocationExpressionSyntax for the Console.WriteLine statement
4. Get the SymbolInfo for the previously returned expression syntax

```
var tree = CSharpSyntaxTree.ParseText(@"
	public class MyClass 
	{
		void SomeMethod() { System.Console.WriteLine(""Printing""); }
	}
");

var mscorlib = MetadataReference.CreateFromFile(typeof(object).Assembly.Location);
var compilation = CSharpCompilation.Create("MyCompilation",
	syntaxTrees: new[] { tree }, references: new[] { mscorlib });
var root = tree.GetRoot();
var model = compilation.GetSemanticModel(tree);

// Retrieving the method declaration works fine
var methodSyntax = root.DescendantNodes().OfType<MethodDeclarationSyntax>().First();
// And getting the declared symbol also works fine
var methodSymbol = model.GetDeclaredSymbol(methodSyntax);

// Getting the expression syntax works, returning the "System.Console.WriteLine("Hello World");" statement
var invokes = root.DescendantNodes().OfType<InvocationExpressionSyntax>().First();
// But the following call always returns an object with Symbol == null
var info = model.GetSymbolInfo(invokes);

if (info.Symbol == null)
{
        // This line is always hit
	Console.WriteLine("No symbol info returned");
	return;
}
```

For as far as I can follow along while debugging this, I saw that the CSharpSemanticModel class hits this line when generating a result:

```
// Empty typically indicates an error symbol that was created because no real
// symbol actually existed.
 return SymbolInfoFactory.Create(ImmutableArray<Symbol>.Empty, LookupResultKind.Empty, isDynamic);
```

**Expected Behavior**: A valid SymbolInfo object for the line "System.Console.WriteLine("Hello World");"

**Actual Behavior**: The returned SymbolInfo has it's Symbol property set to null and the list of candidate symbols is empty

**Comment by salaerts** [comment]
Ok, so for the following code:

```csharp
var tree = CSharpSyntaxTree.ParseText(@"
	public class MyClass 
	{
		void SomeMethod() { System.Console.WriteLine(""Hello World""); }
	}
");
var mscorlib = MetadataReference.CreateFromFile(typeof(object).Assembly.Location);
var compilation = CSharpCompilation.Create("MyCompilation",
    syntaxTrees: new[] { tree }, references: new[] { mscorlib });
```

I get these diagnostics messages:

> Error: Program does not contain a static 'Main' method suitable for an entry point
> Error: The type or namespace name 'Console' does not exist in the namespace 'System' (are you missing an assembly reference?)

The first error I can understand, there is no Main method and there are no top-level statements so that makes sense.
But that second error is a bit more puzzling. If I put the same code in a .cs file it compiles just fine.
I'm quite sure the Console class has existed in the System namespace since at least .NET Framework 1.1 and as far as I know it should be provided using the mscorlib reference.

**Comment by jjonescz** [comment]
> I'm quite sure the Console class has existed in the System namespace since at least .NET Framework 1.1 and as far as I know it should be provided using the mscorlib reference.

That's true, but aren't you on .NET Core? There it's in System.Console.dll - https://learn.microsoft.com/en-us/dotnet/api/system.console?view=net-8.0. You might want to use https://github.com/jaredpar/basic-reference-assemblies

**Comment by salaerts** [comment]
Ah yes, that was it. Thanks a lot for the help!
That basic reference repo is very convenient, thanks.
