### ISSUE TITLE
Collection expressions apply to types implementing IEnumerable<T> and containing an Add(X) method but no implicit conversion between X and T

### ISSUE THREAD

**Issue by Arthri** [dotnet/roslyn#74543]
**Version Used**: `4.10.0-3.24324.8 (04fb3916)`

**Steps to Reproduce**:
```cs
using System;
using System.Collections;
using System.Collections.Generic;

Tk l = [new Tk()]; // error, dotnet build and dotnet format
Zd v = [new Zd()]; // error, dotnet format only

interface Irrelevant<T> : IReadOnlyDictionary<string, T>
{
    T IReadOnlyDictionary<string, T>.this[string key] => throw null;
    IEnumerable<string> IReadOnlyDictionary<string, T>.Keys => throw null;
    IEnumerable<T> IReadOnlyDictionary<string, T>.Values => throw null;
    int IReadOnlyCollection<KeyValuePair<string, T>>.Count => throw null;
    bool IReadOnlyDictionary<string, T>.ContainsKey(string key) => throw null;
    IEnumerator<KeyValuePair<string, T>> IEnumerable<KeyValuePair<string, T>>.GetEnumerator() => throw null;
    bool IReadOnlyDictionary<string, T>.TryGetValue(string key, out T value) => throw null;
}

class Tk : Irrelevant<Tk>
{
    IEnumerator IEnumerable.GetEnumerator() => throw null;
    public void Add(Tk a) => throw null;
}

class Zd : Irrelevant<Zd>
{
    public IEnumerator GetEnumerator() => throw null;
    public void Add(Zd a) => throw null;
}
```
This can be observed on the latest .NET 8.0.3xx SDK: `dotnet build` prints one error, but `dotnet format` prints two

Compiling against the main branch results in one error [sharplab(main)](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK7wCYgNQB8ACATAIwCwAUPgAwAE+xAdAMID2ANmwKYDGCULMAM4BuCtTrEALKPIUAKgGsabGgF4aAbRicA7jUUAKAJQBdGQC0MNAG5rN2vZeNmKFWAk7IAZhG6caAJLIyJxc1hAwCAA8cgB8NCCBAEqcEBgA8jBsAJ4AIlC8/DAQyNlR9FRw+rEUAN4UNI36yakZWXkFfAIlZRVVcQwIABZQghoVNAqc2SZq8cPILHowqBwyTRIAzOXEVPEBKWmZOfmF3aU7ldUMANLTgnM0C0s0K2sNTfTbcS1H7addYoXPrXABqEDYqE4D1U8yGi2WqzY6ya7l+bRyrA4PEBUTu2XBkM4AAVoMhLv1YrFmCx0AhHs9Ee9yBtgCx2Ojjh0zkDertKTTItAhPiDBMptkjAz4S83siPo0AgBRFZgTwQBAscn4wlQ0lQckguLxL546a6klkinVakAcU4CBVqDVyA1WuM0oRryRKMabI5B1aXIBRR61oGclK9oQFrFu0m0yqtPpchsEKhUthTxlTPl5AAvq5KIR9EpEkEQmEItFFDVyPUWU1lar1ZrkFsGNGnS63cgPVnGd7mRt8Js6JIaABBDAYAyKGgQTNwr1ymSF2TFmiWBKBYKhTjhSJRSx1hsjsfN52trU0Lst11t/vL2U+hV0Mf4CfT2fbxeel/MuuQA==), while compiling against the default branch(`4.8.0-7.23558.1 (e0917286)` as of writing) results in two errors [sharplab](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAICYCMBYAUKgBgAJVMA6AYQHsAbGgUwGNgBLKqAZwG49CTMALD1x4AKgGsiNIgF4iAbSj0A7kQkAKAJQBdYQC04RAG6yFS1Qa268eFlGD0wAMwCGjekQCSYMPQZGXewAeUQA+IhAvACV6FzgAeSgaAE8AERZmNigXMGSg0gIYNVC8AG88Ikq1aNiEpLSM1nYcvIKisLJgAAsWDnkConF6ZO1ZcO6wKlUoCDphKv4AZnzMAnDPGLjElPTM5tyVwuKyAGlhjjGiCamiGbmKqtJlsJqt+t2m7IO244A1FxoEHoFxk4y6k2msxo8yqdmArzqKWodCYnyCZ2S/0B9AACi4WGBDu1QqFKFRoPDQVdwTc7tCHpUAEZUWgI7YNPZfVqrYlk+z4zgY9QDIbJTSXa6Q+64BaeACiMwAto4XMAqISMVigXiCUTiuEnujhlrcfjCT8wqSAOL0YAKiDKsCq9VaCU0qX0mVVZmsja1dkfLItPUdUS5G3AE3C1aDYZFcnw0TGAFA8VUyW3KHCAC+Nnw6DUkki3l8/kCwBC4hKuHKXsq8qVKrVYCWZAj9sdzrArvT7sz0oWqEWJAERAAgnA4OoJEQXGmwRD+57cyJ80QDBEvD4/PQAsEDNXa4Phw2HU31UR242nc2ewvaVmGSRh6hRxOpxu527F3Sc3ggA===)

**Diagnostic Id**: `"CS0029: Cannot implicitly convert type 'Tk' to 'System.Collections.Generic.KeyValuePair<string, Tk>'"`

**Expected Behavior**: Two errors, on both top-level statements

**Actual Behavior**: One error, on the first top-level statement

**Comment by cston** [comment]
The current behavior is expected.

The [*collection expression conversion*](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-12.0/collection-expressions.md#conversions) requires each expression element to be implicitly convertible to the [*iteration type*](https://github.com/dotnet/csharpstandard/blob/standard-v6/standard/statements.md#1295-the-foreach-statement).

For `Tk`, the iteration type is `KeyValuePair<string, Tk>` from the `IEnumerable<T>` implementation; for `Zd`, the iteration type is `object` from the `public IEnumerable GetEnumerator()` implementation.

In 4.8.0, the `public` `GetEnumerator()` was incorrectly overlooked, resulting in two errors rather than one.
