### ISSUE TITLE
MS.CA.LanguageServer depends on MS.VS.Telemetry via Microsoft.CodeAnalysis.Remote.Workspaces

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#74568]
We are shipping MS.VS.Telemetry (though unused) in C# standalone due to a dependency on `Microsoft.CodeAnalysis.Remote.Workspaces` which depends on it.  Additionally, that project depends on `Microsoft.ServiceHub.Client` which itself has a dependency on the telemetry dll.  

We should refactor the code to either move all the components used in the language server out, or remove the need for Remote.Workspaces to depend on `Microsoft.VisualStudio.Telemetry` / `Microsoft.ServiceHub.Client`

Likely will need to move all of the project system brokered service definitions out, as well as the various descriptors and other pieces.

cc @jasonmalinowski , @tmat

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If this needs to happen, please reactive and place in an appropriate milestone.
