### ISSUE TITLE
OrganizeDocument: ArgumentException: The specified SnapshotPoint is on a different ITextSnapshot than this SnapshotPoint.

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#74594]
1. Have any C# project stored in Git with no pending changes
2. Open any .cs file, add an unused using and any other line of code in the class below (needs to be two adds, one for using and one other)
3. In Git Changes, right-click on the changed file, Compare with Unmodified
4. Right-click the editor diff and select Remove and Sort usings

![image](https://github.com/user-attachments/assets/c624168f-bcbc-477d-9ac5-033974d761a1)

ArgumentException: The specified SnapshotPoint is on a different ITextSnapshot than this SnapshotPoint.

![image](https://github.com/user-attachments/assets/167f1e62-5a82-4dde-9bd7-74b671b529f8)

https://github.com/dotnet/roslyn/blob/52e29db514078c9f1bcf6d4c01a106d69f95d63b/src/EditorFeatures/Core/Organizing/OrganizeDocumentCommandHandler.cs#L128

This is because this code grabs the `caretPoint` from the `subjectBuffer`, which is C#, but then calls `textView.GetTextElementSpan(caretPoint.Value)` which expects a point in the top (projection) buffer.

It needs to also grab a caretPoint from the top buffer, and use that for the indicatorFactory, because that expects a span on the top (projection) buffer, not the subject buffer.

```
	Microsoft.VisualStudio.Platform.VSEditor	WpfTextView.ValidateBufferPosition Line 4829
	Microsoft.VisualStudio.Platform.VSEditor	WpfTextView.GetTextElementSpan Line 687
	Microsoft.CodeAnalysis.EditorFeatures	OrganizeDocumentCommandHandler.ExecuteAsync
	Microsoft.CodeAnalysis.EditorFeatures	OrganizeDocumentCommandHandler.ExecuteCommand
	Microsoft.CodeAnalysis.EditorFeatures	OrganizeDocumentCommandHandler.ExecuteCommand
	Microsoft.VisualStudio.Platform.VSEditor	EditorCommandHandlerService.ExecuteStartingAtIndex Line 218
	Microsoft.VisualStudio.Platform.VSEditor	GuardedOperations.CallExtensionPoint Line 549
	Microsoft.VisualStudio.Platform.VSEditor	EditorCommandHandlerService.ExecuteStartingAtIndex Line 232
	Microsoft.VisualStudio.Platform.VSEditor	EditorCommandHandlerService.Execute Line 154
	Microsoft.VisualStudio.Platform.VSEditor	EditorCommandHandlerService.ExecuteCommandHandlerChain Line 318
	Microsoft.VisualStudio.Platform.VSEditor	EditorCommandHandlerService.Execute Line 159
```

**Comment by KirillOsenkov** [comment]
@CyrusNajmabadi should be an easy fix

**Comment by CyrusNajmabadi** [comment]
@KirillOsenkov def feel free to contribute :D

**Comment by KirillOsenkov** [comment]
@CyrusNajmabadi here you go: https://github.com/dotnet/roslyn/pull/74645

**Comment by KirillOsenkov** [comment]
Oops, this was closed by accident. The PR is still outstanding.
