### ISSUE TITLE
Code issues

### ISSUE THREAD

**Issue by LHK-666** [dotnet/roslyn#74614]
### Type of issue

Code doesn't work

### Description

            var projectId = ProjectId.CreateNewId();
            var versionStamp = VersionStamp.Create();
            var projectInfo = ProjectInfo.Create(
                projectId,
                versionStamp,
                "AdhocProject",
                "AdhocProject",
                LanguageNames.CSharp,
                metadataReferences: new[]
                {
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
                MetadataReference.CreateFromFile(typeof(Uri).Assembly.Location),
                MetadataReference.CreateFromFile(typeof(InstruControlTool).Assembly.Location),
                MetadataReference.CreateFromFile(typeof(BrowsableAttribute).Assembly.Location),
                MetadataReference.CreateFromFile(Assembly.Load("netstandard, Version=2.0.0.0").Location),
                MetadataReference.CreateFromFile(Assembly.Load("System.Runtime, Version=0.0.0.0").Location)
                });
            var project = workSpace.AddProject(projectInfo);
            return project;
Use this method to add a solution when the code is executed to var project=workSpace AddProject(projectInfo); Display 'Language C #' unsupported during runtime

[在此处输入反馈]

### Page URL

https://learn.microsoft.com/zh-cn/dotnet/api/microsoft.codeanalysis.adhocworkspace.addproject?view=roslyn-dotnet-4.7.0#microsoft-codeanalysis-adhocworkspace-addproject(system-string-system-string)

### Content source URL

https://github.com/dotnet/roslyn-api-docs/blob/live/dotnet/xml/Microsoft.CodeAnalysis/AdhocWorkspace.xml

**Comment by CyrusNajmabadi** [comment]
This operation is not supported in the adhoc workspace.  So this is by design.
