### ISSUE TITLE
No warning on use of static variable before initialization

### ISSUE THREAD

**Issue by chuckries** [dotnet/roslyn#74612]
The following code compiles with no warnings or errors and outputs 0: 

```cs
    internal class Program
    {
        static int first = second;
        static int second = 42;

        static void Main(string[] args)
        {
            Console.WriteLine(first);
        }
    }
```

This may be unexpected for developers; I was surprised there was no warning or error for this.

**Comment by jaredpar** [comment]
Thanks for taking the time to file this feedback but this behavior is "By Design". Static variables in C# are considered initially assigned (spec section 5.3.1) and hence always available for usage.
