### ISSUE TITLE
Backing field symbol for record with a primary constructor in a referenced project is missing

### ISSUE THREAD

**Issue by kzu** [dotnet/roslyn#74634]
**Version Used**:  Compiler version: '4.11.0-2.24304.1 (e68227ea)'. Language version: 12.0

**Steps to Reproduce**:
1. Given a library that references another library
2. Both libraries have a record type with a primary constructor
3. A source generator running with a compilation from the main library, cannot access the backing field symbol for the referenced library record, but it can for the locally declared record.

This is inconsistent and prevents a generator to treat source symbols from local + referenced types uniformly. 

I believe this to be the root cause of [an issue with the Orleans serialization code generation](https://github.com/dotnet/orleans/issues/9092) for record types in referenced projects.

A minimal repro, with source-code provided, is ideal.  Using [sharplab](https://sharplab.io/) is preferred for compiler/language issues whenever possible.

Full repro: https://github.com/kzu/BackingFieldRecordSymbolMissing

The repro contains an analyzer project with the two libraries, which can be directly run with F5 to see the problem.
The output of the generator is a diff of the members accessible by using `symbol.GetMembers()` on both symbols, which looks like the following and showcases the missing backing field:

```
// Local                                   External
// --------------------------------------------------------------------------------
// .ctor                                   .ctor
// .ctor                                   .ctor
// <Amount>k__BackingField                 
// <Clone>$                                <Clone>$
// Amount                                  Amount
// Deconstruct                             Deconstruct
// EqualityContract                        EqualityContract
// Equals                                  Equals
// Equals                                  Equals
// get_Amount                              get_Amount
// get_EqualityContract                    get_EqualityContract
// GetHashCode                             GetHashCode
// op_Equality                             op_Equality
// op_Inequality                           op_Inequality
// PrintMembers                            PrintMembers
// set_Amount                              set_Amount
// ToString                                ToString

```
**Expected Behavior**: whether the symbol is locally defined or via metadata reference, the same backing fields should be available.

**Actual Behavior**: only the local records contain the backing fields.

NOTES:

1. Setting `<ProduceReferenceAssembly>false</ProduceReferenceAssembly>` in the referenced project, AND `<CompileUsingReferenceAssemblies>false</CompileUsingReferenceAssemblies>` on the consuming one, still doesn't produce the right list of symbols. See https://github.com/kzu/BackingFieldRecordSymbolMissing/commit/a2f9b6c4bd29479ba279b8c40d9e14cd510b494c

**Comment by CyrusNajmabadi** [comment]
> This is inconsistent and prevents a generator to treat source symbols from local + referenced types uniformly.

This is not a thing in Roslyn.  Metadata may contain different data. For example, it may not include private information.

**Comment by kzu** [comment]
I'm talking about how Orleans does codegen and does not distinguish in its generator records locally defined from referenced, since all it needs is access the field types and names. You're saying it's by design that that info isn't available and this is not a bug? (just clarifying so I plan accordingly a workaround, rather than expect a fix :)).

**Comment by kzu** [comment]
Gotcha. Thanks for the explanation and the quick reply 💯
