### ISSUE TITLE
Short syntax for lambda declaration

### ISSUE THREAD

**Issue by Romfos** [dotnet/roslyn#7463]
//short lambda declaration for delegates without return keyword
//1. current syntax
example 
    .ExampleMethodName(() => x + 1)
    .ExampleMethodName(() => x + 1).
    .ExampleMethodName(() => x + 2).
    .ExampleMethodName(() => x + 3).

//short syntax
var x = 0;
example 
    .ExampleMethodName(=> Console.WriteLine("1"))
    .ExampleMethodName(=> x + 1).
    .ExampleMethodName(=> x + 2).
    .ExampleMethodName(=> x + 3).

//2. short lamda syntax for variable declaration
//current syntax
Action y = () => Console.WriteLine("123");
y();

//short syntax with '=>' operator
Action y => Console.WriteLine("123");
y();

//maybe var y => Console.WriteLine if Console.WriteLine have once signature;

//3. autocast lamda syntax for delegate
//current syntax

Invoke(new Action(() => {..})); or Invoke(delegate () => {..});
//short syntax
Invoke(=> {..});

Where Invoke method have signature > void Invoke(Delegate proc);

**Comment by HaloFour** [comment]
Your second case isn't valid C# syntax currently since you are referring to a method group.  The valid syntax would be `Action y = Console.WriteLine;` which is shorter than your proposal.

**Comment by Romfos** [comment]
HaloFour, maybe Action y => Console.WriteLine isn't good example.
Action y => Console.WriteLine(params) //short version
vs
Action y = () => Console.WriteLine(params) //current version

**Comment by alrz** [comment]
You are suggesting a special assignment operator just for a lambda expression that takes no args? and if I get it right the whole proposal saves two keystrokes per each lambda expression that takes no args? and number 3 has nothing to do with a lamba expressions that takes no args. are you suggesting the autocast should be a special case for a lamba expression that takes no args?

**Comment by dsaf** [comment]
If maximally short code is the optimum then perhaps F# could be a good choice.

**Comment by Romfos** [comment]
for improvment by number 3:

//how it's work now:
void Invoke(Delegate proc);
Invoke(new Action(() => {..}));

//not work now
Invoke(() => {...});

//how it's doing work. "() => {...}" automaic casting, to Delegate object.
Invoke(() => {..});

//how it's doing work with improvment by number 1
Invoke(=> {...});

Q: You are suggesting a special assignment operator just for a lambda expression that takes no args? and if I get it right the whole proposal saves two keystrokes per each lambda expression that takes no args? 

A:
1. yes, this is improvment for lamda without arguments
2. This is compile-time feature, not as in #3990.

**Comment by alrz** [comment]
@Romfos See, there is no "casting" going on, #3990 suggests a "default" delegate for lambda expressions so it does cover your case. And also, all this happens at compile-time, as it currently does — static type of a lambda expression is known at compile-time.

**Comment by alrz** [comment]
OK, with #117 it actually would be nice if param list becomes optional like `[] => ...`.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
