### ISSUE TITLE
Go to Definition doesn't work sometimes, and I have to retype the symbol to make it work

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#74631]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Go-to-Definition-doesnt-work-sometimes/10713787)._

---
So, more often than not when I try to Ctrl+Click into a Symbol (for example the value of an enum) I don't get the highlight with underline that I would usually get to be able to go to definition, and right clicking and go to definition is not going anywhere.

I often need to re-write the symbol
(For example, let's say I have `MyEnum.EnumValue` and it doesn't allow me to go to definition, I have to delete `EnumValue` so it's just `MyEnum` again, and then I re-enter `.EnumValue` and up until then, the link to definition starts working.

I don't know how to repro as this seems to be non-deterministic, but I constantly find this problem in my regular workflow, I wouldn't think I am the only one seeing this.

---
#### Feedback Bot on 7/31/2024, 11:26 PM: 

(private comment, text removed)
#### Feedback Bot on 8/1/2024, 07:51 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/75001
