### ISSUE TITLE
Quick info stopped working

### ISSUE THREAD

**Issue by Peter-Juhasz** [dotnet/roslyn#74644]
**Version Used**: 17.11.0 Preview 6.0 (no 3rd party extensions enabled)

**Steps to Reproduce**:

It has just suddenly stopped working in all editors (while other language services are working fine):

https://github.com/user-attachments/assets/d438cd32-c5f2-4488-b345-f0e0cab3d729

**Diagnostic Id**:
N/A

**Expected Behavior**:
Quick info works continuously.

**Actual Behavior**:
Quick info stopped working.

**Comment by Peter-Juhasz** [comment]
When I tried to restart Visual Studio, it was completely broken and couldn't load a single package:

![image](https://github.com/user-attachments/assets/08df7cda-0459-4b47-8cb4-969bf836cccc)

I got the following errors in the `ActivitiyLog.xml`:

```xml
  <entry>
    <record>1744</record>
    <time>2024/08/04 08:59:30.279</time>
    <type>Error</type>
    <source>Microsoft.VisualStudio.ComponentModelHost.VsShellComponentModelHost</source>
    <description>Value cannot be null.&#x000D;&#x000A;Parameter name: path</description>
  </entry>
```

```xml
  <entry>
    <record>1757</record>
    <time>2024/08/04 08:59:30.317</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectPackage]Source: &apos;Microsoft.VisualStudio.Validation&apos; Description: Cannot find an instance of the Microsoft.VisualStudio.ComponentModelHost.IComponentModel service.&#x000D;&#x000A;</description>
    <guid>{3347BEE8-D7A1-4082-95E4-38A439553CC2}</guid>
    <hr>0x80131500</hr>
    <errorinfo></errorinfo>
  </entry>
```

**Comment by Peter-Juhasz** [comment]
The second restart was somewhat better (no tons of "could not load package errors"), but it could not load my .NET projects:

![image](https://github.com/user-attachments/assets/dbfc4cf9-9244-4b6f-9066-95ef16b9d6eb)

 - `Engine`, `Game` are simple .NET 8 Class Libraries with no dependencies
 - `Hosting.SilkDirect2D` is a .NET 8 Console Application
 - `Hosting.WinUI3` and `Hosting.WinUI3.Package` are Windows SDK apps

After right click `Reload Project`, it was able to load my projects marked as "incompatible".

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/75001
