### ISSUE TITLE
Is not instance of Class syntax

### ISSUE THREAD

**Issue by omeshechkov** [dotnet/roslyn#7465]
Hello,

I'm not sure if this place is a right place to ask such questions, but I will try..

Is there a way to change/extend expressions like: !(a is SomeClass)
to: a is not SomeClass

I think it's more readable.

Thanks!

**Comment by alrz** [comment]
I would prefer `!is` but I'm not sure if it would add much to be considered in the language.

**Comment by gafter** [comment]
The simplest way is to change your programming language to VB.net.
