### ISSUE TITLE
HelloMetaProgramming/ICompileModule needs better documentation

### ISSUE THREAD

**Issue by muratg** [dotnet/roslyn#7466]
_From @m0sa on January 27, 2015 2:7_

At least on of HelloMetaProgramming.cs or ICompileModule.cs should contain information about the XRE only invoking ICompileModule implementations from paths matching the [preprocess pattern](https://github.com/aspnet/XRE/blob/07fd900f492cea1b285cdbbd5408dbc1d4aab422/src/Microsoft.Framework.Runtime/Project.cs#L29). I just spent way to much time figuring that trivial fact out by browsing through the source code.

_Copied from original issue: aspnet/dnx#1134_

**Comment by muratg** [comment]
_From @mgravell on March 19, 2015 14:59_

Is this still as represented here? https://github.com/aspnet/dnx/issues/39

(waits patiently for documentation...)

**Comment by gafter** [comment]
Roslyn doesn't have anything called HelloMetaProgramming or ICompileModule.

**Comment by muratg** [comment]
I should have linked this bug [to the other one related to ICompileModule functionality](https://github.com/dotnet/roslyn/issues/7466).

@gafter I added you to the internal thread regarding these two bugs I moved over.

cc @davidfowl
