### ISSUE TITLE
Add support for packages containing ICompileModule

### ISSUE THREAD

**Issue by muratg** [dotnet/roslyn#7467]
_From @anurse on January 14, 2015 23:56_

* Scan dependencies for Preprocess flag
* Load 'em up
* Give them to RoslynCompiler somehow
* :sparkles: Run them :sparkles: 

_Copied from original issue: aspnet/dnx#1072_

**Comment by muratg** [comment]
_From @anurse on March 23, 2015 18:4_

This will likely be part of dev-dependencies work in the New Runtime.

**Comment by muratg** [comment]
Moved to beta6 as per the discussions around pending runtime work.

**Comment by muratg** [comment]
_From @per-samuelsson on August 12, 2015 11:11_

Whats the status of this one? It says "Ready", but it's in the backlog milestone. Any info on your thinking regarding this?

**Comment by muratg** [comment]
_From @davidfowl on December 7, 2015 9:32_

/cc @jaredpar

**Comment by gafter** [comment]
@muratg Can you please add a paragraph or two to this issue explaining what it is about?

**Comment by muratg** [comment]
@gafter This is a bug I moved from DNX repo. As we're retiring DNX (and replacing it with dotnet CLI) in RC2, @davidfowl told me that this would be a potential Roslyn feature.

He should be able to give more details, but the main idea is being able to use something like [ASP.NET 5 compile modules](https://github.com/aspnet/dnx/blob/7ac7929aa575e17b3c271e4a7a0c164418de0395/src/Microsoft.Dnx.Compilation.CSharp.Abstractions/ICompileModule.cs) via Roslyn.

**Comment by m0sa** [comment]
it would be nice to make this _internal_ discussion thread mentioned in the original issue public. If this (meta-programming) really is coming to roslyn, it is a huge feature, and deserves at least an entry on the roadmap.

**Comment by gafter** [comment]
If you're saying what I think you're saying, this is a dup of #5561.
