### ISSUE TITLE
Collection Expression Generated Types miss the [CompilerGenerated] attribute

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/roslyn#74676]
**Version Used**: 
VS 17.10.5

**Steps to Reproduce**:
Compile this code:
```
namespace ConsoleApp24 {
    internal class Program {
        static void Main(string[] args) {
            Console.WriteLine("Hello, World!");

            IEnumerable<string> test = ["Test"];

        }
    }
}
```

Then decompile the related assembly.

The class ```u003cu003ez__ReadOnlySingleElementList``` does not have ```[CompilerGenerated]``` on it, however some of its members and private types do.

**Expected Behavior**:
```[CompilerGenerated]``` is present on the type.

**Actual Behavior**:
```[CompilerGenerated]``` is NOT present on the type.

**Comment by cston** [comment]
See also https://github.com/dotnet/roslyn/issues/72539.

**Comment by TonyValenti** [comment]
Thank you @333fred !

**Comment by 333fred** [comment]
@TonyValenti don't thank me, thank @DoctorKrolic. I just merged the PR :slightly_smiling_face:.

**Comment by TonyValenti** [comment]
Thank you @DoctorKrolic !
