### ISSUE TITLE
Generator vs xaml generated files (the "*.g.i.cs")

### ISSUE THREAD

**Issue by Przemyslaw-W** [dotnet/roslyn#74685]
In my source generator, I need to inspect xaml generated files (the "\*.g.i.cs" or "\*.g.cs" files). However, context.Compilation.SyntaxTrees property seems to contain corresponding syntax trees somewhat randomly. Sometimes they are there, and sometimes not. Is there a way to ensure that they are available for my source generator?

**Comment by CyrusNajmabadi** [comment]
When you do a build (like from the command line), you find that those file are there or not non deterministically? 

Can you please supply a repro where you see this?

**Comment by Przemyslaw-W** [comment]
I cannot reproduce it anymore. Looks like something was temporary wrong on my machine. Closing this issue for now, until I will be able to reproduce
