### ISSUE TITLE
The [InterceptsLocation] attribute generates a different "data" string for big-endian platforms

### ISSUE THREAD

**Issue by steveharter** [dotnet/roslyn#74682]
**Version Used**: 4.8.0

**Steps to Reproduce**: See https://github.com/dotnet/runtime/issues/105311

**Expected Behavior**: big-endian platforms have the same string value for the "data" parameter as little-endian platforms.

**Actual Behavior**: big-endian is different than little-endian due to byte swapping on `char`.

See also
https://github.com/dotnet/runtime/issues/101079
https://github.com/dotnet/runtime/issues/104693
https://github.com/dotnet/roslyn/issues/72133

**Comment by RikkiGibson** [comment]
The cause appears to be that `SourceText.GetContentHash()` does not produce the same hash on big-endian, even if the text is the same character-for-character.

**Comment by CyrusNajmabadi** [comment]
I did doc this as: 

```
        /// This hash is safe to use across platforms and across processes, as long as the same version of Roslyn is
        /// used in all those locations. 
```

So this does seem to be a bug in the impl.

I'm curious if there's a fast way to do xxhash in an endian-independent fashion.  @tannergooding @stephentoub ?

**Comment by stephentoub** [comment]
xxhash is not endian-dependent. Given the same sequence of bytes in, you get the same output sequence of bytes, regardless of whether on a big or little endian machine.

If you're getting a different answer, my question is because a different sequence of bytes is being fed in, e.g. if you just reinterpret cast chars to bytes, that input sequence of bytes will be different based on endianness.

**Comment by CyrusNajmabadi** [comment]
> e.g. if you just reinterpret cast chars to bytes, that input sequence of bytes will be different based on endianness.

Yes. That's what is going on. Is there a recommended way to work with chars and xxhash in such a way as to be endian independent and fast?  Thanks!

**Comment by stephentoub** [comment]
> > e.g. if you just reinterpret cast chars to bytes, that input sequence of bytes will be different based on endianness.
> 
> Yes. That's what is going on. Is there a recommended way to work with chars and xxhash in such a way as to be endian independent and fast? Thanks!

You could reverse the endianness only if you're on a big-endian machine. Then there's no cost for the vast majority case where you're on little endian.

**Comment by CyrusNajmabadi** [comment]
Is there a recommended helper for that if I've got a span of bytes? Just wanting to get the best performance even in the uncommon case. Tnx!
