### ISSUE TITLE
Build task is crashing on ETA and VSI runs

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#7470]
C:\Users\dotnet-bot\.nuget\packages\Microsoft.Net.Compilers\1.2.0-beta-20151211-01\tools\Microsoft.CSharp.Core.targets(67,5): error MSB3883: Unexpected exception:  [d:\j\workspace\roslyn-internal_prtest_win_dbg_unit32\Open\src\Features\Core\Portable\Features.csproj]
10:53:14 C:\Users\dotnet-bot\.nuget\packages\Microsoft.Net.Compilers\1.2.0-beta-20151211-01\tools\Microsoft.CSharp.Core.targets(67,5): error : System.NullReferenceException: Object reference not set to an instance of an object. [d:\j\workspace\roslyn-internal_prtest_win_dbg_unit32\Open\src\Features\Core\Portable\Features.csproj]

http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_dbg_unit32/404/consoleFull#56248540979494335-f7bd-47d0-8771-8661e00c2db2

**Comment by heejaechang** [comment]
10:53:15 C:\Users\dotnet-bot\.nuget\packages\Microsoft.Net.Compilers\1.2.0-beta-20151211-01\tools\Microsoft.CSharp.Core.targets(67,5): error : at Microsoft.CodeAnalysis.BuildTasks.ManagedCompiler.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [d:\j\workspace\roslyn-internal_prtest_win_dbg_unit32\Open\src\Features\Core\Portable\Features.csproj]
10:53:16   CSharpCodeAnalysis -> d:\j\workspace\roslyn-

**Comment by davkean** [comment]
We hit this again, @jaredpar can you get someone to have a look at this?

**Comment by davkean** [comment]
And again: http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_vsi_p2/89/consoleFull#-132868381679494335-f7bd-47d0-8771-8661e00c2db2

**Comment by davkean** [comment]
And again here: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p0/111/consoleFull#59593570779494335-f7bd-47d0-8771-8661e00c2db2

**Comment by TyOverby** [comment]
The following projects are failing:

* [404](http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_dbg_unit32/404/consoleFull#56248540979494335-f7bd-47d0-8771-8661e00c2db2)
    * Features 
    * Features
* [89](http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_vsi_p2/89/consoleFull#-132868381679494335-f7bd-47d0-8771-8661e00c2db2)
    * BasicWorkspace
    * BasicWorkspace
* [111](http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p0/111/consoleFull#59593570779494335-f7bd-47d0-8771-8661e00c2db2)
    * CodeAnalysisTest
    * CodeAnalysisTest

**Comment by davkean** [comment]
We suspect that the toolset update introduced this: https://github.com/dotnet/roslyn/pull/7444.

**Comment by TyOverby** [comment]
I am currently attempting to reproduce the issue with PDBs present.  This way, hopefully we can get line-number info as well as (maybe) a call stack.

**Comment by davkean** [comment]
How did we go with this?

**Comment by TyOverby** [comment]
It hasn't failed in the two days since I've tried to repro...

**Comment by davkean** [comment]
We hit this again: https://github.com/dotnet/roslyn/issues/7470

**Comment by amcasey** [comment]
http://dotnet-ci.cloudapp.net/view/roslyn/job/roslyn_prtest_win_dbg_unit64/2549/
http://dotnet-ci.cloudapp.net/view/roslyn/job/roslyn_prtest_win_dbg_unit64/2550/
http://dotnet-ci.cloudapp.net/view/roslyn/job/roslyn_prtest_win_dbg_unit32/2581/

**Comment by davkean** [comment]
Only the middle one, http://dotnet-ci.cloudapp.net/view/roslyn/job/roslyn_prtest_win_dbg_unit64/2550/, looks related.

**Comment by agocke** [comment]
I think I see the problem: https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/MSBuildTask/Shared/ManagedCompiler.cs#L389

NRE if responseTask is null. 

https://github.com/dotnet/roslyn/blob/master/src/Compilers/Shared/DesktopBuildClient.cs#L160

Looks like that should be `return Task.FromResult<BuildResponse>(null)`

**Comment by agocke** [comment]
Making a PR now.

**Comment by davkean** [comment]
Damnit, nice one. We've been trying find the cause for ages. We couldn't get a consistent repro.

**Comment by agocke** [comment]
Jared actually fixed a case in https://github.com/dotnet/roslyn/commit/e0d04ad7b889cca23571b8fa73dfdc4b47284a3f but just missed this one.

**Comment by amcasey** [comment]
Should we have an analyzer that detects constant `null` returns from non-async task-returning methods?

**Comment by agocke** [comment]
@amcasey I could see a good reason for doing that, rather than boxing a `null` in a task. I just happened to choose the "no-null" approach.

**Comment by TyOverby** [comment]
@agocke What is your example scenario?  I've always thought of Task as being a prime example of "this is a reference type, but seriously shouldn't ever be null".

**Comment by agocke** [comment]
@TyOverby Someone with a task-returning method which is often going to be "empty" and they don't want to incur an extra allocation. In theory the Task.FromResult(..) could be cached, but I'm not willing to say that's uniformly better.

**Comment by jaredpar** [comment]
@agocke good catch.  

How were you able to debug this?  Or did you just find this via code inspection?

**Comment by agocke** [comment]
@jaredpar Code inspection
