### ISSUE TITLE
Visual Studio did not auto fill complete after typing Property in VB.net

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#74701]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-did-not-auto-fill-complete/10699465)._

---
[severity:It bothers me. A fix would be nice]
when typing:
 `Public Property` 

Visual studio VB.Net did not auto fill code block

```
  Get

End Get

Set(value)

End Set
End Property
```

---
#### Feedback Bot on 7/9/2024, 08:35 PM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 7/10/2024, 01:41 AM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 7/10/2024, 01:59 AM: 

(private comment, text removed)
#### Hoang Le Minh on 7/10/2024, 02:14 PM: 

(private comment, text removed)
#### Feedback Bot on 7/11/2024, 00:37 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
I'm guessing this is By Design, since VB allows for single-line auto properties. As soon as the `Get` keyword is added on the line after `Property`, the IDE expands the property to a full property.

**Comment by CyrusNajmabadi** [comment]
Yes. This is by design

**Comment by drwho100** [comment]
No. This can easily fix by Visual Studio IDE Developer Team.

**Comment by sharwell** [comment]
Hi @drwho100,

Based on our evaluation of the issue, it is not possible for the behavior in this situation to be changed as suggested, since the change would make it much more difficult for users to define single-line auto-properties, which is a recommended syntax.

If you have a suggestion for an alternate solution, please let us know and we can evaluate it to see if it resolves the concerns.

**Comment by drwho100** [comment]
> Hi @drwho100,
> 
> Based on our evaluation of the issue, it is not possible for the behavior in this situation to be changed as suggested, since the change would make it much more difficult for users to define single-line auto-properties, which is a recommended syntax.
> 
> If you have a suggestion for an alternate solution, please let us know and we can evaluate it to see if it resolves the concerns.

Users could not complete Property Syntax. Because they are already remember Property keyword and they forgot GET .  What the point they care single line or multi line because they could not finish it.
