### ISSUE TITLE
Lightbulb Preview: InvalidOperationException: Unsupported extension '.tmp' and LSP language id 'CSharp'

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#74723]
When you show a lightbulb to remove unused usings, VS has a first-chance exception:

```
System.InvalidOperationException. Unsupported extension '.tmp' and LSP language id 'CSharp'
	Microsoft.CodeAnalysis.LanguageServer.Protocol	LanguageInfoProvider.GetLanguageInformation
	Microsoft.CodeAnalysis.LanguageServer.Protocol	LspWorkspaceManager.GetLanguageForUri
	Microsoft.CodeAnalysis.LanguageServer.Protocol	RoslynRequestExecutionQueue.GetLanguageForRequest
	Microsoft.CodeAnalysis.LanguageServer.Protocol	RequestExecutionQueue`1.CreateQueueItem
	Microsoft.CodeAnalysis.LanguageServer.Protocol	RequestExecutionQueue`1.ExecuteAsync
	Microsoft.CodeAnalysis.LanguageServer.Protocol	AbstractLanguageServer`1.DelegatingEntryPoint.NotificationEntryPointAsync
```

The exception comes from here:
https://github.com/dotnet/roslyn/blob/9c782455cc2f1083538f871c429c7d27ff88b723/src/LanguageServer/Protocol/LanguageInfoProvider.cs#L54-L64

This is because of an unfortunately confluence of two separate defects:
1. VS LanguageServerClient is sending Language ID as `CSharp` (note the case) from here: 
![image](https://github.com/user-attachments/assets/214eb3b1-dc64-463b-ab22-1005d30935ea)
2. LightBulb preview generates a TextDocument using Path.GetTempFileName() which has the .tmp extension and not .cs extension:
https://github.com/dotnet/roslyn/blob/6696095f5aa51290707b5d8518b861ee0bab7884/src/EditorFeatures/Core/Preview/AbstractPreviewFactoryService.cs#L658

If either the temp document path has `.cs` at the end, or we send `csharp` as the language ID (as required by the case-sensitive protocol), the issue will be fixed. My recommendation is to fix both.

Thanks @mgoertz-msft for helping investigate this.

**Comment by KirillOsenkov** [comment]
FYI @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
@dibarbet this helps explain which feature was causing this.

**Comment by dibarbet** [comment]
Aha - thanks.  Was trying to track down where these files were coming from.

Should be fixed by https://devdiv.visualstudio.com/DevDiv/_git/VSLanguageServerClient/pullrequest/569312
