### ISSUE TITLE
API: `Conversion.IsSpan`

### ISSUE THREAD

**Issue by jjonescz** [dotnet/roslyn#74738]
## Background and Motivation

The [first-class Span types](https://github.com/dotnet/roslyn/issues/73445) feature is adding new span conversions. For consistency with other conversions, it would be good to have the API proposed below.

## Proposed API

```diff
 namespace Microsoft.CodeAnalysis.CSharp;
 public readonly struct Conversion
 {
+    public bool IsSpan { get; }
 }
```

## Usage Examples

```cs
var comp = new CSharpCompilation(...);
var tree = comp.SyntaxTrees.Single();
var model = comp.GetSemanticModel(tree);
var expr = tree.GetRoot().DescendantNodes()...;
var conversion = model.GetConversion(expr);
Assert.True(conversion.IsSpan); // used here
```

## Alternative Designs

- Leave the API internal.
- Provide details about which span conversion it is (array to Span/ReadOnlySpan, Span to ReadOnlySpan, ReadOnlySpan to ReadOnlySpan, string to ReadOnlySpan).
- Provide details about the methods that will be used in codegen.

## Risks

- We might remove the feature and then the API will be useless?

**Comment by 333fred** [comment]
### API Review

**Approved**
