### ISSUE TITLE
Support attributes in SymbolDisplayParameterOptions

### ISSUE THREAD

**Issue by grosch-intl** [dotnet/roslyn#74742]
I've got a code generator that automatically creates the interface for a given class by putting all public items into it.  Using the format, below, it mostly works.  One piece I've noticed I can't do (AFAIK) is getting attributes.

If I have a method like so:

```csharp
public async Task DoSomething([NotNullIfNotNull(nameof(other))] int? one, int? other) ...
```

then I end up with this in the generated code:

```csharp
global::System.Threading.Tasks.Task DoSomething(int? one, int? other)
```

how do I get the `NotNullIfNotNull` attribute?  This is my formatter:

```csharp
private static readonly SymbolDisplayFormat _displayFormat = new SymbolDisplayFormat(
    typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
    propertyStyle: SymbolDisplayPropertyStyle.ShowReadWriteDescriptor)
    .WithGenericsOptions(SymbolDisplayGenericsOptions.IncludeTypeParameters | SymbolDisplayGenericsOptions.IncludeTypeConstraints)
    .WithMemberOptions(SymbolDisplayMemberOptions.IncludeType | SymbolDisplayMemberOptions.IncludeParameters)
    .WithParameterOptions(SymbolDisplayParameterOptions.IncludeType | SymbolDisplayParameterOptions.IncludeName | SymbolDisplayParameterOptions.IncludeDefaultValue | SymbolDisplayParameterOptions.IncludeModifiers)
    .WithMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.UseSpecialTypes | SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier | SymbolDisplayMiscellaneousOptions.AllowDefaultLiteral)
    .WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Included);
```

As a side question, any reason there doesn't seem to be `WithTypeQualificationStyle` and `WithPropertyStyle` methods like the others have?

**Comment by CyrusNajmabadi** [comment]
> how do I get the NotNullIfNotNull attribute?

You can get it off of the IParameterSymbol.Attributes.

**Comment by CyrusNajmabadi** [comment]
> Using the format, below, it mostly works

Note, this is explicitly *not* supported, and is a non-goal for ToDisplayString.  ToDisplayString is for display purposes only, not for code-generation.  We have carved out a subset of cases that are supported, but they are only doing .ToDisplayString on an ITypeSymbol.  For all other code generation needs, you will have to generate the code explicitly yourself.  There may be libraries that help with this (but i'm unfamiliar with them).

**Comment by grosch-intl** [comment]
@CyrusNajmabadi Thanks for the information.
