### ISSUE TITLE
Go To Definition stops working

### ISSUE THREAD

**Issue by Peter-Juhasz** [dotnet/roslyn#74756]
**Version Used**: 17.12.0 P1

**Steps to Reproduce**:
Unfortunately, can't consistently reproduce it, but it happens so frequently it makes work difficult.

https://github.com/user-attachments/assets/318adfa2-4c56-4b95-bfaf-cf593a5b46a4

**Diagnostic Id**:
N/A

**Expected Behavior**:
Works every time.

**Actual Behavior**:
Nothing happens. Neither to F12 or manually selecting "Go To Definition" from the context menu.

**Comment by Peter-Juhasz** [comment]
While `Go To Definition` is broken, at the same time `Go To Implementation` and `Peak Definition` works.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/75001
