### ISSUE TITLE
Duplicate compilation events for partial methods

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#7477]
Partial methods in C# currently result in duplicate compilation events.

**Comment by gafter** [comment]
The same is true in VB.

**Comment by gafter** [comment]
@mavasani Is this issue adequately worked around for Update 2?

**Comment by mavasani** [comment]
Not really, we will make both callbacks as they are different symbols. We can put a workaround in the driver if fixing complier issue is non trivial.

**Comment by jaredpar** [comment]
Didn't we merge the PR that fixed this already?
