### ISSUE TITLE
Advanced analysis options are unreliable, confusing and poorly documented

### ISSUE THREAD

**Issue by lorcanmooney** [dotnet/roslyn#74788]
**Version Used**: 
17.11.0

![analysis](https://github.com/user-attachments/assets/c42c5cd1-f193-4528-9c53-d0b134b3dc71)

**Issues**:

* `Entire solution` behaves like `Open documents` **_unless_** the solution was loaded with **no** open document tabs (in which case it _seems_ to work correctly).

* `Open documents` seems to work fine, **_unless_** you've just opened a solution with already-open document tabs; if so the error list will be incomplete, only showing diagnostics for _visible_ documents. The other tabs seem to be in some sort of deferred-load state, and diagnostics will only be listed once you active them.

* `Current document` only ever seems to work like `Open documents`. I would have expected the error list to be pruned as I switch between tabs (but I've never used this option, so maybe my expectations are wrong).

* The [documentation](https://learn.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-csharp-advanced?view=vs-2022#analysis) is confusing. It has one table trying to describe two different behaviours, or maybe it's just outdated and referencing an older release.

**Comment by CyrusNajmabadi** [comment]
Moving to editor @olegtk .  Seems to be an issue with editor/platform lying about what documents are open.  The tabs are there.  but the RDT doesn't tell us about these documents actually being opened.  so we do not report diagnostics on them as editor considers them closed.
