### ISSUE TITLE
Allow multi-line interpolated strings in C#.

### ISSUE THREAD

**Issue by brettfo** [dotnet/roslyn#748]
Multi-line strings (default in VB and available as raw strings in C#) make it very easy to visualize the final form of a string, but it seems that a developer will often need to visualize a multi-line string with additional values inserted.  This can be easily accomplished in VB since all strings are multi-line, but in C# you are restricted to either multi-line (raw) or single line interpolated.

E.g., this is nice and easy in VB:

    Dim message = $"
        {victim.Title} {victim.Name},
    Your PayPal account has bene hacked!  Please click this link to confirm your password:
        {phishingUrl}
    Thank you,
        {fakeCustomerServiceName}"

But in C#:

    var message = string.Format(@"
        {0} {1},
    Your PayPal account has bene hacked!  Please click this link to confirm your password:
        {2}
    Thank you,
        {3}", victim.Title, victim.Name, phishingUrl, fakeCustomerServiceName);

or this, which isn't much better:

    var message =
    $"{victim.Title} {victim.Name}\n" +
    "Your PayPal account has been hacked!  Please click this link to confirm your password:\n" +
        phishingUrl + "\n" +
    "Thank you,\n" +
    $"    {fakeCustomerServiceName";

**Comment by sharwell** [comment]
Didn't these get added in CTP 5?

https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/04882dc916ad75288dda6ede44e406d71cfc6712/StyleCop.Analyzers/StyleCop.Analyzers.Test/MaintainabilityRules/SA1400UnitTests.cs#L742-L744

**Comment by brettfo** [comment]
Good call!  I tried @$"" but not $@"".

Closing the issue.
