### ISSUE TITLE
Reference highlighting doesn't work from primary constructor base call constructor call

### ISSUE THREAD

**Issue by Peter-Juhasz** [dotnet/roslyn#74804]
**Version Used**: 17.12.0 P1

**Steps to Reproduce**:

https://github.com/user-attachments/assets/759db2e2-f427-4d26-a0d4-a5a3e2da9f23

```cs
public class A();

public class B() : A$$();
```

Similar and may be related to #74803

**Comment by Rekkonnect** [comment]
It seems that in the example code, `INamedTypeSymbol A` is returned instead of its constructor, which is why the reference is not found. So there needs to be a breaking change where `GetSymbolInfo` returns the constructor `A()` instead of the type itself.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/76097.
