### ISSUE TITLE
Anonymous-Params-delegate is generated incorrectly with AllowRefStructFlag

### ISSUE THREAD

**Issue by bernd5** [dotnet/roslyn#74823]
**Version Used**: 

**Steps to Reproduce**:

Compile the following code:

```csharp
var counter = Counter;
counter.Invoke();

void Counter(params int[] arr)
{
}
```

**Expected Behavior**:
The compiler should generate an unspeakable delegate type like:

```csharp
[CompilerGenerated]
internal delegate void <>f__AnonymousDelegate0<T1>(params T1[] arg);
```

**Actual Behavior**:

It generates code like:

```csharp
[CompilerGenerated]
internal delegate void <>f__AnonymousDelegate0<T1>(params T1[] arg) where T1: allows ref struct;
```

If you look in *dotPeek* for example and have a look at the TypeParameter flags you can see 0x0020 is set.

![grafik](https://github.com/user-attachments/assets/34dd2b69-aa97-4e25-81e0-11932eadbbbf)

The value is defined [here](https://github.com/dotnet/roslyn/blob/ed51fbe4ca48d4abc615439a9a4cb25c48ec1008/src/Compilers/Core/Portable/MetadataReader/MetadataHelpers.cs#L26): it means `allows ref struct`

**Comment by jjonescz** [comment]
Why would that be incorrect? Is anything broken by the compiler generating the delegate with `allows ref struct`?

Btw, the behavior follows [the feature proposal](https://github.com/dotnet/csharplang/blob/9996380f5ad191b0bddaf81c440489f6d3ea09aa/proposals/ref-struct-interfaces.md#delegate-type-for-the-anonymous-function-or-method-group):

> If target runtime supports `allows ref struct` constraints, generic anonymous delegate types will include `allows ref struct` constraint for their type parameters. This will enable substitution of those type parameters with ref struct types and other type parameters with `allows ref struct` constraint.

**Comment by bernd5** [comment]
It is correct without usage as array element type.

E.g.:
```csharp
internal delegate void <>f__AnonymousDelegate0<T1>(T1 arg) where T1: allows ref struct;
```
would be very well.

But 
```csharp
internal delegate void <>f__AnonymousDelegate0<T1>(params T1[] arg) where T1 : allows ref struct;
```

violates the following part of the proposal:

> A type parameter bound by allows ref struct has all of the behaviors of a ref struct type: <br/>
    Instances of it cannot be boxed
    Instances participate in lifetime rules like a normal ref struct
    The type parameter cannot be used in static fields, **elements of an array**, etc ...
    Instances can be marked with scoped

Any usage of the delegate with an ref-like type as typeargument would be invalid. Currently the runtime simply does not care (and roslyn enforces that such delegate types can't be declared by a user).

E.g.
```csharp
internal delegate void SomeDelegate0<T1>(params T1[] arg) where T1 : allows ref struct;
```
emits the following diagnostic: [CS0611](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/array-declaration-errors?f1url=%3FappId%3Droslyn%26k%3Dk(CS0611)#invalid-element-type): Array elements cannot be of type T1

**Comment by jaredpar** [comment]
Think that part of the spec needs to be limited to using `allows ref struct` where it would be legal.
