### ISSUE TITLE
IncrementalGenerator stopped working in VS 17.11

### ISSUE THREAD

**Issue by nvborisenko** [dotnet/roslyn#74840]
**Version Used**: Visual Studio 17.11.1

**Steps to Reproduce**:

1. Create simple incremental generator (it generates source code based on `*.txt` files as input)

Simple incremental generator (took from docs):

```csharp
    [Generator]
    public class Generator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext initContext)
        {
            // define the execution pipeline here via a series of transformations:

            // find all additional files that end with .txt
            IncrementalValuesProvider<AdditionalText> textFiles = initContext.AdditionalTextsProvider.Where(file => file.Path.EndsWith(".txt"));

            // read their contents and save their name
            IncrementalValuesProvider<(string name, string content)> namesAndContents = textFiles.Select((text, cancellationToken) => (name: Path.GetFileNameWithoutExtension(text.Path), content: text.GetText(cancellationToken).ToString()));

            // generate a class that contains their values as const strings
            initContext.RegisterSourceOutput(namesAndContents, (spc, nameAndContent) =>
            {
                File.AppendAllText("E:\\Generator.log", "I am called\n");

                spc.AddSource($"ConstStrings.{nameAndContent.name}", $@"
    public static partial class ConstStrings
    {{
        public const string {nameAndContent.name} = ""{nameAndContent.content}"";
    }}");
            });
        }
    }
```

**Expected Behavior**:

Each time when I add or change any `*.txt` file I should see new file at `E:\\Generator.log` path.

**Actual Behavior**:
Incremental generator is invoked only once at build stage. But seems it is not invoked when I add new `*.txt` file or edit its content.

**NOTE:**
It worked well in VS 17.10, seems stopped working in 17.11

**Comment by CyrusNajmabadi** [comment]
This is controlled by:

![Image](https://github.com/user-attachments/assets/2c7467d5-9259-4681-8e88-7211e7c5838b)

We also fixed this in 17.12: https://github.com/dotnet/roslyn/pull/74542

Primary issue was that we weren't tracking saves to non-Roslyn files (like your text file).  So even saving them wasn't causing generators to rerun.
