### ISSUE TITLE
Deconstruct works inconsistently in patterns and in deconstruction into tuple

### ISSUE THREAD

**Issue by B1Z0N** [dotnet/roslyn#74852]
**Version Used**: Main branch (11 June 2024)

**Steps to Reproduce**: [Sharplab](https://sharplab.io/#v2:EYLgtghglgdgNAFxANwKYCcoDMCecAmIA1AD4ACATAIwCwAUPbAgPwAEAVqwLysCsA3PXoB6YawDqACxyt8Ae1QBnVgklRlWaABtmjLKwAUndYYToArqjh8AlDdYBvAL5C6oidNkLlqkwHc5dABrXTpkCHRDSQhFADUILUtrcMTUex52QQZssioANlZKVgA5cy0tCGAtVABRAA8EVBhFKDlm+gd6Vm7CgGZC/MKAFlYAEVQAYzbFM3MJhAAeABUAPgNfZSW2GDKKqqtWLp7jk9Oz8+O5cwRWYDk5LVZouISkw7oLz6/zq5ul1hSlnsR1OfkkGFQrH+IFYMws8xBjkRx2e8VS3FYO3KlWqADoABIxNGWLLnQGQnhYvZ4gDiqAQxNQAHl0ONNGUEAYbKSei46HygA=)

**Expected Behavior**: It works just as in the second case with deconstruction into tuple using deconstruct on `int?`.

**Actual Behavior**: It outputs compilation error that there's no deconstruct for `int`.

Copied (with slight edit) from sharplab:
```
using System;

int? j = 5;

// Why does this fail?
if (j is (true, 5)) {}

// Why does this work?
(bool hasValue, int value) = j;


static class NullableExtensions
{
    public static void Deconstruct<T>(this T? nullable, 
                                      out bool hasValue, 
                                      out T value) 
        where T : struct
    {
        hasValue = nullable.HasValue;
        value = nullable.GetValueOrDefault();
    }
}
```

**Comment by jcouv** [comment]
This falls out of current design.

The error states:
```
// (6,10): error CS1061: 'int' does not contain a definition for 'Deconstruct' and no accessible extension method 'Deconstruct' accepting a first argument of type 'int' could be found (are you missing a using directive or an assembly reference?)
// if (j is (true, 5)) {}
```

The [spec](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-8.0/patterns.md#positional-pattern) says:
"A positional pattern checks that the input value is not null, invokes an appropriate Deconstruct method, and performs further pattern matching on the resulting values."

So what's happening is that the positional pattern first null-checks the `int?` and then tries to deconstruct the resulting `int`.
For the `j is (true, 5)` check to work, you'd need a `Deconstruct` extension method on `int`.
