### ISSUE TITLE
Error reporting stops working

### ISSUE THREAD

**Issue by Peter-Juhasz** [dotnet/roslyn#74873]
**Version Used**: 17.12.0 P1

**Steps to Reproduce**:

Can't consistently reproduce it, it just happens after some time:

https://github.com/user-attachments/assets/63f4346f-9c44-4af9-adbc-7516f7111690

All files affected even after reopening.

Error List doesn't display any errors either.

**Diagnostic Id**:
N/A

**Expected Behavior**:
Squiggles are shown in the editor, document map on scrollbar shows errors, Error List shows errors.

**Actual Behavior**:
No errors are shown.

**Comment by CyrusNajmabadi** [comment]
Likely fixed with #74724 which was breaking the language server.
