### ISSUE TITLE
Proposal: Private Parameters

### ISSUE THREAD

**Issue by AustinBryan** [dotnet/roslyn#7488]
I saw someone asking this on StackOverflow. The basic syntax is this:

```c#
public void Method(string str, private int x =  0)
{
    // do something
}
```

For anyone calling the function publicly, from outside the class, they get this function:
`public void Method(string str);` and the parameter `x` is completely abstracted from them.

However, anyone inside the class calling `Method()` sees `Method(string str, int x);`

This method will actually compile as this:
```C#
public void Method(string str)
{
    Method(str, 0)
}
private void method(string str, int x)
{
   // do something
}
```

The other accessors, `public`, `protected`, and `internal` can also be used and work in the same fashion

**Comment by dsaf** [comment]
https://github.com/dotnet/roslyn/issues/5966

https://help.github.com/articles/searching-issues
