### ISSUE TITLE
[Feature] Collapse multiple leading #pragma lines

### ISSUE THREAD

**Issue by lonix1** [dotnet/roslyn#74897]
Consider this C# file:
```cs
#pragma warning disable 123
#pragma warning disable 456
#pragma warning disable 789
#pragma warning disable abc
using System.Collections.ObjectModel;
using System.Net.Mimel
using Microsoft.AspNetCore.Mvc;

namespace Foo;

public class Bar {
```

If that file is collapsed, the `using` lines will be collapsed into a single line, but the `#pragma` lines will not.

In a non-trivial codebase there are many files which deviate from defaults and need top-level pragmas. It would be cleaner and more readable if those would also be collapsible to single lines.

After collapsing:
```cs
> #pragma warning disable 123
> using System.Collections.ObjectModel;

  namespace Foo;

  public class Bar {
```

**Comment by migig** [comment]
@dibarbet Is the reason is it's too complicated?

By the way I'm using VSCode not VS.
