### ISSUE TITLE
Collection expression spread optimization using `List<T>.AddRange(IEnumerable<T>)` skipped for `ICollection<U>` when `T` and `U` are distinct types at compile-time only

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#74894]
The collection expression spread optimization for `[.. x]` where the target type is `List<T>` is skipped unnecessarily when:
- `x` has a value type enumerator, and
- `x` implements `ICollection<U>`, and
- `T` and `U` are distinct types at compile-time but not at runtime (for instance, `object` vs. `object?`, or `(int X, int Y)` vs. `(int, int)`).

See https://github.com/dotnet/roslyn/pull/74630
See https://github.com/dotnet/roslyn/pull/74769#issuecomment-2308489340

**Comment by cston** [comment]
Lowering is currently using `TypeSymbolExtensions.ImplementsInterface()` to check for `ICollection<T>` (see [LocalRewriter_CollectionExpression.cs](https://github.com/dotnet/roslyn/blob/main/src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs#L1079)), but we should probably use a conversion method such as `ConversionsBase.ClassifyBuiltInConversion()` instead.

**Comment by DoctorKrolic** [comment]
`ImplementInterface` currently [uses `TypeCompareKind.ConsiderEverything2`](https://github.com/dotnet/roslyn/blob/14f5b27c7206557c9054ba6ce59cb9c819d5b473/src/Compilers/CSharp/Portable/Symbols/TypeSymbolExtensions.cs#L21), which is marked as ["temporary" an should be removed](https://github.com/dotnet/roslyn/blob/14f5b27c7206557c9054ba6ce59cb9c819d5b473/src/Compilers/Core/Portable/Symbols/TypeCompareKind.cs#L17-L18). Given that current behavior of `ImplementInterface` may lead to unexpected results like this issue and is confuisng enough, that it passed a compiler code review, maybe we should revise its implementation and use other compare kind (like `CLRSignatureCompareOptions`) instead? Currently this helper is only used in [1 other place](https://github.com/dotnet/roslyn/blob/14f5b27c7206557c9054ba6ce59cb9c819d5b473/src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol_ImplementationChecks.cs#L367), so it should be simple to track all behavior changes if we revise the helper. Also note, that in both places `discardedUseSiteInfo` is passed as a second argument, so if we decide to touch the method, maybe we should also get rid of that parameter entirely?

**Comment by cston** [comment]
As mentioned in https://github.com/dotnet/roslyn/pull/74769#discussion_r1730100876, I don't think we should use `ImplementsInterface()` here.

The check we want to perform in this case is essentially `expr is ICollection<T>` which should be implemented by `ConversionsBase.ClassifyBuiltInConversion()` or a similar conversion method. It's not clear that `ImplementsInterface()` matches the expected conversion behavior.
