### ISSUE TITLE
`dotnet_analyzer_diagnostic.category-Naming.severity` does not apply to naming rule violations

### ISSUE THREAD

**Issue by just-ero** [dotnet/roslyn#74901]
### Version Used

Compiler: 4.12.0-2.24416.3 (ee863ede)  
.NET: 9.0.100-preview.7.24407.12  
Visual Studio Code: 1.92.2, `fee1edb8d6d72a0ddff41e5f71a671c23ed924b9`, x64  
C# Extension: v2.44.19  
C# Dev Kit Extension: v1.10.10

### Steps to Reproduce

1. Create or open a C# project in Visual Studio Code.
2. Create or edit an `.editorconfig` file.
3. Add any naming rule.
4. Add any code violating said naming rule with a severity above `silent`.
5. Add the following line to the `.editorconfig` file:
   ```
   dotnet_analyzer_diagnostic.category-Naming.severity = silent
   ```

### Expected Behavior

The naming rule violations are no longer reported.

### Actual Behavior

They are.

**Comment by sharwell** [comment]
Naming rules have severity `silent` by default. Can you check to see if a severity was specified on the individual rules, or a severity was set for IDE1006 directly?

**Comment by just-ero** [comment]
Yes, the rules themselves have the `warning` severity.

I have noticed that `dotnet_analyzer_diagnostic.category-Style.severity = none` is able to suppress all *property* rules (like `dotnet_style_require_accessibility_modifiers`). However, rules specified via `dotnet_diagnostic.IDE0040.severity = warning` override that suppression.

**Comment by sharwell** [comment]
`dotnet_analyzer_diagnostic.category-*.severity` and `dotnet_diagnostic.*.severity` are in the same "category" of configuration, and thus have a well-defined precedence order. The rules like `dotnet_style_require_accessibility_modifiers` are separate, and their priority depends on the specific SDK version in use along with some project properties. Once .NET 9 SDK (non-preview) is released, this form will have lower priority unless `EnableCodeStyleSeverity` is set to true in the project file. Some preview builds of the .NET 9 SDK, as well as some build at the end of .NET 8 SDK, will place this form at higher priority as long as `AnalysisLevel` is set to 9 or higher in the project file.

**Comment by just-ero** [comment]
This is expected behavior then? If so, feel free to close.
