### ISSUE TITLE
DebuggerStepThrough is ignored

### ISSUE THREAD

**Issue by 0x084E** [dotnet/roslyn#7492]
When you enable 'Break When Thrown' for exceptions in older Version of Visual Studio I could suppress thrown  and catched exceptions in methods with decorating the method with a DebuggerStepThrough attribute. This doesn't work anymore, the debugger breaks at the point of the caller.

See also http://stackoverflow.com/questions/31741071/in-visual-studio-2015-debuggerstepthrough-doesnt-pass-over-exceptions-anymore

**Comment by leppie** [comment]
How would you debug other people's code then? Say when you only have the .NET assembly? I prefer it breaks when told to.

**Comment by 0x084E** [comment]
Sure it should break when told to, but it should also not break when told to, That's what the Debugger* attributes are good for.

**Comment by leppie** [comment]
I thought they were related to stepping and not breakpoints.

**Comment by 0x084E** [comment]
This issue is not about breakpoints, it's about breaking on  thrown exceptions, but breakpoints are also ignored in DebuggerStepThrough methods  all along.

**Comment by KevinH-MS** [comment]
Hi @0x084E, this is not related to Roslyn.

I can log a bug in the internal VS bug database, but the best option for you to receive updates would be to log this using http://connect.visualstudio.com.

Let me know what you prefer--thanks

**Comment by 0x084E** [comment]
Hi @KevinH-MS, since I don't have an account for connect.visualstudio.com I would appreciate if you could open it for me. Thanks!

**Comment by KevinH-MS** [comment]
Opened internal bug for debugger team...  I'll post back when I hear something.

Closing this bug for now...

**Comment by KevinH-MS** [comment]
@0x084E the debugger team has provided some detail as to the reason for this change in behavior at:  https://blogs.msdn.microsoft.com/visualstudioalm/2016/02/12/using-the-debuggernonusercode-attribute-in-visual-studio-2015/

It appears that you may be able achieve the old behavior by either:

1. Turning off "Just My Code" (not sure if this will work, but reading between the lines, it might)
1. Setting the registry key detailed in the blog post (HKCU\Software\Microsoft\VisualStudio\14.0_Config\Debugger\Engine\AlwaysEnableExceptionCallbacksOutsideMyCode = 1)

Hope that helps!

**Comment by KevinH-MS** [comment]
Woops, one additional note--the registry key will only work if you have Visual Studio 2015 Update 2 installed.

**Comment by 0x084E** [comment]
@KevinH-MS Thanks for your response (and thanks to the debugger team for writing the blog entry). I will wait for the final Update 2 and give it a try.

**Comment by korhun** [comment]
1. Turning off "Just My Code" 
2. Setting the registry key (HKCU\Software\Microsoft\VisualStudio\14.0_Config\Debugger\Engine\AlwaysEnableExceptionCallbacksOutsideMyCode = 1)

does not work on Visual Studio 2015 Update 3
