### ISSUE TITLE
Error message change for type not found is not correct

### ISSUE THREAD

**Issue by leppie** [dotnet/roslyn#7493]
```
using A = List<Bar>;
```
Reports in Roslyn:
```
Error CS0246: The type or namespace name 'List<Bar>' could not be found (are you missing a using directive or an assembly reference?)
```
In legacy compiler:
```
Error CS0246: The type or namespace name 'List' could not be found (are you missing a using directive or an assembly reference?)
```
To me, this is possibly confusing. In this case it is `List<T>` that could not be found. Not `List<Bar>`. And especially when going into some silly variations, eg `List<"moo">`.

I can understand it was a possible enhancement, but it would be better to say `no generic type 'List' taking 1 argument`.

Unfortunately, the Git history does not go back far enough to say why this change was done. 

The point of interest is the `whereText` parameter in `Binder.NotFound(...)`. See: https://github.com/dotnet/roslyn/blob/master/src%2FCompilers%2FCSharp%2FPortable%2FBinder%2FBinder_Symbols.cs#L1742

Related: #7387

**Comment by AdamMaras** [comment]
I agree, this is kind of strange. It may not be completely obvious to everybody that, in your example, it's `List` that can't be found, not `Bar`. Perhaps we can split the difference between the two?

    The type or namespace name 'List' taking 1 generic argument could not be found (are you missing a using directive or an assembly reference?)

**Comment by YuvalItzchakov** [comment]
+1 for @AdamMaras  suggestion. LGTM.

**Comment by leppie** [comment]
@AdamMaras The `or namespace name` should be dropped from the error message else it stays nonsensical :)

**Comment by leppie** [comment]
It might even be a good idea to try separate that error message completely to have a proper distinction between namespaces and types.
