### ISSUE TITLE
Load Roslyn Analyzers from VS

### ISSUE THREAD

**Issue by arunchndr** [dotnet/roslyn#74941]
Refer to https://github.com/dotnet/sdk/issues/42087 and https://github.com/dotnet/roslyn/pull/74775 for context. 

The experience for roslyn analyzers is diff than the rest of the .NET SDK analyzers. But it should follow suit with the SDK analyzers.

Also, since this tightens up the load range for the analyzers, this should make it a low risk change to bring into 17.12. 

cc: @sharwell to help validate the analyzers functionality and @tmat to get the option and insertion config correct.

**Comment by CyrusNajmabadi** [comment]
@JoeRobich @sharwell what is remaining on this?  If nothing is remaining, please closeout.

**Comment by JoeRobich** [comment]
Sorry, yes this work is complete. The only future task would be to move the redirection logic from ProjectSystemProject to the analyzer assembly redirection API being added in https://github.com/dotnet/roslyn/pull/74820.
