### ISSUE TITLE
Renaming several times automatically exit

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#74945]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Renaming-several-times-automatically-exi/10733703)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:17.6.X]
I rename many variables in succession, but if I use Ctrl+R, Ctrl+R within a second of the previous rename, the tooltip when I type the new name closes quickly. I have to wait between each rename to not have this problem.

---
#### Feedback Bot on 8/29/2024, 01:32 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Cosifne** [comment]
Very likely to be a dup of https://github.com/dotnet/roslyn/issues/74347
And fixed in https://github.com/dotnet/roslyn/pull/74905
