### ISSUE TITLE
`TypeLoadException` when invoking functions accepting arguments of type `Span<T>` or `ReadOnlySpan<T>` in certain `dynamic` contexts

### ISSUE THREAD

**Issue by tuespetre** [dotnet/roslyn#74952]
# Introduction

Bear with me here. Before today, I had the following installed:

    Visual Studio Community 2022 17.8.2
    Visual Studio Build Tools 2022 17.8.2

    dotnet --version
    8.0.100

    Compiler version: '4.8.0-7.23572.1 (7b75981c)'. Language version: 12.0.

Today, I agreed to let Visual Studio update on close, and also updated the build tools. After updating, I ran my code and encountered a `TypeLoadException`. Then, after some consideration I decided to file this bug. But before filing this bug, I made sure I could reproduce it. Then I used the Visual Studio installer to roll back the updates so I could gather information about the previous version and confirm that my code worked with it. Then I proceeded to use the installer to update, but it updated to a newer version than it did the first time it updated, for some reason. Now, here is what I have:

    Visual Studio Community 2022 17.11.2
    Visual Studio Build Tools 2022 17.11.2

    dotnet --version
    8.0.400

    Compiler version: '4.11.0-3.24365.8 (9e9c7c1d)'. Language version: 12.0.

I did happen to take note of the `dotnet --version` after the first update, which was `8.0.304`. I also grabbed a version number from the installer's logs for the first update, which is ` 17.10.35201.131`. I do not have the compiler version number from that point in time, unfortunately.

Why did I just explain all of this? Because (part) of the bug disappeared after the second update. My code is no longer affected by this bug as of now, but in putting together a reproduction of the bug, I did uncover a similar bug that has been reproduced across all three versions of the environment used today.

# Code that only reproduces a bug for the intermediate version

```
var source = new dynamic[] { new { a = "a" } };

source.Select(x => @class.method(x.a)).First();

public static class @class
{
    public static dynamic method(ReadOnlySpan<char> span)
    {
        return new string(span);
    }
}
```

# Code that reproduces a bug for all tried versions

```
var source = new dynamic[] { new { a = "a" } };

source.Select(x => function(x.a)).First();

static dynamic function(ReadOnlySpan<char> span)
{
    return new string(span);
}
```

# The exception message and trace

```
Unhandled exception. System.TypeLoadException: GenericArguments[2], 'System.ReadOnlySpan`1[System.Char]', on 'System.Func`3[T1,T2,TResult]' violates the constraint of type parameter 'TResult'.
   at Program.<>c.<<Main>$>b__0_0(Object x)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Program.<Main>$(String[] args) in ...\path\to\Program.cs:line 3
```

Note that the exception message was identical for both cases, and the trace was virtually identical (perhaps different generated type names for closures.)

# Expected behavior

No `TypeLoadException` and it just works.

# Potential workaround

Cast the dynamic argument as a `string`; i.e., `function((string)x.a)`. This only works if the function accepts `ReadOnlySpan` and not `Span`.

**Comment by jaredpar** [comment]
This behavior is "By Design". The use of `ref struct` types in `dynamic` is very limited as reflection generally does not support them.

**Comment by tuespetre** [comment]
@jaredpar that is understandable, but is the introduction of runtime exceptions in previously working code with a new version of Roslyn also "by design"? If Roslyn tries to produce some kind of delegate like `System.Func`3[T1,T2,TResult]` where `TResult` is invalid (like `System.ReadOnlySpan<char>`) shouldn't it produce an error?

**Comment by jaredpar** [comment]
> hat is understandable, but is the introduction of runtime exceptions in previously working code with a new version of Roslyn also "by design"?

The entire intersection of the features is unsupported. That means behavior which did work could start breaking and code that didn't work could start working. In retrospect we likely should've put stronger guards in place here and said that having a signature which explicitly mixed `dynamic` and `ref struct` was an error.
