### ISSUE TITLE
Simplier Local New Variable Declaration [Feature Request]

### ISSUE THREAD

**Issue by Linchy** [dotnet/roslyn#7495]
Instead of having to write:

``` c#
var room = new Room(roomType, player);
```

Why not:

``` c#
new Room room(roomType, player);
```

~~or even:~~

~~new Room(roomType, player);~~

~~(and name is set to `Room`)~~

!

**Comment by alrz** [comment]
there is an old saying that goes what on earth are you talking about.

**Comment by stepanbenes** [comment]
Second example is just crazy, third example is already valid C# code...

**Comment by Linchy** [comment]
Heh 2nd example shows how the redundant `var` and `=` could be removed. Of course it wouldn't like nice for multiple declarations on one line (`var a, b, c ...`), but I don't think I've ever worked at a place where this wasn't frowned upon..

The third example just shows how you could extend it to remove the redundant 2nd `room`. Many variables are usually given the exact same name as their type, so I think it is a common case. I expect everyone will disagree with capitalising local variables though :) (The wake language does this for example: http://www.wakelang.com/#variables)

**Comment by alrz** [comment]
There is a programming language called "whitespace", it is extremely concise, for example,
```



```
I think it is a common case.

**Comment by HaloFour** [comment]
What would that do to the following perfectly legal C# code?

```cs
new Room(roomType, player);
var room = SomeFunction();
```

**Comment by Linchy** [comment]
Good point! I suppose that makes it a breaking change then so I will cross it out. Still I think the second point stands.

**Comment by gafter** [comment]
@Linchy 

"Why not?"

Our criteria for including features does not include whether or not we can think of a reason *not* to do it. Our default position is that we're not going to do any particular proposed feature unless there is a sufficiently good reason to do it.

Can you think of any reasons that we should consider doing this?

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
