### ISSUE TITLE
Moving away from 1.0.0.0rc1 doesn't work

### ISSUE THREAD

**Issue by philippe-lavoie** [dotnet/roslyn#7497]
I tried to upgrade my nuget package, however I'm getting so many errors that I"m tempted to give up. Is there a magic thing I need ?

I have a roslyn project that works perfectly well with 1.0RC1. However, moving to 1.0 or 1.1.1 means, I have to install VB otherwise the solution doesn't open (even if VB isn't used in the solution). Then it throws exceptions about invalid task from Microsoft.Bcl, when ignoring that, I'm getting type cast exception from string to char* everywhere, when ignoring that I'm getting a tried to close a task that's already close when I try to do

compilation = project.GetCompilationAsync().Result;

I think it's because it threw so many exceptions that it went to a faulted state so .Result doesn't work proplery.

I tried to use samples with nuget packages and that failed fast too (see my other issue). 

Any guidance on going from RC1 to proper package ?  Are there any packages to exclude ?

**Comment by gafter** [comment]
Can you please give us a zip file of all the relevant files to repro the issue?

**Comment by philippe-lavoie** [comment]
The issue was a corrupt SLN file. Too many merges with Git got it in a weird state.
