### ISSUE TITLE
`Use language keywords` does not work for `nint` and `nuint` when targeting `net4.8.1` using `LangVersion` 9.0 or higher

### ISSUE THREAD

**Issue by just-ero** [dotnet/roslyn#74973]
### Version Used

Compiler: 4.12.0-2.24416.3 (ee863ede)  
.NET: 9.0.100-preview.7.24407.12  
Visual Studio Code: 1.92.2, `fee1edb8d6d72a0ddff41e5f71a671c23ed924b9`, x64  
C# Extension: v2.44.19  
C# Dev Kit Extension: v1.10.10

### Steps to Reproduce

1. Create or open a C# project in Visual Studio Code.
   * Target `net4.8.1`.
   * Use `LangVersion` 9.0 or higher.
2. Create or edit an `.editorconfig` file.
3. Enforce `dotnet_style_predefined_type_for_locals_parameters_members`/`IDE0049`.
4. Add any local, parameter, or member with `System.IntPtr` or `System.UIntPtr` as its type.
   ```cs
   namespace Ns
   {
     class C
     {
       public System.IntPtr Prop { get; }
     }
   }
   ```
5. Observe the violation not being highlighted.

### Expected Behavior

Due to `nint` and `nuint` being supported from 9.0 upwards, I expect violations of the rule to be reported, and the fix applied when running `dotnet format`.

### Actual Behavior

It is not.

**Comment by huoyaoyuan** [comment]
It's by design. .NET Framework doesn't expose `RuntimeFeature.NumericIntPtr`, which affects the behavior of `IntPtr`. The analyzer explicitly detects this:

https://github.com/dotnet/roslyn/blob/3b7995d6cd6dc92c3b23bd3d028bfc8e89114420/src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpPreferFrameworkTypeDiagnosticAnalyzer.cs#L31-L35

**Comment by just-ero** [comment]
So `semanticModel.Compilation.SupportsRuntimeCapability(RuntimeCapability.NumericIntPtr)` must be returning `false`? Which is confusing to me personally, since using numeric `nint` and `nuint` clearly works fine in .NET Framework.

**Comment by huoyaoyuan** [comment]
> So `semanticModel.Compilation.SupportsRuntimeCapability(RuntimeCapability.NumericIntPtr)` must be returning `false`?

By spec, runtime features are indicated by existence of corresponding member in `System.Runtime.CompilerServices.RuntimeFeature`, which doesn't exist in .NET Framework at all. See the spec at https://github.com/dotnet/csharplang/blob/main/proposals/csharp-11.0/numeric-intptr.md :

> since using numeric `nint` and `nuint` clearly works fine in .NET Framework

They are working under the C# 9 behavior. Under C# 11 behavior, `IntPtr` and `nint` will be strict aliases.

**Comment by CyrusNajmabadi** [comment]
We can add an additional check if the version is >11, and offer in that case regardless of runtime feature support.

**Comment by CyrusNajmabadi** [comment]
we would take a targeted community pr here.
