### ISSUE TITLE
[Feature Request] `nameof(X)u8` : Generating UTF-8 byte sequences using `nameof()`

### ISSUE THREAD

**Issue by xin9le** [dotnet/roslyn#74979]
## Background and Motivation
UTF-8 literals were introduced in C# 11, which has been extremely beneficial for developers performing optimizations using UTF-8 byte sequences. However, at present, it is not possible to apply `u8` to `nameof()`. This proposal aims to simplify the generation of UTF-8 byte sequences in a manner that follows name changes. Additionally, it will bridge the asymmetry gap between the generation of regular strings and UTF-8 byte sequences.

```cs
// string
string t1 = "CSharp";
string t2 = nameof(Language.CSharp);

// UTF-8 string
ReadOnlySpan<byte> = "CSharp"u8;
ReadOnlySpan<byte> = nameof(Language.CSharp)u8;  // currently, doesn't support
```

## Proposed API
```cs
ReadOnlySpan<byte> text = nameof(X)u8;
```

## Usage Examples
``` cs
MyEnumExtensions
    .IsDefined<HttpStatusCode>(nameof(HttpStatusCode.OK)u8)
    .Should()
    .BeTrue();
```

## Alternative Designs
If `$"nameof(X)"u8` were to be implemented, it would enable equivalent functionality. However, this would not resolve the asymmetry issue mentioned earlier.

- https://github.com/dotnet/csharplang/issues/7072

## Risks
I guess it depends on being able to parse `nameof(X)u8`, but no further concerns come to mind.

**Comment by huoyaoyuan** [comment]
This is a C# language feature and should go to https://github.com/dotnet/csharplang/discussions. The `API request` category is for API provided by the compiler, to support analyzers and IDEs etc.

**Comment by xin9le** [comment]
@huoyaoyuan 
Thank you for your observation. I had the feeling that I might have posted in the wrong place, so I appreciate your guidance in directing me to the appropriate location.
