### ISSUE TITLE
Avoid dependency on `System.Index` for list patterns

### ISSUE THREAD

**Issue by Rekkonnect** [dotnet/roslyn#74983]
## Motivation

I'm targeting `netstandard2.0` and use C# 12 on a project. In .NET Standard 2.0 there is no `System.Index`, and we have to use a polyfill package to effectively introduce the type. Without this, we cannot use even the simplest list patterns.

## Example

Screenshot:
![image](https://github.com/user-attachments/assets/9a982d5f-1f5a-4c55-b73e-3470a873dd35)

Snippet:
```csharp
        public static bool TryGetSingle<TBase, TDerived>(this IReadOnlyList<TBase> list, out TDerived single)
            where TDerived : TBase
        {
            if (list is [TDerived singleDerived])
            {
                single = singleDerived;
                return true;
            }
            single = default;
            return false;
        }
```

Even if the pattern was `list is []`, we can still not use list patterns because index is required. This is unnecessarily restrictive.

## Proposal

Refactor the list pattern lowering into something that does not use `System.Index` as much as possible. I believe it's possible to also remove that dependency 100%, but even allowing simple patterns like this is more than nothing.

## Aftermath

Probably better performance, and probably lower binary size. DX improves for lower framework versions by having fewer runtime dependencies for new handy syntax.

**Comment by jaredpar** [comment]
>  In .NET Standard 2.0 there is no System.Index, and we have to use a polyfill package to effectively introduce the type. Without this, we cannot use even the simplest list patterns.

That is essentially "By Design". The newer language features are only supported on the target framework that they were shipped with. That means there is an expectation that types in those target frameworks are available to be used. Attempting to use features down level like this is going, inevitably, run into issues like this. 

Removing dependencies like this is mostly a non-goal in the compiler.
