### ISSUE TITLE
pushd command not found if invoked from non-bash shell.

### ISSUE THREAD

**Issue by abhiranjankumar00** [dotnet/roslyn#7499]
When invoked make file from the zsh, it prints the following error.

```
/bin/sh: 1: pushd: not found
```

IMO, it is due to the fact that `pushd` is a [bash specific command](http://stackoverflow.com/questions/5193048/bin-sh-pushd-not-found). I got it running by prepending the makefile with `SHELL = /bin/bash`.

If this is a valid solution, then I can submit a pull request.

**Comment by davkean** [comment]
tag @agocke

**Comment by agocke** [comment]
I think I just merged the fix here

**Comment by agocke** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/7483

**Comment by abhiranjankumar00** [comment]
Thank you.
