### ISSUE TITLE
Incorrect nullability analysis 

### ISSUE THREAD

**Issue by michelemottini** [dotnet/roslyn#75017]
**Version Used**: 

Current - Default (see SharpLab)

**Steps to Reproduce**:

See 
```
using System;
public class C {
    public void M() {
    }
    
    public int Test(int? value)
    {
        if (value == null)
        {
            return 0;
        }

        if (value != null)
        {
            return 11;
        }

        return value.Value; // warning CS8629: Nullable value type may be null.
    }
}
```

[sharplab](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQMwAJboMLoN7LpGYZQAs6AsgBQCU+hxAvo0ayegJYB2ALugBUApgGde1HrwD86AG4BDADYBXIbXYEkxbVwBm6agpVD0AXlPpuyxYvVadRTQ4dQA7OgAMAbnbaWSX2JOfUMlVXQAQgsrGztnBnt4ojd0ODgfRJ1/QOT3I1UAOgA1MKEMv2QmIA=)

or also
```
using System;
public class C {
    public void M() {
    }
    
    public int Test(int? value)
    {
        if (value == null)
        {
            return 0;
        }

        if (value != null && value.Value == 10)
        {
            return 11;
        }

        return value.Value; // warning CS8629: Nullable value type may be null.
    }
}
```

[sharplab](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQMwAJboMLoN7LpGYZQAs6AsgBQCU+hxAvo0ayegJYB2ALugBUApgGde1HrwD86AG4BDADYBXIbXYEkxbVwBm6agpVD0AXlPpuyxYvVadRTQ4dQA7OgAMAbnbaWSX2JOfUMlVXQAQgsrG3QAMji5MKEAOgA1ZLMLOA87ZwZ7fKI3dDg4H0Kdf0Di9yNVdOSKv2QmIA=)

(where the warning is no longer on unreachable code)

**Expected Behavior**:

No warnings / errors

**Actual Behavior**:

'Nullable value type may be null' at line 18 (`return value.Value;`)

**Comment by jcouv** [comment]
This behavior is expected. The compiler treats user non-null checks seriously, so in the alternative branch the variable is considered maybe-null.

For example:
```
void M(object o)
{
  // not-null
  if (o != null)
  {
    // not-null
  }
  else
  {
    // maybe-null
  }
}
```

FWIW, here's a [short write-up](http://blog.monstuff.com/archives/2020/01/analyzing-a-nullability-example.html) on this question.

**Comment by michelemottini** [comment]
OK, I see, thanks
