### ISSUE TITLE
Refactoring "Introduce local for all occurences of..." does more than it should be allowed to

### ISSUE THREAD

**Issue by Joe4evr** [dotnet/roslyn#7504]
![badroslynbad](https://cloud.githubusercontent.com/assets/1058562/11824066/d6d501b4-a377-11e5-9964-58221ba7a34f.png)
Notice in this picture that aside from introducing a local like I want, this refactoring also wants to change `Int64.Parse` into `long.Parse`, something that this refactoring should have nothing to do with.

**Comment by DustinCampbell** [comment]
@Joe4evr, That definitely looks like a bug, but it's hard to tell what's happening in the screenshot. Is all of the code nested within a lambda? Is there a smaller code example that demonstrates the problem? I'll try looking for a repro as well. I'm just curious to know if you have more info.

**Comment by Joe4evr** [comment]
The scope where the local is introduced is inside a lambda. The call to `Int64.Parse` is inside of a different lambda, since I'm using a fluid builder API. Here's a short Repro:
```c#
class Repro
{
    void Foo(string arg)
    {

        var fb = new FooBuilder().SetBar(() => String.IsNullOrWhiteSpace(arg))
            .SetFoo(() =>
            {
                Console.WriteLine(5); //Use Ctrl+. on any of the '5's here
                Console.WriteLine(5);
                Console.WriteLine(5);
                Console.WriteLine(5);
                Console.WriteLine(5);
            });
    }
}

class FooBuilder
{
    private Action _foo;
    private Func<bool> _bar;
    public FooBuilder SetFoo(Action foo)
    {
        _foo = foo;
        return this;
     }

    public FooBuilder SetBar(Func<bool> bar)
    {
        _bar = bar;
        return this;
    }
}
```

**Comment by DustinCampbell** [comment]
Here's an even simpler repro.

```C#
using System;
using System.Linq;

class Program
{
    static void Main()
    {
        var d = 2;
        var q = Enumerable.Range(Int32.Parse("1"), Int32.Parse("64"))
            .Where(x => x % d == 0);
    }
}
```

**Comment by CyrusNajmabadi** [comment]
I don't repro this, including with the second repro.
