### ISSUE TITLE
AsyncLazy frequently generates InvalidOperationException...

### ISSUE THREAD

**Issue by KevinH-MS** [dotnet/roslyn#7505]
We should investigate a way to make this fire less often.

The previously attempted approach (492dc66f66123c04231a9c8eadba5c5370d0e087) resulted in excess allocations/VM usage (see #6636).  We will have to understand/mitigate the extra allocations or else find another way to prevent the Exception.

**Comment by jasonmalinowski** [comment]
Note that the proper fix is still to move us forward to .NET 4.6 which has exactly the method we need.

**Comment by CyrusNajmabadi** [comment]
Can we move to 4.6? @mattwar @pilchie what do you think?

On Dec 18, 2015 9:51 AM, Kevin Pilch-Bisson <notifications@github.com> wrote:

Assigned #7505<https://github.com/dotnet/roslyn/issues/7505> to @CyrusNajmabadi<https://github.com/CyrusNajmabadi>.

-

**Comment by Pilchie** [comment]
The discussion we had on this in the past was that we could for the future branch, but not in master.  It's a big deal to drop support for 4.5.1 for all users of Workspace in a point release.

**Comment by jasonmalinowski** [comment]
Of course, we still need to understand why this had the claimed regression...it's still inexplicable.

**Comment by CyrusNajmabadi** [comment]
is this one of those types we can use reflection to find/invoke the proper method for?  I'm all for doing that if necessary.

**Comment by jasonmalinowski** [comment]
We could. Can we understand why this "regression" happened? @KevinH-MS, can we apply this change to see if it happens again?

**Comment by KevinH-MS** [comment]
@jasonmalinowski, Yes, I can, but it will be next week (prob Tuesday, because I'm not working Monday).

**Comment by DustinCampbell** [comment]
Moving to 1.3. This is not required for 1.2

**Comment by mattwar** [comment]
I hit this every time I debug. :-(

**Comment by CyrusNajmabadi** [comment]
Kevin, can you see if this still reproes with the revert reverted.  We'd really like to put this back to where it was.

**Comment by KevinH-MS** [comment]
Test run is going...should have an answer in a couple hours...

**Comment by KevinH-MS** [comment]
Sorry for the "dog ate my homework" excuse here, but the run results still aren't on the share where I'd expect.  I reached out to the RPS team to figure out what's up.  If I don't hear back this morning, I'll kick off another run.

**Comment by KevinH-MS** [comment]
Okay, I've reset two tests (both C# Desktop and Web) several times, and I've convinced myself that this no longer leads to a clear increase in VM usage.  Please feel free to revert my revert. :+1:

**Comment by Pilchie** [comment]
Also, at this point we should just merge a real fix in future, where we are targeting 4.6.
