### ISSUE TITLE
Formatting within `#if #else #endif` Statements

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#75054]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Formatting-within-if-else-endif-Sta/10740495)._

---
Within `#if #else #endif` statements, formatting does not happen on the not selected (if true than the `#else` part and vice versa) part of the statement.

Ideally the not selected part needs to be (1) formatted also and (2) error checked.

---
#### Lisa Gao (CSI Interfusion Inc) [MSFT] on 9/8/2024, 07:08 PM: 

(private comment, text removed)
#### Suminda Dharmasena on 9/10/2024, 06:55 AM: 

(private comment, text removed)
#### Feedback Bot on 9/10/2024, 06:11 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
By design. The code inside the not taken path is not even lexed into tokens. There is nothing to format in there (it can be arbitrary, invalid, code)
