### ISSUE TITLE
Feature Request: Allow method type parameter names to match method names

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#7507]
```C#
void T<T>() {}
```

There is no reason that this should be illegal, and both Mono and the spec allow it.

 > Error CS0694: Type parameter 'T' has the same name as the containing type, or method

**Comment by SLaks** [comment]
To fix this, just delete http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Symbols/Source/SourceMemberMethodSymbol.cs,825

**Comment by svick** [comment]
This looks exactly the same as #7506 and was posted at the same time.

**Comment by gafter** [comment]
Great minds think alike. Or something.

**Comment by gafter** [comment]
I suspect the language spec doesn't restrict this. If that is true, there is no more work to do, in either the compiler or the spec.
