### ISSUE TITLE
Pattern matching an enum using an enum value following by using "with expression" on a record causes a compilation error

### ISSUE THREAD

**Issue by NicholasMoss** [dotnet/roslyn#75074]
**Version Used**: 
Visual Studio 17.12.0 Preview 2.0
DotNet 9.0.100-rc.1.24452.12

**Steps to Reproduce**:
Create a console app with just this snippet
```csharp
enum E { A, B }
record R(int E) { }

static class TestClass
{
    public static R TestMethod(E testEnum, R record) =>
        testEnum is E.A ? record with { E = 1 } : record with { E = 1 };
}

```

**Diagnostic Id**:
```
Build started at 11:46...
1>------ Build started: Project: ConsoleApp1, Configuration: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\9.0.100-rc.1.24452.12\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(326,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
1>...\Program.cs(9,33,9,37): error CS1073: Unexpected token 'with'
1>...\Program.cs(9,48,9,49): error CS1002: ; expected
1>...\Program.cs(9,48,9,49): error CS1519: Invalid token ':' in class, record, struct, or interface member declaration
1>...\Program.cs(9,66,9,67): error CS1519: Invalid token '=' in class, record, struct, or interface member declaration
1>Done building project "ConsoleApp1.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build completed at 11:46 and took 01.248 seconds ==========
```

**Expected Behavior**:
Code would compile as it does using stable compiler

**Actual Behavior**:
Errors as shown above

**Comment by KyouyamaKazusa0805** [comment]
See https://github.com/dotnet/roslyn/issues/66841#issuecomment-1429793998

In short, because you define a property `E`, which conflicts with type `E`. You should append an extra discard token `_` to tell compiler that here `E` is a type with a discard, and not be a field.

C# compiler well make `is Type` to be recognized as a type, but C# also introduced a pattern type called "constant pattern", which also uses such syntax `is ConstantField`, which leads to a confliction.

**Comment by NicholasMoss** [comment]
This is only a snippet to replicate it in a standalone solution. In the actual solution where I hit these issues the names do not overlap.

The `E` part is unrelated which you can prove by wrapping the enum parts in parenthesis (which the analyzers tell you are unnecessary)

```csharp
enum E { A, B }
record R(int E) { }

static class TestClass
{
    public static IEnumerable<R> TestMethod(E testEnum, R[] records) =>
        testEnum is (E.A)
            ? from item in records
              select item
            : records;
};

```

This will build successfully.

Note if you create a console app with that code you will still get the error even if you the property from `E` to something else.

**Comment by KyouyamaKazusa0805** [comment]
This compiles fine because you don't have a type also called `A`, and is the nested type of `E` and won 't make an confliction.

**Comment by DoctorKrolic** [comment]
There is nothing to do with semantics here, this is purely a parser regression introduced in https://github.com/dotnet/roslyn/pull/72805. It doesn't matter what additional types or variables you declare: the expression just isn't parsed correct and produces a syntax error
