### ISSUE TITLE
Syntax highlighting missing from just the active C# file in a Visual Basic project on second vertical document group when solution opened

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#75109]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Syntax-highlighting-missing-from-just-th/10743468)._

---
[severity:It bothers me. A fix would be nice] [regression] [worked-in:17.11.2]
In a solution with multiple projects, where one is C# and another is VB (not sure if this is relevant), Attach a C# file or convert one of the vb files to the VB project - it is a miscellaneous file in the project. 

Open two vertical document groups with the C# file of the vb project selected in the right hand side. Uncertain if the quantity of tabs is a factor - I have many open in both document groups with 25 on left and 17 on right, using multiple rows option.

Save the solution.

Close VS

Open VS and the solution.

The C# of the source file has not been detected and is presented as a plain file rather than a miscellaneous file with syntax highlighting and sections, etc.

Other tabs not in the foreground at load time are all good.

To resolve the problem: Close the affected tab and reopen the C# file. Not a permanent solution, since the problem reappears on next solution load.

---
#### Feedback Bot on 9/11/2024, 08:49 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not investing in this scenario.
