### ISSUE TITLE
Type name of EditorFeaturesOnTheFlyDocsElement appears at the end of QuickInfo in Razor component

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn#75106]
**Version Used**: VS 17.11.3, 17.12.0 Preview 2.0

**Steps to Reproduce**:

Hover over a piece of code in a Blazor component file (.razor).

**Expected Behavior**: QuickInfo shows normally.

**Actual Behavior**:

QuickInfo shows with the string `Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.QuickInfo.EditorFeaturesOnTheFlyDocsElement` (the output of calling `ToString()`?) appended at the end:

![](https://github.com/user-attachments/assets/36a6cc2d-f220-47be-9adb-1fb76888323f)

**Comment by arunchndr** [comment]
@akhera99 to scout and move to razor.
