### ISSUE TITLE
Visual Studio unable to suggest "using static" expressions as quick fix

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#75127]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-unable-to-suggest-using-s/10722553)._

---
Hello everyone!

When you use a type that requires a using statement, Visual Studio succesfully suggests the using statement in the quick fixes:

![image.png](https://aka.ms/dc/image?name=Ba0ce77b23007490e80b8b1398a3c2dff638592427032678076_20240814-163140-image.png&tid=a0ce77b23007490e80b8b1398a3c2dff638592427032678076)

However, when you use a method that could be resolved by a static using expression, Visual Studio has no idea what to do:

![image.png](https://aka.ms/dc/image?name=Bdbfba5c157be4958a3549e5eef457859638592427843987637_20240814-163302-image.png&tid=dbfba5c157be4958a3549e5eef457859638592427843987637)

In this example, putting "using static DebugUtil" on the top of the file would resolve the Assert call, as it is defined as a member of the static DebugUtil class.

Is there a feature like this or is there maybe a plugin to provide this? Or maybe there is an option to set up a shortcut so I can quickly add the using statement myself?

Thanks for any tips!

---
#### Feedback Bot on 8/15/2024, 00:02 AM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Closing out as i do not repro this.
