### ISSUE TITLE
Collapse to Definition when loading a file

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#75129]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Collapse-to-Definition-when-loading-a-fi/10721017)._

---
I usually hit Ctrl+M+O after opening a file, to see an overview of what I'm looking at. It gives me a bigger picture of the class in the file. 

I wish you add an editor option to do collapse all definition by default when I open a C# file. 

---
#### Feedback Bot on 8/14/2024, 00:01 AM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
This option already exists.
