### ISSUE TITLE
Create Required Property in C# with propr

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#75128]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Create-Required-Property-in-C-with-prop/10722495)._

---
In C#, I create property using the shortcut 'prop'. I want to be able to create required property using 'propr'

---
#### Feedback Bot on 8/14/2024, 07:52 PM: 

(private comment, text removed)

**Comment by deepakrathore33** [comment]
@CyrusNajmabadi Can we add tags feature-request and help wanted.

**Comment by akhera99** [comment]
> [@akhera99](https://github.com/akhera99) this seems reasonable to be. What do you think?

Seems reasonable, I will add feature-request and help wanted tags.
