### ISSUE TITLE
Add "Copy Error Message Text" button to syntax error popups in the Visual Studio text editor

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#75131]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Add-Copy-Error-Message-Text-button-to-/10707825)._

---
I was working in C#.  In my specific case, I was trying to assign a value to a field in a record after it had been initialized.  I hover over the words with red underline and a popup appears saying the error is CS8852 and tells me what the error is.  I try to select the text with the mouse and copy it, but I can't.  It won't select, so I can't Google it without remembering it and typing it all in.

How about a button to copy the error message text to the clipboard, so I don't even have to bother selecting the text?

Or even better, how about a button to send the text as a search in the default browser?  DEFAULT browser.  Don't just open up Edge like Windows does when you try and do a search from the Start Menu.  That's insufferable.

---
#### Feedback Bot on 7/22/2024, 06:38 PM: 

(private comment, text removed)
#### Mika Dumont [MSFT] on 8/15/2024, 11:32 AM: 

(private comment, text removed)
#### Matt Gregory on 8/15/2024, 03:36 PM: 

(private comment, text removed)

**Comment by mikadumont** [comment]
Looks like the link to error CS8852 isn't listed and is taking users to: https://learn.microsoft.com/en-us/dotnet/csharp/misc/sorry-we-don-t-have-specifics-on-this-csharp-error?f1url=%3FappId%3Droslyn%26k%3Dk(CS8852)

**Comment by CyrusNajmabadi** [comment]
Closing out as external.  roslyn does not own these docs.
