### ISSUE TITLE
Provide a means to automatically generate declarations for out parameters to a method

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#75130]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Provide-a-means-to-automatically-generat/10716417)._

---
It would be great if Visual Studio provided a means to automatically declare and pass-in parameters that are designated with the “out” keyword. Maybe this could be done via a keypress combination or possibly with a quick-action prompt for the method. This quick-action could be displayed whenever the keyword “out” is typed for a method argument being called.

---
#### Feedback Bot on 8/5/2024, 07:01 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Closing as not planned due to lack of broad feedback.
