### ISSUE TITLE
duplicate language feature status

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/roslyn#75144]
Seems the language feature status for the `ref struct interfaces` is duplicated

![image](https://github.com/user-attachments/assets/ebc9bdc1-de0a-4ce6-a908-308676f5127c)

**Comment by jcouv** [comment]
Seems fine to merge, since we ended up shipping both parts of the in the same release (17.11p2). Tagging @AlekseyTs to confirm

**Comment by AlekseyTs** [comment]
No preference. In implementation we have to distinct feature ids. If we keep both, it would be good to have them next to each other.

**Comment by WeihanLi** [comment]
Since it's the same feature, linked to the same proposal issue, and the same feature branch, so maybe it's better to keep only one status I think
