### ISSUE TITLE
Replace 'xxx' with method has bug

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#75186]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Replace-xxx-with-method-has-bug/10745950)._

---
![GIF 2024-09-15 오후 5-37-40.gif](https://aka.ms/dc/image?name=B220f1be21b9a46e99547385f62471d3d638619863244745946_GIF_2024-09-15_%EC%98%A4%ED%9B%84_5-37-40.gif&tid=220f1be21b9a46e99547385f62471d3d638619863244745946)

---
#### Feedback Bot on 9/18/2024, 04:59 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

**Comment by sharwell** [comment]
### Input code

```cs
class A
{
    #region
    static bool a;
    #endregion
    static bool b => true;
}
```

### Steps

Run **Replace 'b' with method** on property `b`.

### Actual result

```
class A
{
    #region
    static bool a;

    #endregion
    #endregion
    private static bool Getb()
    {
        return true;
    }
}
```

### Expected result

```
class A
{
    #region
    static bool a;
    #endregion
    private static bool Getb()
    {
        return true;
    }
}
```
