### ISSUE TITLE
WarningsAsErrors is not working

### ISSUE THREAD

**Issue by MhAllan** [dotnet/roslyn#75198]
**Version Used**:  Visual Studio 17.11.4

`WarningsAsErrors` is not working as expected, VS is showing red line for the error, but still builds and runs! so the code below gives runtime ref null exception instead of compile time error

```xml
<PropertyGroup>
	<OutputType>Exe</OutputType>
	<TargetFramework>net8.0</TargetFramework>
	<Nullable>enable</Nullable>
	<WarningsAsErrors>nullable</WarningsAsErrors>
	<ImplicitUsings>enable</ImplicitUsings>
</PropertyGroup>
```

```csharp
class Program
{
    static void Main()
    {
        string x = null;
        Console.WriteLine(x.GetType());
    }
}
```

**Expected Behavior**: Compile time error

**Actual Behavior**: Nothing at compile time, leaving null exceptions to runtime

**Comment by huoyaoyuan** [comment]
I can't reproduce this in VS 17.11.4 and VS 17.2 P2. The build fails with provided example.

**Comment by MhAllan** [comment]
@huoyaoyuan , That is strange, mine compiles and run!!

I tried to remove bin and proj folders, no difference
I tried `string x = 10`, and got compiler error, so errors are breaking the build correctly

but still the WarningsAsErrors above not breaking the build and run!? 

**here are versions in .sln**
# Visual Studio Version 17
VisualStudioVersion = 17.4.33213.308
MinimumVisualStudioVersion = 10.0.40219.1

what do you suggest?

**Comment by huoyaoyuan** [comment]
Try to collect the build log may help to diagnose the issue. You can use the command line `dotnet build -bl:filename.binlog` to collect the log, and try to use the viewer at https://msbuildlog.com/ to see if `WarningsAsErrors` gets accidentally override.

**Comment by MhAllan** [comment]
VS is behaving correctly today 🤔. Thanks a lot @huoyaoyuan

**Comment by MhAllan** [comment]
VS is behaving correctly today 🤔. Thanks a lot @huoyaoyuan

**Comment by MhAllan** [comment]
@huoyaoyuan actually the build is correct, but the VS "debug" button runs it skipping the build errors!
