### ISSUE TITLE
Suggestion: Select the span automatically based on cursor position for introduce local / constant

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#752]
Ported from TFS WorkItem: **1065670**, originally filed by @shyamnamboodiripad 

---

**Repro Steps:**

Currently, I&nbsp;if I want to invoke introduce local /constant&nbsp;refactoring on a multiline string literal, I am forced to select the entire string first. It&nbsp;would be nice if&nbsp;I could invoke the&nbsp;refactoring by simply placing cursor somewhere in the string and hitting ctrl +&nbsp;.&nbsp;

Can't we figure out the minimum enclosing span for the current cursor position&nbsp;(i.e. expand to&nbsp;span of innermost node / expression&nbsp;containing the cursor) and offer refactorings as if the user had selected this span? I could also imagine this being useful for other&nbsp;expressions (date literals,&nbsp;expressions / method calls&nbsp;involving long identifiers etc.)

![image](https://cloud.githubusercontent.com/assets/4213867/6311587/a001512c-b919-11e4-8be7-c0960e7576fc.png)

Looks like we do this already in some other refactorings? For example, if i select jsut 'String' in the following If statement, I am offered an extract method refactoring that extracts the entire 'typeof x isnot string' expression-

![image](https://cloud.githubusercontent.com/assets/4213867/6311588/b48d5c6c-b919-11e4-9422-40e522b8373d.png)

Revision History:

1) Created By Shyam Namboodiripad (10/16/2014 11:22:37 PM)

2) Edited By Kevin Pilch-Bisson (10/17/2014 10:03:24 AM)

Can you think about the UX here?

3) Edited By Kevin Pilch-Bisson (2/20/2015 3:21:24 PM)

Yes, I think this is a good idea to help with our refactoring discoverability.&nbsp; It may not fit in RTM though.&nbsp; Can you port to GitHub.

**Comment by Pilchie** [comment]
Moving to 1.1.

**Comment by ryanbrandenburg** [comment]
Design Meeting Notes: Let's try this out with a service that lets the customer select an expression from a sub-list based on where their caret was when they invoked.

**Comment by sharwell** [comment]
This refactoring will use `IRefactoringHelpersService` to provide the span information for a position:

https://github.com/dotnet/roslyn/blob/d140d0857b91dbe68968c574ce80ee0bf56d72da/src/Features/Core/Portable/CodeRefactorings/IRefactoringHelpersService.cs#L39

**Comment by CyrusNajmabadi** [comment]
Introduce constant is offered within a string literal:

![image](https://user-images.githubusercontent.com/4564579/217117537-492c358b-64b0-4244-b9fe-e56f6e6a6db6.png)
