### ISSUE TITLE
Parameter type infer failed in lambda.

### ISSUE THREAD

**Issue by diryboy** [dotnet/roslyn#7520]
VS2015 Community Update 1 on Win10 RTM x64
Just create a new Console Application and type the following, ignore the color bug:
![image](https://cloud.githubusercontent.com/assets/159110/11834108/2a89effe-a404-11e5-9c46-9ec0b0a1e613.png)

**Comment by diryboy** [comment]
Ah, duped #5498

**Comment by diryboy** [comment]
Reopening, as this one dose not involve overload resolution.

**Comment by diryboy** [comment]
I think I have a fix for this.

**Comment by AlekseyTs** [comment]
@jaredpar Please assign appropriate milestone for this issue. Need to know what branch the fix should go into.

**Comment by jaredpar** [comment]
@AlekseyTs moved to 2.0 as that is when I expected us to have time to fix it.  Willing to accept in 1.3 though if communiyt is doing the work ;)

**Comment by AlekseyTs** [comment]
Should be fixed now. @TyOverby please verify.
