### ISSUE TITLE
Collection expressions can avoid additional local when constructing a `List<T>` of fixed size

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#75208]
See [codegen of `C.M`](https://sharplab.io/#v2:EYLgtghglgdgNAFxFANgHwAIAYAEGCMALANwCwAUBRgMx4BMOAwhQN4U4d60AyUAzggA8sBAD4cAWQAUAShwBecQG18cHHTXUAumXIBfIA==):
```cs
using System.Collections.Generic;

public class C
{
    public List<int> M() => [1, 2, 3];
}
```

To construct the resulting list the following is emitted:
```cs
int num = 3;
List<int> list = new List<int>(num);
CollectionsMarshal.SetCount(list, num);
...
```
It takes more ceremony to init the local and then use it than if the number of elements was used directly:
```cs
List<int> list = new List<int>(3);
CollectionsMarshal.SetCount(list, 3);
...
```

**Comment by CyrusNajmabadi** [comment]
Does this affect the jitted code at all?

**Comment by DoctorKrolic** [comment]
No, it doesn't. But it doesn't have to. Similarly to #74982 the aim here is to reduce IL size a little bit. You can add a 'help wanted' label, I'll take this after #74982 is merged. It is most likely a matter of a single `if` check somewhere in the local rewriter

**Comment by jaredpar** [comment]
How common is this pattern though? I agree yes it could reduce IL a bit but does it happen often enough to be worth the complexity trade off? 

Does this impact ENC? I'm warry of cases like this where we convert variables to repeated constants and how that could / couldn't impact areas like ENC.

**Comment by jaredpar** [comment]
Closing because haven't seen data that this is a substantial issue and thus not sure it's worth the trade off to implement
