### ISSUE TITLE
remove `net7.0` target

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/roslyn#75205]
![image](https://github.com/user-attachments/assets/4a8483d9-727c-4b28-a898-6cdb96b08435)

Since `net7.0` is out of date, maybe we should remove the `net7.0`

![image](https://github.com/user-attachments/assets/e997c85f-0eaf-4e3c-ae4c-c8fca665b6f5)

https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

**Comment by huoyaoyuan** [comment]
The previous major version seems used for source build: https://github.com/dotnet/roslyn/blob/main/eng/targets/TargetFrameworks.props

We should be able to remove this when moving source build to next version.
