### ISSUE TITLE
[LSP] Return the same resultId if the diagnostic report is the same

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#75240]
Related to https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2261953

Diagnostic allocations are coming up as a high hitting perf issue.  The request from the VS client side is for the server to re-use resultIds more often.  Currently we only re-use the resultId if we see that the checksum of the current document+project cone is the same as the last request.  The requested change is as follows

If both the last diagnostic report and the current diagnostic report for a document+kind contains the exact same data, then we should re-use the resultId from the last report to avoid re-serializing over the same diagnostic data.

**Comment by CyrusNajmabadi** [comment]
> If both the last diagnostic report and the current diagnostic report for a document+kind contains the exact same data,

How would we know if it has the same data?  Or is this a suggestion for us to cache teh results as well on our end to compare against?

**Comment by dibarbet** [comment]
> > If both the last diagnostic report and the current diagnostic report for a document+kind contains the exact same data,
> 
> How would we know if it has the same data? Or is this a suggestion for us to cache teh results as well on our end to compare against?

Yeah - cache the result (or hash of result or something) with the resultId so we can compare and avoid re-sending the same diagnostics again.
