### ISSUE TITLE
Unable to translate bytes [C5] at index 560 from specified code page to Unicode.

### ISSUE THREAD

**Issue by philippe-lavoie** [dotnet/roslyn#7527]
I'm getting that error when doing 

var compilationTask = project.GetCompilationAsync();

This is very frustrating since I had good working code and now that I tried to do an upgrade, everything is starting to fall apart with exceptions everywhere and missing package dependencies. Very frustrating.

In this particular case, how can I move forward ? Why is a solution that builds in VS2015 has all this sorts of trouble ? I even had to add

workspace.SkipUnrecognizedProjects = true;

otherwise my call to 

var originalSolution = workspace.OpenSolutionAsync(solutionPath).Result;

would never end.

Do you also have the same issues with post RC1 code ?  I'm sure I'm not the only one trying to load a very complex solution?

**Comment by gafter** [comment]
Can you please gather a repro into a zip file and share it with us?

**Comment by philippe-lavoie** [comment]
The problem was a corrupt SLN file... too many merges from many branches caused the sln to be in a weird state. It would compile within Visual Studio, but Roslyn would just go BOOM. I re-imported manually all projects in a new sln file. Very painfull, but now it works. 
Is there a tool to check the sanity of a SLN file ?

**Comment by DustinCampbell** [comment]
@philippe-lavoie -- sadly, I don't know of a tool to do this. MSBuild does have a solution parsing API, but it's fairly resilient to broken SLN files and might not be useful in detecting problems.
