### ISSUE TITLE
Call Hierarchy not navigating/searching some symbols

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#7528]
View call hierarchy on `ObjectDisplay.FormatPrimitive(object obj, ObjectDisplayOptions options)`.  I'm using the copy in `CSharpCodeAnalysis`.  

The first and third callers can be expanded and navigated-to, but the second and fourth cannot.  It looks like symbol ID resolution is failing.

**Comment by amcasey** [comment]
FYI @dpoeschl

**Comment by Pilchie** [comment]
Was this fixed by your changes around unification between Portable and Desktop references?

**Comment by Pilchie** [comment]
Ping on the question above...

**Comment by CyrusNajmabadi** [comment]
Could not repro this.  Navigation succeeded for me on all results.
