### ISSUE TITLE
VisualBasic is now required for a C# solution...

### ISSUE THREAD

**Issue by philippe-lavoie** [dotnet/roslyn#7530]
Why is VisualBasic required now ? With 1.1.1, MsBuildWorkspace.Create fails if VB isn't there. Any reasons ?

**Comment by mattwar** [comment]
This is not supposed to be the case.  What exception stack are you getting?

**Comment by mattwar** [comment]
I am not able to reproduce this.  I created a simple c# project that uses nuget to reference Microsoft.CodeAnalysis.CSharp.Workspaces package (and dependencies).  This does not include VB dlls.  I am able to create the MSBuildWorkspace and successfully open the same C# project.

**Comment by philippe-lavoie** [comment]
Ok, you can close this (or perhaps start another issue ?)

My issue was that my sln file was corrupt after too many bad merges. It would open and compile fine in VS2013 or VS2015, but it asked for VB when opened with Roslyn and couldn't generate a Compilation unit (see my other bugs). So, my solution was to start a new sln and manually re-import all the project files to that new solution. After that it worked, It was very painfull since we have 70+ projects.
