### ISSUE TITLE
IReadOnlyList/IReadOnlySet Collection Expression Parity

### ISSUE THREAD

**Issue by shravan2x** [dotnet/roslyn#75308]
There's currently some difference between the `IReadOnlyList` and `IReadOnlySet` interfaces where the latter can't be initialized using a collection expression

```c#
IReadOnlyList<int> readOnlyListOfInts = [1, 2, 3]; // Works
List<int> listOfInts = [1, 2, 3]; // Works
ImmutableList<int> immutableListOfInts = [1, 2, 3]; // Works
IReadOnlySet<int> readOnlySetOfInts = [1, 2, 3]; // Error <-------
HashSet<int> hashSetOfInts = [1, 2, 3]; // Works
ImmutableHashSet<int> immutableHashSetOfInts = [1, 2, 3]; // Works
```

The error is `CS9174	Cannot initialize type 'IReadOnlySet<int>' with a collection expression because the type is not constructible`. Could you clarify why this occurs?

**Comment by CyrusNajmabadi** [comment]
The language specifies that any interface implemented by an array is constructible.  If it's a mutable interface, you get `List<T>`. If it's a read only interface you get a synthesized collection that can't be mutated. 

There is no such support of set interfaces as the language does not view sets as something core to it.

**Comment by shravan2x** [comment]
This seems to be highly unexpected behavior. Perhaps the language should change its definition of what collections are constructible?

**Comment by CyrusNajmabadi** [comment]
> Perhaps the language should change its definition of what collections are constructible?

Feel free to start a discussion on dotnet/csharplang about that idea :)

> Please consider leaving the issue open till the discussion surrounding it is complete.

You didn't open a discussion, you opened an issue asking why something worked a particular way.  There is no actual issue here, and the reason was given :)

If you'd like this to change, teh right approach is to start with a discussion over on dotnet/csharplang.  Thanks :)
