### ISSUE TITLE
Pattern match condition in ternary resulting in collection expression fails to parse; ternary appears to be mis-parsed as nullability modifier

### ISSUE THREAD

**Issue by EamonNerbonne** [dotnet/roslyn#75318]
**Version Used**:  Compiler: '4.12.0-2.24459.2 (be9c072e)'. Language: 12.0. Prior compiler versions supporting C# 12 IIRC also behave like this.

**Steps to Reproduce**:

Compile the following program:

```C#
using System;
int[] nextDayOffSet = DateTime.Today.DayOfWeek is DayOfWeek.Friday ? [1, 2, 3] : [1];
Console.WriteLine(nextDayOffSet.Length);
```

**Expected Behavior**:
Compiles without error and prints 1 or 3.

**Actual Behavior**:
```
    error CS1002: ; expected
    error CS1022: Type or namespace definition, or end-of-file expected
    error CS1001: Identifier expected
    error CS1003: Syntax error, ',' expected
    error CS0426: The type name 'Friday' does not exist in the type 'DayOfWeek'
    error CS0270: Array size cannot be specified in a variable declaration (try initializing with a 'new' expression)
    error CS0029: Cannot implicitly convert type 'bool' to 'int[]'
    error CS7014: Attributes are not valid in this context.
```

**Workarounds**
Parenthesize either condition or true-branch or some other hack such that the `?` cannot be misunderstood as a nullability indication,, i.e. these compile and run fine:

```C#
using System;
int[] nextDayOffSet = (DateTime.Today.DayOfWeek is DayOfWeek.Friday) ? [1, 2, 3] : [1];
Console.WriteLine(nextDayOffSet.Length);
```
or 
```C#
using System;
int[] nextDayOffSet = DateTime.Today.DayOfWeek is (DayOfWeek.Friday) ? [1, 2, 3] : [1];
Console.WriteLine(nextDayOffSet.Length);
```
or
```C#
using System;
int[] nextDayOffSet = DateTime.Today.DayOfWeek is DayOfWeek.Friday ? ([1, 2, 3]) : [1];
Console.WriteLine(nextDayOffSet.Length);
```
or even
```C#
using System;
int[] nextDayOffSet = DateTime.Today.DayOfWeek is (DayOfWeek)5 ? [1, 2, 3] : [1];
Console.WriteLine(nextDayOffSet.Length);
```

I'm not sure whether this is a compiler bug, or just a really unfortunate bit of the language spec (i.e. is this better reported to https://github.com/dotnet/csharplang?). This actually bites when I'm trying to conditionally pick one of two collections to pass to some method; the use of a variable here is just for clarity.

**Comment by jaredpar** [comment]
@CyrusNajmabadi, @cston is this a bug or language spec issue?

**Comment by CyrusNajmabadi** [comment]
Bug in the impl.  This should parse properly.  However, the parser for patterns has a lot of complexity in trying to determine if `X?` is a nullable, or a the start of a conditional expr.  Looks like this case was missed.  Feel free to assign to me.  I can see if this is simple to fix.

**Comment by EamonNerbonne** [comment]
🥳 That was an impressively fast fix; hats off!

**Comment by CyrusNajmabadi** [comment]
Thanks for the report :)
