### ISSUE TITLE
Broken NGEN in 4.13

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#75323]
NGen of various binaries (Microsoft.VisualStudio.LanguageServices.Razor.dll, Microsoft.CodeAnalysis.Razor.Workspaces.dll, and Microsoft.VisualStudio.DesignTools.XamlLanguageService.dll) is broken in our main validation insertions when we update Roslyn to 4.13. Various errors along this line:

```
09/30/2024 08:41:12.349 [1796]: Failed to load dependency Microsoft.CodeAnalysis.LanguageServer.Protocol of assembly Microsoft.CodeAnalysis.Razor.Workspaces, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 because of the following error : The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
09/30/2024 08:41:12.584 [1796]: 1>    Compiling assembly C:\VisualStudio\Common7\IDE\CommonExtensions\Microsoft\RazorLanguageServices\Microsoft.CodeAnalysis.Razor.Workspaces.dll (CLR v4.0.30319) ...
09/30/2024 08:41:12.819 [1796]: 1>Warning: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.CodeAnalysis.LanguageServer.Protocol, Version=4.12.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) while resolving 0x2000091 - Microsoft.CodeAnalysis.Razor.Protocol.AutoInsert.RemoteAutoInsertTextEdit.
```

See https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/582158 (MSFT-internal) for an example and full NGen log.

**Comment by arkalyanms** [comment]
@RikkiGibson would you take a peek at this first and work with Gen for ngen?

**Comment by RikkiGibson** [comment]
It looks like following 3 DLLs are failing to ngen
- Microsoft.VisualStudio.LanguageServices.Razor.dll
- Microsoft.CodeAnalysis.Razor.Workspaces.dll
- Microsoft.VisualStudio.DesignTools.XamlLanguageService.dll

I'm not sure yet what change has caused this. #75226 seems suspicious to me, but I don't understand well enough the change it's making, to say that this is the cause.

**Comment by 333fred** [comment]
We figured this out; there are new roslyn DLLs missing from the binding redirects.

**Comment by DustinCampbell** [comment]
Glad you figured it out (and that it wasn't my fault)! 😀
