### ISSUE TITLE
Add keyboard shortcut for "Add null checks" in Generate Constructor refactor

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#75320]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Add-keyboard-shortcut-for-Add-null-chec/10756853)._

---
ALT+ENTER on a class and select "Generate constructor"
![image.png](https://aka.ms/dc/image?name=Babf59ab5c9924d6286d59e40a4f43551638633973185524272_20241001-173517-image.png&tid=abf59ab5c9924d6286d59e40a4f43551638633973185524272)

When I don't want null checks I can just hit Enter and the constructor is created.

When I do want null checks I either have to take my hands off the keyboard (sacrilege) and use the mouse to check the checkbox, or press TAB 5 times and then press Space before pressing Enter.

If the N in "Add **n**ull checks" was a shortcut I could replace those 6 keyboard operations with just ALT+N.

**Comment by CyrusNajmabadi** [comment]
@olegtk Another request for the ability to easily get to a lightbulb item when it is open.  if we allowed typing (and then searching/filtering of items) in the lightbulb, this would help out.  Can you redirect this?

**Comment by mrpmorris** [comment]
@CyrusNajmabadi @olegtk This isn't a request to quickly get to a lightbulb item. It's a request for a keyboard shortcut on a checkbox in a refactor dialog.

![image](https://github.com/user-attachments/assets/8b353ffc-4981-4cb9-be4c-5d407061eeac)

**Comment by mrpmorris** [comment]
Hooray! I have wanted this for years!!!!
