### ISSUE TITLE
Support proper unicode canonicalization in the fuzzy spell checker.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#7533]
Note: this is non-trivial because we need to move the platform the Workspaces layer is targeting to something that contains the Normalization APIs.  This is only in very recent CoreCLR platforms.

**Comment by Pilchie** [comment]
Seems like we'll need to do `PortableShim` based reflection

**Comment by Pilchie** [comment]
We should soon be targeting a more modern netstandard here in future.

**Comment by CyrusNajmabadi** [comment]
Closing this out as this only downside of this is that spell-checking might not find a result in complex unicode normalization cases (i.e. where the internal string has a normalized codepoint, but the user wrote out something non-normalized).  

1. We haven't heard about anyone running into a case where this impacted them.
2. It doesn't seem like that is that important.  Spell-checking, by definition, is a best-effort basis to try to find results.  Even in straight latin, we are very limited in what we find, and we don't even go beyond matches that are more than two characters different.
