### ISSUE TITLE
No suggestions in switch expression arm when dotting on an enum type in a `Color Color` case

### ISSUE THREAD

**Issue by Rekkonnect** [dotnet/roslyn#75350]
## Version Used
VS 2022 Version 17.11.4
Roslyn 4.11.0 (5649376e0e5f5db3743a94a62b073f2cce4be5d9)

Project info
C# 12.0
.NET 8.0

## Steps to Reproduce

Paste the following snippet and place the cursor at the position of `$$`:

```csharp
public sealed record OrderModel(int Id, Status Status)
{
    public string StatusDisplay
    {
        get
        {
            return Status switch
            {
                Status.$$
            }
        }
    }
}

public enum Status
{
    Undisclosed,
    Open,
    Closed,
}
```

In [SharpLab](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK4wD4AEDMACAZwFMIAbIgEz2SIGMB7ZKgeSaOQFl6KjSAKWAjwBJCnDwBlBBASoCk6bIIBKALAAoAN4a8uvLn0BGAAwKZcgCJQCAB1IQAnjr3b1e93gDmRBM495Xf38sAHYzJUIAdygEWgALPyDdQKSgqXMCADoAEmzEpIBffL0itxKNUo0DIhhUMHC5DRTdAFUYCmtaUnpiMUTmGxq4RIBhbt7h9QKgA)

In the above example, the auto complete will not show any suggestions. Note that this also works in a regular class, not binding to the primary constructor parameter, and also when the current context is a static method.

## Expected Behavior

I get all the suggestions for the enum field values of `Status` that I can use.

## Actual Behavior

No suggestions appear.

**Comment by Rekkonnect** [comment]
Can I take this up?

**Comment by CyrusNajmabadi** [comment]
Yes :)

**Comment by Rekkonnect** [comment]
This also hides an actual bug of a very unusual Color Color case shown below:
```csharp
public sealed record OrderModel(int Id, Outer.Status Status)
{
    public string Outer { get; }
    public string Inner { get; }

    public string StatusDisplay
    {
        get
        {
            return this switch
            {
                { Inner: Outer.Status.A } => "",
                { Inner: Outer } => "",
            };
        }
    }
}

public static class Outer
{
    public enum Status { A, B, C }
}
```

`Outer` binds to the property `Outer`, despite being directly inside a `ConstantPattern`, because it is a `SimpleMemberAccess`. When binding, `SimpleMemberAccess` is evaluated to always resolve Color Color cases, regardless of the context, assuming that the convention was to use `SimpleMemberAccess` when there is the probability of binding to a member or a type, and `QualifiedName` when we will always expect a type.

This same bug can also be observed in parenthesized constant patterns:
```csharp
public sealed record OrderModel(int Id, Status Status)
{
    public string StatusDisplay
    {
        get
        {
            if (Status is (Status.$$))
                ;
        }
    }
}

public enum Status
{
    Undisclosed,
    Open,
    Closed,
}
```
