### ISSUE TITLE
VS 2015 Update 1 on build machines

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#7537]
This work item is tracking the work required to move the build machines to VS Update 1. As part of this, 

- [x] VSIX Installer needs to stop trying to elevate
- [x] VSIX Installer needs to stop trying to uninstall the MSI installed extensions
- [x] Stop copying code marker's dll to System32 directory (StartTargetAction.EnsureCodeMarkersDllInstalled), and instead make sure we modify the environment so that LoadLibrary will find it. Apparently we're using code markers within the tests for synchronization.
- [x] Figure out if we need the custom watson handler, and if so, can we install it without admin privileges and better yet, without touching machine state.
- [x] TAO is test signed and requires skip verification entries to run
- [x] Disconnect script doesn't work on images (maybe for the same reason as on the fbld machines?)
- [x] System.Reflection.Metadata 1.1 is getting copied to the binaries directory instead of 1.2
- [x] Tao tests pass even though skip verification hasn't been run (review existing exceptions)
- [x] Get access to image from @mmitche and run all combination of CIBuilds on machine to verify that they all pass
- [x] Work with @mmitche to rollout Update 1 once we've confirmed the image is good

**Comment by heejaechang** [comment]
@davkean are these work item prevent us to move to update 1 VS drop or are those what we want going forward? asking since items seems not preventing us from moving to update 1 VS drop.

also, can you add a bit more detail on each item? for example, I don't know why VSIX installer require elevate permission currently? is it VSIX itself require it or the way we use require it. if it is the latter, what does make it require admin permission?

**Comment by heejaechang** [comment]
@davkean anyway, I will start looking at second code marker item.

**Comment by davkean** [comment]
If we were make the process admin, that would enable the first two - the other two require us to InstallDogfood/Install skip verification entries, which would mean we would have two separate images for open and closed jobs.

We're not blocked on Update 1 yet, so we may as well remove the admin rights to prevent further bleeding of things that break machine-state.

**Comment by davkean** [comment]
@heejaechang CrashDumps.CreateForProcess crashes when the custom watson handler isn't installed.

**Comment by davkean** [comment]
PR's out for 1 and 2: https://github.com/dotnet/roslyn-internal/pull/477

**Comment by amcasey** [comment]
The disconnect script doesn't seem to be working on the reimaged machine (rbld3).

**Comment by davkean** [comment]
@amcasey That would be a problem, can you talk to @tannergooding about that to see what the cause of that was?

**Comment by amcasey** [comment]
@davkean, yes, we're working on it between crises. :)

I remember you mentioning we were going to do less as Admin.  Have there been any changes in that area?  It looks like elevation might not suffice for tscon.

**Comment by davkean** [comment]
No probs. What do you mean by "elevation might not suffice for tscon"?

**Comment by amcasey** [comment]
I saw comments like this: https://social.technet.microsoft.com/Forums/windowsserver/en-US/2daa38a5-c089-4c6f-a1ab-98013cc448fb/tscon-cmd-and-permissions

**Comment by davkean** [comment]
User is still admin, just not elevated.

**Comment by amcasey** [comment]
A lot of user tests are failing with `<![CDATA[System.TypeInitializationException : The type initializer for 'Roslyn.Test.Utilities.TestBase' threw an exception.\r\n---- System.IO.FileNotFoundException : Could not load file or assembly 'System.Reflection.Metadata, Version=1.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.]]>`

**Comment by amcasey** [comment]
All the copies from nuget are 1.2, so I'm not sure where we got a 1.1. assembly.  Looking.

**Comment by amcasey** [comment]
Building locally (naively - not with scripts) copies 1.2 to the binaries directory.  Investigating the official process now to try for a repro that I can debug.

**Comment by amcasey** [comment]
Manually running cibuild.cmd also copies 1.2 to the binaries directory.

**Comment by amcasey** [comment]
I ran `cibuild /debug /test64` manually and it succeeded.  I'll kick off another lab run and see if we get 1.1. again.

**Comment by amcasey** [comment]
@davkean These are the failed runs I mentioned: http://dotnet-ci.cloudapp.net/view/roslyn-internal/job/roslyn-internal_master_win_dbg_unit64_test/

**Comment by amcasey** [comment]
I don't see CodeMarkers in %System32%

**Comment by amcasey** [comment]
@davkean Back to you.  If I think of anything else, I'll add a note.

**Comment by heejaechang** [comment]
Sorry, I have followed this thread. But CodeMarker shouldn’t be in the system anymore except perf tests. And for perf tests, they explicitly add it there rather than implicitly like before which affected all integration tests.


-          heejae

**Comment by dpoeschl** [comment]
When this is complete, I can fix a hack introduced in the snippets enumeration code to work around this. See #7943.

**Comment by agocke** [comment]
Regarding System.Reflection.Metadata, that appears to be bad references in the Closed Samples. I have created a PR https://github.com/dotnet/roslyn-internal/pull/516 to fix that.

**Comment by dpoeschl** [comment]
Any updates on the status of this? :smile:

**Comment by davkean** [comment]
it's been worked on, in between fires.

**Comment by dpoeschl** [comment]
Any updates on the status of this? :smile:

**Comment by agocke** [comment]
@dpoeschl The new "tst" queues are on Update 1, so when we switch over to those fully we should have update 1 everywhere.

**Comment by davkean** [comment]
We're blocked on @tannergooding on the dynamic pooling, it looks like, given the job failures that I'm still seeing that it might be at least a few more days.

**Comment by davkean** [comment]
This now has been resolved.
