### ISSUE TITLE
Add IncrementalAnalyzerProvider that primes SymbolTreeInfo

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#7538]
Especially now that we populate the backing BKTrees for Fuzzy Add Using.

//cc: @CyrusNajmabadi

**Comment by dpoeschl** [comment]
A known large assembly with ~38k members took about a second to populate the BKTree. With 10s/100s of referenced assemblies across a large solution, this time could add up.

**Comment by Pilchie** [comment]
@DustinCampbell and I thought we already had one (to use for Navigate To).
