### ISSUE TITLE
[New API] IsIterator field on DeclarationModifiers type

### ISSUE THREAD

**Issue by CoolCoderSuper** [dotnet/roslyn#75388]
## Background and Motivation
For quick reference the file can be found [here](https://github.com/dotnet/roslyn/blob/18fa0ea1b119b512df696ddf7ff6b3926f66a552/src/Workspaces/Core/Portable/Editing/DeclarationModifiers.cs)
The purpose of this api is to solve [this issue](https://github.com/dotnet/roslyn-analyzers/issues/7433) in the make member static analyzer.

C# does not have the explicit Iterator api and when using the SyntaxGenerator the modifier is dropped.
The type already has features that are language specific (ie IsUnsafe) so I would see no harm in supporting this as well.

This would bring the option for generators to create iterator methods closer to reality (not necessarily important).

## Proposed API

```diff
namespace Microsoft.CodeAnalysis.Editing
{
     public readonly record struct DeclarationModifiers
     {
+           public bool IsIterator => (_modifiers & Modifiers.Iterator ) != 0;
     }
```
This would also include the corresponding WithIterator() api. 

## Alternative Designs

Not having the API and having language specific code in the analyzer.

## Risks

Possible confusion since it only exists in VB.

**Comment by CyrusNajmabadi** [comment]
Why does this need to be public?  As opposed to just fixing GetModifiers to include this data internally to ensure that WithModifiers doesn't remove the modifier?

**Comment by CoolCoderSuper** [comment]
I suppose it wouldn't have to be but this would allow new generation to have the modifier applied.
But maybe that doesn't matter since you would still have to deal with `yield return` vs `Yield`.

**Comment by CoolCoderSuper** [comment]
@CyrusNajmabadi just so I understand, your proposal would be the same just internal rather than public?
