### ISSUE TITLE
Symbols not published for 4.11.0

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#75407]
If I create a new net8.0 console app and use Roslyn 4.11.0:
`<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Features" Version="4.11.0" />`
and then debug into Roslyn, I can't download symbols neither from nuget.org nor from Azure Symweb.

Did the process that publishes NuGets publish symbols as well? Is it time to just embed the pdbs for the Roslyn assemblies that ship in the NuGet packages?

**Comment by arunchndr** [comment]
@genlu can this be resolved now?

**Comment by genlu** [comment]
From what I can tell, those pdbs are shipped as part of the NuGet package, and I believe they are also published to some symbol servers (as part of each Roslyn signed build)

**Comment by KirillOsenkov** [comment]
Would you mind linking to a pair of package + symbols for Microsoft.CodeAnalysis for any recent public build? Thanks!

**Comment by genlu** [comment]
@KirillOsenkov I just downloaded Roslyn package from nuget.org. For example this is the content of [MS.CA.Features 4.11.0
](https://www.nuget.org/packages/Microsoft.CodeAnalysis.Features/4.11.0)
![Image](https://github.com/user-attachments/assets/1fb99728-08f2-4ef7-9707-1209fcd322cd)

**Comment by KirillOsenkov** [comment]
OK thank you!
