### ISSUE TITLE
IntelliCode suggestion stuck and never goes away

### ISSUE THREAD

**Issue by Peter-Juhasz** [dotnet/roslyn#75408]
**Version Used**: 17.12 P2.1

https://github.com/user-attachments/assets/f3d02950-dfc8-40d5-bacf-2cd6b3941003

It can't be dismissed either by:
 - `Esc` key
 - activating the suggestion with `Tab`
 - or even deleting text from its applicable to span

**Comment by Peter-Juhasz** [comment]
(Most likely it is the correct behavior, when an IntelliCode session is active, just an observation: it blocks Copilot inline suggestions to trigger in the whole file while being stuck at one location.)

**Comment by Neme12** [comment]
This has happened to me too once, and I had to restart VS.

**Comment by CyrusNajmabadi** [comment]
IntelliCode is not Roslyn.  please file an issue on developercommunity, thanks :)
