### ISSUE TITLE
Bring back MetadataReference.CreateFromAssembly

### ISSUE THREAD

**Issue by FajarMerahDiwangkaraDeveloper** [dotnet/roslyn#75409]
I'm currently using Roslyn inside Unity to perform script analysis. I'm using IL2CPP backend for my Unity project. I add mscorlib references to my CSharpCompilation using MetadataReference.CreateFromFile(Assembly.Load("mscorlib").Location) as argument to AddReferences method. It works in unity editor, but not after i built the project. And the reason why it didn't work after i built the project is simple: mscorlib.dll does not exist. Unity, through some magic, added mscorlib without mscorlib.dll . 

![mscorlib not found](https://github.com/user-attachments/assets/d1ccf950-c88d-424f-a27f-9ee87e200893)

Now, without mscorlib.dll, what am i supposed to do? I tried using MetadataReference.CreateFromAssembly, but it throws obsolete error which made my unity didn't want to run because there is error thrown in the console.

![unity createfromassembly error](https://github.com/user-attachments/assets/053276ae-f7dc-4c09-a861-b588f105b734)

This shows a clear flaw in Roslyn design. Just because an assembly exist, does not mean the assembly file exist. Without MetadataReference.CreateFromAssembly, now i didn't know how to create metadatareference for assembly that did not have a file. Please bring back MetadataReference.CreateFromAssembly.

Edit: i'm using roslyn version 3.11.0, because unity is still stuck at C#9 so newer version of roslyn won't work with unity. Please bring back MetadataReference.CreateFromAssembly not only for newer version of roslyn but also for older version of roslyn, especially version 3.11.0

**Comment by jjonescz** [comment]
Instead of referencing the real DLLs, you can use https://github.com/jaredpar/basic-reference-assemblies

**Comment by FajarMerahDiwangkaraDeveloper** [comment]
> Instead of referencing the real DLLs, you can use https://github.com/jaredpar/basic-reference-assemblies

Thanks for the reply. I tried adding that library to Unity and got this error
![image](https://github.com/user-attachments/assets/5a6c4085-d39c-4d38-a2d3-6d5db28405f9)

The library needs roslyn version 4.11.0, while the version of roslyn i use is 3.11.0. Unfortunately, i cannot upgrade roslyn version because unity is still in C#9, and according to https://github.com/dotnet/roslyn/blob/main/docs/wiki/NuGet-packages.md, roslyn version 4 and above include C#10 or above.

And also my compilation need to reference UnityEngine and Unity module. While UnityEngine itself have a dll, Unity did not, so i don't know how to modify that library to add Unity module. Unity module can be referenced and used inside script, but cannot be loaded manually using Assembly.Load (unity magic working once again). Below is error message trying to run Assembly.Load("Unity").Location
![image](https://github.com/user-attachments/assets/7badf87a-9413-4abb-9d7f-9b8cb2800479)

**Comment by FajarMerahDiwangkaraDeveloper** [comment]
I just read the metadatareference.createfromassembly source code and it was reading the assembly file, i thought it can read loaded assembly that did not have a file, my bad. https://github.com/dotnet/roslyn/blob/9934fb9e3527e1c0c51314e57d4aab30f97e8f9e/src/Compilers/Core/Portable/MetadataReference/MetadataReference.cs#L350

Im closing this, sorry.
