### ISSUE TITLE
[Code refactor proposal] Split/merge multiple attributes into/from separate attribute lists

### ISSUE THREAD

**Issue by Rekkonnect** [dotnet/roslyn#75411]
## Summary

Code refactors that convert between multiple attributes in a list and multiple attribute lists into a single attribute list

## Details

The proposed refactors are the following:
- provided on attribute lists that contain multiple attributes, splitting them into multiple attribute lists, each with one attribute, with the following options:
  - only split attributes that have constructor arguments
  - split all attributes
- provided on the attribute list collection of the declared symbol, merging the attributes into one attribute list with the following options:
  - only merge attributes that have no constructor arguments
  - merge all attributes

## Examples

```csharp
[A, B, C, D(1), E]
[F]
[G, H]
public class C;
```

The proposed attribute list splitting refactoring will be available within each attribute list that contains more than one attributes, resulting in the following code:

- split all attributes
```csharp
// Only fixes the selected attribute list, in this case [A, B...]
[A]
[B]
[C]
[D(1)]
[E]
[F]
[G, H]
public class C;
```

- only split attributes that have constructor arguments
```csharp
[A, B, C, E]
[D(1)]
[F]
[G, H]
public class C;
```

For attribute merging, the inverse process will be applied.

**Comment by balogun14** [comment]
@Rekkonnect can i work on this

**Comment by Rekkonnect** [comment]
Sure thing

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of movement.
