### ISSUE TITLE
IDE0300 Collection Initialization for Static Readonly Array Infinite Logic Loop

### ISSUE THREAD

**Issue by midahenshaw** [dotnet/roslyn#75436]
**Version Used**: 

Which ever Visual Studio 17.11.4 uses by default. Really need a clean method to obtain this from the About dialog!

**Steps to Reproduce**:

1. Rosyln will recommend refactoring the following code:
```
public static class Helper
{
    private static readonly char[] InvalidChars = new char[] { '1', '2', '3', '4', '0', '=', '+', '_', '-' };
}
```

2. Into this refactored code:
```
public static class Helper
{
    private static readonly char[] chars = new char[] { '1', '2', '3', '4', '0', '=', '+', '_', '-' };
    private static readonly char[] InvalidChars = chars;
}
```

3. Roslyn will then recommend refactoring the second code example into this code:
```
public static class Helper
{
    private static readonly char[] chars1 = new char[] { '1', '2', '3', '4', '0', '=', '+', '_', '-' };
    private static readonly char[] chars = chars1;
    private static readonly char[] InvalidChars = chars;
}
```

4. This will go on forever and ever.

**Diagnostic Id**:

IDE0300

**Expected Behavior**:

Do not suggest this refactoring at all.

**Actual Behavior**:

Keeps recommend to change the refactoring forever after the factoring was changed.

**Comment by CyrusNajmabadi** [comment]
I'm a bit confused IDE0300 is 'use collection expression'.  Can you show a picture of what you're experiencing?  Thanks!

**Comment by midahenshaw** [comment]
Sorry, it is Collection Initialization Can Be Simplified. Had something similar related to array initialization.

**Comment by midahenshaw** [comment]
![IDE0300](https://github.com/user-attachments/assets/c7d5f65d-ecd5-4756-ad7a-5aead1dcf186)

Visual Studio 17.11.4 Refactoring recommendation.

**Comment by CyrusNajmabadi** [comment]
You are choosing the 'introduce field' refactoring there.  That's just a general refactoring available on lots (most) expressions.  The collection can be simplifeid means you can replace that with `char[] chars = ['a', 'b', 'c']`:

![Image](https://github.com/user-attachments/assets/1ec9bad5-41a7-41a2-ada9-23816f18f799)
