### ISSUE TITLE
Migrate the target framework in our builds

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#75453]
Now that `main` is 17.13 and .NET 9 is hitting RTM it's time to update the target frameworks used in our build. 

Specifically in [TargetFramework.props](https://github.com/dotnet/roslyn/blob/main/eng/targets/TargetFrameworks.props). 

- `$(NetRoslyn)` should be net9.0
- `$(NetRoslynAll)` should be net8.0 and net9.0

For the moment `$(NetRoslynNext)` should remain `net9.0` if possible as we won't have a real `net10.` target for a few more months. 

Other items: 

- Make sure to check for `#if NET7` style directives that can be moved forward.
- Likely requires us to change YML files in a few places.
- The `NetVSShared` can likely move to simply `net8.0` now but we should check with IDE that they don't need `net7.0` in VS Code anymore

**Comment by jjonescz** [comment]
> * Make sure to check for `#if NET7` style directives that can be moved forward.

Why would these need to move forward? I think they will still work, and it seems more resilient to let them be.

**Comment by jaredpar** [comment]
When people see `#if NET7` in code but no `net7.0` in the TFM list then there is a tendency to ask "wait, is that stale? can we remove that?" Hence I like to roll them forward to make sure that we still need them and to make it clearer to readers that they are intended.
