### ISSUE TITLE
record `with` lowering is uninutitive and unexpected

### ISSUE THREAD

**Issue by aradalvand** [dotnet/roslyn#75452]
The lowering of `recordInstance with { Prop = "some new value" }` is bad.

Given this — here's [the sharplab](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAICYCMBYAUHgNwEMwACAU01IF5SpyB3UgZQHsBbcgUTDFbAAUADRClMABhikAmqPTiAlAG5CJCuhp1GLDt179hogMySKmAHTTleVJgCcA8unMBZcgGd3RAOblr+XFQjUiIAI3dgMCIAY2BSMHJo/jhSHj5BW3FSN08fPxVA4ISksBS2TjSDAEsoOKEpGrirUlFKwQASACJyfTJOXN9SAHIAbyEAXyHSAFphkelJzv8gA=):
```cs
using System;

var e1 = new SomeError(X: 10, Y: 20);
var e2 = e1 with { X = 30 };
Console.WriteLine(e2.Message);

public abstract record Error(string Message);
public record SomeError(int X, int Y) : Error($"error message '{X}' - '{Y}'");
```
I'd expect `error message '30' - '20'` to be printed to the console, but `error message '10' - '20'` is instead.
Surprising.

I would expect the above code to be equivalent to:
```cs
using System;

var e1 = new SomeError(X: 10, Y: 20);
var e2 = new SomeError(X: 30, e1.Y);
Console.WriteLine(e2.Message);

public abstract record Error(string Message);
public record SomeError(int X, int Y) : Error($"error message '{X}' - '{Y}'");
```
But it's not, because the cloning mechanism does not utilize the constructor.

**Expected Behavior**:
Clone such that the values go through the constructor, that's the only lowering that yields the most inutitive/expected result.

**Comment by CyrusNajmabadi** [comment]
The compiler is behaving as the language is spec'ed.  'with' goes and clones the object, only changing the properties you request. That's all. If you want that to change, please open a discussion at dotnet/csharplang.
