### ISSUE TITLE
Mac is failing with "Only one project can be specified"

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#7548]
PR: [#7541](https://github.com/dotnet/roslyn/pull/7541) *Properly add a using for an extension method when another, incompatible, one is in scope already.* by @CyrusNajmabadi
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_mac_dbg_unit32/2069/

**Issue 1: MSBuild Error**
error MSB1008: Only one project can be specified.

**Comment by davkean** [comment]
Looks like mic-mac-bld-3 is broken right now. @mmitche

**Comment by davkean** [comment]
Or rather our scripts are broken on mic-mac-bld-3 due to the spaces in the volume name.

**Comment by mmitche** [comment]
I think this is likely a result of spaces that were in the workspace path.  I am working to fix this.

Sent from my Windows Phone
________________________________

**Comment by mmitche** [comment]
I took them both offline.  I will softlink the home dir to the external HD workspace due.

Sent from my Windows Phone
________________________________

**Comment by davkean** [comment]
We could just fix the cibuild.sh to quote the right paths.

**Comment by mmitche** [comment]
That's okay.  Cli had other problems that may time to fix

Sent from my Windows Phone
________________________________
