### ISSUE TITLE
New files, members are not recognized after git pull

### ISSUE THREAD

**Issue by Peter-Juhasz** [dotnet/roslyn#75495]
**Version Used**: 17.12 P2.1 with no extensions enabled

**Steps to Reproduce**:

1. Somebody pushes changes
2. Pull changes

New files and added/changed members are not recognized:

![Image](https://github.com/user-attachments/assets/e354a463-59a6-489e-b367-3d00e37ccb34)

The new files are not even visible in Solution Explorer, although they are there in the file system:

![Image](https://github.com/user-attachments/assets/33b4876c-ed02-4f61-8eef-e5946f29372c)

The project is a standard class library:

```msbuild
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="*" />
    <PackageReference Include="System.Linq.Async" Version="*" />
  </ItemGroup>

</Project>
```

(Content of one of the missing files:)

![Image](https://github.com/user-attachments/assets/18e14f63-d70c-4bb4-9736-0c99180c8f7e)

(Code successfully compiles on the build server.)

**Additional information**

`AccelerateBuildsInVisualStudio` is enabled.

```msbuild
<Project>
	<PropertyGroup>
		<AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
		<EnableNETAnalyzers>true</EnableNETAnalyzers>
	</PropertyGroup>
</Project>
```

**Workaround**

- Build doesn't solve the issue
- Restarting Visual Studio doesn't solve the issue
- Solution rebuild sometimes does

This issue makes work quite difficult if more than 1 people work on a project.

**Comment by CyrusNajmabadi** [comment]
Populating solution explorer is not a Roslyn issue. This sounds like CPS or msbuild issue.

**Comment by Peter-Juhasz** [comment]
Neither Visual Studio Solution Explorer (nor Code Search), (although files are available in the file system) nor Roslyn/IntelliSense picks up the changes after a git pull. I was not sure about the layering here, whether Roslyn access the file system directly or only via Visual Studio Project System, and since it is broken, the issue bubbles up.

**Comment by CyrusNajmabadi** [comment]
We only know about the files the project system tells us about. It's for them ma msbuild to interpret the project file, and then determine if new files should now be included.

**Comment by Peter-Juhasz** [comment]
I've found a matching issue here:
https://developercommunity.visualstudio.com/t/Visual-Studio-shows-outdated-errors-when/10761617

Although it has already got the infamous "Needs more info" state, I added a comment there referencing this issue.

**Comment by Peter-Juhasz** [comment]
We tried disabling `AccelerateBuildsInVisualStudio` since then, but it did not help.

**Comment by CyrusNajmabadi** [comment]
Can you add any information to the developer community issue. This will have to be investigated by project system.
