### ISSUE TITLE
LightBulb Preview buffer leaks via LSP

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#75492]
When you open a LightBulb preview, DiagnosticsReactingDocumentoperationListener.DocumentOpened is getting called for the buffer that contains the preview text (even two because it's a diff?)

However I'm not seeing the DocumentClosed called for these buffers, which results in a pretty bad memory leak

![Image](https://github.com/user-attachments/assets/bb4161c6-6437-4f30-b75d-a4e7660180f2)

![Image](https://github.com/user-attachments/assets/7dfcea93-ca7a-47bc-ac83-41e6fcd9f403)

**Comment by KirillOsenkov** [comment]
This is pretty impactful, we're leaking quite a lot on every lightbulb preview invocation.

We should also check other scenarios where we show buffers: Peek, diff, debugger textboxes, output window (?), etc

**Comment by dibarbet** [comment]
Had a quick chat with Kayle, we may need to set the content type back to inert to signal features to unhook from it.

**Comment by KirillOsenkov** [comment]
yup, that should do the trick
