### ISSUE TITLE
? : with Byte* causes Invalid Program with Optimize+

### ISSUE THREAD

**Issue by markhurd** [dotnet/roslyn#7550]
I was glancing at another bug report (regarding ?. with a Byte*) that I can't find now and I adjusted the code (in LinqPad) to get it to compile and it threw InvalidProgramException.

I tried with Optimize- and it works fine. Looking at the IL, the optimized version clearly "forgets" to pop the unused value on the stack.

    //Straight from C# Program in LinqPad:
    void Main()
    {
        unsafe
        {
            var x = new A();
            byte* ptr = (x == null) ? null : x.Ptr;
        }
    }
    
    // Define other methods and classes here
    public class A
    {
        public unsafe byte* Ptr;
    }

The optimised IL displayed by the same program:

    IL_0000:  newobj      UserQuery+A..ctor
    IL_0005:  stloc.0     // x
    IL_0006:  ldloc.0     // x
    IL_0007:  brfalse.s   IL_0011
    IL_0009:  ldloc.0     // x
    IL_000A:  ldfld       UserQuery+A.Ptr
    IL_000F:  pop         
    IL_0010:  ret         
    IL_0011:  ldc.i4.0    
    IL_0012:  conv.u      
    IL_0013:  ret         
    
    A..ctor:
    IL_0000:  ldarg.0     
    IL_0001:  call        System.Object..ctor
    IL_0006:  ret         

IMHO There should be a pop after IL_0012.

This is with LinqPad v5.03.07 and as I mentioned at http://stackoverflow.com/q/32665389/256431 I don't have a simple way to confirm the C# compiler version used, but I do know it is Rosyln-based.

**Comment by chrisaut** [comment]
I can reproduce this with VS2015 Update 1
Unhandled Exception: System.InvalidProgramException: JIT Compiler encountered an internal limitation.

**Comment by leppie** [comment]
This is problematic in master too.

PEVerify result:
```
[IL]: Error: [d:\roslyn\roslyn\dt.exe : A::Main][offset 0x00000015][found unmanaged pointer][expected unmanaged pointer] Unexpected type on the stack.
[IL]: Error: [d:\roslyn\roslyn\dt.exe : A::Main][offset 0x00000014] Non-compatible types on stack depending on path.
```
PEVerify result with /o+:
```
[IL]: Error: [d:\roslyn\roslyn\dt.exe : A::Main][offset 0x00000013] Stack must be empty on return from a void function.
```

Also with `/o+`, an assertion fails in `ILBuilderEmit.cs:101`.

**Comment by leppie** [comment]
I found the issue, and created a PR.
