### ISSUE TITLE
c# 6 null-conditional operator doesn't work for await statement

### ISSUE THREAD

**Issue by Misterhex** [dotnet/roslyn#7556]
`var body = await request.Content?.ReadAsStringAsync();`

throw an `nullreferenceexception` when when request.Content is null instead of just returning null.

Is this an intended behaviour?

**Comment by ufcpp** [comment]
https://github.com/dotnet/roslyn/issues/7171

**Comment by gafter** [comment]
Yes, it is intentional behavior that awaiting null results in a null reference exception.

**Comment by Mardoxx** [comment]
>Yes, it is intentional behavior that awaiting null results in a null reference exception.

That sucks.

I wanted to do something like this:

```csharp
var graphClient = new GraphServiceClient(_authProvider);
var users = await graphClient.Users.Request().GetAsync();

do
{
    foreach (var user in users)
    {
        Console.WriteLine($"{user.Id} : {user.GivenName} {user.Surname}");
    }
}
while ((users = await users.NextPageRequest?.GetAsync()) != null);
```

I guess
```csharp
while (users.NextPageRequest != null && (users = await users.NextPageRequest.GetAsync()).Count > 0);
```
isn't as bad...

**Comment by CyrusNajmabadi** [comment]
Proposal on a language change to address htis is here: https://github.com/dotnet/csharplang/issues/35
