### ISSUE TITLE
What do you mean lack of feedback? I'm here!! :)

### ISSUE THREAD

**Issue by dave-yotta** [dotnet/roslyn#75575]
> Closing due to lack of feedback. 

 _Originally posted by @CyrusNajmabadi in [#44592](https://github.com/dotnet/roslyn/issues/44592#issuecomment-2427605704)_

Sorry I have no other way to respond to this!

**Comment by CyrusNajmabadi** [comment]
Lack of feedback here means we haven't gotten enough reports of this to want to change the behavior. So we are sticking with the current behavior.

Thanks :-)
