### ISSUE TITLE
IDE0058 / IDE0029 does not handle multiple discards when at least one is from a parameter

### ISSUE THREAD

**Issue by JohanRoss** [dotnet/roslyn#75599]
**Version Used**: 
VS 2022 ver 17.12.0 preview 3.0

**Steps to Reproduce**:

1. Create a method with an input parameter that is discarded with underscore.
2. Inside the method call some function/method, without assigning its return value to anything. (Make sure the return type is something else than the discarded input parameter typ, e.g. one is int and the other is string).
3. Note how IDE0058: "Expession is never used" pops up, and a suggested fix is to use discard parameter "_". Apply this fix.
4. Note how IDE0029 "Cannot implicitly convert type 'int' to 'string'" now pops up.

```
    public static void DoSomething(string _)
    {
        _ = Convert.ToInt32("123", CultureInfo.CurrentCulture);
        _ = 123.ToString(CultureInfo.CurrentCulture);
    }
```
![Image](https://github.com/user-attachments/assets/21c4aeb8-8405-4731-bcba-3e417e43bb7b)

Multiple discards for varables of different types works fine when there is no parameter discard:
```
    public static void DoSomething()
    {
        _ = Convert.ToInt32("123", CultureInfo.CurrentCulture);
        _ = 123.ToString(CultureInfo.CurrentCulture);
    }

```
![Image](https://github.com/user-attachments/assets/f8b09a80-27cb-4578-b24e-0f9d30f29b56)

**Expected Behavior**:
Discards allowed to be of different types, even when they come from parameters to the method.

**Actual Behavior**:
Discards from input parameters can not be of different type than a discard variable in the method. (Gives IDE0029 error).

**Comment by CyrusNajmabadi** [comment]
This is a language issue, and woudl need to go through a discussion on dotnet/csharplang before we could do anything about it in the ide.  Currently the language disallows this.

**Comment by JohanRoss** [comment]
What a shame that this was closed. I mostly come across this in unit tests, where you have to pass TestContext to class init method.
"public static void MyClassInitialize(TestContext _) { }"... Will you bring it up for discussion on dotnet/csharplang as you mentioned?

**Comment by CyrusNajmabadi** [comment]
> What a shame that this was closed

As mentioned, this is a language issue. If the language relaxes here, then Roslyn can do something. 

Green free to start a discussion at dotnet/csharplang on this topic if you are passionate here.
