### ISSUE TITLE
`readonly` modifier recommended on non-fields inside non-struct types

### ISSUE THREAD

**Issue by Rekkonnect** [dotnet/roslyn#75625]
## Version Used
VS 2022 Version 17.11.5
Roslyn 4.11.0 (5649376e0e5f)

Project info
C# 12.0
.NET 8.0

## Steps to Reproduce

Use the following code:

```csharp
public sealed class C
{
    public $$ string Property { get; set; }
}
```

Place the caret at `$$` and try typing `r`

## Expected Behavior

No `readonly` is recommended, since we are in a class and `readonly` cannot be used on non-field members of a non-struct type.

## Actual Behavior

The `readonly` keyword is recommended. This is a problem mainly because it now takes priority over `required`, which is a commonly used recommendation after having declared a property.

## Note

This also works on properties, events, methods and non-struct types themselves like classes, interfaces, delegates and enums.

**Comment by CyrusNajmabadi** [comment]
We don't look to the right as the user may be intending to add a new field before an existing member.  This is very much by design behavior.
