### ISSUE TITLE
Bulk "Use auto property" skips things that it can refactor individually

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#75634]
**Version Used**: 17.12 Preview 3.0

It seems to be an essential part of this particular repro that the fields have initializers.

Invoking "Use auto property" on B alone works:
![Image](https://github.com/user-attachments/assets/98f893b2-03ca-43b7-bd09-11dbe3820e4a)

But any of the "Fix all in" options skip it:
![Image](https://github.com/user-attachments/assets/42182e1f-b158-4186-b97c-dae107552a17)

Generally it seems to skip every other property.

Repro source:

```cs
using System;

public sealed class SomeViewModel
{
    private bool a = true;
    public bool A { get => a; set => Set(ref a, value); }

    private bool b = true;
    public bool B { get => b; set => Set(ref b, value); }

    private bool c = true;
    public bool C { get => c; set => Set(ref c, value); }

    private void Set<T>(ref T field, T value) => throw new NotImplementedException();
}
```

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

</Project>
```

**Comment by Rekkonnect** [comment]
I've seen this same behavior on other refactors (can't remember which ones), where the middle ones are not actually fixed, and the user has to do a second (or even third) round of fixes

**Comment by CyrusNajmabadi** [comment]
Mentioned offline. This is due to using the batch fixer. We either need a dedicated fixer here, or we need the batch fixer to be better about edits that abut.
