### ISSUE TITLE
Old Unresolved Issues Closed and Locked: Is This the Right Approach?

### ISSUE THREAD

**Issue by Varorbc** [dotnet/roslyn#75638]
@CyrusNajmabadi 

Hey there, I noticed you've been closing some really old issues lately that were never actually resolved. A lot of these problems might still be happening, and now they're locked so no one can comment on them. Is this really the right way to go about it?

**Comment by CyrusNajmabadi** [comment]
The issues were closed with the reason why. Including if they aren't things were going to be investing in anymore, or which we haven't heard enough feedback on to do something about given the resources we have available.

**Comment by huoyaoyuan** [comment]
I disagree with the action of locking the issues immediately. Sometimes we would want to argue about the reason.
