### ISSUE TITLE
Empty lines removal  1,2,3,4,

### ISSUE THREAD

**Issue by Mupli** [dotnet/roslyn#75656]
## Is your feature request related to a problem? Please describe.
Ex. I'm always frustrated when reformat code via shortcut but empty lines are not removed. Java has it done so well. prettier too (in other languages)!

## Describe the solution you would like
omnisharp formatter doesn't remove lines in cases like lambdas and overall in code. 
So I need for 2 cases: 
1.  should remove empty line and add indent  so arrow and method should be in one line.

Before: 
``` 
void LambdaMethod()
=>
<empty line> 
this.DoSomething()
```
After:
``` 
void LambdaMethod() => this.DoSomething()
```
v2:
``` 
void LambdaMethod() 
     => this.DoSomething()
```
(Both should be supported)

2. remove in code empty lines 
Before: 
```
DoSomething()
<empty line> 
<empty line> 
<empty line> 
DoSomething2()
```
After: 

```
DoSomething()
<empty line> 
DoSomething2()
```

Sadly there is no option for that. 
https://learn.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.csharp.formatting.csharpformattingoptions?view=roslyn-dotnet-4.9.0

**Comment by CyrusNajmabadi** [comment]
Closing out as we have a feature for one of these cases, and that is the extent of support we intend to add.
