### ISSUE TITLE
QuickAction for making a class Public or adding Static

### ISSUE THREAD

**Issue by AkashGutha** [dotnet/roslyn#7567]
As the VS starts and class that the user creates is by default marked doesn't have any **access modifier** so the user goes in directly types up his variables.
suppose he types in a **Public variable** the error showed up is that the _Class_ is less accessible than the _property_ which cannot be.
so it's good to make an Analyzer that can detect such issues and give a quick action to turn the class into **Public** or even it can be extended to **static**

**Comment by CyrusNajmabadi** [comment]
We have added a feature to automatically add accessibility modifiers to a type.  Adding/removing static seems to be of fairly marginal value.  Closing out.
