### ISSUE TITLE
C# Source Generator - The JSON-RPC connection with the remote party was lost before the request could complete.

### ISSUE THREAD

**Issue by Phylum123** [dotnet/roslyn#75679]
**Version Used**: Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.11.5

Every time my source generator is automatically run by visual studio, AFTER the initial run at startup, it produces the crashes of the systems in the image below (there are more crashes, just can't fit more in the image). The error inside each of them is the same, and is also below. Outside of that, the source generator works and produces the correct code, until the system crashes happen.

![Image](https://github.com/user-attachments/assets/984566f6-03ea-49f2-8c3a-097488760d2e)

StreamJsonRpc.ConnectionLostException : The JSON-RPC connection with the remote party was lost before the request could complete. ---> System.OperationCanceledException : The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at async StreamJsonRpc.MessageHandlerBase.WriteAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async StreamJsonRpc.JsonRpc.SendAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async StreamJsonRpc.JsonRpc.InvokeCoreAsync(<Unknown Parameters>)
   --- End of inner exception stack trace ---
   at async StreamJsonRpc.JsonRpc.InvokeCoreAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.TryInvokeAsync[TService,TResult](<Unknown Parameters>)

**Expected Behavior**:
Do not crash these vs systems when my source generator runs

**Actual Behavior**:
The vs systems crash

**What I have tried:**

I found a post with a similar issue and followed these instructions to the letter (including updating windows, etc). It did not work:

Hello [@Starfall Conquer ](https://learn.microsoft.com/users/na/?userid=92db66f4-87c4-484e-9216-ee1a0f38479b),

Welcome to Microsoft Q&A forum.

I suggest first try cleaning VS cache(rename ComponentModelCache folder(s) in C:\Users\username\AppData\Local\Microsoft\VisualStudio\17.0_xxxxxxxx folder), and then reset VS(run devenv /ResetSettings command in Developer Command Prompt For Visual Studio 2022) => run Visual Studio as administrator.

Sometimes, updating Windows OS or uninstalling Newtonsoft.Json assembly file(run gacutil -u Newtonsoft.Json in command prompt) works.

**Comment by CyrusNajmabadi** [comment]
@ToddGrun fixed by your cancellation token capture fix?

**Comment by Phylum123** [comment]
This is still ongoing. Anyone have any clue as to what the problem is?

**Comment by CyrusNajmabadi** [comment]
@Phylum123 We need more details.  Can you provide your project so we can try to repro this?  And what version of VS are you on?  Our fixes went into the latest VS 17.12 previews.  Are you seeing the same issue there?

**Comment by Phylum123** [comment]
After installing the preview version, even the regular version is working better. However, if there is a runtime exception in your source generator, it will cause the same crashes.

**Comment by CyrusNajmabadi** [comment]
Closing out.  That sounds like another issue.  And we would assign that to compiler to deal with.

**Comment by mwwhited** [comment]
This issue me still persists.  Is there a way to turn on additional feedback of telemetry is sent in when these errors pop up? Once these error show intellisense, code completion, refactoring, and code navigation stop working.  It really limits how fast one can get work done.

**Comment by CyrusNajmabadi** [comment]
@mwwhited these issues are already reported to us through telemetry.  If you're hitting a new issue, please open a bug, with a stack, so we can investigate.  Thanks.
