### ISSUE TITLE
Show autocompletion for implementing the methods of an interface that have default implementations

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#75689]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Show-autocompletion-for-implementing-the/10778876)._

---
Assuming an interface as default method implementations, when implementing this interface in a new class the methods with the default implementation are not scaffolded, which is expected. However I'd like to have a gesture to list these methods as I can still implement them.

Example:

The following interface has 3 methods with a default implementation.

![image.png](https://aka.ms/dc/image?name=B0a36fbd655fe48ef827a612e4c5d9e85638658293746267583_20241029-130935-image.png&tid=0a36fbd655fe48ef827a612e4c5d9e85638658293746267583)

If I create a new class implementing this interface:

![image.png](https://aka.ms/dc/image?name=Be69413051ba64ea4bf267fe069c84e21638658294581976299_20241029-131059-image.png&tid=e69413051ba64ea4bf267fe069c84e21638658294581976299)

Doing CTRL + . on the interface won't generate the code for these methods, because they have a default implementation. And it's ok.

But I'd like to be able to type something that will show me a list of methods I can still implement. The same way as when you start typing `override` from a base class it shows the methods you can actually override.

As an example if I type the name of the base interface them `.` it could show it. Or if I type `implement`, or CTRL + '.'. Just a few ideas.

---
#### Feedback Bot on 10/29/2024, 10:45 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further. You will hear from us in about a week on our next steps.</p>

**Comment by CyrusNajmabadi** [comment]
@Rekkonnect does your pr handle this?

**Comment by Rekkonnect** [comment]
Yes, #75568 now follows the behavior of override and helps discover the implementable interface members

**Comment by Rekkonnect** [comment]
@CyrusNajmabadi the PR was merged, and it seems that we also cover the other part of the issue about providing suggestions for members with default implementations. Check the tests `ExplicitInterfaceMember_03` and `ExplicitInterfaceMember_04` in `ExplicitInterfaceMemberCompletionProviderTests`. I think this is safe to close now as completed.

**Comment by sebastienros** [comment]
Is there a way for me to test it? (OP)

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/75568

**Comment by CyrusNajmabadi** [comment]
@sebastienros if you follow the instructions at https://github.com/dotnet/roslyn/blob/main/docs/contributing/Building%2C%20Debugging%2C%20and%20Testing%20on%20Windows.md#trying-your-changes-in-visual-studio to build and test out our latest bits.  You'll need to be running the latest VS public preview.
