### ISSUE TITLE
Searching for References should have a simply UI button that excludes references from unit test projects

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#75685]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Searching-for-References-should-have-a-s/10766357)._

---
Many times I want to see what production code is referencing a particular method.   When I do so, I only want to see references from other production code, not unit tests.   But not always, sometimes I want to see both.   It would be good to be able to have a filter to filter out unit-test projects.

---
#### Feedback Bot on 10/10/2024, 11:25 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further. You will hear from us in about a week on our next steps.</p>

**Comment by CyrusNajmabadi** [comment]
Closing as external.  This would be for platform and unit testing team to hash out.  Roslyn provides the items with  info about what proejcts tjhey are in already.  @shyamnamboodiripad and @peterwald if you guys want to do anything here.
