### ISSUE TITLE
Comment option in the settings in VS VB

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#75686]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Comment-option-in-the-settings-in-VS-VB/10757097)._

---
In the settings "Name", "Type", "Range", "Values" there should be another column: "Comment".
Since the settings file (config) is an XML file, it should not be a problem to include this option.

In the settings "Name", "Type", "Range", "Values" there should be another column: "Comment".
Since the settings file (config) is an XML file, it should not be a problem to include this option.

---
#### Feedback Bot on 10/3/2024, 06:07 AM: 

<p>Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by CyrusNajmabadi** [comment]
This is not Roslyn.   We don't own editing the config/settings xml files
