### ISSUE TITLE
All Quick Actions should have assignable shortcuts

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#75693]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/All-Quick-Actions-should-have-assignable/10777185)._

---
Only some of Quick Actions have an assignable shortcut (i.e. Extract interface), many of them don’t (Move type to X.cs, Generate constructor). I believe all actions available under Alt+Enter menu should have their own shortcut, even if disabled by default.

The according github entry https://github.com/dotnet/roslyn/issues/67413 (https://developercommunity.visualstudio.com/t/All-Quick-Actions-should-have-assignable/10203590) was closed but I don't understand why and I can't comment there so I need to restart a new thread to ask why it has been closed.

---
#### Feedback Bot on 10/27/2024, 10:50 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further. You will hear from us in about a week on our next steps.</p>

**Comment by CyrusNajmabadi** [comment]
Closing out as external.  Platform has considered a way of doing htis (along with searching forlightbulb members easily).  we would just piggy back off of that.
