### ISSUE TITLE
Suggested changes to VS2022 shortcuts (highly recommended)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#75691]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Suggested-changes-to-VS2022-shortcuts-h/10762319)._

---
I strongly recommend abolishing the Visual Studio rule that requires "if the selected content is at the beginning of a line, it must be a line comment." In my development work, I rarely use line comments; I almost exclusively use block comments. However, every time I try to comment out a selected area with a block comment, Visual Studio automatically converts it to a line comment! No matter how I change the shortcut keys, it doesn’t work!

Here’s an example:

struct Node {
    int data;
};
Whenever I select this entire section, it forcefully changes the comment to a line comment, and it looks like this:

//struct Node {
//    int data;
//};
This is extremely frustrating and severely affects my development efficiency! What I need is:

/*struct Node {
    int data;
};*/
Please consider my suggestion seriously. I would greatly appreciate it if you could accept my proposal and modify this feature as soon as possible!

---
#### Feedback Bot on 10/7/2024, 11:42 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further. You will hear from us in about a week on our next steps.</p>

**Comment by CyrusNajmabadi** [comment]
Closing out as not planned.  It is intentional that we use `//` as it is the preferred form for the ecosystem and handles things like nesting commented regions (which `/* */` does not).
