### ISSUE TITLE
Compiler: thinks a local's type is that of another local

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#75710]
I'm seeing a recent regression in Csc, it wasn't there in `4.12.0-3.24463.9` but it is present in `4.12.0-3.24510.2` (Preview 5)

The symptoms are:
```
MetadataType.cs(411,36): error CS1061: 'IList<KeyValuePair<string, ulong>>' does not contain a definition for 'Attributes' and no accessible extension method 'Attributes' accepting a first argument of type 'IList<KeyValuePair<string, ulong>>' could be found (are you missing a using directive or an assembly reference?)
```

I can't find a standalone repro, but it looks like it thinks that a local's type is that of another local.

I can't share the repro publicly but ping me in private.

I think this is pretty bad.

**Comment by KirillOsenkov** [comment]
Oops, I missed that there was a warning:

warning CS9258: In language version preview, the 'field' keyword binds to a synthesized backing field for the property. To avoid generating a synthesized backing field, and to refer to the existing member, use 'this.field' or '@field' instead.

In the code snippet, there was a local named `field`.

My apologies, this is by design.

Thanks @cston for investigating.

**Comment by KirillOsenkov** [comment]
Oh, and that explains why I couldn't find a simple repro: in the simple project I didn't set the LangVersion preview.

**Comment by miloush** [comment]
ref: https://github.com/dotnet/csharplang/issues/140 https://github.com/dotnet/roslyn/issues/74937
https://github.com/dotnet/csharplang/blob/main/proposals/field-keyword.md

especially for breaking changes https://github.com/dotnet/csharplang/issues/7964

Why do we continue to allow `var field = x;` syntactically?

**Comment by CyrusNajmabadi** [comment]
@miloush for language questions, please submit them at csharplang. Thanks
