### ISSUE TITLE
Design: Figure out how to order add using versus generate versus fuzzy matches

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#7573]
We now have a bunch of code actions providers that give actions of varying levels of confidence/quality.  For example 'add using' might give a 'low confidence' spell checking fix, while 'generate member' might give a high confidence fix.  an example of this would be "_text".  The spell checker finds matches that can fix this, but the user really wanted to generate a member.

Right now there is no way to order actions (except at the provider level).  @dpoeschl and i think this might be doable with a simple 'confidence' value.  something like "Low/Medium/High".  All high actions go together, ordered by their provider, then medium, then low.

**Comment by Pilchie** [comment]
My concern here is how we would design the confidence levels.  I don't think it's as simple as exact matches versus fuzzy matches.

What if the only difference is case?  What if it's a very commonly misspelled word?  It seems like it will be hard to get right.

**Comment by CyrusNajmabadi** [comment]
Fixed with: https://github.com/dotnet/roslyn/pull/9296
