### ISSUE TITLE
Allow my source-generator to run before GeneratedRegex

### ISSUE THREAD

**Issue by ItaiTzur76** [dotnet/roslyn#75762]
I created [my ModularExpressions project](https://GitHub.com/ItaiTzur76/ModularExpressions) to allow the generation of regular expressions in compile-time using C# syntax. For example, the following code:
```cs
[GenerateModex(nameof(ThreeDigitsAndThenSomeModex))]
public static partial string ThreeDigitsAndThenSome();

private static Modex ThreeDigitsAndThenSomeModex => Beginning + Digit.Times(3) + AnyCharacterNotIn('a', NonWordCharacter);
```
results in the generation of:
```cs
public static partial string ThreeDigitsAndThenSome()
    => "^\\d{3}[^a\\W]";
```
This means that, although the regular-expression pattern `string` is generated at compile-time, it still has to be used for constructing a `Regex` object at runtime, which ruins that performance edge.
I would really love it if I could rephrase it as:
```cs
[GenerateModex(nameof(ThreeDigitsAndThenSomeModex))]
public static partial Regex ThreeDigitsAndThenSome();

private static Modex ThreeDigitsAndThenSomeModex => Beginning + Digit.Times(3) + AnyCharacterNotIn('a', NonWordCharacter);
```
and it could create the following instead:
```cs
[GeneratedRegex("^\\d{3}[^a\\W]")]
public static partial Regex ThreeDigitsAndThenSome();
```
That way, developers using my package can enjoy both readabilty and maintainability (by using C# syntax to create regular expressions) and the performance advantage the `GeneratedRegex` attribute offers.
Currently I cannot do it because my source-generator would generate source containing the attribute of another source-generator.
I suggest to allow a source-generator to specify before which *other* source-generators it should run, so that its output can be used as the input of those source-generators.

**Comment by CyrusNajmabadi** [comment]
It's an explicit and intentional design that there can be no visibility from one generator to another.

**Comment by ItaiTzur76** [comment]
> It's an explicit and intentional design that there can be no visibility from one generator to another.

@CyrusNajmabadi - I see there was [a similar request made](https://GitHub.com/dotnet/roslyn/issues/57239#issuecomment-2265961718) in which you wrote:
>Not planning to do anything now doesn't mean we won't do something in the future.

It looks like there is more and more demand for this inter-generator visibility. Perhaps the time is ripe to change the design to allow it? That would be legendary.

**Comment by CyrusNajmabadi** [comment]
No one has proposed a design that would be viable as of yet.  We learned the hard way that you can't just throw any solution at the problem (that was v1). It can be a disaster. You need a solution that works and scales. Absent a design that actually accomplishes that, we can't move forward here. 

In other words, we don't have a magic wand we can wave.  We're not doing this because we don't like the idea. We're not doing this because no one has any idea on how to do it viably.
