### ISSUE TITLE
Encapsulate field should preserve Unicode-escaped field names when possible.

### ISSUE THREAD

**Issue by brettfo** [dotnet/roslyn#7576]
_Issue filed on behalf of [this](https://github.com/dotnet/roslyn/pull/7540#discussion_r47952821) comment in a PR._

**Repro:**
Invoke encapsulate field on the following:

``` C#
class C
{
    int \u0061;
}
```

**Result:**
The backing field was renamed to `'a'`.  E.g.,

``` C#
class C
{
    int a;

    public int A
    {
        get
        {
            return a;
        }
        set
        {
            a = value;
        }
    }
}
```

but should keep its original name of `\u0061`.  E.g.,

``` C#
class C
{
    int \u0061;

    public int A
    {
        get
        {
            return \u0061;
        }
        set
        {
            \u0061 = value;
        }
    }
}
```

**Comment by CyrusNajmabadi** [comment]
Need info from ecosystem if this is actually an issue in practice.
