### ISSUE TITLE
Expose "IsGeneratedCode" on analysis contexts

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#7578]
PR https://github.com/dotnet/roslyn/pull/7526 adds support for analyzers to configure generated code analysis: analyzers can turn off reporting of diagnostics on generated code and/or turn off analyzer callbacks on generated code. Analyzer driver uses a heuristic to determine what code is generated code for analysis for this filtering.

We have received public requests (see https://github.com/dotnet/roslyn/issues/6998#issuecomment-165297425 and https://github.com/dotnet/roslyn/issues/6998#issuecomment-165451569) to expose this boolean flag on the relevant analysis contexts so that analyzers can do customized generated code analysis relying on driver's heuristic.

**Comment by 333fred** [comment]
Rather than a boolean, should this be using `GeneratedKind`?

**Comment by mavasani** [comment]
@333fred We (compiler and IDE team) discussed exposing the GeneratedKind enum and/or a custom generated code kind string, but were unsure if these are sufficient for various heuristic based ways to classify generated code kinds in the analyzer driver (GeneratedCodeAttribute, line hidden directives, file extensions, auto-generated comment, source generator generated, marked generated via editorconfig, etc.). Additionally, we may want to eventually expose even more fine grained generated code kind for some of these heuristic based approaches, such as proposal in #39758 to mark Razor generated files via a custom Type string inside auto-generated comment. This felt like too much of design work/overengineering, for something that doesn't seem too critical and non-blocking. We decided to expose just a simple bool for now and if/when we decide to expose more richer generated code kind information, we can always expose this additional data.

**Comment by 333fred** [comment]
@mavasani can we get a filled out proposal so this can go to API review?

**Comment by mavasani** [comment]
## Proposal

Expose the following set of public APIs on various analysis contexts:

```
Microsoft.CodeAnalysis.Diagnostics.CodeBlockAnalysisContext.IsGeneratedCode.get -> bool
Microsoft.CodeAnalysis.Diagnostics.CodeBlockStartAnalysisContext<TLanguageKindEnum>.IsGeneratedCode.get -> bool
Microsoft.CodeAnalysis.Diagnostics.OperationAnalysisContext.IsGeneratedCode.get -> bool
Microsoft.CodeAnalysis.Diagnostics.OperationBlockAnalysisContext.IsGeneratedCode.get -> bool
Microsoft.CodeAnalysis.Diagnostics.OperationBlockStartAnalysisContext.IsGeneratedCode.get -> bool
Microsoft.CodeAnalysis.Diagnostics.SemanticModelAnalysisContext.IsGeneratedCode.get -> bool
Microsoft.CodeAnalysis.Diagnostics.SymbolAnalysisContext.IsGeneratedCode.get -> bool
Microsoft.CodeAnalysis.Diagnostics.SymbolStartAnalysisContext.IsGeneratedCode.get -> bool
Microsoft.CodeAnalysis.Diagnostics.SyntaxNodeAnalysisContext.IsGeneratedCode.get -> bool
Microsoft.CodeAnalysis.Diagnostics.SyntaxTreeAnalysisContext.IsGeneratedCode.get -> bool
```

**NOTE:**
1. We discussed exposing `GeneratedKind` enum instead of a bool, but decided against it. The [comment above](https://github.com/dotnet/roslyn/issues/7578#issuecomment-1219208590) has more context
2. We would probably want a similar follow-up API addition on source generator contexts. I'll let Chris drive that forward.

**Comment by mavasani** [comment]
@333fred Thanks, I have filled up a proposal and marked it ready for review.

**Comment by 333fred** [comment]
### API Review

- Some users want to do something special for generated code, but only specific types. This gives an up-front check before doing a parse options check for specific generated code kinds.
- Should we add this to source generator contexts as well?
  - No requests for it now, but we could do it in the future.

**Conclusion**: Approved.
