### ISSUE TITLE
The tuple encounters a nullable inference error when using the LINQ expression FirstOrDefault

### ISSUE THREAD

**Issue by jnzhsh** [dotnet/roslyn#75797]
**Version Used**: 
Microsoft(R) Visual C# 编译器 版本 4.12.0-1.24379.11 (cf82d399)
版权所有(C) Microsoft Corporation。保留所有权利。
**Steps to Reproduce**:

1.  see following code
``` Csharp
        IEnumerable<(Guid, List<string>)> testCase = new List<(Guid, List<string>)>() { (Guid.Empty, Enumerable.Empty<string>().ToList()) };
        var nullableVeb = testCase.FirstOrDefault(x => x.Item1 == Guid.NewGuid()).Item2;
        Test(nullableVeb);
```
2.  the `nullableVeb ` should  nullable,but IntelliSense show it not null
 ![Image](https://github.com/user-attachments/assets/bb6869c5-8dc3-4f50-b078-0fed5fd19f63)

**Expected Behavior**:
nullableVeb may be null here

**Actual Behavior**:
nullableVeb is not null here

**Comment by chrisoverzero** [comment]
The default value of a type is not always `null`. The method `FirstOrDefault` will return the default value of a type when the predicate does not match any element of the collection. The syntax `(1, 2)` creates a value of type `ValueTuple<T1, T2>`. Any value of type `ValueTuple` (and types similar to it, such as `ValueTuple<T1, T2>`) is a _value type_, which means that its default value is not `null`. This is similar to how `default(int)` has a value of `0`, not a value of `null`.

```c#
int[] collection = [1, 2, 3, 4, 5];
var element = collection.FirstOrDefault(v => v >= 6);

Console.WriteLine(element == null); // ==> False
Console.WriteLine(element == 0);    // ==> True
```

If "first or `null`" is the behavior you want, there are packages on NuGet which can provide a `FirstOrNull` method for you to use.
