### ISSUE TITLE
OperationKind.MethodReferenceExpression and IMethodReferenceExpression not produced by the compiler in any circumstances.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#7584]
It appears as if this part of the IOperation API is simply unimplemented right now.  No bound nodes implement IMethodReferenceExpression, and there is no usage of OperationKind.MethodReferenceExpression at all.

This is needed for an IDE feature we want to build on IOperation (as well as just general completeness of the IOperation feature).

**Comment by CyrusNajmabadi** [comment]
tagging @brettfo and @JohnHamby 

Brett, i would still do your work, but just disable your tests for methods (and have a bug open about that).  Then, once this is implemented by IOperation, we can light up those tests as well.

**Comment by JohnHamby** [comment]
This was addressed awhile back, but I forgot to close this issue. As part of this, MethodReferenceExpression was renamed to MethodBindingExpression, and occurs in delegate creation. Normal method invocation does not produce an expression for the method reference, but one can get it from the invocation expression.
