### ISSUE TITLE
Convert to Generated RegEx mangles Constants

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/roslyn#75866]
**Version Used**: 
17.11.5

**Steps to Reproduce**:

Use this code:
```
        const RegexOptions MyOptions = RegexOptions.Compiled | RegexOptions.IgnoreCase;

        static Regex RX = new("asdf", MyOptions);
```

And apply the fixer.  You now have the following:
```
        const RegexOptions MyOptions = RegexOptions.Compiled | RegexOptions.IgnoreCase;

        static Regex RX = MyRegex();
        
        [GeneratedRegex("asdf", RegexOptions.IgnoreCase | RegexOptions.Compiled, "en-US")]
        private static partial Regex MyRegex();
```

You'll notice that the constant, ```MyOptions```, is not used in the generated regex but is now expanded.

**Expected Behavior**:
I should get this code:
```
        const RegexOptions MyOptions = RegexOptions.Compiled | RegexOptions.IgnoreCase;

        static Regex RX = MyRegex();
        
        [GeneratedRegex("asdf", MyOptions, "en-US")]
        private static partial Regex MyRegex();
```

**Actual Behavior**:
```MyOptions``` is not used in the generated code.

**Comment by CyrusNajmabadi** [comment]
What fixer are you referring to?

**Comment by TonyValenti** [comment]
The "convert to generated regex" fixer.

**Comment by CyrusNajmabadi** [comment]
I don't see any such fixer in Roslyn itself.  Do you have a diagnostic ID for it @TonyValenti ?

**Comment by TonyValenti** [comment]
Here's what I see in VS:
![Image](https://github.com/user-attachments/assets/8f202152-dcdf-4691-ae5b-e6a6f848dce2)

Do I need to post this somewhere else?
