### ISSUE TITLE
Extend the "Use collection expression" suggestion to scenarios requiring the spread operator

### ISSUE THREAD

**Issue by obonn1** [dotnet/roslyn#75870]
## Summary

Expand the Roslyn analyzers to suggest using `[.. collection]` syntax where applicable. This is a more concise and expressive way to initialize collection from elements in existing collections.

## Background and Motivation

The IDE currently suggests collection initialization when a spread operator wouldn't be required. The motivation for this feature is the same as the existing suggestions, informing developers of the existence of a more readable syntax. Notably, ReSharper already suggests using collection expressions in these situations. Adding this feature directly to Roslyn would ensure consistency and improve native support for modern C# practices.

## Proposed Feature

Before:
``` cs
List<int> GetNumbers()
{
    return new List<int>(Enumerable.Range(1, 10));
}
```
After:
``` cs
List<int> GetNumbers()
{
    return [.. Enumerable.Range(1, 10)];
}
```

Before:
``` cs
ImmutableArray<string> GetFormattedNumbers(ImmutableArray<int> numbers)
{
    return numbers.Select(n => $"Number: {n}").ToImmutableArray();
}
```
After:
``` cs
ImmutableArray<string> GetFormattedNumbers(ImmutableArray<int> numbers)
{
    return [.. numbers.Select(n => $"Number: {n}")];
}
```

Before:
``` cs
ImmutableArray<string> GetFormattedRange()
{
    return ImmutableArray.CreateRange(Enumerable.Range(1, 10).Select(n => $"Item {n}"));
}
```
After:
``` cs
ImmutableArray<string> GetFormattedRange()
{
    return [.. Enumerable.Range(1, 10).Select(n => $"Item {n}")];
}
```

**Comment by CyrusNajmabadi** [comment]
We'd likely take targeted community PRs here.  Thanks for the suggestions :)

**Comment by CyrusNajmabadi** [comment]
Working on this now.

**Comment by CyrusNajmabadi** [comment]
@obonn1 Thanks for the suggestions!

**Comment by obonn1** [comment]
@CyrusNajmabadi Wow that fast! Thanks for working on this
