### ISSUE TITLE
Compiler doesn't produce either FieldReferenceExpression or PropertyReferenceExpression for events.

### ISSUE THREAD

**Issue by brettfo** [dotnet/roslyn#7587]
Similar to #7584, events don't generate any `IOperation`s.

FYI @CyrusNajmabadi @JohnHamby

**Comment by CyrusNajmabadi** [comment]
Note: events seem so first class that I would expect the IOperation level to have some sort of IEventAccessExpression.  That type could then point to the specific field/property that was actually being referenced.

I think this would be appropriate given how special events are and how they even have first class operations in the language for manipulating them (i.e. += and -=)
