### ISSUE TITLE
Error CS0121: File.AppendAllTextAsync("", null)

### ISSUE THREAD

**Issue by znakeeye** [dotnet/roslyn#75905]
This works when targeting `.NET 8`. However, when targeting `.NET 9` it breaks the build.
```c#
namespace BreakingApi;

internal class Program
{
    static async Task Main(string[] args)
    {
        await File.AppendAllTextAsync("", null).ConfigureAwait(false);
    }
}
```
Apparently, it fails to see that `ReadOnlyMemory<char>` struct cannot be `null`. Or am I missing something here?
```
The call is ambiguous between the following methods or properties:
'File.AppendAllTextAsync(string, string?, CancellationToken)'
and
'File.AppendAllTextAsync(string, ReadOnlyMemory<char>, CancellationToken)'
```

**Comment by CyrusNajmabadi** [comment]
ROM has the following operator:

```c#
 public static implicit operator ReadOnlyMemory<T>(T[]? array)
```

So 'null' is assignable to it.

**Comment by CyrusNajmabadi** [comment]
Closing as not a language issue.  You could let dotnet/runtime know this is a possibility.

**Comment by huoyaoyuan** [comment]
This sounds like a good use case for `OverloadPriority` to force tie-breaking for `null`.
