### ISSUE TITLE
Unable to View Class Definitions from Nuget in Visual Studio Community

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#75902]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Unable-to-View-Class-Definitions-from-Nu/10784243)._

---
[severity:It's more difficult to complete my work]
When I click on Open Definition it takes me to decompiled code not the GitHub code of the MudBlazor NuGet.   I confirmed this occurs on a fresh install of Visual Studio Community.   A colleague is able to see the MudBlazor GitHub code by using Open Definition in Visual Studio Professional and VS Code.

![image.png](https://aka.ms/dc/image?name=B51073d1f7f0b45c5ba61643f4cd59f8e638664829173140542_20241106-044156-image.png&tid=51073d1f7f0b45c5ba61643f4cd59f8e638664829173140542)

![image.png](https://aka.ms/dc/image?name=B7c0119d171c74f6da22814618697f977638664833530646072_20241106-044912-image.png&tid=7c0119d171c74f6da22814618697f977638664833530646072)

I believe I have the correct settings necessary to see the MudBlazor GitHub code.  Notice how when I go to the Size class it says SourceLink in the screenshot.

![image.png](https://aka.ms/dc/image?name=B76e4b819dd134575b7ad034271cc6fe5638664832098054867_20241106-044649-image.png&tid=76e4b819dd134575b7ad034271cc6fe5638664832098054867)

![image.png](https://aka.ms/dc/image?name=B84fd99d38f3a4a8d96b22cd8a6d59c72638664834850700528_20241106-045124-image.png&tid=84fd99d38f3a4a8d96b22cd8a6d59c72638664834850700528)

Can you please advise how I can activate this feature in Visual Studio Community for all the MudBlazor Classes?  

Thank you

---
#### Feedback Bot on 11/6/2024, 05:50 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 11/13/2024, 01:59 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

**Comment by davidwengier** [comment]
That's not decompiled code, it's the actual code embedded in the PDB. If it was decompiled it would say "decompiled" in the tab, not "embedded". Things are working as expected
