### ISSUE TITLE
Location (highlighting) of IL2026 diagnostic could be improved

### ISSUE THREAD

**Issue by YoshiRulz** [dotnet/roslyn#75914]
```csharp
void Current() => {|IL2026:JsonSerializer.Serialize(obj.LongMethodCallWith(args))|};
void Proposal() => {|IL2026:JsonSerializer.Serialize|}(obj.LongMethodCallWith(args));
```
Apologies if this is the wrong repo. I believe [this](https://github.com/dotnet/runtime/blob/c65320833210f3df7412e2fcd11d6751fa374adc/src/tools/illink/src/ILLink.RoslynAnalyzer/RequiresUnreferencedCodeAnalyzer.cs#L16) is the source for the Analyzer, but it's not obvious where the relevant `GetLocation` call is.
I have version 8.0.110 of the SDK installed.

**Comment by CyrusNajmabadi** [comment]
This is not an analyzer owned by Roslyn. You could try the runtime team.
