### ISSUE TITLE
Is it possible to add quick fix for CS1593 ?

### ISSUE THREAD

**Issue by Thaina** [dotnet/roslyn#75926]
## Is your feature request related to a problem? Please describe.
Most of the time we made anonymous delegate without knowing method signature. It was really tedious to go to see delegate declaration just to fill in parameters

## Describe the solution you would like
I wish there would be quick fix option in vscode to fill in all parameter with the name from the delegate

## Applicable Scenarios
When calling method with anonymous function

## Describe alternatives you've considered
-

## Additional context
-

**Comment by CyrusNajmabadi** [comment]
Please expand on what you're asking for. It's very unclear currently

**Comment by Thaina** [comment]
This is some sample code to elaborate

```C#
    public delegate void SomeListenerDelegate(string name,float value,Dictionary<int,int> changed);

    public void Listen(SomeListenerDelegate someListenerDelegate)
    {

    }

    void DoSomething()
    {
        Listen(() => {});
    }

```

The error message is not very useful

![Image](https://github.com/user-attachments/assets/8a05f496-5f24-4512-882a-d6c19c8b3e09)

And the quick fix is nothing related to fix `CS1593`

![Image](https://github.com/user-attachments/assets/1b403443-d392-4e60-a381-11bf02bd7d0f)

I wish it should have quick fix option to generate simple signature for anonymous method for match the delegate

```cs

    void DoSomething()
    {
        Listen((name,value,changed) => {});
    }

```

**Comment by CyrusNajmabadi** [comment]
Closign out as unplanned.  In most cases this won't be helpful (like with Action/Func) as the names are too generic (no pun intendeD).

**Comment by Thaina** [comment]
> Closign out as unplanned. In most cases this won't be helpful (like with Action/Func) as the names are too generic (no pun intendeD). This is too niche a request.

All of the old style delegate are not generic, especially legacy ones. There was always delegate being made specific for function whenever people not using `action`/`func` because it was become a norm only recently. It was a practice to made real signature delegate everywhere even now

And even it was only action/func it still helpful to just generate an exact number of variable to match signature beforehand and then let user change the name and see the type by hovering

**Comment by CyrusNajmabadi** [comment]
@Thaina if you feel like this would be useful, you can create an code fixer here in a few minutes to solve the problem for yourself.

**Comment by Thaina** [comment]
> [@Thaina](https://github.com/Thaina) if you feel like this would be useful, you can create an code fixer here in a few minutes to solve the problem for yourself.

First, I propose here so that it would be officially supported pattern

Second, I wish to see if there is any related idea it should be fixed together or any blind spot I miss

Third, if it really that easy in few minutes then any member can made it without me making pull request and wait for accepted to be officially supported in roslyn

**Comment by CyrusNajmabadi** [comment]
As I said, this is too niche for us. It's simple though. So you should just make it for yourself if you really want this.
