### ISSUE TITLE
VS highlights issues after git pull

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#75922]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS-highlights-issues-after-git-pull/10789248)._

---
[severity:It bothers me. A fix would be nice] [regression] [worked-in:17.12.0]
Repro:
1. Open a VS C# project that is in a git repo - open a C# file in the editor
2. Modify the git repo used changing the C# file to call new methods created in other files
3. From VS, git pull on the project

Note the C# file shown is updated but now shows red squigglies on the new method calls. Problem persists even after doing a rebuild all (which succeeds).

Problem workaround: open the C# file where the new method is defined, then open the problematic C# file again. Squigglies go away.

---
#### Hafthor Stefansson [MSFT] on 11/13/2024, 00:37 PM: 

<p>just tried to record a screen video of this happening, but this time it didn’t occur. will update if I figure out any additional steps needed to repro this.</p>

#### Hafthor Stefansson [MSFT] on 11/13/2024, 04:12 PM: 

(private comment, text removed)
#### Feedback Bot on 11/13/2024, 07:28 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 11/14/2024, 10:30 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

**Comment by CyrusNajmabadi** [comment]
Likely an issue with lost FS notifications.

**Comment by ToddGrun** [comment]
Hopefully fixed by https://github.com/dotnet/roslyn/pull/75815, as that would cause general instability wrt file system notifications. If you continue to see this after 17.13 Preview 2, please reactivate and we'll continue investigating. Thanks!
