### ISSUE TITLE
Add Delphi like keyword "implements" for interface implementation delegation for subobjects

### ISSUE THREAD

**Issue by GoldyD** [dotnet/roslyn#7594]
Example:

``` csharp
public interface IFoo
{
    void Foo();
}

public class Foo : IFoo
{
     public void Foo()
     {
        Console.Write("IFoo called");
     }     
}

public class FooUser : IFoo
{
      private IFoo _iFoo implements IFoo;

      public FooUser(IFoo iFoo)
      {
          _iFoo = iFoo;
      }            
}

Usage:

var fooUser = new FooUser(new Foo());
fooUser.Foo();  // Call Foo subobject implementation IFoo interface
```

**Comment by alrz** [comment]
#6081

**Comment by gafter** [comment]
It is unlikely we would do this instead of proper mixins.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.

Note that we are considering *traits*. See https://github.com/dotnet/csharplang/issues/52
