### ISSUE TITLE
CS8604 FP with static partial class

### ISSUE THREAD

**Issue by shuebner** [dotnet/roslyn#75954]
**Version Used**: 8.0.402, 9.0.100

**Steps to Reproduce**:

1. Build the attached repro ([repro_CS8604.zip](https://github.com/user-attachments/files/17796868/repro_CS8604.zip))

**Diagnostic Id**: CS8604

**Diagnostic Message**: CS8604: Possible null reference argument for parameter 'baseUnit' in 'Unit<Second> Unit.From<Second>(IScale scale, Unit<Second> baseUnit)'

**Expected Behavior**:
No nullability warning

**Actual Behavior**:
Nullability warning

The warning goes away when no partial class is used.

**Comment by jcouv** [comment]
This is by-design. Simplifying the repro even further, you'd get:
```csharp
#nullable enable

public static class D
{
    public static readonly object problem = field; // 1 warning CS8601: Possible null reference assignment.
    public static readonly object field = null!;
}
```
You have two static fields in two parts of your partial type. Given your build and the order that the compiler processes the partial parts, the field named `Second` is unassigned (ie. `null`) by the time it gets used in `    public static readonly Unit<Second> Foo = Unit.From(NoScale.Instance, Second);`

**Comment by shuebner** [comment]
Ah yes, the good ol' static initialization order, :-)
Thank you for the reminder and thank the analyzer for covering this common gotcha case.

Consider my issue moot then.
