### ISSUE TITLE
Quote paths in cibuild.sh so that we can build on volumes/paths with spaces in them

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#7597]
We've got some new Mac machines that have spaces in their volume name, causing build breaks, before we turn on these machines, we quote all the paths.

**Comment by davkean** [comment]
Can someone from @dotnet/roslyn-infrastructure pick this up today?

**Comment by jasonmalinowski** [comment]
Looks like we have plenty of quoting. If we see a concrete issue, will create a new bug.
