### ISSUE TITLE
Code cleanup removes usings from external C# files

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#75979]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Code-cleanup-removes-usings-from-externa/10790432)._

---
[severity:It's more difficult to complete my work]
* Load a .cs file into the IDE which is not part of the current Solution
* Run code cleanup (with "remove unused usings" feature enabled)
* Most of the usings are deleted from the file because cleanup doesn't have any knowledge of the types used in the file.

Why this matters:
* When debugging nuget library code in my application, I load the library source files in my IDE so I can single step through the library code. However, because the library file is not in the current solution, and I have "run code ccleanup on save" enabled, my library files become corrupted every few minutes.
* I often load source files from other Solutions to search/view/copy their code. If I happen to save while viewing a file, it corrupts the code. (As with most experienced computer users I automatically hit save about every 10-15 seconds to protect my work)

I can work around this by disabling useful features (automatically add usings, clean away the unused usings, clean up when saving), but it would be nice if it only removes "usings that it knows are not used" instead of "usings it doesn't know are used".

---
#### Feedback Bot on 11/14/2024, 05:58 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 11/19/2024, 00:47 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/76019
