### ISSUE TITLE
Visual Studio 2022 Community - Open in Terminal

### ISSUE THREAD

**Issue by bcheung4589** [dotnet/roslyn#75989]
1. Open in Terminal.
![Image](https://github.com/user-attachments/assets/f58e38e5-4371-4dbe-95cd-ed112d537433)
2. Is this what vs developer powershell is? a non-loading prompt?
![Image](https://github.com/user-attachments/assets/c0df6215-b6fd-43b0-a251-3a3d0aceba1a)
3. After clicking on +Developer PowerShell in the NON-LOADING prompt. It opens in the ROOT map, not the selected location.
![Image](https://github.com/user-attachments/assets/8799dbc4-929d-4585-9acf-3d6a3645a2bc)

**This is an issue I have for months now..**

![Image](https://github.com/user-attachments/assets/a3ed34dc-511f-4189-b3fd-4d62acf1b0b3)

**Comment by CyrusNajmabadi** [comment]
This is not a roslyn issue. Please file an issue at developercommunity.
