### ISSUE TITLE
When generating a class from an anonymous object, implicitly-named properties are ignored

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#75980]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/When-generating-a-class-from-an-anonymou/10783263)._

---
[severity:It bothers me. A fix would be nice]
if I have an anonymous object (e.g. in a select) like this:

```
new 
{
   SomeProperty1 = a.SomeProperty1,
   a.SomeProperty2
};
```

When I use the "create class" refactor option to turn this into a class, the implicitly-named properties (e.g. SomeProperty2 in the above example) are ignored. 

Ideally they would be included in the new class with the same names, and the "new" statement updated to reflect this (e.g. SomeProperty2 = a.SomeProperty2)

---
#### Feedback Bot on 11/5/2024, 05:42 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 11/19/2024, 00:56 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

**Comment by CyrusNajmabadi** [comment]
I don't repro this.  I get:

![Image](https://github.com/user-attachments/assets/17f840ef-ba6b-4301-91b8-15bb14d9d5bd)
