### ISSUE TITLE
`Replace 'Property' with method` erases DIM

### ISSUE THREAD

**Issue by RenderMichael** [dotnet/roslyn#75999]
**Version Used**: 

.NET SDK 9.0.100

**Steps to Reproduce**:
Existing code:

```csharp
interface I
{
    public string Name
    {
        get
        {
            return string.Empty;
        }
    }
}
```

After fix:

```csharp
interface I
{
    string GetName();
}
```

**Diagnostic Id**:

IDE did not present one, so I'm unsure whether this is the right repo, or if this is implemented in `roslyn-analyzers`

**Expected Behavior**:

```csharp
interface I
{
    public string GetName()
    {
        return string.Empty;
    }
}
```

**Actual Behavior**:
```csharp
interface I
{
    string GetName();
}
```

**Comment by CyrusNajmabadi** [comment]
This is the correct repo for this.
