### ISSUE TITLE
Fix `Implement abstract class` generates invalid code when target type has no body and is followed by file-scoped type

### ISSUE THREAD

**Issue by just-ero** [dotnet/roslyn#75992]
**Full issue information + repro project**:  
https://github.com/just-ero/roslyn-issues-repros/tree/main/4.13.0/000_ImplementAbstractClass_WithoutBodyWithFileScopedTypeBelow

### Version
**Roslyn**: 4.13.0-2.24565.3 

### Steps to Reproduce

1. Add the following code wherever syntactically applicable:
   ```cs
   abstract class A
   {
       public abstract void M();
   }
   
   class B : A
   
   file class C;
   ```
2. Apply the `Implement abstract class` fix on `B`.

### Expected Behavior

```cs
abstract class A
{
    public abstract void M();
}

class B : A
{
    public override void M()
    {
        throw new System.NotImplementedException();
    }
}

file class C;
```

### Actual Behavior

```cs
abstract class A
{
    public abstract void M();
}

class B : A

file
{
    public override void M()
    {
        throw new System.NotImplementedException();
    }
}

class C;
```

**Comment by just-ero** [comment]
Let me know if this format of reporting issues is not welcome. I wanted to avoid duplicating the information here and on my repo.

**Comment by RikkiGibson** [comment]
Repro projects are welcome, however, it would probably be best if the contents of the linked README.md were pasted into this issue description.
