### ISSUE TITLE
Allow spelling errors in NavigateTo

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#7602]
Now that we have a fast edit distance algorithm, we should try allowing spelling errors from NavigateTo. I spent a little time playing with an implementation and it seems fairly straightforward--checks in the PatternMatcher that do exact string matching need to know how to compare using EditDistance instead. Sample screenshot below.

![image](https://cloud.githubusercontent.com/assets/3751401/11904285/012c979e-a574-11e5-9655-414e37e61ce1.png)

**Comment by rchande** [comment]
And I suppose we should prototype the same thing for statement completion, though I would expect us to be much stricter there.

**Comment by davkean** [comment]
You probably want a way to opt out of that, perhaps by "Quoting"

**Comment by rchande** [comment]
Sure, but we'll also need to modify the match ranking to penalize matches that had errors.

**Comment by davidroth** [comment]
@rchande Please also enable matching fragments on camelCase basis (e.x. like in Monodevelop/XamarinStudio/Resharper).

For example in your screenshot I see the method `TheRainInSpainFallsMainly'.
With camelCase fragment matching i could search for *thraiispafalma* to find the correct method.
At the moment I have to specify wildcards explicitly which is not that fast.

Or is this already contained in your probosal?

**Comment by alrz** [comment]
It would be nice to completely ignore character capitalization to suggest add `using` etc.

**Comment by davkean** [comment]
@davidroth We already support it based on just prefix (see below), but your suggestion is a great idea and we should consider that.

![image](https://cloud.githubusercontent.com/assets/1103906/11914972/f90fbd4c-a646-11e5-8807-91f558f690c3.png)

@alrz Yep, this is exactly what @CyrusNajmabadi just checked in.

**Comment by Pilchie** [comment]
@davidroth @davkean Right - we currently require capital letters to indicate the start of words, but we shouldn't necessarily require that.

**Comment by Pilchie** [comment]
Resolving since this was done by #11474
