### ISSUE TITLE
Infallible var pattern causes "not all code paths return a value"

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/roslyn#76059]
**Version Used**: '4.12.0-3.24523.4 (f3348c2a)'. Language version: latest (13.0).

**Steps to Reproduce**:
```cs
int _value;
int Value() => _value;
string? EnsureValid(int value) => value switch 
{ 
    42 => throw new System.Exception("Fatal"),
    > 42 => "additional data"
    _ => null 
}
int NextValue() => _value++;

int Pseudo()
{
    var current = Value();
    while(EnsureValid(current) is var result) 
    { 
        if (result is "additional data")
            return current;
        current = NextValue();
    }
}

int Minimized()
{
   while(1 is var number) {}
}

int Compiles()
{
    var current = Value();
    while(true) 
    { 
        var result = EnsureValid(current);
        if (result is "additional data")
            return current;
        current = NextValue();
    } 
}
```

**Diagnostic Id**: CS0161

**Expected Behavior**:
I expect this to compile as a `while(true) {}` would.

I couldn't come up with a particular reason for this to work differently from a `true` loop condition, there is no function call or other opaqueness to semantically cloud the equivalence with `true`, and the pattern always succeeds according to the language spec.

As for the code, you could argue the call and pattern belongs in the while body, however there are cases where doing something like this actually reads quite naturally. Certain coding patterns may rely on breaking out of the loop through another channel (exceptions in this case) and look fairly natural as part of the loop condition.

**Actual Behavior**:
```
    error CS0161: 'Pseudo()': not all code paths return a value
    error CS0161: 'Minimized()': not all code paths return a value
```

**Comment by CyrusNajmabadi** [comment]
I didn't believe the language ever thinks of patterns as constant values.  But it's reasonable to say that it could for certain cases. I think that would be needed here so that it would know which points of the method are reachable or not. 

So for this to happen, I think it would be necessary to change the language, which would happen at dotnet/csharplang. 

If you started a discussion there, and tagged me, I'd be willing to bring this idea to the ldm to see what the team thinks about this.

**Comment by jcouv** [comment]
I think the [current spec](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-8.0/patterns.md#var-pattern) for `var` pattern with simple designation is sufficient to justify flow analysis always considering it true:

> a match to a var pattern always succeeds with a simple_designation.

**Comment by jcouv** [comment]
I'm proposing a fix in https://github.com/dotnet/roslyn/pull/76109

**Comment by jaredpar** [comment]
Think we should check with LDM before moving forward with a change here.

**Comment by jcouv** [comment]
@jaredpar You're right. If we open the doors for patterns, we need to open the door to other non-constant expressions affecting reachability analysis as well. For example, binary operations like `while (M2() is var number1 && M2() is var number2) { }`. It seems we have all the infrastructure in place to make that work, but for some reason we only limited ourselves to analyze constants.

**Comment by jcouv** [comment]
@alrz The proposal you linked to would consider some patterns to be constants, but I don't think it would or should treat `M() is var x` as a constant (it needs to be evaluated). So I think to make the OP scenario work, we need to update our reachability rules.

That said, my quick prototype showed there are dragons I don't understand, so I closed it. I'll ask around to understand the current design more, but I believe it is by-design.

**Comment by jcouv** [comment]
Confirmed that the current reachability behavior is by-design. Here's the relevant section of the [spec](https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/statements.md#132-end-points-and-reachability):

> Note: To determine whether a particular statement or end point is reachable, the compiler performs flow analysis according to the reachability rules defined for each statement. The flow analysis takes into account the values of constant expressions ([§12.23](https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/expressions.md#1223-constant-expressions)) that control the behavior of statements, but the possible values of non-constant expressions are not considered. In other words, for purposes of control flow analysis, a non-constant expression of a given type is considered to have any possible value of that type.

I'll close this roslyn issue. @NinoFloris, you're welcome to start a discussion on csharplang to change that design. Thanks
