### ISSUE TITLE
String Interpolation in assembly:AssemblyCopyright

### ISSUE THREAD

**Issue by ajorians** [dotnet/roslyn#7605]
This is probably a feature request.

I can do this in my AssemblyInfo.cs file:
```csharp
[assembly: AssemblyCopyright( "Copyright © " + VersionConstants.ThisYear + " My Company Here. All rights reserved." )]
```

Where VersionConstants looks like this:
```csharp
public class VersionConstants
{
   public const string ThisYear = "2015";
}
```

And I thought I'd be able to use the string interpolator instead like so:
```csharp
[assembly: AssemblyCopyright( $"Copyright © {VersionConstants.ThisYear} My Company Here. All rights reserved." )]
```

I cannot.  Error CS0182 An attribute argument must be a constant expression...

It would be nice if I can use string interpolator as a replacement of string concatenation.

**Comment by gafter** [comment]
Since string interpolation is defined in terms of the "current" (runtime) culture, this is impossible.
