### ISSUE TITLE
IMemberReferenceExpression should expose a Member property with the symbol

### ISSUE THREAD

**Issue by brettfo** [dotnet/roslyn#7608]
The three interfaces that implement `IMemberReferenceExpression`; `IFieldReferenceExpression`, `IPropertyReferenceExpression`, and `IMethodReferenceExpression`; each have their own `Field`, `Property`, and `Method` properties that expose the symbol.  This API would be much easier to use if that symbol was exposed on the parent interface.

**Comment by brettfo** [comment]
When this is fixed, either ping @brettfo or remove the `GetSymbol()` method from `QualifyMemberAccessDiagnosticAnalyzerBase.cs`.

**Comment by JohnHamby** [comment]
The requested property appeared late last year. Sorry for forgetting to notify @brettfo .
