### ISSUE TITLE
IDE0301 code fixer in ternary expression produces invalid C# code (CS0029)

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/roslyn#76085]
**Version Used**: 4.12.0-3.24523.10 (16f58fa3)'. Language version: 13.0

**Steps to Reproduce**:

1. Paste this code in a blank new console:

```csharp
using System.Collections.Immutable;

static IEnumerable<string> M(object obj)
{
    return obj is int
        ? Enumerable.Empty<string>()
        : Enumerable.Repeat("", 1);
}
```

2. Hover over "Empty" and apply the suggested IDE0301 code fixer.

**Diagnostic Id**: IDE0301

**Expected Behavior**:

Should now get a code fixer here. Arguably you shouldn't get IDE0301 in the first place.

**Actual Behavior**:

You get IDE0301, and the code fixer breaks the code entirely:

![Image](https://github.com/user-attachments/assets/c32353f4-0a98-4ce9-8514-5010ddb8047a)

cc. @CyrusNajmabadi

**Comment by RikkiGibson** [comment]
I'm not reproing on [SharpLab](https://sharplab.io/#v2:EYLgtghglgdgNAFxFANgHwAIAYAEGCMALANwCwAUNnvgHQAysAjmeRQQGzUDMAPAVgD4cAWQAUAe2AArAKYBjBDklSAlBQDeFHNrwB2JdJxQAzkZgItOqwH4cAbQC6lq9pA4AojACuYGQCcIYBQZGgAlGQAHGQgEUQAiOLgcfBUWAF8gA===) (which I'm happy to see was updated today).

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/75328
