### ISSUE TITLE
Support rewriting `string.Remove` in IDE0057 "Use range operator"

### ISSUE THREAD

**Issue by reflectronic** [dotnet/roslyn#76091]
The IDE0057 code style analyzer suggests replacing calls to `string.Substring` with the range operator. In some cases, calls to `string.Remove` can also be replaced with the slice syntax. The analyzer should suggest replacing such calls as well. 

The following forms are equivalent:
- `string.Remove(string.Length - x)`
- `string.Remove(string.Length - x, x)`
- `string.Substring(0, string.Length - x)`
- `string[..^x]`

And:
- `string.Remove(0, string.Length - x)`
- `string.Substring(string.Length - x)`
- `string[^x..]`

And:
- `string.Remove(x, string.Length - x)`
- `string.Substring(0, x)`
- `string.Remove(x)`
- `string[..x]`

And:
- `string.Remove(0, x)`
- `string.Substring(x)`
- `string[x..]`

And:
- `string.Remove(x, 0)`
- `string`

I believe there are no more cases where `string.Remove` may be rewritten as a slice.

**Comment by CyrusNajmabadi** [comment]
![Image](https://github.com/user-attachments/assets/0d105605-43a7-4318-94d4-4188c44ca390)

This doesn't seem to be the case.  For example:

```c#
        var v = "the quick brown fox jumped over the lazy dog";
        Console.WriteLine(v.Remove(10));
        Console.WriteLine(v[..^10]);
```

**Comment by reflectronic** [comment]
Sorry, I meant to write `string.Remove(string.Length - x)` there :-(

`string.Remove(x)` should be next to `string[..x]`
