### ISSUE TITLE
CollectionExpressionSyntax vs ImplicitArrayCreationExpressionSyntax difference in behaviour

### ISSUE THREAD

**Issue by EvgenyMuryshkin** [dotnet/roslyn#76136]
Hi,

I thought that c1 and c2 should be identical, but C# disagrees.

![Image](https://github.com/user-attachments/assets/ecdef8ac-0e22-4fc3-8515-9ef5a3d3d9df)

Is that an expected behavior?

```
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Experimental.Tests
{
    class TestClass
    {
        public TestClass(byte[] values)
        {

        }
    }

    [TestClass]
    public class CESTests
    {

        [TestMethod]
        public void CESCtor()
        {
            var c1 = new TestClass([1,2,3,4]);
            var c2 = new TestClass(new[] { 1, 2, 3, 4 });
        }
    }
}

Thanks,
Regards,
Evgeny.

```

**Comment by CyrusNajmabadi** [comment]
They're not identical. Collection expressions are target typed. So the target here (byte[]) determines the type created.  Implicit arrays are not target typed. They take on the best common type of all their elements (int here). This is also why an implicit array requires at least one element in it.
