### ISSUE TITLE
CTRL + click (and F12) on a partial property should always jump to user-defined part

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/roslyn#76156]
## Summary

One long standing user complaint with the [MVVM Toolkit](https://github.com/CommunityToolkit/dotnet) source generator is that it made navigating code difficult, because F12-ing on the generated property would (understandably) jump to the generated code, and not to the field with `[ObservableProperty]` defined in user code. We've been telling users for months that partial properties would fix this. Turns out that is not actually the case, and the problem is unfortunately still there. Consider this:

```csharp
using CommunityToolkit.ComponentModel;

partial class MyViewModel : ObservableObject
{
    [ObservableProperty]
    public partial string? Name { get; set; }
}
```

The expectation is that if you CTRL + click (or F12) into `Name` from any reference to it, the IDE would navigate to the partial declaration that you defined. Instead, the IDE currently navigates to the generated partial implementation. This is useless and not what users expect. It also means that currently, the workflow every single time is:
- "I want to check this property"
- _\*CTRL + clicks\*_
- "Oh ffffff, I don't care about this"
- _\*CTRL + click on the containing type\*_
- Find the "main" partial part in the list that shows up
- Double check it to open it in a tab
- _\*CTRL + F\*_
- Type the property name manually
- Jump to it
- "Ok so this is the actual property"

This is just... A terrible user experience 😅

## Proposed Feature

I propose the following IDE changes:
- CTRL + click on a partial property _reference_ should jump to the user-defined part (either declaration or implementation)
- CTRL + click on the partial property itself should jump to the generated other part (whichever it is)

This does two things:
- You can easily navigate to your user-defined declaration with CTRL + click
- If you really want to see the generated member, you can easily CTRL + click on the user-defined declaration from there
    - The assumption is that in virtually all cases, users will only be interested in looking at _their_ user-defined partial part

cc. @RikkiGibson

## Alternative Designs

None.

**Comment by RikkiGibson** [comment]
Seems reasonable to me. Users usually only want to go through generated code for debugging or out of interest in the implementation details of the generator. They are more likely to want to navigate to the code they wrote, have source controlled, and have the ability to edit. Regardless of whether that happens to be the "definition" or "implementation" part.

I recall that F12 on 'override' keyword will go to the base method. If ctrl+click on a declaration to go to a different declaration is not found to be viable, then possibly F12 on the 'partial' keyword would help here to jump between the declarations.

**Comment by Sergio0694** [comment]
@CyrusNajmabadi to clarify, the ask here was also to change the default behavior for CTRL + click (and F12) so that when clicking on a property reference, it would always jump to the part defined in user code first, rather to the generated code like today. Did the PR also address that? Just making sure in case otherwise we needed to keep this open 🙂

**Comment by CyrusNajmabadi** [comment]
@Sergio0694 i'm not planning on making any more changes here.  If you want to adjust the behavior, we'd take a community PR here.

**Comment by Sergio0694** [comment]
But if that PR didn't actually fix this issue why did it close it? 😅

**Comment by CyrusNajmabadi** [comment]
> But if that PR didn't actually fix this issue why did it close it?

Because now you can easily get between the members.  Which addresses hte pain point of:

- *CTRL + click on the containing type*
- Find the "main" partial part in the list that shows up
- Double check it to open it in a tab
- *CTRL + F*
- Type the property name manually
- Jump to it
