### ISSUE TITLE
[Test Failure] ETA test timed out

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#7619]
http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_dbg_eta/441/

ETA test didn't finish but stay up until timed out.

**Comment by heejaechang** [comment]
all ETA tests have passed. by the way.

**Comment by heejaechang** [comment]
looks like hang when it tries to write test result.

**Comment by brettfo** [comment]
Closing since the build link is dead and it's been a long time since this saw any activity.
