### ISSUE TITLE
When loading an MSBuildSolution, building project references should be error tolerant

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#762]
There is a place where the workspace tries to figure out a project reference to a project type it doesn't have a loader for, by having MSBuild load the project file so we can discover its output path, so we can make a metadata reference if the file is there.
 
That's two different kinds of loading. The MSBuild API can load any kind of project file, because they are all MSBuild project files regardless of language.  The workspace can only successfully load project files associated with languages it knows, but via MSBuild loading it can sometimes turn project to project references into metadata references. This code is in there precisely for the case of having mixed solutions with C++ projects in them.

I'd argue that the loading of a referenced project for the purpose of determining the OutputPath should be resilient to failure and not cause failing of the entire MSBuildWorkspace just because we weren't able to build a referenced C++ project.

Right now when we load a solution with a C++ project and a C# project that references it, if the C++ project fails to build (e.g. missing include target file), the entire load process will fail.

Instead, we should issue a warning and proceed loading the C# project as if the reference wasn't there, or maybe hang diagnostics off of it.

**Comment by jasonmalinowski** [comment]
Did you feel this previously worked? We've recently discovered some regressions around C# to C++ project references where WinMDs are involved.

**Comment by KirillOsenkov** [comment]
I think @mattwar has added logic to convert non-C#/VB project references to metadata references if their output assembly exists, and it wasn't error-tolerant since that change. Before that change we never tried to build those referenced projects at all.

**Comment by mattwar** [comment]
fixed by #2343
