### ISSUE TITLE
Crash class BatchFixAllProvider

### ISSUE THREAD

**Issue by SergeyZhurikhin** [dotnet/roslyn#7623]
After calling the preview window CodeFix at the level of the whole Project or Solution, comes crash class BatchFixAllProvider:

![2](https://cloud.githubusercontent.com/assets/16261478/11914071/07c5a0a0-a687-11e5-9622-abef7ce60ec2.png)
![1](https://cloud.githubusercontent.com/assets/16261478/11914069/07c1cf52-a687-11e5-9e7d-a3aef9891d7e.png)

If you attach to the process Visual Studio, you will see an exception that probably led to the crash.
Most recently an InvalidOperationException with the description: "The sequence is empty.":

![3](https://cloud.githubusercontent.com/assets/16261478/11914070/07c50af0-a687-11e5-8d4c-3a9573c01baa.png)

Before it was also two exceptions InvalidOperationException with the description: "An attempt was made to transfer to the final status of a task that has already been done.":

![4](https://cloud.githubusercontent.com/assets/16261478/11914072/07c75bd4-a687-11e5-8c66-72bfb9c88774.png)

Assembly: Microsoft.CodeAnalysis.Workspaces, Version 1.1.0.0, File version: 1.1.0.51109
Location: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\PrivateAssemblies\Microsoft.CodeAnalysis.Workspaces.dll 

What can I do for you to resolve crash class BatchFiksAlProvider?

**Comment by SergeyZhurikhin** [comment]
What can I do for you to resolve crash class BatchFiksAlProvider?

**Comment by davkean** [comment]
A dump Debug -> Save Dump As -> Minidump with Heap at the point the crash occurs would be helpful.

**Comment by Pilchie** [comment]
Unfortunately, we're not able to reproduce this, and without more information we can't make further progress.
