### ISSUE TITLE
Unverifiable IL generated for switch over Nullable<Int64> and Nullable<UInt64>

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/roslyn#7625]
Found while working on expression trees for statement nodes, where Roslyn produced different evaluation results compared to compiled expression tree code.

Consider the following piece of code:

```csharp
// repro.cs
public static class C
{
    public static bool F(long? x)
    {
        switch (x)
        {
            case 1:
                return true;
            default:
                return false;
        }
    }
}
```

Compile it with:

```
> csc /t:library repro.cs
Microsoft (R) Visual C# Compiler version 1.0.0.50618
Copyright (C) Microsoft Corporation. All rights reserved.
```

And run peverify.exe as follows:

```
> peverify repro.dll
Microsoft (R) .NET Framework PE Verifier.  Version  4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

[IL]: Error: [C:\temp\repro.dll : C::F][offset 0x00000018][found Long][expected Int32] Non-compatible types on the stack.
1 Error(s) Verifying repro.dll
```

When trying to invoke the function with a value of `1L`, it prints `false` incorrectly. Changing `case 1:` to `case 1L:` makes the problem disappear. Changing the signature from `long?` to `long` also causes the problem to go away.

The issue is a missing `conv.i8` instruction, which is present when switching over `long` or when using the `1L` literal:

```
.method public hidebysig static bool  F(valuetype [mscorlib]System.Nullable`1<int64> x) cil managed
{
  // Code size       27 (0x1b)
  .maxstack  2
  .locals init (valuetype [mscorlib]System.Nullable`1<int64> V_0,
           int64 V_1)
  IL_0000:  ldarg.0
  IL_0001:  stloc.0
  IL_0002:  ldloca.s   V_0
  IL_0004:  call       instance bool valuetype [mscorlib]System.Nullable`1<int64>::get_HasValue()
  IL_0009:  brfalse.s  IL_0019
  IL_000b:  ldloca.s   V_0
  IL_000d:  call       instance !0 valuetype [mscorlib]System.Nullable`1<int64>::GetValueOrDefault()
  IL_0012:  stloc.1
  IL_0013:  ldloc.1
  IL_0014:  ldc.i4.1
  // needs conv.i8
  IL_0015:  bne.un.s   IL_0019
  IL_0017:  ldc.i4.1
  IL_0018:  ret
  IL_0019:  ldc.i4.0
  IL_001a:  ret
} // end of method C::F
```

**Comment by bartdesmet** [comment]
The issue occurs for Nullable<UInt64> as well.

**Comment by gafter** [comment]
Related (possibly dup of) #5604

**Comment by bartdesmet** [comment]
My last reply has eaten the angle brackets, so Nullable means Nullable(Of UInt64).

**Comment by serbrech** [comment]
So, we just hit this on our system, it was caught in tests, but took us 3 days to figure it out... thanks guys... Such a insane impact has not been communicated as I would expect, and our release is now certainly delayed!
![madness](https://cloud.githubusercontent.com/assets/315853/12923051/6e031384-cf54-11e5-8902-52a2a2472e5d.PNG)

**Comment by serbrech** [comment]
So, we just hit this on our system. Any communication done around this issue? it seems relatively important. When is update 2 coming?
![madness](https://cloud.githubusercontent.com/assets/315853/12924240/6637d414-cf59-11e5-9981-65bc7f132aeb.PNG)
