### ISSUE TITLE
Support `dotnet_format_on_save` in .editorconfig

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#76256]
TypeScript has this option:
https://github.com/microsoft/typespec/blob/968f9c941c8a8052b290a5497acf6aaaaaf3d875/.vscode/settings.json#L24

Not sure if we have an equivalent in .editorconfig or .vsconfig files? A repo would configure this and then VS would format on save for files from that repo.

I found this but it doesn't seem to be hooked up to anything:
https://github.com/dotnet/roslyn/blob/ea73dc337175ff0e40fffc93a00364e1fc21cc9a/src/EditorFeatures/Core/Formatting/FormattingOptionsStorage.cs#L14C62-L14C83

Also apparently you can run Code Cleanup profiles on Save:
https://learn.microsoft.com/en-us/community/content/how-to-enforce-dotnet-format-using-editorconfig-github-actions#enforcing-code-style-on-save

But there doesn't seem to be an option to control this per-repo and not globally.

**Comment by CyrusNajmabadi** [comment]
Format on save should be handled through lsp as a host controlling option. The language server shouldn't have to do anything except expose a format handler (which we do).

**Comment by JoeRobich** [comment]
1. VS Code

`editor.formatOnSave` is an editor option and can be configured globally for all languages or can be scoped to specific languages such as `csharp` ([docs](https://code.visualstudio.com/docs/getstarted/settings#_language-specific-editor-settings)).

```json
{
  "[csharp]": {
    "editor.formatOnSave": true
  }
}
```

2. VS

This experience isn't quite as good at the moment. Assuming you have opt-ed in to the new settings experience. You can add a settings.VisualStudio.json file to your repo that configures the Code Cleanup profile. You cannot, however, configure the specifics of the profile yet. By default this should include "Format document", but also includes other options you may not want or it may have been customized on an individual developers machine. 

![Image](https://github.com/user-attachments/assets/6f47286b-72dd-437e-a176-a7cea324d0a8)


```jsonc
/* Visual Studio Settings File */
{
  "textEditor.codeCleanup.profile": "profile1"
}
```

**Comment by CyrusNajmabadi** [comment]
In other words, this should go to editor/platform

**Comment by CyrusNajmabadi** [comment]
@JoeRobich Is there anything for roslny to do here?  Again, this sounds like a host issue to support this option.

**Comment by KirillOsenkov** [comment]
I filed DevDiv 2318379 and assigned to @olegtk who can hopefully help triage and set the right fields on the bug.

**Comment by CyrusNajmabadi** [comment]
Ok.  Closing out.
