### ISSUE TITLE
Please implement Enumberable.Repeat with an instance factory.

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/roslyn#7628]
Hi,

There are `Enumerable.Range` and `Enumerable.Repeat` which are awesome, however, when using `Repeat` with a reference type, it's the reference to the same object being repeated, hence, changing a property of the repeated object will reflect in that property being changed for all indexes.

The solution would be to create another overload of `Enumerable.Repeat` that is either parameterless or ones that accepts `Func<T>` or `Func<int, T>` that uses as a factory of the generated element, where the latter overload (with the `int` argument provides the index of the current element to be generated.

    //will initialize an array of 40 instantiated StringBuilder objects.
    var builders = Enumerable<StringBuilder>(40).ToArray(); 

    //will initialize an array of 40 instantiated StringBuilder objects using a custom constructor
    var builders = Enumerable<StringBuilder>(i => new StringBuilder($"Line {i} says:"));

Another overload I'd want to see is for `Enumberable.Range`, is omitting the `start` parameter so that it's set to `0`, and only the `count` is provided. Merely a syntactic sugar.

**Comment by jmarolf** [comment]
This appears to be unrelated to the compiler. Please file on https://github.com/dotnet/corefx which owns the System.Collections.* libraries

**Comment by weitzhandler** [comment]
You're right. Reposted [here](https://github.com/dotnet/corefx/issues/5078).
