### ISSUE TITLE
Duplicate inline hints when in work in VB Code

### ISSUE THREAD

**Issue by Cosifne** [dotnet/roslyn#76290]
VS Version 17.13.0 Preview 3.0 [35605.136.main]

Open `src\VisualStudio\TestUtilities2\MockServiceProvider.vb`
Then scrolling down/up a few times you will see:
![Image](https://github.com/user-attachments/assets/6e364aa6-7ae4-4c41-8a30-a5d6723d9cef)

And the duplicate hints get disappeared after a few sec

**Comment by Peter-Juhasz** [comment]
Same with C#:

![Image](https://github.com/user-attachments/assets/60ffec78-483c-4970-84b0-f425b83b280a)

(although I started to experience this issue from 17.13 P2 only)

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/76525
