### ISSUE TITLE
VB - actions duplicated in IDE with multiple imports on same line

### ISSUE THREAD

**Issue by jwooley** [dotnet/roslyn#763]
In VS 2015 CTP5 when multiple imports apply on a single line, all of the code actions appear duplicated in the drop down window.
![vbmultipleimportsdropdown](https://cloud.githubusercontent.com/assets/365256/6312453/fb46d872-b946-11e4-8093-2fc713d9799e.png)

**Comment by jwooley** [comment]
Correcting: Consider sorting the recommendations to make identifying differences easier.

**Comment by srivatsn** [comment]
We've done some work here to collapse the same items in the list. So if there was a suggestion to import Microsoft.CodeAnalysis - you should only see it once now. The order of the list is based on the priority of the fixes and the proximity of the issue being fixed. Sorting it would make the important fixes like adding a using not show up as the first item and break muscle memory for people who press cltr+ . and then enter to commit the action.
