### ISSUE TITLE
IDE0032 code fixer misses method arguments and produces invalid C# code (CS0103)

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/roslyn#76349]
**Version Used**: 4.12.0-3.24572.7 (dfa7fc6b)

**Steps to Reproduce**:

1. Create a project with this:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <AnalysisLevel>latest</AnalysisLevel>
    <AnalysisLevelStyle>latest-all</AnalysisLevelStyle>
  </PropertyGroup>

</Project>
```
2. Add this code:
```csharp
class Foo
{
    private string? _someValue;

    public string? SomeValue
    {
        get
        {
            if (string.IsNullOrEmpty(_someValue))
            {
                return _someValue = "hello";
            }

            return _someValue;
        }
    }
}
```
3. Apply the suggested IDE0032 code fixer on `_someValue`

**Diagnostic Id**: IDE0032

**Expected Behavior**:

The code fixer should produce valid code.

**Actual Behavior**:

The code fixer misses the argument to that `string.IsNullOrEmpty` call:

![Image](https://github.com/user-attachments/assets/b4a905fb-4cc4-4682-ab5f-e4e73e645373)

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/75519
