### ISSUE TITLE
Syntax Visualizer - Should the Span backets be consistent in Syntax Tree

### ISSUE THREAD

**Issue by shaggygi** [dotnet/roslyn#7634]
I noticed in the Syntax Visualizer's Syntax Tree, the Span starts with a bracket and ends with a parenthesis.  It is also displayed the same in the Span and FullSpan fields in the Properties window.

Example: ThrowStatement [818..840)

Was this intentional or should it really end with a bracket (or begin with a parenthesis)?

Example: ThrowStatement [818..840]
Example: ThrowStatement (818..840)

**Comment by pdelvo** [comment]
This is a well known notation to specify which bound is in the intervall and which is not. The '[' brackets says that the bound is included in the span, the '(' brackets show that the number is excluded. E.g. The first char of the throw statement is at index 818 and the last one is at index 839.

**Comment by davkean** [comment]
This is coming from TextSpan: http://source.roslyn.io/#Microsoft.CodeAnalysis/Text/TextSpan.cs,239 and it looks deliberate.

**Comment by shaggygi** [comment]
Makes more sense.  Thanks for providing the info. I'm closing the issue.
