### ISSUE TITLE
Add performance test for FixAllProvider

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#7636]
Currently we don't have any performance tests for FixAll. There have been public requests (https://github.com/dotnet/roslyn/issues/2637) as well as reports of performance regression in Update1. Unfortunately, we don't track or measure performance for this scenario right now. We need to add a performance test for it ASAP.

**Comment by mavasani** [comment]
Tagging @sharwell

**Comment by sharwell** [comment]
Someone is about to find out how slow the batch fixer is :laughing:

**Comment by davkean** [comment]
@rchande Can you work with @basoundr to figure between yourselves who's going to work on this?

**Comment by mavasani** [comment]
See https://github.com/DotNetAnalyzers/StyleCopAnalyzers/pull/1979#issuecomment-166630853 for the amount of performance regression in cold FixAll operation. I have explained the reasoning in https://github.com/DotNetAnalyzers/StyleCopAnalyzers/pull/1979#issuecomment-166654999 and a perf test which did a warm and cold FixAll for any real world project/analyzer should suffice. You may want to work with @sharwell as they already have some existing FixAll perf tests for StyleCopAnalyzers on real world code, which we may be able to reuse.

**Comment by rchande** [comment]
@mavasani @sharwell I'm starting to look at this now. How should this test work? 

Many of our existing performance tests measure performance while automating typing (or rename, or diagnostics, etc) in VS on old snapshots of the Roslyn solution. I was thinking of finding a diagnostic that appears in that solution and measuring fix all performance on it--how does that sound?

**Comment by rchande** [comment]
There will probably be many removable usings.

**Comment by mavasani** [comment]
@rchande If we want to write a test for the core FixAll performance, you can probably do so using a non-UI test. See StyleCopTester's FixAll infrastructure: https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/StyleCop.Analyzers/StyleCopTester/Program.cs#L192

Alternatively or additionally, you can write a UI test which measures the end to end FixAll performance in VS. Remove unused usings should be a good candidate.

**Comment by rchande** [comment]
@mavasani I believe our goal is to detect regressions in the scenario in VS, so I'll probably write this as a UI test.

**Comment by KevinH-MS** [comment]
We'll look at this in the next milestone.

**Comment by mavasani** [comment]
I have an [internal PR](https://github.com/dotnet/roslyn-internal/pull/805) out for a VS Integration test verifying FixAllOccurrences - so adding a perf test on top of this should be trivial.

**Comment by mavasani** [comment]
Any updates here? I am worried that this will get pushed out of Update3 due to it being a test item. 

@heejaechang has changed the IDE diagnostic engine and @CyrusNajmabadi has refactored the FixAll code base quite a bit for Update3. I'd really love this test to be in place to sign off on the new diagnostic engine. Large regressions such as https://github.com/DotNetAnalyzers/StyleCopAnalyzers/pull/1979#issuecomment-166654999 (Update1) can creep in any time without a perf test for FixAll.

**Comment by mavasani** [comment]
So I did some manual testing around FixAll ocurrences with v2 diagnostic engine (latest bits) and there seems to be a **huge** performance regression with FixAll across project using the batch fixer. The performance is extremely good for stylecop fix all, which have a custom FixAll provider. I am going to file an urgency-soon bug with the details, and mark this perf test as urgency soon as well.

**Comment by mavasani** [comment]
Okay, so the extremely slow performance that I saw from batch fixer (1:20) was with Debug bits in RoslynDev hive - the performance is comparable with release bits (1:2 compared to stylecop batch fixer). We still need to investigate and figure out if this is indeed a regression, and if so a recent one post Udpate2.

**Comment by CyrusNajmabadi** [comment]
Note: performance of fix-all is in a good place.  I don't see value in this tracking issue.  EIther we actually make a perf test or we don't.  THe presence/absence of this issue doesn't impact that thinking.
