### ISSUE TITLE
No ability to disable fading for unused private methods analyzer

### ISSUE THREAD

**Issue by timheuer** [dotnet/roslyn#76396]
## Summary
IDE00051 basically grays out unused private methods. Customers are not liking this but also don't want to disable the analyzer all together. It's the visual representation that is annoying. There are also areas where methods are used dynamically that analyzers don't know about.

## Background and Motivation
We have other analyzers that 'fade' views, but we enable a toggle to disable the fade.
![Image](https://github.com/user-attachments/assets/f5eb3c74-3fb5-421c-b501-ecf26a5fbb87)

## Proposed Feature
Add the ability to disable the fade with this analyzer

**Comment by raffaeler** [comment]
I started suppressing the IDE0051 with a GlobalSuppression.cs in my project but it’s time expensive and I don’t find this to be appropriate for some reasons:
1.	This is my own choice. Other users may find the fade-out code useful. The GlobalSuppression.cs does not respect users’ choices
2.	The Analyzer finds an “issue” but the way the IDE “notifies” this issue to the user should be left to the IDE and configured by the users (in Tools-Options)
3.	There are several good reasons to keep away the fade-out from some methods as the are used dynamically or via interop. In this specific case, there is probably the need to pair this analyzer with an attribute informing the analyzer to ignore them.
 
Said that, I don’t like the current behavior at all.

**Comment by CyrusNajmabadi** [comment]
Seems reasonable to have an option here.

**Comment by raffaeler** [comment]
BTW, I hope we don't end up in only having to use an attribute to suppress it.
During the development, it's quite common to start writing code that isn't called yet. In this case you are still modifying the code which is grayed and very hard to read.
Before suppressing the IDE0051 in the file, I used to close VS and continue coding with VSCode, which is really a defeat for VS.

**Comment by CyrusNajmabadi** [comment]
> BTW, I hope we don't end up in only having to use an attribute to suppress it.

As mentioned, it seems reasonable for there to be an option controlling this.

**Comment by sharwell** [comment]
@CyrusNajmabadi What about making the current "Fade out unreachable code" option apply to this as well?

**Comment by CyrusNajmabadi** [comment]
@sharwell i'm not opposed to that. both are conceptually 'unreachable'  either because flow analysis says we can't reach a particular statement, or because there's no reference to some private member.

**Comment by CyrusNajmabadi** [comment]
We would take an appropriately sized community pr here.

**Comment by ddobric** [comment]
The current fade-out behaviour is disruptive. When writing new private methods, they are not immediately used, and I do not want them to be greyed out. However, the concept of fading out unused methods is excellent.

My recommendation is to include a menu item (possibly in the code analyzer) that allows developers to manually check for unused methods in the code. This approach aligns better with the typical development process.

**Comment by Dreamescaper** [comment]
Would it be possible to disable fading when the cursor or caret is on that code block?
I'm fine with fading unused code, but not when I'm actually writing it.

**Comment by andypoly** [comment]
> ## Summary
> IDE00051 basically grays out unused private methods. Customers are not liking this but also don't want to disable the analyzer all together. It's the visual representation that is annoying. There are also areas where methods are used dynamically that analyzers don't know about.
> 

Perfect summary! - it seems an introduced 'feature' which should have therefore been 'opt-in' or easily disabled by a menu option. Personally I really dislike it!

**Comment by raffaeler** [comment]
How does the analyzer read the VS checkboxes values?
Is there a doc describing this mechanism?

**Comment by janseris** [comment]
This behavior is now even worse in 17.13.
Now also currently written method is dark.

https://github.com/user-attachments/assets/ed3829b1-ac2f-47ca-aa6d-183ec58ba21a

**Comment by CyrusNajmabadi** [comment]
Roslyn does not control how fading looks. For that, please file an issue with visual studio (that is not us) 

If you want to disable fading for this, you can do so @janseris

**Comment by CyrusNajmabadi** [comment]
@janseris 

>  Change in plus/minus signs for expanding sections in code, 

That is not Roslyn. Please file reports with visual studio. 

> broken Blazor C# code editor for many years since its launch in winter 2021, 

That is not Roslyn. Please let razor or visual studio know. 

> slower and buggy syntax and code coloring 

I'm unaware of any slowdowns here (no customer telemetry indicates any issues there). If you are having issues with these, please file issues. It may be something specific to your configuration.

**Comment by janseris** [comment]
> [@janseris](https://github.com/janseris)
> 
> > Change in plus/minus signs for expanding sections in code,
> 
> That is not Roslyn. Please file reports with visual studio.
> 
> > broken Blazor C# code editor for many years since its launch in winter 2021,
> 
> That is not Roslyn. Please let razor or visual studio know.
> 
> > slower and buggy syntax and code coloring
> 
> I'm unaware of any slowdowns here (no customer telemetry indicates any issues there). If you are having issues with these, please file issues. It may be something specific to your configuration.

I have been filing issues like crazy in Visual Studio Feedback since launch of Visual Studio 2022 in winter 2021 but nothing changed. I give up. GitHub issues are at least tracked.

What is exactly Roslyn? That will help me distinguish where to write the issue. Thank you.

**Comment by CyrusNajmabadi** [comment]
> I have been filing issues like crazy in Visual Studio Feedback since launch of Visual Studio 2022 in winter 2021 but nothing changed. 

Sorry about that. We can't help with that. It's up to individual vs teams to prioritize issues. If they get very low volumes of feedback, they will often not view a change a worth making (same with us)

> What is exactly Roslyn? That will help me distinguish where to write the issue.

We provide c# and VB language analysis support. That then plugs into tools like VS/VSCode/other-tools to give rich language understanding. 

> How can I disable the fading completely like it was in 17.10 or 17.11 and older (or just reverting to 17.10 would be enough! but I can't do it, I can just revert to previous Visual Studio version which is some kind of 17.12 patch which already has all the issues).

There is an option under tools|options|languages|c#|advanced controlling fading.  I'm not in front of a computer, so I can't provide a screen shot right now. 

It will be something like: fade unused members.

**Comment by raffaeler** [comment]
FYI: I just found a bug.
If you turn the fading option off, the unused code is still faded out.
I **must** close the file and re-open to see the unused code unfaded.

@CyrusNajmabadi is this a Roslyn or a VS bug? (Where should I open the issue?)

**Comment by CyrusNajmabadi** [comment]
That's a Roslyn bug.

**Comment by raffaeler** [comment]
@CyrusNajmabadi do you want me to open a new issue or you keep this one as the reference for this bug?

**Comment by CyrusNajmabadi** [comment]
Make a new issue. This issue is closed as completed.

**Comment by jacktilford** [comment]
Hi Cyrus! An option is not the solution here. I like fading out unused code. I do not like (correction: I despise with prejudice) having a new method faded out while I am working on it before it is called (which is simply nuts). Perhaps the solution is to fade out only the method name rather than the whole thing. 
--Jack Tilford
