### ISSUE TITLE
The warning about `yield return` in lock statements (CS9237) is documented in reference but not implemented.

### ISSUE THREAD

**Issue by Akeit0** [dotnet/roslyn#76442]
https://github.com/dotnet/roslyn/issues/46004

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/iterator-yield#restrictions-on-iterator-methods
> CS9237: ''yield return' should not be used in the body of a lock statement

>You can't yield return from inside a lock statement block. Doing so can cause deadlocks.

https://github.com/dotnet/roslyn/blob/633f34af4fe019eaf0c2e830bdc07c891ecd49f7/src/Compilers/CSharp/Portable/Errors/ErrorCode.cs#L2315

**Comment by jcouv** [comment]
Updating docs accordingly: https://github.com/dotnet/docs/pull/43988
