### ISSUE TITLE
Unable to load analyzer assembly when targeting ARM64

### ISSUE THREAD

**Issue by exchange321** [dotnet/roslyn#76467]
This is Alfred from the M365 Clipchamp team. We've recently added a source generator project using `Microsoft.CodeAnalysis`, but we've run into an issue that the compiler complains that it isn't able to load the generator project DLL, and it occurs ONLY when we target ARM64: it builds fine when targeting x64. We are running out of ideas so reaching out to see if you have ideas about what we might have done wrong, or further contacts who you think might be able to help 🙏.

**Version Used**: 
Microsoft.CodeAnalysis.CSharp 4.12.0

**Steps to Reproduce**:
1. Clone [this Clipchamp repo branch](https://onedrive.visualstudio.com/Clipchamp/_git/clipchamp-native?path=%2F&version=GBchore%2Fsource-gen-for-polymorphic-deserialization&_a=contents)
2. Open Clipchamp.sln with Visual Studio
3. Copy Clipchamp\App.Local.config into Clipchamp\App.config
4. Build Clipchamp.csproj targeting ARM64

**Diagnostic Id**:
CS8034: Unable to load Analyzer assembly C:\Users\alfredsee\source\repos\clipchamp-native\Clipchamp.Generators\bin\ARM64\Debug\netstandard2.0\Clipchamp.Generators.dll : Unable to load Clipchamp.Generators

P.S.: I can confirm that ^ DLL exists in ^ directory.

[Link to failed build with ^ error](https://onedrive.visualstudio.com/Clipchamp/_build/results?buildId=37513362&view=logs&j=5eb83ddc-153a-5aa6-a621-addb40ff91ce&t=0d34343a-b43e-5996-a321-b20479a60827)

**Expected Behavior**:
The build should pass when targeting ARM64 just like when targeting x64.

**Actual Behavior**:
The build fails with the following error:
```
1>CSC : warning CS8034: Unable to load Analyzer assembly C:\Users\alfredsee\source\repos\clipchamp-native\Clipchamp.Generators\bin\ARM64\Debug\netstandard2.0\Clipchamp.Generators.dll : Unable to load Clipchamp.Generators
```

**Comment by Youssef1313** [comment]
Maybe you are hitting the same as https://github.com/dotnet/roslyn/issues/70148 ?
Can you try the suggestion described in the issue?

**Comment by exchange321** [comment]
Hi @Youssef1313, thanks for the tips! I tried the suggested approach and it does work in my local machine, but for some reason it continues to fail in CI with [a different error](https://onedrive.visualstudio.com/Clipchamp/_build/results?buildId=37567203&view=logs&j=5eb83ddc-153a-5aa6-a621-addb40ff91ce&t=0d34343a-b43e-5996-a321-b20479a60827):
```
##[error]C:\hostedtoolcache\windows\dotnet\sdk\8.0.404\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): Error NETSDK1047: Assets file 'D:\a\_work\1\s\Clipchamp.Generators\obj\project.assets.json' doesn't have a target for 'netstandard2.0/win-arm64'.
Ensure that restore has run and that you have included 'netstandard2.0' in the TargetFrameworks for your project. You may also need to include 'win-arm64' in your project's RuntimeIdentifiers.
```
I tried to follow the error description by adding `<RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>` to the generator project, but it ended up with [the same error](https://onedrive.visualstudio.com/Clipchamp/_build/results?buildId=37567430&view=logs&j=5eb83ddc-153a-5aa6-a621-addb40ff91ce&t=0d34343a-b43e-5996-a321-b20479a60827) as before:
```
2>CSC : warning CS8034: Unable to load Analyzer assembly D:\a\_work\1\s\Clipchamp.Generators\bin\Debug\netstandard2.0\win-arm64\Clipchamp.Generators.dll : Unable to load Clipchamp.Generators [D:\a\_work\1\s\Clipchamp\Clipchamp.csproj]
```

Our team is quite new to Windows app development so please bear with us if we're missing some obvious things 🙏

**Comment by Youssef1313** [comment]
I don't think it's correct to add `<RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>` to the source gen project. In your CI artifacts I can't see a binlog. It may be useful to produce a binlog if you don't already (better to not share it publicly as it contains the contents of all your csproj,props,targets files).

**Comment by exchange321** [comment]
Hi @Youssef1313, is [this](https://learn.microsoft.com/en-us/visualstudio/msbuild/obtaining-build-logs-with-msbuild?view=vs-2022) the correct guide to generate the binlog you mentioned?

**Comment by Youssef1313** [comment]
In your build step, I think you need to modify `msbuildArgs` to have: `/bl:$(Build.ArtifactStagingDirectory)/build-package.binlog`

**Comment by exchange321** [comment]
@Youssef1313 the binlog is in [this build's artifact](https://onedrive.visualstudio.com/Clipchamp/_build/results?buildId=37575140&view=artifacts&pathAsName=false&type=publishedArtifacts) 🙏

**Comment by Youssef1313** [comment]
@exchange321 Can you try adding `GlobalPropertiesToRemove="AppxBundlePlatforms;AppxPackageDir;UapAppxPackageBuildMode;AppxPackageSigningEnabled"` in addition to the `SetPlatform` you already added?

**Comment by exchange321** [comment]
@Youssef1313 it seems like it ended up with [the same errors](https://onedrive.visualstudio.com/Clipchamp/_build/results?buildId=37589230&view=logs&j=5eb83ddc-153a-5aa6-a621-addb40ff91ce&t=0d34343a-b43e-5996-a321-b20479a60827) 😔 binlog can be found [here](https://onedrive.visualstudio.com/Clipchamp/_build/results?buildId=37589230&view=artifacts&pathAsName=false&type=publishedArtifacts)

**Comment by Youssef1313** [comment]
For some reason, `GlobalPropertiesToRemove` isn't doing what I would expect. @jaredpar may be better to advise better.

**Comment by exchange321** [comment]
@Youssef1313 No worries, really appreciate your help 🙂

**Comment by Youssef1313** [comment]
Actually looking once again, your ProjectReference in the generator is missing `ReferenceOutputAssembly="false"`

**Comment by exchange321** [comment]
Hmm... there are classes in the generator project that the main project needs, that's why we didn't set `ReferenceOutputAssembly="false"`

**Comment by Youssef1313** [comment]
Couldn't you link the source files that you need in the main project instead of referencing the generator assembly? i.e, using `<Compile Include="..." />`?

**Comment by exchange321** [comment]
Hmm... wasn't aware of that before... I'll give it a try 👍

**Comment by exchange321** [comment]
Adding `ReferenceOutputAssembly="false"` does work~ thanks a lot @Youssef1313!!
