### ISSUE TITLE
"Requires `unsafe` context" error in an `unsafe` iterator

### ISSUE THREAD

**Issue by xparadoxical** [dotnet/roslyn#76514]
**Version Used**: 
Compiler version: '4.12.0-3.24572.7 (dfa7fc6b)'. Language version: 13.0.
**Steps to Reproduce**:
`unsafe IEnumerable<int> M() { int* i = null; yield return 1; }`
([sharplab](https://sharplab.io/#v2:EYLgtghglgdgPgAQAwAIEEYAsBuAsAKAIFcYBnCAMwFM10BmAHlgBcA+FAWQAoBKFAbxQsAVEJQBeFDCIAbGdlro0AdhToFAXyA=))

**Diagnostic Id**:
> CS0214: Pointers and fixed size buffers may only be used in an unsafe context

**Expected Behavior**:
Compiles, since the entire method is unsafe so pointers should be allowed without an explicit `unsafe` block.
**Actual Behavior**:
Doesn't compile, you have to use `unsafe { int* i = null; }`.

**Comment by huoyaoyuan** [comment]
It's intentional breaking change: https://github.com/dotnet/roslyn/blob/main/docs/compilers/CSharp/Compiler%20Breaking%20Changes%20-%20DotNet%209.md#iterators-introduce-safe-context-in-c-13-and-newer

**Comment by xparadoxical** [comment]
> If an iterator declaration is marked with the unsafe modifier, the signature is in an unsafe scope but the iterator block used to implement that iterator still defines a safe scope.
Well that's sad. I thought my example would be equivalent to `IEnumerable<int> M() { unsafe { int* i = null; } yield return 1; }`, in other words yield returns which can't be in unsafe context would implicitly divide the unsafe context into smaller unsafe blocks. This doesn't seem to have been considered, looking at the 8th bullet point of the "alternatives" section. Unsafe blocks add a level of indentation, which is why I always prefer to mark entire members as unsafe.

**Comment by jcouv** [comment]
Thanks @huoyaoyuan for digging up the reference. This was indeed by design: "If an iterator declaration is marked with the unsafe modifier, the signature is in an unsafe scope but the iterator block used to implement that iterator still defines a safe scope."
But I don't recall the motivation for that choice. Tagging @jjonescz for comment. Thanks

**Comment by jjonescz** [comment]
> But I don't recall the motivation for that choice.

The speclet has the motivation in https://github.com/dotnet/csharplang/blob/main/proposals/csharp-13.0/ref-unsafe-in-iterators-async.md#alternatives:

![Image](https://github.com/user-attachments/assets/837109e0-ad1d-44bd-96fa-f7d8a993dc4c)

> I thought my example should be equivalent to `IEnumerable<int> M() { unsafe { int* i = null; } yield return 1; }`, in other words yield returns which can't be in unsafe context would implicitly divide the unsafe context into smaller unsafe blocks. This doesn't seem to have been considered, looking at the 8th bullet point of the "alternatives" section.

That indeed wasn't considered (fwiw it looks like an overly complicated language rule to me), but feel free to open a lang proposal for that in https://github.com/dotnet/csharplang.
