### ISSUE TITLE
SyntaxVisualizer is getting assembly conflicts warnings on build machines

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#7651]
15:54:17 BUILD WARNINGS for d:\j\workspace\dotnet_roslyn_prtest_win_vsi_p1\Closed\Setup\Setup.proj
15:54:17 22:58:04.355    12>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [d:\j\workspace\dotnet_roslyn_prtest_win_vsi_p1\Open\src\Tools\Source\SyntaxVisualizer\SyntaxVisualizerControl\SyntaxVisualizerControl.csproj]
15:54:17 22:58:04.514    13>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [d:\j\workspace\dotnet_roslyn_prtest_win_vsi_p1\Open\src\Tools\Source\SyntaxVisualizer\SyntaxVisualizerDgmlHelper\SyntaxVisualizerDgmlHelper.vbproj]
15:54:17 22:58:06.369    11>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.Collections.Immutable, Version=1.1.36.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [d:\j\workspace\dotnet_rosly

**Comment by jmarolf** [comment]
Issue moved to [dotnet/roslyn-sdk #50](https://github.com/dotnet/roslyn-sdk/issues/50) via [**ZenHub**](https://www.zenhub.com/)
