### ISSUE TITLE
fix(DebuggerNonUserCode) DebuggerNonUserCode inoperative

### ISSUE THREAD

**Issue by kimdiego2098** [dotnet/roslyn#76533]
**Version Used**: 
VS2022 17.12.3
**Steps to Reproduce**:

https://devblogs.microsoft.com/devops/performance-improvement-when-debugging-net-code-with-visual-studio-2015/

This blog introduces the debuggerNonUserCode and includes a test demo, but in VS2022, it was found to be ineffective. Did this feature be removed during the update iteration

[ExceptionTest.zip](https://github.com/user-attachments/files/18206069/ExceptionTest.zip)

**Comment by CyrusNajmabadi** [comment]
Closing out.  This is not a Roslyn issue.  If you're having an issue with VS and its debugger, you can use the following feature within VS to report the problem:

![Image](https://github.com/user-attachments/assets/bbb9c4b1-11e9-4445-8b41-507131b8b0a1)
