### ISSUE TITLE
The Remove Unused References Dialog option should take vulnerable libraries into account

### ISSUE THREAD

**Issue by webreidi** [dotnet/roslyn#76540]
## Summary

In the remove unused references dialog, the vulnerability database info is not integrated. The UI suggests to remove a dependency that once removed, the parent UI will complains that a project contains vulnerable packages.

The UI should warn the user that if he removes this “unused” reference, it will instead rely on a vulnerable transitive one.

Copied from: https://developercommunity.visualstudio.com/t/The-Remove-Unused-References-Dialog-opti/10793010

**Comment by CyrusNajmabadi** [comment]
This should move to nuget or whoever owns the package manager system.  Roslyn shouldn't be in the business of having to understand things like a "vulnerability database".  We should just be in hte business of saying "this reference is used or not", and allowing domain experts in the package/reference management space take control at that point.

**Comment by webreidi** [comment]
NuGet already has a mechanism to determine if the package is vulnerable or not (they started exposing warnings to users with .NET9), although not sure if they expose it via an API for Roslyn to use. This feature request is a combination of the two, so would require they expose that information to Roslyn. So, if Roslyn has a "remove unused usings" action for the user, but by removing it, it uses a vulnerable package, there is a warning beforehand.

**Comment by CyrusNajmabadi** [comment]
> So, if Roslyn has a "remove unused usings" action for the user, but by removing it, it uses a vulnerable package, there is a warning beforehand.

Roslyn should not be removing packages ourselves.  We pass this info along to the package manager.  The package manager itself can/should warn if they feel that that is appropriate.  

Roslyn doesn't want to have to query external systems about their domain expertise to surface that in our world.  That's an unending amount of work/consideration/cost.  Our responsibility here is determining that the reference is unused.  That's what maps into the world of compilers.  We then let the user know.  THe user then chooses to remove, which goes to the package manager.  The package manager can then say if there's a concern with that.  

> This feature request is a combination of the two, 

I understand.  I'm just saying that that shoudl be outside of roslyn.  Even having this be part of roslyn means that roslyn is now part of a security handshake of a system that we are not security experts in.  We should *not* be doing that as there is virtually no way we can make informed, correct, security design decisions.  We need to defer that to the teams that can, and have them decide how to present that experience to the user.

**Comment by CyrusNajmabadi** [comment]
I'm closing this out.  THe original devcom issue is the right place to track this, as this is something that should happen for VS as a whole with package management.
