### ISSUE TITLE
Records won't warn about an unimplemented abstract ToString

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#76554]
**Version Used**:  https://github.com/dotnet/roslyn/commit/98ea496177bc8e607dbf454abd6b5a5e4678aed2

**Steps to Reproduce**:

```cs
abstract class ClassBase
{
    public abstract override string ToString();
    sealed class Class : ClassBase; // error
}
abstract record RecordBase
{
    public abstract override string ToString();
    sealed record Record : RecordBase; // ok (error expected)
}

```

**Expected Behavior**: `error CS0534: 'RecordBase.Record' does not implement inherited abstract member 'RecordBase.ToString()'`

**Actual Behavior**: there's no error on the record declaration.

**Comment by CyrusNajmabadi** [comment]
Why should this be an error?  The compiler synthesizes ToString for all records, right?  So the method will be implemented.

**Comment by CyrusNajmabadi** [comment]
Abstract means an override must be provided. The compiler provides that override. It has nothing to do with the user providing it or not :-)

**Comment by CyrusNajmabadi** [comment]
I don't know what you're asking for here.  You said you thought this was a bug.  I'm saying that i don't think this is a bug in the compiler, and the compiler is doing exactly the right thing as far as the language is concerned.  At no point in the design of records did we say that if the base method is abstract that you would then have an error if the user didn't implement the method in source themselves.

If you want that, you'd need to propose a language change over at csharplang.
