### ISSUE TITLE
Invalid suggestion for dictionary collection expressions

### ISSUE THREAD

**Issue by hamarb123** [dotnet/roslyn#76555]
**Version Used**:

VS Code with C# extension `v2.55.29`, and C# Dev Kit `v1.14.14`

<details>
<summary>Full information</summary>
Extension version: 2.55.29
VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Darwin x64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|8, 10, 9|
|Memory (System)|64.00GB (0.27GB free)|
|Process Argv|--crash-reporter-id 0ba11368-f3f3-4deb-a46c-5d04cc05b7c6|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupytercf:31046870
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc1:31192215
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530
6074i472:31201624

```

</details>

</details>

**Steps to Reproduce**:

```csharp
string[] names = [/*some collection*/];
Dictionary<string, int> namesInverse = new(names.Select((x, i) => new KeyValuePair<string, int>(x, i)));
```

**Diagnostic Id**:

`IDE0028`

**Expected Behavior**:

No suggestion to use dictionary expressions as they do not exist.

**Actual Behavior**:

![Image](https://github.com/user-attachments/assets/7c595084-a974-4c84-91e7-23beb28dc332)

Following the suggestion obviously gives invalid code:

![Image](https://github.com/user-attachments/assets/094d234c-9b6c-498e-a228-e50aa0453027)

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/75897
