### ISSUE TITLE
WithEvents in heritance chain

### ISSUE THREAD

**Issue by Volker-V** [dotnet/roslyn#7659]
If you define three handlers of the same event using Visual Basic `WithEvents` and `Handles` keywords, one of the handlers will not be called. I encountered this issue in Visual Studio 2015. After Update 1 it still remains.

I have written a [test solution](https://github.com/dotnet/roslyn/files/69472/WithEventsTest.zip) and posted this issue on [stackoverflow](http://stackoverflow.com/questions/33608936/withevents-bug-in-visual-studio-2015).

**Comment by Styxion** [comment]
Hello,

we have the same problem. If there is a heritance chain of 3 classes and a minimum of 2 handlers which handles the same event, one of the handlers is not registered.
Is a hotfix available? If not - when will this compiler-bug be fixed? 

It's very expensive to find this bug...
