### ISSUE TITLE
Allow nameof on declarations with var

### ISSUE THREAD

**Issue by JoshVarty** [dotnet/roslyn#766]
I ran into a limitation of `nameof` today shown in the code below:

```CSharp
string test = nameof(test); //Valid
var test2 = nameof(test2); //Error: Cannot use local variable before it is declared.
```

The motivating use-case (for me) is logging assignments and declarations of variables.

I wish to turn this:
```CSharp
var test = "Hello World";
```
into this:
```CSharp
var test = Log(nameof(test), "Hello World");

...

public static T Log<T>(string name, T value)
{
    //store info such as name and value

    return value;
}

```

I scanned http://roslyn.codeplex.com/discussions/570551 and didn't see any mention of this. Was it a conscious design decision to limit `nameof` in this case? Perhaps it's too difficult to do type inference in this case?

I'd love to get some feedback on the feasibility of such a feature.

**Comment by AdamSpeight2008** [comment]
I thought that `nameof` feature didn't care about the type, all that was required is that the token can be classified as an identifier. eg a named variable.

**Comment by gafter** [comment]
@MadsTorgersen @ljw1004 thought you might want to comment on this. The spec implies the current behavior, but that is obviously not what we would want here.

**Comment by gafter** [comment]
The same issue occurs for VB:

```vb
Dim test2 = Nameof(test2); //Error: Type of 'test2' cannot be inferred from an expression containing 'test2'
```

**Comment by gafter** [comment]
I'm going to put this on the back burner until the next language design meeting. If we find this programming idiom compelling, then we'd want to see what the cost is in terms of the added specification complexity. If the idiom is not compelling, then we'd probably leave things in their current state.

Note that it is possible to compatibly support this later, as the change to supporting this idiom only turns programs that would not compile into programs that would compile. It doesn't change the meaning of any correct program.

//cc @AnthonyDGreen @mattwar @Pilchie @stephentoub

**Comment by JoshVarty** [comment]
Sounds good to me. I'm not completely convinced it's worth the additional complexity.

In the use-case I described earlier, we realized the proper approach to rewrite to:

```CSharp
var test = Log("test", "Hello World");
```
instead of:
```CSharp
var test = Log(nameof(test), "Hello World");
```

So we ultimately didn't need this functionality anyways.

**Comment by ljw1004** [comment]
Josh, could you also tell me since I don't understand by looking at it -- what's the goal of your code? what goal were you originally hoping to achieve with Log(nameof(test),...) ?

**Comment by JoshVarty** [comment]
We're rewriting code at edit time, compiling it, running it and showing the results of that code. It's a tool similar to Light Table (At 1:20 he demonstrates a similar feature)

The code I was demonstrating occurs at the rewrite phase. We're logging all assignments and declarations as the code is running.

**Comment by gafter** [comment]
The LDM confirmed that this is an implication of the spec.
