### ISSUE TITLE
VS2015.1: F12 in the interactive window can produce weird results

### ISSUE THREAD

**Issue by Suchiman** [dotnet/roslyn#7661]
I was testing some code in the interactive window and was bugged that i couldn't see any documentation in IntelliSense so i pressed `F12` :smile: but MetadataAsSource wasn't any more helpful :wink:

On the right side you can see the MetadataAsSourceProject opened by pressing F12 in the interactive window, on the left side you see the MetadataAsSourceProject opened by copying the code from InteractiveWindow into my source and pressing F12 there.
![interactivemetadataassource](https://cloud.githubusercontent.com/assets/7110884/11954984/bf6738ae-a8ad-11e5-8a1d-9fac02f4245d.png)

**Comment by SergeyZhurikhin** [comment]
I have the same behavior (VS2015.1 Russian). Window "C# Interactive" It uses a path for assemblies in .NET Framework, but the IDE in Reference Assemblies.
IDE:
```CS
#region Сборка mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
// C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\mscorlib.dll
#endregion
```
Window "C# Interactive":
```CS
#region Сборка mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
// C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll
#endregion
```
I would like a uniform behavior.

**Comment by tmat** [comment]
The underlying issue is the same as https://github.com/dotnet/roslyn/issues/5013. The interactive code compiles against implementation assemblies. We don't have logic that would map them to the reference assemblies and get the doc comments.
