### ISSUE TITLE
Proposal: Escaping double quotes

### ISSUE THREAD

**Issue by andrew-vandenbrink** [dotnet/roslyn#7662]
Double quotes and quote are commonly used in any text.

```
"This \" is not very readable."
@"This "" one also"
```

Please consider how to can c# have readable double quotes in text

```
@`Something like this maybe? As we can use " and ' without any escape
perhaps with new line too`
```

**Comment by HaloFour** [comment]
Check out #2239.

**Comment by alrz** [comment]
I thought this is about identifiers. OMG.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
