### ISSUE TITLE
Proposal: auto property backing field reference resolving when used as ref and out arguments

### ISSUE THREAD

**Issue by m0sa** [dotnet/roslyn#7678]
It would be great if auto properties would automatically reslove to their backing filed, allowing us to pass them to methods as ref and out arguments:

``` csharp
public class Foo
{ 
     public int Bar { get; set; }
     public void Test(string str)
     {
          int.TryParse(str, out Bar);
     }

     public int Baz { get; } // readonly
     public Foo(string str) // ctor
     {
          int.TryParse(str, out Baz); // Bar = 1  would also get translated in <Bar_backingField> = 1
     }   
}
```

this proposal is about making the private backing fields available, as it is already the case with setters for read-only properties in the constructor. The code above should be equivalent to:

``` csharp
public class Foo
{
     private int _bar;
     public int Bar { get { return _bar; } set { _bar = value; } }
     public void Test(string str)
     {
          int.TryParse(str, out _bar);
     }

     private readonly int _baz;
     public int Baz { get { return _baz;  }
     public Foo(string str) // ctor
     {
          int.TryParse(str, out _baz);
     }   
}
```

...and thus only work inside the class declaring the property.

**Comment by NickCraver** [comment]
I'd love to see this as well, but more for interlocked operations that can't use auto properties today either. I think it's currently a gap in the goals of terseness that auto properties are after.

**Comment by svick** [comment]
I think this goes against the goal of properties, which is to hide the implementation.

For example, right now, you can change an auto-property to a normal property and all code that uses it will still work. (There is one exception: writing to get-only auto-properties.) This proposal would break that. 

Also, this is not clearly stated in the proposal, but I assume this would work only inside the class (since the generated field is private), right?

**Comment by m0sa** [comment]
@svick I've clarified my proposal. I think because of get-only auto-properties your point is invalid.

**Comment by alrz** [comment]
I think you'd better use #6183, something like `out Bar` smells and won't compile if you decide to use normal properties (which is the point, properties hide the implementation).

**Comment by m0sa** [comment]
@alrz to me, it doesn't smell any more than the read-only auto property setter in the constructor.

Just for comparison:
```csharp
// regular field
public class Foo
{
    private readonly int _bar;
    public int Bar => _bar;
    public Foo(int bar) { _bar = bar; }
    public Foo(string bar) { int.TryParse(bar, out _bar); }
}

// auto property
// spares me from typing `private readonly int _bar;` but forces me to write this:
// 2 additional statements for nothing + I hate that I can't write `var parsed;`
public class Foo
{
    public int Bar { get; }  
    public Foo(int bar) { Bar = get; } // check, we're still on the upside
    public Foo(string bar) // sad trombone
    {
        int parsed;
        int.TryParse(bar, out parsed);
        Bar = parsed;
    }
}
```
The suggested `int.TryParse(bar, out var parsed)` gets rid of the  `int parsed;` declaration, but the assignment still needs to be there. LOC-wise this makes it equal (-y bad) to manually declaring the backing field. So of course, the best of both worlds would be:

```csharp
    // ...
    public Foo(string bar) => int.TryParse(bar, out Bar);
    // ...
```

**Comment by jasonwilliams200OK** [comment]
protected bool SadTrombone => http://www.sadtrombone.com/?autoplay=true

**Comment by jveselka** [comment]
This would be very usefull. But why stop at autoprops?
```C#
int.TryParse(val, out Prop);
```
could mean
```C#
int temp;
int.TryParse(val, out temp);
Prop = temp;
```
Autoproperties could be optimized by the compiler to actually pass reference

Only possibly weird behavior is that multiple assignments in the method would not trigger setter multiple times.

**Comment by AqlaSolutions** [comment]
I would like to see this feature too! To avoid "implementation" problems I would allow such access for current class only. It also makes a sense because backing fields are private.

**Comment by m0sa** [comment]
@zippec that obviously wouldn't work for `ref` properties.

@AqlaSolutions yup, that's basically what a private access modifier on the backing field implies.

**Comment by ViIvanov** [comment]
Just for me, adding an ampersand (for example) before a name of the auto-property for reference to the backing field is better than implicit referencing in ref/out context:
```cs
public class Foo
{
    public int Bar { get; }  
    public Foo(string bar) { int.TryParse(bar, out &Bar); }
}
```
May be, ampersand should be changed to something else, because in unsafe context it not obvious.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
