### ISSUE TITLE
C#: incorrectly distinguishes between Func<TArg, Task> and Action<TArg> when resolving generic extension methods

### ISSUE THREAD

**Issue by wasabii** [dotnet/roslyn#7681]
I have the following snippet of code:

    Body = Activities.Invoke<int>(i =>
    {
        runCount++;
        throw new Exception("broke");
    }),

There are 16 available overloads of Invoke<>. These are the two that are confused. Roslyn is selecting the first.

`public static AsyncActionActivity<TArg1> Invoke<TArg1>(Func<TArg1, Task> func)`
`public static ActionActivity<TArg1> Invoke<TArg1>(Action<TArg1> action)`

Clearly, the first requires that the delegate returns a `Task`. In my example, I am returning nothing. I am throwing an `Exception`. The code compiles, selecting the `Func<int,Task>` signature, but then fails at runtime.

if I make one change to my original calling code block, the compiler chooses the correct implementation:

    Body = Activities.Invoke<int>(i =>
    {
        runCount++;
        throw new Exception("broke");
        return;
    }),

A useless `return` statement fixes it.

Whatever version is running in VS 2015 Update 1.  .Net 4.6.1 project.

**Comment by i3arnon** [comment]
IIUC this is by design and it matches the spec: http://stackoverflow.com/q/24316189/885318

**Comment by wasabii** [comment]
That's going to take me awhile to understand.

**Comment by wasabii** [comment]
Okay. That makes sense. Except for that the `return` fixes it, while ALSO raising a warning about unreachable code. So, the return is enough to change the operation of the code, but it warns that the value isn't useful.

That's a slight conflict.

**Comment by wasabii** [comment]
I notice also that this block of code works fine:

    Body = Activities.Invoke<int>(i =>
    {
        if (++runCount < 3)
            throw new Exception("Exception");
    }),

The difference being that it cannot prove that the method does not end, and so ... what? Neither method every actually returns anything, in any place.

**Comment by i3arnon** [comment]
@wasabii The point is that returning a value is prefered to not returning a value so `Func` is prefered over `Action`. Now, when there are no code paths out of the method at all, than the compiler has no reason to force it to be void returning so it doesn't. When there is a code path (e.g. if there's an `if` statement) that is `void` or when you explicitly specify the `return;` compiling as `Func` is no longer an option.

**Comment by svick** [comment]
@wasabii There is a difference between "doesn't return anything" (in other words, returns void) and "doesn't return at all" (e.g. because of a thrown exception).

**Comment by alrz** [comment]
Doesn't #1226 address this? then return type would be inferred as `never`, and the first overload wouldn't be selected.

**Comment by svick** [comment]
@alrz I hope not, that would be a breaking change.

**Comment by alrz** [comment]
@svick I think this is the consequence of combining #1226 and #5143, so you say those would not affect lambda expression type inference? e.g. `() => throw null;`

**Comment by gafter** [comment]
See [@i3arnon 's explanation](https://github.com/dotnet/roslyn/issues/7681#issuecomment-166946368) for why this is by design.
