### ISSUE TITLE
VB Rename Local perf regressed 1234.67 ms -> 2557.33 ms

### ISSUE THREAD

**Issue by KevinH-MS** [dotnet/roslyn#7687]
I believe there are traces for this scenario at:
[well known file share]\RoslynPerf\Traces\ROSLYN-4CORE\BasicPerfRenameRoslyn

Traces from 12/15 should be good, the ones from 12/17 should show the regression.

Perhaps related to https://github.com/dotnet/roslyn/issues/7446?

**Comment by KevinH-MS** [comment]
:christmas_tree:

**Comment by mavasani** [comment]
I checked in a change yesterday which might have helped IDE analyzer perf. We should recheck in vsuml after next insertion.

**Comment by rchande** [comment]
@mavasani It looks like we're spending significantly more in in "GetDiagnosticsForMethodBodiesInTrees"

Name
 microsoft.codeanalysis.visualbasic.ni!VisualBasicCompilation.GetDiagnosticsForMethodBodiesInTree
+ microsoft.codeanalysis.visualbasic.ni!VisualBasicCompilation.GetDiagnosticsForSyntaxTree
 + microsoft.codeanalysis.visualbasic.ni!SyntaxTreeSemanticModel.GetDiagnostics

Do you think rename is a scenario where we should simply suspend solution crawler?

**Comment by mavasani** [comment]
The change that I checked in towards the end of December specifically moved the analyzer execution to _not_ require invoking GetDiagnostics. Do we have recent traces showing GetDiagnostics is still the culprit?

**Comment by rchande** [comment]
@mavasani We got numbers today and rename is well within goal, so your change must have fixed it. Thanks!
