### ISSUE TITLE
[Test Failure] Test Failures in prtest/win/dbg/unit64 on PR #7672

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#7688]
PR: [#7672](https://github.com/dotnet/roslyn/pull/7672) *Guard against being passed bad symbols or expressions* by @jmarolf
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/2358/

**1 Test Failures:**
Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Classification.SyntacticTaggerTests.TestTagsChangedForEntireFile

**Issue 1: Test Failures**
There were test failures, see Test Results above.

The SyntacticTaggerTests appear flaky

**Comment by dpoeschl** [comment]
Dupe of https://github.com/dotnet/roslyn/issues/7196
