### ISSUE TITLE
Picasso Build perf regressed 30,481 ms -> 38,654 ms

### ISSUE THREAD

**Issue by KevinH-MS** [dotnet/roslyn#7689]
Ty, can you take a look at this new regression?  I checked on the ROSLYN-4CORE machine, and it *seems* that things are getting ngen'ed correctly now.

I can't find traces for this scenario on the build share, but the regression seems to have been introduced between 12/10 and 12/12.  See:

[well known file share]\RoslynPerf\ROSLYN-4CORE\PerfReports\Roslyn.DiffReport.2015.12.12[8.25].mht

**Comment by KevinH-MS** [comment]
:christmas_tree:

**Comment by TyOverby** [comment]
> it seems that things are getting ngen'ed correctly now 

Does that mean that we got our perf back?

**Comment by TyOverby** [comment]
Looks like this is a problem with jitting again.

There are a few binaries that we don't own that aren't included in this summary.

# NEW

Binary | JitTime msec
----------|-----------------
TOTAL | 8,454.8
C:\Program Files (x86)\MSBuild\14.0\Bin\Microsoft.CodeAnalysis.VisualBasic.dll | 3,479.6 
C:\Program Files (x86)\MSBuild\14.0\Bin\Microsoft.CodeAnalysis.dll | 1,730.2  
C:\Program Files (x86)\MSBuild\14.0\Bin\Microsoft.CodeAnalysis.CSharp.dll | 1,305.1 
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Collections.Immutable\v4.0_1.1.37.0__b03f5f7f11d50a3a\System.Collections.Immutable.dll | 440.4 

# BASELINE

Binary | JitTime msec
----------|-----------------
TOTAL | 5,522.7
C:\Program Files (x86)\MSBuild\14.0\Bin\Microsoft.CodeAnalysis.VisualBasic.dll | 2,154.8  
C:\Program Files (x86)\MSBuild\14.0\Bin\Microsoft.CodeAnalysis.dll | 1,051.4 
:\Program Files (x86)\MSBuild\14.0\Bin\Microsoft.CodeAnalysis.CSharp.dll | 821.1 
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Collections.Immutable\v4.0_1.1.37.0__b03f5f7f11d50a3a\System.Collections.Immutable.dll | 123.0

**Comment by TyOverby** [comment]
Looking at the traces anyway, it seems like we're spending more time in MSBuild, but there is less CPU activity going on while that program is running.

**Comment by KevinH-MS** [comment]
Are we loading ngen'ed (*.ni.dll) images?  I've updated the optprof training data several times, so I wouldn't expect extra jit'ing.

**Comment by KevinH-MS** [comment]
We are indeed loading the native images.  Confirmed in trace:

[well known file share]\RoslynPerf\Traces\ROSLYN-4CORE\RoslynFullSolutionBuild\635857704697387021.etl.zip

(this is a different test, but running on the same machine and also shows a regression that coincides with the Picasso regression)

**Comment by jaredpar** [comment]
Haven't we verified this was a machine issue?

**Comment by KevinH-MS** [comment]
No, it has not yet been confirmed (although it's very strong suspected).  I'm still struggling to produce new numbers from the automation (on the new machine).

**Comment by KevinH-MS** [comment]
Still struggling with the automation, but manual testing shows that this is almost certainly an issue with the old hardware.  Nothing further to do for 1.2, but moving to 1.3 until I have an automated run that confirms the manually produced numbers.

**Comment by jaredpar** [comment]
Did we eventually decide this was indeed a hardware issue?

**Comment by KevinH-MS** [comment]
We never conclusively established this, but the old system hasn't been able to successfully run in a month now.  Since we now have the new system up and running, I'm going to just close this.  We'll baseline results against Update 1 using the new hardware/runner.
