### ISSUE TITLE
Linq to SQL fails badly when there's a predicate passed through a select clause

### ISSUE THREAD

**Issue by markhurd** [dotnet/roslyn#7694]
As with most bugs, this was originally noticed with a relevant example, but I've reduced it here to a simple example that, as I say in comments, I don't mind if it's ment to fail, but it shouldn't be failing in the way that it is.

This was originally noted in LinqPad, where the setup of the example _is_ rather simple (find a Master database to connect to and past this code in a "VB Program":

    Sub Main
        Dim q = From t In Tables '{New With {.Name = "Test", .Object_id = 1}}.AsQueryable ' ' If you don't use Linq2SQL it all works correctly.
                Select t.Name, PredTest = Noop(t.Object_id, Function(m As Integer) m <> m) ' This fails with NullRefererenceException
                'Select t.Name, PredTest = Noop(t.Object_id, Function(m As Integer) (False And m <> m)) ' This fails with a complaint about a Boolean where a predicate is expected. (Seems to be premature optimisation! It does still happen with /o off though.)
                'Select t.Name, PredTest = Noop(t.Object_id) ' This works.
                'Select t.Name, PredTest = Noop(t.Object_id) + Noop(t.Object_id) ' If the two that fail can't work, I'd expect the error you get here.
    
        q.Dump
    End Sub
    
    Function Noop(Of T)(ByRef O As T, Optional Arg As Func(Of T, Boolean) = Nothing) As T
        Return O
    End Function

) but I've reproduced the problem in VS2015 Update 1:

    Imports System.Data.Linq

    Module Module1

    Sub Main()

        ' Through LinqPad I was able to just connect to a local master database and use the Tables view.
        ' The VS2015 task is a little harder. NB For this purpose I just want a non-empty table with at least one column, preferably two. Just change the types in the code to correspond to the type of the second column.
        ' Nevertheless, along with the code below, you need to:
        ' 1. Add a new item to the project, specifically a Data/Linq to SQL Classes I called MasterDataClasses.dbml
        ' 2. Connect to a master database in the Server Explorer.
        ' 3. Change the View of the master database to Object Type via right-clicking on the connection in Server Explorer.
        ' 4. Locate the System View called "tables" and drag it to the MasterDataClasses.dbml designer.

        Dim dc As New DataContext(My.Settings.masterConnectionString)
        Dim td = dc.GetTable(Of table)
        Dim q = From t In td '{New With {.name = "Test", .object_id = 1}}.AsQueryable ' ' If you don't use Linq2SQL all four alternates below work correctly.
                Select t.name, PredTest = Noop(t.object_id, Function(m As Integer) m <> m) ' This fails with NullRefererenceException
                'Select t.name, PredTest = Noop(t.object_id, Function(m As Integer) (False And m <> m)) ' This fails with an InvalidCastException re a Boolean where a predicate is expected, when the table isn't empty. (Seems to be premature optimisation! It does still happen with /o off though.)
                'Select t.name, PredTest = Noop(t.object_id) ' This works.
                'Select t.name, PredTest = Noop(t.object_id) + Noop(t.object_id) ' If the two that fail can't work, I'd expect the InvalidOperationException you get here.

        For Each n In q
            Console.WriteLine(n)
        Next
        Console.WriteLine("Completed!")
        If Debugger.IsAttached Then _
            Console.ReadLine()
    End Sub

    Function Noop(Of T)(ByRef O As T, Optional Arg As Func(Of T, Boolean) = Nothing) As T
        Return O
    End Function

    End Module

Note that this is probably two separate issues:

 1. The NullReferenceException passing a predicate at all (NB this example shows it's not related to the predicate containing Linq expressions that would make it rather likely it should fail to find a SQL expression)
 2. The InvalidCastException that seems to be due to a (Function() Constant) being "optimised" to (Constant) without letting something else know the type's changed. 

Of course, this is clearly well within Linq to SQL and so it is unsurprising I have confirmed I can see the same issues in C#.

**Comment by gafter** [comment]
@markhurd Am I correct that this is an attempt to report a bug in Linq to SQL, rather than in the compiler?

**Comment by mattwar** [comment]
Unless the behavior for this query changed (it worked before, doesn't now, etc) then this is only about LINQ to SQL's implementation and not the compiler.  If it used to work, then its likely the compiler has changed how some expression's are encoded and L2S doesn't deal with them correctly any more; L2S has not changed.

**Comment by markhurd** [comment]
I don't know if this has changed. I just reported the bug I found, but, yes, as I said in my initial report "this is clearly well within Linq to SQL", especially seeing as Linq to Objects works correctly (when you use the `In {New With ` commented out first line).

**Comment by VSadov** [comment]
I get exactly the same behavior with VS2013

The exceptions are happening inside System.Data.Linq and I cannot guess why. Possibly this query shape runs into some limitations of LINQ to SQL. 
However, we can certainly rule out a breaking change introduced in Roslyn compiler as the reason for the failures.

**Comment by jaredpar** [comment]
@VSadov should we move this bug to CoreFX then if it's not a compiler issue?

**Comment by VSadov** [comment]
This should be moved to wherever System.Data.Linq is maintained. It is not Roslyn and I do not think it is CoreFX either.

**Comment by GSPP** [comment]
I believe L2S is no longer being maintained since bugs do not seem to go away between releases of the .NET Framework. It would be awesome if L2S was open-sourced so that the community can fix bugs and other issues.

**Comment by jaredpar** [comment]
Thanks for taking the time to file this issue.  Closing though as this appears to be a bug in Linq2Sql vs. the Roslyn compiler. 

We contacted the Linq2Sql team about this issue.  They said the best place to file bugs on that project is via connect: 

> http://connect.microsoft.com/

**Comment by markhurd** [comment]
Now on Connect: https://connect.microsoft.com/VisualStudio/feedback/details/2353962
