### ISSUE TITLE
Two small changes to the pattern matching spec

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#7703]
Per https://github.com/dotnet/roslyn/issues/206#issuecomment-167268457

The use of a pattern in a `case` was intended to be an *extension* to the existing alternative of a constant expression. That should be clarified, though. In addition, it was intended that a *case-guard* could be used with a constant-valued `case`. I will amend the [spec](https://github.com/dotnet/roslyn/blob/future/docs/features/patterns.md) to clarify.

The `goto case` statement would be relaxed in two ways. First, the expression no longer needs to be a constant. Second, the expression no longer needs to correspond directly to a `case` label. Logically the `goto case` statement would take an expression and dispatches the whole `switch` statement with the new expression. This needs to be added to the [spec](https://github.com/dotnet/roslyn/blob/future/docs/features/patterns.md) too.

**Comment by HaloFour** [comment]
@gafter 

Example:

```cs
int i = 1;
bool b = false;
switch (i) {
    case 2 when b == true:
        Console.WriteLine("case 2 when b == true");
        break;
    case 2:
        Console.WriteLine("case 2");
        b = true;
        goto case (i + 1);
    default:
        Console.WriteLine("default");
        goto case 2;
};
```

Would print:

```
default
case 2
case 2 when b == true
```

**Comment by gafter** [comment]
@HaloFour That is a useful example for the spec, thanks!

**Comment by bondsbw** [comment]
Curious, does the following loop or halt?

```c#
int i = ...;
switch (i)
{
    case i:
       goto case i++;
    case i + 1:
       break;
}
```

**Comment by alrz** [comment]
@bondsbw A *constant-pattern* doesn't accept a general variable, just "a literal, the name of a declared `const` variable, or an enumeration constant". However, earlier in the spec, it is defined as a *shift-expression* which is not correct I guess.

**Comment by gafter** [comment]
@alrz this is a constant expression, not a constant pattern. That is an existing production in the language grammar not intended to be changed by the pattern-matching spec. In any case, you are correct to say that you cannot have an expression that is not a constant.

**Comment by alrz** [comment]
@gafter Yes, I meant that, well, *constant-pattern* defined as a *constant-expression* according to the spec. But in the "Pattern" section it is defined differently which I believe, is not intended.

**Comment by bondsbw** [comment]
Ah, I misinterpreted "First, the expression no longer needs to be a constant."  I thought that was intended for both ```goto case``` and ```case```.

**Comment by gafter** [comment]
Fixed in branch `features/patterns`.
