### ISSUE TITLE
Would it be possible to add enhanced support for nameof for method parameter names?

### ISSUE THREAD

**Issue by taori** [dotnet/roslyn#7706]
Let's say we have a method signature like this:

public IActionResult SomeMethod(int someParameter)

which is a common case in mvc.

When you're rendering action links or $.ajax calls you will have to pass route values which have to match the name of the parameter (unless something changed which i am unaware of). 

Let's say i am constructing a call like this:

`$.ajax("url" : "@Url.Action("SomeMethod", new {someParameter : "+someJsValue+"})");`

This might potentially break on refactoring unless you do careful checking or use workarounds to render the url (which i am doing currently).

This is why i thought it would be nice if roslyn offered the option of doing it like this:

`$.ajax("url" : "@Url.Action("SomeMethod", new {nameof(SomeMethod.someParameter) : "+someJsValue+"})");`

Since method calls usually provide parameter names of their declaration i figured the necessary information might already exist, to provide this feature.

Would this be an option?

**Comment by alrz** [comment]
Have you seen similar issues in MVC repo? like aspnet/Mvc/issues/2608 or aspnet/Mvc/issues/2015. I think you'd better open an issue there.

**Comment by taori** [comment]
Not yet no. I guessed the Roslyn team knows best about this while the use case scenario just belongs to mvc

**Comment by ashmind** [comment]
That is also useful for some DI registrations, e.g.:
```csharp
class SomeRepository {
    public SomeRepository(sring connectionString) {}
}

builder.RegisterType<SomeRepository>()
       .WithParameter("connectionString" /* needs nameof for ctor args */, connectionStringFromConfig)
```

**Comment by jamesbascle** [comment]
Have talked to a number of people about this recently.  Seems like a highly desired feature.  Seems folks expect
````C#
nameof(MyClass.MyMethod.MyParameter)
````
to work.  So throwing my hat in for support on this.  I specifically would like it for registering Castle interceptors with Autofac using the .WithParameter extension method on the ContainerBuilder.

**Comment by gafter** [comment]
Issue moved to [dotnet/csharplang #811](https://github.com/dotnet/csharplang/issues/811) via [**ZenHub**](https://www.zenhub.com/)
