### ISSUE TITLE
Public Sign does not work on Roslyn

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#7730]
Consider this branch:

- https://github.com/jaredpar/roslyn/tree/public-sign

This uses the latest toolsets, which have `/publicsign` support, to replace `FakeSign` in the build with `/publicsign`.  I have verified that `/publicsign` is being passed to the compiler via the MSBuild logs but also verified the signed bit is not being set.  No error is produced and `/publicsign` is not actually signing the bits.

**Comment by agocke** [comment]
I think this is #7734

**Comment by jaredpar** [comment]
Resolving as a dupe of #7734
