### ISSUE TITLE
SyntaxFactory.XmlEmptyName has incorrect default trailing trivia

### ISSUE THREAD

**Issue by DRAirey1** [dotnet/roslyn#7745]
If you use the following statement:

XmlSyntaxFactory.Text("Initializes a new instance of the "),
SyntaxFactory.XmlEmptyElement(
    SyntaxFactory.XmlName(SyntaxFactory.Identifier("see")))
    .WithLessThanToken(SyntaxFactory.Token(SyntaxKind.LessThanToken))
    .WithAttributes(
        SyntaxFactory.SingletonList<XmlAttributeSyntax>(
            SyntaxFactory.XmlCrefAttribute(
                SyntaxFactory.XmlName(SyntaxFactory.Identifier("cref")),
                SyntaxFactory.Token(SyntaxKind.DoubleQuoteToken),
                SyntaxFactory.NameMemberCref(SyntaxFactory.IdentifierName(this.uniqueConstraintSchema.Name)),
                SyntaxFactory.Token(SyntaxKind.DoubleQuoteToken))
            .WithEqualsToken(SyntaxFactory.Token(SyntaxKind.EqualsToken))))
    .WithSlashGreaterThanToken(SyntaxFactory.Token(SyntaxKind.SlashGreaterThanToken)),
XmlSyntaxFactory.Text(" class."))))));

You'll generate a comment that looks like this:

/// Initializes a new instance of the &lt;seecref="ConfigurationKey"/&gt; class.

Note that there's no space between the 'see' and the 'cref' words.  You need to explicitly add a trailing trivia whitespace to get it to work.

**Comment by mattwar** [comment]
None of the SyntaxFactory API's insert whitespace trivia. It's expected that syntax created via the factory is formatted before presentation. You can use the Formatter class in the workspace layer or the  SyntaxNode.NormalizeWhitespace API to adjust the whitespace.
