### ISSUE TITLE
Assigning void to a variable with dynamics

### ISSUE THREAD

**Issue by afscrome** [dotnet/roslyn#7751]
Consider the following program

```csharp
    public static class Program
    {
        public static void Main(string[] args)
        {
            var x = DynamicArg(123);
            var y = DynamicArg((dynamic)123);
            var z = StaticArg((dynamic)123);
        }

        public static void DynamicArg(dynamic arg1) { }
        public static void StaticArg(object arg1) { }
    }
```

The assignment to `x` correctly reports as a compile time error.  The assignments to `y` and `z` however succeed at compile time, but later fail at runtime with the error `Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot implicitly convert type 'void' to 'object'`.

I'd expect all three cases to be compile time failure - the method invocation on the right hand side of the assignment is guaranteed to return a void, so the assignment should not be allowed.

**Comment by bartdesmet** [comment]
Current behavior seems consistent with the language specification section 7.6.5 (Invocation expressions) where the expression is classified as a value of type `dynamic`, hence it is a valid rhs of an assignment expression:

```
An invocation-expression is dynamically bound (§7.2.2) if at least one of the following holds: 
•	The primary-expression has compile-time type dynamic.
•	At least one argument of the optional argument-list has compile-time type dynamic and the primary-expression does not have a delegate type.
In this case the compiler classifies the invocation-expression as a value of type dynamic. The rules below to determine the meaning of the invocation-expression are then applied at run-time, using the run-time type instead of the compile-time type of those of the primary-expression and arguments which have the compile-time type dynamic. If the primary-expression does not have compile-time type dynamic, then the method invocation undergoes a limited compile time check as described in §7.5.4.
```

This could be considered an extension of the interplay between section 7.6.5 and section 7.5.4 (Compile-time checking of dynamic overload resolution) of the language specification, if the rules in 7.5.4 would allow to determine the candidate set, and if it is not `unknown` an analysis of the set of types of those candidates (i.e. return types in the case of invocations) is performed to determine whether the result type is guaranteed to be `void` (if any candidate is non-void, a dynamic result type has to be assumed), where it meets the existing case in 7.6.5:

```
•	If the invocation-expression invokes a method or delegate that returns void, the result is nothing. An expression that is classified as nothing is permitted only in the context of a statement-expression (§8.6) or as the body of a lambda-expression (§7.15). Otherwise a binding-time error occurs.
```
