### ISSUE TITLE
Error squiggle in misleading place for setable indexer with an argument named 'value'

### ISSUE THREAD

**Issue by afscrome** [dotnet/roslyn#7753]
Consider the indexer decleration `public abstract object this[object value] { set; }`

This fails with a compilation error `The parameter name 'value' conflicts with an automatically-generated parameter name`, however the red squiggle for the error is in a confusing place (specifically under only the `this` in the Indexer declaration)

![indexersetvalueparamname](https://cloud.githubusercontent.com/assets/289860/12072269/579dcdea-b0ce-11e5-878d-be8d1e393183.png)

It would make more sense if the squiggle was shown under the `value` parameter name (see green line in screenshot above)

**Comment by leppie** [comment]
The same seems to happen with these:
```
class MyClass { } //defaults to internal accessibility

public class MyClass2
{
    public int this[MyClass myClass] => 0;  // CS0055
    public void Foo(MyClass myClass) { } // CS0051
}
```

**Comment by AlekseyTs** [comment]
@TyOverby Please verify.
