### ISSUE TITLE
Question: how to obtain full path from PEAssemblySymbol?

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn#7764]
The analyzer I'm working on should scan assembly references and check whether a specific file exists in the same folder as the assembly dll.

For that to work, I need some way to determine the assembly full path that the symbol originated from. I tried `symbol.ContainingAssembly.Identity`, which returns a value like:

```ExternallyAnnotatedClassLibrary, Version=1.2.3.4, Culture=neutral, PublicKeyToken=null```

So, without path information. Is there a way to find the full path? My scenario does not need to support GACed assemblies.

**Comment by tmat** [comment]
You can call Compilation.GetMetadataReference to get a MetadataReference from IAssemblySymbol

http://source.roslyn.io/#Microsoft.CodeAnalysis/Compilation/Compilation.cs,24b299a1bad60cc2

then you need to check what kind of reference it is. PortableExecutableReference might have path (not all do however).

**Comment by bkoelman** [comment]
That works great, thanks a lot!
