### ISSUE TITLE
Support "Make Async" on methods

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#7769]
It's always a huge bummer to convert a bunch of my methods to async. Right now, I have to manually add "async" to my signature, change my return type to Task, and await my method call, etc. etc.

I would love if I could just `Ctrl+.` on a method and click "Make Async" and it would do all these tedious changes for me for each method. It would also be cool if you could pipe async through all affected code...not sure how plausible that is though.

**Comment by kuhlenh** [comment]
FYI @CyrusNajmabadi, @dpoeschl

**Comment by MgSam** [comment]
Adding `async' and changing the return type to Task in a single step sounds like a useful feature.

> It would also be cool if you could pipe async through all affected code...not sure how plausible that is though.

This sounds really dangerous, being that properly using async requires propagating it up the call stack. It seems pretty likely a tool doing that recursively would have unintended side effects on the program execution.

**Comment by i3arnon** [comment]
However, without changing the methods all the way up the transformation may end up with non-compiling code.

Adding `await` to the method call will not compile in a non-`async` method and not adding an await may not compile if there's an assignment to something which is not a `Task`.

**Comment by daveaglick** [comment]
In addition to what @i3arnon said, if the originally synchronous method calls any async methods it's likely doing some combination of `.Result`, custom contexts, etc. Unwinding that automatically so that your newly-async method makes purley async calls to other async methods sounds very tricky (if it's even possible).

**Comment by MgSam** [comment]
> However, without changing the methods all the way up the transformation may end up with non-compiling code.

I think this is preferable. You want to force the user (via errors) to consider the implications of making each and every method async, not just do work that may compile but is likely to have runtime bugs.

**Comment by jmarolf** [comment]
Note that if you await a method that is not `async` we offer to convert the method for you (see [CSharpAddAsyncCodeFixProvider](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Features/CodeFixes/Async/CSharpAddAsyncCodeFixProvider.cs))

Few things we could do to improve:
1. We don't convert `void` to `Task`, we should probably have some heuristics to detect the few cases where `async void` is appropriate and in all others change the return type.
2. We don't check for entry points, we should have special logic if the async method is an entry point, possibly creating an encapsulating method that we call `GetAwaiter().GetResult()` on (unless we implement proposal https://github.com/dotnet/roslyn/issues/7476)
3. We don't change `MethodName` to `MethodNameAsync`
4. We should also offer this as a refactoring on any non-async method

**Comment by roji** [comment]
I wrote something that does almost exactly what this issue describes: http://github.com/roji/AsyncRewriter. It's used in Npgsql (the .NET driver for PostgreSQL) to selectively generated async methods from sync counterparts.

FWIW I really don't think this kind of thing belongs in the compiler.

**Comment by scottsauber** [comment]
+1 to this feature.  It's a minor annoyance that when you create a new Razor Page or Controller from the default scaffolder in VS and have to convert the methods to async.  Especially in Core where it's encouraged to async all the things.

I get I could just wait until I await the method, but my brain struggles not to fix something immediately when I see it's wrong.  :)

**Comment by CyrusNajmabadi** [comment]
> I think we could close this issue. 

Agreed.  I think a core case here has been addressed.  If there are more, we should call them out specifically with new issues that we can evaluate.
