### ISSUE TITLE
Add .NET 4.6 support to Mono toolsets

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#7770]
Our current Mono toolset on Linux + Mac currently doesn't have the targets or reference assemblies for .NET 4.6. We can fix this in two ways:
1. Simply copy the targets and references from Windows into the current drops and upload new packages.
2. Update to a newer Mono commit that theoretically has these targets + ref changes.

(1) is easier, but moves us farther from an upstream baseline. (2) is a pain because we usually build our own drop from source, which requires a Mac machine, which is difficult to come by, since most devs on the team don't have Macs.

Either way, we should try to support this.

**Comment by tmat** [comment]
FYI @jaredpar

**Comment by jaredpar** [comment]
Moved to 1.3 because I couldn't immediately see a need for this in update 2. Please let me know if i'm missing something.

**Comment by borgdylan** [comment]
The latest mono commits support compiling for .NET 4.6/4.6.1 and have separated the 4.6 assemblies form the strictly 4.5 reference assemblies.

**Comment by agocke** [comment]
Closing as obsolete -- our xplat solution doesn't build net46 projects anymore
