### ISSUE TITLE
In FixAllProvider.md the link to PublicSurfaceAreaFixAllProvider does work

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#7774]
http://source.roslyn.io/#q=PublicSurfaceAreaFixAllProvider returns no result found.

**Comment by jmarolf** [comment]
We should fix this up [PublicSurfaceAreaFixAllProvider](https://github.com/dotnet/roslyn-analyzers/blob/805488ca77226b7cbc360e7b5a8019635b332274/src/Unfactored/Roslyn/Core/ApiDesign/DeclarePublicAPIFix.cs#L209) was moved to https://github.com/dotnet/roslyn-analyzers
