### ISSUE TITLE
Signing change causes all VSI tests to fail.

### ISSUE THREAD

**Issue by brettfo** [dotnet/roslyn#7777]
Starting with [this build](http://dotnet-ci.cloudapp.net/job/roslyn-internal_master_win_vsi_p0/655/) the VSI tests have been failing with:

d:\j\workspace\roslyn-internal_master_win_vsi_p0\Open\build\Targets\VSL.Imports.targets(268,5): error MSB3073: The command ""C:\Program Files (x86)\Microsoft SDKs\Windows\v8.0A\bin\NETFX 4.0 Tools\sn.exe" -q -R "d:\j\workspace\roslyn-internal_master_win_vsi_p0\Open\Binaries\Obj\CodeAnalysis\Release\Microsoft.CodeAnalysis.dll" "d:\j\workspace\roslyn-internal_master_win_vsi_p0\Open\build\Strong Name Keys\35MSSharedLib1024.snk"" exited with code 1. [d:\j\workspace\roslyn-internal_master_win_vsi_p0\Open\src\Compilers\Core\Portable\CodeAnalysis.csproj]

This comes from internal commit 936a21116b6a38d2edbd0eb91cb12faa17eb17e3 which is based off of 4c109948b7bdedf49a8a1c980c6adec6663f9e0a (PR #7747).

**Comment by agocke** [comment]
Looking now.

**Comment by brettfo** [comment]
Fixed in #7780.
