### ISSUE TITLE
Put search term in the Find Results title bar

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#7778]
When I do "Find All References" or "Go To Implementation" (where there is more than one implementation), my search term is nowhere in sight. It would be super helpful to place the search term in the title bar of the Find Results window.

This is a pain when I'm navigating a code base that I am unfamiliar with and can't remember the name of the method I am finding the references for (note: this problem doesn't exist for "Go To Definition" where I have only one option).

**Comment by dpoeschl** [comment]
Now that Find Refs is hierarchical, the search term (declarations) are the top-level nodes, making it somewhat easier to find. 

@kuhlenh @Pilchie Can we just fold this into https://github.com/dotnet/roslyn/issues/903?

**Comment by dpoeschl** [comment]
Merging into #903
