### ISSUE TITLE
Make Formatter#GetFormattedTextChanges public

### ISSUE THREAD

**Issue by jrieken** [dotnet/roslyn#778]
For OmniSharp we want to use Formatter#GetFormattedTextChanges since that returns a list of text changes which is more useful than a (formatted) syntax node. Therefore, the wish to make it publicly available to others: https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/Formatting/Formatter.cs#L314

**Comment by Pilchie** [comment]
@mattwar - what do you think?

**Comment by mattwar** [comment]
Yes we should do this.

**Comment by Pilchie** [comment]
I'm taking a look at this.

**Comment by Pilchie** [comment]
Can you verify for me?
