### ISSUE TITLE
[Test Failure] GitHub Timeout in prtest/mac/dbg/unit32 on PR #7784

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#7786]
this is second time Mac failed to clone repo.

...

PR: [#7784](https://github.com/dotnet/roslyn/pull/7784) ** by @
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_mac_dbg_unit32/2416/

**Issue 1: GitHub Timeout**
Timeout cloning repo from GitHub. Retry the job.

**Comment by heejaechang** [comment]
@dotnet/roslyn-infrastructure is this known issue?

**Comment by amcasey** [comment]
@heejaechang Usually that indicates a networking issue (azure or GitHub).  I think you just have to retry.

**Comment by amcasey** [comment]
@tannergooding @brettfo @davkean It looks like we're fetching *every* PR.  Is that expected?
```
Command "git -c core.askpass=true fetch --tags --progress https://github.com/dotnet/roslyn.git +refs/pull/*:refs/remotes/origin/pr/*" returned status code 143
```

**Comment by amcasey** [comment]
Regardless of whether or not the current behavior is expected, it looks like it is generally fast enough so I'm guessing this was just a transient network issue.

**Comment by amcasey** [comment]
In particular, I think @brettfo mentioned that Mac machines had to be rebooted yesterday to clear up some perf issues,

**Comment by davkean** [comment]
We've been having lots of issues with the Mac machines, we don't know whether it's network/hardware related. This is the first time I've seen this timeout though.

**Comment by davkean** [comment]
I'm going to close this - Mac has been stable past week, we've not hit this issue again - looks like something transient with the boxes.
