### ISSUE TITLE
BasicErrorList is flaky

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#7787]
http://dotnet-ci.cloudapp.net/view/roslyn-internal/job/roslyn-internal_prtest_win_vsi_p0/116/artifact/Open/Binaries/Release/VSIntegrationTestLogs/BasicErrorList.html

```
 Scenario: Error List
    Executing action [1/5/2016 7:21:51 PM] AddProject
    Executing action [1/5/2016 7:22:01 PM] AddItem
    Executing action [1/5/2016 7:22:01 PM] OpenFile
    Executing action [1/5/2016 7:22:01 PM] SetEditorText
    Executing action [1/5/2016 7:22:02 PM] ExecuteCommand
    Executing action [1/5/2016 7:22:02 PM] VerifyErrorList
    Executing action [1/5/2016 7:22:15 PM] VerifyCaretPosition
    Executing action [1/5/2016 7:22:15 PM] Build
Waiting for Roslyn features SolutionCrawler: 1/5/2016 7:22:18 PM
Waiting for Roslyn features ErrorList: 1/5/2016 7:22:18 PM
Finished waiting for Roslyn features SolutionCrawler and ErrorList: 1/5/2016 7:22:18 PM
Waiting for error list: 1/5/2016 7:22:20 PM
Finished waiting for error list: 1/5/2016 7:22:22 PM
    Executing action [1/5/2016 7:22:24 PM] VerifyErrorList
--------------------------------
System.Exception: Wrong number of errors in error list. Expected '2', found '3'.

Actual errors:
Type 'P' is not defined.
'Foo' is not declared. It may be inaccessible due to its protection level.
file 'C:\Users\dotnet-bot\AppData\Local\Temp\hfv2pqv4.p3z\TestProj\Class1.vb' could not be found
```

**Comment by amcasey** [comment]
@brettfo conjectures that the unexpected error is stale and was a result of "Class1.vb" temporarily existing during project creation.

**Comment by heejaechang** [comment]
I dont believe this error is from us
"file 'C:\Users\dotnet-bot\AppData\Local\Temp\hfv2pqv4.p3z\TestProj\Class1.vb' could not be found"

rather probably from project system.

I think this has hit a race where we add base template project and remove default item from it

**Comment by heejaechang** [comment]
pushed wrong button, reopened the issue. anyway, I changed basicerrorlist.xml to check there is no error at the beginning of the test to make sure test starts from valid context.

**Comment by heejaechang** [comment]
the PR will not fix the race but will fail the test even before running test to figure out why the race happens.
