### ISSUE TITLE
Gap in Getting Started

### ISSUE THREAD

**Issue by Gentlehag** [dotnet/roslyn#7789]
I want to test roslyn for a small script engine. So I tried to get started with a simple evaluation like described in the aritkels.

The Code I want to run is this

object result = await CSharpScript.EvaluateAsync("1 + 2");

For this I added the 2 nuget packages mentioned on the start page:

Microsoft.Net.Compilers   
Microsoft.CodeAnalysis 

But still the CSharpScript type is unknonw

what am I missin ?

**Comment by davkean** [comment]
Which article or page are you referring to exactly? For scripting, you also need to install the scripting package, here: https://www.nuget.org/packages/Microsoft.CodeAnalysis.Scripting/

**Comment by Gentlehag** [comment]
thx that solved it

**Comment by davkean** [comment]
@Gentlehag Can you point out the page you read this so that we can update it to include this information?
