### ISSUE TITLE
After successful build, errors start appearing in the error list

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#7790]
I built Roslyn and it succeeded with no errors. However, after a few minutes (of not doing anything) I had 167 errors in the error list. Log at \\mlangfs1\public\rchande\workspace\RoslynWorkspaceInfo.xml

**Comment by davkean** [comment]
Can you figure out root cause to see if we're going to do anything for 1.2?

**Comment by KevinH-MS** [comment]
I wonder if this might be similar (or the same as) #6809.

**Comment by jasonmalinowski** [comment]
Only looking at Ravi's logs will tell. @drognanar also has another issue right now which could be related; just trying to knock off a few higher priority things and then will be taking a look.

**Comment by rchande** [comment]
I have this error in the CodeAnalysis project:
<diagnostic severity="Error">Key file 'C:\roslyn-internal\Open\build\Strong Name Keys\35MSSharedLib1024.snk' is missing the private key needed for signing</diagnostic>

Same as what we discussed at lunch @amcasey @jasonmalinowski ?

**Comment by jasonmalinowski** [comment]
Yes, that's the same issue.

**Comment by jasonmalinowski** [comment]
Yes, your issue is the same as @drognanar, but that's not #6809. Right now this it the active tracking bug.

**Comment by jasonmalinowski** [comment]
This was fixed last week.
