### ISSUE TITLE
[Test Failure] test output directory can't be deleted because it is locked

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#7796]
http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_dbg_unit64/493/

here is copy of output

The test runner has encountered a non-test-related exception.
00:26:41 To be clear, this is a problem with the test runner, not a test.
00:26:41 0a7ba10e-c611-4fb0-aefe-0c2efd6fe413
00:26:41 System.IO.IOException: The process cannot access the file 'd:\j\workspace\roslyn-internal_prtest_win_dbg_unit64\Open\Binaries\Debug\TestResults\xxx2016-01-06 08_10_50\Out' because it is being used by another process.
00:26:41    at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
00:26:41    at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
00:26:41    at RoslynBuildAndTest.TestRunner.DeleteTestResultsFile(String resultsFile)

**Comment by davkean** [comment]
Is this a dup of https://github.com/dotnet/roslyn/issues/7838?

**Comment by Pilchie** [comment]
@davkean says it was a dupe.
