### ISSUE TITLE
WorkspaceChanged event for external changes (VS 2013)

### ISSUE THREAD

**Issue by Inspyro** [dotnet/roslyn#78]
In relation to this [stackoverflow post] (http://stackoverflow.com/questions/11732067/detect-iworkspace-changes-by-vs-from-outside-vs-host-environment), I would like to ask if it's still possible to update a workspace whenever a file gets changed (externally). 

Background to my question is, whether it is possible to make a Visual Studio extension that provides the most current version of the *Roslyn* solution model like it is already possible in *Visual Studio 2015* (AFAIK). I guess this could be easily supported for *VS2013* by implementing such an extension. Otherwise, when using the MSBuildWorkspace, loading large solutions for every update can take quite some time, which we want to avoid by using a continously updated model. 

Maybe this is possible by using a *FileSystemWatcher* and calling some API function that checks the solution for changes?

**Comment by JoshVarty** [comment]
Have you considered using the VisualStudioWorkspace? I believe it lives in Microsoft.VisualStudio.LanguageServices.dll. In your extension you can use MEF to import it: 

```CSharp
[Import(typeof(Microsoft.VisualStudio.LanguageServices.VisualStudioWorkspace))]
public VisualStudioWorkspace myWorkspace { get; set; }
```

You'll be notified of any changes made to the workspace made by the user.

**Comment by Inspyro** [comment]
Does this work for **Visual Studio 2013** with the current Roslyn Version *1.0.0 beta 2*
Or is this only possible with the April CTP?

**Comment by JoshVarty** [comment]
For VS 2013, it only works with the April CTP.

**Comment by mattwar** [comment]
The Visual Studio workspace already tracks changes to documents on disk and will send workspace changed events corresponding to the changes.

**Comment by Inspyro** [comment]
Ok thanks.
