### ISSUE TITLE
Change default pre-selection in Results window

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#7802]
When I do Find All References on a method, the pre-selected element in the Results window does not match the instance of the method I have selected in my editor. Instead, it has the root of the result hierarchy pre-selected (see image). This is confusing, because any other time the blue highlight is over a search term I am navigated to that instance in the editor.

![image](https://cloud.githubusercontent.com/assets/1402694/12149271/b8de5bc4-b457-11e5-94d7-5fa47497c13f.png)

It would make more sense to me if the pre-selection was on the instance of the method I selected and clicked FAR for in the editor. For example, the blue highlight in the above image would be over the second element in the hierarchy because that is what is currently highlighted in my editor.

**Comment by kuhlenh** [comment]
@CyrusNajmabadi said it better than I: "it's inconsistent that the root is selected, but in the editor i'm not on that item"

**Comment by dpoeschl** [comment]
@kuhlenh @Pilchie Can we roll this into https://github.com/dotnet/roslyn/issues/903?

**Comment by dpoeschl** [comment]
Rolling into #903.
