### ISSUE TITLE
Expand new() generic constraint to support constructor parameters

### ISSUE THREAD

**Issue by mteper** [dotnet/roslyn#7808]
Today, the only way to create an instance of the generic type in a generic class is to constrain the class with a `new()` constraint, which limits us to parameterless constructors only. It would be very useful to extend this to constructors with specific typed parameters.

Here's a contrived example,
```cs
public class Foo<T> where T : FooBase, new(JObject)
{
  public T FromJson(JObject data)
  {
    return new T(data);
  }
}
```

In this case, as long as T has a constructor that accepts a `JObject` type parameter, code will compile.

**Comment by HaloFour** [comment]
This would be great but currently the CLR does not support this form of constraint.

**Comment by mteper** [comment]
Is there a more appropriate place to make suggestions that need CLR work?

**Comment by HaloFour** [comment]
Check out #2136, under "Interesting but require CLR support" is a series of enhancements around generic constraints.  Could post to [CoreCLR](https://github.com/dotnet/coreclr) as well.  I don't know how the teams are coordinating those kinds of requests, assuming that they are.

**Comment by gafter** [comment]
Dup of #2206.
