### ISSUE TITLE
Incomplete check for an ability to emit attribute in CSharpCompilation.TrySynthesizeAttribute.

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#7809]
```
            var ctorSymbol = (MethodSymbol)GetWellKnownTypeMember(constructor);
            if ((object)ctorSymbol == null)
            {
                // if this assert fails, UseSiteErrors for "member" have not been checked before emitting ...
                Debug.Assert(WellKnownMembers.IsSynthesizedAttributeOptional(constructor));
                return null;
            }
```

This code checks for presence of the constructor, but doesn't verify if the constructor is good, i.e. doesn't have use-site errors associated with it. Similar helper in VB checks for errors:
```
            Dim constructorSymbol = TryCast(GetWellKnownTypeMember(constructor), MethodSymbol)
            If constructorSymbol Is Nothing OrElse
               Binder.GetUseSiteErrorForWellKnownTypeMember(constructorSymbol, constructor, False) IsNot Nothing Then
                Return ReturnNothingOrThrowIfAttributeNonOptional(constructor)
            End If
```

Proposed fix:
Rather than calling ```CSharpCompilation.GetWellKnownTypeMember``` method we should call 
```Binder.GetWellKnownTypeMember(CSharpCompilation compilation, WellKnownMember member, out DiagnosticInfo diagnosticInfo, bool isOptional = false)```, passing true for the ```isOptional``` parameter. It looks like this will ensure that non-null value is returned only when member is present and good.

**Comment by jcouv** [comment]
Just to confirm, below is the change. Next, I'm trying to come up with a test that triggers use-site diagnostics with severity=Error. 
Let me know if you have a suggestion.

```C#
            DiagnosticInfo useSiteDiagnostics = null;
            var ctorSymbol = (MethodSymbol)Binder.GetWellKnownTypeMember(this, constructor, out useSiteDiagnostics, true);
            
            if ((object)ctorSymbol == null)
            {
                // if this assert fails, UseSiteErrors for "member" have not been checked before emitting ...
                Debug.Assert(WellKnownMembers.IsSynthesizedAttributeOptional(constructor));
                return null;
            }
```

**Comment by AlekseyTs** [comment]
Look through the set of optional attributes synthesized with this helper, pick one that has constructor parameters and try to create a compilation in such a way that one of the parameter types is missing, but everything else in the compilation is good.

**Comment by jcouv** [comment]
Modified code per recommendation and verified.
