### ISSUE TITLE
New compiler switches need to be threaded through the project system for intellisense builds

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#7812]
Right now these flags are not being passed through to the IDE design time builds:

- /features
- /deterministic
- /pathmap
- /publicsign
- /pdb:portable

Issue #6945 is tracking the feature request of adding UI, but even if we do not do that, we must pass these flags through design time builds or all sorts of things don't work. Notably, lack of /publicsign breaks semantics like crazy, since it assumes the .snk has private keys. Lack of /pathmap would be observable if an ENC edit did something around CallerInfo. /feature is a blocker for anybody trying to build new features.

**Comment by jasonmalinowski** [comment]
@jaredpar Can you confirm the list of flags I gave above is the full list that was added since 1.0? (note: since 1.0, not 1.1, since we missed some in 1.1 too)

**Comment by edbenson** [comment]
Your list has /feature. The error message I'm getting suggests it should be /features. 

Error CS8058 Feature 'pattern matching' is experimental and unsupported; use '/features:patterns' to enable.

**Comment by jaredpar** [comment]
@jasonmalinowski that list looks correct to me.

CC @TyOverby and @agocke in case I missed anything.

**Comment by jasonmalinowski** [comment]
Are pathmap and pdb:portable emit-only settings?

**Comment by jaredpar** [comment]
Yes.

**Comment by jasonmalinowski** [comment]
The internal parts are also checked in too.
