### ISSUE TITLE
Error adding file to shared project

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#7813]
Repro steps:
1. Open Compilers.sln (in Roslyn repo) 
2. Right click on ServerShared project choose Add -> New Item
3. Choose a class file and hit Add

At this point a dialog pops up with the text

> The reference "System" could not be added to the project ... 

The file then successfully adds and is usable.  So it's not blocking, just a tad frustrating to dismiss the dialog every time.  

Note: I chose ServerShared because it's a specific project I've been working with but it should repro just fine with any shared project in the solution.

**Comment by Pilchie** [comment]
I suspect this is because the template says to add System, and that conflicts with something about the project itself?

**Comment by jasonmalinowski** [comment]
Doesn't seem to repro anymore.
