### ISSUE TITLE
[Proposal] Improved event declaration syntax

### ISSUE THREAD

**Issue by TKharaishvili** [dotnet/roslyn#7814]
Let us review the following:
```C# 
event Action<object, EventArgs> OnApproved; 
```
Now, that implies an awful lot of things for a one-liner. It generates a backing field, creates `add/remove` accessors for the event and synchronizes them by locking on, you guessed it, `this`, [which is not recommended.](http://stackoverflow.com/questions/251391/why-is-lockthis-bad) 
It is also fairly confusing to understand on the first try and the number of stackoverflow questions and blog posts on the web dedicated to explaining it, speaks for itself.

I suggest to add an alternate, more explicit syntax for declaring events, that looks something like this:
```C# 
Action<object, EventArgs> OnApproved{ add; remove; }
```
The pros of this syntax are:

* It is more explicit, without being too verbose and therefore it's less confusing
* Stylistically aligned with the property syntax
* Ideally it would require one less keyword in the language. (`event`)

But there's still a question regarding thread safety, should it still imply locking on `this`? In my opinion an answer to that is - **No**, but using the full syntax every time you need synchronization(which is every time) is too much of a drag.
So how do we minimize the syntax and stay explicit?

My suggestion is something similar to [MethodImplOptions.Synchronized](https://msdn.microsoft.com/en-us/library/system.runtime.compilerservices.methodimploptions(v=vs.110).aspx), which in our case would look something like:

```C# 
[EventImpl(EventImplOptions.Synchronized)]
Action<object, EventArgs> OnApproved{ add; remove; }
```
Now the above syntax still locks on `this` but at least the intent is stated by the developer him/herself. Additionally this matches some potential ideas in the community about removing property implementation boilerplate through attribute metaprogramming.

**Up a notch:**

Ideally you wouldn't have two ways of doing the same thing in the language so how about, replacing the old syntax instead of just adding a new one? 

I know that the C# design team has a rule: Whatever can be compiled by C# n must also be compilable by C# n++ and this is a great approach meant for avoiding breaking changes, but one has to wonder when the downsides of backwards compat start outweighing it's very own benefits? Also enforcing the new syntax doesn't have to be radical, implemented on the compiler level, it can instead be an opt in thing, realized through Analyzers which would not only enforce, but help update the codebase to a new approach.

**P.S.** I understand that event declaration is one of the less frequently used language features and the compiler team has more important issues to dedicate their time to, but that doesn't rule out someone in the community deciding to tackle this feature. If, of course, this proposal gets a green light from the powers that be(the C# design team).

**Comment by svick** [comment]
> synchronizes them by locking on, you guessed it, `this`

That hasn't been true [since C# 4](http://blogs.msdn.com/b/cburrows/archive/2010/03/05/events-get-a-little-overhaul-in-c-4-part-i-locks.aspx).

> one has to wonder when the downsides of backwards compat start outweighing it's very own benefits?

Indeed, but I'm pretty sure making the language more consistent by a tiny bit does not come anywhere close to that.

**Comment by HaloFour** [comment]
I'd say that to most developers this syntax would be more confusing because it is quite rare to manually write event accessors so even being aware of `add` and `remove` is likely not that pervasive.  The old syntax would have to remain supported into perpetuity given existing codebases so `event` would permanently remain a keyword.  And, as @svick mentioned, that locking behavior has already been fixed using the existing syntax.

**Comment by TKharaishvili** [comment]
@svick 

> That hasn't been true since C# 4.

My bad, didn't know about that. Thanks for pointing it out. Other than that, what do you think of the proposed syntax itself?

> tiny bit does not come anywhere close to that.

Well, my thought process was, if the suggestion gets accepted it would be better to replace the old approach instead of just adding a new one, because having two ways of doing the exact same thing, kind of, is big enough a deal. Plus the improvement may be tiny, but it's the little unpolished things that add up over time and make the language look old...


@HaloFour 
> being aware of add and remove is likely not that pervasive

* Except every time anyone asks: "Why do I need an the `event` keyword at all, why don't I just use the delegate without it? " you will have to explain that, there's really a property-like thing going on in there and that the `add/remove` accessors are being added and that it's the encapsulation thing and this and that. So I figured why wouldn't one just put it in the syntax instead of explaining it every time a new kid arrives around the block?

* Which one do you think is more natural a progression?
From
```C# 
event Action<object, EventArgs> OnApproved; 
```
To
```C# 
Action<object, EventArgs> _onApproved;
event Action<object, EventArgs> OnApproved { add { /* custom stuff */ } remove { /* custom stuff */ } }
```
Or from
```C# 
Action<object, EventArgs> OnApproved{ add; remove; }
```
To
```C# 
Action<object, EventArgs> _onApproved;
Action<object, EventArgs> OnApproved { add { /* custom stuff */ } remove { /* custom stuff */ } }
```
* And do you seriously think that the full awareness of the language you use is bad?

**Comment by HaloFour** [comment]
@TKharaishvili

I think that it might have been a good argument 15 years ago, but the existing event syntax exists and will not go away and there is little reason to have two separate syntaxes.

Knowing the language that you use is a good thing, knowing the trivial details that you're very unlikely to use is just a waste of brain-space.  The vast majority of developers will never have a reason to write custom event accessors and will never see those keywords used, which is probably a good thing because the Correct Way™ way to update the delegate field is far from simple for most developers.  Given such there is little reason to have a progression at all.

**Comment by paulomorgado** [comment]
@TKharaishvili, I'll second @HaloFour on this.

I could arguable be better, but that's the way it was born.

You could also argue (on the opposite direction) that a read-only property might be defined as:

   property int X = 0

But that's not how it was born.

Besides knowing the syntax, developers must also know the culture. For example, one never calls an event `OnSomethingHappened`. `OnSomethingHappened` is the `protected virtual` method that fires the `SomethingHappened` event.

I do agree that, in the long run, this wouldn't harm and would, most likely, be the de facto of writing event handlers as it is for properties, but I don't think it's worth the work and confusion.

**Comment by TKharaishvili** [comment]
@paulomorgado 

> one never calls an event OnSomethingHappened

Correct, but naming is beyond the focus of this conversation.

@paulomorgado @svick @HaloFour thank you all for voicing your opinions.

I'll close the issue, since there has been no more activity or supportive feedback whatsoever.
