### ISSUE TITLE
CsiTests.CurrentWorkingDirectory_Change is flaky

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#7826]
```
    Microsoft.CodeAnalysis.CSharp.Scripting.Hosting.UnitTests.CsiTests.CurrentWorkingDirectory_Change
      
      Actual:
      Microsoft (R) Visual C# Interactive Compiler version 42.42.42.42
      Copyright (C) Microsoft Corporation. All rights reserved.
      Type ""#help"" for more information.
      > (1,1): error CS1056: Unexpected character 'ï¿½'
      (1,2): error CS1056: Unexpected character 'ï¿½'
      (1,3): error CS1056: Unexpected character 'ï¿½'
      (1,4): error CS1040: Preprocessor directives must appear as the first non-whitespace character on a line
      (1,10): error CS1504: Source file 'a.csx' could not be opened -- Could not find file.
      > (1,1): error CS0006: Metadata file 'C.dll' could not be found
      > > > > 1
      > C { }
      > 
      Differences:
          Microsoft (R) Visual C# Interactive Compiler version 42.42.42.42
          Copyright (C) Microsoft Corporation. All rights reserved.
          Type ""#help"" for more information.
      ++> > (1,1): error CS1056: Unexpected character 'ï¿½'
      ++> (1,2): error CS1056: Unexpected character 'ï¿½'
      ++> (1,3): error CS1056: Unexpected character 'ï¿½'
      ++> (1,4): error CS1040: Preprocessor directives must appear as the first non-whitespace character on a line
      ++> (1,10): error CS1504: Source file 'a.csx' could not be opened -- Could not find file.
      --> > (1,7): error CS1504: Source file 'a.csx' could not be opened -- Could not find file.
          > (1,1): error CS0006: Metadata file 'C.dll' could not be found
          > > > > 1
          > C { }
          > 
```

**Comment by amcasey** [comment]
http://dotnet-ci.cloudapp.net/view/roslyn/job/roslyn_prtest_win_dbg_unit32/2580/
http://dotnet-ci.cloudapp.net/view/roslyn/job/roslyn_prtest_win_dbg_unit64/2553/

**Comment by amcasey** [comment]
@drognanar, do you have a few minutes to look at this one?

**Comment by tmat** [comment]
This is very odd. It seems like there might be a BOM issue. But no idea why would it fail only sometimes.

**Comment by tmat** [comment]
Also, why do we print ```> > > > 1```? The prompts should always be on the start of the line.

**Comment by amcasey** [comment]
@drognanar, can you please skip the test while you're investigating?

**Comment by amcasey** [comment]
http://dotnet-ci.cloudapp.net/view/roslyn/job/roslyn_prtest_win_dbg_unit64/2565/

**Comment by diryboy** [comment]
Also hit this in my local box, the unexpected char looks different though
```
      Actual:
      Microsoft (R) Visual C# Interactive Compiler version 42.42.42.42
      Copyright (C) Microsoft Corporation. All rights reserved.
      Type ""#help"" for more information.
      > (1,1): error CS1056: Unexpected character '�'
      (1,2): error CS1056: Unexpected character '�'
      (1,3): error CS1056: Unexpected character '�'
      (1,4): error CS1040: Preprocessor directives must appear as the first non-whitespace character on a line
      (1,10): error CS1504: Source file 'a.csx' could not be opened -- Could not find file.
      > (1,1): error CS0006: Metadata file 'C.dll' could not be found
      > > > > 1
      > C { }
      > 
      Differences:
          Microsoft (R) Visual C# Interactive Compiler version 42.42.42.42
          Copyright (C) Microsoft Corporation. All rights reserved.
          Type ""#help"" for more information.
      ++> > (1,1): error CS1056: Unexpected character '�'
      ++> (1,2): error CS1056: Unexpected character '�'
      ++> (1,3): error CS1056: Unexpected character '�'
      ++> (1,4): error CS1040: Preprocessor directives must appear as the first non-whitespace character on a line
      ++> (1,10): error CS1504: Source file 'a.csx' could not be opened -- Could not find file.
      --> > (1,7): error CS1504: Source file 'a.csx' could not be opened -- Could not find file.
          > (1,1): error CS0006: Metadata file 'C.dll' could not be found
          > > > > 1
          > C { }
          > 
```

**Comment by amcasey** [comment]
@diryboy Are you hitting it consistently?  We're having trouble getting a repro.  It would be very useful to know the raw bytes that the lexer is receiving.

**Comment by diryboy** [comment]
Not sure, I only ran full tests once, hit this issue and saw this item has several dumps, so I ignored and moved on. Anything I need to keep an eye on, if I ran into this again?

Sorry I did not read the test code, I'll read it tomorrow.

**Comment by diryboy** [comment]
I switched to another machine and hit this again. But the error message and looks different. Maybe because the codepage is 936 this time?

      Actual:
      Microsoft (R) Visual C# Interactive Compiler version 42.42.42.42
      Copyright (C) Microsoft Corporation. All rights reserved.
      Type ""#help"" for more information.
      > (1,8): error CS1003: Syntax error, ':' expected
      > (1,1): error CS0006: Metadata file 'C.dll' could not be found
      > > > > 1
      > C { }
      > 
      Differences:
          Microsoft (R) Visual C# Interactive Compiler version 42.42.42.42
          Copyright (C) Microsoft Corporation. All rights reserved.
          Type ""#help"" for more information.
      ++> > (1,8): error CS1003: Syntax error, ':' expected
      --> > (1,7): error CS1504: Source file 'a.csx' could not be opened -- Could not find file.
          > (1,1): error CS0006: Metadata file 'C.dll' could not be found
          > > > > 1
          > C { }
          >

**Comment by davkean** [comment]
@drognanar What's the progress on this? This falls under the 48 flaky test rule.

**Comment by amcasey** [comment]
@davkean We think there's some sort of race in setting the encoding on the pipe.  We can work around the issue by setting it manually, but @drognanar is doing local experiments to try to determine the root cause.  If getting the test unskipped is a priority, let's just explicitly set the encoding and file a new bug to figure out why that's necessary.

**Comment by ManishJayaswal** [comment]
@drognanar did you ever get a change to pursue this investigation further. Looks like it is only happening in test run and it does not repro manually hence I am removing the flaky label. The test is still disabled so we should investigate this soon hence leaving it in 1.2 milestone.
