### ISSUE TITLE
ISymbol.GetDocumentationCommentId() sometimes returns unqualified names

### ISSUE THREAD

**Issue by mairaw** [dotnet/roslyn#7829]
I’m working on a solution that reads our existing IntelliSense files and parses the source code so we can add the content in the form of /// comments back in the source code using Roslyn.
When I call the ISymbol.GetDocumentationCommentId() method, the CommentID is not *always* matching what we have in the IntelliSense file.
For example, for System.String class, instead of M:System.String.Join\`\`1(System.String,System.Collections.Generic.IEnumerable{\`\`0}), I’m getting M:System.String.Join\`\`1(System.String,IEnumerable{\`\`0}) as the CommentID for one of the String.Join methods.
Or instead of M:System.String.Concat(System.Object,System.Object), I'm getting M:System.String.Concat(Object,Object).

Can you please check?

Thanks!

**Comment by amcasey** [comment]
Thanks for the report!  If it turns out that this is by design, we'll post and explanation, but I'm pretty sure it's just a bug.

**Comment by amcasey** [comment]
FYI @dotnet/roslyn-compiler

**Comment by mairaw** [comment]
It seems like it since it doesn't match the signature from the API catalog too. Thanks for investigating it!

**Comment by amcasey** [comment]
This code behaves as expected on my box (with Microsoft.CodeAnalysis 1.1.1):

```C#
            var mscorlibRef = MetadataReference.CreateFromFile(typeof(object).Assembly.Location);
            var comp = CSharpCompilation.Create("dummy.dll", references: new[] { mscorlibRef });
            var join1 = comp.GetSpecialType(SpecialType.System_String).GetMembers("Join").OfType<IMethodSymbol>().Single(m => m.Arity == 1);
            Console.WriteLine(join1.GetDocumentationCommentId());
```

It prints `M:System.String.Join``1(System.String,System.Collections.Generic.IEnumerable{``0})`.

**Comment by mairaw** [comment]
Thanks @amcasey. As we discussed, the issue was that I was creating the compilation without adding the references. So changing my code to something like this did the trick and GetDocumentationCommentId started working:

```c#
var metadataReferences = new MetadataReference[] { MetadataReference.CreateFromFile(typeof(object).Assembly.Location) };
SyntaxTree tree = (SyntaxTree)CSharpSyntaxTree.ParseText(File.ReadAllText(file));
var compilation = CSharpCompilation.Create("test", syntaxTrees: new[] { tree }, references: metadataReferences);
