### ISSUE TITLE
Rip out support for inferred return type in local functions

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#7832]
The prototype for local functions (in the future branch) currently includes some support for inferring the return type. The LDM decided that we don't want that. Of course it would be possible to relax this in the future, but for the first iteration this is what we want.

Please remove the code and only support explicitly declared return types.

**Comment by AdamSpeight2008** [comment]
What was the reason for this decision?

**Comment by gafter** [comment]
It isn't well-specified, it is a mess to implement, and it conflicts with the possibility of extending local functions to support forward reference (to local functions) in the future.
