### ISSUE TITLE
VSI tests BasicWPF and CSharpWPF are failing consistently

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#7838]
```
 Scenario: Rename from code behind file and Undo after build
	Executing action [1/5/2016 11:01:35 PM] CloseFile
	Executing action [1/5/2016 11:01:35 PM] CloseFile
	Executing action [1/5/2016 11:01:35 PM] OpenFile
	Executing action [1/5/2016 11:01:35 PM] PlaceCursor
	Executing action [1/5/2016 11:01:35 PM] Rename
	Executing action [1/5/2016 11:01:36 PM] SendKeys
	Executing action [1/5/2016 11:01:38 PM] WaitForRenameCompletion
	Executing action [1/5/2016 11:01:38 PM] OpenFile
	Executing action [1/5/2016 11:01:38 PM] WaitForRenameCompletion
	Executing action [1/5/2016 11:01:38 PM] OpenFile
	Executing action [1/5/2016 11:01:39 PM] CodeMarkersWait
	Executing action [1/5/2016 11:01:41 PM] VerifyEditorContainsText
	Executing action [1/5/2016 11:01:41 PM] Build
Waiting for Roslyn features SolutionCrawler: 1/5/2016 11:01:42 PM
Waiting for Roslyn features ErrorList: 1/5/2016 11:01:48 PM
Finished waiting for Roslyn features SolutionCrawler and ErrorList: 1/5/2016 11:01:48 PM
Waiting for error list: 1/5/2016 11:01:50 PM
Finished waiting for error list: 1/5/2016 11:02:22 PM
2 projects failed build. Build output:
1>------ Build started: Project: WpfControlLibrary1, Configuration: Debug Any CPU ------
1>CSC : error CS2012: Cannot open 'C:\Users\dotnet-bot\AppData\Local\Temp\Closed\Test\Files\CSharpWPFtest\WpfControlLibrary1\obj\Debug\WpfControlLibrary1.dll' for writing -- 'The process cannot access the file 'C:\Users\dotnet-bot\AppData\Local\Temp\Closed\Test\Files\CSharpWPFtest\WpfControlLibrary1\obj\Debug\WpfControlLibrary1.dll' because it is being used by another process.'
2>------ Build started: Project: CSharpWPFtest, Configuration: Debug Any CPU ------
2>C:\Users\dotnet-bot\AppData\Local\Temp\Closed\Test\Files\CSharpWPFtest\CSharpWPFtest\MainWindow.xaml(7,10): error MC3074: The tag 'myControl' does not exist in XML namespace 'clr-namespace:WpfControlLibrary1;assembly=WpfControlLibrary1'. Line 7 Position 10.
========== Build: 0 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by amcasey** [comment]
I'm going to try for a local repro.  If that doesn't work, I'll start cataloging the lab failures.

**Comment by amcasey** [comment]
I understand @CyrusNajmabadi may have run into this as well.

**Comment by amcasey** [comment]
Passed the first run on my box.  Retrying.

**Comment by amcasey** [comment]
Failures are occurring across different Jenkins machines, so it's likely not a machine state issue.

**Comment by amcasey** [comment]
Looks like this started with 81502c886c576872330953bc60baac041e46658d

FYI @heejaechang

**Comment by heejaechang** [comment]
let me take a look.

**Comment by heejaechang** [comment]
I can't find 81502c886c576872330953bc60baac041e46658d

**Comment by heejaechang** [comment]
found the commit. but the commit shouldn't have anything to do with the logged issue I believe. anyway, looking.

**Comment by CyrusNajmabadi** [comment]
Can you point to the commit?  I can't find it either.

**Comment by amcasey** [comment]
It's internal.

**Comment by CyrusNajmabadi** [comment]
ah thanks.

**Comment by CyrusNajmabadi** [comment]
I've disabled the tests: 
https://github.com/dotnet/roslyn-internal/commit/a99160f586edfbc30d95c801c2cdb17e4737c1c3

**Comment by amcasey** [comment]
Thanks!  Do you mind if I dup your bugs against this one?

**Comment by heejaechang** [comment]
@amcasey @CyrusNajmabadi I sent out PR. turns out the issue is indeed due to my change. basically, procdump will lock on any dlls target process loaded to itself. but even if target process let the dlls go, procdump won't until target process terminates.

it looks like xaml designer loads those dlls to vs process and let them go at some point. my fix is basically for those 2 tests, always use new VS instance.

...

I thought about creating new procdump for each tests, but unfortunately, it looks like there is no way to gracefully terminate procdump that is monitoring a process except terminating the target process itself.

**Comment by davkean** [comment]
@heejaechang Do you have a fix? If so, can you point to it?

**Comment by davkean** [comment]
Please reenable the tests at the same time.

**Comment by amcasey** [comment]
@davkean the PR was https://github.com/dotnet/roslyn-internal/pull/504
