### ISSUE TITLE
Change Signature Removes wrong argument at Callsite

### ISSUE THREAD

**Issue by basoundr** [dotnet/roslyn#784]
In [CSharpSyntaxContext](http://index/#Microsoft.CodeAnalysis.CSharp.Workspaces/Extensions/ContextQuery/CSharpSyntaxContext.cs, 12) of Roslyn Solution, try removing the argument `position` in any of the syntaxTree extension method call inside the `CsharpSyntaxContext` instantiation using ChangeSig(Invoked through Ctrl+.)

The call site removes `cancellationToken`, which is the second argument, instead of the `position` argument

--------

Couldn't get a simpler repo

**Comment by dpoeschl** [comment]
@brettfo Can you verify in @basoundr's absence? Thanks!
