### ISSUE TITLE
DynamicAttribute is not emitted for types of events.

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#7845]
```
    class Program
    {
        event Action<dynamic> E1;
        Action<dynamic> P1 { get; set; }
    }
```

```
.event class [mscorlib]System.Action`1<object> E1
{
  .addon instance void ConsoleApplication7.Program::add_E1(class [mscorlib]System.Action`1<object>)
  .removeon instance void ConsoleApplication7.Program::remove_E1(class [mscorlib]System.Action`1<object>)
} // end of event Program::E1

.property instance class [mscorlib]System.Action`1<object>
        P1()
{
  .custom instance void [System.Core]System.Runtime.CompilerServices.DynamicAttribute::.ctor(bool[]) = ( 01 00 02 00 00 00 00 01 00 00 ) 
  .get instance class [mscorlib]System.Action`1<object> ConsoleApplication7.Program::get_P1()
  .set instance void ConsoleApplication7.Program::set_P1(class [mscorlib]System.Action`1<object>)
} // end of property Program::P1
```

It doesn't look like there is a difference by comparison to behavior of the native compiler.

**Comment by AlekseyTs** [comment]
Note, for a custom event
```
    event System.Action<dynamic> E2
    {
        add { }
        remove { }
    }
```
we report an error about missing DynamicAttribute, but do not emit it on the event type when the attribute is present. I have not checked behavior of the native compiler for this scenario.

**Comment by jaredpar** [comment]
Was this discovered as part of the nullable work or was it reported by a customer?

**Comment by AlekseyTs** [comment]
It was discovered by me, @MadsTorgersen confirmed that the current behavior is not "by design".

**Comment by jcouv** [comment]
Confirmed this problem already existed with the native compiler
`C:\Windows\Microsoft.NET\Framework\v4.0.30319\csc.exe`

**Comment by gafter** [comment]
Removing "Bug" as we seem to be using that for the most severe effects (e.g. compiler crashing, bad code gen, etc).

**Comment by jaredpar** [comment]
Adding "Bug" back as this is a bug.
