### ISSUE TITLE
Linux PR test fails when attempting to execute tests

### ISSUE THREAD

**Issue by TyOverby** [dotnet/roslyn#7854]
```
09:24:39 build/scripts/tests.sh /tmp/mono.linux.4/bin/mono Debug 2.1.0
09:24:39 /bin/bash: build/scripts/tests.sh: Permission denied
```

http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/2559/console

**Comment by TyOverby** [comment]
@agocke Feel free to punt this to someone else, Tanner thought you would know the most about this issue.

**Comment by TyOverby** [comment]
Same thing is happening on the mac builds

**Comment by robinsedlaczek** [comment]
@TyOverby Thanks for opening this issue. Does it mean, that you cannot accept any PR until this is fixed?

**Comment by TyOverby** [comment]
Interestingly #6790 is the PR that I've seen impacted.  

Unfortunately, Jenkins is offline for maintenance right now, but I plan on investigating this today.

**Comment by robinsedlaczek** [comment]
Great. But as far as I could see there are other PRs impacted, too. Nevertheless, would be great to see it fixed in order to see my PR accepted! :) Many thanks in advance!

**Comment by TyOverby** [comment]
This is a bug in #6790; closing
