### ISSUE TITLE
Wrong Snippet inserted.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#7858]
I happen upon this issue today.

**Example**
```VB
Module Module1

    Sub Main()
        Dim used = {1, 3, 5}
        Dim unused = Enumerable.Range(0, 10).E ' Highlight Except then do double tab.
    End Sub

End Module
```

**Actual Output**
```
Module Module1

    Sub Main()
        Dim used = {1, 3, 5}
        Dim unused = Enumerable.Range(0, 10).Public Class 
    Inherits System.Exception

    Public Sub New(ByVal message As String)
        MyBase.New(message)
    End Sub

    Public Sub New(ByVal message As String, ByVal inner As Exception)
        MyBase.New(message, inner)
    End Sub
    End Class
    End Sub

End Module
```
**Expected Output**

```
Module Module1

    Sub Main()
        Dim used = {1, 3, 5}
        Dim unused = Enumerable.Range(0, 10).Except( || ) ' || Caret position.

    End Sub

End Module

```

**Comment by Pilchie** [comment]
This happens because `Except` is the snippet shortcut for the "Define an Exception type" snippet.  It doesn't matter what was selected in completion before that - the snippet insertion logic just matches the characters in the editor when the second tab is pressed.

**Comment by AdamSpeight2008** [comment]
@Pilchie 
It looks it shouldn't do that from the intellisense.
![vs intellisense issue](https://cloud.githubusercontent.com/assets/900107/12241829/74cd6b98-b88d-11e5-98b9-20c599b03e6a.jpg)

**Comment by Pilchie** [comment]
The `Except` snippet is actually the one to define a new exception type.

**Comment by AdamSpeight2008** [comment]
@Pilchie yes, I know it outputs `Expection` snippet, but from the Note: in the intellisense it suggest that. It suggests something to do with `Enumerable.Expect`

**Comment by Pilchie** [comment]
It's not referring to the method, it's referring to the snippet which has the shortcut `Except`.  The tooltip logic just adds that text any time there is a snippet with a shortcut that matches the selected item.
