### ISSUE TITLE
Figure out what should be done in response to exceptions from RunServerCompilation and HandleResponse in BuildClient

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#7866]
See https://github.com/dotnet/roslyn/pull/7841

**Comment by jaredpar** [comment]
Seems like we should log the exception and then fall back to the local compilation.

**Comment by agocke** [comment]
What did you have in mind for logging?

**Comment by jaredpar** [comment]
Hmm.  I had originally thought we could hook into the logging infrastructure used by the compiler server.  But I don't think that will work for the client.  

Made me wonder more generally: when investigating bugs like this how can we make it easier to get information?  Should we set an environment variable and get detailed logs, etc ...
