### ISSUE TITLE
"Inline temporary variable" introduces an unnecessary cast

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/roslyn#7877]
In the following reduced snippet, I call the code fix "Inline temporary variable" on `temporary`

``` csharp
private void foo(MyType e)
{
    var temporary = e;
    if (temporary == MyType.PublicStaticReadonlyMemberOfMyType)
        return;
    // more code
    temporary.Member.Select(); // …
}
```

and get

``` csharp
private void foo(MyType e)
{
    if ((MyType)e == MyType.PublicStaticReadonlyMemberOfMyType)
        return;
    // more code
    e.Member.Select(); // …
}
```

The cast should be unnecessary, but it's not marked as superfluous (not grayed out). Removing it, doesn't introduce an error, though. `MyType` doesn't override any form of `Equals`, so `object.Equals` is chosen.

Later in that function, I use the `temporary` a second time, but that occurrence isn't replaced by a cast.

**Comment by CyrusNajmabadi** [comment]
This doesn't repro for me.  I get:

![image](https://user-images.githubusercontent.com/4564579/198718207-dc91eb20-4ee4-421f-9794-95c512a7d2bb.png)

Closing out.
