### ISSUE TITLE
Wrong source code location for CS0060 error

### ISSUE THREAD

**Issue by marek-safar** [dotnet/roslyn#7878]
```
internal class NV
{
}

public partial class C1
{
}

partial class C1 : NV
{
}
```

Produces error message like `x.cs(5,22): error CS0060: Inconsistent accessibility: base class 'NV' is less accessible than class 'C1'` but I'd expect the error row to be 9 not 5.

**Comment by leppie** [comment]
The code as it is now when dealing with `partial` seems to simply choose the first location. When debugging you will note there is 2 locations. 

It does not seem so trivial to address this as you would have to trawl through syntax trees to match where the actual base type is declared.

**Comment by leppie** [comment]
Heh, I just had to scroll up to get to the syntax needed :)
