### ISSUE TITLE
How to get the Keywords using Roslyn

### ISSUE THREAD

**Issue by Vidhyakp** [dotnet/roslyn#7879]
I need a script editor that provides intellisense and squiggling (something like  DotNetpad )

With Recommender I am not able to get the "keywords" which was possible using ICompletionService which was public in earlier versions of Roslyn (Roslyn.Services.ICompletionProvider).

Can you please let me know whether we have any thing similar to ICompletionService  in the latest Microsoft.CodeAnalysis version or any update on making "ICompletionService" public?

**Comment by Pilchie** [comment]
This is not currently possible, but issue #3538 is tracking that work.
