### ISSUE TITLE
Proposal: Attribute on auto-properties for backing fields

### ISSUE THREAD

**Issue by zdimension** [dotnet/roslyn#7880]
Recently, I started writing some game engin that reads some 15 years old file format (Tomb Raider II levels) and these levels are made of structures ([look here](http://www.tnlc.com/eep/tr/TRosettaStone.html)) that contains arrays. Most are fixed-size.
So I needed to do something like that:
```csharp
[MarshalAs(UnmanagedType.ByValArray, SizeConst = 256)]
public ushort[] SomeArray { get; set; }
```
It works, but if I replace ```ushort``` by a structure, here ```tr2_colour```, I get an error.
```csharp
public struct tr2_colour
{
    public byte Red;
    public byte Green;
    public byte Blue;
}

[MarshalAs(UnmanagedType.ByValArray, SizeConst = 256)]
public tr2_colour[] Palette { get; set; }
```
I get this error: ```Attribute 'System.Runtime.InteropServices.MarshalAsAttribute' is not valid on this declaration type. It is valid on Field, Parameter, ReturnValue only.```
So I need to make that property a property with backing field so that I can put the MarshalAs on the field that looks like that ```private tr2_colour[] _palette;``` and then it works.
It'd be great if it was possible to put attributes on auto-properties so that they go automatically on the backing field.

**Comment by HaloFour** [comment]
Check out #7004.

**Comment by zdimension** [comment]
Ah I'm sorry I didn't see it. I think I can close this one.
