### ISSUE TITLE
Add binary redirects in nuget packages for Roslyn

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#7889]
See https://github.com/dotnet/roslyn/issues/7654

It can be difficult to add the correct binary redirects in a console app to load a workspace and get things done in roslyn.  The roslyn SDK should generate all the necessary redirects so consumers do not need to think about this,

**Comment by Pilchie** [comment]
We should also generate the msbuild binding redirects we need for tasks that were built against MSBuild 2.0. (cc @mattwar @jasonmalinowski)

**Comment by jasonmalinowski** [comment]
Or we should just finally implement the AppDomain, since adding stuff in the SDK doesn't help people adding Roslyn to an existing app, or upgrading their apps to newer versions of Roslyn.

**Comment by jasonmalinowski** [comment]
Although an interesting thought: we could update our NuGet packages to include .targets which would let the MSBuild automatic app.config generation include the redirects. Was this what you were thinking of, @jmarolf?

**Comment by jmarolf** [comment]
@jasonmalinowski Yes, we could do more in the SDK itself, but the nuget packages should know how to do this. Changing the title...

**Comment by jmarolf** [comment]
Issue moved to [dotnet/roslyn-sdk #51](https://github.com/dotnet/roslyn-sdk/issues/51) via [**ZenHub**](https://www.zenhub.com/)
