### ISSUE TITLE
Consider adding support for syntax analyzer actions with a predicate for enclosing symbol

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn#7890]
Ported from internal TFS backlog. Originally filed by @mavasani :

---

While writing analyzers, I have very often felt the need for writing syntax actions which get executed only within a specific symbol. For example, writing diagnostics on how a DiagnosticAnalyzer should be written, we want to analyze code within sub-types of DiagnosticAnalyzer.

I feel this particular case is often enough to consider adding the below overload:

``` csharp
RegisterSyntaxNodeAction(Action<SyntaxNodeAnalysisContext> action, Func<ISymbol, bool> shouldAnalyzeSymbol, params SyntaxKind[] syntaxKinds)
```

Implementation of this should also be trivial: we execute the symbol predicate during `AnalyzerDriver.AnalyzeSymbol` and if it returns true, then execute the action in `AnalyzerDriver.AnalyzeDeclaringReferenceAsync` with other syntax node actions.

**Comment by CyrusNajmabadi** [comment]
Closing out.  We have RegisterSymbolStartAction for this purpose.
