### ISSUE TITLE
Local variable type is bound twice

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#7895]
The type of a local variable is bound *twice* in the C# compiler. Here are the two places

In Binder_Statements.cs
```cs
        private BoundStatement BindDeclarationStatement(LocalDeclarationStatementSyntax node, DiagnosticBag diagnostics)
        {
            var typeSyntax = node.Declaration.Type;
            bool isConst = node.IsConst;

            bool isVar;
            AliasSymbol alias;
            TypeSymbol declType = BindVariableType(node, diagnostics, typeSyntax, ref isConst, isVar: out isVar, alias: out alias);
```

In SourceLocalSymbol.cs (where diagnostics are computed and dropped on the floor):
```cs
        private TypeSymbol GetTypeSymbol()
        {
            var diagnostics = DiagnosticBag.GetInstance();

            Binder typeBinder = this.binder;

            bool isVar;
            TypeSymbol declType = typeBinder.BindType(_typeSyntax, diagnostics, out isVar);
```

For efficiency the compiler should bind each construct once.

**Comment by leppie** [comment]
The latter never seems to be called when `BindDeclarationStatement` is involved as `SetSymbolType` is called in `DeclareLocalVariable`. 

That said, it looks like `SourceLocalSymbol.IsVar` is never used.

**Comment by gafter** [comment]
@leppie Interesting. In that case there might not be an issue.

**Comment by jaredpar** [comment]
My investigation agrees with @leppie analysis.  Both places do have code paths that can result in calling `BindType` but use of `SetTypeSymbol` in the `DeclareLocalVariable` means the latter use will never be hit.  

Note: when debugging issues like this it's important to disable auto evaluation of properties.  Leaving it enabled can cause `_type` to be silently set just by stepping over interesting areas of the code base.
