### ISSUE TITLE
Wrong overload in intellisense in C#

### ISSUE THREAD

**Issue by ViIvanov** [dotnet/roslyn#7898]
Hello!

I have a next code in MSVS 2015 Update1 and updated Roslyn Compiler Platform SDK 1.2.0.51222 (I don`t tried this code with previous version of SDK or MSVS):

``` cs
enum E
{
  None,
}

class Program
{
    public static void M(E value) { }

    public void M() { }

    static void Main()
    {
        var p = new Program();
        p.M|
        // ^ caret here
    }
}
```

After pressing an open brace "(" intellisense suggests enum as parameter.

![image](https://cloud.githubusercontent.com/assets/795200/12259833/47208882-b929-11e5-8f55-71eb9e0f3cf7.png)

I think, parameter should not be suggested.

**Comment by Pilchie** [comment]
@rchande We thought this was a dupe, but couldn't find the original issue.

**Comment by SergeyZhurikhin** [comment]
I confirm, that this behavior is typical only for enumerations.

**Comment by SLaks** [comment]
There is also a more-general issue (which I reported privately); enum pre-selection needs to respect the selected overload in parameter help.

**Comment by CnSimonChan** [comment]
I also believe this is a dupe but I can only find this one so I post here.

--------

This problem also happens on `protected` constructors. When a class have two overloaded constructors like this one.

```` C#
public enum EnumA { A }

public class ClassA
{
    public ClassA() { }

    protected ClassA(EnumA e) { }

    public void DoSomething() { }

    protected void DoSomething(EnumA e) { }
}
````

When typing `new ClassA(|`, IntelliSense will preselect `EnumA` but display there is no overload. But this problem doesn't happen on `DoSomething()` method.

--------

There is also a reversed behavior on `Attribute` constructors, if an `Attribute` class have two `public` overloaded constructors like this one:

```` C#
public enum EnumA { A }

public class AttributeAAttribute : Attribute
{
    public AttributeAAttribute() { }

    public AttributeAAttribute(EnumA e) { }
}
````

Now typing `[AttributeA(|` will not preselect `EnumA`, and use arrow key to select the `AttributeAAttribute(EnumA e)` overload then hit `Ctrl` + `J`, IntelliSense still doesn't select `EnumA`.

**Comment by miloush** [comment]
I also believe this is a dupe, when ~~complaining~~ reporting, I remember being told that overload selection and code editor is now disconnected as opposed to VS 2013. 

(Might have been on Connect though, this is likely related: http://roslyn.codeplex.com/workitem/337)

The examples above are easy do dismiss as you only need to close the parenthesis, it gets worse when there are different parameters too:

![capture](https://cloud.githubusercontent.com/assets/10546952/14139559/c0c3de12-f66b-11e5-90a8-6f2e57b55e77.PNG)

Delegates especially are another tricky part as they toggle the completion mode, don't they?

**Comment by miloush** [comment]
Another broken example:
```C#
// in System.ServiceModel
X509SecurityTokenParameters p = new X509SecurityTokenParameters(|
```
hit Ctrl+Space. `X509SecurityTokenParameters` is preselected in autocomplete which doesn't make sense (The constructor has an overload without parameters and others that start with an enum).

**Comment by CyrusNajmabadi** [comment]
We do offer the enum preselected.  But typing the close paren will still close without inserting it.  So you can get the 'no argument' method call you want.
