### ISSUE TITLE
Inconsistent DeclaredAccessibility for property symbol between languages

### ISSUE THREAD

**Issue by Przemyslaw-W** [dotnet/roslyn#7899]
When I have protected internal property inside struct in c#, DeclaredAccessibility for corresponding property symbol has  value of Accessibility.ProtectedOrInternal.
When I have protected friend property inside structure in vb, DeclaredAccessibility for corresponding property symbol has value of Accessibility.Private.

It is inconsistent. Since above situation is error in both languages, they should behave similar. I believe VB behaviour is incorrect here.

**Comment by Przemyslaw-W** [comment]
I can see "Need More Info" label. What exact data do you need from me? code snippets?

**Comment by jmarolf** [comment]
@Przemyslaw-W it would be great to have a concrete example, perhaps in the form of code snippets
