### ISSUE TITLE
Missing dependency in deployment of Microsoft.CodeAnalysis

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#7907]
Crossgen fails on Microsoft.CodeAnalysis after `make bootstrap` unless `-MissingDependenciesOK` is added. This indicates we're missing a referenced assembly in the output. We should find that missing assembly and discover why it's not being copied.

**Comment by agocke** [comment]
If PR https://github.com/dotnet/roslyn/issues/7897 is merged the `-MissingDependenciesOK` argument should be removed from https://github.com/dotnet/roslyn/pull/7897/files#diff-5168909006e3e6b230fdd47857af8442R39

**Comment by jaredpar** [comment]
@agocke this PR is now merged, should we remove this line?

**Comment by jaredpar** [comment]
This is not actually a functionality bug.  Crossgen is complaining because we don't specify the full set of dependencies.  The `-MissingDependenciesOK` flag works around this for now.  Moving the resolution to Update 3.
