### ISSUE TITLE
VS crashes with ArgumentOutOfRangeException: "startIndex cannot be larger than length" for unclosed /* comment in C# source

### ISSUE THREAD

**Issue by basoundr** [dotnet/roslyn#791]
Ported from TFS WorkItem: **1108049**

------------------------------

**Repro Steps:**

Paste this C# code into ETA (or VS):
`/*`

System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.

&nbsp; at string.Substring(int startIndex)

&nbsp; at M.CA.Editor.CSharp.Outlining.CSharpOutliningHelpers.CreateCommentBannerTextWithPrefix(string text = "", string prefix = "/*")

&nbsp;

The call stack is attached.

See the dump at [\\mlangfs1\public\vladres\78c676647ef347a7917a0b954666544a](file://\\mlangfs1\public\vladres\78c676647ef347a7917a0b954666544a)

------------------------------

**Revisions:**

1) Created By Vladimir Reshetnikov (1/14/2015 2:23:48 PM)

------------------------------

2) Edited By Kevin Pilch-Bisson (1/15/2015 10:26:03 AM)

Leaving in RTM, because it has to be a a file with less than 2 characters after the /*.

------------------------------

**Comment by VladimirReshetnikov** [comment]
@VladimirReshetnikov

**Comment by VladimirReshetnikov** [comment]
@VladimirReshetnikov adding myself to the issue
