### ISSUE TITLE
Extension methods not offered for autocompletion in the owner class

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#7932]
```C#
public static class Test
{
    static void TestB()
    {     
        Te|
    }
    static void TestA(this string s) { }
}
```
Inside `TestB`, `TestA` should be offered in the autocompletion list as one starts typing it, but it is not.

**Comment by HaloFour** [comment]
I wonder if it's excluded because as an extension method it's required to be qualified by `this` (see #998) and IntelliSense does not expect you to be attempting to invoke it directly as a static member?

**Comment by miloush** [comment]
It's only required to be qualified by `this` if you are trying to call it within the inheritance chain without referring to the static type. You can't type `this` in the above example. Moreover, if offers you the methods if you qualify it with `Test` type itself, so that shouldn't be an issue. In either case it worked in previous versions of Visual Studio, and although I have no numbers, I wouldn't be surprised if that was a common syntax to call different overload of an extension method.

**Comment by HaloFour** [comment]
@miloush Of course.  I imagine that the second point still stands, that it's excluded intentionally because it is an extension method and the IDE doesn't expect you to intend to call it directly.

**Comment by Pilchie** [comment]
Nope - I think this is just a bug :frowning:

**Comment by Pilchie** [comment]
@rchande can you work with @dpen2000 to get the PR through?

**Comment by rchande** [comment]
Please verify, @rchande
