### ISSUE TITLE
[Bug] IntelliSense does not show Dispatcher in WPF

### ISSUE THREAD

**Issue by Unknown6656** [dotnet/roslyn#7936]
I do not know, whether this Bug only applies to VS2013 and VS2015, or if it is specific to my machine or installation, but my IntelliSense does not show the Property `Dispatcher` after having typed `this.  ...` inside a WPF Window / UserControl / etc.

**Comment by Pilchie** [comment]
The `Dispatcher` property is marked with `[EditorBrowsable(EditorBrowsableState.Advanced)]`, which means that we don't show it unless Tools\Options\Text Editor\C#\General - Hide advanced members is unchecked.

<img width="480" alt="screen shot 2016-01-13 at 1 19 59 pm" src="https://cloud.githubusercontent.com/assets/312835/12308155/753a37a2-b9f8-11e5-830c-cf03d30f0ff8.png">

**Comment by Unknown6656** [comment]
@Pilchie: Ooh - I am so dumb -_-

Do please excuse me, Sir, that I have openend a new issue only for this little "problem"
