### ISSUE TITLE
[PR Available] Remove IExpansionManager dynamic workaround

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#7943]
Introduced in https://github.com/dotnet/roslyn/pull/7935

I need to reference a type introduced in Update 1, but the build machines are still on RTM, so I'm working around it by calling the method I need dynamically. Once the build machines are on Update 1, I can remove the hack.

**Comment by dpoeschl** [comment]
Blocked by https://github.com/dotnet/roslyn/issues/7537

**Comment by dpoeschl** [comment]
Remove this from ExceptionLog.RegisterKnownExceptions when this is fixed.

**Comment by DustinCampbell** [comment]
@dpoeschl, what's the status of this issue now that the build machines are on Update 1?

**Comment by dpoeschl** [comment]
@DustinCampbell PR #9009. I had tagged it as fixing the wrong # so it  didn'tshow as linked here

**Comment by Pilchie** [comment]
Closing, since this is merged in future.
