### ISSUE TITLE
MSBuild error finding the nuget.targets file

### ISSUE THREAD

**Issue by bigbaldy1128** [dotnet/roslyn#7948]
I'm trying to build a csproj project with msbuild,but it fails with these errors:

The imported project "C:\SignalR-0.5.63pre\SignalR\\.nuget\nuget.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

The csproj specifies the location of the nuget.targets file like this:
&lt;Import Project="$(SolutionDir)\\.nuget\NuGet.targets" /&gt;

And the SolutionDir is defined like so:
&lt;SolutionDir Condition="$(SolutionDir) == '' Or $(SolutionDir) == '*Undefined*'">..\\</SolutionDir/&gt;

the csproj file is in C:\SignalR-0.5.63pre\SignalR,so I think $(SolutionDir) should be C:\SignalR-0.5.63pre,but $(SolutionDir) is C:\SignalR-0.5.63pre\SignalR in fact.I think msbuild parse SolutionDir is wrong

**Comment by asvishnyakov** [comment]
Maybe you just need `\` after `$(SolutionDir)` in `<Import Project="$(SolutionDir)\.nuget\NuGet.targets" />`?

**Comment by Pilchie** [comment]
It sounds like http://github.com/nuget/home might be a better place for this?  Tag @yishsaigalatzer.

**Comment by yishaigalatzer** [comment]
This doesn't look like a Roslyn or NuGet problem, it is a simple case of msbuild and importing targets. Can you validate that the targets are on disk, and yes you ned to add the extra `\`

**Comment by bigbaldy1128** [comment]
\\ just did not show,actually have,you can download source from https://github.com/SignalR/SignalR/tree/v0.5.63pre,then use MSBuildWorkspace.Create().OpenSolutionAsync("SignalR.sln"),problems will reproduce

**Comment by Pilchie** [comment]
It sounds like you'll need to do a nuget restore on the solution before you can open it.

**Comment by bigbaldy1128** [comment]
I think `<SolutionDir Condition="$(SolutionDir) == '' Or $(SolutionDir) == 'Undefined'">..\</SolutionDir/>` indicate `$(SolutionDir)` is `..\`,but in fact `$(SolutionDir)` points to the current path,`Import Project` should be `"..\.nuget\NuGet.targets"` instead of `".nuget\NuGet.targets"`

**Comment by bigbaldy1128** [comment]
For example:
the sln file is in `C:\a`

the csproj file is in `C:\a\b`

the csproj specifies the location of the nuget.targets file is:
 `<Import Project="$(SolutionDir)\.nuget\NuGet.targets" />`

and the SolutionDir is:
`<SolutionDir Condition="$(SolutionDir) == '' Or $(SolutionDir) == 'Undefined'">..\</SolutionDir/>`

msbuild should go to `c:\a\b\..\.nuget\` (`c:\a\.nuget\`) to search NuGet.targets,bug in fact it search the file in `c:\a\b\.nuget\`,of course it can not find

**Comment by mattwar** [comment]
MSBuildWorkspace sets SolutionDir to the directory of the solution file being opened.

**Comment by mattwar** [comment]
I don't reproduce this now.  Possibly this was fixed with nuget changes.

If you find this is still happening please re-open it.

**Comment by okutbay** [comment]
I'm having the same problem. SolutionDir is correct and there is no physical ".nuget" folder which contains the "NuGet.targets" file. Package restore did not created this folder and file, any other solutions?
