### ISSUE TITLE
Default argument operation doesn't handle caller info attributes

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#7960]
We need to decide if we want to make argument operation handles caller info attributes.

**Comment by jinujoseph** [comment]
@genlu (from cyrus) Do IArguments not expose the constant value that was passed to the call?  If so, then we shuold have this information.  If not, that's likely a bug that we would want to fix.

**Comment by genlu** [comment]
This information is not currently available. With the change I'm making (to use call rewriter to get arguments), there's a chance the fix will make into 15.3. I'm still testing/experimenting, will provide some update later. And I agree, whether in 15.3 or not, we will fix this :)
