### ISSUE TITLE
C# param array argument in operation needs improvement

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#7969]
1. insufficient check for a parameter treated as a valid params parameter by the compiler:
   https://github.com/dotnet/roslyn/pull/7352/files#diff-18ac4fedd81a77515d7f6800b5268a8eR229
2. param argument doesn't handle derived type correctly:
   https://github.com/dotnet/roslyn/pull/7352/files#diff-18ac4fedd81a77515d7f6800b5268a8eR233

**Comment by genlu** [comment]
This should be addressed by #19237

**Comment by jinujoseph** [comment]
closed via #19237
