### ISSUE TITLE
Allow type inference for ref and out in lambda

### ISSUE THREAD

**Issue by Thaina** [dotnet/roslyn#7977]
Normally we use lambda with type inference. This ability make our life easier when we need to work with variable which so long typename or namespace

But it sad that ref and out function cannot do type inference. I don't know why it hard to do

At least let we can `(ref i) => i++` or `(ref var i) => i++`

**Comment by ViIvanov** [comment]
I already created such issue #303

**Comment by Thaina** [comment]
as duplated
