### ISSUE TITLE
ForRef and MapRef extension method for array

### ISSUE THREAD

**Issue by Thaina** [dotnet/roslyn#7978]
It is an easy implement to let foreach for reference in array
I want it to be included in official System.Linq library

```
public delegate void RefAction<T>(ref T item);
public static void ForRef<T>(this T[] array,RefAction<T> action)
{
    int i = 0;
    while(i < array.Length)
    {
        action(ref array[i]);
        i++;
    }
}

public delegate void RefFunction<T,R>(ref T item,out R obj); //// (const T item,out R obj) is more preferable
public static R[] MapRef<T,R>(this T[] array,RefFunction<T,R> func)
{
    int i = 0;
    var res = new R[array.Length];
    while(i < array.Length)
    {
        func(ref array[i],out res[i]);
        i++;
    }

    return res;
}
```

Also it could be great if this pattern also allowed in Dictionary and List

I want to discus first then I may create a fork and pull request by myself

**Comment by davkean** [comment]
Hey, thanks for the bug - this belongs over on https://github.com/dotnet/corefx. Both Linq and anything related to arrays belongs in that repo.
