### ISSUE TITLE
Merge tool should automatically kick off eta/vsi runs

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#7983]
The merge tool should automatically do a VSI and an ETA run.

**Comment by TyOverby** [comment]
Does @dotnet-bot look in the pull-request description for test commands?

**Comment by davkean** [comment]
@TyOverby I'm not sure.

**Comment by TyOverby** [comment]
Do you know where the code for dotnet-bot lives?

**Comment by davkean** [comment]
This didn't work :( I was wrong.

You'll need to add a new comment.
