### ISSUE TITLE
Mac builds sporadically time out 

### ISSUE THREAD

**Issue by TyOverby** [dotnet/roslyn#7987]

**Comment by TyOverby** [comment]
http://dotnet-ci.cloudapp.net/job/roslyn_prtest_mac_dbg_unit32/2718/

**Comment by TyOverby** [comment]
cc @davkean

**Comment by TyOverby** [comment]
http://dotnet-ci.cloudapp.net/job/roslyn_prtest_mac_dbg_unit32/2712/

**Comment by TyOverby** [comment]
By looking at http://dotnet-ci.cloudapp.net/job/roslyn_prtest_mac_dbg_unit32/buildTimeTrend, we can see that quite a few of the builds are timing out.

Out of 400 builds (since Dec 29), 30 of them time out.

**Comment by jaredpar** [comment]
Duplicate of #6407.  It's the general Mono is timing out problem.
