### ISSUE TITLE
Snippets should be smarter about inserting accessibility modifiers

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#7988]
Many C# snippets for members include accessibility modifiers in them. For example, `prop` and `ctor` both include "public" right in the snippet. It'd be very cool if I could type private ctor<tab><tab> and rather than the snippet spitting public, it'd realize I already have an accessibility modifier and thus doesn't need to spit anything.

Chatting with @dpoeschl, one possible implementation would be the introduction of a new snippet function in the snippet like $modifier$. This would evaluate to "public" if there was no modifier, or just to an empty string if there already was one there. This would require us to update our snippets, but that wouldn't be too difficult to do.

**Comment by AdamSpeight2008** [comment]
mmm. :smirk_cat: : It's almost like you want templates (#174)?

**Comment by miloush** [comment]
You kind of can just update the snippets to allow you to specify modifier...

Or if you are that keen on typing the modifier first, you could use a surround with snippet to do the trick perhaps? :-)

Anyway I think there are subtle issues with this. Are you specifying modifier for the property or for the backing field? What should snippets that have multiple modifiers do?

**Comment by CyrusNajmabadi** [comment]
Consumed by 'semantic snippets'.  If there are issues tehre, they should be raised with the particular snippet.
