### ISSUE TITLE
PublicAPI.Shipped.txt files need to be updated for the 1.1.0/Update 1 baselines

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#7989]
The PublicAPI.Shipped.txt files in master need to be updated to include the APIs we shipped in 1.1/Update 1. Failure to do so means we might break back compat in 1.2/Update 2.

**Comment by jasonmalinowski** [comment]
@amcasey, did you do this?

**Comment by amcasey** [comment]
@jasonmalinowski I did something.  I wasn't clear on whether I had addressed all of your concerns.

**Comment by jasonmalinowski** [comment]
I think you did. :smile:
