### ISSUE TITLE
[Test Failure] Compile Error in prtest/win/dbg/eta on PR #7997

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#7998]
PR: [#7997](https://github.com/dotnet/roslyn/pull/7997) *Remove # character from VSIX descriptions.* by @CyrusNajmabadi
Failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/3195/

**Issue 1: Compile Error**
error CS2007: Unrecognized option: '/publicsign+' [d:\j\workspace\dotnet_roslyn_prtest_win_dbg_eta\Open\src\Workspaces\CSharp\Portable\CSharpWorkspace.csproj]

**Comment by davkean** [comment]
@agocke What's going on here?

**Comment by davkean** [comment]
I've looked and I have no idea how this failed, *at all*

**Comment by heejaechang** [comment]
I have hit same issue. should I retest or wait for fix?

**Comment by davkean** [comment]
@agocke Assuming Update 1 one is now done - or -blocked-. Please pick this up.

**Comment by davkean** [comment]
@jaredpar as FYI

**Comment by davkean** [comment]
@heejaechang Please link the build and retest

**Comment by agocke** [comment]
@heejaechang You can retest, I'm looking at the build

**Comment by agocke** [comment]
Build is http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/3061/

**Comment by davkean** [comment]
This has been resolved.
