### ISSUE TITLE
Using scripting API on UWP

### ISSUE THREAD

**Issue by tpetrina** [dotnet/roslyn#8005]
Is this even possible? Right now, using Scripting API-s in UWP raises runtime exception because get_CurrentDomain is not available. I tried to use a workaround by patching the compiler to correctly use `AssemblyLoadContext`:
```csharp
    internal static class CoreClrShim
    {

        internal static class AssemblyLoadContext
        {
            internal static readonly Type Type = ReflectionUtilities.TryGetType(
               "System.Runtime.Loader.AssemblyLoadContext, System.Runtime.Loader, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")
                ??
                ReflectionUtilities.TryGetType("System.Runtime.Loader.AssemblyLoadContext, mscorlib, Version = 4.0.0.0, Culture = neutral, PublicKeyToken = 7cec85d7bea7798e");
        }
```

This creates new problems and I get the following exception:

An exception of type 'System.IO.FileNotFoundException' occurred in Microsoft.CodeAnalysis.Scripting.dll but was not handled in user code

Additional information: Could not load file or assembly 'System.Runtime.Loader, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

If scripting is not supported UWP, why are libraries currently portable? I do hope this is work in progress as I would love to use it in Windows 10 apps.

**Comment by Suchiman** [comment]
I could be wrong but i don't think that this will work... some genius at microsoft put the requirement in place that every store app must be .NET Native so everything must be AOT compiled which means that there's no JIT at runtime and you can't do anything dynamically like scripting.

**Comment by tmat** [comment]
@Suchiman is correct, runtime code generation is not supported by UWP.

The libraries are portable so that they can be run on Core CLR on Windows, Linux and Mac OS.

**Comment by tpetrina** [comment]
Thanks for the clarification.

**Comment by 7eee** [comment]
They compile on Android, and I haven't tested them at runtime yet. But you get a linker error with `System.Runtime.Loader
`
