### ISSUE TITLE
NavigateTo omitting string resources (and other generated items)

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#8009]
Add a string resource named "SomeString" and then NavigateTo (ctrl+,) for SomeString. I would expect it to find the match in the .designer.cs file.

**Comment by dpoeschl** [comment]
@brettfo Did you say that the current behavior matches that of pre-VS2015?

**Comment by brettfo** [comment]
Correct, VS2013 doesn't search inside generated files, but I think I would like it to in certain instances like I think you mentioned in the Slack channel. E.g., include Something.Generated.cs, but not SomeControl.xaml.g.i.cs. Ideally this could be tuned by user options.

**Comment by Pilchie** [comment]
@DustinCampbell proposes a principle of: If the file is visible in solution explorer, it's contents should be available in Navigate To.

**Comment by CyrusNajmabadi** [comment]
Please fix this.  It's brutal in Roslyn given how many important types are generated and no longer show up in NavigateTo.

**Comment by Pilchie** [comment]
Assigning to @CyrusNajmabadi since he has the PR open for it.
