### ISSUE TITLE
[ide] Escaped Keyword Identifiers

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#8011]
Can we update the intellisense list for VB.net to include escaped keyword identifiers. 
eg `( [optional] as boolean )`

So that on typing `['. `[optional]` is one of the first, within the list. 
Instead having to type `optio` then find it in the list.

**Comment by Pilchie** [comment]
A few notes here:

1. C# does show escaped identifiers with the `@` in the list.
2. Note that there seems to be a parse issue with having an unclosed `[`.  If you turn automatic brace completion off, the completion list doesn't show at all.

Not sure if it's worth triggering completion on `[`.

**Comment by AdamSpeight2008** [comment]
In VB.net (I think) it could be starting an attribute or an escaped identifier. Both are equally likely give the context (of the repo above), slightly biased towards it being an identifier. Only trigger completion if it one of those contexts? @Pilchie

**Comment by Pilchie** [comment]
Attributes in VB use `<`, so it's always going to be an identfier.
