### ISSUE TITLE
Structs: Readonly fields and assigning to this

### ISSUE THREAD

**Issue by omariom** [dotnet/roslyn#8013]
It is allowed to assign to *this* even when struct has readonly fields. 
May be it should be forbidden?
 
```C#
private Wrapper wrapper = new Wrapper(33);

private void Main()
{
	Console.WriteLine(wrapper.Value);
	
	wrapper.Test();
	
	Console.WriteLine(wrapper.Value);
}

struct Wrapper
{
	readonly int value;

	public Wrapper(int value)
	{
		this.value = value;
	}
	
	public int Value => value;

	public void Test()
	{
		this = new Wrapper(44);
	}
}
```
Outputs:
33
44

**Comment by orthoxerox** [comment]
You can't disallow that without breaking existing programs, but perhaps an opt-in warning about mutating `this` reference could be added instead?

**Comment by Thaina** [comment]
I think that is fine

To create a struct yourself you have control over your implementation. To has method to mutate a struct even it has readonly field is the creator of that struct responsible. They may just want it tobe readonly so it cannot directly change but it could be change only from that method by changing everything something like that

**Comment by gafter** [comment]
You can write an analyzer to warn about this sort of thing, but we cannot and will not make such a breaking change in the language.

**Comment by omariom** [comment]
> but we cannot and will not make such a breaking change in the language.

I've realized a warning will be a breaking change as well.
So yes, an analyzer is the way to go in such case.
