### ISSUE TITLE
Feature Request: Passing by Value for reference types and vice versa

### ISSUE THREAD

**Issue by dan2002s** [dotnet/roslyn#8015]
**EDIT:** I'm using `int`s as an example, the idea is to have this work with reference types too.

**Bar and Foo are separate pieces of data.**

`int Foo = 34;`
`int Bar = 35;`

---------------------------------------

**Now we are setting Bar to the VALUE of Foo.**
Bar and Foo are still separacte pieces of data, but now they both equal 34.
If Bar changes it's value to 5, Foo's value will remain at 34.
If Foo changes it's value to 2, Bar's value will remain at 5.
This is a simple way of making Bar a deep copy of Foo.

`int Foo = 34;`
`int Bar = val Foo;`

---------------------------------------

**We are setting Bar to the REFERENCE of Foo.**
Bar points to the same piece of data as Foo now.
If Foo changes it's value to 3, Bar's value will also be 3.
If Bar changes it's value to 5, Foo's value will also be 5.

`int Foo = 34;`
`int Bar = ref Foo;`

---------------------------------------

`val int Foo = 43;`
`ref int Bar = ref Foo;`

**Foo can only contain a int value.** 
**Bar can only contain a int reference.**
Foo must contains it's own data (which is 43).
Bar must point to another piece of data (which is Foo's).

---------------------------------------

`val int Foo = ref Bar; // ERROR`
`ref int Bar = 789; // ERROR`

Foo cannot point to another piece of data.
Bar cannot contain it's own data, only a reference.

---------------------------------------

**References must eventually point to a value.**
If references doesn't point to a value, 
or point to a null reference you get null back! (Or exception, maybe?)

`ref int Thing1;`
`ref int Thing2;`
`Thing1 = ref Thing2;`
`Thing2 = ref Thing1;`
`// ERROR! Thing1 is refering to Thing2, but Thing2 is refering back to Thing1`

`val int Thing1 = 34;`
`ref int Thing2;`
`ref int Thing3;`
`Thing3 = ref Thing1;`
`Thing2 = ref Thing3;`
`// FINE!`

`val int Thing1 = 34;`
`ref int Thing2;`
`ref int Thing3;`
`ref int Thing4;`
`Thing2 = ref Thing1;`
`Thing3 = ref Thing2;`
`Thing4 = ref Thing2;`
`// FINE!`

**Comment by aluanhaddad** [comment]
What are the _deep copy_ semantics proposed? The examples you provide only deal with ints. Specifically, how are the issues with ```ICloneable``` addressed in this proposal?

**Comment by HaloFour** [comment]
What problem is this supposed to solve exactly?  You can already pass the references of a reference type by value and a value type by reference.

**Comment by svick** [comment]
Part of this is a duplicate of #118.

Part of this doesn't make much sense to me: why are you adding `val int` when `int` already behaves like that, and why are you turning `int` into some hybrid "can either be a reference or a value"? Why would that *ever* be useful? It doubt it makes sense to make this the default (especially since it would likely mean degrading performance of existing code).

**Comment by dan2002s** [comment]
The idea, is that it wouldn't only work with `ints`, but reference types too.

**Comment by HaloFour** [comment]
@dan2002s What exactly is "it"?  Deep cloning isn't something built into the CLR.  Even with structs if they contain a field of a reference type it is only the reference that is copied.  Exactly what "cloning" means is left up to the individual classes that implement `ICloneable`.

**Comment by dan2002s** [comment]
@svick You can't think of one time you'd want to pass a value type by reference or a reference type by value???

**Comment by dan2002s** [comment]
@HaloFour Why can't deep cloning by built into c#, that kinda what i'm proposing. Don't you read the question!?

**Cloning:** Making a duplicate of a object that has NO references shared between the original object and any child objects.

**Comment by HaloFour** [comment]
@dan2002s C# can still only go as far as the CLR lets it.  C# could automatically cause every class written in it to be deep-clonable by supporting `ICloneable`, etc., but why should it?  You'd be incurring fairly heavy penalties for something few classes would need to use and would defeat the purpose of attempting to attain the performance benefits of treating reference types as value types.

As for treating value types like references, you have `ref`, pointers and #118, all of which are basically different syntax around the same IL.

**Comment by dan2002s** [comment]
Whatever...
I'll keep dreaming then...

**Comment by dan2002s** [comment]
With `ICloneable` you have to be super careful otherwise you'll only get a shallow clone anyway.

**Comment by paulomorgado** [comment]
There's nothing in `IClonable` that mandates it to be deep or shallow.

> An implementation of Clone can perform either a deep copy or a shallow copy.
> https://msdn.microsoft.com/library/System.ICloneable.Clone

It's up to the implementer and there's nothing the caller can do about it.

**Comment by dan2002s** [comment]
My point exactly, using `IClonable` means you won't always get a deep copy unless you use it on classes you've made (assuming you implement it.properly).
