### ISSUE TITLE
Proposal : Replacing current obejct

### ISSUE THREAD

**Issue by vbcodec** [dotnet/roslyn#8019]
In some cases, ability to replace 'ambient' objects available inside methods inside classes, could be useful.

```
Class cx

    Public m1 As Integer = 1

    Public Sub s1()
        ' here Me.m1 = 1
        Dim no = New cx With {.m1 = 2}
        Me = no
        ' here Me.m1 = 2
    End Sub

End Class
```

This should be also available to external methods (outside classes), like:

```
    Public Sub ExtMethod(Dim obj As cx)
        Dim no = New cx With {.m1 = 2}
        obj.Me = no
    End Sub
```

This is very useful, especially inside async function / lambdas, where execution is delayed and should be performed on newest instance.
Currently replacing is only available by raw copying using reflection which may be problematic (read only members, properties with code).

**Comment by HaloFour** [comment]
What actual use cases would something like this solve?  Even assuming that any of this was remotely verifiable or permitted by the CLR (and I'm fairly sure that none of it is) I can't imagine any problem that couldn't be solved without such raw memory chicanery.

**Comment by mburbea** [comment]
This is possible if Cx were a struct. In structs I find this useful to have a ctor that doesn't initialize all members (e.g. `this = default(MyStruct)`), I can't really think of many other use cases.

**Comment by vbcodec** [comment]
@HaloFour , @mburbea 
I have posted this proposal from practical standpoint, not some theoretical speculation. I have app with documents that read content from database. These document have buttons with events handled by async functions, because user must provide some data. I also have background system that updates database periodically. There are situations with fired async handlers waiting for data from users, and updating data in database related to document. After database is updated, I want to reload document, but it will cause problems, because async function will continue on previous instance of document, not newest one. There are many workarounds, but I have realized, that object replacement could be best.
There may be other situations where you put some object into collection inside other object or register it by calling function. This object may be waiting for processing, and if you realize that there are wrong data, you are forced to pull it from collection or unregister it, then again register new instance with correct data. For such cases replacing object is fastest and simplest way.
You may ask: why create new instance ? just update data on current object. As you may imagine, some objects may be very complex, and require complex code to update it, or there may be read-only members or just unavailable members, and update is impossible. For these cases only creating new instance and perform some default initialization (not counting ctor) is possible..

**Comment by HaloFour** [comment]
You could wrap those instances within another class which simply contains an instance to a reference.  Then you can modify the instance within those classes at well and any code that has a reference to the wrapper instance would see the change immediately.  This has the added benefit of being able to add event handlers to the wrapper to notify classes that the contained data has changed.

Overwriting the memory of an instance that already exists would certainly be unsafe territory and I'm quite certain that the CLR would very much forbid it.

**Comment by vbcodec** [comment]
Using wrappers is some workaround, as I have stated above. But it not solve async function that still refer to original object. These internal functions may be changed to track for newest instaces, but this complicates code. And if you cannot change code (using class from library), wrappers are useless.

**Comment by diryboy** [comment]
I am scared about this. A lot of existing code do not expect their states get swapped in the middle. It would yield undeterministic behavior. It sounds like yet another GC that not only potentially pause your code, but also do some potential damage.

If you want, you can put all fields that your code expects to be swapped without notice in a struct as the field type of your object.

**Comment by svick** [comment]
@vbcodec For the first situation, I think what you actually want is cancellation.

**Comment by vbcodec** [comment]
@diryboy 
None problems here. If tow threads use the same object and one of them want to replace object, then they must use mutex or monitor for sync, just ordinary synchronization techniques,

@svick 
I do not want to cancel anything, but continue procedure with new object's instance

**Comment by HaloFour** [comment]
@vbcodec 

Which renders the entirety of the CLR completely un-thread-safe.  It would be impossible to overwrite the memory of a class instance atomically making every single method invocation, every single property accessor and every single field access would need to be wrapped by some arbitrary synchronization mechanism.  I'm sorry, the entire concept is horrid.  Having memory flipped out from under you is the epitome of unsafe software and would be considered bad practice even in languages where it might be possible.

**Comment by vbcodec** [comment]
@HaloFour 
This idea is very simple and help to avoid complex problems or using convoluted workarounds.
Object replacement do not require any new features to protect from concurrency. It is up to devs to provide synchronization where necessary, just like any other currently used techniques with shared data. Do not suggest that such nonsense perfect protection is required, because it is not.
Also, do not worry about implementation details. Roslyn/CLR teams are smart enough to implement it with ease.

**Comment by HaloFour** [comment]
@vbcodec 

The problem is a complicated, messy, convoluted and inherently unsafe problem to normal issues of learning to design around concurrency and merging.

As for implementation details, even if the Roslyn team loved this (which I can guarantee they won't) they couldn't do anything about it anyway because the CLR doesn't make anything like this possible.  You can try your hand suggesting it to the CoreCLR team but I'm quite certain that they'll be similarly receptive.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
