### ISSUE TITLE
CompilationWithAnalyzers.GetEffectiveDiagnostics API

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#802]
See discussions in PR #775.  CompilationWithAnalyzers.GetEffectiveDiagnostics iterates on the passed in IEnumerable, but the API consumer might have changed the contents of the passed in data structure as the API is an iterator API.
Possible actions:

1. Change the API to either take an ImmutableArray parameter or return an ImmutableArray or both, so that source of filtered collection is force computed before control leaves this API.
2. Fix the API to execute .ToImmutableArray() on passed in IEnumerable before iterating in the foreach loop.
3. Document the API to warn API consumers of guarding against this, and fix nothing.

**Comment by srivatsn** [comment]
I believe we decided to fix nothing here.

**Comment by mavasani** [comment]
I think we need to at least do (2) or (3), otherwise the API is bound to throw for any consumer that is passing a truly delay-computed IEnumerable.

**Comment by srivatsn** [comment]
Fair enough. Can you add a comment about it then? - i.e (3)
