### ISSUE TITLE
Access static members via `static` function. (Shared in VB)

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#8021]
This proposal is for use reuse `static`(c#) and `shared`(vb). So that they can be used a function to access the static / shared members of an object.

```C#
T Foo<T >() where T is Derived
{
  var tmp = static(T).GetNew()
  return tmp
}
```

```vb.net
Function Foo(Of T As Derived)() as T
  Dim tmp =  Shared(T).GetNew() 
  Return Tmp
End Function
```

**Comment by GeirGrusom** [comment]
How is this useful exactly?

**Comment by AdamSpeight2008** [comment]
@GeirGrusom  Let's say we know that there is always going the be a specific shared method, implemented on the those inheriting `derived`

For example `.CreateNew( )`

```vb
Public MustInherit Class Parsed
    Friend Sub New(s As Source.Span, Last As Source.Reader)
        Me.Span = s
        Me.Last = Last
    End Sub
    Public ReadOnly Property Span As Source.Span
    Public ReadOnly Property Last As Source.Reader

    Public MustInherit Class Parsed(Of q As Parsed)
        Inherits Parsed
        Friend Sub New(s As Source.Span, last As Source.Reader)
            MyBase.New(s, last)
        End Sub
        MustOverride Function GetParser() As Parser(Of q)
    End Class

End Class

Public MustInherit Class Parser
End Class
Public MustInherit Class Parser(Of t As Parsed)
    Inherits Parser
    Public MustOverride Function Parse(sr As Source.Reader, ByRef output As t) As Boolean
End Class
```
Instead on passing in the "default" `parser`,
```vb
Public Class Opt
    Public ReadOnly Property State As Boolean
    Protected Friend Sub New(state As Boolean)
        Me.State = state

    End Sub

    Public Class opt(Of t As Parsed)
        Inherits Opt
        Protected Friend Sub New(state As Boolean, Content As t)
            MyBase.New(state)
            Me.Content = Content
        End Sub
        Public ReadOnly Property Content As t
    End Class

    Public Shared Function ional(Of T As Parsed.Parsed(Of T))(p As Parser(Of T), sr As Source.Reader) As opt(Of T)
        Dim output As T
        Dim Res = p.Parse(sr, output)
'...
    End Function
End Class
```
we could access it via `Shared(t)`.
```vb
   Public Shared Function ional(Of T As Parsed.Parsed(Of T))( sr As Source.Reader) As opt(Of T)
        Dim output As T
        Dim Res = shared(T).GetParser.Parse(sr, output)
'...
    End Function
End Class
```

**Comment by AdamSpeight2008** [comment]
The compiler can infer that this usage of `T` must the additional constraint that the `T` must have a `shared GetParser` method.

**Comment by HaloFour** [comment]
The compiler can, but the CLR can't, which will result in a runtime exception if someone forces an invalid type either through a different language or via reflection.  I would expect that any such constraint would have to be explicitly declared and not inferred from usage.  I also don't believe that there is any clean IL that could be emitted to invoke that static member short of using reflection which seems pretty kludgy.

I believe #154 already touched on generic constraints for static members.

**Comment by AdamSpeight2008** [comment]
@GeirGrusom If we did have static interfaces, wouldn't you still need a way of accessing the "static" context of the type?

**Comment by GeirGrusom** [comment]
@AdamSpeight2008 Yes. Isn't that what this is about though?
Currently C# doesn't allow accessing static members of generic type arguments. If it did should it select the shadowed method, or the shadowing method? `static(T)` could resolve that.

**Comment by AdamSpeight2008** [comment]
`static(Tobj)` should only give access to shared member on the `derived`, as we can always cast to the base type first `static(TObj as Tbase)`

**Comment by GeirGrusom** [comment]
> static(Tobj) should only give access to shared member on the derived, as we can always cast to the base type first static(TObj as Tbase)

Or just use `TBase` directly. Why should it only give access to shared members?

**Comment by AdamSpeight2008** [comment]
@GeirGrusom 
Because, we don't have an instance. In VB if do the language already lets you access them via an instance. This proposal is more about the case when we don't.

**Comment by HaloFour** [comment]
Just so that I understand this correctly, the proposal is that the following should work?

```cs
public class Foo {
    public static void Hello() {
        Console.WriteLine("Hello from Foo!");
    }
}

public class Bar : Foo {
    public static void Hello() {
        Console.WriteLine("Hello from Bar!");
    }
}

public class Baz : Bar { }

public class Frob : Foo { }

public T PityFoo<T>() where T : Foo {
    static(T).Hello();
}
```

I'm not sure that I understand what the compiler should be doing, using reflection to look up whether the specified class as a static function with the same signature as `Foo.Hello` and then invoking it?  If the type argument doesn't have a matching static method should it walk the class hierarchy backwards looking for one?

There are only two ways that I can see this proposal being feasible.  Either the CLR officially gets the notion of virtual static members where a type has a vtable, or the CLR officially gets support for static member generic type constraints.  Otherwise there is really nothing for the compiler/CLR to enforce that the generic type argument meets the requirement.

Also, `static(T)` and `Shared(T)` both would seem extraneous, `T.Hello()` should be sufficient in both the case of C# and VB.NET as `T` does refer to the type.  The fact that VB.NET does let you invoke a static method off of an instance shouldn't have a bearing on that.

**Comment by AdamSpeight2008** [comment]
I agree that `static(T)` and `Shared(T)` are probably extraneous, but to me it make explicitly clearer in the code that you're working with the static aspects of the type.

>If the type argument doesn't have a matching static method should it walk the class hierarchy backwards looking for one?

No.  compile-time error.  I think inheriting `static` members would be wrong, 
```c#
public void PityFoo<T>() where T : Foo {
    static(T).Hello();
}

PityFoo<Foo>();  // outputs to console Hello from Foo!
PityFoo<Bar>();  // outputs to console Hello from Bar!
PityFoo<Baz>();  // Error
PityFoo<Frob>(); // Error
```

----

If we to allow inherited `static` members, I suggest we make it opt in. 
```c#
public class Baz : Bar, static<Bar> { }
public class Frob : Foo, static<Foo> { }
```
**examples**
These would then walk up the (static) inheritance chain, 
```c#
PityFoo<Baz>();  // outputs to console Hello from Foo!
PityFoo<Frob>(); // outputs to console Hello from Bar!
```

**Comment by HaloFour** [comment]
@AdamSpeight2008 

So this is a generic constraint for static methods.  As such I definitely don't think that the constraint should be inferred.  As with any generic constraint it should be explicitly declared via a `where` clause.  And without proper CLR support I'd be concerned about compilers being able to enforce it properly.  F# has such these kinds of constraints but they are erased by necessity and other languages can use them with invalid types resulting in an exception at runtime.

**Comment by GeirGrusom** [comment]
@AdamSpeight2008

> Because, we don't have an instance

So? What does this proposal have to do with instances? TObj is a type, and so is TDerived. I thought this proposal was about being able to call static members on these, and make TObj call a shadowing static member... It will require CLR support though.

> In VB if do the language already lets you access them via an instance.

Well in my opinion that is a design flaw left over from VB6.

In any case static methods is a way in C# to do procedural programming. I think implementing inheritance chains is very very wrong. Use singletons instead.

**Comment by AdamSpeight2008** [comment]
@GeirGrusom + @HaloFour 

What should happen in the non generics case?
```c#
static void PityFoo( Foo obj )
{
  static(obj).SayHello();
}
```

Would this only ever output to the console `Hello from Foo!`

**Comment by HaloFour** [comment]
@AdamSpeight2008 

That syntax has zero purpose.  `Foo.SayHello()` is perfectly sufficient.  C# definitely doesn't need to repeat the mistakes of VB.NET.  Even in the context of this proposal, `static(T)` and `Shared(T)` serves no utility.

**Comment by AdamSpeight2008** [comment]
@HaloFour  What if I pass in a `bar`?
```c#
var b = new bar();
b.PityFoo();
```

**Comment by AdamSpeight2008** [comment]
`static` does help,  
```c#
public void PityFoo<object>() where object : Foo {
    static(object).Hello();
}
```

**Comment by HaloFour** [comment]
@AdamSpeight2008 

No, `status(object)` just makes things confusing.  The proper syntax is `Foo.Hello()` and there is no reason to add some additional keyword to emulate a really bad idea from VB.NET.

**Comment by AdamSpeight2008** [comment]
**@HaloFour**
That only works when you know the type. The methods accepts any type the inherits `Foo`. I ask what what happens when it passed an instance of an object that isn't `Foo`, lets say a `Bar`

**Comment by HaloFour** [comment]
@AdamSpeight2008 

Simple, `Foo.Hello()`, because static methods aren't virtual.  This is even the case in VB.NET, it will invoke the static method based on the type of the *variable* regardless of what the instance happens to be:

```vb
Dim o As Foo = new Bar()
o.Hello() ' calls Foo.Hello()
```

**Comment by AdamSpeight2008** [comment]
Also if we have extension methods, for `static`.
```c#
static bool method(this static(Foo),  ... ){ ... }
```

**Comment by AdamSpeight2008** [comment]
@GeirGrusom How do you access the singleton?

**Comment by HaloFour** [comment]
@AdamSpeight2008

>  if we have extension methods, for `static`.

That would be a completely unrelated proposal, and there it still wouldn't make any sense because there would be no `this` parameter to be assigned.  Even you omitted the identifier name, and it would make less sense to have a half-parameter just to try to declare where the static extension belonged.

**Comment by gafter** [comment]
This is a dup of #154.
