### ISSUE TITLE
Can roslyn analyzer errors fail the linux and mac queues?

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#8028]
In https://github.com/dotnet/roslyn/pull/7413, I pushed a commit that was missing some public API entries.  The windows run failed to compile but the linux and mac runs passed.  Is this expected?  The public API is just as undocumented on linux, so I would have expected the build to fail on all platforms.

**Comment by amcasey** [comment]
FYI @dotnet/roslyn-infrastructure

**Comment by amcasey** [comment]
FWIW, the linux build seems not to have encountered `RS0016` so succeeding seems like the right outcome.  http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/2884/console

**Comment by davkean** [comment]
Do we build this API on Linux and Mac?
