### ISSUE TITLE
Order of symbols provided by DataFlowAnalysis should be deterministic

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#803]
DataFlowAnalysis exposes various symbol lists (VariablesDeclared, DataFlowsIn, etc.). The order of symbols in these arrays is non-deterministic. The underlying implementation usually dumps the content of a hash set or a dictionary to these arrays.

Since it’s too easy to take a dependency on the order when enumerating items of an array.

**Comment by gafter** [comment]
@AlekseyTs Can you please "Verify" that this has been fixed?
