### ISSUE TITLE
C# /langversion:3 handles closures in foreach loops like /langversion:5

### ISSUE THREAD

**Issue by binki** [dotnet/roslyn#8034]
```
C:\Users\ohnob\Documents\Visual Studio 2015\Projects\ConsoleApplication9>PROMPT ^>

>cat Program.cs
﻿using System;
using System.Collections.Generic;
using System.Linq;

public class Program
{
    public static void Main()
    {
        var closures = new List<Action>();
        foreach (var i in Enumerable.Range(0, 10))
            closures.Add(() => Console.WriteLine(i));
        foreach (var closure in closures)
            closure();
    }
}

>packages\Microsoft.Net.Compilers.1.2.0-beta1-20160108-01\tools\csc.exe /langversion:3 /out:Program.exe Program.cs
Microsoft (R) Visual C# Compiler version 1.2.0.60108
Copyright (C) Microsoft Corporation. All rights reserved.


>.\Program.exe
0
1
2
3
4
5
6
7
8
9

>
```

I was expecting all lines to output `10` if [Eric Lippert’s comment on how this behavior changes in C#-5.0](http://stackoverflow.com/a/8899347/429091) are accurate.

It seems weird to me that the compiler claims to support langversions less than 5 when it won’t change such a breaking behavior as this. There are other examples of when setting `/langversion` behaves like the latest compiler rather than an older one, please let me know if I should file issues like this when I notice them.

**Comment by gafter** [comment]
Yeah, this is intentional. the `/langversion` switch affects the syntax recognized by the compiler, not the semantics.
