### ISSUE TITLE
Proposal - Ability to call family ctors within the body

### ISSUE THREAD

**Issue by ghost** [dotnet/roslyn#8043]
At present:

``` C#
abstract class A
{
    public A(object obj)
    {
        InitConfigA(obj);
        PostInitConfig(obj);
    }

    private void InitConfigA(object obj) { /* snip */ }
    protected abstract void PostInitConfig(object obj);
}

class B : A
{
    public B() : base(new object())
    {
        InitConfigB();
    }

    private void InitConfigB() { /* snip */ }
    protected override void PostInitConfig(object obj) { /* snip */ }
}
```

Base will be called before `InitConfigB()`.

To be able to do call base after `InitConfigB`, we need to extract out that code in a base class method and call in the base ctor.

This proposal is about providing a semantically improved way to alert the sequence of sibling and base ctors (similar to what is possible in Java):

``` C#
abstract class A
{
    public A(object obj)
    {
        InitConfigA(obj);
        PostInitConfig(obj);
    }

    private void InitConfigA(object obj) { /* snip */ }
    protected abstract void PostInitConfig(object obj);
}

class B : A
{
    public B()
    {
        InitConfigB();

        base(new object());
        this(new object());
        // base(new object()); // <- calling the same ctor twice can be a compile-time error
    }

    public B(object obj) { /* snip */ }
    private void InitConfigB() { /* snip */ }
    protected override void PostInitConfig(object obj) { /* snip */ }
}
```

**Comment by svick** [comment]
In what situations would this be useful?

**Comment by HaloFour** [comment]
```cs
    public B()
    {
        InitConfigB();

        base(new object());
        this(new object());
    }
```

This will cause two constructors on the base class to be called since the sibling constructor is required to chain to either another sibling constructor or a base constructor.  The currently syntax limitations exist to ensure that only one constructor chain is invoked.

There have been other proposals about being able to call methods before the parent/sibling constructor for the purposes of initialization, but the problem there is that such a method would not be able to update `readonly` fields thus neutering their functionality.  There are also concerns that calling out into arbitrary methods could lead to a call into the base class that has not yet been initialized causing unexpected problems.  I've run into this personally with custom serialization as the CLR invokes the deserialization methods before calling any constructors and I had to tiptoe around what I could do with the base class as many methods expected fields to be instantiated and initialized by the base constructors but since it was never called those fields were all `null`.

**Comment by orthoxerox** [comment]
I think sequence expressions (#6182), when implemented, will provide a viable, albeit ugly, way out.

```c#
class A
{
	public A(int foo)
	{
		...
	}
}

class B : A
{
	public B(Florb foo)
	: base((
		if (foo is null) throw new ArgumentNullException(nameof(foo));
		int foovalue;
		if (!TryDeflorbinate(foo, out foovalue)) foovalue = DefaultFoo();
		OhAndSetBlubAtThisPointAsWell();
		foovalue))
	{
		...the rest of the constructor...
	}	
}
```

**Comment by jasonwilliams200OK** [comment]
@svick, the proposal is about giving user more control over object construction, similar to Java.

@HaloFour, I wonder if there is any CLR limitation to achieve this?
Regarding the sibling ctor calling the base chain; this is a very good point. My suggestion is to to opt out of default chain in the presence of `this()` or `base()` calls in the ctor body and create a graph which would work like this:

* Analyze step 1: If one of the mandatory ctor is not called, insert it immediately right after the first neighboring node.
* Analyze step 2: If any paths overlap; throw compile time exception: "`CtorSignature` is called multiple times", preferably with code-paths/call-stacks: "`CtorSignature` is called multiple times: \n 1) ..call stack lines for first path... 2) ..call stack lines for second path.. and so on..".
* If any field/property is accessed which is yet to initialized, throw regular NRE at run time. User will still be able to add null checks branches to keep the code paths reusable.

@orthoxerox, that is an interesting approach too. IMO, both can co-exist.

**Comment by HaloFour** [comment]
@jasonwilliams200OK

The CLR considers it to be invalid if a constructor never calls a sibling/parent constructor.  The CLR also considers it to be invalid if the constructor attempts to push the `this` pointer into the stack prior to the sibling/parent constructor being called, which eliminates being able to invoke instance methods or assign instance fields.

**Comment by HaloFour** [comment]
Essentially it seems that the CLR explicitly forbids what you're attempting to propose, invoking an instance method prior to initializing the instance.  

The following code:

```cs
public B(object obj) {
    InitConfigB();
    base(obj);
}
```

Would result in the following IL:

```
ldarg.0
call instance void B::InitConfigB()
ldarg.0
ldarg.1
call instance void A::.ctor(object)
ret
```

Which results in the following error from peverify.exe:

```
[IL]: Error: [b.exe : B::.ctor][offset 0x00000001]
[found <uninitialized> ref ('this' ptr) 'B'][expected ref 'B'] Unexpected type on the stack.
```

**Comment by jasonwilliams200OK** [comment]
Nice fine!

> Unexpected type on the stack.

Looks like it only gets checked in debug config:
https://github.com/dotnet/coreclr/blob/2b3c93d/src/utilcode/ex.cpp#L1309

**Comment by HaloFour** [comment]
> Looks like it only gets checked in debug config:

This is true.  The behavior at runtime in a release build is probably indeterminate.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
