### ISSUE TITLE
Proposal: Local variable scoping syntax

### ISSUE THREAD

**Issue by dsaf** [dotnet/roslyn#8049]
(This is inspired by #8004)

Scoping helps reducing cognitive load just like immutability and encapsulation are. More granular functions can help, but are not always ideal.

Current syntax for local variable scoping is being avoided due to (1) extra brackets and (2) lack of explicitness (unless variable is ```IDisposable```):

(1)
```csharp
//Maintaining developer's thoughts: "Are extra brackets a mistake? What was the motivation? Better remove them to make code shorter..."
{
  var text = "Hello";
  Console.WriteLine(text); 
}

Console.WriteLine(text); // Use unintended, compiler error is expected.
```

(2)
```csharp
//Maintaining developer's thoughts: "OK, so this thing is disposable and is only used in this small scope."
using (var something = new Something())
{
  something.Do();
}

something.Do(); // Use unintended, compiler error is expected.
```

Why not introduce a more explicit scoping syntax e.g. using a keyword such as ```unvar```?

Prefix statement form:

```csharp
var text = "Hello";
Console.WriteLine(text);
unvar text;

Console.WriteLine(text); // Use unintended, compiler error is expected.
```

Postfix inline form (use-and-destroy):

```csharp
var text = "Hello";
Console.WriteLine(text unvar);

Console.WriteLine(text); // Use unintended, compiler error is expected.
```

It might even actually remove the variable from memory stack if this is beneficial, but again **the focus is on cognitive load reduction rather than memory management**.

**Comment by dsaf** [comment]
This would also be possible:

```csharp
var text = "Hello 1";
unvar text;

//Cannot use the variable text here.

var text = "Hello 2";
unvar text;

//Cannot use the variable text here.

var text = "Hello 3";
unvar text;

//Cannot use the variable text here.
```

**Comment by olivier-spinelli** [comment]
What about this simpler (and still structured)  syntax?

    using
    {
        var text = "Hello";
    }

IMO `unvar` breaks structure, and this is bad.

**Comment by HaloFour** [comment]
I agree, arbitrary points at which a variable is dropped out of scope that doesn't rely on block scoping seems very unstructured.

Adding new syntax or use of keywords before/around existing block syntax seems quite unnecessary.  You're making something more verbose for the sake of being more verbose, and the existing block syntax is just as readable.

**Comment by olivier-spinelli** [comment]
@HaloFour I agree with you, the only point is I have seen {scopes} removes by programmers that missed the {point}. Using using would have avoid this.

**Comment by alrz** [comment]
I just don't understand what's is wrong with current block's scoping. As a common pattern which is followed by Roslyn codebase,
```cs
switch( ... ) {
  case 0:
  {
     var scoped = ...
     F(scoped);
     break;
  }
  case 1:
  {
     var scoped = ...
     G(scoped);
     break;
  }
}
```
with the proposed syntax it could be rewritten like this,
```cs
switch( ... ) {
  case 0:
     var scoped = ...
     G(scoped);
     unvar scoped;
     break;
  case 1:
     var scoped = ...
     F(scoped);
     unvar scoped;
     break;
}
```
which is horrible.

**Comment by MgSam** [comment]
If you really have a business case for preventing a local variable from being used again, whatever piece of "sensitive code" its a part of should be its own method. We shouldn't add features to the language that encourage long, unreadable methods.

**Comment by orthoxerox** [comment]
Related to #3718 (let-in)

**Comment by dsaf** [comment]
@olivier-spinelli 

```csharp
using {}
```

There is no indication of what exactly is being "used".

@alrz 1) this is not a replacement syntax for every scenario; 2) in that specific example brackets don't look awkward only because they are preceded with ```case```s and could potentially lead to ```break```s being omitted by less experienced developers.

@MgSam I usually start wishing for better scoping syntax when working with unit tests, particularly their arranging part. In my opinion unit tests often benefit from having all code within one method.

**Comment by alrz** [comment]
@dsaf Can you give an example of awkward use of brackets for scoping?

**Comment by dsaf** [comment]
@alrz yes, it's the first code snippet in the opening post.

**Comment by HaloFour** [comment]
@dsaf I don't think that syntax is at all awkward.  An inexperienced developer is likely going to be making all sorts of mistakes with grammar, removing all such syntactic structures from the language wouldn't leave much left.

**Comment by alrz** [comment]
By the way, indentions actual helps you to know  what's going on.
```
var text = "Hello";
unvar text;
Console.WriteLine(text); 
```
not only doesn't essentially lessen the awkwardness, but also because of the fact that `unvar` can be applied in the same scope, you have to literally scan the code up-down to know what's actually accessible and what's not.

**Comment by dsaf** [comment]
Fair enough, I guess using plain blocks for scoping is more mainstream than I thought.
