### ISSUE TITLE
Adding a parameter quick-fix

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#805]
When an argument is added to a call site the IDE offers a quick-fix to generate a method (if the overload doesn't exist). It would be nice if it also offered a quick-fix to add the parameter to existing method(s).

**Comment by dpoeschl** [comment]
This feature would share a lot of work with another potential feature of including an Add Parameter option to ChangeSignature. 

@srivatsn If your team decides to tackle this, I'd be very interested in collaborating & reusing code to enable both scenarios.

**Comment by Youssef1313** [comment]
Already fixed.

**Comment by CyrusNajmabadi** [comment]
Closing out.  Thanks!
