### ISSUE TITLE
[Test Failure] MSBuild Error (+1 more) in prtest/lin/dbg/unit32 on PR #8038

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#8052]
PR: [#8038](https://github.com/dotnet/roslyn/pull/8038) *Ensure that we only reduce extension methods from the same language.* by @CyrusNajmabadi
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/2946/

**Issue 1: MSBuild Error**
error MSB6006: "csc" exited with code 134. [/mnt/j/workspace/roslyn_prtest_lin_dbg_unit32/src/Compilers/CSharp/Portable/CSharpCodeAnalysis.csproj]

**Issue 2: Compile Error**

**Comment by CyrusNajmabadi** [comment]
Note: my commit did not touch the compiler.

**Comment by jaredpar** [comment]
Haven't seen this fail since moving to CoreCLR.
