### ISSUE TITLE
"unrecognized option publicsign+" in jenkins build

### ISSUE THREAD

**Issue by TyOverby** [dotnet/roslyn#8062]
http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/2956/

@agocke didn't you fix this recently?

**Comment by agocke** [comment]
I thought so. No idea on how this failed.

**Comment by davkean** [comment]
More node reuse? Anyway, we're hitting this more times than I'd like, I've seen 3 times in the past day.

**Comment by davkean** [comment]
Dup of https://github.com/dotnet/roslyn/issues/7998
