### ISSUE TITLE
Analyzer errors from vsix packages are not respected in builds.

### ISSUE THREAD

**Issue by weltkante** [dotnet/roslyn#8068]
I'm on VS 2015 Update 1 and doing following steps:
- Create a new project based on the analyzer with codefix template
- Remove the test project, build the analyzer and vsix project
- Run the vsix for debugging in the experimental instance
- Create a new WinForms project

I do get warnings in the error list but when I compile I see nothing in the debug output. (Note that I'd expect 4 warnings but only get 3, but thats a different issue, opened #8067 for it).
- Close the experimental instance
- Change the analyzer to report as an error instead of an warning and rebuild
- Run another session for vsix debugging in the experimental instance.

Again, I get the errors in the error list but on compile I do not get any errors, contrary to what happens when I reference the analyzer manually.

Not respecting errors during builds is a big problem because it effectively downgrades errors to warnings and makes it impossible for vsix analyzers to ensure code quality.

**Comment by maslisko** [comment]
Not sure how relevant my comment is, but I'll try: code analyzer as a VSIX is not capable of breaking build by design. To do so, you need to use your analyzer as a NuGet. 
[https://github.com/dotnet/roslyn/issues/5493#issuecomment-144371786](url)

**Comment by weltkante** [comment]
I'm aware of that, but its a broken design, as I said in my last paragraph it effectively downgrades errors to warnings, making vsix analyzers nearly useless.

I can understand that this doesn't fit into the current design of msbuild being decoupled from VS and VSIX and possibly there was not enough time to design and implement this feature properly, but there is definitely the need to improve the current design and provide a proper solution to the problem, so thats what this issue is about. Maybe mark it as feature request or something.

**Comment by sharwell** [comment]
The current behavior is expected. Command line builds do not have access to Visual Studio extensions, and cannot include or evaluate analyzers from those locations. VSIX-installed analyzers also lack portability, where all members of a project and CI systems have a consistent view of the analysis rules in effect. As such, only project-system installed analyzers (e.g. from NuGet packages) are considered during builds.
