### ISSUE TITLE
Debugger* attributes not applied to async methods

### ISSUE THREAD

**Issue by anhall1** [dotnet/roslyn#807]
DebuggerNonUserCode and DebuggerStepThrough attributes are not correctly applied to async methods

**Comment by theoy** [comment]
Yeah, you probably want those copied down from the original async method.

**Comment by theoy** [comment]
Wonder what the native compiler does. Need to investigate.

**Comment by AlekseyTs** [comment]
@anhall1, could you elaborate please? What behavior do you expect?

**Comment by AlekseyTs** [comment]
It looks like this is not a behavior change in Roslyn. None of the attributes applied to an async or an iterator method are propagated to the corresponding MoveNext method.

**Comment by tmat** [comment]
Correct, we preserve the suboptimal behavior of Dev12.

**Comment by AlekseyTs** [comment]
@VSadov Please verify

**Comment by amcasey** [comment]
Adding label to make this appear in the to-verify query.

**Comment by gafter** [comment]
I see we do have a non-skipped test that demonstrates that this is fixed. Verified.

**Comment by thomaslevesque** [comment]
Actually I think the fix is incomplete. The `DebuggerStepThrough` attribute can be applied to a method, but also to a class (in which case it applies to all methods in the class). But async methods in a class with the attribute don't inherit the attribute in their state-machine type.
