### ISSUE TITLE
No blancs between parameters

### ISSUE THREAD

**Issue by GeertVL** [dotnet/roslyn#8073]
I generate code as in the following example:

```csharp
var constructorDeclaration1 = SyntaxFactory.ConstructorDeclaration(ClassName);
var parameter1 = SyntaxFactory.Parameter(default(SyntaxList<AttributeListSyntax>),
                default(SyntaxTokenList),
                SyntaxFactory.ParseTypeName("string"),
                SyntaxFactory.Identifier("message"),
                null);
var constructorDeclaration2 = constructorDeclaration1.AddParameterListParameters(parameter1);
var statement1 = SyntaxFactory.ParseStatement("System.Console.WriteLine(message);");
var constructorDeclaration3 = constructorDeclaration2.AddBodyStatements(statement1);

Console.WriteLine(constructorDeclaration3.ToFullString());
```

I get the following result:

```
TestClass1(stringmessage){System.Console.WriteLine(message);}
```

Maybe it is as expected but it is annoying that there are no blancs in the parameter declaration. Is it a bug or by design for some reason?

**Comment by gafter** [comment]
We don't insert trivia for you.

@mattwar What is the right way to use the APIs so that trivia is inserted making the code nicely formatted?

**Comment by axel-habermaier** [comment]
@GeertVL: Try calling ``NormalizeWhitespace()`` in ``Microsoft.CodeAnalysis.SyntaxNodeExtensions`` on the syntax node.

**Comment by mattwar** [comment]
Yes, node.NormalizeWhitespace() will give you a very specific whitespace formatting.  You can also use the Formatter API, with all its formatting options. If the constructed nodes are being used to perform a code fix or refactoring using those plug-in API's the formatter will be automatically applied to any changed regions of documents you modify, so you don't have to do anything.
