### ISSUE TITLE
Support switch case with one line break

### ISSUE THREAD

**Issue by Thaina** [dotnet/roslyn#8076]
switch case break syntax is staying so long. Still I want to have it more compact

Many times we just have a case with one line and break. The most compact code is

```
switch(a)
{
    case 0: DoSomething(); break;
    case 1: return DoSomethingAndStop();
}
```

Which make it 2 semicolon in one line

I just think why we don't do like return that could return void. So break will just be
```
switch(a)
{
    case 0: break DoSomething();
    case 1: return DoSomethingAndStop();
}
```

Also I would like case to auto break with { } block
```
switch(a)
{
    case 0: break DoSomething();
    case 1: return DoSomethingAndStop();
    case 2 { /// curly braces instead of colon for auto break
        DoSomething(0);
        DoSomething(1);
        DoSomething(2);
    } /// break without syntax error
    default: return;
}
```

**Comment by gafter** [comment]
So you really want to save a single character in your program? That does not sound worth making a language change for.

**Comment by HaloFour** [comment]
@gafter From the last code sample it seems that he would want the `switch` statement to not require a `break` statement if the colon was omitted and instead was followed by a block:

```cs
switch (a) {
    case 123 {
        string s = "foo";
        Console.WriteLine(s);
    }
    case 456 {
        string s = "bar";
        Console.WriteLine(s);
    }
}
```

equivalent to:

```cs
switch (a) {
    case 123:
        {
            string s = "foo";
            Console.WriteLine(s);
        }
        break;
    case 456:
        {
            string s = "bar";
            Console.WriteLine(s);
        }
        break;
}
```

**Comment by Thaina** [comment]
@gafter For me it not a problem of drop siggle character

It is a problem to have 2 semicolon in one line
And also I want the code tobe the same pattern between break and return

**Comment by NightElfik** [comment]
I am very much in favor of curly-braces auto-break. I (nearly) always include curlies for all case statement anyways to separate scopes so auto-break would be a nice cleanup of the syntax.

**Comment by alrz** [comment]
I think `catch when` syntax would play well for no break switches.
```cs
switch(obj) {
  case (pattern) { ... }
  case (pattern) when ( ... ) { ... }
  default { ... }
}
```
it'd be better to require all cases be consistent, all semicolon break, or all parens and curly braces.
