### ISSUE TITLE
[Test Failure] error VSSDK1031: Extension 'ConvertToAutoPropertyRefactoring.Microsoft.a95ab02d-0f23-4c9a-a8d2-b29692654076' could not be found. Please make sure the extension has been installed. 

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#8077]
PR: [#8070](https://github.com/dotnet/roslyn/pull/8070) *changed meaning of closed file diagnostic option. now it is solely fo…* by @heejaechang
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/2991/

**Issue 1: VSSDK Build error**
error VSSDK1031: Extension 'ConvertToAutoPropertyRefactoring.Microsoft.a95ab02d-0f23-4c9a-a8d2-b29692654076' could not be found. Please make sure the extension has been installed. [d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\Samples\CSharp\ConvertToAutoProperty\ConvertToAutoPropertyCS.csproj]

**Comment by davkean** [comment]
@jmarolf does this have anything to do with you moving the samples? 

tag @TyOverby Please investigate.

**Comment by jmarolf** [comment]
@davkean we shouldn't be deploying vsixes on cibuilds

**Comment by TyOverby** [comment]
@jmarolf @davkean What is ConvertToAutoPropertyRefactoring and what does it mean when it can't be found?

**Comment by davkean** [comment]
It looks like we're incorrectly deploying VSIXes, see: https://github.com/dotnet/roslyn/pull/7500 for more information. In particular, Jason's comment.

**Comment by TyOverby** [comment]
@jaredpar We are seeing DeployExtensions=True in the build queue. You made a change to DeployExtensions here: in https://github.com/dotnet/roslyn/blame/70b8933a9ed3c0c84a58561fa630fb2fe8be449c/build/Targets/VSL.Settings.targets#L94.  Is this still a valid check?

**Comment by jaredpar** [comment]
Have we upgraded to the update 1 image?  If so the csi check is invalid now.

**Comment by TyOverby** [comment]
CC @agocke

**Comment by agocke** [comment]
@jaredpar We have not yet upgraded the build machiens to update 1

**Comment by jaredpar** [comment]
@agocke hmm.  Not sure why this check is failing then.  Either way we should update this check because it's about to be wrong.  @jasonmalinowski may have some ideas on a better check.

**Comment by davkean** [comment]
@jasonmalinowski Mentioned that we handled both with Update 1 and without Update 1.

**Comment by TyOverby** [comment]
@jaredpar @jasonmalinowski What is the actual case that we want to handle with that condition?

**Comment by jaredpar** [comment]
@TyOverby the key problem is that by default VSIX projects deploy by default during a build.  This changes machine state and hence shouldn't be a part of a Jenkins build.

**Comment by TyOverby** [comment]
This was happening on a machine that had extensions deployed to it.  The hive has been cleared so we should be good to go.

**Comment by davkean** [comment]
:+1: Thanks - for figure it out.

**Comment by jaredpar** [comment]
@TyOverby do we have any idea how the extensions got there?  If not perhaps we should add a check at the end of our build scripts to error if an extension is deployed to the hive.  That would catch this problem in the future.

**Comment by jmarolf** [comment]
Happening on bit machines now http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/3034/

**Comment by diryboy** [comment]
+1 http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/3038/

**Comment by TyOverby** [comment]
I've seen this happen on the following machines:

tbld25
tbld20

I'll update this list as I find more occurrences.

**Comment by davkean** [comment]
We should figure out why we're deploying this - DeployExtensions is supposed to be false, so something is causing them to be deployed.

**Comment by davkean** [comment]
Also dci-win-bld-3

**Comment by TyOverby** [comment]
This should be fixed in #8110 by explicitly turning deploy-extensions to false.

**Comment by Pilchie** [comment]
Looks like we just hit this again in #8176:  http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/3124/

**Comment by davkean** [comment]
I don't trust that build or the changes it attempted to build with - it says that it the PR had already been merged: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/3124/consoleFull#-5668148229d2d7e4c-c23a-4646-ab1a-afaa25e9af32.

**Comment by davkean** [comment]
Okay, I looked at this, this is a little confusioning, but it looks like GitHub/pull request builder got confused when you have two PRs out with the same commit. That build you pointed to actually ran against https://github.com/dotnet/roslyn/pull/8177, _after_ it had merged in. Because there's was conflicts, it didn't merge and attempted to ran against whatever Jason's head was, which did not include Ty's changes to stop deployment. ie This is a false positive, and closing the issue again.

**Comment by jaredpar** [comment]
@heejaechang closing as @agocke just merged a change that should fix this last night.  It looks like your PR ran just before he got this in.  If you see it on any new PRs though please reopen.

**Comment by heejaechang** [comment]
happened again.
http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/3567/

**Comment by davkean** [comment]
I'm looking into this. dup of https://github.com/dotnet/roslyn/issues/8498
