### ISSUE TITLE
Jenkins xunit plugin failures seems to have problems with newlines.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#8090]
See 
http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/3011/testReport/junit/Microsoft.CodeAnalysis.CSharp.UnitTests/LexicalErrorTests/CS1015ERR_TypeExpected/   or
http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/2994/testReport/junit/Microsoft.CodeAnalysis.CSharp.UnitTests/LocalFunctionTests/BadModifiers/

The display of the errors seems to be thrown by newlines in the output.  So jenkins actually displays things like "\n" or "\r\n" instead of properly wrapping things.  Super annoying for grokking the issue.

![image](https://cloud.githubusercontent.com/assets/4564579/12498434/5a1fcb0c-c057-11e5-8321-ba96adbb2ff7.png)

**Comment by sharwell** [comment]
No longer relevant since we switched to ADO, though there are some related issues I plan to file in that context.
