### ISSUE TITLE
FormattableString and IFormattable should win over string in overload resolution

### ISSUE THREAD

**Issue by AceHack** [dotnet/roslyn#8097]
It's a terrible design to have string win over FormattableString and IFormattable, this makes using FormattableString for logging libraries impossible.  Please fix this issue.

**Comment by gafter** [comment]
We cannot "fix" this issue - it would be a breaking change. There is also no reasonable way to fix it, as the conversion from an interpolated string literal to `string` is an identity conversion.

**Comment by AceHack** [comment]
This is a big hole in the design then, it makes this feature must less useful.  That combined with the fact that the default is Current Culture makes this very only useful in very niche situation. :(

**Comment by gafter** [comment]
Yes, it was *intended* to be very useful only in a very niche situation. It is *supposed* to act like a string for most purposes.
