### ISSUE TITLE
[Test Failure] MSBuild Error (+1 more) in prtest/lin/dbg/unit32 on PR #8083

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#8098]
PR: [#8083](https://github.com/dotnet/roslyn/pull/8083) *[WIP] readonly locals and parameters* by @CyrusNajmabadi
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/3032/

**Issue 1: MSBuild Error**
error MSB6006: "csc" exited with code 134. [/mnt/j/workspace/roslyn_prtest_lin_dbg_unit32/src/Test/PdbUtilities/PdbUtilities.csproj]

**Issue 2: Compile Error**

**Comment by jaredpar** [comment]
Closing as we haven't seen this since we moved to CoreCLR hosts of the compiler.
