### ISSUE TITLE
Missing Generic Type Parameter shows quick fix for redundant namespace

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#81]
Source:

``` C#
using System.Collections.Generic;
class X : IEnumerable
```

The word `IEnumerable` will correctly show quick fixes for `using System.Collections` and `System.Collections.`.

It will also show a quickfix for `System.Collections.Generic.`, even though that is redundant and doesn't fix the error.  (it does not show the corresponding `using` quick fix)

**Comment by SLaks** [comment]
![image](https://cloud.githubusercontent.com/assets/313894/5908941/c96eee42-a579-11e4-91e6-44d35a837be3.png)


Also (not visible in the screenshot), the quick fix menu items are truncated, masking the difference between the two fixes.
That's very poor UX.

**Comment by srivatsn** [comment]
It offers you the suggestion to fully qualify to either the non-generic or generic IEnumerable (with the non-generic one showing up first). The user might have been intending to write IEnumerable<T> here and invoked the fix to fully qualify it - so it's not an unreasonable option. In general that particular quickfix tries to find all generic\non-generic names that can possibly bind to that identifier and offers them as suggestions.

**Comment by SLaks** [comment]
@srivatsn No; _I already have a `using` statement for that namespace_.  
See the first line of code.

I like the fact that it will offer to add a `using` statement for a namespace that contains a type with the same name but a different arity.
But if I already have that `using` statement, there is no reason to add a qualifier to the type.

**Comment by dpoeschl** [comment]
Maybe fully qualify shouldn't be offered if the resulting QualifiedName still doesn't bind (which is the case here). Reopening to ensure this is reconsidered.

**Comment by SLaks** [comment]
@dpoeschl That's still not what I mean; I _like_ the fact that you offer these quick fixes before I add generic parameters.

My point is that you should never offer to qualify a name with a namespace that _already has a `using` in scope_.
To put it differently, since you aren't offering AddUsing, you shouldn't offer QualifyName either.

**Comment by amcasey** [comment]
@slaks Maybe it’s a different code fix or something, but mightn’t you want to qualify because multiple usings exist for the type?

**Comment by amcasey** [comment]
@slaks Maybe it’s a different code fix or something, but mightn’t you want to qualify because multiple usings exist for the type?

**Comment by SLaks** [comment]
You're right, but that isn't the case here.

**Comment by srivatsn** [comment]
I see. Yes we could check to see if the using is already present and in that case not offer the fully quialify fix.

**Comment by SLaks** [comment]
It's not that simple; if there are two conflicting `using`s, you do need the quick fix.
You need to check whether there are any other types with that name & arity in scope.

**Comment by Meir017** [comment]
what should the quick-fix suggest in this case?
maybe adding `<>` after the `IEnumerable` and move the cursor between the braces?

before:
```cs
class X : IEnumerable
```

after:
```cs
class X : IEnumerable<T>
```

**Comment by Youssef1313** [comment]
@CyrusNajmabadi I cannot reproduce this. I think this can be closed.

![image](https://user-images.githubusercontent.com/31348972/161434310-09240dd2-7f41-4052-8b3d-6417d34b8bb2.png)

**Comment by CyrusNajmabadi** [comment]
Cool.  THanks!
