### ISSUE TITLE
Make ICodeGenerationService public 

### ISSUE THREAD

**Issue by yinon1992** [dotnet/roslyn#810]
This interface was public in the Roslyn 2012 CTP and it's very useful for a variety of uses. Please make this publicly available once more.

**Comment by Pilchie** [comment]
We are instead, trying to migrate things to use the APIs in the Microsoft.CodeAnalysis.Editing namespace, like `SyntaxGenerator`.  Can you let us know what is lacking from that API set?

Tagging @mattwar

**Comment by canton7** [comment]
I'm trying to access [`ExpressionGenerator.GenerateExpression`](http://sourceroslyn.io/#Microsoft.CodeAnalysis.CSharp.Workspaces/CodeGeneration/ExpressionGenerator.cs,21), and it looks like one of the places that this is surfaced is [`ICodeGenerationService.AddParameters`](http://sourceroslyn.io/#Microsoft.CodeAnalysis.Workspaces/CodeGeneration/AbstractCodeGenerationService.cs,81). I can't find an equivalent method in `Microsoft.CodeAnalysis.Editing` (there's `SyntaxGenerator.ParameterDeclaration`, but it doesn't take account of default values).

For me, it would be useful to have access to `ExpressionGenerator.GenerateExpression`, by some means.

**Comment by sharwell** [comment]
What about `SyntaxGenerator.TypedConstantExpression`?

https://github.com/dotnet/roslyn/blob/31c2a014d1e126672396d42225eb73b6b6a9e1d0/src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs#L3617-L3620

**Comment by canton7** [comment]
Apparently I'm blind, thank you!

**Comment by CyrusNajmabadi** [comment]
There's also SyntaxGenerator.LiteralExpression (mentioned in gitter).  I don't think TypedConstantExpression will work because it's not possible to make an instance of a TypedConstant publicly.

**Comment by CyrusNajmabadi** [comment]
Closing out.  SyntaxGenerator is the way to do things.  If there are deficiencies there, we should open new issues to track those.
