### ISSUE TITLE
CodeModel navigation from XAML fails on expression-bodied methods

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#8103]
Hi, not really sure this is a Roslyn issue, but if you ask the XAML designer to go to definition for an event handler that is implemented using expression body, it says it cannot navigate to definition.

E.g. start a WPF project, add `<Button Click="OnClick"  />` and `private void OnClick(object sender, RoutedEventArgs e) => Close();` and hit F12 in the XAML on OnClick.

**Comment by dpoeschl** [comment]
Yep, this fails for me locally too. @DustinCampbell Is this a codemodel issue?

**Comment by DustinCampbell** [comment]
Maybe. I thought XAML using the `VisualStudioWorkspace.TryGoToDefintion(...)` API though.

**Comment by dpoeschl** [comment]
@DustinCampbell Hrm, @Pilchie thought so too, but debugging through shows it going through CodeModel. Did something change / regress here, or did the switch to `VisualStudioWorkspace.TryGoToDefintion(...)` never actually happen? /cc: @mgoertz-msft

Anyway, in CodeModel, they're requesting the `vsCMPart.vsCMPartBody` and [we throw if `node.Body == null`](http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices.CSharp/CodeModel/CSharpCodeModelService.NodeLocator.cs,389), which it does for expression-bodied methods.

**Comment by DustinCampbell** [comment]
Ah, looks like a Code Model bug then. Should be an easy fix.

**Comment by CyrusNajmabadi** [comment]
@mgoertz-msft is this still an issue?  If not, can it be clsoed out?

**Comment by mgoertz-msft** [comment]
@CyrusNajmabadi I just tried this with a WPF project in 17.9 and it worked for me.

**Comment by mgoertz-msft** [comment]
@CyrusNajmabadi I don't have permissions to close this issue.

**Comment by CyrusNajmabadi** [comment]
Closing out.
