### ISSUE TITLE
Proposal: Small extension to Null-conditional operators for delegates

### ISSUE THREAD

**Issue by spasutto** [dotnet/roslyn#8108]
Why can't we write this?

    Action myaction = null;
    myaction?(); // produce nothing

this is easier than

    Action myaction = null;
    if (myaction != null)
        myaction();

sorry if this has already been asked

**Comment by Pilchie** [comment]
Unfortunately, there is a grammar ambiguity that would make that very hard to support.  However, you *can* already just use the `Delegate.Invoke()` method, so your example could be written as 
```C#
Action myaction = null;
myaction?.Invoke();
```

**Comment by Pilchie** [comment]
Also, as of VS 2015 Update 1, it will offer to re-write event invocations using this pattern.
