### ISSUE TITLE
LanguageExtensions.Kind(SyntaxNode) throws NullRefrenceException

### ISSUE THREAD

**Issue by pdelvo** [dotnet/roslyn#811]
Both LanguageExtensions.Kind(SyntaxNode) throw a NullReferenceException if the parameter is null. I think checking for null and throwing an ArgumentNullException would be preferable.

https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/CSharpExtensions.cs#L160
and
https://github.com/dotnet/roslyn/blob/master/src/Compilers/VisualBasic/Portable/VisualBasicExtensions.vb#L194

I would create a PR if this change is accepted.

**Comment by pharring** [comment]
Given how often this is called, adding null checks here is likely to negatively impact perf.

**Comment by tmat** [comment]
Agree with @pharring. There is not much value in throwing ArugmentNullException, on contrary - these are extension methods, so usually they will be called as node.Kind(). NullReferenceException is expected from such a call-site if node is null.

**Comment by pdelvo** [comment]
This is inconsistant with how IsKind() works. IsKind does not throw a NullRefrrenceException nd contains a null check. I dont think it is good design if have to know the implementation of a method to know how it is going to behave. https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/CSharpExtensions.cs#L29

**Comment by tmat** [comment]
That's a different question though - whether or not Kind() and IsKind() should throw an exception (vs. what exception to throw).

**Comment by pharring** [comment]
Entered #849 to track the potential change to IsKind
