### ISSUE TITLE
The open->closed pump should tell us when it cannot connect

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#8113]
When the pump goes down, we don't find out until someone notices or when a signed build doesn't kick off.

We just have it tell us, via an email probably, when it cannot pump.

**Comment by davkean** [comment]
FYI @jmarolf :)

**Comment by jasonmalinowski** [comment]
@agocke I guess you fix this too at the same time?

**Comment by agocke** [comment]
Also an obsolete bug
