### ISSUE TITLE
The C# identifier rename operation is not accepting "@" as a permissible character in an identifier

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#8118]
Ported from internal bug #175773

**Comment by dpoeschl** [comment]
Note that you can just type a keyword into Inline Rename without the "@" and we auto-add it for you, even during the rename session. The question here is about the *user* typing the @ themselves.

**Comment by AdamSpeight2008** [comment]
Isn't `@` only valid as the first character in a identifier?

**Comment by dpoeschl** [comment]
Yes, but if the user doesn't know that Inline Rename will add it for them, they might be hesitant to change the identifier to "int" for fear of messing things up.

**Comment by CyrusNajmabadi** [comment]
Need information to justify investment in fixing this issue.
