### ISSUE TITLE
VB Line Commit only fixes up some name casing changes

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#8120]
Ported from internal bug 175449

Paste VB, change the declaration of `list` to `List`, and move the caret off that line:

``` VB
Class C
    Sub M()
        Dim list As New List(Of String)
        list.Add("Apple")
        list.Add("Banana")
    End Sub
End Class
```

**Expected**: I'm not sure what's expected here. @jasonmalinowski - any thoughts? Fix both? Fix neither?
**Actual**: the `list` reference on the `Apple` line gets capitalized, but the one on the `Banana` line does not.

**Comment by dpoeschl** [comment]
The other thing the customer was encountering here was https://github.com/dotnet/roslyn/issues/2123, where clicking the lightbulb or Ctrl+<dot> would consume the lightbulb and basically not let you use Rename Tracking here.

**Comment by Pilchie** [comment]
I would expect neither would get changed, as neither would be part of the "dirty" span in the line commit code, but both should be fixed if you format document.

**Comment by dpoeschl** [comment]
Visual Studio 2013 agrees with @Pilchie on both counts.

**Comment by jasonmalinowski** [comment]
Well, @Pilchie is correct in that the implementation should cause neither to be changed. That behavior is arguably terrible. :smile:
