### ISSUE TITLE
Add ITypeSymbol.IsNullable and ITypeSymbol.Implements

### ISSUE THREAD

**Issue by Vannevelj** [dotnet/roslyn#8123]
There are some internal helpers that would be very useful for us too since now we just end up duplicating those same helpers. 
I'd rather re-use existing ones that I know will have a solid implementation.

It seems like there is a whole bunch of them under Shared/Extensions.

Created an issue per request by @jmarolf

**Comment by davkean** [comment]
These sorts of issues are easier to make traction on if you call out specific examples of things that you've duplicated or used, and what you use them for.

**Comment by Vannevelj** [comment]
The specific example that triggered this was [`ITypeSymbol.IsNullable`](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Shared/Extensions/ITypeSymbolExtensions.cs,9da3d89af760c92a) and used [here](https://github.com/Vannevelj/VSDiagnostics/blob/issue289/VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/TryCastWithoutUsingAsNotNull/TryCastWithoutUsingAsNotNullCodeFix.cs#L116) to determine whether I have to turn it in a nullable type (to go from a cast to an `as` statement). [My implementation](https://github.com/Vannevelj/VSDiagnostics/blob/develop/VSDiagnostics/VSDiagnostics/VSDiagnostics/Utilities/Extensions.cs#L109) was much more brittle.

Another example that comes to mind is [`ITypeSymbol.Implements`](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Shared/Extensions/ITypeSymbolExtensions.cs,360) which I have written [myself](https://github.com/Vannevelj/VSDiagnostics/blob/develop/VSDiagnostics/VSDiagnostics/VSDiagnostics/Utilities/Extensions.cs#L35) in a less secure way as well (mixing reflection and Roslyn).

If I had known about these implementations (by seeing them in intellisense) when I was still starting out with Roslyn I wouldn't have re-implemented them poorly myself. Then again, it's true that there are a *lot* of helpers available -- many of which I'll probably never need.

**Comment by gafter** [comment]
We will treat this as a feature request for those two specific APIs: `ITypeSymbol.IsNullable` and `ITypeSymbol.Implements`.

**Comment by CyrusNajmabadi** [comment]
This would need to go through an API proposal.  in general, the reason we don't just make things public is because it increases maintenance costs and locks down our ability to change things in teh future.  We can open things up, but we have a process that requests need to go through to make sure the appropriate people weigh in and the right API shape is determined and shipped.
