### ISSUE TITLE
Proposal: Enable implementing interface interface properties with interface implementer.

### ISSUE THREAD

**Issue by baterja** [dotnet/roslyn#8125]
### Problem
I have nice third-party (Prism) interface like:
```C#
public interface IInteractionRequestAware {
    INotification Notification { get; set; }

    Action FinishInteraction { get; set; }
}
```
and I want to implement it with my custom INotification implementing class. I have to do it like this:
```C#
public abstract class BasePopupWindowViewModel<T> : IInteractionRequestAware
    where T : INotification  {
    protected T Confirmation;

    public Action FinishInteraction { get; set; }
    
    public INotification Notification {
        get { return Confirmation; }
        set { Confirmation = (T)value; }
    }
}
```
Now it is bug-friendly when I want to bind something from Confirmation
```xaml
<TextBox Text="{Binding Notification.SomePropertyExistingInMyCustomConfirmation}" />
```
because xaml cannot resolve property in desing-time, because only INotification properties are visible.

Another way to solve my problem is:
```C#
public abstract class BasePopupWindowViewModel<T> : IInteractionRequestAware 
    where T : INotification {
    private T _customConfirmation;

    public T CustomConfirmation {
        get { return _customConfirmation; }
        set { _customConfirmation = value; }
    }
    
    public Action FinishInteraction { get; set; }
    
    public INotification Notification {
        get { return _customConfirmation; }
        set { _customConfirmation = (T)value; }
    }
}
```
and now I can proper bind T properties:
```xaml
<TextBox Text="{Binding CustomConfirmation.SomePropertyExistingInMyCustomConfirmation}" />
```
but I have done it in a way far away from clean.

Some other people having problems with this (years ago):
http://stackoverflow.com/questions/9845620/implementing-interface-properties-in-interfaces
http://stackoverflow.com/questions/14028850/c-sharp-interface-property-implementation
(maybe there are some new problems with this, but it is hard to google "implementing interface interface properties with interface implementer")
### Solution
Enabling implementing interface like:
```C#
public abstract class BasePopupWindowViewModel : IInteractionRequestAware {
        public Action FinishInteraction { get; set; }

        public INotificationImplementer IInteractionRequestAware.Notification { get; set; }
}
```
or explicitely with generic constraint like:
```C#
public abstract class BasePopupWindowViewModel<T> : IInteractionRequestAware 
        where T : INotification {
        public Action FinishInteraction { get; set; }

        public T IInteractionRequestAware.Notification { get; set; }
}
```
would be useful (and seems non-breaking for everything else).

I know my problem wouldn't exist if interface IInteractionRequestAware was generic like:
```C#
public interface IInteractionRequestAware<T> where T : INotification {
        T Notification { get; set; }

        Action FinishInteraction { get; set; }
    }
```
but my problem isn't the only way to benefit from proposed change (good example is in the first link to stackoverflow posted before).

(I hope my proposal isn't a duplicate, because really searching "interface interface" in issues was not easy)

**Comment by svick** [comment]
I believe the technical term for what you want is "return type covariance" and has already been suggested: #357.

**Comment by baterja** [comment]
Thanks, I've [read it](https://github.com/dotnet/roslyn/issues/357#issuecomment-172994781) and it really is something covering my issue.

**Comment by gafter** [comment]
OK, closing as a dup of #357.
