### ISSUE TITLE
Proposal: Adding a scoped index parameter to foreach

### ISSUE THREAD

**Issue by jamesqo** [dotnet/roslyn#8130]
I realize that there are already several other issues (#1651, #1752, and #5194) covering this, but they didn't address exactly what I had in mind so I'm making a new one here.

## Background

A common pattern when working with `IEnumerable<T>` is to capture the index during each iteration of the loop. For example, LINQ has many overloads that take a `Func<T, int>` as well as a `Func<T>`, such as Select and Where. Languages like Python solve this problem with a method called `enumerate`, which returns the index and value of the current item in the collection:

```python
for index, item in enumerate(items):
    # do something with index and item
```

## Problem

At the moment, there's no way to capture the index in a `foreach` loop without 1) introducing a local variable in the outer scope and 2) incrementing it manually after each iteration. For example:

```csharp
int index = 0;
foreach (var item in GetItems())
{
    Console.WriteLine($"Index: {index}. Item: {item}.");
    index++;
}

// index is still visible here after the loop has completed
```

Aside from the boilerplate, this can be problematic in functions that have multiple `foreach` loops in the same scope: a new index variable with a new name has to be initialized for each loop.

```csharp
int i = 0;
foreach (var item in items) { /* Use i */ i++; }

int index = 0;
foreach (var item in items2) { /* Use index */ index++; }

/* Running out of variable names... we have to keep coming
up with new ones like idx or ind, which creates ambiguity */
```

### For-loops

A traditional for-loop works and scopes correctly, but

- can only be used for collections that support indexers, and
- requires a significant amount of boilerplate

I'm sure you've all seen plenty of examples of for-loops already, so I'll leave it to you to weigh their pros and cons.

### foreach + Select / other LINQ-based variations

This also works well and scopes properly:

```csharp
foreach (var tuple in items.Select((item, index) => Tuple.Create(item, index)))
{
    var item = tuple.Item1;
    var index = tuple.Item2;
    // use item and index
}
```

But let's be honest, this is not as readable as it could be. It's not immediately clear what `Item1` and `Item2` mean, and the `Select` expression makes the code look like an overstretched diving board (see the similarity?). [Language support for tuples](https://github.com/dotnet/roslyn/issues/347) may improve the problem somewhat, but it'd still have to look like [this.](https://github.com/dotnet/roslyn/issues/8130#issuecomment-174313609)

---

## Proposal: Add a scoped index parameter to foreach

With the new syntax, the code example above now looks like this:

```csharp
foreach (var item, index in GetItems())
{
    Console.WriteLine($"Index: {index}. Item: {item}.");
}
```

The compiler-generated code is equivalent to

```csharp
{ // Extra braces to add scope
    int outer = 0;
    var e = GetItems().GetEnumerator();

    while (e.MoveNext())
    {
        int index = outer; // Handle closures
        var item = e.Current;

        Console.WriteLine($"Index: {index}. Item: {item}.");
        outer++;
    }
}
```

## Benefits

- **Less boilerplate.** The need to initialize and increment an `index` variable after every loop has been eliminated.
- **No indexers required.** This means that types like `IEnumerable`, `ICollection`, or `IReadOnlyCollection` can be used with the new syntax.
- **Scoping.** The scope of `index` is limited to inside the loop, which circumvents the problem above with multiple loops in the same scope.
- **Immutability.** `index` is readonly, preventing accidental assignments and making the code easier to read.

## Type Inference

- By default, the type of `index` is inferred to be `int`.

- `index` may also be prefixed with `var` or `int`, e.g.

```csharp
foreach (var item, var index in items)
```

for those who prefer to spell their types out explicitly.

- Since we support collections with counts greater than `int.MaxValue` (via `LongCount`), the type of `index` may also be explicitly specified as `long`:

```csharp
foreach (var item, long index in largeCollectionOfItems)
```

This ensures that we keep performant code for the vast majority of cases, but support using larger numbers when they are needed.

**Comment by orthoxerox** [comment]
I like this idea, we just need to make sure this won't conflict with the destructuring assignment syntax.

**Comment by SolalPirelli** [comment]
If tuples are added as first-class citizens to the language, this could be replaced by an extension method on `IEnumerable<T>`, without the need for special syntax.

**Comment by jamesqo** [comment]
@orthoxerox Probably not, the existing consensus in so far in #6400 seems to lean towards using `let`.

**Comment by jamesqo** [comment]
@SolalPirelli Good point. I assume you mean something like this:

```csharp
static void ForEach(this IEnumerable<T> source, Action<T, int> action)
{
    int count = 0;
    foreach (var item in source) action(item, count++);
}
```

I agree that would be less work than implementing a new language feature. It would be kinda strange to newcomers though, since you would have some people writing `foreach` and others writing `ForEach`. It's better to provide just one syntax for consistency.

**Comment by alrz** [comment]
What's wrong with `GetItems().Select((item,i) => { ... })`?

**Comment by SolalPirelli** [comment]
@jamesqo No, I meant an `IEnumerable<T * int> Indexed(this IEnumerable<T> source)` method, which would then be iterated using `foreach(var (item, index) in stuff.Indexed()) { ... }`.

**Comment by jamesqo** [comment]
@alrz Because `Select` has to return something (the return type can't be void), so your code would end up looking like this:

```csharp
items.Select((item, i) =>
{
    // work
    return 0;
});
```

**Comment by jamesqo** [comment]
@SolalPirelli Hmm, seems interesting. Would it be possible to omit the parentheses in the tuple declaration?

**Comment by alrz** [comment]
@jamesqo @SolalPirelli That was proposed in #6067 but it seemingly dismissed. Then you have to do this:
```cs
foreach(var tuple in list.Indexed()) {
  let (var item, var index) = tuple;
  // ...
}
```

**Comment by Blecki** [comment]
> /* Running out of variable names... we have to keep coming
> up with new ones like idx or ind, which creates ambiguity */

You could try more meaningful variable names than 'index'. In your example, 'indexItems1' and 'indexItems2' would be a better name. Further, if you're not using the value of 'indexItems1' after the loop you could just use index over and over. Or you could do this.

    foreach (var indexedValue in SomeList.Select((e, i) => Tuple.Create(e,i)))
         ....

**Comment by jamesqo** [comment]
@Blecki See my updated post. That would definitely work, I just don't think it's readable as it could be.

**Comment by gafter** [comment]
As the OP points out, this is morally similar to existing issues (#1651, #1752, and #5194), but I'll leave this open for a bit for discussion.

**Comment by paul1956** [comment]
If you are going to do this there needs to be a "Finally" so I can access the index.

**Comment by Blecki** [comment]
@jamesqo, I can't argue with the readability. I avoid tuples because the names 'item1' and 'item2' are meaningless.

**Comment by techman2553** [comment]
How about a mashup of both for and foreach:

    foreachindex(var item in collection, int i = 0, i++)
    {
        Console.WriteLine("item={0}  index={1}", item, i);
    }

This gives you the freedom to change the behavior of the index if you wanted to for some reason:

    foreachindex(var record in records, long pos = 0, pos += 20)
    {
        Console.WriteLine("record={0}  byte position={1}", record , pos);
    }

**Comment by GeirGrusom** [comment]
```csharp

public struct IndexedElement<T>
{
	public T Value { get; }
	public int Index { get; }
	public IndexedElement(T value, int index)
	{
		Value = value;
		Index = index;
	}
	public static IndexedElement<T> Map(T value, int index)
	{
		return new IndexedElement<T>(value, index);
	}
}

void Main()
{
	var items = new List<string> { "Foo", "Bar" };

	foreach (var item in items.Select(IndexedElement<string>.Map))
	{
		Console.WriteLine(item.Index);
	}
}
```

**Comment by jamesqo** [comment]
@techman2553 I'm not convinced, the whole point of this proposal was to eliminate the boilerplate and the need for a state variable. Your suggestion seems to just move it to a different place (inside the foreach loop).

@GeirGrusom Your solution is good, but there's still a need to write out `Select(IndexedElement<T>.Map)` every time you want the index, which aside from being repetitive can create overhead (since LINQ uses iteration). Also, it'd be preferable to capture the index/value in 2 variables, rather than wrapping them in one.

**Comment by jamesqo** [comment]
The general consensus so far seems to be "we don't need this." If we choose not to go ahead with this proposal, I think we should reconsider the [earlier suggestion](https://github.com/dotnet/roslyn/issues/8130#issuecomment-174313609) about using the new destructuring syntax in loops. That would allow us to do something like this:

```csharp
foreach (let (thing, i) in things.Index())
{
    // do something with thing and i
}
```

Although it's definitely a bit more verbose than my proposal above, it would support the scenario with no new syntax additions to the language (at least, after tuples/destructuring assignments are added in C# 7).

**Comment by RichiCoder1** [comment]
Correct me if I'm wrong, but wouldn't it be:
```csharp
foreach ((var item, var index) in things.Index())
{
    // do something with item and index
}
```

**Comment by alrz** [comment]
@RichiCoder1 You can't use patterns in `foreach`.

**Comment by fowl2** [comment]
For reference, 'de-structuring foreach' did end up being allowed, eg. this is ok:
```
foreach (var (index, item) in things.Indexed())
{
    // do something with item and index
}
```

Neither linq or morelinq have the "`Indexed()`" method though. An straightforward but inefficient implementation would be:

```
public static IEnumerable<(TItem item, int index)> Indexed<TItem>(this IEnumerable<TItem> items)
    => items.Select((item, index) => (item, index));
```
