### ISSUE TITLE
Toggle Compiler Features per Project

### ISSUE THREAD

**Issue by ilexp** [dotnet/roslyn#8131]
As C# runs upwards through all the new and exciting versions and more and more language features get added, project owners may want to specify which of them can be used. As a per-project compiler setting, this would not affect libraries or dependencies.

**Examples for opt-out C# compiler features:**
- Record types
- Pattern matching
- Expression-bodied members
- Nullability tracking
- `dynamic` keyword (the C# 4.0 one)
- `var` keyword (the C# 3.0 one)
- ...and so on. Essentially, a full, uncheck-all-the-boxes opt-out would constrain the compiler to accept only a very limited subset of C#.

The opt-out mechanism could be done in a modular way. Rather than specifying a "simulated" C# compiler version, each language feature could be disabled individually - so I might want to keep nullability tracking, but not pattern matching or record types. Or I might allow `var`, but prohibit `dynamic`.

Reasons to disable certain language features may include coding style policies, or enforcing a smaller surface area of required language proficiency to maintain the project. I'm excited about the progress the C# language is making recently, but as it gains more and more features, as a project owner and maintainer, I also want to be able to pick exactly which feature I need and which of them are not allowed.

This is not about whether or not certain features are "good" or "bad", but about being able to decide what's desirable for a given project, and what isn't. The language's newly added features increase both development value and required proficiency - for all kinds of use cases. However, since I may be only interested in _some specific_ use cases, I may not want the proficiency / complexity overhead of getting all of them.

If this is already possible or has been discussed, feel free to point me in the right direction.

**Comment by HaloFour** [comment]
Sounds like something that could be solved through an analyzer.

**Comment by alrz** [comment]
@gafter Can experimental/optional features be enabled by assembly attributes rather than compiler flags?

**Comment by gafter** [comment]
@alrz I'm not sure I understand your question. The compiler command line is what is used to produce an assembly. Of course for every new feature, we need to make sure we say how it is seen from the point of view of previous language features (i.e. if an assembly generated in the presence of the new language feature is used in an older compiler), but I have not seen any language feature proposed where the answer isn't easy to see.

**Comment by alrz** [comment]
@gafter I'm not talking about backward compatibility, I think assembly attributes would be a more desirable way of turning experimental features on/off (related to issues that I've mentioned above). There is a similar feature in Rust: the `feature` attribute, which is used to turn on unstable features.

**Comment by gafter** [comment]
@alrz I am against having attributes affect the static semantics of the language. We do that as a last resort.

**Comment by HaloFour** [comment]
@gafter I think the one feature where it may make sense to have more granular support is non-nullable reference types.  It could be quite cumbersome to migrate an existing project over to supporting it in one go and it would be nice to be able to migrate individual classes or source files at a time.  I don't know of any other language that narrows the nature of the language, though.

**Comment by ilexp** [comment]
@HaloFour I'm not sure it is a good idea to allow disabling / enabling language features at a smaller scope than project / Assembly-level. Things would just get really confusing.

**Comment by HaloFour** [comment]
@ilexp For the most part I agree with you.  But I think that one language feature is an exception given that it changes the existing semantics of the language on a massive scale.  I fear that people will simply not adopt the feature because it will be too scary/cumbersome to do so in one fell swoop.

**Comment by gafter** [comment]
@HaloFour If you're referring to "nullable reference types", we will use attributes to affect *which warnings the compiler will emit*. It doesn't change the static semantics of the code. This is not turning the feature on or off, but rather controlling which diagnostics it reports.

**Comment by HaloFour** [comment]
@gafter

For everyone who has `/warnaserror+` enabled it might as well be changing the semantics of the language.  That setting has been used to justify never adding new warnings to the language before.

In any case, someone who enables it on a project and seeing a massive barrage of new warnings (or errors) may be quickly tempted to turn it right back off and leave it off.

**Comment by alrz** [comment]
@HaloFour isn't the point that it actually report warnings because you've done something wrong?

**Comment by gafter** [comment]
@HaloFour You won't get warnings (or warnings-as-errors) unless you *add* an attribute turning them on. So `/warnaserror+` would not be a problem.

**Comment by HaloFour** [comment]
@alrz It wasn't wrong before as far as the compiler was concerned.  I'm not arguing against the usefulness of the feature or the correctness of the diagnostic.

**Comment by alrz** [comment]
@HaloFour Then you shouldn't get any warnings.

**Comment by HaloFour** [comment]
@gafter Exactly, my only argument is that perhaps said attribute should be more granular than assembly-wide so that people can approach migrating in incremental chunks rather than an all-or-nothing proposition.  Think about how you'd react if you were to turn on said feature and get hit with a wall of warnings.  Think about how those big companies react today when Microsoft fixes a bug or makes a slight change to something internal and undocumented which adversely affects their horrific and nasty code bases.

**Comment by MgSam** [comment]
I think this is awful idea. You don't want different pieces of code that are ostensibly the same language but act differently depending what compiler features are turned on or off. Sounds like a recipe for fragmenting a language beyond recognition; not to mention it would greatly increase the cost of implementing and supporting the features for the compiler team.

This should be handled separately from compilation, the same as any other style convention enforcement is.

**Comment by paulomorgado** [comment]
@HaloFour,

I think your first assessment was the correct one:

> Sounds like something that could be solved through an analyzer.

**Comment by gafter** [comment]
@HaloFour We are actively looking at having the attribute that enables the "nullable reference types" feature more granular. In fact, we're experimenting with that right now. But I don't think I would take from that any general principle for how language features should be controlled.

**Comment by HaloFour** [comment]
@gafter I was poking at the implementation notes and I do see that, an attribute that can be targeted to individual types or methods, etc.  That's exactly what I was looking for.

Otherwise I completely agree, I don't think it makes sense to control most language features like that.  I'm not even sure that it would be that valuable to control language features independently from their version.

**Comment by srivatsn** [comment]
Closing the issue since the consensus seems to be that one could write an analyzer for this.
