### ISSUE TITLE
When doing a rename operation in dark theme, it is very hard to see the cursor position in the symbol

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#8136]
Ported from internal work item 121121

For example:

![image](https://cloud.githubusercontent.com/assets/235241/12537866/5dfeaca0-c27f-11e5-8b7b-2612691bc729.png)

**Comment by dpoeschl** [comment]
From the editor team:

The Roslyn IDE team can detect when the caret is in a rename span and flip the caret color to a more contrasting one.

**Comment by dpoeschl** [comment]
Checking to see if this needs to stay in 15.3

**Comment by CyrusNajmabadi** [comment]
Closing out as this UI was redone.
