### ISSUE TITLE
Diff View: Navigating using NavBar in diff view opens new file

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#8137]
Ported from internal bug 116789
1. Create new C# console app
2. add to source control
3. make changes and compare to version in source control
4. use navbar in right view to select a method

**Expected**: View scrolls to selected method
**Actual**: File in right view is opened in a new window

**Comment by dpoeschl** [comment]
I think this bug was introduced with the change that allowed preview tabs to get promoted to regular tabs. When the document is navigated to, we now always ask to reopen it, which causes this behavior. Any fix will have to somehow introduce more context into that process to get both scenarios working correctly.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
