### ISSUE TITLE
Go to Definition not showing all defs of partial type

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#8138]
Ported from internal bug 127814 (description edited)

When I hit F12 on the definition of BoundExpression, it only shows me three of the four definitions.  The missing one is in a generated file (BoundNodes.xml.Generated.cs). Still, it seems unfortunate that it's not even included when I GTD within the generated file. My only option seems to be to find a generated member in the member list and go to that.  Maybe we need some sort of special case that shows ALL the definition, e.g. when you F12 on one of the definitions (vs a ref).

**Comment by jcouv** [comment]
F12 on BoundExpression declaration currently returns 3 results, including the one in BoundNodes.xml.Generated.cs, which I think is correct.
Good to close?

**Comment by jcouv** [comment]
The issue no longer seems to repro. I'll go ahead and close.
