### ISSUE TITLE
Preview Dialog: highlighting in change lists missing

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#8140]
Ported from internal bug 125906
1. invoke Rename on some method name
2. click Preview Changes

**Expected**: Dev12

![image](https://cloud.githubusercontent.com/assets/235241/12538355/94b7f2f8-c28c-11e5-9f2d-192c06dca708.png)

Dev12 also has nice highlighting in the code pane, could we do that?

![image](https://cloud.githubusercontent.com/assets/235241/12538357/9d5cae8a-c28c-11e5-926a-de9b0ed4a155.png)

**Actual**:

![image](https://cloud.githubusercontent.com/assets/235241/12538359/a321e204-c28c-11e5-986c-1c56f467084d.png)

**Comment by dpoeschl** [comment]
Triage, does this still seem appropriate for 1.2?

**Comment by CyrusNajmabadi** [comment]
Closing out as we've heard nothing on this from customers.
