### ISSUE TITLE
Change signature on collection initializer add methods

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#8141]
Ported from internal bug 97241

Steps to reproduce:
1. Try to reorder parameters at the $$:

``` C#
using System;
using System.Collections;

class Program : IEnumerable
{
    static void Main(string[] args)
    {
        new Program { { 1, 2 }, { ""three"", ""four"" }, { 5, 6 } };
    }

    public void Add(int x, int y)$$ { }

    public void Add(string x, string y) { }

    public IEnumerator GetEnumerator() { throw new NotImplementedException(); }
}
```

**Comment by dpoeschl** [comment]
The failure to update these methods is not a regression, but Visual Studio 2013 had a dialog that stated "This member may have compiler generated references with the same name. Refactoring the member will not update these references, which may introduce semantic changes and/or build errors into your code. Do you want to continue?"

**Comment by CyrusNajmabadi** [comment]
Closing out as too costly to justify the complexity given lack of customer feedback.
