### ISSUE TITLE
Warn users when manipulating members with special names / signatures that may be implicitly referenced

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#8142]
Split from #8141 (internal bug 97241)

Visual Studio 2013 had a dialog that stated "This member may have compiler generated references with the same name. Refactoring the member will not update these references, which may introduce semantic changes and/or build errors into your code. Do you want to continue?"

This impacts at least Rename and Change Signature

**Comment by Pilchie** [comment]
We think the right thing here is to eventually generate conflicts, and we don't think it's worth tracking this dialog as a stop-gap.
