### ISSUE TITLE
The language item of the Code Snippets Manager was changed

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#8143]
Ported from internal bug 105318

**Expected**:
![image](https://cloud.githubusercontent.com/assets/235241/12538426/2a130c38-c28e-11e5-918d-9001a9222a08.png)

**Actual**:
![image](https://cloud.githubusercontent.com/assets/235241/12538427/2f9e2eb2-c28e-11e5-8024-1fbb94387720.png)

**Comment by dpoeschl** [comment]
If we switch to providing all of the snippet authoring in Roslyn, we could fix the name as part of that work.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback on this.
