### ISSUE TITLE
Nested types from other partial parts are not present in the nav bar

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#8145]
Ported from internal bug 97926
1. Add two VB files to VS. Define Partial Class C with a part in each file. Add a nested type Class D to one of the parts. Go to the other file and put the caret inside C. "D" is not listed in the middle nav bar.

File1.vb

``` VB
Partial Class C
    Class D
    End Class
End Class
```

File2.vb

``` VB
Partial Class C
    $$
End Class
```

**Comment by dpoeschl** [comment]
The current behavior matches that of Visual Studio 2013 and prior, but we'd still like to include these nested types in the nav bar.

**Comment by CyrusNajmabadi** [comment]
Closing out given lack of any customer requests for this.
