### ISSUE TITLE
VB: Rename should add Overloads modifier if necessary

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#8146]
Ported from internal bug 98001

Inline-renaming "NewMethod" to "Foo" in the following code results in a compilation error: `function 'Foo' must be declared 'Overloads' because another 'Foo' is declared 'Overloads' or 'Overrides'.`

``` VB
MustInherit Class Bar
    MustOverride Function Foo()
End Class

Class Foo
    Inherits Bar

    Overrides Function Foo()
        Dim x = 1
        Dim y = 2
        Return NewMethod(x, y)
    End Function

    Private Shared Function NewMethod(x As Integer, y As Integer) As Integer
        Return x + y
    End Function
End Class
```

**Comment by dpoeschl** [comment]
We can't safely add the "Overloads" keyword to NewMethod because that could itself introduce an error if there is another NewMethod method, so I'm not sure this will easily fit into the existing expand/reduce paradigm.

**Comment by CyrusNajmabadi** [comment]
Closing as we are not likely to invest in this area.
