### ISSUE TITLE
NavBar & Change Signature shouldn't show a numeric literal for special values of optional parameters

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#8147]
Ported from internal bug 100950
1. Paste this code:

``` C#
 interface I
 {
     void Foo(decimal x = decimal.MaxValue);
 }
```
1. Position the caret on the method

**Expected**: In the right NavBar combo, there should be `Foo(decimal x = decimal.MaxValue)`

**Actual**: `Foo(decimal x = 79228162514264337593543950335)`

**Comment by dpoeschl** [comment]
Note from @DustinCampbell - I took a look here and appears that the code to show the user's code will need to be factored out of the symbol description service. Or, the symbol description code will need to become a more general service, taking arbitrary symbol formats. At the moment, NavBar can't simply use it without inheriting a bunch of display quirks from Quick Info and Signature Help.

**Comment by dpoeschl** [comment]
This also affects the Change Signature dialog "Default" column

**Comment by CyrusNajmabadi** [comment]
Closing out as too costly to justify the complexity needed to solve this, along with the lack of any customer feedbakc on this issue.
