### ISSUE TITLE
Audit uses of Workspace.TryApplyChanges that do not observe the return value

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#8149]
Ported from internal bug 127469

Many places call Workspace.TryApplyChanges but do not observe its return value. Some have //todo comments and some just ignore it (perhaps incorrectly).

**Comment by dpoeschl** [comment]
(the above 2 changes was @jmarolf making changes using my phone 😬)

**Comment by jmarolf** [comment]
👍 👍 👍

**Comment by sharwell** [comment]
Good data flow analyzer candidate

**Comment by CyrusNajmabadi** [comment]
Closing as speculative.
