### ISSUE TITLE
Nullable and comparison

### ISSUE THREAD

**Issue by MatthieuMEZIL** [dotnet/roslyn#8155]
`(int?)null >= 0` -> false
`(int?)null <= 0` -> false
`(int?)null == (int?)null` -> true
Fine. But why `(int?)null >= (int?)null` -> false? 
I would expect true as == is true.
Is it a bug or a feature? 
If it's a feature, I would be curious to know the reason.

**Comment by alrz** [comment]
The definition of the nullable monad is that if either side of the operation was null the result is null, no matter what operation it is.

**Comment by gafter** [comment]
@MadsTorgersen do you want to take a stab at answering this?

**Comment by jveselka** [comment]
Eric Lippert may have answered some of your questions here: http://ericlippert.com/2015/08/31/nullable-comparisons-are-weird/

**Comment by MatthieuMEZIL** [comment]
@jveselka Thanks for the link.
