### ISSUE TITLE
Fix FAR wait indicator text

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#8157]
It says something like "Finding references to 'x'", The "to" should probably be an "of".

**Comment by dpen2000** [comment]
References "to" is fine. See second definition of reference here: http://www.oxforddictionaries.com/definition/english/reference with example: "each chapter should have references to books covering the subject in greater depth"

**Comment by CyrusNajmabadi** [comment]
Closing out.  This was intentionally phrased.
