### ISSUE TITLE
Show recently visited document results at top of 'Navigate To'

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#8158]
If I am working in a large codebase like Roslyn.sln and I type a common keyword (e.g., "Navigate"), the first results that populate the results list get swept away as more and more results get loaded.

It would be great if the top of my results list had the items I visited recently (via 'Navigate To' or 'Find All References' or 'Go To Def'). Most of the time, this is what I'm looking for anyways... Also, this will make my parsing experience better because the item I'm reading the in result list won't vanish.

**Comment by Pilchie** [comment]
@kuhlenh Totally agree, but I think this is a core editor request, not something we can solve in Roslyn.  Tagging @markw-t and @olegtk
