### ISSUE TITLE
Somehow indicate if a result is in a C# or VB file

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#8159]
For example, if I'm in 'Navigate To' I can't tell if my search results are in a C# or VB file...

**Comment by Pilchie** [comment]
Tagging @markw-t and @olegtk.

@kuhlenh any ideas on what this might look like?  It's already distinguished for filename matches, but maybe we could put a small glyph to the right of the project name with the project's glyph?

**Comment by Pilchie** [comment]
Still, This would require support from the editor APIs.  Please file against the editor team.
