### ISSUE TITLE
Update supported version in the Nuget packages 

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn#8160]
Currently they say .NET Framework 4.5 is supported for all packages whereas that's only true for the compiler packages. Workspaces depend on 4.5.2

https://www.nuget.org/packages/Microsoft.CodeAnalysis/

**Comment by shyamnamboodiripad** [comment]
cc @jinujoseph - Another one that is probably fixed at this point but need to verify.
(This may also be related to #12444)

**Comment by jasonmalinowski** [comment]
These were updated long ago.
