### ISSUE TITLE
Razor code formats braces incorrectly

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#8162]
![image](https://cloud.githubusercontent.com/assets/1402694/12564251/15f7d460-c363-11e5-9ad2-55f3dcdc7c38.png)

**Comment by Pilchie** [comment]
I know I told you to file this on Roslyn, but `style` sections are not actually handled by us - only the ones that end up with C# code in them.  Can you file against ASP.NET instead?
