### ISSUE TITLE
Roslyn Compilers VSIX does not deploy props file to hive

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#8168]
/cc: @agocke @jasonmalinowski @jmarolf 

I cleaned all my hives, built Roslyn, and the designtime builds in RoslynDev fail with the following (causing all files to open in Misc Files):

```
C:\USERS\DAVIP\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\14.0ROSLYNDEV\EXTENSIONS\MICROSOFT\ROSLYN COMPILERS\42.42.42.42\Microsoft.CSharp.Core.targets(67,5): error MSB4062: The "Microsoft.CodeAnalysis.BuildTasks.Csc" task could not be loaded from the assembly C:\Users\davip\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\4ffmfu5w.dxu\Microsoft.Build.Tasks.CodeAnalysis.dll. Could not load file or assembly 'file:///C:\Users\davip\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\4ffmfu5w.dxu\Microsoft.Build.Tasks.CodeAnalysis.dll' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
```

Note: The ROSLYN COMPILERS\42.42.42.42 directory doesn't have a props file.

**Comment by jasonmalinowski** [comment]
Just writing here what @dpoeschl and I discussed privately: the VSIX doesn't ship a copy of the .props file, since the file needs to be different for VSIX installations. The file is generated and written in the [CompilerPackage itself](https://github.com/dotnet/roslyn/blob/80771ee4779980e13e01ced6ee78a418beb29724/src/Compilers/Extension/CompilerPackage.cs#L64).

**Comment by jaredpar** [comment]
Shouldn't this issue be fixed by the work @jasonmalinowski did?  I can F5 Roslyn now and run the compiler directly out of the new hive.

**Comment by jasonmalinowski** [comment]
Ugh, I don't remember what this bug is tracking. I remember having the conversation with @dpoeschl but not what the resolution was. Let's just close it until somebody speaks up.
