### ISSUE TITLE
diagnostic engine not working when vsix and nuget analyzers are installed at the same time

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#8169]
I spent some time but couldn't pin point the root cause yet. I might need help from @mavasani for it. basically, when vsix based analyzers and nuget based analyzers are installed on same VS, some analyzers looks like completely not being called.

I will work with @mavasani once he cames back.

**Comment by heejaechang** [comment]
so far what I think I know is that, IDE side, it discovered the analyzer fine, but the driver seems not generating right events for it and completely skip it (not even call initialize method)

**Comment by mavasani** [comment]
@heejaechang I am unable to repro this - I wrote an analyzer from the template project and installed it both as VSIX and NuGet package, and it seems to work fine.

Can you attach a repro analyzer + project where you saw this behavior?

**Comment by heejaechang** [comment]
moved to 1.3

**Comment by heejaechang** [comment]
not repro. closing it.
