### ISSUE TITLE
ObjectInitializerCodeFixProvider crashes and therefore BatchFixAllProvider crashes too

### ISSUE THREAD

**Issue by jakubsuchybio** [dotnet/roslyn#8180]
Hi.
When I wanted to resolve aprox. 60 Warnings via BatchFixAllProvider of CC0008, I encountered crash.
So I started to make it manually and I found one, that is crashing ObjectInitializerCodeFixProvider and I think that was a reason for BatchFixAllProvider crashes.
Here is the snippet:
```
var quitButton = new GButton( 0x7D9, 0x7DB, 0x7DA, 18, 445, new OnClick( FinalGumps.Quit_OnClick ) );
quitButton.Tooltip = new Tooltip( ClientLocalization.GetString( "#57#Ukončit Ultimu Online" ) );
```
Hope it helps to solve these crashes, regards.

Edit: And I am sorry I had opened more Github Projects and I created this issue in the wrong one and I can't delete it. 

However it still crashes BatchFixAllProvider, which is from here, so maybe some sort of fail checking of crashes and ignoring in BatchFixAllProver would be welcome.

**Comment by jmarolf** [comment]
[ObjectInitializerCodeFixProvider](https://github.com/code-cracker/code-cracker/blob/master/src/CSharp/CodeCracker/Style/ObjectInitializerCodeFixProvider.cs#L24) is a code fix offered by [code cracker](https://github.com/code-cracker) Looks like this has already been [filed over there](https://github.com/code-cracker/code-cracker/issues/676).  Closing this issue as this looks to be an exception originating from the codefix itself, not the BatchFixAllProvider .
