### ISSUE TITLE
Build task shouldn't eat exceptions without logging in InitializeHostCompiler

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#8186]
Both the Csc and Vbc build tasks have a method called `InitializeHostCompiler` that does what it sounds like. This method eats all exceptions without logging them. As a part of the investigation that led up to #8177, the build task was throwing an exception, swallowing it, and then failing the design time build with no further explanation why. The catch block in InitializeHostCompiler should log that exception rather than eating it.

**Comment by TyOverby** [comment]
The catch block in InitializeHostCompiler thinks that it can get away without logging if the command-line compiler will log the errors.  Should I remove that check and log anyway?

**Comment by jasonmalinowski** [comment]
Which code are you referring to?

**Comment by TyOverby** [comment]
[This code](https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/MSBuildTask/Shared/Vbc.cs#L968-L974)  There's a similar pattern in csc.cs

**Comment by jasonmalinowski** [comment]
In my scenario I didn't even see that error, so I guess that path is fine?

**Comment by TyOverby** [comment]
I mean, that's the only catch block inside of InitializeHostCompiler, so I don't know what else I would do?
