### ISSUE TITLE
Publish Nuget package for Microsoft.CodeAnalysis.EditorFeatures

### ISSUE THREAD

**Issue by paulvanbrenk** [dotnet/roslyn#8188]
TypeScript has a dependency on the Microsoft.CodeAnalysis.EditorFeatures,and having this published on NuGet would significantly simplify our development process.

(As in we would no longer have to publish ourselves in a TypeScrip dev package).

Discussed with @Pilchie, @DustinCampbell, and @CyrusNajmabadi

**Comment by Pilchie** [comment]
@davkean had some interesting points about this that we should discuss further.

**Comment by jaredpar** [comment]
This will begin publishing on myget starting later today.  Do we want to keep this open to track NuGet.org as well (as the bug states)?

**Comment by Pilchie** [comment]
No, right now I don't think there is any reason to publish to NuGet until we know that any added public APIs will actually be in this package.

**Comment by jaredpar** [comment]
:hammer: :watch:

**Comment by aelij** [comment]
Hey @jaredpar, could you please point me to the MyGet feed where this package is published? I'm currently using the nightly feed and apparently older versions of packages don't stay there for long... :) Thanks!

**Comment by jaredpar** [comment]
@aelij the nightly feed is where we are publishing this at the moment.  Packages do rotate out of there every 10 days or so.  There isn't a feed where this is stored long term at the moment.

**Comment by aelij** [comment]
Ah, too bad. I guess I'll have to make do. Hacking this package is essential for [RoslynPad](https://github.com/aelij/RoslynPad) ;)
