### ISSUE TITLE
C# Completion List not listing types from VB runtime assembly

### ISSUE THREAD

**Issue by basoundr** [dotnet/roslyn#8189]
```C#
using Microsoft.VisualBasic.CompilerServices;

namespace ConsoleApplication2
{
    class Program
    {
        static void Main(string[] args)
        {
            var s = typeof(Standard$$)
        }
    }
}

```

I am expecting to see the public Type StandardModuleAttribute to be listed in the completion list but it is not listed. But I see the type binding if I happen to type the whole name(StandardModuleAttribute ).

**Comment by Pilchie** [comment]
Does it have `EditorBrowsableAttribute` on it?

**Comment by Pilchie** [comment]
Indeed it does.  https://github.com/dotnet/corefx/blob/c02d33b18398199f6acc17d375dab154e9a1df66/src/Microsoft.VisualBasic/src/Microsoft/VisualBasic/CompilerServices/StandardModuleAttribute.vb#L6
