### ISSUE TITLE
VS debugger crash when try to open this dump

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#8197]
dump is in [mflang file server]\hechang\ee\minidump.mdmp

there are so many exception happening so not 100% sure what is actual exception that caused VS to go down, but it repro every time with the dump.

**Comment by KevinH-MS** [comment]
I can repro crash if I "Debug with Managed Only", then open the Locals window and attempt to expand the "$exception" item.

**Comment by KevinH-MS** [comment]
I have file 216563 in VSO for the core debugger team.

**Comment by ManishJayaswal** [comment]
Not a Roslyn EE issues so closing this out.

**Comment by KevinH-MS** [comment]
FYI, this has been fixed in current Dev14 Update 3 drops (vsucorediag).
