### ISSUE TITLE
VS2013 link points into the eternal void

### ISSUE THREAD

**Issue by mihailik** [dotnet/roslyn#82]
> You can also try April's End User Preview, which installs on top of Visual Studio 2013. (Note: The VS 2013 preview is quite out of date, and is no longer being updated.)

Did you mean 1st April End User Preview?

The link doesn't work.

**Comment by davkean** [comment]
@mihailik We no longer ship on top of Visual Studio 2013, so closing this out. Feel free to reopen, or file a new issue if you are still running into issues.
