### ISSUE TITLE
Add using quick fix incorrectly offered for extension methods with CS1501

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#8202]
``` C#
namespace ConsoleApplication1
{
    struct S
    {
        public static S Multiply(S a, S b) { return a; }
        public static S Multiply(S a, float b) { return a; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            S s;
            s.Multiply(4.0); // nobody takes double
        }
    }

    static class Extensions
    {
        public static S Multiply(this S a, int b) { return a; }
    }
}

```

This generates `CS1501 No overload for method 'Multiply' takes 1 argument`. The quick fix offered is to add `using ConsoleApplication1;` which not only does not solve the problem, but it does not make any semantic difference to the code if I am correct.

Note that if there is only one of the overloads in S, you get CS7036 instead and the fix is not offered.

**Comment by Pilchie** [comment]
Good catch - we should check applicability of the extension methods before offering them.

**Comment by zaytsev-victor** [comment]
Can't reproduce the issue.
![8202](https://user-images.githubusercontent.com/23630781/28405211-0f7e715c-6d35-11e7-8a12-1c9b9d6ae35e.png)

**Comment by Pilchie** [comment]
Same using VS 15.3.
