### ISSUE TITLE
You can invoke Change Signature on very broken signatures

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#8205]
1. Copy the broken field declaration `private string Lazy<string> _fullPackagePath;` into a new class.
2. Invoke Change Signature.

_Actual:_ I can actually do that. You get a dialog like this:

![image](https://cloud.githubusercontent.com/assets/201340/12625289/01c519d6-c4e8-11e5-9cee-9535d56fe17c.png)

_Expected:_ I can't invoke the feature when parameters don't even have names.

**Comment by Pilchie** [comment]
We should probably not offer Change Signature if the method declaraion (not body) contains syntax errors.

**Comment by dpoeschl** [comment]
We also let you rename "Lazy"

**Comment by dpoeschl** [comment]
> We should probably not offer Change Signature if the method declaraion (not body) contains **syntax** errors.

(emphasis added) Great! I was coming up with all sorts of cases with declaration errors where I wouldn't want to get in the way, but I think restricting the scope to syntax errors will work well.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback on this.
