### ISSUE TITLE
Comprehensively test the full set of changes to Add Using

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#8206]
Some testing was done for https://github.com/dotnet/roslyn/pull/7830, but we should do a full test pass, with a proper test plan, before release. Particularly the many ways of NuGet.

/cc: @CyrusNajmabadi @Pilchie @davkean @jasonmalinowski

**Comment by jmarolf** [comment]
### Test Cases:

**Add Metadata Reference**
- [x] Simple Case (Add reference from other assembly)
- [x] Have two different assemblies that will match
- [x] Have Different .NET frameworks being targeted in each project
- [x] Have metadata reference be nuget package
- [x] Have type be internals visible to referenced project
- [x] Have type added via props file
- [x] Have different version of assembly already referenced

**Add Project Reference**
- [x] Simple Case
- [x] Shared project
- [x] ASP.NET Project
- [x] VB , C# , F#, C++ managed as project reference
- [x] Portable to Non-Portable
- [x] Conflicting type definitions
- [x] Conflicting .Net framework targets

**Fuzzy Search**
- [x] Mis-spellings
- [x] Wildcard characters
- [x] First Letter of Each Word
- [x] Extremely common type names

### Bugs Filed:

1. Visual Studio crashes when trying to add reference #8514
2. Add Using will offer to add metadata references even when reference is invalid for target framework #8516
3. [Add Using] Only project suggested even if assembly matches #8563
4. [Add Using] Add project reference is not offered if project is renamed #8565
5. [Add Using] Assembly dependencies are not added #8568
6. [Add Using] Only suggests one reference if two match #8571
7. [Add Using] Does not offer to add reference to shared project #8572
8. [Add Using] CSharpAddImportCodeFixProvider crashes in ASP.NET Core 1.0 Project #8577

**Comment by Pilchie** [comment]
Let's keep this open until we look at the NuGet changes too.

**Comment by davkean** [comment]
By ASP.NET project, what do we mean here? Did we test xproj?

**Comment by jmarolf** [comment]
@davkean I've cleared up the comment.  I tested this on RC 1  ASP.NET Core 1.0

**Comment by davkean** [comment]
:+1:

**Comment by Pilchie** [comment]
We should probably test more project types than that - including:
1. UWP.
2. csproj based web application (either MVC/WebAPI/WebForms).
3. Web *site* projects.

Anyone other interesting project flavors that might customize add reference support?

**Comment by davkean** [comment]
Phone 8 (Silverlight) does just magic with references - in particular non-Phone Silverlight.
Silverlight itself also intercepts references.

**Comment by jmarolf** [comment]
Updated comment with new bugs and scenarios tested.  Waiting on VS installation repair to verify Phone 8.

**Comment by jmarolf** [comment]
Finished project verification. The answer to "what happens when we try to add a reference to something the project type doesn't support" is "It brings down the codefix with some exception"
