### ISSUE TITLE
Roslyn.Services.Editor.CSharp.UnitTests.dll - 307 tests fail with Russian language set as primary with localized resources present

### ISSUE THREAD

**Issue by brettfo** [dotnet/roslyn#821]
Ported from TFS WorkItem: **1101388**

------------------------------

**Repro Steps:**

**Steps to reproduce (likely to&nbsp;repro with other languages):**<BR>

1. Follow three steps described at [http://windows.microsoft.com/en-us/windows-8/using-multiple-languages](http://windows.microsoft.com/en-us/windows-8/using-multiple-languages)&nbsp;to install Russian language pack and make Russian the primary language.

&nbsp;

2. Queue Main-PerCheckin-Debug build with pseudo localization for Russian language (go to the Parameters tab in the Queue Build dialog and change Localization Languages value to RUS)

&nbsp;

3. Wait for the drop. Copy binaries to the machine prepared on step 1. Copy localize\RUS folder from the drop location next to the binaries and rename it to 'ru'. Verify that output of command line compilers is localized.

&nbsp;

4. Run tests. I simply copy bits over to Binaries\Debug folder on the previous step and run 'test' script.

&nbsp;

The test log is attached.

------------------------------

**Revisions:**

1) Created By Aleksey Tsingauz (1/2/2015 10:22:53 AM)

------------------------------

**Comment by brettfo** [comment]
Assigning to Aleksey to resolve once the other loc bugs are fixed (#818, #819, #820)

**Comment by AlekseyTs** [comment]
It looks like 82 tests are failing at the moment.

**Comment by AlekseyTs** [comment]
Four test are still failing for me.

**Comment by brettfo** [comment]
Let's try this again: updated in commit 7b98b34d777ea8c97b95891d597a9f1dd097a385

**Comment by AlekseyTs** [comment]
Verified.
