### ISSUE TITLE
Please consider BatchFixAllProvider more verbose

### ISSUE THREAD

**Issue by jakubsuchybio** [dotnet/roslyn#8211]
Hi.
When I run any changes from code-cracker or any other analyzer via BatchFixAllProvider for the whole solution.. 
First in the last step it is blocking operation on UI thread of VS so it gives me [Not Responding] and Second could there be some more verbosity? Like:
- Searching solution to apply change: {change description} A of N files searched, found B occurences
- Then there is a preview window and after hitting Apply
- Applying changes: C of D changes applied
It would be so awesome.
Thanks, regards.

**Comment by Pilchie** [comment]
I definitely agree.  Related to #6601

**Comment by Pilchie** [comment]
Let's track this with #6601
