### ISSUE TITLE
Roslyn.Compilers.CSharp.Symbol.UnitTests failed on mac due to timeout

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#8216]
Random failure while running tests for https://github.com/dotnet/roslyn/pull/8096.

Build link: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_mac_dbg_unit32/3099

**Comment by jaredpar** [comment]
Letting #6407 be the primary tracker here.
