### ISSUE TITLE
Add keyboard shortcut for "Go To Implementation"

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#8226]
Enable non-mouse users to be more productive by giving them a shortcut key for GoToImplementation.

In previous discussions, we considered using 'CTRL+F12' for this.

**Comment by diryboy** [comment]
+1

**Comment by DustinCampbell** [comment]
@davkean -- what's the status of this? I seem to remember you working on it the other week.

**Comment by Pilchie** [comment]
Fixed in `stabilization` by #9586.
