### ISSUE TITLE
Autocomplete forces new line

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#8228]
Forgot to file this separately (#2837)...

Update 1 RTM (24720), relevant settings:
C# > Formatting > Wrapping > Leave block on single line  on  (on by default)
C# > Automatic brace completion  off  (newly on by default)

The following code is expected to stay on the same line.
```C#
namespace ConsoleApplication1
{
    class Program
    {
        public static bool One { get|

        static void Main(string[] args)
        {
        }
    }
}
```
But instead it turns into:
```C#
        public static bool One {
            get;
```
The same with:
```C#
public static void Test() { return|
```

Note that if you cancel the autocomplete suggestions of `get`/`return` it does not happen.

**Comment by balajikris** [comment]
dupe of #7768 ?

**Comment by miloush** [comment]
Yep, apparently my search terms weren't good enough.
