### ISSUE TITLE
Missing method generation for delegate arguments when other overload exists

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#8230]
I believe I already filed or discussed this, but cannot find it...
```C#
using System;

namespace ConsoleApplication1
{
    class PropertyMetadata
    {
        public PropertyMetadata(object defaultValue) { }
        public PropertyMetadata(EventHandler changedHandler) { }
    }

    class Program
    {
        static void Main()
        {
            new PropertyMetadata(OnChanged);
        }
    }
}
```
Actual: Generate property, field, local-only field, local.
Expected: also method, like in VS2013:

![tmpc3d3 1](https://cloud.githubusercontent.com/assets/10546952/12655673/fdc3d6be-c5f1-11e5-9268-9f483c9e20ed.png)
Declaring dependency properties hits this issue.

**Comment by Pilchie** [comment]
The issue here is that we just pick the first overload in this case, but we should be merging the results.

**Comment by miloush** [comment]
The problem with merging I see is if there was one overload with double and one with int, what would you generate as a field?

**Comment by CyrusNajmabadi** [comment]
@miloush "Generate field" and "generate method" are two different features.  Do they can have differing behavior.  For "generate field" we can keep the behavior where we just pick one.  But for generate method, we shouldn't just look at one, say "oh, there's no possible method here" and bail out.  We should look through all the overloads to see if there's at least one viable choice that could allow us to produce a method.
