### ISSUE TITLE
Missing C# code snippets in completion list

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#8231]
Seeing this in latest vsuml build. Some of the common code snippets appear to be missing in the completion list. For example 'cw' (which is Console.WriteLine(); doesn't appear in the completion list, and you aren't able to complete the snippet by tapping twice. Snippets all appear to be present and working still.

![image](https://cloud.githubusercontent.com/assets/10537189/12656261/26a1dbc0-c5b2-11e5-8177-3e177e6805c9.png)

Additionally some of the snippets still work, but they don't show up as snippets in the completion list. Just keywords and are even missing the snippet tooltip. See below for an example. You can actually still tab twice and create the snippet successfully here.

![image](https://cloud.githubusercontent.com/assets/10537189/12656068/0949c69c-c5b1-11e5-889f-52e044b16a0b.png)

**Comment by Pilchie** [comment]
This was fixed in the VS editor code internally today. (cc @davkean @dpoeschl)

**Comment by dpoeschl** [comment]
> and you aren't able to complete the snippet by tapping twice

@mattscheffer Just an FYI in case you didn't know, if you hit esc to dismiss completion first, then tab should still expand the snippet. The presence of snippets in the completion list and the expandability of snippets via tab (assuming the completion list is not showing) are unrelated.
