### ISSUE TITLE
Unexpected value 'QualifiedName' of type 'Microsoft.CodeAnalysis.CSharp.SyntaxKind' is thrown by Binder.GetEventSymbol

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#8234]
This is a repro for Watson bucket tracked by DevDiv 179982.

```
        [Fact]
        public void EventAccessInTypeNameContext()
        {
            var source =
@"
class Program
{
    static void Main() {}

    event System.EventHandler E1;

    void Test(Program x)
    {
        System.Console.WriteLine();
        x.E1.E
        System.Console.WriteLine();
    }

    void Dummy()
    {
        E1 = null;
        var x = E1;
    }
}
";
            var comp = CreateCompilationWithMscorlib(source);
            var tree = comp.SyntaxTrees[0];
            var model = comp.GetSemanticModel(tree);

            var node1 = tree.GetRoot().DescendantNodes().Where(n => n.IsKind(SyntaxKind.IdentifierName) && ((IdentifierNameSyntax)n).Identifier.ValueText == "E").Single().Parent;
            Assert.Equal("x.E1.E", node1.ToString());
            Assert.Equal(SyntaxKind.QualifiedName, node1.Kind());
            var symbolInfo1 = model.GetSymbolInfo(node1);
            Assert.Null(symbolInfo1.Symbol);
        }
```

Result:
Test 'Microsoft.CodeAnalysis.CSharp.UnitTests.Semantics.BindingTests.EventAccessInTypeNameContext' failed: Microsoft.CodeAnalysis.ThrowingTraceListener+DebugAssertFailureException : Unexpected value 'QualifiedName' of type 'Microsoft.CodeAnalysis.CSharp.SyntaxKind'

	ThrowingTraceListener.cs(25,0): at Microsoft.CodeAnalysis.ThrowingTraceListener.Fail(String message, String detailMessage)
	at System.Diagnostics.TraceListener.Fail(String message)
	at System.Diagnostics.TraceInternal.Fail(String message)
	at System.Diagnostics.Debug.Assert(Boolean condition, String message)
	InternalUtilities\ExceptionUtilities.cs(13,0): at Roslyn.Utilities.ExceptionUtilities.UnexpectedValue(Object o)
	Binder\Binder_Statements.cs(1578,0): at Microsoft.CodeAnalysis.CSharp.Binder.GetEventSymbol(BoundExpression expr, BoundExpression& receiver, CSharpSyntaxNode& eventSyntax)
	Binder\Binder_Statements.cs(1718,0): at Microsoft.CodeAnalysis.CSharp.Binder.CheckEventValueKind(BoundEventAccess boundEvent, BindValueKind valueKind, DiagnosticBag diagnostics)
	Binder\Binder_Statements.cs(1682,0): at Microsoft.CodeAnalysis.CSharp.Binder.CheckValueKind(BoundExpression expr, BindValueKind valueKind, DiagnosticBag diagnostics)
	Binder\Binder_Statements.cs(1656,0): at Microsoft.CodeAnalysis.CSharp.Binder.CheckValue(BoundExpression expr, BindValueKind valueKind, DiagnosticBag diagnostics)
	Binder\Binder_Expressions.cs(4673,0): at Microsoft.CodeAnalysis.CSharp.Binder.BindMemberAccessWithBoundLeft(ExpressionSyntax node, BoundExpression boundLeft, SimpleNameSyntax right, SyntaxToken operatorToken, Boolean invoked, Boolean indexed, DiagnosticBag diagnostics)
	Binder\Binder_Expressions.cs(725,0): at Microsoft.CodeAnalysis.CSharp.Binder.BindQualifiedName(QualifiedNameSyntax node, DiagnosticBag diagnostics)
	Binder\Binder_Expressions.cs(542,0): at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
	Binder\Binder_Expressions.cs(353,0): at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
	Binder\Binder_Expressions.cs(348,0): at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, DiagnosticBag diagnostics)
	Compilation\SyntaxTreeSemanticModel.cs(205,0): at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken)
	Compilation\CSharpSemanticModel.cs(524,0): at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfo(ExpressionSyntax expression, CancellationToken cancellationToken)
	Compilation\CSharpSemanticModel.cs(4292,0): at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfoFromNode(SyntaxNode node, CancellationToken cancellationToken)
	Compilation\CSharpSemanticModel.cs(4436,0): at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfoCore(SyntaxNode node, CancellationToken cancellationToken)
	Compilation\SemanticModel.cs(95,0): at Microsoft.CodeAnalysis.SemanticModel.GetSymbolInfo(SyntaxNode node, CancellationToken cancellationToken)
	Semantics\BindingTests.cs(3203,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.Semantics.BindingTests.EventAccessInTypeNameContext()

**Comment by AlekseyTs** [comment]
@TyOverby Please verify.

**Comment by ezhupa99** [comment]
Still persists

**Comment by CyrusNajmabadi** [comment]
@ezhupa99 Please provide a repro so we can determine what is going on.  Thanks!

**Comment by ezhupa99** [comment]
I don't remember quiet well but I think

I had a interface

Interface IRepository

With multiple interfaces in it

And when I wanted to extract these inner Interfaces into new files, this issue happened
