### ISSUE TITLE
Roslyn dlls being loaded on clicking "New Project" on VS

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#8235]
Repro is simple, just click “New Project” from VS, and see VSWorkspace get initialized. (and see module list for Roslyn dlls).

this seems happening regardless whether it is related to managed language or not.

**Comment by heejaechang** [comment]
opened it based on experience on my dev box. could be red herring,

**Comment by rchande** [comment]
@heejaechang I don't see this on my dev box. Can you try to repro on recent InstallDogfood?

**Comment by heejaechang** [comment]
@rchande I just checked again, and it is happening on my /rootsuffix RoslynDev.

can you drop by?

here are callstack when it happens.

>	Microsoft.VisualStudio.LanguageServices.Implementation.dll!Microsoft.VisualStudio.LanguageServices.RoslynVisualStudioWorkspace.RoslynVisualStudioWorkspace(Microsoft.VisualStudio.Shell.SVsServiceProvider serviceProvider, Microsoft.VisualStudio.LanguageServices.Implementation.SaveEventsService saveEventsService, System.Collections.Generic.IEnumerable<System.Lazy<Microsoft.CodeAnalysis.Editor.Host.INavigableItemsPresenter>> navigableItemsPresenters, System.Collections.Generic.IEnumerable<System.Lazy<Microsoft.CodeAnalysis.Editor.Host.IReferencedSymbolsPresenter>> referencedSymbolsPresenters) Line 41	C#
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	Microsoft.VisualStudio.Composition.dll!Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue() Line 487	C#
 	Microsoft.VisualStudio.Composition.dll!Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create() Line 1171	C#
 	Microsoft.VisualStudio.Composition.dll!Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleState nextState) Line 1266	C#
 	Microsoft.VisualStudio.Composition.dll!Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleState requiredState) Line 1345	C#
 	Microsoft.VisualStudio.Composition.dll!Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose() Line 1072	C#
 	Microsoft.VisualStudio.Composition.dll!Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetExportedValueHelper.AnonymousMethod__0() Line 318	C#
 	Microsoft.VisualStudio.Composition.dll!Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportElement(Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker importingPartTracker, Microsoft.VisualStudio.Composition.RuntimeComposition.RuntimeImport import, Microsoft.VisualStudio.Composition.RuntimeComposition.RuntimeExport export, System.Func<System.Func<object>, object, object> lazyFactory) Line 224	C#
 	Microsoft.VisualStudio.Composition.dll!Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportSite(Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker importingPartTracker, Microsoft.VisualStudio.Composition.RuntimeComposition.RuntimeImport import) Line 193	C#
 	Microsoft.VisualStudio.Composition.dll!Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue.AnonymousMethod__10_0(Microsoft.VisualStudio.Composition.RuntimeComposition.RuntimeImport import) Line 482	C#
 	System.Core.dll!System.Linq.Enumerable.WhereSelectArrayIterator<System.__Canon, System.__Canon>.MoveNext() Line 327	C#
 	System.Core.dll!System.Linq.Buffer<object>.Buffer(System.Collections.Generic.IEnumerable<object> source) Line 2558	C#
 	System.Core.dll!System.Linq.Enumerable.ToArray<object>(System.Collections.Generic.IEnumerable<object> source) Line 830	C#
 	Microsoft.VisualStudio.Composition.dll!Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue() Line 481	C#
 	Microsoft.VisualStudio.Composition.dll!Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create() Line 1171	C#
 	Microsoft.VisualStudio.Composition.dll!Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleState nextState) Line 1266	C#
 	Microsoft.VisualStudio.Composition.dll!Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleState requiredState) Line 1345	C#
 	Microsoft.VisualStudio.Composition.dll!Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose() Line 1072	C#
 	Microsoft.VisualStudio.Composition.dll!Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetExportedValueHelper.AnonymousMethod__0() Line 318	C#
 	Microsoft.VisualStudio.Composition.dll!Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportElement(Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker importingPartTracker, Microsoft.VisualStudio.Composition.RuntimeComposition.RuntimeImport import, Microsoft.VisualStudio.Composition.RuntimeComposition.RuntimeExport export, System.Func<System.Func<object>, object, object> lazyFactory) Line 224	C#
 	Microsoft.VisualStudio.Composition.dll!Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportSite(Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker importingPartTracker, Microsoft.VisualStudio.Composition.RuntimeComposition.RuntimeImport import) Line 193	C#
 	Microsoft.VisualStudio.Composition.dll!Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue.AnonymousMethod__10_0(Microsoft.VisualStudio.Composition.RuntimeComposition.RuntimeImport import) Line 482	C#
 	System.Core.dll!System.Linq.Enumerable.WhereSelectArrayIterator<System.__Canon, System.__Canon>.MoveNext() Line 327	C#
 	System.Core.dll!System.Linq.Buffer<object>.Buffer(System.Collections.Generic.IEnumerable<object> source) Line 2558	C#
 	System.Core.dll!System.Linq.Enumerable.ToArray<object>(System.Collections.Generic.IEnumerable<object> source) Line 830	C#
 	Microsoft.VisualStudio.Composition.dll!Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue() Line 481	C#
 	Microsoft.VisualStudio.Composition.dll!Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create() Line 1171	C#
 	Microsoft.VisualStudio.Composition.dll!Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleState nextState) Line 1266	C#
 	Microsoft.VisualStudio.Composition.dll!Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleState requiredState) Line 1345	C#
 	Microsoft.VisualStudio.Composition.dll!Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose() Line 1072	C#
 	Microsoft.VisualStudio.Composition.dll!Microsoft.VisualStudio.Composition.ExportProvider.CreateExport.AnonymousMethod__0() Line 472	C#
 	mscorlib.dll!System.Lazy<object>.CreateValue() Line 437	C#
 	mscorlib.dll!System.Lazy<object>.LazyInitValue() Line 388	C#
 	mscorlib.dll!System.Lazy<object>.Value.get() Line 339	C#
 	Microsoft.VisualStudio.Composition.Configuration.dll!Microsoft.VisualStudio.Composition.NetFxAdapters.MefV1ExportProvider.UnwrapExport.AnonymousMethod__1() Line 235	C#
 	System.ComponentModel.Composition.dll!System.ComponentModel.Composition.Primitives.Export.GetExportedValueCore() Line 247	C#
 	System.ComponentModel.Composition.dll!System.ComponentModel.Composition.Primitives.Export.Value.get() Line 207	C#
 	System.ComponentModel.Composition.dll!System.ComponentModel.Composition.ExportServices.GetCastedExportedValue<Microsoft.AppInsights.GettingStarted.IAddAppInsightsToProjectProvider>(System.ComponentModel.Composition.Primitives.Export export) Line 135	C#
 	System.ComponentModel.Composition.dll!System.ComponentModel.Composition.ExportServices.CreateStronglyTypedLazyOfT.AnonymousMethod__1() Line 107	C#
 	mscorlib.dll!System.Lazy<Microsoft.AppInsights.GettingStarted.IAddAppInsightsToProjectProvider>.CreateValue() Line 437	C#
 	mscorlib.dll!System.Lazy<Microsoft.AppInsights.GettingStarted.IAddAppInsightsToProjectProvider>.LazyInitValue() Line 359	C#
 	mscorlib.dll!System.Lazy<Microsoft.AppInsights.GettingStarted.IAddAppInsightsToProjectProvider>.Value.get() Line 339	C#
 	Microsoft.VisualStudio.ApplicationInsights.dll!Microsoft.AppInsights.GettingStarted.FileNew.EnableAppInsightsModel.CanAddToProject.AnonymousMethod__0(System.Lazy<Microsoft.AppInsights.GettingStarted.IAddAppInsightsToProjectProvider> p) Line 1100	C#
 	System.Core.dll!System.Linq.Enumerable.FirstOrDefault<System.Lazy<Microsoft.AppInsights.GettingStarted.IAddAppInsightsToProjectProvider>>(System.Collections.Generic.IEnumerable<System.Lazy<Microsoft.AppInsights.GettingStarted.IAddAppInsightsToProjectProvider>> source, System.Func<System.Lazy<Microsoft.AppInsights.GettingStarted.IAddAppInsightsToProjectProvider>, bool> predicate) Line 960	C#
 	Microsoft.VisualStudio.ApplicationInsights.dll!Microsoft.AppInsights.GettingStarted.FileNew.EnableAppInsightsModel.CanAddToProject(Microsoft.VisualStudio.TemplateProviders.IVsTemplate template) Line 1101	C#
 	Microsoft.VisualStudio.ApplicationInsights.dll!Microsoft.AppInsights.GettingStarted.FileNew.EnableAppInsightsVisibilityConverter.Convert(object value, System.Type targetType, object parameter, System.Globalization.CultureInfo culture) Line 55	C#
 	PresentationFramework.dll!System.Windows.Data.BindingExpression.TransferValue(object newValue, bool isASubPropertyChange) Line 1512	C#
 	PresentationFramework.dll!System.Windows.Data.BindingExpression.Activate(object item) Line 1027	C#
 	PresentationFramework.dll!System.Windows.Data.BindingExpression.AttachToContext(System.Windows.Data.BindingExpression.AttachAttempt attempt) Line 850	C#
 	PresentationFramework.dll!System.Windows.Data.BindingExpression.AttachOverride(System.Windows.DependencyObject target, System.Windows.DependencyProperty dp) Line 555	C#
 	PresentationFramework.dll!System.Windows.Data.BindingExpressionBase.OnAttach(System.Windows.DependencyObject d, System.Windows.DependencyProperty dp) Line 378	C#
 	PresentationFramework.dll!System.Windows.StyleHelper.GetInstanceValue(System.Windows.UncommonField<System.Collections.Specialized.HybridDictionary[]> dataField, System.Windows.DependencyObject container, System.Windows.FrameworkElement feChild, System.Windows.FrameworkContentElement fceChild, int childIndex, System.Windows.DependencyProperty dp, int i, ref System.Windows.EffectiveValueEntry entry) Line 2994	C#
 	PresentationFramework.dll!System.Windows.FrameworkTemplate.ReceivePropertySet(object targetObject, System.Xaml.XamlMember member, object value, System.Windows.DependencyObject templatedParent) Line 868	C#
 	PresentationFramework.dll!System.Windows.FrameworkTemplate.LoadOptimizedTemplateContent.AnonymousMethod__3(object sender, System.Windows.Markup.XamlSetValueEventArgs setArgs) Line 948	C#
 	System.Xaml.dll!System.Xaml.XamlObjectWriter.OnSetValue(object eventSender, System.Xaml.XamlMember member, object value) Line 198	C#
 	System.Xaml.dll!System.Xaml.XamlObjectWriter.Logic_ApplyPropertyValue(MS.Internal.Xaml.Context.ObjectWriterContext ctx, System.Xaml.XamlMember prop, object value, bool onParent) Line 1620	C#
 	System.Xaml.dll!System.Xaml.XamlObjectWriter.Logic_DoAssignmentToParentProperty(MS.Internal.Xaml.Context.ObjectWriterContext ctx) Line 2054	C#
 	System.Xaml.dll!System.Xaml.XamlObjectWriter.Logic_AssignProvidedValue(MS.Internal.Xaml.Context.ObjectWriterContext ctx) Line 1683	C#
 	System.Xaml.dll!System.Xaml.XamlObjectWriter.WriteEndObject() Line 477	C#
 	System.Xaml.dll!System.Xaml.XamlWriter.WriteNode(System.Xaml.XamlReader reader) Line 41	C#
 	PresentationFramework.dll!System.Windows.FrameworkTemplate.LoadTemplateXaml(System.Xaml.XamlReader templateReader, System.Xaml.XamlObjectWriter currentWriter) Line 1024	C#
 	PresentationFramework.dll!System.Windows.FrameworkTemplate.LoadTemplateXaml(System.Xaml.XamlObjectWriter objectWriter) Line 982	C#
 	PresentationFramework.dll!System.Windows.FrameworkTemplate.LoadOptimizedTemplateContent(System.Windows.DependencyObject container, System.Windows.Markup.IComponentConnector componentConnector, System.Windows.Markup.IStyleConnector styleConnector, System.Collections.Generic.List<System.Windows.DependencyObject> affectedChildren, System.Windows.UncommonField<System.Collections.Hashtable> templatedNonFeChildrenField) Line 955	C#
 	PresentationFramework.dll!System.Windows.FrameworkTemplate.LoadContent(System.Windows.DependencyObject container, System.Collections.Generic.List<System.Windows.DependencyObject> affectedChildren) Line 582	C#
 	PresentationFramework.dll!System.Windows.StyleHelper.ApplyTemplateContent(System.Windows.UncommonField<System.Collections.Specialized.HybridDictionary[]> dataField, System.Windows.DependencyObject container, System.Windows.FrameworkElementFactory templateRoot, int lastChildIndex, System.Collections.Specialized.HybridDictionary childIndexFromChildID, System.Windows.FrameworkTemplate frameworkTemplate) Line 1869	C#
 	PresentationFramework.dll!System.Windows.FrameworkTemplate.ApplyTemplateContent(System.Windows.UncommonField<System.Collections.Specialized.HybridDictionary[]> templateDataField, System.Windows.FrameworkElement container) Line 502	C#
 	PresentationFramework.dll!System.Windows.FrameworkElement.ApplyTemplate() Line 365	C#
 	PresentationFramework.dll!System.Windows.FrameworkElement.MeasureCore(System.Windows.Size availableSize) Line 4315	C#
 	PresentationCore.dll!System.Windows.UIElement.Measure(System.Windows.Size availableSize) Line 664	C#
 	PresentationCore.dll!System.Windows.ContextLayoutManager.UpdateLayout() Line 317	C#
 	PresentationCore.dll!System.Windows.UIElement.UpdateLayout() Line 1660	C#
 	PresentationCore.dll!System.Windows.Interop.HwndSource.SetLayoutSize() Line 1179	C#
 	PresentationCore.dll!System.Windows.Interop.HwndSource.RootVisualInternal.set(System.Windows.Media.Visual value) Line 571	C#
 	PresentationCore.dll!System.Windows.Interop.HwndSource.RootVisual.set(System.Windows.Media.Visual value) Line 515	C#
 	PresentationFramework.dll!System.Windows.Window.SetRootVisual() Line 2878	C#
 	PresentationFramework.dll!System.Windows.Window.SetRootVisualAndUpdateSTC() Line 2893	C#
 	PresentationFramework.dll!System.Windows.Window.SetupInitialState(double requestedTop, double requestedLeft, double requestedWidth, double requestedHeight) Line 2853	C#
 	PresentationFramework.dll!System.Windows.Window.CreateSourceWindow(bool duringShow) Line 2591	C#
 	PresentationFramework.dll!System.Windows.Window.CreateSourceWindowDuringShow() Line 2459	C#
 	PresentationFramework.dll!System.Windows.Window.SafeCreateWindowDuringShow() Line 5554	C#
 	PresentationFramework.dll!System.Windows.Window.ShowHelper(object booleanBox) Line 5646	C#
 	PresentationFramework.dll!System.Windows.Window.Show() Line 212	C#
 	PresentationFramework.dll!System.Windows.Window.ShowDialog() Line 456	C#
 	Microsoft.VisualStudio.Shell.14.0.dll!Microsoft.Internal.VisualStudio.PlatformUI.WindowHelper.ShowModal(System.Windows.Window window, System.IntPtr parent) Line 337	C#
 	Microsoft.VisualStudio.Shell.14.0.dll!Microsoft.VisualStudio.PlatformUI.DialogWindow.ShowModal() Line 71	C#
 	Microsoft.VisualStudio.Dialogs.dll!Microsoft.VisualStudio.Dialogs.SVsDialogService.InvokeDialog(Microsoft.Internal.VisualStudio.Shell.Interop.VSNEWPROJECTDLGINFO dlgInfo, out string bstrLocation) Line 86	C#

**Comment by heejaechang** [comment]
I think this is culprit.

Microsoft.VisualStudio.ApplicationInsights.dll!Microsoft.AppInsights.GettingStarted.FileNew.EnableAppInsightsModel.CanAddToProject.AnonymousMethod__0(System.Lazy p) Line 1100 C#
System.Core.dll!System.Linq.Enumerable.FirstOrDefault>

**Comment by heejaechang** [comment]
chain seems  IAppInsightsProjectCommandProvider -> IAddAppInsightsToProjectProvider -> AddToUAPProjectProvider  ->  ICodeInjectionFactory  -> CodeInjectionFactory 

something like that, and CodeInjectionFactory will import VisualStudioWorkspace.

**Comment by rchande** [comment]
Thanks for tracking that down. I'll take a look tomorrow and file a bug for them.

**Comment by rchande** [comment]
(Since they probably don't track bugs on GitHub)
