### ISSUE TITLE
Lazy acquisition paradigm and C# Auto-Initializers

### ISSUE THREAD

**Issue by JensMeinecke** [dotnet/roslyn#8245]
In lots of classes we do something like this:

``` C#
class MyClass
{
       private  OtherClass _otherValue;
       public OtherClass OtherValue
       { 
          get { return _otherValue?? (_otherValue = SomeExpensiveExpression());}
      }
}
```

In other words we have a read-only property with a backing field that we want to only evaluate once and keep in memory (classic lazy acquisition). 

But now that we have Auto-Property Initializers, which automatically create a backing field, couldn't we simply extend this concept to a lazily acquired Auto-Property - in other words, only carry out the initialization when the property is first accessed.

I am not sure about the syntax, but how about something along these lines?

``` C#
      public OtherClass OtherValue { get; } ??= SomeExpensiveExpression(); 
```

It would tidy up lots of classes immensely.

**Comment by alrz** [comment]
Dup of #3415, #4374 and a couple of others.
