### ISSUE TITLE
When code reached the end of switch sections

### ISSUE THREAD

**Issue by Citringo** [dotnet/roslyn#8247]
I want C# to terminate the switch statement when code reaches the end of switch section.

Because, I always think it is verbose that each switch sections have a break statement.

Like this:
```C#
class Program
{
	static void Main(string args[])
	{
		Random r = new Random();
		switch (r.Next(5))
		{
			case 0:
				Console.WriteLine("It's 0.");
			case 1: // No fall through
				Console.WriteLine("It's 1.");
			case 2: 
			case 3: // Allow multiple case label
				Console.WriteLine("It's 2 or 3.");
			case 4:
				Console.WriteLine("It's 4.");
				break; // Traditional break can also use
			default:
				Console.WriteLine("!?");
		}
	}
}
```

In this program, If variable "r" is 0, console will show "It's 0." and program will finish.

(Sorry to my bad English...)

**Comment by alrz** [comment]
Dupe of #1426, though, this is about implicit `break`, not allowing fall through.

**Comment by Citringo** [comment]
I don't want to allow fall through. I want to terminate switch block like Select Case of VB.

**Comment by alrz** [comment]
@Citringo Then check out #959.

**Comment by Citringo** [comment]
I see.
