### ISSUE TITLE
What happened to Visual Basic Scripting?

### ISSUE THREAD

**Issue by TanielianVB** [dotnet/roslyn#8248]
Today in the [Scripting API Samples](https://github.com/dotnet/roslyn/wiki/Scripting-API-Samples) there's only C# Scripting.

When I install the:

``` PowerShell
PM> Install-Package Microsoft.CodeAnalysis.Scripting
```

only the

``` C#
using Microsoft.CodeAnalysis.CSharp.Scripting;
```

comes. Where's the 

``` C#
using Microsoft.CodeAnalysis.VisualBasic.Scripting;
```

?
There are some mentions that indicate that he existed. Example:
["... You can grab the C# scripting package using the following NuGet installation command (there is also a corresponding one for Visual Basic scripting, _Microsoft.CodeAnalysis.Scripting.VisualBasic_): ..."](http://blogs.msdn.com/b/cdndevs/archive/2015/12/01/adding-csharp-scripting-part-1.aspx)

**Comment by tmat** [comment]
VB scripting is not currently available.

**Comment by TanielianVB** [comment]
Thanks for the reply.

**Comment by robinsedlaczek** [comment]
@tmat @Pilchie Are there any news regarding your plans for VB script?

**Comment by tmat** [comment]
See also: https://github.com/dotnet/roslyn/issues/13523
