### ISSUE TITLE
Poor codegen for o?.Prop == k

### ISSUE THREAD

**Issue by pharring** [dotnet/roslyn#825]
Consider this code:

    static bool HasLength(string s, int len)
    {
        return s?.Length == len;
    }

I expected this to generate the same code as:
```return (s != null) ? (s.Length == len) : false;```

However, it currently generates the equivalent of:
```return ((s != null) ? new int?(s.Length) : null) == len;```

It's actually a bit worse than that because of the implicit conversion rules. It's more like:

        int? t = (s == null) ? default(int?) : new int?(s.Length);
        return t.GetValueOrDefault() == len && t.HasValue;

Is that "by design" or simply a missed optimization opportunity?

Note that this pattern appears in Roslyn code in the [IsKind] (https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/CSharpExtensions.cs#L29) extension method. It would be nice to continue to use ?. there, but if this is the expected codegen, we should avoid it.

**Comment by pharring** [comment]
@VSadov @gafter opinions?
I notice that if ```len``` is replaced by a constant, then the expected optimization kicks in. i.e.
```s?.Length == 1;``` generates code equivalent to ```(s != null) ? (s.Length == 1) : false;```

**Comment by VladimirReshetnikov** [comment]
I would expect that we optimize it even with non-constant RHS. Looks like a bug.

**Comment by tmat** [comment]
It's been pointed out that IsKind() and Kind() are inconsistent in that Kind() throws NRE while IsKind() handles null. @AnthonyDGreen what is your opinion on this? Should IsKind() throw NRE as well?

**Comment by AnthonyDGreen** [comment]
IsKind should throw NRE. We have the ?. operator in the language now, users can be explicit about whether they want operations to be null-propagating. It's actually kind of unintuitive and hides bugs when we implicitly handle it in some places.

Though honestly I've never been very fond of IsKind at all due to the minimal value compared to ==. Perhaps we should remove it?

**Comment by tmat** [comment]
+1 for throwing NRE.
-1 for removing IsKind - Yes, it's slightly redundant but node.IsKind(SyntaxKind.Foo) actually reads much better than node.Kind() == SyntaxKind.Foo

**Comment by VladimirReshetnikov** [comment]
NRE should be only thrown by the runtime. If we want to throw anything manually, it should be ArgumentNullException (even for extension methods).

**Comment by tmat** [comment]
By throwing NRE I meant just do nothing :) -- that is just dot thru the argument and don't check anything.

**Comment by gafter** [comment]
It would be great to produce better code for this.

**Comment by mattwar** [comment]
IsKind doesn't throw because at the time I introduced it there was already an internal extension of the same name that lots of IDE features used, and having it throw caused many of them all to break. I agree that it should throw, but someone's got to find and fix all the call sites that are problematic.

**Comment by pharring** [comment]
The discussion of IsKind can be continued at issue #849. Please keep this issue focused on the code-gen quality for Boolean expressions involving ?.
Thanks.

**Comment by pharring** [comment]
@VSadov do you want to take a look at the code generation issue?

**Comment by VSadov** [comment]
I will take a look at the codegen part.

**Comment by VladimirReshetnikov** [comment]
Please also consider other relational operators, e.g. `list?.Count >= 1`, operators on floating-point and enum types, and VB counterparts.
