### ISSUE TITLE
Test 'Make Method Synchronous' code refactoring

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#8251]

**Comment by brettfo** [comment]
I tested (in no particular order) the following scenarios:

- Code action only appears on `async` methods lacking the `await` keyword (VB/C#)
- Simple cases (VB/C#); both declaration and callsites appropriately renamed
  - `async Task<bool> FooAsync()` -> `bool Foo()` // return type and name altered
  - `async Task FooAsync()` -> `void Foo()` // return type and name altered
  - `async void Foo()` -> `void Foo()` // neither altered
  - Cross-project/language
- Naming conflicts (VB/C#)
  - `void Foo() { } async void FooAsync() { }` -> `void Foo() { } void Foo() { }`  Definition was renamed but callsites
    were untouched leaving broken calls to `FooAsync()` which I think is the correct behavior because the user must
    solve that conflict and the error serves as a marker.  Similar naming conflicts were tested with type and namespace
    names.
  - Keyword conflicts: `async void intAsync() { }` -> `void @int() { }`
  - Name-trimming not possible: `async void Async() { }` -> `void Async()`

Marking issue as complete.
