### ISSUE TITLE
Edit and continue / QuickWatch

### ISSUE THREAD

**Issue by punicaaa** [dotnet/roslyn#8254]
we changed our environment from Visual Studio 2008 to 2015 (Update 1) and now we got some strange debug behaviours.

When we hit a breakpoint and insert new lines of code and continue, we are not able to see the variable content of some types in QuickWatch or immediate window anymore. (e.g. DataTables, Images ...)

Error message : A type or generic instantiation needed to evaluate this expression does not exist in the process being debugged

Our target framework is .NET 3.5. When we change it to 4.0 or higher everything works fine.

It is not a project releated problem. We can reprocude it with a simple 'Hello World' console application.

**Comment by tmat** [comment]
@pnelsonmsft

**Comment by davkean** [comment]
@punicaaa Can you attach a simple repro? I'll make sure this gets on the right team's radar.

**Comment by punicaaa** [comment]
@davkean here is a simple example
[Debug_Example.zip](https://github.com/dotnet/roslyn/files/116297/Debug_Example.zip)

`

	Sub Main()
		Dim tempTable As New DataTable
		tempTable.Columns.Add("Col1")
	
		System.Diagnostics.Debugger.Break()
		'Uncomment the following line
		'tempTable.Columns.Add("Col2")
	
		'Now Check the Column Count or whatever in QuickWatch or Immediate Window.
		System.Diagnostics.Debugger.Break()
	End Sub
`

Target framework must be 3.5 and Target CPU x86.

**Comment by ManishJayaswal** [comment]
This is likely not related to Roslyn EEs. Debugger team should take a look.

**Comment by plnelson** [comment]
This is already being tracked by internal bug 206464

**Comment by ManishJayaswal** [comment]
Closing this since it is not Roslyn related.
