### ISSUE TITLE
make additionaldocument support in workspace consistent with document

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#8256]
additionalDocument in workspace behave different than document in workspace. there is no document open/close or text changed event but some data we put in workspace and some not. quite inconsistent.

we should either make workspace API which doesnt require Document to TextDocument such as TextChanged event or DocumentOpened event, or we should add event for it as well.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  We haven't needed to do this so far, so we don't need an item tracking this.
