### ISSUE TITLE
IntelliSense and GFU always add "using System;" if its not there

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#8257]
For example:

``` C#
abstract class A
{
    protected abstract void M();
}

class B :A
{
    // <-- type 'override M<TAB>' here
}
```

This results in a member being generated with `throw new NotImplementedException();` in the body and `using System;` at the top of the file. The addition of 'using System' can be pretty annoying because the user has to remove unused usings after they implement the body. I propose that we only minimally-qualify `NotImplementedException` if `using System` is already present. Otherwise, we should leave it fully-qualified.

**Comment by DustinCampbell** [comment]
This was reported through VS Feedback

**Comment by joao-moraes-petitfabrik** [comment]
Not only that, but the added 'using System' is causing an ambiguous reference error on my file.

'Random' is an ambiguous reference between 'UnityEngine.Random' and 'System.Random'
