### ISSUE TITLE
cref should not be able to access private fields in other assemblies

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#826]
This is a continued discussion from issue #77 

Today the binding which occurs during a `cref` lookup does not respect accessibility.  This is a back compat behavior to the native compiler which makes sense to a degree.  The ability to reference private fields which are defined in the same assembly does have documentation value.  

But I think the dangers of allowing references to private fields across assembly boundaries outweighs the documentation benefit because it creates the following issues:

- It should force a change in how tools generate reference assemblies.  Today they typically exclude private data.  This prevents them from being perfect stand ins for non-reference assemblies.  For example today I cannot add a `cref` to `string.m_firstChar` because the ref assembly excludes it.  
- It opens up the possibility that private member name changes can cause compilation errors in unrelated assemblies.  Private member rename should not be a back compat break.  
- It reduces the set of refactorings that can be safely done intra-project which slows down our overall refactoring story.
- It opens up the possibility that adding a new private member creates a compilation error (could create an ambiguity with other accessible members used by a `cref`).  

Limiting the accessibility suppression to be intra-assembly only would mitigate these concerns.

**Comment by gafter** [comment]
@theoy Please consider this a request to the compat council. I expect you'll want some data about the impact. We'll prototype it and see what happens.

**Comment by sharwell** [comment]
@jaredpar How would you feel about expanding this to the same scope as `InternalsVisibleTo`?

**Comment by sharwell** [comment]
@jaredpar Also, what about preserving the ability to reference API-visible items across assembly boundaries. This specifically applies to protected members of another type, which could actually be a useful scenario even in public-facing API documentation.

**Comment by jaredpar** [comment]
@sharwell unfortunately any change here is a back compat breaking change.  If I were designing this from scratch I would feel significantly different about this behavior.  Given the back compat constraints though any change here must be targeted and deliberate.  

I feel less strong about the problem occurring for `protected` and `internal` members.  Those are modifiers which are designed to open the member to visibility in other contexts (even if the context of the modifier means it's not as accessible as its name).  

The `private` modifier though is unambiguous in its meaning.  Outside of nested types, which are directly controlled by the type adding `private`, no one else can see a `private` member.  Adding and removing `private` members by themselves should never affect the success or failure of the compilation.  Except in the cases of `cref` and it can do so across assembly boundaries.  

This was bad before but in Roslyn the problem gets worse because:

- `using static` makes this problem much more visible because it allows `private` members to be used without qualification in a `cref`.  That makes it much easier for them to conflict with other unqualified members. 
- Roslyn is an API now and letting `private` be visible across assembly boundaries means that refactorings which should logically be limited to a single assembly now actually have to be a cross assembly refactoring.  It's inserting a large perf issue to deal with a crazy pathological case that no one should be doing anyway.

**Comment by gafter** [comment]
@AnthonyDGreen @DustinCampbell @ljw1004 @MadsTorgersen @gafter @srivatsn @theoy Paging the compat council to consider the proposed outcome.

**Comment by gafter** [comment]
@amcasey Just told me "@agocke explained to me offline that we would just update the spots in the code that detect the cref case and suppress accessibility checking to detect the cref case and use modified accessibility checking.  That sound feasible.  Please just be careful not to make the change in BindCref – it’s tempting, but it breaks the SemanticModel."

**Comment by gafter** [comment]
@jaredpar assigning to you to "Verify", please.

**Comment by gafter** [comment]
@amcasey Can you please verify that this is the behavior on the stabilization branch?

**Comment by amcasey** [comment]
@gafter With project-to-project references, internal members are accessible in crefs.  With metadata references, they are not.  Is that expected?

**Comment by amcasey** [comment]
```C#
        [WorkItem(1928, "https://github.com/dotnet/roslyn/pull/1928")]
        [Fact]
        public void Repro1928()
        {
            var source1 = @"
public class Class
{
    static public int Public;
    static protected int Protected;
    static protected internal int ProtectedInternal;
    static internal int Internal;
    static private int Private;
}
";

            var source2 = @"
class Program
{
    /// <see cref=""Class.Public""/>
    /// <see cref=""Class.Protected""/>
    /// <see cref=""Class.ProtectedInternal""/>
    /// <see cref=""Class.Internal""/>
    /// <see cref=""Class.Private""/>
    static void Main(string[] args)
    {
    }
}
";

            var comp1 = CreateCompilationWithMscorlib(source1);
            var comp2a = CreateCompilationWithMscorlibAndDocumentationComments(source2, new[] { new CSharpCompilationReference(comp1) });
            comp2a.VerifyDiagnostics(
                // (8,20): warning CS1574: XML comment has cref attribute 'Private' that could not be resolved
                //     /// <see cref="Class.Private"/>
                Diagnostic(ErrorCode.WRN_BadXMLRef, "Class.Private").WithArguments("Private").WithLocation(8, 20));

            var comp2b = CreateCompilationWithMscorlibAndDocumentationComments(source2, new[] { comp1.EmitToImageReference() });
            comp2b.VerifyDiagnostics(
                // (7,20): warning CS1574: XML comment has cref attribute 'Internal' that could not be resolved
                //     /// <see cref="Class.Internal"/>
                Diagnostic(ErrorCode.WRN_BadXMLRef, "Class.Internal").WithArguments("Internal").WithLocation(7, 20),
                // (8,20): warning CS1574: XML comment has cref attribute 'Private' that could not be resolved
                //     /// <see cref="Class.Private"/>
                Diagnostic(ErrorCode.WRN_BadXMLRef, "Class.Private").WithArguments("Private").WithLocation(8, 20));
        }
```

**Comment by gafter** [comment]
@amcasey No, that is not intended! Given where we are in the release cycle, can you please open up a separate bug for that?

**Comment by gafter** [comment]
@amcasey I'll file the bug.

**Comment by amcasey** [comment]
Verified, modulo #3500.
