### ISSUE TITLE
NavigateTo hangs the UI thread when searching in large solutions

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#8260]
_Repro Steps:_ invoke Navigate To in Roslyn, and try to use it.
_Expected:_ a nice user experience.
_Actual:_ sadness where the UI gets blocked like crazy.

I attached a debugger to see why we were getting such bad hangs, and it turns out this is our fault. We build an index of [`DeclaredSymbolInfo`](https://github.com/dotnet/roslyn/blob/6288d75afa5d7ae86ab534dfd0100962f3742607/src/Workspaces/Core/Portable/FindSymbols/DeclaredSymbolInfo.cs#L28)s and store that index as a way to quickly find members. We use that index, and produce a bunch of NavigateTo items. But once we are asked for the glyph or the display string of those items, we then try to realize a Symbol...on the UI thread. Curiously, since our index exists and is populated from syntax only, we are able to return items for projects we might not yet have `Compilations` for, so realizing symbols might be _really_ expensive.

I chatted with @dpoeschl and @CyrusNajmabadi to discuss a few possible options:
1. Make the Navigate To core system asynchronous. :wink:
2. Update our `DeclaredSymbolInfo` cache to cache additional information, ensuring we don't need to realize symbols in the first place. This looked possible, but might require a bit of work because we produce the index from source only and might have to semi-reimplement `SymbolDisplay`.
3. Don't provide items through our provider until we have a symbol realized. This means there is a delay in giving the results (which makes our index less useful), but at least ensures we won't hang the UI afterwards.

**Comment by jasonmalinowski** [comment]
Another possible mitigation would be to use the in-progress solution when we get symbols, since we only care to get the source symbol, and only enough for purposes of symbol display. I'm going to try that quick, but that still means getting the symbol is backed up behind parsing which isn't great either.

**Comment by DustinCampbell** [comment]
@jasonmalinowski, I assume there's further work to do here. Using partial semantics is a reasonable change but it might make the experience non-deterministic. Isn't Navigate To always supposed to be asynchronous? It seems wrong that it would every hang the UI thread.

**Comment by jasonmalinowski** [comment]
"maybe". We believe that the move to partial semantics is not noticeable, since the things that are done with the symbols won't be impacted by incomplete information. Still, it only _reduces_ instead of _eliminates_ the blocking. So yes, there's more work to do here, but it's quite possible that the move to partial semantics is "good enough" and this is low enough priority to just close it.

**Comment by jasonmalinowski** [comment]
In any case, I'm completely OK with moving this to 1.3 assuming we don't see any further ugliness with partial semantics, either functionally or performance wise.

**Comment by CyrusNajmabadi** [comment]
The current behavior feels fine to me.  No massive hangs of the UI.  No painting problems.  So overall i consider this issue to be addressed.  If you do want to keep this around to track doing no blocking, then that's ok with me.

**Comment by Pilchie** [comment]
@jasonmalinowski Should this be resolved at this point?

**Comment by jasonmalinowski** [comment]
I've seen it happens since the last set of fixes. Probably appropriate to move to 2.0 though.

**Comment by jasonmalinowski** [comment]
Saw this again today.

**Comment by CyrusNajmabadi** [comment]
I have a change where we make this all async.  It's here: https://github.com/dotnet/roslyn/pull/16445

However, it is currently blocked on: https://github.com/dotnet/roslyn/issues/16450

**Comment by Pilchie** [comment]
@AmadeusW this is the issue you are fixing in the VS Platform, right?

**Comment by dpoeschl** [comment]
This may be another instance of this: https://developercommunity.visualstudio.com/content/problem/28371/type-navigator-is-very-slow.html

**Comment by jasonmalinowski** [comment]
I'm still regularly hitting this in dogfooding.

**Comment by AmadeusW** [comment]
@jasonmalinowski please send me a trace, I'll take a look at it

**Comment by jasonmalinowski** [comment]
Yeah, will do if I see it again.

**Comment by jasonmalinowski** [comment]
Looks like the hang I was hitting was https://github.com/VsVim/VsVim/issues/2715, so closing this again.
