### ISSUE TITLE
C#: 'new' completion doesn't work for field above attribute

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#8261]
``` C#
using System;

class B
{
    object o = new // <-- press SPACE here
    [CLSCompliant(true)]
    int x;
}
```

It looks to me like the parse tree is in a shape that we don't expect. The attribute gets treated as the `[]` in an implicit array creation expression.

**Comment by DustinCampbell** [comment]
This came through VS Feedback

**Comment by rchande** [comment]
Dupe of https://github.com/dotnet/roslyn/issues/15804
