### ISSUE TITLE
Typeless Construction

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#8270]
This proposal is to allow us to write `new( )` inside of a **class** or **structure** to invoke the constructor of the type, we are within.

```vb
Class Foo

  Public ReadOnly Property Value As Integer

  Sub New(Value as integer)
    Me.Value = Value
  End Sub

  Public Shared Function One() As Foo
    Return New(1) ' Invokes the Constructor Foo
  End Function

End Class
```

**Alternative**
An alternative syntax would be to use `new Me` (`new this` *c#*)
```
Class Foo

  Public ReadOnly Property Value As Integer

  Sub New(Value as integer)
    Me.Value = Value
  End Sub

  Public Shared Function One() As Foo
    Return New Me(1)
  End Function

End Class
```

**Comment by alrz** [comment]
Dup of #35

**Comment by AdamSpeight2008** [comment]
@alrz Not a dupe, this is restricted to only being the type you are in. Target type has nothing to do with it.

**Comment by alrz** [comment]
@AdamSpeight2008 While your example clearly defined `One` so that it returns `Foo`, what is the advantage of this over #35?
```cs
public static Foo One() {
  return new(1);
}
```
Even with self types (#311) you can do the same,
```cs
public static this One() {
  return new(1);
}
```
right?

**Comment by AdamSpeight2008** [comment]
Helpful when writing immutable objects.
```vb.net
class Reader
  readonly property Source as Source
  readonly property Index  as Integer

  protected friend sub New( Source As Source, Index As Integer)
    me.Source = Source
    me.Index  = Index
  end sub

  public function [Next]() as me
    return new(me,index+1)
  end function

end class
```

**Comment by alrz** [comment]
@AdamSpeight2008 Again, what you actually want is *self types* and naturally you would get concise constructors with #35 because compiler can infer `new` type from the target (return type of `Next` method).

**Comment by AdamSpeight2008** [comment]
@alrz  I don't won't `new me` to mean construct an instance on my return type (even through inference)
Let's say `Reader` has the following
```
  public function Foo() As Foo
    return new(nothing,0)' would construct a `Reader` not a 'Foo`, it fails on the conversion to Foo
  end function
```

**Comment by HaloFour** [comment]
For your first syntax it doesn't make sense to restrict the inference to the containing type.  I would intuitively expect it to infer the type based on the target of the assignment.  I think that the second syntax is a little clearer in expressing that the type is inferred based on the containing type.  Although in general I'm not sure that I find this a particularly useful proposal.  How often are your type names so egregiously long that it would be an undue burden to type them out, assuming that Intellisense wouldn't autocomplete within one or two keystrokes?

**Comment by AdamSpeight2008** [comment]
@halofour,
*Yes, I know constructor and methods are different, but lets think as them being the same here*

From within the class **new** / **new me** should should be treated as if it was function call to the constructor.  

Return type inferred construction won't work if the return is an abstract class. Having it mean construct an instance of my type, does make sense, if you consider the caae of an overriden method that returns a base class.  As the inheritance relationship as already been accounted for by the class definition.

**Comment by HaloFour** [comment]
@AdamSpeight2008 

You'd have the same issue with your proposal if you tried to use it from within an abstract class, so I think that argument is moot.  Beyond that I don't see why `new()` should be considered a call to the constructor of the current type.  Syntactically it doesn't read that way.  And either way it's not much of an improvement, especially given Intellisense.

**Comment by AdamSpeight2008** [comment]
@HaloFour 
Within an abstract class it would be a error, in a non-abstract base class call the relevant constructor.
```c#
abstract class base
{
  public readonly propery int Value;
  public new(int value)
  {
    this.Value = value;
  }

  abstract base Foo()
  
  base Bar()
  {
    return new(10); \\ Is an error, as it is an abstract class
  }
}

class A : base
{
  public sub new(int value, string text) : base(value)  { ...  }

  override base Foo()
  {
    var obj = new(10,"A"); \\ constructs a new instance of 'A'
    return obj; \\  returns it as a 'base'
  }
}

class B : base
{
  public sub new(int value, string text) : base(value)  { ...   }

  override base Foo()
  {
    var obj = new(20,"B"); \\  constructs a new instance of 'B'
    return obj; \\ return it a 'base'
  }
}
```

**Comment by aluanhaddad** [comment]
Personally, I find the use of ```new``` proposed here to be rather counterintuitive given the the syntax for anonymous types and the proposed syntax for tuples. It also looks very odd in constructor signature position.

**Comment by gafter** [comment]
This conflicts with #35, which we prefer.
