### ISSUE TITLE
Multi-line comment formatting issue

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#8275]
[Filed on behalf of a customer]

If you start a multi-line comment and hit Enter twice, you lose your indentation. This repros most consistently for multi-line comments but has been seen in other circumstances as well. 

![image](https://cloud.githubusercontent.com/assets/1402694/12724341/5f057cd4-c8c2-11e5-8273-9df99f7c0098.png)

**Comment by Pilchie** [comment]
Same issue as https://github.com/dotnet/roslyn/issues/3321?

**Comment by CyrusNajmabadi** [comment]
i don't repro this at all (the comment continues as expected).  and this system was rewritten.  So closing out as something busted in the past.
