### ISSUE TITLE
Outlining: Allow collapsing VB Select Case and Case statements

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#8278]
Suggested though VS Feedback

**Comment by AdamSpeight2008** [comment]
@DustinCampbell :+1:  :+1: 
Whilst at it can we also do the following collapses.
* Multi-line Lambdas
* `If  Then` blocks.
```vb
If ... Then
...
Else If ... Then
...
Else
...
End If
```
* Looping Blocks
 * `While ... End While`
 * `For ... Next`
 * `For Each ... Next`
 * `Do ... Loop Until`
 * `Do ... Loop While`
 * `Do While ... Loop`
 * `Do Until ... Loop`

* Method Parameters
* Array LIterals 

Or put simply anything that is over multiple lines.

**Comment by DustinCampbell** [comment]
@AdamSpeight2008 multi-line lambdas already work. We added that in VS 2015.

Good suggestions, thanks.

**Comment by DustinCampbell** [comment]
Note: I think we would want options for this behavior if somebody wants to do it.

**Comment by CyrusNajmabadi** [comment]
No repro anymore. This appears to have been implemented.
