### ISSUE TITLE
Analyzer dependencies are in the wrong place

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn#828]
The Microsoft.CodeAnalysis.Analyzers NuGet package includes several assemblies:

1. Microsoft.CodeAnalysis.Analyzers.dll
2. Microsoft.CodeAnalysis.CSharp.Analyzers.dll
3. Microsoft.CodeAnalysis.VisualBasic.Analyzers.dll

2 and 3 both depend on 1, but it isn't located next to them as expected. This sometimes leads to compilation errors such as

    CSC : warning CS8032: An instance of analyzer Microsoft.CodeAnalysis.CSharp.Analyzers.MetaAnalyzers.CSharpDiagnosticDescriptorCreationAnalyzer cannot be created from D:\GitWorkspace\NRefactory\packages\Microsoft.CodeAnalysis.Analyzers.1.0.0-rc1\tools\analyzers\C#\Microsoft.CodeAnalysis.CSharp.Analyzers.dll : Could not find file 'D:\GitWorkspace\NRefactory\packages\Microsoft.CodeAnalysis.Analyzers.1.0.0-rc1\tools\analyzers\C#\Microsoft.CodeAnalysis.Analyzers.dll'..

The fix is to make sure the dependency ends up next to the analyzer.

**Comment by jmarolf** [comment]
@tmeschter This is fixed internally with checkin 1424915. Could you please verify?

**Comment by tmeschter** [comment]
I've verified that when installing the package the dependency ends up next to the analyzers.
