### ISSUE TITLE
Roslyn.VisualStudio.Setup.Interactive.dll and Roslyn.VisualStudio.InteractiveComponents.dll need to be excluded from loc

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#8285]
These binaries need to be excluded from loc.

**Comment by amcasey** [comment]
FYI @tannergooding @jinujoseph

**Comment by dpoeschl** [comment]
@davkean @jinujoseph @tannergooding  Why? What's going wrong?

**Comment by davkean** [comment]
They don't contain any resources that need to be localized.

**Comment by dpoeschl** [comment]
@davkean So we just need to delete the locprojs for these?
