### ISSUE TITLE
Update locproj generation to include lcl path

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#8286]
Locproj generation now needs to include lcl path/lcl files as this is now owned by the dev team over the localization team.

**Comment by tmat** [comment]
@davkean @nguerrera Is this still relevant given the new loc system?

**Comment by sharwell** [comment]
@tmeschter can this be closed?

**Comment by tmeschter** [comment]
@We haven't fully moved to the new loc system, but we won't be investing in this particular work item as it pertains to the system we're trying to get off of.
