### ISSUE TITLE
"Compiler Platform Console Application" template is missing NuGet packages

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn#829]
Specifically, it is missing the Microsoft.CodeAnalysis.Analyzers package, even though it is a dependency of the Microsoft.CodeAnalysis.Common package which is included.

**Comment by jmarolf** [comment]
@tmeschtert this was fixed with an internal code change. Could you please verify?

**Comment by tmeschter** [comment]
I've verified that the analyzers are now included, and run correctly, when creating a project from the template.
