### ISSUE TITLE
[VB] 'Simplify type name' on Global alias and base class name introduces a conflict

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#8292]
```
Class Base
    Public Sub New(x As Integer)
    End Sub
End Class
Class Derived : Inherits Base
    ''' <summary>
    ''' <see cref="Global.Base.New(Integer)"/>
    ''' </summary>
    ''' <param name="x"></param>
    Public Sub New(x As Integer)
        MyBase.New(x)
    End Sub
    Public Sub Base(x As Integer)
    End Sub
End Class
```
1. Put the cursor on the Global modifier.
2. Observe the light bulb to appear with "Simplify type name" suggestion. Accept it.

Expected:
"Simplify type name" suggestion does not appear

Actual:
After "Global." is removed, cref="Base.New(Integer)" can no longer be resolved, as it considers "Base" to be the name of the method in Derived class

**Comment by CyrusNajmabadi** [comment]
Closing out as this is an area we are no longer investing in.
