### ISSUE TITLE
Perceived PERF issue in preview colorization when toggling/switching to formatting options

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#8294]
There's a noticeable delay in the semantic classification when toggling formatting options or switching among different options.  For example, the colorization of "Exception" in New Lines page.

David suggested that we could use the same document that contains all the code examples, and project the relevant part for each options.

**Comment by CyrusNajmabadi** [comment]
Closing out as there really doesn't seem to be an issue here, and this is such a narrow space, it's not worth investing in (esp. if this all gets ripped out anyways with new LSP/editorconfig oriented options systems).
