### ISSUE TITLE
Crash - Renaming escaped [New] token should not rename the constructor

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#8297]
1) Trigger rename for "[New]" in below code:

```VB
Class [New]
    Sub New()
    End Sub
End Class
```

**Expected**: Only 1 reference is found, constructor New is not renamed.
**Actual**: 2 references found by rename, including the constructor New. Renaming to a different name throws InvalidCastExceptions as the constructor also gets renamed.

**Comment by DustinCampbell** [comment]
Note: This crashes for VS 2015.

**Comment by dpoeschl** [comment]
This is going wrong here: http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Rename/RenameLocation.ReferenceProcessing.cs,295

When investigating constructors (or static constructors or destructors), it decides to include them in the rename if their text matches the name of the symbol being renamed. It should really only be doing this for C#.

**Comment by AdamSpeight2008** [comment]
@dpoeschl Does the C# rename work correctly for `@` member names?

**Comment by dpoeschl** [comment]
@AdamSpeight2008 Rename works great with verbatim identifiers in both C# and VB. It will add or remove the verbatim-ness as necessary. If you find any bugs with it, let us know!

In this case, we were trying to do something C#-specific (include ctors etc. in the rename) without thinking of the edge case where VB would fail.
