### ISSUE TITLE
Possible bug typo

### ISSUE THREAD

**Issue by vlova** [dotnet/roslyn#83]
Here in the method InsertAfter is used method InsertBefore. 
Also InsertBefore(SyntaxNode node, SyntaxNode newNode) and InsertAfter(SyntaxNode node, SyntaxNode newNode) are duplicates
https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/Editing/SyntaxEditor.cs#L156

**Comment by mattwar** [comment]
Yep, cut & paste error.

**Comment by Pilchie** [comment]
This was fixed by the commit above, just had the "Fixes" in the title instead of the description.
