### ISSUE TITLE
Rename tracking leaks a reference to IWpfTextView.

### ISSUE THREAD

**Issue by brettfo** [dotnet/roslyn#830]
In `RenameTrackingTaggerProviderTests.cs` add a test method with the body:

``` C#
[Fact]
[Trait(Traits.Feature, Traits.Features.RenameTracking)]
public void RenameTrackingTextBufferObjectCounts()
{
    var code = @"
class C
{
    void M$$()
    {
        M();
    }
}
";
    WeakReference textViewWeakReference;
    using (var state = new RenameTrackingTestState(code, LanguageNames.CSharp))
    {
        textViewWeakReference = new WeakReference(state.HostDocument.GetTextView());
        state.EditorOperations.InsertText("ethod");
        state.AssertTag("M", "Method");
        Assert.True(textViewWeakReference.IsAlive);
    }

    GC.Collect();
    GC.WaitForPendingFinalizers();
    GC.Collect();
    Assert.False(textViewWeakReference.IsAlive);
}
```

### Result
`Assert.False()` fails because the weak reference to IWpfTextView is still active.

**Comment by jasonmalinowski** [comment]
Nitpick for the code: can we refactor out a "TestForMemoryLeaks" context that does the creation of weak references and the GC stuff in a single place?

**Comment by dpoeschl** [comment]
This is due to Rename Tracking's [custom undo handling](http://index/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/RenameTracking/RenameTrackingTaggerProvider.UndoPrimitive.cs,61a921100b3ce82f)

**Comment by rchande** [comment]
@jasonmalinowski I feel like we do have that helper.

**Comment by rchande** [comment]
@jasonmalinowski Never mind.

**Comment by dpoeschl** [comment]
@brettfo Didn't you have a better test for this that was done during integration tests or something? This one fails even if you comment out all the rename code.

**Comment by brettfo** [comment]
Replied offline with a pointer to an internal test.

**Comment by dpoeschl** [comment]
@brettfo and I are looking into this.

**Comment by dpoeschl** [comment]
@brettfo I know it was forever ago, but you verified this, right? Can we mark as Verified if that's the case?
