### ISSUE TITLE
[Discussion/Suggestion] Generic struct delegate

### ISSUE THREAD

**Issue by Suchiman** [dotnet/roslyn#8303]
# Preface
I'm not having too high hopes for this since this should have been done in .NET 2 already and is a major breaking change but i guess it's worth a try / discussion. This change would likely require a CLR change so linking #420

# Suggestion
I would suggest to introduce a generic System.Delegate<T>.
Notable changes, taking the existing System.Delegate as a base  
```csharp
public struct Delegate<T>
{
    public T Target { get; }
}
```

# Pros
* Less Heap allocations of course!  
* Since Delegate<T> can be created without a heap allocation, higher level constructs such as LINQ become cheaper to use.  
* Also with having the Target generic, closures can be generated as a struct, avoiding even more heap allocations.

# Cons
* The JIT is bothered with creating more specialized code, probably leading to a higher average runtime memory usage and higher startup costs.  
* Passing around huge closures could become expensive, if they're allocated as structs, but that should probably profiled first.  
* It's a severe major breaking change, even if it's not replacing the current Delegate.  
* Reflection?
* struct Delegate<T> isn't nullable but Delegate is often null --> would need a "void" default

# Ideas
### Break nothing https://github.com/dotnet/roslyn/issues/8303#issuecomment-178610623
Optimize through runtime hacks

### Two worlds https://github.com/dotnet/roslyn/issues/8303#issuecomment-178622223
Adding a special keyword to the delegate declaration to differentiate classic vs. generic delegates, e.g.:
```csharp
public struct delegate void Action();
```

**Comment by HaloFour** [comment]
Since delegates are such a specialized type from the perspective of the CLR I bet a lot of those optimizations could be done without having to change the BCL or the language.  Otherwise I think that such a change would be an extremely breaking change.  How do you propose to handle the issue with the existing delegate hierarchy?  Specifically that user-defined delegates really inherit from `System.MulticastDelegate` and not directly from `System.Delegate`?

**Comment by Suchiman** [comment]
Following the KISS principle, extending the delegate declaration syntax to:
```csharp
public struct delegate void Action();
```
would be the least breaking change since it allows both paradigms to exist at the same time, offloading the work to the compiler to generate case specific code.

Since delegates aren't interchangeable anyway, this isn't a concern here either. The disadvantage is of course that it only works in new code.

I've opened the issue with the Discussion / Suggestion headline because i have no clear proposol for it, so i would like to hear alternatives on how the "breaking" or the "two worlds" issue could be solved.

**Comment by svick** [comment]
For non-closure lambdas, the compiler already avoids the allocation by caching the delegate.

And generally speaking, closures need to be heap allocated, for example, when the closed-over local variable outlives the method or when it's shared by multiple lambdas.

**Comment by Suchiman** [comment]
I've just rediscovered this article: http://xoofx.com/blog/2015/10/08/stackalloc-for-class-with-roslyn-and-coreclr/
Could also be used to archive this without any breaking changes

**Comment by Suchiman** [comment]
Having thought about this again, it has many more problems than i anticipated.
Especially since this leads to delegates that are generic based on the closure, methods with suitable signature are now incompatible when they have different closures which would defeat any benefit from this Feature.

Damn it, not yet a language designer 😉 , closing this as absolutely impossible.
