### ISSUE TITLE
[Test Failure] MSBuild Error (+1 more) in prtest/lin/dbg/unit32 on PR #8288

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#8305]
PR: [#8288](https://github.com/dotnet/roslyn/pull/8288) *Flush 'add using' caches when we encounter low memory conditions.* by @CyrusNajmabadi
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/3293/

**Issue 1: MSBuild Error**
error MSB6006: "csc" exited with code 134. [/mnt/j/workspace/roslyn_prtest_lin_dbg_unit32/src/Compilers/CSharp/Portable/CSharpCodeAnalysis.csproj]

**Issue 2: Compile Error**

**Comment by davkean** [comment]
@agocke Any idea what's going on here?

**Comment by gafter** [comment]
Not enough information to evaluate. Please reopen if this recurs.
