### ISSUE TITLE
Test 'Delegate Invocation to Conditional Access" refactoring

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#8309]

**Comment by balajikris** [comment]
Notes: Feature is currently disabled. #7486 tracks re-enabling it.

**Comment by balajikris** [comment]
_status_: completely blocked by #8476

**Comment by balajikris** [comment]
- [ ] To be unblocked by #8517

**Comment by balajikris** [comment]
_status_: In process

**Comment by balajikris** [comment]
_status_: Signed off :white_check_mark: , **contingent** on #7486, that feature is re-enabled.

- [x] Manually test the feature in various scenarios in the IDE
- [x] Add more coverage via unit tests
