### ISSUE TITLE
Auto completion should not propose a module or not newable type after new or as new

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#8311]
It does not make sense to get "Program" as a recommendation if it's a module.

```
Module Program
    Sub Main
        dim f as new P<place cursor here and check completion list>
    End Sub
End Module
```

**Comment by markhurd** [comment]
I don't think the behaviour here should change. If there were any subclasses of `Program`, they'd be accessible after completion.

**Comment by CyrusNajmabadi** [comment]
Need info if this is actually a problem for the ecosystem.
