### ISSUE TITLE
Type names containing right-to-left characters are displayed corrupted in IntelliSense

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#8312]
![image](https://cloud.githubusercontent.com/assets/3751401/12758468/3eca7850-c991-11e5-83b7-a2ccee360c2e.png)

```
using System.Collections.Generic;

namespace م
{
    class ف {  }
    class ظ<T> {  }
}

class Program
{
    Dictionary<م.ف, م.ظ<م.ف>> x = new  
}
```

**Comment by rchande** [comment]
This is not a regression from VS2013.

**Comment by CyrusNajmabadi** [comment]
Closing out as we haven't heard about any issues here from customers.
