### ISSUE TITLE
"into" recommended after dotting into object

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#8315]
1. Create a new C# project.
2. Enter the following code in a method:

`var y = from x in new [] { 1,2,3 } select x.`
1. Observe the intellisense list after dotting into x.

Actual: "into" keyword is listed.
Expected: nope. nope nope nope.

**Comment by davkean** [comment]
Resolved with https://github.com/dotnet/roslyn/pull/8731.

**Comment by jcouv** [comment]
Any reason to still keep this issue open? @davkean linked to the fix above.

**Comment by davkean** [comment]
Nope feel free to close these sorts of things off the bat and I'll reopen if not.
