### ISSUE TITLE
Debugger intellisense doesn't work when breaking on constructor calls to base class

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#8316]
Start VS, create a new C# console app and paste this:

``` C#
namespace ConsoleApplication1
{
    class Program
    {
        static void Main()
        {
            var x = new derived("test");
        }
    }

    class baseclass
    {
        public baseclass(string s) { }
    }

    class derived : baseclass
    {
        public derived(string s) : base(s)
        { }
    }
}
```

Set a breakpoint on the highlighted line, and hit F5.
When you hit the breakpoint, type 's.' in the watch window

Expected results:
Intellisense should show up for 's' after typing '.'

Results:
No intellisense.

**Comment by rchande** [comment]
VS 2013 behaves similarly.

**Comment by CyrusNajmabadi** [comment]
Not repro on latest builds.
