### ISSUE TITLE
IntelliSense in cref cannot correctly complete 'string' keyword

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#8317]
``` C#
/// <see cref="Foo(str)"/>
class C
{
    void Foo(string s) { }
    void Foo() { }
}
```

Press Ctrl+Space after str.

ACTUAL:

``` C#
/// <see cref="Foo(Foo(string))"/>
class C
{
    void Foo(string s) { }
    void Foo() { }
}
```

EXPECTED:

``` C#
/// <see cref="Foo(string)"/>
class C
{
    void Foo(string s) { }
    void Foo() { }
}
```

**Comment by CyrusNajmabadi** [comment]
Not repro:

![image](https://user-images.githubusercontent.com/4564579/75642586-e3c77600-5bf0-11ea-9443-d8be20f694af.png)

Completing this gives:

![image](https://user-images.githubusercontent.com/4564579/75642596-eaee8400-5bf0-11ea-90b2-36538cb44809.png)
