### ISSUE TITLE
Extra as/is in IntelliSense

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#8319]
Expressions of type 'void' and 'method group' should only show 'is' in IntelliSense, not 'as'. 
Arguably, they shouldn't show 'is' either, since it will always result in a warning, but 'as' will always result in an error, so it certainly shouldn't be shown. 

Similarly, lambdas & anonymous methods shouldn't show any IntelliSense afterwards, as neither is nor as is applicable. 

Source: 

``` C#
var b = Console.Beep 
var b = Console.Beep() 
Action a = delegate { } 
Action b = (() => 0) 
```

Press Ctrl+Space at the end of each line.

**Comment by rchande** [comment]
FYI @slaks

**Comment by bmay2** [comment]
Mind if I take on this one?

**Comment by Pilchie** [comment]
Of course not @bmay2.  I'll remove the `Up for Grabs` label if you want to claim it.  Assigning to @rchande to help push things along if necessary.

**Comment by bmay2** [comment]
Thanks @Pilchie. @rchande, is it okay if I remove the 'is' IntelliSense option from 'void' and 'method group' expressions, too? It is a more straightforward fix because 'is' and 'as' are currently in the same syntax context.

**Comment by rchande** [comment]
@bmay2 Fine with me.
