### ISSUE TITLE
IntelliSense shows named argument that was already passed positionally

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#8323]
Keystrikes:

``` C#
int.Parse("", style: 0, 
```

Pressing Ctrl+Space will show both `provider:` and `s:`, even though `s:` was already specified as the first positional argument.

This also happens if you don't pass any named arguments:

``` C#
string.Intern("", str
```

IntelliSense will show `str:`.

**Comment by rchande** [comment]
FYI @slaks

**Comment by CyrusNajmabadi** [comment]
Closing out as we're unlikely to change anything here.  It's been 7 years without anyone raising this as a problem.  Generally speaking, its' fine for completion to show extra items.  This may also be helpful as users may type in arbitrary orders, or may be rejiggering existing code.  Showing them extra stuff is fine.
