### ISSUE TITLE
Proposal: allow nameof(default(SomeType).SomeField)

### ISSUE THREAD

**Issue by rstarkov** [dotnet/roslyn#8324]
If there is no local of the required type already available to use `nameof` on, one is forced to declare a dummy local of that type or to instantiate the type.

`default(SomeType)` looks like a natural work-around for this scenario. Unfortunately C# as it stands today does not allow this, reporting an error and a warning:

* Error CS8082: Sub-expression cannot be used in an argument to nameof.
* Warning CS1720: Expression will always cause a System.NullReferenceException because the default value of 'SomeType' is null

Perhaps allowing `default` in this context is a simple enough work-around.

**Comment by Timwi** [comment]
... or just allow nameof(SomeType.SomeField) even for instance members?

**Comment by rstarkov** [comment]
@Timwi, turns out that is already supported. Apologies.
