### ISSUE TITLE
Add error preview to encapsulatefield code action

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#8325]
in some error cases, encapsulte field will show entry in the lightbulb but when applied it will do nothing and there will be no preview.

encapsulatefield codeaction should override GetOperationsAsync and return PreviewOperation with an error messsage in it.

ex)

``` C#
class A
{
public int s = "aaa"; | <= caret
public int s = "aaa";
}
```

**Comment by CyrusNajmabadi** [comment]
Haven't heard any feedback on this.  No need to do this.
