### ISSUE TITLE
‘Edit | Refactor | Encapsulate Field’ does not work if the cursor is before the field on the same line separated by whitespace

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#8328]
This is regressed form Dev12 Update 4.
1.       Create a C# console application with the following.

``` C#
class Program
{
    string someField;
    static void Main(string[] args)
    {
    }
}
```
1.       Move the cursor to the line with someField in the first column so that there is space between the cursor and ‘string’.
2.       Invoke ‘Edit | Refactor | Encapsulate Field’

Expected: A suggestions pops up asking you to encapsulate someField.

Actual: A dialog pops up with the following text: ‘Please select the definition of the field to encapsulate.’

**Comment by CyrusNajmabadi** [comment]
Closing out.  This is incredibly minor and we haven't gotten any customer feedback on this.
