### ISSUE TITLE
Intellisense filtering with no matches is worse than Dev12

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#8330]
Description: Invoking Intellisense with <ctrl><space> sometimes positions farther from the result in the list than with VS 2013 

Repro Steps:Declare a variable, e.g "var YearIncome = 0;" 
Type somewhere in the same method "yo". Press escape to remove the Intellisense list. 
Type <ctrl><space> to invoke the Intellisense list again: you are positionned at the top of the list, while it was in the "y" with previous versions.

**Comment by CyrusNajmabadi** [comment]
Need info from community if there's actually an issue here.
