### ISSUE TITLE
The colors of ‘Punctuation’  and ‘Brace Matching’ overlap

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#8335]
Ported from internal bug 114176
1.       Launch VS .
2.       Create a C# console application.
3.       Go to Tools->Options->Environment->Fonts and Colors->Display items-> Brace Matching  and set Item background to ‘Blue’ .
4.       Go to Tools-> Options->   Environment-> Fonts and Colors->Display items-> Punctuation and set Item background to ‘Yellow’ .
5.       Open file ‘Program.cs’ and put caret at the end of method       Main, just behind the brace.

Expected result:
The background color of the matching braces is Blue.

Actual result:
The background color of the matching braces is Yellow, see the screenshot below.

![image](https://cloud.githubusercontent.com/assets/235241/12761053/5b22c428-c99e-11e5-955e-f8db41057570.png)

Notes:
1.       Both the color settings of Punctuation and Brace Macthing do not work in C++ and JS.
2.       Visual Studio 2013 Update 5 doesn’t  have the setting of  ‘Punctuation’  or Brace Matching.

**Comment by DustinCampbell** [comment]
Weird. It looks like the classification is appearing above the marker tag. Is it on the wrong adornment layer? I'm somewhat surprised that marker tags don't fill the same space as a classification tag.

**Comment by CyrusNajmabadi** [comment]
It's been 7 years without this being an issue.  Going to close this out as we are unlikely to change this absent a clear customer need/ask.
