### ISSUE TITLE
Completion list invokes the formatter in unexpected cases, likely indicating a bug.

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#8337]
[Completion code invokes formatter](https://github.com/dotnet/roslyn/blob/a4e375b95953e471660e9686a46893c97db70b0e/src/EditorFeatures/Core/Implementation/IntelliSense/Completion/Controller_Commit.cs#L132)

when and why do we do this? 

In case like below, typing semicolon at `$$`, triggers formatter twice - once from completion and once from formatting command handler :
```C#
string Property { get$$
```

Can we not trigger formatting from completion, or if we have to, can we do better?

**Comment by DustinCampbell** [comment]
Completion invokes the formatter to ensure that various preprocesser constructs, such as `#if` or `#region` get left-aligned correctly when committed from the list.

**Comment by balajikris** [comment]
That gives me a feeling that it is not expected to invoke in the above case, is that right?

**Comment by DustinCampbell** [comment]
Correct -- there's a bit that gets set in the CompletionItem [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Completion/CompletionItem.cs,b8145a03579cf9df). When set, that's supposed to be when the completion controller formats.

**Comment by balajikris** [comment]
Hmm, it doesn't seem to be the only controlling bit. It is OR -ed with isCommitChar && formatting supported for that char [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/Intellisense/Completion/Controller_Commit.cs,126), hence the format on semi-colon.

**Comment by DustinCampbell** [comment]
Yuck. That smells very fishy.

**Comment by balajikris** [comment]
Thanks for confirming :smiley: I'll tag it with a bug label and let triage take a look then.

**Comment by balajikris** [comment]
@CyrusNajmabadi did the work that decouples completion and formatting. This bug can now be closed.
