### ISSUE TITLE
Review and consolidate helpers that determine the span or range to format.

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#8338]
We have multiple methods in two classes `FormattingRangeHelper` and `CommonFormattingHelpers` to determine the span/range to format for the formatter. These methods are consumed from various formatting API. While the span to format may indeed be different for various scenarios, it'd be instructive to understand and consolidate them if possible.
##### Helpers:
1. [FindAppropriateRange](https://github.com/dotnet/roslyn/blob/8f01cb099f9b7faf26f6acf1a2c68ec2e98e0ea5/src/Workspaces/CSharp/Portable/Utilities/FormattingRangeHelper.cs#L20)
2. [GetFormattingSpan](https://github.com/dotnet/roslyn/blob/f1af7930c8b5cc9433720957facd2abf0218dd9e/src/EditorFeatures/Core/Shared/Utilities/CommonFormattingHelpers.cs#L14)
3. [GetFormattingSpan overload](https://github.com/dotnet/roslyn/blob/f1af7930c8b5cc9433720957facd2abf0218dd9e/src/EditorFeatures/Core/Shared/Utilities/CommonFormattingHelpers.cs#L27)

**Comment by CyrusNajmabadi** [comment]
Unlikely to do anything here.
