### ISSUE TITLE
Connect: Quick Action "Generate class for <class> in <Project1.Folder> (in new file)" places file in root folder.

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#8342]
Porting from:
https://github.com/aspnet/Tooling/issues/189

When using the Quick Action to generate a new class in a new file, the file is created in the root project folder, even if the source is in a folder. 

Steps to reproduce: 
1. Create a Asp.Net Core 1.0 Web Site.
2. On the root folder, add a new folder called "Anything". 
3. Add a class file to the Anything folder. 
4. Inside the class file, create a property "SomeProperty" of type "NewClass". 
5. Call Quick Action to create NewClass in new file. 

**Expected**: NewClass.cs will be nested in the Anything folder. 
**Actual**: NewClass.cs is placed in the root folder.

**Comment by Pilchie** [comment]
This doesn't repro on the new .NET Core projects in VS 2017.
