### ISSUE TITLE
`IEventAssignmentExpression` should contains an `IEventReferenceExpression`

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#8346]
Right now, it is defined to directly contain event symbol and event instance. @JohnHamby mentioned this is intentional since the bound tree makes it difficult to provide operation this way. We need to spend a little more time to decide if this is possible to fix.

Update with proposed interface:

```cs

    /// <summary>
    /// Represents a binding of an event.
    /// </summary>
    /// <remarks>
    /// This interface is reserved for implementation by its associated APIs. We reserve the right to
    /// change it in the future.
    /// </remarks>
    public interface IEventAssignmentExpression : IOperation
    {
        /// <summary>
        /// Event being bound.
        /// </summary>
        IEventReferenceExpression Event { get; }
 
        /// <summary>
        /// Handler supplied for the event.
        /// </summary>
        IOperation HandlerValue { get; }
 
        /// <summary>
        /// True for adding a binding, false for removing one.
        /// </summary>
        bool Adds { get; }
    }
```

**Comment by genlu** [comment]
@jinujoseph Have we discussed this? I saw you linked this to the meta issue above but can't find it there.

**Comment by jinujoseph** [comment]
cc / @CyrusNajmabadi  
No this was not discussed yet. Taggging for discussion next week.

**Comment by CyrusNajmabadi** [comment]
Yes, we should do this.  It should be simple to do now that we're creating our own operation nodes.  It doesn't matter what the bound nodes do internally.
