### ISSUE TITLE
`LambdaExpression` operation missing when a lambda expression is used for delegate creation

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#8347]
For example, in the following code snippet, `(s, e) => { }` is not recogonized as a `LambdaExpression`:

``` cs
Mumble += new MumbleEventHandler((s, e) => { });
```

It is mistakenly recognized as a `MethodBindingExpression`.

There's a testscase for this bug:
src\compilers\csharp\test\semantic\diagnostics\operationanalyzertests.cs

**Comment by mavasani** [comment]
Dupe of https://github.com/dotnet/roslyn/issues/8884#issue-134680222.

Will be fixed by https://github.com/dotnet/roslyn/pull/19307
