### ISSUE TITLE
Test ref locals & ref returns against IDE features

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#8350]
PR: https://github.com/dotnet/roslyn/pull/8030
Test Plan Template: https://github.com/dotnet/roslyn/issues/8389

Completion has been updated, with tests, by the compiler team.

**Comment by dpoeschl** [comment]
[ This post is a work in progress - things may be added/removed/updated. ]

:white_check_mark: = Tested & Approved (possibly with linked bugs)
:x: = Merge Blocking
:free: = No Expected Impact

### Internal Dogfooding Requirements
| Feature | Signoff |
| --- | --- |
| ****Typing**** | |
| Feature Flag functional | |
| Completion <br />| |
| &nbsp;&nbsp;&nbsp;&nbsp;Formatting | |
| &nbsp;&nbsp;&nbsp;&nbsp;Automatic Brace Completion (*C# only*) | |
| &nbsp;&nbsp;&nbsp;&nbsp;Indentation | |
| **Navigating** | |
| &nbsp;&nbsp;&nbsp;&nbsp;Go To Definition | |
| &nbsp;&nbsp;&nbsp;&nbsp;Find All References | |
| &nbsp;&nbsp;&nbsp;&nbsp;Go To Implementation | |
| **Viewing** | |
| &nbsp;&nbsp;&nbsp;&nbsp;Colorization | |
| &nbsp;&nbsp;&nbsp;&nbsp;Error Squiggles | |

### IDE Features
| Feature | Signoff |
| --- | --- |
| Signature Help | |
| Quick Info | |
| Outlining | |
| Brace Matching (*C# only*) | |
| Highlight References | |
| Peek | |
| Navigation Bars | |
| Metadata As Source | |
| Navigate To | |
| Go to Next/Previous Method | |
| Solution Explorer Pivots | |
| Call Hierarchy | |
| Code Lens | |
| Project System | |
| Debugger IntelliSense | |
| Code Model / Class Designer | |
| Line Separators | |
| Object Browser / Class View | |
| Lightbulb | |
| Options | |

### Code Transformations
| Feature | Signoff |
| --- | --- |
| **Refactoring with UI** | |
| &nbsp;&nbsp;&nbsp;&nbsp;Inline Rename | |
| &nbsp;&nbsp;&nbsp;&nbsp;Change Signature UI | |
| &nbsp;&nbsp;&nbsp;&nbsp;Extract Interface UI | |
| &nbsp;&nbsp;&nbsp;&nbsp;Generate Type UI | |
| **Refactorings** | |
| &nbsp;&nbsp;&nbsp;&nbsp;Rename Tracking | |
| &nbsp;&nbsp;&nbsp;&nbsp;Extract Method | |
| &nbsp;&nbsp;&nbsp;&nbsp;Introduce Variable | |
| &nbsp;&nbsp;&nbsp;&nbsp;Organize Usings | |
| **Fixes** | |
| &nbsp;&nbsp;&nbsp;&nbsp;Add Using | |
| &nbsp;&nbsp;&nbsp;&nbsp;Generate Local/Field | |
| &nbsp;&nbsp;&nbsp;&nbsp;Generate Constructor | |
| &nbsp;&nbsp;&nbsp;&nbsp;Implement Interface | |
| &nbsp;&nbsp;&nbsp;&nbsp;Implement IDisposable | |
| &nbsp;&nbsp;&nbsp;&nbsp;Implement Abstract Class | |
| &nbsp;&nbsp;&nbsp;&nbsp;Convert "Get*" Methods to Properties | |
| &nbsp;&nbsp;&nbsp;&nbsp;Encapsulate Field | |
| **Code Gen** | |
| &nbsp;&nbsp;&nbsp;&nbsp;Event Hookup on Tab (*C# only*) | |
| &nbsp;&nbsp;&nbsp;&nbsp;Snippets | |
| &nbsp;&nbsp;&nbsp;&nbsp;End Construct Generation (*VB only*) | |
| &nbsp;&nbsp;&nbsp;&nbsp;Automatic End Construct Update (*VB only*) | |

### Project System & External Integration
(*Any changes to the runtime will require much more testing in this category*)

| Integration | Signoff |
| --- | --- |
| Linked Files (all flavors) | |
| .NET Core "Console Application (Package)" | |
| Razor | |
| WPF | |
| TypeScript | |

**Comment by dpoeschl** [comment]
:white_check_mark: = Tested & Approved (possibly with linked bugs)
:x: = Merge Blocking
:free: = No Expected Impact

<a name="testfootnote1"><sup>1</sup></a> Feature updated by compiler team, with appropriate unit tests.
<a name="testfootnote2"><sup>2</sup></a> Feature requires more complete testing by IDE team. (?)

## <a name="mergesignoff">Internal Dogfooding Requirements (Merge Signoff)</a>
Critical IDE features in the areas of **Typing**, **Navigating**, and **Viewing** must function as expected. Any non-trivial issues in these areas blocking language feature merging.
*All feature descriptions and testing suggestions are merely examples. Each language feature should be carefully considered independently against each IDE feature to find interesting intersections*

| Category | Feature | Signoff/Notes |
| --- | --- | --- |
| **Enable/Disable** | **Feature Flag** <br />*Add Description* | |
| **Typing** | **Completion**<sup>[1](#testfootnote1)</sup> <br />- Typing new keyword/construct names<br />- Dotting off of new constructs | |
| | **Formatting** <br />- Spacing in and around new constructs<br />- Spacing options<br />- Format Document command | |
| | **Automatic Brace Completion** (*C# only*) <br />- Auto-insert close brace<br />- Shift+Enter commit of pending brace completion | |
| | **Indentation** <br />- Typing `Enter` in an unfinished statement indents the next line | |
| **Navigating** | **Go To Definition** <br />- F12 from callsites to definition | |
| | **Go To Implementation** <br />- Jump from virtual members to their implementations<br />- Jump from inheritable types to their implementations | |
| | **Find All References** <br />- Lists references to a symbol in "Find Symbol Results" window<br />- Shows results in hierarchy grouped by definition | |
| **Viewing** | **Colorization** <br />- Keywords, literals, and identifiers colored appropriately in code | |
| | **Error Squiggles** <br />- Squiggles appear as expected on reasonable spans | |

##  <a name="featuresignoff">IDE Features (Feature Signoff)</a>
For the remaining set of IDE features, only crashes and asserts are considered blocking. However, *all* issues discovered must be filed and linked here.
*All feature descriptions and testing suggestions are merely examples. Each language feature should be carefully considered independently against each IDE feature to find interesting intersections*

### Code Transformations
| Category | Feature | Signoff/Notes |
| --- | --- | --- |
| **Refactoring with UI** | **Inline Rename**<br />*Add Description* | |
| | **Change Signature UI**<br />*Add Description* | |
| | **Extract Interface UI**<br />*Add Description* | |
| | **Generate Type UI**<br />*Add Description* | |
| **Refactorings** | **Rename Tracking**<br />*Add Description* | |
| | **Extract Method**<br />*Add Description* | |
| | **Introduce Variable**<br />*Add Description* | |
| | **Organize Usings**<br />*Add Description* | |
| **Fixes** | **Add Using**<br />*Add Description* | |
| | **Generate Local/Field**<br />*Add Description* | |
| | **Generate Constructor**<br />*Add Description* | |
| | **Implement Interface**<br />*Add Description* | |
| | **Implement IDisposable**<br />*Add Description* | |
| | **Implement Abstract Class**<br />*Add Description* | |
| | **Convert "Get*" Methods to Properties**<br />*Add Description* | |
| | **Encapsulate Field**<br />*Add Description* | |
| **Code Gen** | **Snippets**<br />*Add Description* | |
| | **Event Hookup on Tab** (*C# only*)<br />*Add Description* | |
| | **End Construct Generation** (*VB only*)<br />*Add Description* | |
| | **Automatic End Construct Update** (*VB only*)<br />*Add Description* | |

### IDE Features
| Feature | Signoff/Notes |
| --- | --- |
| **Signature Help**<br />*Add Description* | |
| **Quick Info**<br />*Add Description* | |
| **Outlining**<br />*Add Description* | |
| **Brace Matching** (*C# only*)<br />*Add Description* | |
| **Highlight References**<br />*Add Description* | |
| **Peek**<br />*Add Description* | |
| **Navigation Bars**<br />*Add Description* | |
| **Metadata As Source**<br />*Add Description* | |
| **Navigate To**<br />*Add Description* | |
| **Go to Next/Previous Method**<br />*Add Description* | |
| **Solution Explorer Pivots**<br />*Add Description* | |
| **Call Hierarchy**<br />*Add Description* | |
| **Code Lens**<br />*Add Description* | |
| **Project System**<br />*Add Description* | |
| **Debugger IntelliSense**<br />*Add Description* | |
| **Code Model / Class Designer**<br />*Add Description* | |
| **Line Separators**<br />*Add Description* | |
| **Object Browser / Class View**<br />*Add Description* | |
| **Lightbulb**<br />*Add Description* | |
| **Options**<br />*Add Description* | |

### Project System & External Integration
(Any changes to the runtime will require much more testing in this category)
*All feature descriptions and testing suggestions are merely examples. Each language feature should be carefully considered independently against each IDE feature to find interesting intersections*

| Integration | Signoff/Notes |
| --- | --- |
| **Linked Files (all flavors)**<br />*Add Description* | |
| **.NET Core "Console Application (Package)"**<br />*Add Description* | |
| **Razor**<br />*Add Description* | |
| **WPF**<br />*Add Description* | |
| **TypeScript**<br />*Add Description* | |

## <a name="featuresuggestions">New Feature Suggestions</a>
What refactorings, fixes, code transformations, or other in-editor experiences would enhance this language feature?

| Feature Name | Description |
| --- | --- |
| ? | ? |

**Comment by DustinCampbell** [comment]
Removing urgency-soon label since the bulk of the actual test work and bug generation is done.

**Comment by dpoeschl** [comment]
Closing out, since this really is done. I have a few spots in the matrix to fill in above based on my OneNote notes, but nothing of consequence.
