### ISSUE TITLE
Test binary literals

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#8351]

**Comment by jasonmalinowski** [comment]
Things to test:

- [ ] constants shown in quick info, signature help
- [ ] constants from both source and metadata
- [ ] intellisense triggering after . after a literal

**Comment by jasonmalinowski** [comment]
Testing is completed, bugs found are mentioning this parent bug. Notably, #8436 is pretty nasty.

**Comment by DustinCampbell** [comment]
@jasonmalinowski - did you test this for C# too? I thought this was one of the first things @khyperia implemented as part of his internship.

**Comment by jasonmalinowski** [comment]
@DustinCampbell: yes, C# was tested too. I've updated #8440 to clarify that applies to both.
