### ISSUE TITLE
ParseOptions.CommonWithKind should be marked EditorBrowsable.Never

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#8353]
The rest of the Common* ones are private; this seems unexpected. It's unclear to me if this shipped or not.

**Comment by jaredpar** [comment]
This was shipped as public in 1.0.

**Comment by jasonmalinowski** [comment]
Can we at least hide it with EditorBrowsable.Never, or [Obsolete] or something?

**Comment by jaredpar** [comment]
I'd be fine with `EditorBrowsable`.

**Comment by jasonmalinowski** [comment]
Reactivate then to track that.

**Comment by eriawan** [comment]
Hi @jasonmalinowski and @jaredpar ,

Since this "up for grabs" is quite here for long, could I take the initiative to create a PR for this? Or has this issue already been solved?

**Comment by jasonmalinowski** [comment]
@jaredpar owns this area, so it's up to him, but I have no problem with it. We do use GitHub as our primary issue tracker, so being active here means we think it's still a problem.

**Comment by eriawan** [comment]
@jasonmalinowski ok, thanks for your quick response :+1: 

@jaredpar could I grab this and make a PR?

**Comment by eriawan** [comment]
@jaredpar 

The related PR #10304 has been merged. Can we close this issue?

cc @jasonmalinowski
