### ISSUE TITLE
Roslyn.Compilers.CSharp.Emit.UnitTests.dll (ConditionalMemberAccessRace002) fails intermittantly...

### ISSUE THREAD

**Issue by KevinH-MS** [dotnet/roslyn#836]
I'm seeing the following in several builds today:

Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.CodeGenShortCircuitOperatorTests.ConditionalMemberAccessRace002 [FAIL]
   System.CannotUnloadAppDomainException : Error while unloading appdomain. (Exception from HRESULT: 0x80131015)
   Stack Trace:
      at System.AppDomain.Unload(AppDomain domain)
      C:\Builds\Roslyn\Main-PerCheckin-Release\src\Open\src\Test\Utilities\HostedRuntimeEnvironment.cs(422,0): at Microsoft.CodeAnalysis.Test.Utilities.HostedRuntimeEnvironment.System.IDisposable.Dispose()
      C:\Builds\Roslyn\Main-PerCheckin-Release\src\Open\src\Test\Utilities\CommonTestBase.CompilationVerifier.cs(116,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompilationVerifier.Emit(String expectedOutput, IEnumerable`1 manifestResources, Boolean peVerify, SignatureDescription[] expectedSignatures)
      C:\Builds\Roslyn\Main-PerCheckin-Release\src\Open\src\Test\Utilities\CommonTestBase.cs(329,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.Emit(CommonTestBase test, Compilation compilation, IEnumerable`1 dependencies, TestEmitters emitOptions, IEnumerable`1 manifestResources, SignatureDescription[] expectedSignatures, String expectedOutput, Action`2 assemblyValidator, Action`2 symbolValidator, Boolean collectEmittedAssembly, Boolean verify)
      C:\Builds\Roslyn\Main-PerCheckin-Release\src\Open\src\Test\Utilities\CommonTestBase.cs(220,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerify(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, TestEmitters emitOptions, Action`2 sourceSymbolValidator, Action`2 assemblyValidator, Action`2 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Boolean collectEmittedAssembly, Boolean verify)
      C:\Builds\Roslyn\Main-PerCheckin-Release\src\Open\src\Test\Utilities\CommonTestBase.cs(155,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerify(String[] sources, IEnumerable`1 additionalRefs, IEnumerable`1 dependencies, TestEmitters emitOptions, Action`2 sourceSymbolValidator, Action`2 assemblyValidator, Action`2 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, CompilationOptions options, Boolean collectEmittedAssembly, Boolean verify)
      C:\Builds\Roslyn\Main-PerCheckin-Release\src\Open\src\Test\Utilities\CommonTestBase.cs(119,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerify(String source, IEnumerable`1 additionalRefs, IEnumerable`1 dependencies, TestEmitters emitOptions, Action`2 sourceSymbolValidator, Action`2 assemblyValidator, Action`2 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, CompilationOptions options, Boolean collectEmittedAssembly, Boolean verify)
      C:\Builds\Roslyn\Main-PerCheckin-Release\src\Open\src\Compilers\Test\Utilities\CSharp\CSharpTestBase.cs(79,0): at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CompileAndVerify(String source, IEnumerable`1 additionalRefs, IEnumerable`1 dependencies, TestEmitters emitOptions, Action`1 sourceSymbolValidator, Action`2 assemblyValidator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, CompilationOptions options, Boolean collectEmittedAssembly, Boolean verify)
      C:\Builds\Roslyn\Main-PerCheckin-Release\src\Open\src\Compilers\CSharp\Test\Emit\CodeGen\CodeGenShortCircuitOperatorTests.cs(4244,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.CodeGenShortCircuitOperatorTests.ConditionalMemberAccessRace002()

**Comment by gafter** [comment]
Dup of #760
