### ISSUE TITLE
Cannot restore packages

### ISSUE THREAD

**Issue by BrisingrAerowing** [dotnet/roslyn#8363]
When I try to restore the packages so I can build, I get an error stating that NuGet cannot find a sha512 file for ManagedEsent and promptly quits. I am not sure if this is a bug here or with NuGet itself.

All I want to build is the scripting system, but having to open the full solution just for that is a bit of a pain, since this issue doesn't let anything build.

**Comment by davkean** [comment]
Can you post the exact error?

**Comment by BrisingrAerowing** [comment]
I'll try again and see what I get.

**Comment by BrisingrAerowing** [comment]
```text
Restoring packages: Toolsets
WARNING: Dependency specified was Microsoft.Build.Mono.Debug (≥ 14.1.0-prerelease) but ended up with Microsoft.Build.Mono.Debug 14.1.0.
WARNING: Dependency specified was Microsoft.Build.Mono.Debug (≥ 14.1.0-prerelease) but ended up with Microsoft.Build.Mono.Debug 14.1.0.
Restoring packages: Samples
Restoring packages: Roslyn (this may take some time)
Could not find a part of the path 'C:\Users\Zachary\.nuget\packages\ManagedEsent\1.9.2\ManagedEsent.1.9.2.nupkg.sha512'.
Restore failed with ERRORLEVEL 1
```

**Comment by BrisingrAerowing** [comment]
I just noticed that the nuget tool is looking for the file under my user directory, not the project directory. This makes me think that this is a NuGet bug.

I have the project on my E: drive, not the C: drive.

**Comment by BrisingrAerowing** [comment]
The directory also has the extra zero in it. I just copied it to 1.9.2 which made the process work correctly.

**Comment by davkean** [comment]
What OS is this?

**Comment by BrisingrAerowing** [comment]
Windows 10 x64. I don't have any earlier versions to test on.

**Comment by davkean** [comment]
Are you still running into issues? No matter how much I try I cannot repro this.

**Comment by davkean** [comment]
Closing this issue, please open another issue if you are still having trouble.
