### ISSUE TITLE
Treat typeof, sizeof and default expression different from Method Invocation expression

### ISSUE THREAD

**Issue by basoundr** [dotnet/roslyn#8366]
Treat typeof, sizeof and default expression different from Method Invocation expression when applying formatting rules.

The option _Set spacing for method calls -> Insert space within argument list parentheses_ should not affect typeof, sizeof and default expressions

**Comment by basoundr** [comment]
From the customer, R# treats these expressions different from Method invocations.

**Comment by Michael-DST** [comment]
Wow... great, thank you for opening this issue @basoundr!  I would also like to share my appreciation for the Visual Studio team there for creating a feedback system that you actually use. :)  Usually it feels with MSFT products that feedback goes into a black hole and never heard from again, but in this case you and your team were listening and it culminated into this issue.  Really cool stuff!  I really feel that the Visual Studio team along w/ Azure are two of the best groups in MSFT right now, and this does nothing but support that claim.

Anyways, enough of the praise. :P I wanted to provide a screenshot of what these options look like in R#, for context:
![](http://content.screencast.com/users/Mike-EEEE/folders/Jing/media/34f6129c-06b8-4585-84fa-b1e8ce5d5323/2016-02-03_1237.png)

Additionally, I would also like to shamelessly promote an idea (hey, I was buttering you up for some reason!) [that I feel would really solve a lot of these issues in the current development workflow process with Visual Studio (and incidentally solve a lot of arguments in the workplace)](http://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/10020390-enable-roslyn-powered-code-views).  

I see a future where these types of issues are a thing of the past, and each developer has individual, full control over their formatting preferences completely separate from what gets ultimately saved in the code file and checked into source control.  When the file does get saved, it gets saved in a consistent format that can then be used to view in a raw format and/or source control (I recommend 100% StyleCop-compliance as the initial file format in the idea).

Thank you for any consideration/support!

**Comment by CyrusNajmabadi** [comment]
Haven't heard anything on this in nearly 10 years.  Unlikely to make any changes here unless we did a new formatting engine.  Closing out.
