### ISSUE TITLE
NavigateTo/FAR caches should be hooked up to "Low VM" warning

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#8369]
NavigateTo and FAR cache some data in `SyntaxTreeInfo`. These caches are only used when those features are invoked, so we should consider flushing them when we receive the "Low VM" warning.

**Comment by rchande** [comment]
FYI @KevinH-MS. What milestone do you think this belongs in?

**Comment by KevinH-MS** [comment]
Thanks!  We should try to do this in 1.2 (should be a relatively simple change, and we don't want to be introducing new OOMs with large solutions).

**Comment by DustinCampbell** [comment]
@rchande, @KevinH-MS -- who should this be assigned to? We've got several hundred bugs to fix in 1.2. If this is tenet-affecting, I'd like to get it assigned out.

**Comment by KevinH-MS** [comment]
@DustinCampbell as long as we didn't change anything that will cause these caches to hang around longer in Update 2, then this can go to Update 3.  Thanks

**Comment by rchande** [comment]
@DustinCampbell @Pilchie @KevinH-MS @mavasani Do we _need_ to do this for RTM?

**Comment by mavasani** [comment]
@rchande Have received any performance traces/reports showing memory usage from these features for  Low VM situations? Otherwise, I'd given go even a step further and close the issue and do this work when we get reports.

**Comment by CyrusNajmabadi** [comment]
> Otherwise, I'd given go even a step further and close the issue and do this work when we get reports.

1. I don't believe any reports have been received pointing to this data.
2. This data is now stored out of proc.  So the impact on the VS solution should be minimal. 

Closing out.
