### ISSUE TITLE
VB.NET: Short fields are ignored in IDE0003 code fix

### ISSUE THREAD

**Issue by ehasis** [dotnet/roslyn#8381]
The VB.NET IDE editor does not provide IDE0003 (Name can be simplified) code fix for fields or properties declared as Short (System.Int16).
```vb
Class Class1
    Private field1 As Short
    Private field2 As Integer

    Public Sub New()
        Me.field1 = 0 ' IDE0003 fix not available for the Me keyword
        Me.field2 = 0
    End Sub
End Class
```
Tested in Visual Studio 2015 Update 1.

**Comment by DustinCampbell** [comment]
Hmmm... this only seems to happen when Option Strict is On. Amusingly, I think this is related to the fix for #2560.
