### ISSUE TITLE
Proposal: Throw exception in null-coalescing operator

### ISSUE THREAD

**Issue by lachbaer** [dotnet/roslyn#8399]
I think that there are often times where one would like to throw an exception if a value is `null`, like in
```C#
public string {
    get { return _myString; }
    set {
        if (value!=null) _myString = value;
        throw new ArgumentNullException();
    }
}
```
When allowing to throw an exception in the `??` Operator then things could be less verbose, but also quite understandable to everyone.
```C#
public string {
    get { return _myString; }
    set { _myString = value ?? throw new ArgumentNullException(); }
}
```

**Comment by alrz** [comment]
Dupe of #5143 (see 3rd point under "allowed in only the following contexts").

**Comment by lachbaer** [comment]
Ah, I see that it is already completely written down in https://github.com/dotnet/roslyn/blob/future/docs/features/patterns.md.
(Did my research, but didn't see the forrest because of all the trees ;-)
