### ISSUE TITLE
Should generate "Catch ex As System.Exception" when no Imports

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#841]
1. Create VB project
2. Remove any imported namespaces from project properties
3. In Main(), type "Try<enter>"

Expected: "ex As System.Exception"

Actual: "ex As Exception"

```
Sub Main()
    Try
    Catch ex As Exception
    End Try
End Sub
```

**Comment by Pilchie** [comment]
While true, I expect the number of VB Projects that don't have Imports System is low enough to not worry about too much.

**Comment by CyrusNajmabadi** [comment]
Indeed.  especially as 'System' is just auto-imported.  Even removing that import is very difficult.  This just goes into the "won't ever fix" category.
