### ISSUE TITLE
Proposal: Return arrays in the format of initialized arrays

### ISSUE THREAD

**Issue by IshamMohamed** [dotnet/roslyn#8419]
Array initialization is a cool feature in C# meanwhile when we write a methods that returns an array, we always have to define a data (array_ inside the method, build the array with array elements and return it. But this data assignment is not always necessary if we dont use arrays. Instead of 

```
public int AddNumbers(int number1, int number2)
{
    int sum = number1 + number2;
    return sum;
}
```

we can use,

```
public int AddNumbers(int number1, int number2)
{
    return number1+number1;
}
```

but in array's case we cant use this. Somehow we need to do something like the below

```
public string[] Method()
{
    string[] array = new string[2];
    array[0] = "THANK";
    array[1] = "YOU";
    return array;
}
```

My proposal is, C# should be able to support returning arrays in the format of initialized arrays, 

```
public string[] Method()
{
    return { "THANK", "YOU" };
}
```

As I see this feature will be very cool and make developers bit more efficient while coding.

**Comment by tpetrina** [comment]
You can always write:
```csharp
	public string[] Method()
	{
		return new[] { "THANK", "YOU" };
	}
```

**Comment by bondsbw** [comment]
Interesting.  Maybe it can be used in other cases, not just return values.  Could ```{ expr, expr, ... }``` become shorthand for ```new [] { expr, expr, ... }``` in all cases?

```c#
public class MyClass
{
    public string[] Colors = { "Red", "Green", "Blue" };
    public int Foo()
    {
        var ints = { 1, 3, 6, 10, 15, 21 };
        return ints.Sum();
    }
}
```

**Comment by Richiban** [comment]
Interestingly enough the {} syntax is allowed if assigning to an explicitly typed variable. The following is legal C#: 

`int[] a = {1, 2, 3, 4, 5};`

I'm not entirely sure why it doesn't work for a return statement.

**Comment by IshamMohamed** [comment]
@bondsbw Exactly that could be another usecase.

**Comment by bondsbw** [comment]
@Richiban Ha, I didn't even realize that was legal.

**Comment by alrz** [comment]
Perhaps this'd be addressed by #6949.

```cs
from i1 in [1, 2, 3, 4, 5]
from i2 in [10, 100, 1000]
select i1*i2
```

**Comment by bondsbw** [comment]
@alrz Regardless of the outcome of that issue, the curly brace syntax is practically already in the language.  Literally the only thing that needs to happen is implicit typing.  I would prefer that happen either way.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
