### ISSUE TITLE
Editing text and not calling GetCompilationAsync causes memory increase

### ISSUE THREAD

**Issue by DavidKarlas** [dotnet/roslyn#8420]
I noticed "memory leak"(notice quotes) in MonoDevelop(Xamarin Studio)...
- 2 projects in solution
- On both projects GetCompilationAsync is called(just to create initial Compilation on which InProgressState will be based)
- Both project have same file linked
- Edit this file 1000x
- During this edits call GetCompilationAsync only in one project but not other(MD doesn't run diagnostics on closed files and doesn't execute code completion on linked documents so it only calls GetCompilationAsync on selected project).

What happens is that project which is not calling GetCompilationAsync will keep all DocumentStates and SyntaxTrees inside ProgressInState since it will just keep adding it [here](https://github.com/dotnet/roslyn/blob/8bd453fbe55ca65cdd3d09ece17d047dc8cd6ea3/src/Workspaces/Core/Portable/Workspace/Solution/Solution.CompilationTracker.cs#L117-L125). This will be all merged and cleared when GetCompilationAsync is called...(hence quotes on memory leak)

What could maybe be done(if it won't cause too much performance impact) is in lines linked above check if same documentId already has TouchDocumentAction and merge this 2 actions into 1. This might be painful because ChangedText would have to merge and also new IncrementallyParseSyntaxTree would have to be called...

**Comment by mattwar** [comment]
This is due to the CompilationTracker queuing up change deltas that are resolved when the compilation is requested.

**Comment by CyrusNajmabadi** [comment]
This is weird.  This is exactly what the BackgroundCompiler type is designed for: https://github.com/dotnet/roslyn/blob/master/src/Features/Core/Portable/Workspace/BackgroundCompiler.cs

Effectively, it keeps track of the actively edited file and will continually ensure that we have an up to date compilation for it. 

@DavidKarlas are you using that type?  if not, can you move to using it?

**Comment by DavidKarlas** [comment]
In 4 years so much has changed... VSMac is much closer to what VSWindows does so, its likely this is not problem anymore...

**Comment by CyrusNajmabadi** [comment]
Great.  Thanks!
