### ISSUE TITLE
Remove WriteCodeFragmentEx

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#8421]
The MSBuild Task `WriteCodeFragment` is non-deterministic in update 1 it emits `DateTime.Now` into the comments:

> https://github.com/Microsoft/msbuild/issues/408 

This bug has already been fixed and will be shipped in update 2.  In the mean time though we are using a custom MSBuild Task that has a corrected version of `WriteCodeFragment` that is deterministic.  Once we move to update 2 in Jenkins and our developer machines we should remove this work around as it will be just cruft in the system.

**Comment by agocke** [comment]
Note: We'll also need to change this for the xplat netcore MSBuild.

**Comment by jasonmalinowski** [comment]
@jaredpar: we're unblocked to fix this, right? Do you want to continue to own it or should we move it to the backlog?

**Comment by jaredpar** [comment]
Can't remove this until we move to MSBuild 15.0 everywhere.

**Comment by jcouv** [comment]
@agocke I see that you removed the usage of `WriteCodeFragmentEx` in `GenerateAssemblyInfo.targets`
(https://github.com/dotnet/roslyn/commit/62b1ad0b0b712fa42f840219269752e06139fe9e#diff-438aef2327a41182a332b2241112065d).
Can this issue be close?

**Comment by agocke** [comment]
Yes!
