### ISSUE TITLE
Seal DiagnosticDescriptor and get rid of the TriggerDiagnosticDescriptor type

### ISSUE THREAD

**Issue by shyamnamboodiripad** [dotnet/roslyn#843]
- Seal DiagnosticDescriptor
- Add Create() methods to match the current public constructors (which I suppose we have to keep public for compat?)
- Introduce an additional DiagnosticDescriptor.CreateTriggerDescriptor() that will create a descriptor that's equivalent to the current TriggerDiagnosticDescriptor (i.e. will attach the WellKnownDiagnosticTags.Trigger to it)

**Comment by shyamnamboodiripad** [comment]
See PR #815 for the discussion that lead to this ask

**Comment by srivatsn** [comment]
This is resolved by #1065
