### ISSUE TITLE
Line commit with binary literals in VB throws exceptions

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#8436]
1. Enable binary literals in a VB project.
2. Write a binary literal.
3. Move off the line.

*Expected:* nicely formatted binary literals
*Actual:* we throw an exception at [this bit of code in the ReduceTokensRewriter](https://github.com/dotnet/roslyn/blob/d6d0eab2adf23865201084f72bb2c1fd7dbd72ef/src/Workspaces/VisualBasic/Portable/CodeCleanup/Providers/ReduceTokensCodeCleanupProvider.vb#L267). We need to add support for binary literals there.

**Comment by jasonmalinowski** [comment]
(This particular issue was of course forseen by @AnthonyDGreen in his commentary to #6543)

**Comment by jasonmalinowski** [comment]
This was found as a part of #8351.

**Comment by DustinCampbell** [comment]
@jaredpar: moving to the compiler. This should be simple to fix.
