### ISSUE TITLE
[PR Available] Ref returns/locals: Change Signature - "ref" not shown in updated signature preview

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#8437]
![image](https://cloud.githubusercontent.com/assets/235241/12863164/af07f38e-cc27-11e5-86f1-6c8d8a9a39d9.png)

**Comment by DustinCampbell** [comment]
Would this get fixed automatically with the fixes to symbol display need for quick info?

**Comment by dpoeschl** [comment]
Probably. I've been trying to file issues for all of these anyway just in case, as a log of things to verify. But maybe that backfires if people try to parallelize the work on them.

**Comment by rchande** [comment]
@dpoeschl Check to see if this was fixed by symbol display changes for ref returns. If not, it's a minor display bar that probably doesn't meet the bar for 2.0.
