### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by Melab** [dotnet/roslyn#844]
I'm afraid that it is unclear to me on what I need to do to build this. There are no explicit instructions that say what I need to do. Is this meant to be compiled?

**Comment by DustinCampbell** [comment]
Check out this Wiki page:

[Building, Testing and Debugging](https://github.com/dotnet/roslyn/wiki/Building%20Testing%20and%20Debugging)

It still needs updated for Visual Studio 2015 CTP 6, which was released yesterday, but it should get you started.

**Comment by Melab** [comment]
Does the Express version work with it?

**Comment by ManishJayaswal** [comment]
No the express version will not work.
