### ISSUE TITLE
Invoking generate member into enum with binary literals doesn't continue to use binary literals in both C# and VB

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#8440]
1. Copy the following into a VB project with binary literals active:
```
Module Module1
    Enum E
        b = &b01
    End Enum

    Sub Main()
        Console.WriteLine(E.c)
    End Sub
End Module
```
2. Go to E.c, 
3. Invoke "generate member"

*Expected:* we generate the new constant with binary literals, like we do for hex literals
*Actual:* we generate it with 2.

*Note:* this reproduces in both C# and VB.

(Found as a part of #8351)

**Comment by DustinCampbell** [comment]
@jaredpar another for the compiler to take a look at.
