### ISSUE TITLE
Ref returns/locals: Introduced Variable - introduced variable is not ref, nor is its initialization

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#8442]
Introduce Variable on the call to `M()` in:

``` C#
class Program
{
    public ref int M()
    {
        return ref M(); // Run Introduce Variable here
    }
}
```

**Expected**:

``` C#
class Program
{
    public ref int M()
    {
        ref var v = ref M();
        return ref v;
    }
}
```

**Actual**:

``` C#
class Program
{
    public ref int M()
    {
        var v = M();
        return ref v;
    }
}
```

**Comment by DustinCampbell** [comment]
@jaredpar moving to compiler for you guys to take a look at. Let us know if you need any help.

**Comment by CyrusNajmabadi** [comment]
Closing out.  introduce-var isn't offered here at all.

![image](https://user-images.githubusercontent.com/4564579/217126430-c943750d-2c8d-4394-80e2-362d9009a37c.png)
