### ISSUE TITLE
Ref returns/locals: Encapsulate Field - encapsulating fields used as ref returns causes attempt to illegally return ref property

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#8444]
Encapsulate field on `x` (either via the command or with the "and use property" variation) in

``` C#
class Program
{
    int x;

    public ref int M()
    {
        return ref x;
    }
}
```

**Expected**: Only update references to reference the property where it is valid to do so. _Maybe_ there's a use for "Encapsulate Field to ref-returning property", but right now I doubt that will be a common enough pattern to offer every time someone wants to encapsulate a field.

``` C#
class Program
{
    int x;

    public int X
    {
        get
        {
            return x;
        }

        set
        {
            x = value;
        }
    }

    public ref int M()
    {
        return ref x; // Still referencing field
    }
}
```

**Actual**: `ref` references to the field are updated to use the property, which is illegal (without making the property ref-returning).

``` C#
class Program
{
    int x;

    public int X
    {
        get
        {
            return x;
        }

        set
        {
            x = value;
        }
    }

    public ref int M()
    {
        return ref X; // CS 8910
    }
}
```

**Comment by CyrusNajmabadi** [comment]
Closing out due to lacak of feedback.
