### ISSUE TITLE
Using binary literals without /features flag still mentions experimental langversion

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#8445]
1. Use C# binary literals in some project that doesn't have the feature flag on.
2. Build it.

*Expected:* I'm told to set it via /features or something
*Actual:* I get:

    error CS8058: Feature 'binary literals' is only available in 'experimental' language version.

Which isn't really true.

**Comment by jasonmalinowski** [comment]
(Found as a part of #8351)

**Comment by jaredpar** [comment]
This is fixed now.  It's tied to the language version.
