### ISSUE TITLE
Ref returns/locals: Quick Info omits "ref" modifier on properties & locals (needs test)

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#8453]
Properties (no `ref`):
![image](https://cloud.githubusercontent.com/assets/235241/12870620/463dc70c-cd03-11e5-891c-e15abf0b4c12.png)

Locals (no `ref`):
![image](https://cloud.githubusercontent.com/assets/235241/12870631/9b4e4276-cd03-11e5-87ea-b6a9812844f6.png)

Methods (`ref` shown): 
![image](https://cloud.githubusercontent.com/assets/235241/12870634/aaf046c0-cd03-11e5-9938-9aaee7621451.png)

**Comment by DustinCampbell** [comment]
@jaredpar -- this falls into the "IDE basics" camp. Perhaps symbol display needs updating? Or, it might be that quick info needs to specify another symbol display flag (i.e. "modifiers")?

**Comment by jcouv** [comment]
Looks like this was fixed already. Probably by @OmarTawfik, maybe as part of https://github.com/dotnet/roslyn/pull/22614

I'll go ahead and close. Thanks

![image](https://user-images.githubusercontent.com/12466233/33788515-a10e34e8-dc27-11e7-9e56-d6f39e8b75e6.png)

![image](https://user-images.githubusercontent.com/12466233/33788524-b2dc676c-dc27-11e7-8cbc-5e0cbd73c7ff.png)

![image](https://user-images.githubusercontent.com/12466233/33788558-e510b62a-dc27-11e7-93af-69c62f4f5df3.png)

**Comment by OmarTawfik** [comment]
@jcouv in that case, I'd suggest we add tests for properties/locals before we close this issue. Not sure if they are covered. My PR was about structs only.

**Comment by jcouv** [comment]
It turns out this was fixed before your PR for structs. 
That PR https://github.com/dotnet/roslyn/pull/14654 did include compiler-level tests.
Thanks

**Comment by jcouv** [comment]
Hum, Chuck's change only covered members that return ref (methods and properties), not locals. Not sure when that was fixed...

**Comment by OmarTawfik** [comment]
We can just keep it opened and add a few tests for this. I think it can be quiet a small "up for grabs" item.

**Comment by CyrusNajmabadi** [comment]
Looks good to me:

![image](https://user-images.githubusercontent.com/4564579/217126567-bc40c9a6-3b3e-4056-af98-89ea801bd8fa.png)
