### ISSUE TITLE
Infrastructure backlog

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#8458]
The infrastructure backlogs have been moved to [GitHub projects with the name Infrastructure in them](https://github.com/dotnet/roslyn/projects?utf8=%E2%9C%93&query=Infrastructure).

**Comment by AdamSpeight2008** [comment]
@jasonmalinowski @davkean  Issue #13236 is `In Progress` see PR#13202

**Comment by jmarolf** [comment]
@AdamSpeight2008 I've update the list to say `In Progress`

**Comment by AdamSpeight2008** [comment]
Thank you, @jmarolf. Shouldn't this list be updated to show those that have been completed or mergred?

**Comment by tannergooding** [comment]
#9379 was completed and removed from the backlog.

**Comment by tannergooding** [comment]
https://github.com/dotnet/roslyn/issues/10414 was completed and removed from the backlog.

**Comment by jaredpar** [comment]
@davkean how should we marked completed items in the list?  Add a check box or just delete them from the table?

**Comment by tannergooding** [comment]
@jaredpar, I've been removing and leaving a comment indicating that is what I did 😄

**Comment by jasonmalinowski** [comment]
@jaredpar Email me. I'll do the boring work of updating, and it also lets me know what's going on.

**Comment by AdamSpeight2008** [comment]
@jasonmalinowski Some of the `In Progress` don't mention an Assignee.

**Comment by jasonmalinowski** [comment]
Yep, they were started, aren't complete, and aren't currently assigned to someone due to conflicting priorities.

**Comment by AdamSpeight2008** [comment]
@jasonmalinowski Maybe indicate `progress blocked`

**Comment by jasonmalinowski** [comment]
Actually, I'm going to get rid of this issue and move over to GitHub projects, since it's actually designed for precisely this scenario. Feel free to use "email me to yell at me to make improvements" as the mechanism until then.
