### ISSUE TITLE
Binaries should be signed with SHA2 certs

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#8459]
We need to move our SHA1 certs -> SHA2 certs as Windows stopped support SHA1 at the start of the year.

Basically, look for all usages of `<AuthenticodeCertificateName>` with a value that is a SHA1 cert, and replace it with a SHA2 equivalent.

The authenticode mapping is here:
``` XML
<?xml version="1.0" encoding="utf-8" ?>
<CertificateMappings>
  <Authenticode>
    <Certificate Name="Microsoft" Cert="401" />
    <Certificate Name="Microsoft400" Cert="400" />
    <Certificate Name="Microsoft402" Cert="402" />
    <Certificate Name="MobileDevice" Cert="30" />
    <Certificate Name="NativeAssembly" Cert="65" />
    <Certificate Name="ExceptionPack" Cert="49" />
   <Certificate Name="Xml94" Cert="94" />
    <Certificate Name="AppxWin81" Cert="300" />
    <Certificate Name="Appx" Cert="320" />
    <Certificate Name="Vsix" Cert="160" />
    <Certificate Name="VsixSHA2" Cert="100040160" />
    <Certificate Name="MicrosoftSHA1" Cert="10006" />
    <Certificate Name="WindowsPhone" Cert="123" />
    <Certificate Name="MicrosoftSHA2" Cert="200" />
    <Certificate Name="Microsoft201" Cert="201" />
    <Certificate Name="MSDynamicCodePublish" Cert="216" />
    <Certificate Name="MSDynamicCodePublishDual" Cert="219" />
    <Certificate Name="WindowsPhone223" Cert="223" />
    <Certificate Name="WindowsPhone623" Cert="623" />
    <Certificate Name="WindowsPhone691" Cert="691" />
    <Certificate Name="MicrosoftWinBlue" Cert="444" />
    <!-- Single Sign -->
    <Certificate Name="Microsoft445" Cert="445" />
    <Certificate Name="Microsoft644" Cert="644" />
    <Certificate Name="Microsoft645" Cert="645" />
    <Certificate Name="MicrosoftWin8WinBlue" Cert="253" />
    <!-- Dual Sign -->
    <Certificate Name="Microsoft253" Cert="254" />
    <!-- 252 w/PH -->
    <Certificate Name="MicrosoftSHA1Win8WinBlue" Cert="255" />
    <!-- Triple Sign -->
    <Certificate Name="PPMicrosoftWin8WinBlue" Cert="553" />
    <Certificate Name="Microsoft553" Cert="554" />
    <Certificate Name="PPMicrosoftSHA1Win8WinBlue" Cert="555" />
    <Certificate Name="Microsoft411" Cert="411" />
    <!-- 401 w/PH -->
  </Authenticode> 
</CertificateMappings>
```

**Comment by davkean** [comment]
We should replace MicrosoftSHA1 -> Microsoft402 and look at our other usages of `<AuthenticodeCertificateName>` to figure out if they are also SHA1

**Comment by CyrusNajmabadi** [comment]
Based on what i have found, we use the following nice names in our projects:

These nice names map as follows:


| Nice name | Certificate # | Certificate |
| --- | --- | --- |
| MicrosoftSHA1 | 10006 | Microsoft Corporation (SHA1 MS Root)<br>Microsoft Corporation (SHA1 MS Root) |
| Microsoft402 | 402 | Microsoft Corporation (SHA2 with SHA1 Hash)<br>Microsoft Corporation (SHA2 with SHA1 Hash) |
| MicrosoftSHA1Win8WinBlue | 255 | Microsoft Corporation (SHA1 Root, SHA2 Root and SHA2 Standard Root)<br>Microsoft Corporation (SHA1 Root, SHA2 Root and SHA2 Standard Root) |
| WindowsPhone623 | 623 | Windows Phone (SHA2 Root)<br>Windows Phone (SHA2 Root) (Windows Phone Production PCA 2012) |

Based on this, it looks like the only one we need to change is MicrosoftSHA1 to Microsoft402.

**Comment by davkean** [comment]
Resolved by: https://github.com/dotnet/roslyn/pull/9037 and https://github.com/dotnet/roslyn-internal/pull/600
