### ISSUE TITLE
Crash in floating-point parser for 1.0e999999999

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#8480]
Visual Studio Update 1 crashes with the floating-point literal 1.0e9999999999

**Comment by leppie** [comment]
Interesting when I tried to compile from the commandline the first time, I got an exception, now I cant replicate... Still crashes VS tough.

**Comment by leppie** [comment]
Look at the callstack, it seems this has been fixed in https://github.com/dotnet/roslyn/commit/27bd018e4a515c3672d89dc9afa8b2426e4df148

**Comment by gafter** [comment]
Yes, fixed along with #6109

**Comment by gafter** [comment]
Verified fixed in Update 2.

**Comment by gafter** [comment]
@leppie needs ten `9`'s in a row to repro the crash, not merely nine of them.
