### ISSUE TITLE
WPF databinding ref-returning properties fails. Should ref-returning members be invokable via reflection?

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#8489]
WPF databinding to ref-returning properties fails at runtime (the app keeps running but the binding fails) with the following message:

```
System.Windows.Data Error: 17 : Cannot get 'RefReturningProperty' value (type 'String&') from '' (type 'MainWindow'). 
        BindingExpression:Path=RefReturningProperty; 
        DataItem='MainWindow' (Name=''); 
        target element is 'Label' (Name=''); 
        target property is 'Content' (type 'Object') 

NotSupportedException:'System.NotSupportedException: ByRef return value not supported in reflection invocation.   <----------------
   at System.Reflection.RuntimeMethodInfo.ThrowNoInvokeException()
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at MS.Internal.Data.PropertyPathWorker.GetValue(Object item, Int32 level)
   at MS.Internal.Data.PropertyPathWorker.RawValue(Int32 k)'
```

Should reflection be updated to allow invocation of ref-returning members? If should, how would the resulting value be observed, and should WPF be able to bind to such properties?

**Comment by dpoeschl** [comment]
@VSadov - Have you had any discussions with the framework about this?

**Comment by DustinCampbell** [comment]
@jaredpar, @MadsTorgersen -- I think this is something to discuss with partners around the framework and tooling. Ref-returns will likely have farther-reaching impact than many of the features we've done in the last couple of years. For example, should reflection support this now? What should the designers (WPF, WinForms, ASP.NET) do with ref-returning properties? Should Entity Framework support them? There are more -- that's just off the top of my head.

**Comment by VSadov** [comment]
The expectations are that the users of ref-returning members will be roughly the same users that now use unsafe/pointers. At least initially.

It seems ok that support in legacy frameworks is limited and can be gradually improved if the feature really takes off.

For example we do not plan to support byref methods in expression trees right away. Any functional addition there will be demand-driven and evaluated on cost/benefits basis. And it is too early to have a sense on that, especially since for now byref members are virtually nonexistent. 
There is a bit of a chicken-egg situation here.

There is definitely something to discuss though.

**Comment by VSadov** [comment]
Reflection failure seems like a bug though. True byref invoke would indeed need a special reflection API, but that method is there to do a regular byval invoke. I'd expect it to eval, read indirect, and return the value. 

They probably did not have any means to properly test the scenario so just prohibited it.

**Comment by gafter** [comment]
I believe the Roslyn action item for this is to engage with the platform team to ensure they have plans to address the scenarios.

**Comment by jaredpar** [comment]
Agree.  There is really nothing we can do here.  It's up to coreclr / corefx to make the decision here.  Do need to raise this as an issue so they can make an informed decision.

**Comment by VSadov** [comment]
Right. This is not fixable on our side.
I will enter a bug for CoreFX. If there is none already.

**Comment by VSadov** [comment]
issue in codefx  - https://github.com/dotnet/corefx/issues/15960
