### ISSUE TITLE
IsKind extension method on SyntaxNode should not check for null.

### ISSUE THREAD

**Issue by pharring** [dotnet/roslyn#849]
Issue #825 sparked a discussion of the IsKind extension methods.
Specifically, [this one] (https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/CSharpExtensions.cs#L29) for C# and [this one] (https://github.com/dotnet/roslyn/blob/master/src/Compilers/VisualBasic/Portable/VisualBasicExtensions.vb#L47) for VB.

Opinion on the thread is that the null checks should be removed so that the extension method throws a NullReferenceException for a null/Nothing SyntaxNode.

However, MattWar warns:
> IsKind doesn't throw because at the time I introduced it there was already an internal extension of the same name that lots of IDE features used, and having it throw caused many of them all to break. I agree that it should throw, but someone's got to find and fix all the call sites that are problematic.

So, this issue is to:
1) Change these two extension methods to throw (easy)
2) Fix up all the problematic callsites to check for null.

Perhaps we could start by renaming "IsKind" to "IsKindOrNull" and go from there.

**Comment by tmat** [comment]
Let's not rename. That will cause too much churn.

**Comment by DustinCampbell** [comment]
FWIW, I tried to make this extension method not throw on null a year or two ago and it was very challenging. There was just too much code depending on it being null-resilient. Now that it's a public API out in the wild, it might be even harder to change.

**Comment by AnthonyDGreen** [comment]
We already made a decision on this. We want the use of this method to be consistent and throw. It should probably throw an explicit ArgumentNullException.

**Comment by jaredpar** [comment]
Had a brief conversation where we considered a variety of solutions to this problem:

``` csharp
// mixed (today behavior)
SyntaxNode node;
node.Kind() == SyntaxKind.None;     // NRE
node.IsKind(SyntaxKind.None);       // false
 
// null tolerant
SyntaxNode node;
node.Kind() == SyntaxKind.None;     // true
node.IsKind(SyntaxKind.None);       // false
 
// null intolerant
SyntaxNode node;
node.Kind() == SyntaxKind.None;     // NRE
node.IsKind(SyntaxKind.None);       // NRE
```

The fully null tolerant scenario has behavior which is simply confusing, too confusing to be our solution.  The full null intolerant solution isn't really feasible at this point.  There is far too much code which depends on the current null tolerant behavior of `IsKind` and it's too late to change it.  Hence we will keep the current mixed behavior.
