### ISSUE TITLE
[Test Failure] xUnit returned error code without errors (+2 more) in prtest/win/dbg/unit32 on PR #8424

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#8491]
PR: [#8424](https://github.com/dotnet/roslyn/pull/8424) *Code Model: Don't crash when adding element, deleting its text and then adding it again* by @DustinCampbell
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/3530/

**Issue 1: xUnit returned error code without errors**
xunit produced no error output but had exit code 1

**Issue 2: Compile Error**

**Issue 3: Test Failures**
There were test failures, see Test Results above.

**Comment by davkean** [comment]
Dupe of https://github.com/dotnet/roslyn/issues/7976
