### ISSUE TITLE
Microsoft.CodeAnalysis.CSharp for dnxcore50

### ISSUE THREAD

**Issue by andschwa** [dotnet/roslyn#8505]
Hello,

When targeting `dnxcore50` on Linux, dotnet-restoring `Microsoft.CodeAnalysis.CSharp` throws an error: `Microsoft.CodeAnalysis.CSharp 1.1.1 is not compatible with DNXCore,Version=v5.0`.

We've worked around this by changing our `project.json` to `frameworks: { "dnxcore50": { "imports": "portable-net45+win8" } }` (and bubbling up that dependency to all the projects which depend on this), but ideally the package would just target `dnxcore50`.

Will this be fixed, or are waiting for the new frameworks standards to be implemented (`netstandard1.4` etc.)?

**Comment by jaredpar** [comment]
This will be fixed.  We're waiting for netstandard to be implemented and then we will include that as one of our target.

**Comment by andschwa** [comment]
Perfect, thanks @jaredpar.

**Comment by jaredpar** [comment]
Sorry, lost track of this issue. The problem should now be fixed as we have the necessary information in our NuGet packages to be a NetStandard application.
