### ISSUE TITLE
netci should use standard dotnet-ci Utilities 

### ISSUE THREAD

**Issue by mmitche** [dotnet/roslyn#8508]
Should be using the standard utilities (and extending where necessary).  This helps with global updates.

**Comment by davkean** [comment]
Can you specific examples?

**Comment by mmitche** [comment]
Take a look at CLI for instance:

https://github.com/dotnet/cli/blob/rel/1.0.0/netci.groovy

Almost every bit of functionality you guys have a function for has a utility function already

**Comment by jasonmalinowski** [comment]
@jaredpar/@mmitche, I know you've done a bunch of work here; is this effectively done?

**Comment by mmitche** [comment]
@jasonmalinowski Yes
