### ISSUE TITLE
EnvDTE80.CodeProperty2.ReadWrite returns always read-write value for VB.NET body-less properties 

### ISSUE THREAD

**Issue by carlos-j-quintero** [dotnet/roslyn#851]
See MS Connect bug report:

EnvDTE80.CodeProperty2.ReadWrite returns always read-write value for VB.NET body-less properties 
https://connect.microsoft.com/VisualStudio/feedback/details/1147941/envdte80-codeproperty2-readwrite-returns-always-read-write-value-for-vb-net-body-less-properties

**Comment by gafter** [comment]
@carlos-j-quintero Can you please explain how this is related to the Roslyn project?

**Comment by carlos-j-quintero** [comment]
Because in VS 2015 the code model of EnvDTE (EnvDTE.ProjectItem.FileCodeModel) has been re-implemented to use Roslyn. See my post:

Code model of EnvDTE using Roslyn internally in VS 2015. Bugs ahead. http://www.visualstudioextensibility.com/2015/01/21/code-model-of-envdte-using-roslyn-internally-in-vs-2015-bugs-ahead/

I have reported other 7 bugs that were fixed by Dustin Campbell, check with him.

**Comment by DustinCampbell** [comment]
Thanks @carlos-j-quintero -- I'll take a look.

@gafter, this is an IDE bug in the VS Code Model.

**Comment by gafter** [comment]
Thanks. Now that I know I'll route these issues in your direction.

**Comment by DustinCampbell** [comment]
Fixed with PR #1174.
