### ISSUE TITLE
Add Using will offer to add metadata references even when reference is invalid for target framework 

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#8516]
- Create class library that references `xunit` nuget package
- Create portable project targeting `Profile328`
- In the `Portable` project add the following code
```C#
namespace Portable
{
    public class Class1
    {
        [fact]
        public void Test()
        {
        }
    }
}
```
- Invoke `Add Using` on `[fact]`

**Expected**
Adding Xunit is not offered because `Profile328` is not compatible with the version of Xunit that is being referenced in the class library project

**Actual**
Xunit is added and the Portable project is not able to build until the user manually removes the refereces.

**Comment by jmarolf** [comment]
**NOTE**: This will be mitigated by `Add Nuget Package` as that will prefer the nuget package over the assembly reference, causing us to reference the correct binaries for our chosen framework

**Comment by jmarolf** [comment]
@CyrusNajmabadi

**Comment by DustinCampbell** [comment]
Cyrus -- will this be better once we have NuGet package references.

**Comment by CyrusNajmabadi** [comment]
Yes.  This should be better.
