### ISSUE TITLE
potential leak if project forked but nobody ask for compilation

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#8518]
it is first reported by Xamarin. basically, if one create workspace and keep modify a project without calling getcompilation, we will keep add delta to it but never merge those making us to have long list of delta which can be viewed as a leak. 

http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Solution/Solution.CompilationTracker.cs,100

what I wrote above is simplified version, actual one require a bit more state setting to happen, but not very narrow case. and in VS, due to solution crawler, might not actually surface.

for it to happen in real world, there must be the very first GetCompilation call after that, all delta will be accumulated until next GetCompilation call. in Xamarin case, it never happened so triggered as a leak by their tool.

**Comment by heejaechang** [comment]
not sure whether it is something we want to take a look now or not, but wanted to make sure we aware this issue since if we move solution crawler out of VS, we will hit this issue.

one example this might happen in VS is that, user opened a file that belong to a project, and never open files from that project again, but do git pull which affect some files of the project. then we will start to have pending delta hang around until VS shutdown.

**Comment by DustinCampbell** [comment]
Already tracking this as #8420.

**Comment by heejaechang** [comment]
@DustinCampbell issue is duped are you assigning me the other issue? or want me to close it? (it is already closed though)

**Comment by DustinCampbell** [comment]
Nope. I assigned this to you to ensure that it's really a dupe of the other issue. That's all.
