### ISSUE TITLE
Dev14CTP6 branch or tag missing

### ISSUE THREAD

**Issue by DavidKarlas** [dotnet/roslyn#852]
It would be nice to have commit sha which was used to create rc1 packages, mostly so we can rebuild it locally and debug it(.pdbs).

**Comment by DavidKarlas** [comment]
I think milestone is wrong here... It should be 1.0-rc1

**Comment by DavidKarlas** [comment]
Looks like few days ago this branch appeared... :/

**Comment by jaredpar** [comment]
@DavidKarlas yep.  This bug reminded us we had forgotten about that and hence we got it added.
