### ISSUE TITLE
ExpressionCompiler has references to files in the output directory resulting in races

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#8529]
ExpressionCompiler.csproj has references to Moq with @tmat's user name and to a file from the output directory. This is causing races in the build.

These should be replaced with 1) project-to-project references or 2) package references.

``` XML
  <ItemGroup Label="File References">
    <Reference Include="$(OutDir)Microsoft.VisualStudio.Debugger.Engine.dll" />
  </ItemGroup>

    <Reference Include="Moq, Version=4.2.1402.2112, Culture=neutral, PublicKeyToken=69f491c39445e920, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\..\..\..\..\..\Users\tomat\.nuget\packages\Moq\4.2.1402.2112\lib\net40\Moq.dll</HintPath>
    </Reference>
```

**Comment by tmat** [comment]
I have no idea how this happened :-o

**Comment by davkean** [comment]
The Moq reference has been fixed. The Debugger.Engine.dll reference apparently is guaranteed to appear in the output directly by the time this project has built.
