### ISSUE TITLE
IOperation: needs a `GetAncestors(IOperation)` method

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#8535]
Right now it almost impossible for user to get the parent/ancestor operations of a given operaion, which would come in handy for analyzers. 

@srivatsn @JohnHamby suggest we don't expose `SemanticModel` in `OperationAnalysisContext` but provide a method in context instead.

**Comment by jaredpar** [comment]
Please file IOperations bug under Area-Analyzers only.

**Comment by mazhou-msft** [comment]
How this issue is going? I would vote for adding extension methods for Ancestors(), and AncestorsAndSelf(). This enables more flexible analysis (for example, check whether every method invocation's return value (if any) is not ignored in code.)

**Comment by jinujoseph** [comment]
this is addressed as part of https://github.com/dotnet/roslyn/issues/18601 , we don't need extension methods at this point.
