### ISSUE TITLE
Syntax normalizer uses CRLF for EOL character by default

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#8537]
This is true even if the OS convention is just LF, or if the file itself only contains LF characters.

**Comment by jcouv** [comment]
Ran into this when fixing another bug recently. The test below fails on Linux.

From discussion with Andy, it is not obvious that `NormalizeWhitespace` should just the line terminator from environment/OS. 
Most likely we'd want some kind of heuristic that looks at the line terminators in the rest of the file (in the case of a refactoring).

```
        [Fact]
        [WorkItem(21231, "https://github.com/dotnet/roslyn/issues/21231")]
        public void TestSpacingOnNullableIntType()
        {
            var syntaxNode =
                SyntaxFactory.CompilationUnit()
                .WithMembers(
                    SyntaxFactory.SingletonList<MemberDeclarationSyntax>(
                        SyntaxFactory.ClassDeclaration("C")
                        .WithMembers(
                            SyntaxFactory.SingletonList<MemberDeclarationSyntax>(
                                SyntaxFactory.PropertyDeclaration(
                                    SyntaxFactory.NullableType(
                                        SyntaxFactory.PredefinedType(
                                            SyntaxFactory.Token(SyntaxKind.IntKeyword))),
                                    SyntaxFactory.Identifier("P"))
                                    .WithAccessorList(
                                        SyntaxFactory.AccessorList())))))
                .NormalizeWhitespace();

            // no space between int and ?
            Assert.Equal(
@"class C
{
    int? P
    {
    }
}", syntaxNode.ToFullString());
        }
```

**Comment by CyrusNajmabadi** [comment]
An important part of NormalizeWhitespace (to me) is that it's 100% consistent.  It should not have any behavior that varies per platform.  If we want, we can configure it's behavior based on arguments passed to it.  For example, it can have a default newline, but we could also allow the caller to pass in the newline to use.

**Comment by CyrusNajmabadi** [comment]
> The test below fails on Linux.

Why?  Nothing about that test is OS specific.  On any OS the file contents should be exactly the same (i.e. we should not be translating source file line endings) and so the behavior and results should be consistent no matter which OS we're on.

**Comment by jcouv** [comment]
> The test below fails on Linux.

I didn't repro locally yet, but my guess is that when you build the test source on Linux, the multi-string literal ends up with Linux-style line terminators. Since `NormalizeWhitespace` outputs Windows-style terminators, the assert fails.

```
MESSAGE:
Assert.Equal() Failure\n ↓ (pos 7)\nExpected: class C\\n{\\n int? P\\n {\\n }\\n}\nActual: class C\\r\\n{\\r\\n int? P\\r\\n {\\r\\n }\\r\\n}\n ↑ (pos 7)
```

**Comment by CyrusNajmabadi** [comment]
> I didn't repro locally yet, but my guess is that when you build the test source on Linux, the multi-string literal ends up with Linux-style line terminators.

=-o 

That indicates that our source is getting translated when unpacked on linux.  That seems bad :)

**Comment by CyrusNajmabadi** [comment]
If our source is going to be different on different platforms, our test validation code should probably be updated to account for it (i.e. doing it's own platform specific normalization).

**Comment by CyrusNajmabadi** [comment]
In other words, we shoudl not be changing product code to deal with the fact that our test files are actually different on different platforms.  If that's how we want to do things, our test code itself should handle the fallout.

**Comment by tannergooding** [comment]
> If our source is going to be different on different platforms, our test validation code should probably be updated to account for it (i.e. doing it's own platform specific normalization).

By default, files are converted to and commited as \n in Git.
Git for Windows will, by default, automatically convert those back to \r\n on checkout.
Linux, by default, will checkout "as-is" (this is generally the \n form that it is automatically converted to on checkin).

https://help.github.com/articles/dealing-with-line-endings/ goes over this briefly, but there are tons of other blog posts/articles/documentation on it as well

**Comment by CyrusNajmabadi** [comment]
> By default, files are converted to and commited as \n in Git.

We can trivially configure out git repository to not do that.  That would be desirable here as this is test input code.  i.e. we are testing how our own APIs deal with certain inputs.  If those inputs change on different platforms, then our tests are changing what they're actually testing.

If we think this is desirable, then our test infrastructure itself should be resilient to this.  i.e. be converting the inputs to a normalized form before actually calling into product code.  Our product APIs should not be behaving differently.  i.e. if i write a program that calls NormalizeWhitespce, I should not have to know or care if that program then runs on Windows or OSX, it should have consistent results.  If i want different behavior from NormalizeWhitespcae, as the caller i should request htat by passing in data specifying what behavior i want.

**Comment by CyrusNajmabadi** [comment]
I'm closing this out absent an API proposal on what to do.  As before, SyntaxNormalizer is entirely consistent and deterministic with it's behavior.  Clients of it can specify the newline they want.  And tests that go through git line-ending normalization can then normalize their results as well.

I would not be opposed to a new api like NormalizeWithSystemLineEnding.  however, it needs to go through our API review process.
