### ISSUE TITLE
ISymbol.GetDocumentationCommentXml() returns always string.Empty

### ISSUE THREAD

**Issue by jbe2277** [dotnet/roslyn#854]
The call `ISymbol.GetDocumentationCommentXml()` returns always `string.Empty` when the Symbol represents a member of the .NET Framework (e.g. `System.Console.WriteLine`) or a member of a custom Assembly that has a XML documentation file.

It works only for members that are defined via `SourceText` and has the XML comment defined.

I create the assembly references via `MetadataReference.CreateFromAssembly`. A method overload of [CreateFromAssembly](http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis/MetadataReference/MetadataReference.cs,343f1f8eceb748ff,references) supports a `DocumentationProvder` as parameter but does not use it. This seems to be a bug.

How can I support Documentation for referred .NET Framework assemblies?

**Comment by theoy** [comment]
If this is fixed by #897 it may make 1.0-rc2

**Comment by gafter** [comment]
@tmat Can you please tag this issue with an appropriate Resolution-* label and verify it?
