### ISSUE TITLE
Need a way to configure analyzers at a solution level

### ISSUE THREAD

**Issue by eyalsk** [dotnet/roslyn#8541]
Hello,

I know I can do that per project but didn't find a way to do that globally.

I think I tried to change the code analysis settings but it wasn't applied to the solution maybe I forgot to choose the correct rule set file after saving, can't remember, should something like this work?

**Comment by srivatsn** [comment]
No, rulesets apply at a project level. One way to achieve this is to keep a ruleset file in a shared location and have all projects in the solution include the same ruleset file.

**Comment by eyalsk** [comment]
@srivatsn yeah but like I said I already tried it, might forgot to actually select the new ruleset, however, this isn't even ideal for my case.

Sharing the exact same ruleset isn't really a solution what I'd expect is to have a global ruleset file and then the ability to override the global with project specific ruleset and the reason for this is that for some projects I don't want to disable the analyzers.

In addition, at the moment when you open the ruleset it's not possible to flag rules for solution-wide or project-specific analysis and I think that this feature is vital.

**Comment by srivatsn** [comment]
Yes that's a missing feature. Changing this issue to a feature request to track that feature.

**Comment by eyalsk** [comment]
@srivatsn thank you. :)
