### ISSUE TITLE
VB XML doc comment completion incorrectly suggests 'return' tag (should be 'returns' with an 's')

### ISSUE THREAD

**Issue by AnthonyDGreen** [dotnet/roslyn#8546]
(Filing this on behalf of Jan (Đonny) Záruba)
![csxmlcompletion](https://cloud.githubusercontent.com/assets/10539978/12949523/3af22d4a-cfbd-11e5-9afe-6169faa874cf.png)
![vbxmlcompletion](https://cloud.githubusercontent.com/assets/10539978/12949526/3d87b228-cfbd-11e5-99eb-84ccb284311e.png)

"So, is it <returns> or <return>. OK, I know it's <returns>, but in that case there is a bug in VB IntelliSense.
"I was not playing with VBXMLDoc.xml file (if it is still supported)."

**Comment by DustinCampbell** [comment]
This looks like it's simply a bug. Also, `VBXMLDoc.xml` is not supported (and we haven't heard any complaints yet).
