### ISSUE TITLE
Potential leak in AnalyzerManager

### ISSUE THREAD

**Issue by mkrueger** [dotnet/roslyn#8547]
Diagnostics get an event handler added but not removed:

https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.cs#L240

**Comment by mavasani** [comment]
CompilationWithAnalyzers host is responsible for disposing the event handlers by invoking [this](http://source.roslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/CompilationWithAnalyzers.cs,171a3b0b590b2734,references) method.

Analyzers created in VS already do so when they are getting disposed. If you are writing a custom tool based on CompilationWithAnalyzers, you are responsible for doing so, as only the host knows of the actual lifetime of the analyzer instances with which it creates CompilationWithAnalyzers.
