### ISSUE TITLE
SemanticModel.GetSymbolInfo reports an OverloadResolutionFailure when no mscorlib referenced

### ISSUE THREAD

**Issue by OmerRaviv** [dotnet/roslyn#855]
Ported over from: https://roslyn.codeplex.com/workitem/489 - this still reproduces in v1.0.0-rc1
```
using System.Linq;
using System.Reflection;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace RoslynOddity
{
    internal class Program {

        private const string testProgram = @"
    using System.Linq;
    using System.Reflection;
    using Microsoft.CodeAnalysis;
    using Microsoft.CodeAnalysis.CSharp;
    using Microsoft.CodeAnalysis.CSharp.Syntax;

    class TestClass {
        void Foo() {
            var expr = SyntaxFactory.ParseExpression(""a is string"");
            if (expr.IsKind(SyntaxKind.IsExpression)) {
            }
        }
    }";

        private static void Main()
        {
            var tree = SyntaxFactory.ParseSyntaxTree(testProgram);

            var metadataReferences =
                Assembly.GetExecutingAssembly()
                    .GetReferencedAssemblies()
                    .Select(Assembly.Load)
                    .Select(MetadataReference.CreateFromAssembly);

            var compilation = CSharpCompilation.Create(
                "RoslynOddity.dll",
                new[] {tree},
                metadataReferences);

            var semanticModel = compilation.GetSemanticModel(tree);
            var condition = semanticModel.SyntaxTree.GetRoot().DescendantNodesAndSelf()
                .OfType<IfStatementSyntax>()
                .First()
                .Condition;

            var symbolInfo = semanticModel.GetSymbolInfo(condition);
        } // Put breakpoint here..
    }
}
```
In this code, `symbolInfo.Symbol` is null, and `symbolInfo.CandidateReason` is `OverloadResolutionFailure`. This seems to be a bug. The code in the syntax tree compiles just fine, so there doesn't seem to be any reason for the failure.

**Comment by gafter** [comment]
@OmerRaviv Can you confirm that the compilation has no diagnostics? after it is created in this repro?

**Comment by OmerRaviv** [comment]
@gafter I neglected to check this - I get warning on unneeded usings, but also get two errors:
```
at (10,38):  (11,22): and (11:27):
error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
```
and
```
error CS5001: Program does not contain a static 'Main' method suitable for an entry point
```

Solving the latter does not solve the former. Am I missing something?

**Comment by OmerRaviv** [comment]
If I copy paste the code in the repro into a blank new Console application, and NuGet install `Microsoft.CodeAnalysis.CSharp`, it compiles just fine without requiring any reference to System.Runtime.

**Comment by gafter** [comment]
I'm going to guess that `Assembly.GetExecutingAssembly().GetReferencedAssemblies()` does not include mscorlib. If that is true it might be a bug (elsewhere). Try adding the assembly containing `typeof(object)` and see if that helps.

**Comment by OmerRaviv** [comment]
No, it does include mscorlib, and even if I manually remove it and add `MetadataReference.CreateFromAssembly(typeof(object).Assembly)`, same result.

**Comment by tmat** [comment]
Microsoft.CodeAnalysis is a portable library. When referencing portable library from a non-portable library you need to add references for runtime façade assemblies (C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades). 

If you enable logging from msbuild you'll see that it adds these references automatically when compiling the Console application.

**Comment by OmerRaviv** [comment]
@tmat Ah, I see, thank you for the clarification. I'm closing this issue then, as there doesn't seem to be anything Roslyn should have done differently.
