### ISSUE TITLE
Stop adding binaries to the artifacts to reduce build time and space

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#8550]
It's rare for us to look at binaries when diagnosing build failures, we should update the file pattern so that we only store symbols, test logs, build logs and other artifacts from tests and only add those to the zip.

This should reduce our build time, and the amount of data that we're storing.

**Comment by davkean** [comment]
tag @jaredpar

**Comment by davkean** [comment]
@jaredpar says:

> The choice of uploading artifacts is just a file pattern match
> 
> https://github.com/dotnet/roslyn/blob/master/netci.groovy#L156
>   addArtifactArchiving(myJob, "**/Binaries/**", "**/Binaries/Obj/**")
> 
> If you have the list of files you’d like to archive this is very easy to change.  
>

**Comment by jaredpar** [comment]
Globs I'm aware of that are valuable to store:

1. `*.xml`
2. `*.baseline.*` 
3. `*.dmp`

**Comment by tannergooding** [comment]
@davkean, I'm pretty sure the real slow down comes from archiving the individual files in addition to the complete zip file. I would believe that we would get a significant speedup by only archiving the zip file and that should be our first attempt to speed this up. If that doesn't provide a speedup that meets our needs, then we should look at trimming the size of the zip by excluding things that may not always necessary.

**Comment by davkean** [comment]
@tannergooding Disagree. I'm looking at increasing the number of artifacts we store around, we'll want to reduce the size to be reduce the amount of space we use anyway. In the 4 months I've been watching, I've not seen anyone use the dlls when diagnosing a failure.

@jaredpar We'll want to add *.log; *.pdb.

**Comment by davkean** [comment]
We'll probably also want to think about the dlls we write out when peverify fails.

**Comment by jaredpar** [comment]
@davkean updated the list.  Why is `pdb` interesting?

Pretty sure we right those DLLs to a specific directory that we can add in.  If not we can change it up to do that.  

@tannergooding why do work for something we've never looked at?

**Comment by davkean** [comment]
@jaredpar Because without it makes looking a dmp that much harder - you basically have do magic windbg offset magic to have it match up to source.

**Comment by jaredpar** [comment]
@davkean okay.  I thought we didn't need that for managed processes, only native ones.

**Comment by davkean** [comment]
Yeah, you get a nice stack with managed without pdbs, but you often want to see what line actually failed.
