### ISSUE TITLE
Visual Basic BinaryOperators.Test1 fails on CTP6

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#856]
The `BinaryOperators.Test1` suite fails on a machine with only CTP6 installed.  

It is hard to understand why this failure occurs because this suites is essentially running an `Assert.Equal` on strings that are over 100,000 characters long.  For now I'm just going to disable it when we move to CTP6 in Jenkins.

**Comment by theoy** [comment]
We should investigate for 1.0

**Comment by VSadov** [comment]
Consider pushing to 1.1 if this is just an infrastructure/test issue
