### ISSUE TITLE
Add observable functions to properties -- ala Swift

### ISSUE THREAD

**Issue by jrmoreno1** [dotnet/roslyn#8560]
@migueldeicaza  wrote in issue #123 

> I like what Swift does in this area, and it should satisfy the requirements of this request.
> They introduce "observers" which are part of a property declaration. They augment "set" and "get" with "didSet" and "willSet", You can use those to validate the parameters with willSet, and you can run arbitrary code after a value has been set with "didSet".
> 
> Lots of code like this can be trivially rewritten:
>     public Color TextColor {
>        set {
>           _color = value;
>           NeedsUpdate (this);
>       }
>    }
> 
> And just becomes:
> public Color TextColor {
>     didSet { 
>         NeedsUpdate (this); 
>     }
> }

I think this is an excellent idea, worth being raised individually -- the INotifyPropertyChanged interface is common, but not pleasant.

**Comment by HaloFour** [comment]
The use case in #123 is setter validation and this is something that Swift's property observers don't address.  `willSet` cannot cancel changing the value silently nor can it `throw`.  All it provides is notice that the property value is or has changed, which is fine for `INotifyPropertyChanged` but otherwise seems too limited.  Even in Swift to implement validation functionality you are recommended to write full properties complete with setters, getters and backing fields.

**Comment by alrz** [comment]
@HaloFour I think property setter is not a good place to implement validation, in that case whatcha gonna do? `throw`? That doesn't recommended either.

**Comment by HaloFour** [comment]
@alrz 

>  That is not recommended either.

Throwing from a property setter is just fine.  Microsoft's design recommendations for properties recommends against throwing from *property getters*:

> X AVOID throwing exceptions from property getters.

The specs also explicitly state the following:

> ✓ DO preserve the previous value if a property setter throws an exception.

> Property getters should be simple operations and should not have any preconditions. If a getter can throw an exception, it should probably be redesigned to be a method. Notice that this rule does not apply to indexers, where we do expect exceptions as a result of validating the arguments.

**Comment by alrz** [comment]
@HaloFour Why you can't write the validation logic in `willSet` block then? I think this would be a better solution over `T P { get; set { ... } }` syntax (#8364).

**Comment by HaloFour** [comment]
@alrz 

I guess in a C# implementation you can avoid the Swift limitations of not being able to `throw` or modify the proposed value.  But what does it really buy you over proper properties?  Do we need a pseudo-accessor method to express what can already be expressed today without an egregious amount of verbosity?

```cs
public string Name {
    get; set;
    willSet {
        if (value == null) throw new ArgumentNullException("value");
        value = value.ToUpper();
    }
    didSet { NeedsUpdate(this); }
}
```

```cs
public string Name {
    string _name;
    get { return _name; }
    set {
        if (value == null) throw new ArgumentNullException("value");
        _name = value;
        NeedsUpdate(this);
    }
}
```

**Comment by DavidArno** [comment]
Given the move in recent years toward immutable data and away from using setters except for stateful situations like UI's, I'm struggling to see what this proposal would offer, that isn't already offered eg by property bindings in XAML.

**Comment by alrz** [comment]
@HaloFour When you want to change the value inside of `willSet` then why would you use it in the first place? Yes in that case you should definitely use regular getter and setter, but when you want  a callback-like behaviour, that's where it'll be useful.
```cs
public string Name {
    willSet {
        if (value == null) throw new ArgumentNullException("value");
    }
    didSet {
      NeedsUpdate(this);
    }
}
```
I wonder if this can be replaced by #8364.

**Comment by HaloFour** [comment]
@alrz You forgot `set; get;` :grinning:

> When you want to change the value inside of willSet then why would you use it in the first place?

I ask that same question about every flavor of slightly-less-than-auto-properties that I see.  Your example and my full property example are almost the same length and complexity, except full properties don't need the voodoo of pseudo-accessor methods.

It's not even so much that I find issues with these specific proposals, it's just that if the explicit design decision around auto-properties is that the accessors should contain no logic I think that the use case and proposed syntax needs to be exceptional to demonstrate why that decision should be reversed.

**Comment by alrz** [comment]
@HaloFour I followed Swift's syntax, it does need `{ get set }` but when you use property observers there is no need to write that, because it implies the property has a default getter and setter. And I don't usually `throw` from my property setters :smile: However, any use case that I had in mind for this, probably can be implemented via  #5292 and #5561.

**Comment by HaloFour** [comment]
@alrz Yeah, Swift's property syntax is bizarre.  The entire structure changes depending on what you want to do and how you change the default behavior has a variety of inconsistent syntaxes.  It's like they threw all of the spaghetti against the wall and left it there regardless of whether or not it stuck.  If C# were to implement property observers I'd certainly not recommend that they adopt Swift's specific syntax/behavior.

**Comment by lachbaer** [comment]
I also think for the sake of clarity and unambiguous code, all setter related pre- and post-set stuff should stay in the setter and not be split over several pseudo methods!

**Comment by jrmoreno1** [comment]
@HaloFour: I think using Swift was just for the basic concept: easily and cleanly adding pre and post "events" to properties.  That's certainly what I took from @migueldeicaza suggestion and thought would be useful.  Exact syntax or constraints weren't on my radar.

**Comment by jcouv** [comment]
Moving language discussion to csharplang.

**Comment by jcouv** [comment]
Issue moved to [dotnet/csharplang #1030](https://github.com/dotnet/csharplang/issues/1030) via [**ZenHub**](https://www.zenhub.com/)
