### ISSUE TITLE
SignatureHelp should be lazier

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#8564]
SignatureHelp currently computes eagerly the display text for every single signature. This can result in perf issues when 100's of overloads are available (\[fileshare]\public\rchande\179726). To mitigate this, signaturehelp should only do the SymbolDisplay computation when an item is displayed.

Fortunately, the underlying editor API does not require us to realize all the strings up front, so this is doable--in fact, we've already applied this technique to documentation.

**Comment by CyrusNajmabadi** [comment]
We haven't seen any reports in the wild of this being a problem.  Closing out as not a realistic issue for now.
