### ISSUE TITLE
Raising-event should be an independent `IOperation`

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#8567]
Right now it is represented as method invocation.

Proposals:

```cs
public interface IRaiseEventExpression : IHasArgumentsExpression
{
    /// <summary>
    /// Reference to the event to be raised.
    /// </summary>
    IEventReferenceExpression EventReference { get; }
}
```

or

```cs
public interface IRaiseEventExpression : IHasArgumentsExpression
{
    /// <summary>
    /// Referenced event.
    /// </summary>
    IEventSymbol Event { get; }

    IOperation Instance { get; }
}
```

**Comment by jinujoseph** [comment]
**Design Team Decision**

So far we like the first Approach , We should also rename IInvocationExpression to IRaiseEventExpression . 
We will need to investigate how VB raise events are handled, Can you investigate and confirm

**Comment by genlu** [comment]
@jinujoseph @CyrusNajmabadi Do you remember why do we think raising events in VB needs a closer look? From what I saw in the langauge spec, `RaiseEvent` seems to be the only way to do so.

**Comment by genlu** [comment]
Ah, I see. You can have something like this.


```vb
Class Raiser

    Public Event Constructed(ByVal Count As Integer)

    Public Sub New()
        ConstructedEvent.Invoke(CreationCount)
    End Sub
End Class
```

**Comment by tmat** [comment]
@genlu What's the status?
