### ISSUE TITLE
[Add Using] Assembly dependencies are not added

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#8568]
- Create three projects
    - Create class library `ClassLibrary1` that contains type Test
    - Create class library `ClassLibrary2` that references `ClassLibrary1` and contains the following code:
```C#
namespace ClassLibrary2
{
    public class Test
    {
        public static ClassLibrary1.Test Get()
        {
            return new ClassLibrary1.Test();
        }
    }
}
```
 - Create class library `ClassLibrary3` which contains the following code:
```C#
namespace ClassLibrary3
{
    public class Class3
    {
        static void Main(string[] args)
        {
            var t = Test.Get();
        }
    }
}
```

**Expected**: Add using will offer to add project references to `ClassLibrary2` and `ClassLibrary1`

**Actual**: Only references to `ClassLibrary2` are added.  Attempting to add a reference to `ClassLibrary1` via codefix crashes VS due to #8514

**Comment by jmarolf** [comment]
@CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
Not sure how i feel about this.  When you manually add a reference to ClassLibrary2 nothing automatically adds one to ClassLibrary1.  And depending on what you do/don't use from ClassLibrary2, a ClassLIbrary1 reference may or may not be necessary.

On top of this, once you do add hte reference to ClassLibrary2 then you should get an error about a missing transitive reference.  In that case, dont' we have a fixer (written by @jasonmalinowski ) to add the missing reference?

**Comment by jmarolf** [comment]
> dont' we have a fixer

Yes but it crashes Visual Studio in this case #8514

**Comment by CyrusNajmabadi** [comment]
ok.  well,, that's a different matter :)  If we have a feature which already addresses the "transitive references needed" problem... then i'm more inclined to just have it do it's job, and not try to do the same here (which is going to be really expensive).

**Comment by jmarolf** [comment]
@CyrusNajmabadi sure, I can live with that.  Though it would be nice if Stuff Just Worked&#8482; and Add Using auto-magically did this.

**Comment by DustinCampbell** [comment]
Triage feels like it should only offer to add a reference to ClassLibrary2.

**Comment by CyrusNajmabadi** [comment]
Both triage and i agree that this should only add a direct reference to the single project.  So i'm closing.  :)
