### ISSUE TITLE
[Add Using] Only suggests one reference if two match

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#8571]
- Create class library `ClassLibrary1` that contains type Test
```C#
namespace ClassLibrary1
{
    public class Test
    {
        public void Method1() { }
    }
}
```
- Create class library `ClassLibrary2` that contains type Test:
```C#
namespace ClassLibrary1
{
    public class Test
    {
        public void Method2() { }
    }
}
```

- Create class library `ClassLibrary3` that contains assembly reference to `ClassLibrary1` and `ClassLibrary2`
- Create class library `ClassLibrary4` that references none of the above projects but contains the code:

```C#
namespace ClassLibrary4
{
    public class Class4
    {
        static void Main(string[] args)
        {
            var t = new Test();
        }
    }
}
```

**Expected**: Both `ClassLibrary1` and `ClassLibrary2` are offered as assembly references

**Actual**: Only  `ClassLibrary1` is offered

**Comment by jmarolf** [comment]
@CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
This is likely a problem with my equality check.  Because both adds will try to add the same "using ClassLibrary1" we filter the second out.  We need to take account the project ref that will be added as well.

**Comment by CyrusNajmabadi** [comment]
Fixed with: https://github.com/CyrusNajmabadi/roslyn/commit/b7c71517edc3c66dfb3ef48eba19f8c599cb454f

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/commit/d08826231c2dd02678c546bc2d5e0584677f27ef
