### ISSUE TITLE
Consider using NonFatalWatson to report erroneous cases in IOperation

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#8573]
Right now, when the OperationVisitor encounter a Operation of kind `None`, it will ignore it (in contrast of throwing an `code unreachable exception` before, which is changed by #8517 ). We should consider using non fatal Watson for release.

Any thoughts? Should this be done for update2 release?
@dotnet/roslyn-interactive @srivatsn @jaredpar

**Comment by tmat** [comment]
That's odd. Why wouldn't we throw unreachable (invalid operation) exception?

**Comment by genlu** [comment]
Because we don't want to crash VS as we might miss some corner cases (the IOperation API is undertested right now, trying to get more coverage.)

**Comment by tmat** [comment]
I see. Don't we already have a general mechanism that catches and reports exceptions from analyzers though?

**Comment by genlu** [comment]
I'm not sure what you are referering to. I talked to @srivatsn and he suggested the NFW, maybe it's the same thing?

**Comment by srivatsn** [comment]
We catch all exceptions coming from analyzer actions. These exceptions would be coming from the compiler itself in the IOperation implementation.

**Comment by genlu** [comment]
Now we are running all compiler tests against `IOperation`, which should cover a lot of ground, I see less value in doing this. Thoughts? @srivatsn

**Comment by srivatsn** [comment]
No objection.

**Comment by genlu** [comment]
Close this. Reason as mentioned above.
