### ISSUE TITLE
Initializing a class with static members depends on ordering. (throws TypeInitializationException)

### ISSUE THREAD

**Issue by hughbe** [dotnet/roslyn#8574]
Migrated from dotnet/coreclr/issues/3109

I encountered the following code that *really* stumped me. The following code crashes with a TypeInitializationException, if you follow the comments below.

```
class Program
{
    static unsafe void Main(string[] args)
    {
        new InvalidClass();
    }
}

public class InvalidClass
{
    // UNCOMMENT this: works!
    /*private static readonly char[] s_hexUpperChars =
    {
        '0', '1', '2', '3', '4', '5', '6', '7',
        '8', '9', 'A', 'B', 'C', 'D', 'E', 'F'
    };*/

    private static readonly char[] s_specialCharacterChars = new char[] { '%', '@', ',', '?' };
    private static readonly string[] s_specialCharacterHexEscapedStrings = HexEscapeCharsToStrings(s_specialCharacterChars);


    // Uncomment this: crashes with TypeInitializationException
    /*private static readonly char[] s_hexUpperChars =
    {
        '0', '1', '2', '3', '4', '5', '6', '7',
        '8', '9', 'A', 'B', 'C', 'D', 'E', 'F'
    };*/

    private static unsafe string[] HexEscapeCharsToStrings(char[] characters)
    {
        var strings = new string[characters.Length];
        char* chars = stackalloc char[3];
        chars[0] = '%';

        for (int i = 0; i < characters.Length; i++)
        {
            char c = characters[i];
            Debug.Assert(c <= 0xFF);

            chars[1] = s_hexUpperChars[(c & 0xf0) >> 4];
            chars[2] = s_hexUpperChars[c & 0xf];
            strings[i] = new string(chars, 0, 3);
        }

        return strings;
    }
}
```

I think this is because members are initialized in order of appearance, since, if I move `s_hexUpperChars` above where `HexEscapeCharsToStrings` is called, there is no exception thrown.

This is confusing behaviour IMO, and should be corrected. I'm not sure if this is by design or a bug.

There are some solutions:
- On the compiler side, warn the user if calling a static property before its initialized if a situation where a TypeInitializationException is thrown occurs
The compiler could tell this if it detects that a function is called which references a static member is not initialized, and then give a warning saying this may cause a TypeInitializationException,

- Do not rely on the ordering of members when initializing them. Instead form some sort of dependency graph that detects the correct ordering of initializing members so that a TypeInitializationException is not thrown at runtime.

- Keep as is

**Comment by HaloFour** [comment]
@hughbe Per C# 5.0 specification § 10.5.5.1:

> The static field variable initializers of a class correspond to a sequence of assignments that are executed in the textual order in which they appear in the class declaration.

A warning would be nice but the compiler really doesn't have a concept of an "uninitialized" field like it does with locals.  And in your case it would require some more advanced flow analysis since it is a static method which is failing and not the initializer itself.

**Comment by mikedn** [comment]
> This is confusing behaviour IMO, and should be corrected. I'm not sure if this is by design or a bug.

I don't see anything confusing. Initialization happens in source order and that's as clear and simple as it gets. Having initialization order being determined by the compiler based on extensive code analysis is likely to be far more confusing. Especially if it keeps changing when code changes.

> The compiler could tell this if it detects that a function is called which references a static member is not initialized

It may do that in your particular example but it cannot do that in other cases. For example, it cannot do it if the function is in a referenced assembly. That may be a relatively rare situation but ultimately it means that the compiler could generate the warning only in certain circumstances. This kind of warnings are probably better left to code analyzers.

**Comment by jaredpar** [comment]
This behavior is by design as @HaloFour pointed out.  

> On the compiler side, warn the user if calling a static property before its initialized if a situation where a TypeInitializationException is thrown occurs

The compiler could determine this is simple cases such as the one you listed where there is a direct code path.  This is not solvable in the general case though because this usage could be indirect (through virtuals, interfaces, delegates or do to ordering of other static constructor calls).
