### ISSUE TITLE
[Question] How to open a project with the ProjectId

### ISSUE THREAD

**Issue by shaggygi** [dotnet/roslyn#8583]
Basically, I'm trying to get all references in a project including referenced project.  There is probably a better way to get information for all, but not sure.   I have some simple code to open a workspace and open/return a project.

`
using (MSBuildWorkspace msBuildWorkspace = MSBuildWorkspace.Create())
{
    return await msBuildWorkspace.OpenProjectAsync(projectPath, cancellationToken);
}
`

Then I can convert the references into Assemblies to get the info I need like name, version, etc.

`foreach (var metadataReference in project.MetadataReferences)
 {
     Assembly assembly = Assembly.LoadFrom(metadataReference.Display);
}
`

So now I'm trying to do something similar for referenced project, but don't know how.

`foreach (var proRef in project.ProjectReferences)
 {
     // TODO: Get info here
}
`

Any thoughts on how to get this and do it a more appropriate way?  Any help is appreciated.

**Comment by DustinCampbell** [comment]
@shaggygi -- what is it you're trying to accomplish? You should be able to use `Solution.GetProject(...)` with a ProjectId.

**Comment by shaggygi** [comment]
I want to scan all my project files (csproj and vbproj) to see which ones reference a specific DLL.  This searches for DLL by name, version and location (file path).  Since I have many projects throughout many solution (sometimes with the same project added in multiple solutions), I am scanning each project file instead of opening each solution file, scanning its projects, etc.

If a project references a DLL by Add Reference in VS, I am able to open the project and check using the following:

` foreach (var metadataReference in project.MetadataReferences)
 {
 Assembly assembly = Assembly.LoadFrom(metadataReference.Display);
// Other code here to compare name, etc.
 }
  `

So my question would be... how to search for the DLL when the class project is added to solution and is referenced by project in other projects.  I was assuming I can do it by getting a project, create an Assembly object using similar code above with the project.ProjectReferences ProjectId, get the project and use project's OutputPath.  I'm thinking there might be a better way to search for these types of references... just don't know the best place to look in Roslyn APIs.

I was looking for your suggestion on Solution.GetProject, but don't see using IntelliSense.  Is there a particular NuGet package?

As always, thanks @DustinCampbell for trying to help :smile:

**Comment by CyrusNajmabadi** [comment]
> So my question would be... how to search for the DLL when the class project is added to solution and is referenced by project in other projects. 

Insetad of `project.MetadataReferences`, use `project.ProjectReferences`.  With that you can find what other projects are referenced from your project.  You can then examine them to determine information about them (like what their assembly name is) and so on :)
