### ISSUE TITLE
Question about CS0012 for IEnumerable<> type facade in VS2015 Update 1

### ISSUE THREAD

**Issue by ericwj** [dotnet/roslyn#8584]
After reading #560 and other related issues and trying the recommended workaround of adding 
```XML
<Project ToolsVersion="14.0"
    <PropertyGroup>
        <CheckForSystemRuntimeDependency>true</CheckForSystemRuntimeDependency>
</>...</>
```
in the .xproj project file, I still can't get `IEnumerable<>` to be resolved referencing `Microsoft.CodeAnalysis.Common`. All is well for `"frameworks": "dotnet5.4"` but for `net451` I can't seem to figure out any version of that package that will not cause use of `IEnumerable<>` in my code to be accepted. I tried targeting down to `net45` instead, since that is the version listed as supported by the package, but VS and dnu build are still complaining with he following error:

```
.NET Framework 4.5.1 error CS0012: The type 'IEnumerable<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
```

I'm using VS 2015 Update 1 with 1.0.0-rc1-update1 clr x86 in global.json. 

Can you please give a suggestion of something I can do to fix this, or to figure out what the problem is?

**Comment by ericwj** [comment]
I don't think this is an IDE problem, since `dnu build` produces the exact same errors.

**Comment by DustinCampbell** [comment]
Hey @ericwj -- I just added the IDE label so that we would look at it later this morning. :smile:

This looks to us to be a DNX issue and not related to Roslyn at all. Could you file this in the ASP.NET repo please?

**Comment by ericwj** [comment]
Awesome, Github understood the link ;) Thanks Dustin
