### ISSUE TITLE
Proposal: Enhancement to records proposal #206 to included lambda functions in the constructor

### ISSUE THREAD

**Issue by SteveStrong** [dotnet/roslyn#8590]
This is a enhancement to the  records in #206.  Inspired by the NDC 2016 Talk for Bill Wagner.   

I propose we extend the record syntax 

class Person(string FirstName, string LastName);

to include lambdas so this would be a legal and valid syntax:

class Person(
   string FirstName,
    string LastName,
    string FullName =>  { return $"({LastName}, {FirstName})" }
);

The Proposal:

Constructor variables that are defaulted to an Arrow Function => are compiled as a getter that has no backing variable, but a computed value.

so.
    public string FullName 
    {
        get 
        {
           return  $"({this.LastName}, {this.FirstName})" ; 
        }
    }

an example would be.

Person p = new Person(FirstName: "Neil", LastName: "Gafter");

var printableName = p.FullName;   

//printableName  value should now be  "Gafter, Neil"

The Use Case:  

Often DTO classes are designed to transport data to bind to WPF UI elements (read only).  There are many times that the DTO contains computed values that are combinations to the 'base data elements' 

So rather than computing all the values needed to fill the Record structure and create backing data fields to store those values,  let the derived values to be computed on demand according to the lambda expression.

**Comment by alrz** [comment]
You can still define a property for a record in the class body,
```cs
class Person(string FirstName, string LastName) {
  public string FullName => $"{LastName}, {FirstName}";
}
```
which doesn't shove everything in the primary constructor.

**Comment by DavidArno** [comment]
As I understand it,

    class Person(string FirstName, string LastName)

will just be translated to:

    sealed class Person
    {
        public string FirstName { get; }
        public string LastName { get; }

        public Person(string FirstName, string LastName)
        {
            this.FirstName = FirstName;
            this.LastName = LastName;
        }

        public (string First, string Last) Deconstruct() => (First, Last);

        // public override Equals & GetHashCode
    }

You will be free to add `{}` after `class Person(string FirstName, string LastName)` and anything there will be appended to the resultant class contents. Hopefully, there'll be plenty of variance-checking to stop the misuse of records, but that's just speculation on my part.

**Comment by gafter** [comment]
Yeah, you can already do this just by placing the new property between the curly braces of the class.

**Comment by SteveStrong** [comment]
looks like writing the code below does everything I need.  thanks

class Person(string FirstName, string LastName) {
  public string FullName => $"{LastName}, {FirstName}";
}
