### ISSUE TITLE
Proposal: Null-conditional forwarding operator

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#8593]
Given the forward pipe operator proposed in #5445, it has been [suggested by @HaloFour](https://github.com/dotnet/roslyn/issues/5961#issuecomment-148232519)  to extend it with a variant that function like the null-propagation operator, as an alternative to #5961,

```cs
var result = Foo.Bar?.Baz ?> F() ?? false;
var result = Foo.Bar?.Baz != null ? F(Foo.Bar.Baz) : false;
```

The value forwarded to the target function `F` is of a non-nullable type (#5032).

Just like `?.` operator, you don't need to use `?>` if the target function doesn't return a nullable value, so for chaining you should use the regular `|>` operator to not perform an additional null-checking, e.g.
```cs
var result = nullable?.Foo.Bar;
var result = nullable ?> F() |> G();
```
In this example `F` takes a non-nullable and returns a non-nullable but the `result` will be a nullable if you don't use the `??` operator at the end.

**Comment by DavidArno** [comment]
Yes.

Not really much else to say :)

**Comment by gafter** [comment]
This issue is a proposal to modify a proposal described in an issue?

I don't think it belongs as a separate issue. Can you please record this suggestion in the context of the proposal that it applies to?

**Comment by alrz** [comment]
@gafter No, this is not about modifying another proposal, this would be a completely separate feature but it can be considered as a variant of #5445.
