### ISSUE TITLE
Is there an updated version of "Microsoft Build Tools 2015" with the "Update 1" compilers?

### ISSUE THREAD

**Issue by DanTup** [dotnet/roslyn#8595]
We'd like to start using the Roslyn compilers on our build server, without having to explicitly install NuGet packages in all of our projects (we understand the risks of flipping everything over in one go).

I found "Microsoft Build Tools 2015" which I believe would do the job:
https://www.visualstudio.com/en-us/downloads/download-visual-studio-vs.aspx
https://www.microsoft.com/en-us/download/details.aspx?id=48159

However; based on the dates it seems like these are from the original VS release with VS 2015. I'm under the impression VS 2015 Update 1 had a bunch of fixes to the compilers; so I'm worried about us getting the old versions.

Is there an updated version of these build tools? Or can they be updated (eg. via Windows Update)? Or are the only options to have the old ones or install the NuGet packages into all of our projects/solutions?

**Comment by jaredpar** [comment]
Adding some MSBuild team members to see if they can answer this: @rainersigwald, @AndyGerlicher

**Comment by rainersigwald** [comment]
There is no standalone package for updated Build Tools, but the VS Update installer will work fine on a machine with only Build Tools installed, updating the build tools and not installing the rest of VS.

**Comment by jaredpar** [comment]
@rainersigwald on a machine with only build tools installed what should an end user run to get this update?

**Comment by rainersigwald** [comment]
For Build Tools 2015, to apply Update 1, run `VS2015.1.exe` from https://www.visualstudio.com/news/vs2015-update1-vs.

**Comment by DanTup** [comment]
Thanks! Will give this a go when back in the office :)

I presume I need to install the original build tools first, then use this to update.. I can't just install them directly with the .1 installer?

**Comment by rainersigwald** [comment]
@DanTup That's correct, we don't have a "slipstream" installer for Build Tools.

**Comment by rainersigwald** [comment]
@DanTup I just tried this locally, and unfortunately I'm wrong and the update installer doesn't work. It complains that "Update 1 does not apply". We're trying to figure out how to distribute an update (hopefully for Update 2). Tracking at https://github.com/Microsoft/msbuild/issues/480.

Sorry for the misinformation/false hope.

**Comment by jaredpar** [comment]
Going to close this and let the MSBuild issue track this problem.

**Comment by DanTup** [comment]
I've subscribed to the other case; thanks for the help!
