### ISSUE TITLE
 Error trying to download C# 7.0

### ISSUE THREAD

**Issue by Ocisaac** [dotnet/roslyn#8597]
I want to experiment and test C# 7.0, but I'm getting errors running `Resotre.cmd`.
I get the error `error MSB4019: The imported project <path> was not found` over and over again.
How can I fix it?

**Comment by davkean** [comment]
Which branch are you in?
What are the exact errors?

**Comment by Ocisaac** [comment]
@davkean I've tried to run it again and it seems to work now, thanks anyways.

**Comment by davkean** [comment]
Thanks.
