### ISSUE TITLE
Rule set editor should group by Analyzer ID by default

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn#86]
As Roslyn-based analyzers become more widely used we expect most interaction with the rule set editor to be about changing these analyzers, rather than changing legacy FxCop rules. To support this, the rule set editor should group rules by Analyzer ID by default.

**Comment by tmeschter** [comment]
The rule set editor has been updated to fix this issue.

**Comment by giggio** [comment]
Can you post an image on how this will look now? I am really curious about the new design.

**Comment by tmeschter** [comment]
Here's what you used to get by default:
![image](https://cloud.githubusercontent.com/assets/10506730/6259021/ef7ddb82-b782-11e4-8f61-fe726aac1b56.png)

And here is what you get now:
![image](https://cloud.githubusercontent.com/assets/10506730/6259032/0fc369fc-b783-11e4-93ce-00fe0f9f8404.png)

Note that you could already group by Analyzer ID; now it is just the default. The project doesn't have many analyzers, but I think you get the idea.

**Comment by tmeschter** [comment]
Assigning to @mavasani for verification.
