### ISSUE TITLE
CA1802 false positive when initializer contains expression with constant

### ISSUE THREAD

**Issue by breyed** [dotnet/roslyn#8600]
Consider the following field on some class `C`:

    static readonly int F = DateTime.Now.Second == 0 ? 1 : 2;

It generates the following Code Analysis warning:

> Warning CA1802: Field 'C.F' is declared as 'static readonly' but is initialized with a constant value '1'. Mark this field as 'const' instead.

**Comment by mavasani** [comment]
Ported to https://github.com/dotnet/roslyn-analyzers/issues/848
