### ISSUE TITLE
ImportAdder API can result in new document having ambiguity errors

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn#8604]
For code like this:

``` csharp
using A;

class X
{
      B b;
      C.D d;
}
```

where 'C.B' is also a valid type, if one calls ImportAdder.AddImportsAsync on `C.D`, it results in the following code:

``` csharp
using A;
using C;

class X
{
     B b;
     D d;
}
```

But now `B` is ambiguous between `A.B` and `C.B`

**Comment by CyrusNajmabadi** [comment]
Clsoing out as we added support for this.
