### ISSUE TITLE
tighten up AnalyzerOptions

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#8605]
we should do what @tmat suggested.

...

```
    public AnalyzerOptions AnalyzerOptions
    {
        get
        {
            if (analyzerOptions == null)
            {
                this.analyzerOptions = new AnalyzerOptions(this.additionalDocumentStates.Values.Select(d => new AdditionalDocumentStream(d)), globalOptions: null);
            }

            return analyzerOptions;
        }
    }

    private static AnalyzerOptions CreateAnalyzerOptions(ImmutableDictionary<DocumentId, TextDocumentState> additionalDocStates)
    {
        return new AnalyzerOptions(additionalDocStates.Values.Select(d => new AdditionalDocumentStream(d)), globalOptions: null);
    }
```

I couple of concerns 
1)  CreateAnalyzerOptions seems to be unreachable and duplicating logic in the getter – I think it would be better to change analyzerOptions to readonly Lazy<AnalyzerOptions> lazyAnalyzerOptions.
2)  The order of documents in the list passed to AnalyzerOptions is non-deterministic. Since this is then exposed as AnalyzerOptions.AdditionalFiles API it seems like we should order it in some way. Especially since AnalyzerOptions have value equality semantics.
3)  AnalyzerOptions should be sealed and implement IEquatable<AnalyzerOptions>

Tomas

**Comment by mavasani** [comment]
Note that 3. is not possible until we have some way for analyzers running in the IDE to get workspace options (simplify type name analyzer needs it) OR switch such analyzers to be DocumentAnalyzers that can run only in the IDE.

**Comment by heejaechang** [comment]
@mavasani I think I heard that analyzer will support options (I mean like IDE workspace options). once that is supported, we might not need WorkspaceOptions anymore?

**Comment by mavasani** [comment]
@heejaechang Yes that should fix it.

**Comment by mavasani** [comment]
@srivatsn this item depends on the work to support analyzer options, we can then get rid of WorkspaceAnalyzerOptions and make AnalyzerOptions sealed.

Should we move this issue out of 1.3? Its unlikely we will complete the above 2 items by 1.3.

**Comment by mavasani** [comment]
Moving this out of 2.0 to Unknown - not sure if we can even get to supporting analyzer options by 2.0

**Comment by mavasani** [comment]
This is no longer relevant. WorkspaceAnalyzerOptions cannot be removed based on https://github.com/dotnet/roslyn/issues/64046#issuecomment-1248449302. Hence, AnalyzerOptions cannot be sealed (it will also be a breaking change to seal a shipped public type).
