### ISSUE TITLE
SignatureHelp perf tweaks

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#8609]
While investigating, #8654 ( \[fileshare]\public\rchande\179726 ), I made some additional observations about SigHelp:

* [ConvertMemberGroupMember](http://source.roslyn.io/Microsoft.CodeAnalysis.VisualBasic.EditorFeatures/R/de9958eb6b70e333.html) calls ToMinimalDisplayString on the member multiple times and ToMinimalDisplayString on the member's containing type multiple times. I imagine we can save a significant amount of work (and probably some allocations) if we make fewer ToMinimalDisplayString calls. Note that we'll want to audit all of SigHelp (not just VB invocation SigHelp) for this pattern

* SigHelp theoretically has code that code that will cancel a computation if no results have been produced. However, in the repro for 179726, there's already some "initial value" that hasn't yet presented. We should adjust the OnNavigationKey code to not block on the computation if it has never been presented.

* Speculation: it appears that if you type faster than SigHelp can present, it will continuously chain more computations without cancelling them, thus getting further and further behind.

**Comment by rchande** [comment]
@Pilchie: I think the first and second points above are simple enough that they could make it into 1.2,

**Comment by DustinCampbell** [comment]
@rchande -- is this still happening? Should it stay in 1.2

**Comment by rchande** [comment]
@DustinCampbell I implemented the second bullet point and the change is in master/stabilization (and corresponding bug resolved), so I'm going to close this.

**Comment by DustinCampbell** [comment]
Thanks!
