### ISSUE TITLE
Proposal: Implementing IComparable should implement comparison operators

### ISSUE THREAD

**Issue by iDaN5x** [dotnet/roslyn#8633]
Implementing IComparable is sufficient for allowing comparison of two instances of class X.
It is, therefore, preferable that comparison operators (such as !=, =, <, <=, etc.) would be auto-implemented for X pairs when implementing IComparable.

Currently, large share of comparable classes features the following silly-looking pattern:
```
public static bool operator  < (Foo x, Foo y) { return CompareTo(x, y)  < 0; }
public static bool operator  > (Foo x, Foo y) { return CompareTo(x, y)  > 0; }
public static bool operator <= (Foo x, Foo y) { return CompareTo(x, y) <= 0; }
public static bool operator >= (Foo x, Foo y) { return CompareTo(x, y) >= 0; }
public static bool operator == (Foo x, Foo y) { return CompareTo(x, y) == 0; }
public static bool operator != (Foo x, Foo y) { return CompareTo(x, y) != 0; }
```

Moreover, by adding this feature, the following will be possible:
```
public void DoStuff<T>(T x, T y)  where T : IComparable {
    /* Not possible at the moment....
       Instead you're forced to use x.CompareTo(y) < 0
       Which is less readable */
    if (x < y) { 
        moreStuff();
    }
}
```

This is not such a drastic change but it'll be handy :smile:

**Comment by svick** [comment]
At the very least, automatically overloading `==` would be a breaking change. If a class currently implements `IComparable<T>`, but doesn't overload `==`, then using `==` on it will use reference equality. But your proposal would change that to value equality.

**Comment by HaloFour** [comment]
Even with generics that would be a breaking change.  The following is legal today and does perform a reference equality check:

```cs
public static bool IsEquals<T>(T x, T y) where T : class, IComparable<T>
{
    return x == y;
}
```

If the compiler would instead invoke `IComparable<T>.Compare` that could result in a different value or a `NullReferenceException`.

**Comment by iDaN5x** [comment]
Was not considering this issue very deeply, and you're both definitely right.

Maybe it should be limited to `<`, `<=`, `>`, `>=`? 
Not sure if this is worth the time and effort to implement at this form...
what do you think?

**Comment by alrz** [comment]
Probably #5165 or #258 and #5624 could reduce the verbosity of defining of all these operators.

**Comment by AdamSpeight2008** [comment]
'< <= == != => >' should not be automagically be implemented via implementing 'IComparable' or 'IComparable<T>'.  If you want to have the "comparision operators" you can support this by use a lifted type that does. [Exts.Comparisions.Classes.Operators](https://www.nuget.org/packages/Exts.Comparisions.Classes.Operators/)

**Comment by gafter** [comment]
The proposed change would break existing programs.
