### ISSUE TITLE
Add usings is slow in the Interactive Window

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#8637]
Add using in the following submission: `> typeof(ArrayList)`

For another repro, uncomment the integration test scenarios tagged with `https://github.com/dotnet/roslyn/issues/6587`.

**Comment by CyrusNajmabadi** [comment]
Tihs is likely due to the caches we build for adding project/metadata references.  However, as add-using can't add either of those in interactive scenarios, we should probably just skip these codepaths altogether.  I will try to debug through this today to see what's going on.
