### ISSUE TITLE
Local functions: No outlining for local functions.

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#8647]
Should add outlining support here to _collapse/expand_ local functions? See _screenshot_ below.

![image](https://cloud.githubusercontent.com/assets/4213867/13019870/ca3205dc-d186-11e5-8a6b-80a797b8d9bd.png)

**Comment by HaloFour** [comment]
:+1:

**Comment by dpoeschl** [comment]
This is being fixed by @CyrusNajmabadi 's PR #14269, so I'm assigning this over to him.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/14269
