### ISSUE TITLE
Local functions: Nav bar doesn't support local functions

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#8648]
- [ ] Nav bar should say "Local" if caret is inside a local function named "Local"
- [ ] Nav bar should list local functions in its drop down.
- [ ] Nav bar should navigate to local functions if one is selected from the drop down.

![image](https://cloud.githubusercontent.com/assets/4213867/13020077/27c16fde-d188-11e5-95c9-9b1425ef8722.png)

**Comment by DustinCampbell** [comment]
I think we should we consider if we want to show local functions at all, and if we do, how they should be displayed. For now, I think the current behavior's OK.

**Comment by DustinCampbell** [comment]
@Pilchie and I think there's not a lot of value to this one. If we hear feedback we can revisit.

**Comment by miloush** [comment]
For the record I was missing a way to navigate to a local function which I know how it's named or where it was. Be it in the navigation bar or through GoToAll doesn't matter, but there should be a way to get there easily without mouse.
