### ISSUE TITLE
Local functions: do not show up in solution explorer pivots.

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#8652]
In the below scenario, method symbols in solution explorer should be expandable if they have local functions.

![image](https://cloud.githubusercontent.com/assets/4213867/13022294/2d339fb6-d195-11e5-9b60-6ac9ee09b72a.png)

**Comment by DustinCampbell** [comment]
This is similar to the Navigate To case in #8650. We *could* show them in the hierarchy by allowing members to be expanded, but what else should we show? Is this the sort of thing that a file structure view would be better for?
