### ISSUE TITLE
Local functions: Go to Next/Previous methods should work on local functions.

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#8653]
Go to Next/Previous methods should work on local functions as well. Currently, they cycle through top level methods.

```C#
class Class1
{
    public int Main()
    {
        int Local()
        {
            return 1;
        }
        int SecondLocal()
        {
            return 1;
        }
        return Local() + SecondLocal();
    }

    public int Foo(int x)
    {
    }
}     
```

**Comment by DustinCampbell** [comment]
There's a meta-design question of "what is a declaration"? Should we promote locals to this. In this case, we think of this feature as GoToNextMember and GoToPreviousMember and so this wouldn't apply. Again, if we get feedback that shows otherwise once local functions are in use we'll revisit.
