### ISSUE TITLE
Local functions: Call hierarchy search never terminates on local functions.

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#8654]
View Call hierarchy on `Local`, notice that the search never terminates as shown in _screenshot below_.

``` C#
class Class1
{
    public int Main()
    {
        int Local()
        {
            return 1;
        }
        int SecondLocal()
        {
            return 1;
        }
        return Local() + SecondLocal();
    }
}     
```

![image](https://cloud.githubusercontent.com/assets/4213867/13022474/c248b0f4-d196-11e5-901b-0dd8074260fd.png)

**Comment by agocke** [comment]
Dup of #15522
