### ISSUE TITLE
Local functions: do not show up in Object browser or Class view.

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#8656]
Local functions do not show up in CV/OB. 

![image](https://cloud.githubusercontent.com/assets/4213867/13022743/3bc1107e-d198-11e5-9b7d-81776d6805ac.png)

**Comment by HaloFour** [comment]
How would they be visualized in the Object Browser?  The member list is flat, right?  Almost seems like local functions should be nested and collapsed by default, given that they're largely implementation details for their parent method.

**Comment by balajikris** [comment]
Yes, it is a list view, but it could become a treeview if need be. But, I forgot that Roslyn only acts as a data provider to CV and OB and doesn't actually own the UI, so I'm now realizing that this isn't the correct repo for this bug/question :smile: 

> implementation details for their parent method.

Agreed. Given that, should they be browsable, discoverable, navigable and if so, which features should be able to find them, to provide a first class IDE experience for local functions. So, I opened some issues about these to get some discussion started. Some of these may be useful while others not so much. All said, I tend to agree with you on this one that it might not be quite useful.

**Comment by DustinCampbell** [comment]
Triage tends to think that local functions are not members. If we decide to start providing ways to introspect into the bodies of members, showing local functions will make sense then.

**Comment by tmat** [comment]
@DustinCampbell Unless we show local variables and constants we shouldn't show local functions.
