### ISSUE TITLE
Local functions: No line separators

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#8658]
Check option: _Tools -> Options -> Text Editor -> C# -> Advanced -> Show procedure line separators_.

_Actual_: No line separators for local functions.

```C#
class Class1
{
    public int Main()
    {
        int Local()
        {
            return 1;
        }
        int SecondLocal()
        {
            return 1;
        }
        return Local() + SecondLocal();
    }
}  
```

**Comment by DustinCampbell** [comment]
Line separators only separate declaration-level constructs. I think it would be weird to see them inside method bodies.
