### ISSUE TITLE
Create new pr job to validate the nuget.zip

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#8659]
We have been using the a nuget.zip stored in Azure as our restore story for some time. This is because we do not currently have a stable/reliable way to perform nuget restore cross plat.

However, the nuget.zip is frequently missing packages and the lock.json files are, just as frequently, not updated.

We should create a new PR job which performs an actual restore and checks for `project.lock.json` changes as well as missing packages (by comparing the restore output to the contents of the global package cache).

**Comment by tannergooding** [comment]
FYI. @davkean, @jaredpar, @ManishJayaswal

**Comment by tannergooding** [comment]
FYI. @davkean, do to the recent changes, this is likely unneeded now.

**Comment by davkean** [comment]
Yes, we're also actively looking at ways to remove it on Linux/Mac.

**Comment by tannergooding** [comment]
Closing.
