### ISSUE TITLE
[UX] DNX automatic nesting does not provide visual input on the nested files.

### ISSUE THREAD

**Issue by redknightlois** [dotnet/roslyn#8674]
Visual Studio 2015 wont show any file which has the form ```Filename.*.cs``` when the project is a CoreCLR one. CoreCLR does scan those files and build properly, it is just VS2015 which doesnt show them in the solution explorer. 

![roslyn 1](https://cloud.githubusercontent.com/assets/1045411/13029658/0cee67ae-d271-11e5-9452-b817df9619e7.png)
![roslyn 2](https://cloud.githubusercontent.com/assets/1045411/13029660/0f545ed6-d271-11e5-90ed-55ed4817a7ef.png)

Hope this is the proper place to open this issue. I first asked at CoreCLR (https://github.com/dotnet/coreclr/issues/3141)

**Comment by davkean** [comment]
By CoreCLR, do you mean DNX? 

// cc @BillHiebert, where do we file these?

**Comment by DustinCampbell** [comment]
@Pilchie says that this is by design in DNX projects. They automatically nest files that match this pattern.

**Comment by redknightlois** [comment]
@DustinCampbell @Pilchie That is true!!! 

Guys you should do something in regard with UX on this, I have been coding since Visual Studio 6 (in C++) and I haven't realized that there was something different in the "PrefixTree.cs" file. Mind you, I actually filed a bug because I had to resort to find the type and use go to implementation to actually open the relevant file.

I am changing the name of the issue.

**Comment by BillHiebert** [comment]
We have an item on the backlog to address controlling the files that are nested. However, if they are nested the parent file should be expandable.

**Comment by davkean** [comment]
I'll resolve this as external as this code lives outside of Roslyn. @BillHiebert mentioned that he already has an internal backlog item on this. Thanks for the feedback!
