### ISSUE TITLE
[Optimization] Don't use Activator.CreateInstance for generic constructors if known that the target type is a struct

### ISSUE THREAD

**Issue by jamesqo** [dotnet/roslyn#8677]
Now that we've decided to not include parameterless value type constructors in C# 6, can we revert to generating `default(T)` instead of `Activator.CreateInstance<T>` calls for generically-constrained structs? For example, when I type this into [Try Roslyn](http://tryroslyn.azurewebsites.net/#K4Zwlgdg5gBAygTxAFwKYFsDcAoADsAIwBswBjGUogQxBBgGEYBvbGNmfYsmANwHswAExgBZADwAVAHwAKAJQwA7gAtUAJ1QwJMAFwwUa4KWTNW7cxFSKt8nOYC+2e0A):

```csharp
public class C
{
    public void M<T>() where T : struct
    {
        new T();
    }
}
```
I get this output from the decompiler:

```csharp
public class C
{
    public void M<T>() where T : struct
    {
        Activator.CreateInstance<T>();
    }
}
```

**Comment by GeirGrusom** [comment]
Why not let the JIT compiler handle it? There is a difference between `default(T)` and `new T()` so I don't think C# should generate code that can't handle that difference just because C# itself does not.

It seems like RuyJIT currently will invoke `Activator.CreateInstance<T>` even if the struct fits in a single register and the generic method has been inlined.

**Comment by jamesqo** [comment]
@GeirGrusom Is there really a difference? [This](http://tryroslyn.azurewebsites.net/#K4Zwlgdg5gBAygTxAFwKYFsDcAoADsAIwBswBjGFAJ2FORgCFsBvbAX2z0JPNKIEMQIGAGEYLGBJj5iZGADcA9mAAmMALIAKAJRjsk/fL6UYdALwwIqAO4NtOA5IDiwgHQBpVKlwBBEnNQayFr2kuysQAAA=) doesn't seem to suggest so, at least for structs.

Nevertheless, I agree this should also be fixed in the JIT if possible.

**Comment by gafter** [comment]
No, we are not going to have the compiler generate code that would make it fail to interoperate with a possible future revision in which structs can be declared with a no-arg constructor.

**Comment by GeirGrusom** [comment]
@jamesqo `B` doesn't have a parameterless constructor.

**Comment by jamesqo** [comment]
@GeirGrusom I thought we had decided against that for C# 6 though? I read a doc somewhere that said we were initially going to include it, but then reversed it at the last minute.

**Comment by GeirGrusom** [comment]
@jamesqo Yep.

I don't know if C# will actually handle a struct that does have a parameterless constructor, but you can't declare one that has it anyway.

I was just pointing out that the struct you used didn't have one, so it couldn't be called. In generics however the compiler cannot (or should not) make that assumption.
