### ISSUE TITLE
[NuGet Add Using] Duplicate usings are added if you have already imported the namespace

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#8678]
1)

``` C#
using System;
using Newtonsoft.Json.Linq;

public class Program
{
    public class Foo
    {
        public override string ToString()
        {
            JToken
        }
    }
}
```

2) Right-click on JToken, choose using Newtonsoft.Json.Linq -> Find and install latest version

**Expected:** For JSON.NET to be installed, and nothing else:
**Actual:**

``` C#
using System;
using Newtonsoft.Json.Linq; 
using Newtonsoft.Json.Linq; <- Duplicate using

public class Program
{
    public class Foo
    {
        public override string ToString()
        {
            JToken
        }
    }
}
```

**Comment by davkean** [comment]
tag @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
Ooops.  Will fix tonight.

**Comment by CyrusNajmabadi** [comment]
Fixed with: https://github.com/CyrusNajmabadi/roslyn/commit/b969a62988feed86a7b2f4417ff8c990c8cb0af1

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/commit/d08826231c2dd02678c546bc2d5e0584677f27ef
