### ISSUE TITLE
[NuGet Add Using] Unexpected behavior when attempting to resolve Xunit's [Fact]

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#8679]
Given the following:

``` C#

    class Program
    {
        [Fact]
        public void Foo()
        {
        }
```

I expected this to resolve to [xunit's xunit.extensibility.core](http://www.nuget.org/packages/xunit.extensibility.core/2.2.0-beta1-build3239) with ~600,000 downloads. It actually gets resolved to a non-attribute in the [EPPlus](http://www.nuget.org/packages/EPPlus/) with ~480,000 downloads.

Even if EPPlus had more downloads, which it doesn't, I would still expect xunit's attribute to win out here. Interestingly enough, it let's me attempt to resolve again on [Fact], which in this case it does show xunit.

**Comment by davkean** [comment]
tag @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
Nice catch!

**Comment by CyrusNajmabadi** [comment]
Fixed with: https://github.com/dotnet/roslyn/commit/45b6b739851e0f2c99eda6b6f82c68999cbaebf5

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/commit/d08826231c2dd02678c546bc2d5e0584677f27ef
