### ISSUE TITLE
Never let exceptions go unhandled from AnalyzerExecutor.ExecuteAndCatchIfThrows

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#868]
See proposal in comments for #271 to use Action instead of Func for processing analyzer exceptions.

**Comment by heejaechang** [comment]
I hope we use neither action or func, but just let host explicit set try/catch around the driver and deal with exception whatever way they want.

**Comment by mavasani** [comment]
@heejaechang I think that sounds even more dangerous and difficult to track then an explicit catch all in the core ExecuteAndCatchIfThrows method, what if some code new code path needs to invoke into the analyzer but doesn't catch all exceptions or does some custom exception handling?
Having a single point where we callback into the analyzer and wrap it with a try catch and never let exceptions escape seems like the most foolproof strategy. I prefer @jaredpar approach of passing in an Action into AnalyzerExecutor for custom host specific action on exception, but exception should never escape ExecuteAndCatchIfThrows.

**Comment by heejaechang** [comment]
@mavasani not sure functionality wise, someone calling ExecuteAndCatch ... if func or action given is better than, explicitly putting try/catch around action.

**Comment by mavasani** [comment]
@heejaechang Current approach of Func is not better as it decides whether or not to catch exception and exception may escape or go unhandled. However, approach of taking in an Action to do some custom host specific work on exception, such as report non-fatal Watson, is better as we will catch exception, invoke this delegate, but won't allow exception to leave the try catch. Seems more maintainable approach to me.

**Comment by heejaechang** [comment]
@mavasani I am not arguing about that. I am basically saying rather than we provide helper for it. let host (the one that run actions) do that themselves.

- heejae

**Comment by jaredpar** [comment]
@heejaechang that makes the solution ambiguous.  I cannot look at the code and know that exceptions don't escape into the caller.  Having an `Action` makes this completely obvious at a glance what is happening in this code.  No possibility of accidental regressions, bad uses of the `Func`, etc ...

**Comment by heejaechang** [comment]
hmmm if caller (host) decides to let exception escape, what is problem? isn't that host's decision? I understand compiler host doesn't want that to happen. and it is fine for them to catch all. same for IDE however way they decide. but why it shouldn't crash my console app?

**Comment by jaredpar** [comment]
@heejaechang the problem is that if any host can let an exception escape then the exception handling has to be built into the compiler.  The compiler is not resistant to exceptions here and we do not want it to be.  

What should the compiler do?  Let the exception escape all the way out of the compile process?  If so that means callers of the compiler should also except to handle exceptions?  

There is no reason for all of this extra work and design.  If an Analyzer throws it should translate into a `Diagnostic`.  It's the only logical action to take.

**Comment by heejaechang** [comment]
@jaredpar no, compiler can use what you guys are talking about. this helper with Action. I am just saying make it host's implementation. but part of API.

**Comment by jaredpar** [comment]
@heejaechang I am fine with the API taking an `Action` to be applied to the `when` block.  So long as the catch is unconditional my concerns are molified.
