### ISSUE TITLE
[NuGet Add Using] "Find and install latest version" menu item hangs around for a few seconds

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#8681]
The "Find and install latest version" menu item hangs around for a few seconds after you install it, which looks a little unprofessional:

![image](https://cloud.githubusercontent.com/assets/1103906/13031101/6c3ee546-d274-11e5-8ef9-bfaf6e730db2.png)

**Comment by davkean** [comment]
tag @CyrusNajmabadi

**Comment by davkean** [comment]
It actually hangs around for as long as it takes to install the package.

**Comment by CyrusNajmabadi** [comment]
Yes.... i've tried a couple of approaches to deal with this.  

1. Try to explicitly dismiss the light bulb when the suggested action is invoke.  This didn't work.
2. Yield the UI thread and then actually install the package.  Unfortunately, this meant that you don't get the "wait dialog" 

I'm going to talk to the editor guys to see if there is something we can do here.

**Comment by CyrusNajmabadi** [comment]
Fixed with: https://github.com/CyrusNajmabadi/roslyn/commit/26cac1fafd96468c244344d5ef9e3da52261affb

**Comment by michaelcfanning** [comment]
This problem looks fixed in your updated version.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/commit/d08826231c2dd02678c546bc2d5e0584677f27ef
