### ISSUE TITLE
[NuGet Add Using] Undo doesn't undo package install

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#8682]
This is probably a limitation in the NuGet APIs we are using, but undo'ing the package install, undoes the using namespace, but not the package install.

**Comment by davkean** [comment]
tag @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
This shoudl be something we can do.  @jasonmalinowski @Pilchie Are you familiar with the undo infrastructure and what it might take to write our own custom undo handler?

**Comment by Pilchie** [comment]
You need to implement `IOleUndoUnit` and add it to the undo stack. See our [`RenameUndoPrimitive`](http://source.roslyn.io/Microsoft.VisualStudio.LanguageServices/R/08e4b155833c6415.html) for an example.

**Comment by CyrusNajmabadi** [comment]
The approach taken by rename doesn't seem quite applicable to us.  Rename appears to be using the undo stack for a document.  But we're not making any document edits.  It seems like we want to be involved with the vs global undo stack. However, i can't seem to find any documentation on how to manage this functionality.

**Comment by Pilchie** [comment]
See https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.textmanager.interop.ivslinkedundotransactionmanager.openlinkedundo.aspx and the `mdtGlobal` flag then.  Though note I still think you need to put the action onto a specific document.

**Comment by CyrusNajmabadi** [comment]
That's super weird...
Ok, let me see how far i can get.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/CyrusNajmabadi/roslyn/commit/af8799d2c5995e2ba4b6f464a4a1dae19a3ae656

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/commit/d08826231c2dd02678c546bc2d5e0584677f27ef
