### ISSUE TITLE
[NuGet Add Using] We resolve methods, and when we do we don't add "static"

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#8683]
Unsure if this by design that we resolve static methods, but when we do we don't add static to the using 

```
C#
    class Program
    {
        static void Main(string[] args)
        {
            var
        }
    }

```

Right-click resolve, and get:

``` C#
using System.Data.Entity.Core.Common.CommandTrees.ExpressionBuilder.EdmFunctions;

namespace ConsoleApplication19
{
    class Program
    {
        static void Main(string[] args)
        {
            var
        }
    }
}

```

And
```
Error	CS0138	A 'using namespace' directive can only be applied to namespaces; 'EdmFunctions' is a type not a namespace. Consider a 'using static' directive instead
```

**Comment by davkean** [comment]
tag @CyrusNajmabadi

**Comment by davkean** [comment]
There's another bug here - we're not allowed to static import extensions methods, which is what happening above.

**Comment by CyrusNajmabadi** [comment]
fixed with: https://github.com/dotnet/roslyn/commit/b1e065d2e126c43a7c2fbc19ce01d4bd72207c98

This feature is only intended to match types (for now).  We shouldn't even match methods.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/commit/d08826231c2dd02678c546bc2d5e0584677f27ef
