### ISSUE TITLE
[NuGet Add Using] Get offered to bypass NuGet if a project in the solution has the package installed

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#8686]
1. Create two console applications
2. Install EntityFramework into one of the projects
3. In the other project right-click and resolve on `facte`

``` C#
    class Program
    {
        static void Main(string[] args)
        {
            facte
        }
    }

```

__Expected:__ To be offered to resolve to install `EntityFramework` and resolve to `Facet`
__Actual:__ Get offered to directly add a reference to the package binary, bypassing NuGet:

![image](https://cloud.githubusercontent.com/assets/1103906/13031303/d273f8e8-d27d-11e5-9097-45da4979f0ef.png)

**Comment by davkean** [comment]
Looks like we're not spell checking on NuGet packages?

**Comment by davkean** [comment]
tag @CyrusNajmabadi

**Comment by davkean** [comment]
Hmm, even if we were to spell check on NuGet packages this would still happen if the package the other project had referenced wasn't in the index.

**Comment by CyrusNajmabadi** [comment]
I'm going to tweak things so we never off to 'add reference' to something that looks like a nuget package.  We'll want to only use nuget for those guys.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/commit/95a2a5e4339841d5520527df0cc0c9277e610c1a

**Comment by michaelcfanning** [comment]
This still repros in the version I've installed

**Comment by CyrusNajmabadi** [comment]
This is fixed in that we don't offer to add the metadata dll reference.  We *also* don't add a package reference to EntityFramework either.  But that's becaues we don't do spell checking matching for nuget.

This seems like reasonable behavior to have.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/commit/d08826231c2dd02678c546bc2d5e0584677f27ef
