### ISSUE TITLE
[NuGet Add Using] In .NET Framework/Silverlight projects you are offered references from NuGet even if they exist in the .NET Framework

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#8687]
``` C#
    class Program
    {
        static void Main(string[] args)
        {
            CompositionContainer
        }
    }
```

**Expected:** To be offered a reference to System.ComponentModel.Composition.dll from the framework.
**Actual:**

![image](https://cloud.githubusercontent.com/assets/1103906/13031567/a5448910-d286-11e5-9b04-74bb6f3ce555.png)

**Comment by davkean** [comment]
This is really problematic, any common type that happens to also exist on NuGet now gets NuGet suggestions, such HttpClient, SqlConnection, etc which is not what you want:

![image](https://cloud.githubusercontent.com/assets/1103906/13031593/bb8bbd1e-d287-11e5-8def-18a411516d7d.png)

**Comment by davkean** [comment]
tag @CyrusNajmabadi

**Comment by michaelcfanning** [comment]
This is an important bug. We need to understand why CompositionContainer isn't in the index. Will forward to @vScottLouvau

**Comment by michaelcfanning** [comment]
Forwarded this on. This might be an indexing issue. Suggested package has ~6k downloads while Microsoft.Composition has 150K, we should have preferred that option (if it exists in the index).

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/commit/d08826231c2dd02678c546bc2d5e0584677f27ef
