### ISSUE TITLE
[NuGet Add Using] We should simplify menu if there is only a single choice

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#8689]
With below, I keep finding myself clicking the first menu to install the package:

![image](https://cloud.githubusercontent.com/assets/1103906/13031667/1d4556a8-d28a-11e5-99f8-eee9c8c41ee6.png)

If there's only one choice, we should get rid of the sub menu.

**Comment by CyrusNajmabadi** [comment]
I actually disagree.  This change in how the smart tag works really calls out that this is not the normal 'add using' codepath.  If anything, this should help draw people's attention to the fact that we're going and installing something.  Ideally with this, and the glyph you get:

![image](https://cloud.githubusercontent.com/assets/4564579/13031967/d901bec6-d295-11e5-932b-64cc0b0fd954.png)

It's more clear that this is more than just a simple text change.

**Comment by michaelcfanning** [comment]
I agree with Cyrus on this, particularly as I think there's a potential to add additional content in the 2nd level menu (such as options for invoking actual nugget pkg mgr ui, option to install latest pre-release, etc).
