### ISSUE TITLE
[NuGet Add Using] Very unobvious that a package failed to install

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#8690]
When a package fails to install, I only get notification in the status bar:

![image](https://cloud.githubusercontent.com/assets/1103906/13031699/1fcdff14-d28b-11e5-82cb-864efea4de8c.png)

This is extremely unobvious. Can we come up with something better?

**Comment by CyrusNajmabadi** [comment]
Good feedback.  We should be able to at least give a dialog for the failure case.

**Comment by davkean** [comment]
@CyrusNajmabadi It would be great if the shell had a better mechanism for notifying the user that it failed, without showing a modal dialog .

**Comment by CyrusNajmabadi** [comment]
Agreed... but in the interim... :)

**Comment by michaelcfanning** [comment]
Note that it's pretty easy to provoke failure msgs that exceed available screen UI. In this case, there's no pop-up that allows users to read the complete error message. We might want to fix that problem, at least, if we cannot invest an a better reporting mechanism.

![image](https://cloud.githubusercontent.com/assets/13526455/13037417/62196cbe-d335-11e5-82ed-e34ed16e92db.png)

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/9353
