### ISSUE TITLE
[NuGet Add Using] When a package fails to install, we still add the "using"

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#8691]
1) Choose Manage NuGet Packages, next to package sources choose the Cog
2) Uncheck all package sources
3) 
``` C#
class Program
{
    static void Main(string[] args)
    {
        jtoken
    }
}
```

4) Resolve jtoken to Newtonsoft.Json

__Expected:__ Package fails to install and nothing happens
__Actual:__ Package fails to install, but we still install the using:

``` C#
using Newtonsoft.Json.Linq;

class Program
{
    static void Main(string[] args)
    {
        jtoken
    }
}
```

**Comment by CyrusNajmabadi** [comment]
hrm... tricky.  These are two different operations and it's not clear how to make both changes in one immutable step.  

One thing that might help would be to try to do the nuget step first, and if that fails pass something back to the code actions infrastructure to let it know to stop processing further operations...

**Comment by michaelcfanning** [comment]
Would be nice to revert the using, agree. CTRL-Z will remove the using statement, however, so I wouldn't block for update2 if a fix looks complex.

**Comment by Pilchie** [comment]
Does this still repro now that you have a global undo?

**Comment by CyrusNajmabadi** [comment]
Yes, it still reproes.  Currently there is no way to have a failure in one operation "roll tings back".  

All my global undo stuff did was make it so you could undo both the "using" and hte nuget-install in one action.
