### ISSUE TITLE
[NuGet Add Using] When you have no package sources, status bar says "Package install failed: primarySources"

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#8692]
1) Right-click on the project, choose Manage NuGet Packages, next to package sources choose the Cog
2) Uncheck all package sources
3) Click OK
4) Attempt to resolve the following:
``` C#
class Program
{
    static void Main(string[] args)
    {
        jtoken
    }
}
```

Get:
![image](https://cloud.githubusercontent.com/assets/1103906/13031755/059ed36a-d28c-11e5-8047-30e13c5f684e.png)

I'm guessing this isn't our bug, but can you make sure?

**Comment by CyrusNajmabadi** [comment]
We're the one that puts that info in the status bar.  Let me start a conversation as to how i can find out what package sources you have.  If you dont' have any (or don't have nuget.org) then we shouldn't be offering this feature.

**Comment by CyrusNajmabadi** [comment]
actually, i don't see that error.  I see this one:

![image](https://cloud.githubusercontent.com/assets/4564579/13066236/d8164c96-d418-11e5-871d-e9227d294d0a.png)

Now, the grammar is bad (and i have a PR out with the nuget guys to address that).  But i think the overall message is acceptable.

I'm not sure how you got this specific error.

**Comment by CyrusNajmabadi** [comment]
Fixed with: https://github.com/CyrusNajmabadi/roslyn/commit/eff6f9b1b0e5d354fd2ef836ddf8d05cc498b670

**Comment by CyrusNajmabadi** [comment]
This has been fixed.  We only offer this feature if you have the "nuget.org" package source selected.
