### ISSUE TITLE
[NuGet Add Using] It would be nice to be able to see what which projects have which version of the package

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#8693]
Below it would be great to be able to see which projects were using which version of the NuGet package:
![image](https://cloud.githubusercontent.com/assets/1103906/13031776/da767282-d28c-11e5-873f-ce2888cf9d52.png)

Maybe in the preview?

**Comment by CyrusNajmabadi** [comment]
Let me see what i can do about this.  I'll likely add it to the preview but not the smart tag.  It would clutter things up way too much there.

**Comment by CyrusNajmabadi** [comment]
This is what it looks like now:

![image](https://cloud.githubusercontent.com/assets/4564579/13032497/f30b13d0-d2a9-11e5-80c2-c0608e351bb3.png)

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/commit/be5019d7d987e2122d148a14666a70cea8db9843

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/commit/d08826231c2dd02678c546bc2d5e0584677f27ef
