### ISSUE TITLE
Project System: When there's no source control, the source control menu shouldn't be visible

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#8696]
![image](https://cloud.githubusercontent.com/assets/1103906/13257252/ec4f2c24-da02-11e5-8d4f-ae0cfb1f4c2b.png)

**Comment by miloush** [comment]
Do you mean the Add to source control should be directly on the menu?

**Comment by davkean** [comment]
"Add to source control" is on the solution. The project should have no source control commands if it isn't connected to source control.

**Comment by miloush** [comment]
Oh I see, that wasn't really visible from your screenshot or description. Interestingly enough though, I do have add solution to source control on project context menu... maybe it is TFS/Git dependent?

**Comment by davkean** [comment]
Yeah, it might be source control plug-in dependent, so what it really should say is "if there are no commands enabled, we should display the sub menu".

**Comment by davkean** [comment]
This issue was moved to dotnet/roslyn-project-system#94
