### ISSUE TITLE
IOperation support for pattern-matching operations

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#8699]
We need to design and implement IOperation support for pattern-matching language constructs.

**Comment by mavasani** [comment]
@gafter @jinujoseph Is someone from the compiler team going to implement this?

**Comment by gafter** [comment]
Yes, this is on my plate for 15.3 (aka Update 1, I think).

**Comment by tmat** [comment]
Let's figure out what needs to be done here, if anything.

**Comment by mavasani** [comment]
Done with https://github.com/dotnet/roslyn/pull/20276
