### ISSUE TITLE
Rule set editor should show disabled rules by default

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn#87]
By default, the rule set editor hides suppressed/disabled rules. There's a button in the tool bar to show these rules, but it is not obvious. This just makes it harder to find the rules you want to tweak.

Once issue #86 is dealt with we should change default to show the suppressed/disabled rules.

**Comment by tmeschter** [comment]
The rule set editor has been updated to make this the default.

**Comment by giggio** [comment]
:+1: Nice!

**Comment by tmeschter** [comment]
Assigning to @mavasani for verification.
