### ISSUE TITLE
Exception from Roslyn analyzer

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#8700]
The following exception caused my Roslyn build (with changes) to fail after a large merge operation.

```none
  CSC : error AD0001: Analyzer 'Roslyn.Diagnostics.Analyzers.ApiDesign.DeclarePublicAPIAnalyzer' threw an exception of type 'System.ArgumentException' with message 'An item with the same key has already been added.'. [D:\Roslyn-Patterns\src\Compilers\CSharp\Portable\CSharpCodeAnalysis.csproj]
```

THIS IS NOT HELPFUL. There is no obvious way to determine what the problem is.

**Comment by gafter** [comment]
@jaredpar This is blocking my merge from future into features/patterns.

**Comment by jaredpar** [comment]
@gafter do you have a link to a commit where this repros?  Have you tried attaching and seeing where the exception is coming from?

**Comment by mavasani** [comment]
Seems a dupe of https://github.com/dotnet/roslyn-analyzers/issues/829

**Comment by srivatsn** [comment]
Closing as dupe.
