### ISSUE TITLE
[nuget add using] it would be helpful to have an option to invoke nuget pkg mgr ui

### ISSUE THREAD

**Issue by michaelcfanning** [dotnet/roslyn#8705]
I don't believe the nuget API provides hooks for this. This option would be quite helpful, particularly as we are being very conservative about the suggestions we provide (i.e., we only give a single package option). If there are two high volume packages that share a common public type name, we would do better to either show both these options or to allow users to quickly jump into the nuget pkg mgr. 

@CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
Is it common to have two high volume packages with the same type names?

Also, currently Elfie does not provide any information about how popular things are.  It just gives me ordered results.

We'd need popularity information to determine if we should include multiple matches.

---

As far as i understand, elfie has popularity levels (based on power of 2 iirc).  If that's the case, we might want to only allow finding and showing additional results only if they're within a popularity level of the top hit.

i.e. if we have a package that has a million hits, we'd include another that was > 500k results.  But we wouldn't bother if hte popularity level was >1.  At that point we could just assume that by relative popularity that there would be little point in including the second.

**Comment by michaelcfanning** [comment]
this is a good idea. I still tend to think that an option to jump into the nugget package manager UI would be helpful.

**Comment by CyrusNajmabadi** [comment]
Fixed with: https://github.com/CyrusNajmabadi/roslyn/commit/d4c4a3b51e910d143c70771a864efbacdff19e88

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/commit/d08826231c2dd02678c546bc2d5e0584677f27ef
