### ISSUE TITLE
[nuget add using] missing text in negative error message

### ISSUE THREAD

**Issue by michaelcfanning** [dotnet/roslyn#8707]
Package install failure message doesn't scan well:

Package install failed: No latest version found for the 'Newton.Json' for the given source repositories and resolution context.

We should either add 'package' after the package name or emit the 'the' that precedes the package name.

@CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
> We should either add 'package' after the package name or emit the 'the' that precedes the package name.

We don't own this.  THis is the exception message provided by NuGet.VisualStudio.

**Comment by DustinCampbell** [comment]
Hey @michaelcfanning, could you file this on the NuGet home repo?

**Comment by michaelcfanning** [comment]
@DustinCampbell did as you suggested. thanks!
