### ISSUE TITLE
[nuget add using] add option for 'latest pre-release'?

### ISSUE THREAD

**Issue by michaelcfanning** [dotnet/roslyn#8708]
Is it important for users to have the option to add the latest pre-release? It might not be, particularly if we add the ability to jump into the Nuget package mgr. UI.

It could also be a setting to make this available or not.

**Comment by DustinCampbell** [comment]
Hey @CyrusNajmabadi, giving this to you to keep thinking about. But now that we show the NuGet Package Manager UI, maybe it's less important.

**Comment by DustinCampbell** [comment]
@Pilchie thinks we did something around this but isn't sure what it was. Moving to 1.3.

**Comment by DustinCampbell** [comment]
Hey @CyrusNajmabadi -- isn't this already done?

**Comment by michaelcfanning** [comment]
Definitely not in for update 2. We do not have a general API from NuGet yet to install latest pre-release (with no other version information). To mitigate this limitation, we put explicit version information in the index for packages with only pre-release versions (so that the feature could explicitly request install of that version).

My information is stale. Cyrus can bring us up-to-date, I'd like to know, too.

**Comment by CyrusNajmabadi** [comment]
Closing out.  We haven't heard any requests for this. I don't like keeping bugs open for speculative issues.  If we hear about this from customers we can certainly do something in this area.
