### ISSUE TITLE
[nuget add using] add 2-3 most recent stable major versions?

### ISSUE THREAD

**Issue by michaelcfanning** [dotnet/roslyn#8709]
We could consider adding multiple major releases to the update ui. We could take the most recent Major.Minor release, or the last release of the most recent major releases. For JSON.Net, for example, these would be 8.02, 7.01 and 6.08.

**Comment by michaelcfanning** [comment]
@CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
In order to do this, Elfie would have to provide that information.  It's not information i have available at the point that our code action runs.  It's also not something i want to make a network call for during our background processing.

That said, i don't see why Elfie could not provide this information.

**Comment by michaelcfanning** [comment]
Elfie providing it would create additional churn in the index, increasing patch size. Lots of packages are updated frequently, so I'd expect this to appreciably impact patch sizes.

**Comment by CyrusNajmabadi** [comment]
We should run some tests to see if that was the case.  This would just be data at the package level.  And we only have 4k packages in the db.  I'm really curious, on a daily level, what amount of churn that would honestly be...

**Comment by DustinCampbell** [comment]
I'll let you and @michaelcfanning keep thinking about this. :smile:

**Comment by Pilchie** [comment]
Moving to unknown for now.  Let's wait and see what feedback we get here.

**Comment by CyrusNajmabadi** [comment]
Have not gotten any feedback about this.  Closing out.
