### ISSUE TITLE
DebuggerDisplayAttribute and ImmutableArray<> bug

### ISSUE THREAD

**Issue by ViIvanov** [dotnet/roslyn#871]
1. Create a default Console Application in a MSVS 2015 CTP 6.
2. Add reference to a System.Collections.Immutable.1.1.33-beta
3. Replace code in Program.cs to:
  ```cs
  using System.Collections.Immutable;
  using System.Diagnostics;

  static class Program
  {
    static void Main() {
      var test = new Test();
    } // Set breakpoint here
  }

  [DebuggerDisplay("Items = {Items.Length}")]
  class Test
  {
    private ImmutableArray<int> Items { get; } = ImmutableArray.Create(1);
  }
```
4. Run debugger.
5. When debugger stops at breakpoint, move mouse pointer over a "test" variable. Tooltip shows

  > "test = Items = The debugger is unable to evaluate this expression".

Should be
  > "test = Items = 1".

**Comment by tmat** [comment]
Although this is a bug that should be fixed, using arbitrary expressions in debugger display attribute is not recommended. Use a simple identifier or a parameter-less method call. See "Using Expressions in DebuggerDisplay" in article https://msdn.microsoft.com/en-us/library/x810d419.aspx.

**Comment by ViIvanov** [comment]
Thanks, @tmat, I will use right expressions!

**Comment by KevinH-MS** [comment]
Hi @ViIvanov, I'm not sure exactly which commit fixed this, but you should be able to see it working correctly in Visual Studio 2015 RC (https://www.visualstudio.com/en-us/downloads/visual-studio-2015-downloads-vs.aspx).

**Comment by ViIvanov** [comment]
Hello @KevinH-MS! I just tried it and it works fine! Thanks a lot!
