### ISSUE TITLE
Please consider to extend Linq to add a new keyword leftjoin or rightjoin

### ISSUE THREAD

**Issue by uyhung** [dotnet/roslyn#8710]
Please consider to extend Linq to add a new keyword leftjoin or rightjoin. I'm sure a lot of .NET developers dream about this keyword when doing LEFT JOIN using SingleOrDefault() in conjunction with  "into". Mimic left join using SingleOrDefault + "into" is very unclear. The same issue with how we do with Group By. 
By supporting this keyword you really bring Linq to a higher level.

**Comment by DavidArno** [comment]
Could you please expand this request with some details of how left and right joins are currently achieved with linq, how they might be achieved with method chaining and how the proposed query syntax might translate into a method chain?

**Comment by HaloFour** [comment]
For reference:

[How to: Perform Left Outer Joins (C# Programming Guide)](https://msdn.microsoft.com/en-us/library/bb397895.aspx)

```cs
 var query = from person in people
             join pet in pets on person equals pet.Owner into gj
             from subpet in gj.DefaultIfEmpty()
             select new { person.FirstName, PetName = (subpet == null ? String.Empty : subpet.Name) };
```

**Comment by svick** [comment]
I don't think outer joins are actually a common operation in LINQ. In SQL, everything has to be returned in a single flat table, so outer join makes perfect sense. But in LINQ, you have group joins, which I believe are much more natural and easier to work with.

**Comment by HaloFour** [comment]
@svick 

If you're dealing with a 1:1 or 1:0..1 relationship and you want to flatten that result into an anonymous type you are still required to jump through these hoops.  It's not pleasant and often trips up junior devs.

**Comment by svick** [comment]
@HaloFour Yes, but what I'm trying to say is that you shouldn't need to flatten results in common cases. If you do, you're writing a more complicated query and in return you get something that's harder to work with. Just return the group directly (i.e. something like `select new { person, pets = gj }`).

**Comment by HaloFour** [comment]
@svick 

If you were flattening the results in the query it's likely that you need to get the final results in a flattened shape anyway, so using group join doesn't fix anything it just moves the problem downstream.  Not to mention since queryable providers recognize the outer join pattern and understand the relationships that it entails they will create much more optimized SQL for it.

**Comment by uyhung** [comment]
Guys I'm not taking whether there's a better way to do outer join in Linq, I just wanna suggest extending the LINQ to bring it up to a higher level of readability, stylish, more SQL-like. When I'm showing some examples of Linq to my friends who are working on other technology stacks such as PHP, Java etc. at the first glance looking at simple code samples they all say "wow it's great!", but when it comes to show demo about how to do Linq with outer join, group by, having etc... their face looks a little silly :)

**Comment by Unknown6656** [comment]
_I know that this comment is slightly out of place_, but I would rather like to see 'small' functions like `Count`, `Sum`, `FirstOrDefault`, `LastOrDefault`, `Reverse` etc. implemented in LINQ than `LeftJoin` or `RightJoin` -- but maybe this is my personal opinion :)

**Comment by gafter** [comment]
Issue moved to [dotnet/csharplang #361](https://github.com/dotnet/csharplang/issues/361) via [**ZenHub**](https://www.zenhub.com/)
