### ISSUE TITLE
Should not indent inside verbatim interpolated strings

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#872]
Hit enter inside:

``` C#
var s = $@"";
```

*Result*
Indented 4 spaces past `var`.

*Expected*
Caret in column zero.

**Comment by basoundr** [comment]
There are other scenarios that needs to be handled as well when entering Return at `$$`

I would assume the below scenarios get zero indentation and start at the beginning of the new line
1. `var s = $@"$$"` - repro case
2. `var s = $@"There is some text$$"`
3. `var s = $@"There is some text $${variable}"`
4. `var s = $@"There is some text {variable}$$"`

There are some other scenarios where the line break is introduced within braces of the interpolation syntax
1. `var s = $@"There is some text {$$StaticClass.memb}"` 
and the expected result will be
```
        var s = $@"There is some text {
        StaticClass.memb
```
where the indentation is same as the previous line
2.
```
        var s = $@"There is some text {
             StaticClass$$.memb}"
```
and the expected result will be
```
        var s = $@"There is some text {
             StaticClass
             .memb}"
```

We currently return the above results but I don't know if there are unit test cases that will prevent regression. Does this behavior seems legit?

We also have cases like 
`Console.WriteLine($@"PPP{ ((Func<int>)(() => {$$ return number; })).Invoke():(408) ###-####}");`
 What happens then? Do we still move it to the same column as the previous line? The current behavior places the new line at `columnOfPreviousLine + oneIndentation`

@Pilchie @DustinCampbell @heejaechang Would be nice to have your opinion here.

Hopefully I covered all the scenarios.

**Comment by Pilchie** [comment]
For your case 1 (`var s = $@"There is some text {$$StaticClass.memb}"`) we should indent one additional level.

For the case you mention inside the lambda, I think the current behavior is correct.  In general if something isn't the start of a statement then we want it to be indented to show that it's part of the previous line.
