### ISSUE TITLE
CSharpExpressionEvaluator is flaky

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#8725]
This test failure occurred when merging from master into future.

PR: [#570#issuecomment-184513297](https://github.com/dotnet/roslyn-internal/pull/570#issuecomment-184513297) *Merge master into future* by @vslsnap
Failure: http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_vsi_p2/137/

**1 Test Failures:**
CSharpExpressionEvaluator.Validate Locals Window

System.Exception: Locals Window contains an unexpected number of entries. Expected: 20, Actual 0

**Issue 1: Individual TAO Test Failure**
Failing integration tests: 

CSharpExpressionEvaluator.xml

@dotnet/roslyn-interactive

**Comment by davkean** [comment]
@tannergooding Did you disable this?

**Comment by amcasey** [comment]
The screenshots show a blank Locals window.  That looks like a legitimate failure.

**Comment by amcasey** [comment]
http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_vsi_p2/137/artifact/Open/Binaries/Release/VSIntegrationTestLogs/CSharpExpressionEvaluator.html

**Comment by amcasey** [comment]
Looking.

**Comment by davkean** [comment]
This could be a real failure, @brettfo ran into this installing the latest build.

**Comment by brettfo** [comment]
My issue wasn't related to this.  I must have double-clicked a locally-built Roslyn.VisualStudio.Setup.vsix because I had 42.42.42.42 of all of the Roslyn extensions installed into my root hive _except_ for the EE components were still 1.2.  I fixed it by manually removing the 42 extension and re-running IDF.

**Comment by amcasey** [comment]
I don't think the lab had a binary mismatch since at least one expression was successfully evaluated in the Immediate window.

**Comment by tannergooding** [comment]
@davkean, no. I only disabled a single scenario in BasicExpressionEvaluator. All other integration tests were passing.

**Comment by amcasey** [comment]
@davkean Basic EE has been flaky for a long time, but C# EE is generally stable.

**Comment by amcasey** [comment]
Passes on my box.

**Comment by amcasey** [comment]
I'm having trouble getting extensions to deploy: https://github.com/dotnet/roslyn/issues/8782.  Hopefully, the lab isn't also running old bits.

**Comment by tannergooding** [comment]
The lab is manually deploying extensions with VSIXExpInstaller due to some issues we ran across involving deployment.

**Comment by genlu** [comment]
We hit this again:
http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p2/278/

**Comment by amcasey** [comment]
I've sorted out vsix deployment and I still can't repro the issue.  I'm guessing the locals are just taking longer than usual to show up.  Has the lab been under increased load?

**Comment by amcasey** [comment]
It looks like we assume the locals are present by the time the window has keyboard focus.  I'm not sure the two are actually connected - I think the window is "loaded" before it's "populated".

**Comment by amcasey** [comment]
I notice that the Locals window action has a substantial amount of logging - this suggests that we've previously had problems in this area.

**Comment by amcasey** [comment]
I see from the screenshot that the Diagnostic Tools window is being displayed.  @tannergooding, was that enabled before we switched to update 1?  I believe it adds some overhead that might be slowing this down just enough to cause the problem.

**Comment by amcasey** [comment]
These are all the occurrences of which I'm aware:
http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p2/274/
http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p2/278/
http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p2/280/

**Comment by amcasey** [comment]
Failures are spread across machines 1, 2, 7, and 9.

**Comment by tannergooding** [comment]
@amcasey, I believe we explicitly disabled it in the previous images.

**Comment by amcasey** [comment]
How do we feel about disabling it again?  It makes the test less realistic, but probably more stable.

I'm still investigating workarounds.

**Comment by davkean** [comment]
Is there a timeout we can increase? Would prefer not to touch the image if we can avoid it.

**Comment by amcasey** [comment]
@davkean Understood.  I'll see if there's a change I can make to the test instead.

**Comment by amcasey** [comment]
I ran it 30 times consecutively on my box.  Most runs took a little under 80 seconds.  Two runs failed at 13602 and 2488 seconds.  My box wasn't under load, so something whacky is going on.

**Comment by amcasey** [comment]
Huh, I have a log entry `Disable Diagnostics Hub (Roslyn hive)`.  Maybe the test was disabling it directly and that stopped working in Update 1.

**Comment by amcasey** [comment]
The regkey used by `DebugAction.EnusreDiagnosticsHubDisabled` has no apparent effect on my box.

**Comment by amcasey** [comment]
I've made an internal change that I believe will resolve this issue.

**Comment by jinujoseph** [comment]
seeing this still http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/future-stabilization/job/windows_vsi_p2_prtest/20/

**Comment by balajikris** [comment]
@dotnet/roslyn-infrastructure can we please disable this? this has been flakey for a long time and the test is still enabled while no one is looking at it.

**Comment by ManishJayaswal** [comment]
@drognanar can you take a look at this test? I thought Andrew had fixed this when he figured out a way to disable diagnostic window but looks like this test is still flaky.

**Comment by tannergooding** [comment]
I believe this was fixed (or at least it no longer seems to be occurring) after I updated our reference binaries to those that shipped with Update 3 (#12261 and internal 1159).
