### ISSUE TITLE
Non-RDT buffers (Annotate, Compare Files, etc.) do not classify or populate NavBar

### ISSUE THREAD

**Issue by ViIvanov** [dotnet/roslyn#873]
I have a C# project that hosted on GitHub. When I execute for a .cs-file command Annotate from a context menu in a Solution Explorer, Annotate window displayed without coloring:

![gitannotatewithoutcoloring](https://cloud.githubusercontent.com/assets/795200/6380417/8d75715c-bd4a-11e4-8efd-69c091e2e29b.png)

MSVS 2015 CTP 6

(@dpoeschl) Edit: This also occurs in the Compare Files modal window:

![image](https://cloud.githubusercontent.com/assets/235241/7547273/d8cbc962-f59e-11e4-8119-a9f75b020e30.png)

(@dpoeschl) Edit: This also occurs in the Merge Conflict Resolution Window:

![image](https://cloud.githubusercontent.com/assets/235241/7556443/edcc591c-f724-11e4-850e-a074a2acbf53.png)

**Comment by Pilchie** [comment]
@dpoeschl I believe you already have some bugs about files opened by TFS not being part of the workspace - can you take a look at this as well?

**Comment by dpoeschl** [comment]
Related to internal work items 1066504, 1069385

**Comment by dpoeschl** [comment]
Also repros with TFS.

**Comment by dpoeschl** [comment]
The document is not added to the RDT, and so we do not currently process it. Editing title to reflect.

**Comment by dpoeschl** [comment]
Adding Compare Files repro from @shyamnamboodiripad's internal bug #1066504.

**Comment by dpoeschl** [comment]
Adding a Merge Conflict Resolution Window repro from @shyamnamboodiripad's internal bug #1069385.

**Comment by dpoeschl** [comment]
Moving to 1.1 as per #3374

**Comment by Pilchie** [comment]
This was fixed by #6392

**Comment by v-codeel** [comment]
According to discussion on #6658, this was supposed to be reactivated for ```1.2```.

**Comment by CyrusNajmabadi** [comment]
The compare-files window does show the navbars:

![image](https://user-images.githubusercontent.com/4564579/198698089-4e8a2d98-b8a1-436c-ab9d-bda1ab0b2099.png)

Closing out as the built-in scenarios seem to be working, and we haven't heard additional requests for this.
