### ISSUE TITLE
[nuget add using] can't resolve a fully qualified type name

### ISSUE THREAD

**Issue by michaelcfanning** [dotnet/roslyn#8730]
'commandline' is a commonly defined element of nuget package types and namespaces. I tried to add a reference to the 'command line library' package, which I frequently use, and was unable to do so. CommandLine.Parser is the commonly used type in application entry points that invoke this package. CommandLine is taken as a type name elsewhere and Parser is take by a more popular package as well. I then tried the fully qualified name without success (we try to query the first element as a type name).

Repro: 1) new console app, 2) type 'CommandLine.Parser' in entry point
Result: feature locates CommandLineParser type in Magnum package
Preferable: feature detects CommandLine.Parser itself is a match to fully qualified type in command line library package.

Another approach would be to keep current behavior and then add the additional resolution option if we match the complete type name as well.

**Comment by Pilchie** [comment]
Moving to 1.3.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback on this.
