### ISSUE TITLE
Color suggestion in editor is incorrect when using Dark theme

### ISSUE THREAD

**Issue by Pvlerick** [dotnet/roslyn#8735]
When in "Dark" theme, the color suggestions seem to be inverted, e.g: "white" will show a black box and "black" will show a white one. This does not happen in "Light" or "Blue" themes.

![image](https://cloud.githubusercontent.com/assets/4704411/13084951/21745752-d4dc-11e5-923f-a5cb42b28048.png)

![image](https://cloud.githubusercontent.com/assets/4704411/13084988/5a91905e-d4dc-11e5-8e17-71bc07a5504f.png)

These screenshot where made in the editor for a CSS file, I don't know if other file types are affected.

(Sorry if this is a duplicated, I searched in the defect backlog but couldn't find anything.)

**Comment by Pilchie** [comment]
Thanks for the report.  However, the css editor isn't part of the Roslyn project.  This should probably be filed either in Asp.NET, or Connect.  @barryta @madsk - do you have a suggestion?

**Comment by madskristensen** [comment]
This has been fixed already and will be in a future update to VS

**Comment by Pvlerick** [comment]
Ok!
