### ISSUE TITLE
Implement Setup.csx/cleanup.csx (pull sources, build, ngen)

### ISSUE THREAD

**Issue by KevinH-MS** [dotnet/roslyn#8736]
Note: the pull/build should probably be a separate script

**Comment by TyOverby** [comment]
The test-specific sources are pulled in by the test runner individually.  This makes it so that a dev who only wants to run one perf-test only downloads the project that he's interested in.

**Comment by KevinH-MS** [comment]
Fixed by https://github.com/TyOverby/roslyn/pull/1
