### ISSUE TITLE
Determinism is failing for Microsoft.VisualStudio.ProjectSystem.Managed.dll in future

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#8739]
All determinism builds are failing in future due to determinism failing for Microsoft.VisualStudio.ProjectSystem.Managed: http://dotnet-ci.cloudapp.net/job/roslyn_future_determinism/11/console

**Comment by davkean** [comment]
tag @jaredpar

**Comment by jaredpar** [comment]
Testing of this binary is disabled.  I did the disable in master so it won't take hold in future until the next merge.

**Comment by davkean** [comment]
Make sure when this is fixed, that we move it from the skip list in build/scripts/test-determinism.ps1.
