### ISSUE TITLE
Implement "Reporting functionality" (parse etl, generate csv/json, copy to share)

### ISSUE THREAD

**Issue by KevinH-MS** [dotnet/roslyn#8740]
This can either be a standalone .csx or a .csx under util that can be loaded by tests.  It sounds like we're leaning on the latter (tests will report themselves, and there will be switches to control upload, etc).

**Comment by gafter** [comment]
@KevinH-MS Kevin, can you please assign an area label to this issue? I can't tell exactly what it is about.

**Comment by KevinH-MS** [comment]
Done!
