### ISSUE TITLE
Assert fired for IBinaryOperatorExpression while running Operation analyzer

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#8742]
Message: `Unexpected value 'Enum' of type 'Microsoft.CodeAnalysis.CSharp.BinaryOperatorKind'`

Analyzer: `System.Runtime.Analyzers.TestForNaNCorrectlyAnalyzer`

Dump: `<%internal_share%>\public\mavasani\OperationAnalyzerDump\IBinaryOperatorExpression\devenv.dmp`

Call stack:
>  	Microsoft.CodeAnalysis.dll!Roslyn.Utilities.ExceptionUtilities.UnexpectedValue(object o) Line 13	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Expression.DeriveBinaryOperationKind(Microsoft.CodeAnalysis.CSharp.BinaryOperatorKind operatorKind) Line 2730	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundBinaryOperator.Microsoft.CodeAnalysis.Semantics.IBinaryOperatorExpression.BinaryOperationKind.get() Line 1055	C#
 	System.Runtime.Analyzers.dll!System.Runtime.Analyzers.TestForNaNCorrectlyAnalyzer.Initialize.AnonymousMethod__8_0(Microsoft.CodeAnalysis.Diagnostics.OperationAnalysisContext operationAnalysisContext) Line 53	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteOperationAction.AnonymousMethod__1() Line 521	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer analyzer, System.Action analyze, Microsoft.CodeAnalysis.Diagnostics.AnalysisContextInfo? info) Line 1076	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows(Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer analyzer, System.Action analyze, Microsoft.CodeAnalysis.Diagnostics.AnalysisContextInfo? info) Line 1057	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteOperationAction(Microsoft.CodeAnalysis.Diagnostics.OperationAnalyzerAction operationAction, Microsoft.CodeAnalysis.Semantics.IOperation operation, Microsoft.CodeAnalysis.ISymbol containingSymbol, Microsoft.CodeAnalysis.SemanticModel semanticModel, System.Action<Microsoft.CodeAnalysis.Diagnostic> addDiagnostic, Microsoft.CodeAnalysis.Diagnostics.AnalysisState.OperationAnalyzerStateData analyzerStateOpt) Line 520	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteOperationActions(Microsoft.CodeAnalysis.Semantics.IOperation operation, System.Collections.Generic.IDictionary<Microsoft.CodeAnalysis.Semantics.OperationKind, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Diagnostics.OperationAnalyzerAction>> operationActionsByKind, Microsoft.CodeAnalysis.ISymbol containingSymbol, Microsoft.CodeAnalysis.SemanticModel model, System.Action<Microsoft.CodeAnalysis.Diagnostic> addDiagnostic, Microsoft.CodeAnalysis.Diagnostics.AnalysisState.OperationAnalyzerStateData analyzerStateOpt) Line 1024	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteOperationActions(System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Semantics.IOperation> operationsToAnalyze, System.Collections.Generic.IDictionary<Microsoft.CodeAnalysis.Semantics.OperationKind, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Diagnostics.OperationAnalyzerAction>> operationActionsByKind, Microsoft.CodeAnalysis.ISymbol containingSymbol, Microsoft.CodeAnalysis.SemanticModel model, System.Action<Microsoft.CodeAnalysis.Diagnostic> addDiagnostic, Microsoft.CodeAnalysis.Diagnostics.AnalysisState.OperationAnalyzerStateData analyzerStateOpt) Line 1006	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteOperationActionsCore(System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Semantics.IOperation> operationsToAnalyze, System.Collections.Generic.IDictionary<Microsoft.CodeAnalysis.Semantics.OperationKind, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Diagnostics.OperationAnalyzerAction>> operationActionsByKind, Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer analyzer, Microsoft.CodeAnalysis.ISymbol containingSymbol, Microsoft.CodeAnalysis.SemanticModel model, Microsoft.CodeAnalysis.Text.TextSpan filterSpan, Microsoft.CodeAnalysis.Diagnostics.AnalysisState.OperationAnalyzerStateData analyzerStateOpt, bool isGeneratedCode) Line 980	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteOperationActions(System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Semantics.IOperation> operationsToAnalyze, System.Collections.Generic.IDictionary<Microsoft.CodeAnalysis.Semantics.OperationKind, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Diagnostics.OperationAnalyzerAction>> operationActionsByKind, Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer analyzer, Microsoft.CodeAnalysis.SemanticModel model, Microsoft.CodeAnalysis.Text.TextSpan filterSpan, Microsoft.CodeAnalysis.SyntaxReference declaration, int declarationIndex, Microsoft.CodeAnalysis.ISymbol declaredSymbol, Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState analysisStateOpt, bool isGeneratedCode) Line 960	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver<Microsoft.CodeAnalysis.CSharp.SyntaxKind>.ExecuteDeclaringReferenceActions(Microsoft.CodeAnalysis.SyntaxReference decl, int declarationIndex, Microsoft.CodeAnalysis.Diagnostics.SymbolDeclaredCompilationEvent symbolEvent, Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState analysisStateOpt, bool shouldExecuteSyntaxNodeActions, bool shouldExecuteOperationActions, bool shouldExecuteCodeBlockActions, bool shouldExecuteOperationBlockActions, bool isInGeneratedCode, System.Threading.CancellationToken cancellationToken) Line 1553	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver<Microsoft.CodeAnalysis.CSharp.SyntaxKind>.ExecuteDeclaringReferenceActions(Microsoft.CodeAnalysis.Diagnostics.SymbolDeclaredCompilationEvent symbolEvent, Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState analysisStateOpt, bool isGeneratedCodeSymbol, System.Threading.CancellationToken cancellationToken) Line 1401	C#

Repro steps:

1. Clean the RoslynDev hive on your machine
2. Get latest roslyn sources and build
3. Get latest roslyn-analyzer sources and build
4. devenv /rootsuffix RoslynDev
5. Open Roslyn.sln in the VS instance and leave it running for few minutes - you should hit the assert

**Comment by mavasani** [comment]
@genlu @JohnHamby FYI

**Comment by genlu** [comment]
@mavasani This should be fixed by #8612. Could please verify it using latest bits?

**Comment by mavasani** [comment]
Yes, you are correct - this no longer repros.
