### ISSUE TITLE
Implement compiler perf tests

### ISSUE THREAD

**Issue by KevinH-MS** [dotnet/roslyn#8752]
**March 1:**
- Hello World
- Build Microsoft.CodeAnalysisCSharp.dll (no msbuild)
```
csc /shared:blah
csc /shared-
```

*Note:* we probably also want tests with/without analyzers...
	
**April 2:**
- Roslyn Solution Build (also try to eliminate msbuild?)
- Pic*** / Aus*** Solution Build?

**Comment by TyOverby** [comment]
Over in #8642, we have Hello World and all of Csharp being tested

**Comment by AdamSpeight2008** [comment]
I think the perf test(s) should at least use all of the feature of the languages, not just a subset.

**Comment by KevinH-MS** [comment]
I believe we've written the tests we plan to for the time being.
