### ISSUE TITLE
RegisterSymbolAction should handle more SymbolKinds

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#8753]
@mavasani mentioned that there might already be an issue for this -- feel free to dupe and let me know to add my use case there.

I want to make a diagnostic that asserts that certain kinds of symbols have certain naming styles applied to them, and I want this to work for (nearly) every kind of symbol. Unfortunately, `RegisterSymbolAction` doesn't handle things like parameters and locals, so if I want to support them I need to listen to multiple kinds of actions or operations and cobble them all together. I'd rather `RegisterSymbolAction` just handle those cases for me. :smile:

**Comment by mavasani** [comment]
@JohnHamby @srivatsn

**Comment by mavasani** [comment]
@dpoeschl RegisterSymbolAction should work for properties - it won't work for parameters though.

**Comment by dpoeschl** [comment]
Oops, that's what I meant to say. Updating the description above to reflect that.

**Comment by dpoeschl** [comment]
@mavasani @JohnHamby @srivatsn - It looks like you guys aren't planning on changing anything here, but would you accept a PR that changes `RegisterSymbolAction`? Or is it by design? If you'd accept a contribution, can you point me to where the current list of acceptable SymbolKinds exists so I can start to understand the code around that? Thanks.

**Comment by mavasani** [comment]
Also tagging @gafter 
@dpoeschl This would need change across the C# and VB compiler layers. I presume we want to generate [SymbolDeclaredCompilationEvent](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Compilation/CSharpCompilation.cs,2895) for new symbol kinds, and then the analyzer driver should just pick up new symbol events and callback analyzers interested in them.

**Comment by JohnHamby** [comment]
I'm not sure that we would need more compilation events. Executing symbol actions for locals could be driven by the existing event that occurs for analyzing the containing method. When a method is declared, and if there are actions for locals available, get a bound tree for the method and traverse it looking for locals.

This could be layered on top of IOperation in a language-independent way.

However, because it is possible today to write an analyzer that enforces rules about local declarations using either syntax node actions for local declarations or operation actions for local declarations, enabling symbol actions for locals does not add capability (though it does add convenience).

**Comment by dpoeschl** [comment]
It adds convenience, and yes I could do the same (painfully) with syntax node actions (or whatever), but it also _completes_ RegisterSymbolAction and removes an undocumented gotcha. If we're gonna leave it this way, can we at least document the gotcha?

**Comment by JohnHamby** [comment]
I'm actually in favor of enabling symbol actions for locals and parameters, and think that we could do it without adding a lot of internal mechanism. Arguing both sides in hopes of provoking @srivatsn into taking a position...

**Comment by srivatsn** [comment]
:) You've provoked me now John. Sure, respecting all symbol kinds in RegisterSymbolAction would be great. @dpoeschl, I'd love to take a PR here. 

As to it being undocumented, aren't you seeing an analyzer warning when you try to RegisterSymbolAction some unsupported kind? [This analyzer](https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/RegisterActionAnalyzer.cs) should complain.

**Comment by gafter** [comment]
This is a very reasonable request, but please don't do it by having the compiler produce additional symbol-declared events. The bookkeeping required in the compiler would be quite high (the compiler does not require that a method body be bound precisely once), and the GC churn would be high for existing scenarios (which would not use those events).
