### ISSUE TITLE
IOperation: VB - BoundAssignmentOperator implements IAssignmentExpression and ICompoundAssignmentExpression at the same time.

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#8755]
This is very likely to lead to a confusion among consumers that rely on type checks (very common among some developers, look at the IDE code for example) because it is not appropriate for an ordinary assignment to implement ICompoundAssignmentExpression. Similar issue was brought up around field and property initializers during PR code review and was addressed by splitting the nodes. I am not sure if it is desirable to split the bound node in this case. Other options we could consider is to merge IAssignmentExpression and ICompoundAssignmentExpression interfaces, or create facades on top of the bound node for the purpose of implementing either IAssignmentExpression, or ICompoundAssignmentExpression depending on what it actually represents.

**Comment by AlekseyTs** [comment]
Also, see a note about MID assignment in #8759.

**Comment by jinujoseph** [comment]
@heejaechang , this is fixed already ?
