### ISSUE TITLE
IOperation: VB - BoundAssignmentOperator.ExpressionKind is likely to return incorrect result in some scenarios

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#8759]
It looks like a compound assignment, which utilizes a conversion either on top of the binary operator, or on top of the left operand, is going to be classified as OperationKind.AssignmentExpression instead of  OperationKind.CompoundAssignmentExpression.

```
        Protected Overrides Function ExpressionKind() As OperationKind
            Dim rightBinary As BoundBinaryOperator = TryCast(Me.Right, BoundBinaryOperator)
            If rightBinary IsNot Nothing Then
                If TypeOf rightBinary.Left Is BoundCompoundAssignmentTargetPlaceholder Then
                    Return OperationKind.CompoundAssignmentExpression
                End If
            End If

            Dim rightOperatorBinary As BoundUserDefinedBinaryOperator = TryCast(Me.Right, BoundUserDefinedBinaryOperator)
            If rightOperatorBinary IsNot Nothing Then
                If TypeOf rightOperatorBinary.Left Is BoundCompoundAssignmentTargetPlaceholder Then
                    Return OperationKind.CompoundAssignmentExpression
                End If
            End If

            Return OperationKind.AssignmentExpression
        End Function
```

In fact, the logic can be significantly simplified. BoundAssignmentOperator.LeftOnTheRightOpt is not Nothing if and only if the node represents a compound assignment.

**Comment by AlekseyTs** [comment]
Note, that BoundAssignmentOperator is also used to represent MID assignment:
```
Mid$(s1, 3, 3) = s2
```

See comments about BoundMidResult node. It is probably inappropriate for such a node to claim that it is an ordinary or a compound assignment and implement corresponding interfaces. We should probably have a special IOperation node for it.

**Comment by jinujoseph** [comment]
dupe https://github.com/dotnet/roslyn/issues/21738
