### ISSUE TITLE
Compiler doesn't optimize unnecessary field accesses

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#8762]
Source:

```C#
class C {
    static string x = null;
    bool M() {
        x = x;
        return x is bool;
    }
}
```

(the `x = x` is necessary to initialize the type)

This [compiles](http://tryroslyn.azurewebsites.net/#f:>ilr/MYGwhgzhAEDC0G8BQ1XQgFzBglsdGATjgHYDm0AHtALzQkCuIIA3CmgEYD2XI0AsgAoAlInZo01OpTYSJhAKYYGhElWg4Y3XrLQBfJHqAAA=) (in release mode) to 
```il
        IL_0000: ldsfld string C::x
        IL_0005: stsfld string C::x
        IL_000a: ldsfld string C::x
        IL_000f: pop
        IL_0010: ldc.i4.0
        IL_0011: ret
```

The second `ldsfield` and `pop` should be completely unnecessary.

**Comment by SLaks** [comment]
This also happens for instance fields, but not for local variables.

**Comment by jaredpar** [comment]
In this specific case the removal of the field load is unobservable but this is not true generally.  Consider the following modification on your sample:

``` 
class C
{
    static string X = GetValue();

    internal void M()
    {
        X = X;
        Console.WriteLine("after M");
    }

    internal static string GetValue()
    {
        Console.WriteLine("in GetValue");
        return null;
    }
}
```

In this case removing the assignment is potentially observable.  The field is tagged with `beforefieldinit` and hence the call to `GetValue` occurs on the first usage of `X`.  Even if that usage is a redundant assignment.  Removing this call potentially changes when `GetValue` executes.  

This is demonstrable with the following program (use a release build): 

``` csharp
class Program
{
    static void Main(string[] args)
    {
        new C().M();
    }
}
```

The output changes whether or not you comment away the assignment:

``` txt
// With the assignment
in GetValue
after M
// Without the assignment
after M
```

Hence this assignment is only redundant in the case where the field contains an initializer without side effects.  That's a pretty narrow case to optimize.

**Comment by jaredpar** [comment]
> This also happens for instance fields, but not for local variables.

Instance variables are another case where removing the self assign is observable.  Although a bit obscure it is possible for `this` to be `null`.  Hence removing a self assign instance variables is potentially removing a NRE from the code.
