### ISSUE TITLE
Remove the ubuntu-14.04-anycpu and osx.10.10-anycpu runtime entries from our project.json

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#8767]
This is currently dependent on us also upgrading the mono.linux and mono.mac toolsets to use the Update 1 nuget targets.

**Comment by davkean** [comment]
Help me understand the "why" behind this?

Also sounds like there's additional work here in updating the toolsets - do we have a doc documenting this? Do we have a bug on that?

**Comment by tannergooding** [comment]
These targets no longer exist in Update 1, and were replaced with the 'ubuntu-14.04' and 'osx.10.10' targets (and IIRC, there are were changes that couldn't happen because we are still referencing the legacy targets). The other work had already been done (remove 'win7-anycpu'), but it was reverted due to a series of other issues we were seeing.

I don't know if we have any documentation covering what needs to be done to update the Mono toolset, @agocke should have more info.

**Comment by agocke** [comment]
Don't bother trying to change the Mono toolset. Aside from being risky, I'm trying to get rid of it entirely, so it's not productive work.

**Comment by tannergooding** [comment]
@agocke, thanks for the update. @davkean, it sounds like this should wait for the removal of the mono toolset and then we can update the targets more easily (should just be removing the legacy runtime entries at that point).

**Comment by davkean** [comment]
@agocke Is there a bug tracking Mono removal?

**Comment by agocke** [comment]
@davkean https://github.com/dotnet/roslyn/issues/7139

**Comment by davkean** [comment]
This is blocked on #7139.

**Comment by jasonwilliams200OK** [comment]
FWIW, @mellinoe has done similar work in CoreFX repo: https://github.com/dotnet/corefx/pull/5905 (remove Mono dependency) and https://github.com/dotnet/corefx/pull/6077 (remove build dependency on PCL reference assemblies).

**Comment by agocke** [comment]
@jasonwilliams200OK I believe we need to target PCL profile7...

**Comment by jasonmalinowski** [comment]
@tannergooding @agocke is this still blocked on anything at this point?

**Comment by tannergooding** [comment]
@jasonmalinowski, not as far as I am aware.
