### ISSUE TITLE
IOperation: VB - BoundLiteral.ISpelling possibly has some implementation issues 

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#8769]
Binder often creates BoundLiteral nodes that do not correspond to a literal in syntax. For example, it creates BoundLiteral(Int32 1) to add to an upper bound of an array. The value returned by Syntax.ToString() is not likely to match the value of the literal. There are several more scenarios like that. What is the value of having ILiteralExpression.Text property?

```
        Private ReadOnly Property ISpelling As String Implements ILiteralExpression.Text
            Get
                Return Me.Syntax.ToString()
            End Get
        End Property
```

**Comment by jinujoseph** [comment]
we removed the API
