### ISSUE TITLE
Building roslyn.sln with /p:DeployExtension=true fails

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#8782]
```
(FindSourceVsixManifest target) ->
         C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\VSSDK\Microsoft.VsSDK.targets(59,5): error VSSDK10
       39: Source.extension.vsixmanifest file not found in project. If a file with this name is present in the project,
        make sure the build action is set to "None".
```

**Comment by amcasey** [comment]
I've had problems with both master and future.

**Comment by amcasey** [comment]
FYI @davkean @tannergooding

**Comment by amcasey** [comment]
The error is from src\VisualStudio\Core\Def\ServicesVisualStudio.csproj

**Comment by davkean** [comment]
By DeployExtension=false, do you actually mean "true"?

**Comment by davkean** [comment]
I agree with your assessment that deployment is broken, right now only the compiler gets deployed.

**Comment by davkean** [comment]
I don't know how this happened - it looks like all the extensions opt-out of deployment and have done so for a long time. Why hasn't this been a problem forever? @jasonmalinowski

**Comment by jasonmalinowski** [comment]
Where is the opt-out happening? I don't see the property being set strangely anywhere in my checkout.

**Comment by davkean** [comment]
```
> findstr /sip /c:"DeployExtension" *.csproj
src\VisualStudio\Core\Def\ServicesVisualStudio.csproj:    <DeployExtension>false</DeployExtension>
src\VisualStudio\CSharp\Impl\CSharpVisualStudio.csproj:    <DeployExtension>false</DeployExtension>
src\VisualStudio\CSharp\Repl\CSharpVisualStudioRepl.csproj:    <DeployExtension>false</DeployExtension>
```

**Comment by jasonmalinowski** [comment]
That's expected. We include the VSSDK targets in those packages so CreatePkgDef can be ran, but those don't produce .vsixes themselves. They just produce assets that get included in VisualStudioSetup, which will produce a VSIX which will get deployed.

**Comment by davkean** [comment]
Ok, so @amcasey's error is expected in that case (perhaps we should mark DeployExtension as a local property to avoid being overriden by `/p:DeployExtension=true`.

**Comment by davkean** [comment]
Now to figure out why we're not deploying.

**Comment by jasonmalinowski** [comment]
Yes, historically /p:DeployExtension=true hasn't worked well because it would force it to true and break things. We just never set LocalProperty I guess because we never cared (or thought to.)

**Comment by amcasey** [comment]
@davkean Updated title.

**Comment by davkean** [comment]
There's two issues here; the first is that explicitly passing in an DeployExtension=true results in a build failure. You shouldn't need to do that, MSBuild'ing the project via command-line should result in the extension being deployed, if it does not, please add a comment to #8847.

We'll use this bug to track that issue, the fix should be as simple as treating DeployExtension as a local property in the projects that opt-out of deployment. That will prevent the build error.

The second is that extensions aren't being deployed in some cases via F5. I've filed that here: https://github.com/dotnet/roslyn/issues/8847.
