### ISSUE TITLE
[nuget add using] would be nice to provide add ref fixer on unresolved using statement

### ISSUE THREAD

**Issue by michaelcfanning** [dotnet/roslyn#8788]
Repro: 
1) new project
2) type using CommandLine; at relevant location

Result: warning about unused namespace
Nice to have: fixer that provides ability to add package reference to 'Command Line Parser Library' package

The Elfie index provides for namespace searches, so we should be able to act on this without DB changes if we choose.

**Comment by DustinCampbell** [comment]
We'll keep this on the backlog for post-1.2

**Comment by kendrahavens** [comment]
[Duplicated in Developer Community](https://developercommunity.visualstudio.com/content/problem/858021/lightbulb-c-on-using-statements-does-not-contain-o.html)

> **Problem statement**:

> The lightbulb triggered on a `using` statement when the namespace referenced is not a part of currently added references provides options to **remove** the references, but does not contain an option to **add** that reference to the project.

> **Why?**

> While coding, lets say you use this construct:
```csharp
string s = JsonConvert.SerialzeObject(foo);
```
> You will get a squiggle under the `JsonConvert`, and the intelligent system will know that it comes from the `Newtonsoft.Json` NuGet package. Depending on your project setup, you will get one of two options:

> 1. If you already have the package installed and the DLL reference added to your project, you will be prompted to add the `using` statement for it on top of this file/namespace.

> 2. If you don't have the DLL reference added, it will prompt you to add the reference + the `using` statement, also installing the NuGet package for you.

> Now, apply the same thing to the `using` block of statements. When I have this:
```csharp
using Newtonsoft.Json;
```

> But I don't yet have the corresponding NuGet package installed [or the DLL reference added], why shouldn't the "intelligent system" prompt me for option #2 above [install package + add reference] ?

> That in essence is the point of this request. When the system detects a `using` statement whose namespace belongs in a NuGet package / assembly not yet added to the project, then there should be a lightbulb prompt in that dropdown to [install package + ] add reference to it. Currently the options only ask to remove that `using`, or suppress the error.

**Comment by sujayvsarma** [comment]
Thank you @kendrahavens for porting this over. Wondering about traction, because the original one is from **4 years** ago!

**Comment by CyrusNajmabadi** [comment]
> Thank you @kendrahavens for porting this over. Wondering about traction, because the original one is from 4 years ago!

It's not high priority.  You can just do something like type `JToken` and we'll offer to add both the reference and the `using`.  The use case of someone writing the `using` first is far less important.

**Comment by sujayvsarma** [comment]
@CyrusNajmabadi - you're wrong.

**Comment by CyrusNajmabadi** [comment]
@sujayvsarma About which part? Thanks!

**Comment by sujayvsarma** [comment]
That it's "not important".

You don't get to decide what's important for us.



- Sent from mobile. Pardon typos.

On Dec 18, 2019 23:13, CyrusNajmabadi <notifications@github.com> wrote:

@sujayvsarma<https://github.com/sujayvsarma> About which part? Thanks!

**Comment by michaelcfanning** [comment]
Cyrus is stating his own opinion here, of course, not trying to speak for you. It's true that his approach, adding a well known type and resolving it allows a fix up both for the namespace and assembly reference. Once you know this approach, it's definitely worth using. But it also requires that you can recall a relevant type like 'JToken'. For this assembly, I actually use JsonConvert as the relevant type, because I use that helper class constantly.

For some components, however, I tend to forget its constituent types and only remember the namespace. This is exactly what happened with the example in this issue. I only use this OSS component in short bursts (when I create a new console app and drop in the args construction), so I tend to forget individual type names. I recall the namespace between each event, though.

If you think about the activity of adding a namespace directive which is not strictly necessary or can't be resolved to a reference, it seems more likely that this is an indicator that a developer intends to move on to actually utilizing it rather than that they simply unnecessarily introduced the code edit. 

From this angle, I think the feature request is reasonable. I'm not sure statistically how likely the scenario is to occur. It'd be interesting to know whether VS telemetry could help quantify the pattern in some way.

**Comment by CyrusNajmabadi** [comment]
> That it's "not important".

You're putting in quotes.  But that's not anything that i said.  This is highly disingenuous.  

I said: "It's not high priority"

Which is true.  It's not a high priority to support this scenario.  It would likely be taken if someone wanted to contribute a PR.  But it's not super critical that it be done or that resources be allocated for it.

**Comment by CyrusNajmabadi** [comment]
> From this angle, I think the feature request is reasonable. 

So do I.  @sujayvsarma Would you be interested in contributing here?

**Comment by sujayvsarma** [comment]
@CyrusNajmabadi  Please see this line at the end of your comment up there (emphasis added):

> The use case of someone writing the `using` first is **far less important**.

That is what I was referring to. And we can agree to disagree on what is high priority (and I do not agree with your POV that it is not critical or important). 

Anyway... 

> Would you be interested in contributing here?

What are you thinking? How do you want me to contribute here?

**Comment by CyrusNajmabadi** [comment]
> What are you thinking? How do you want me to contribute here?

You could add support to the 'add reference' feature to support it working on `using` directives.

**Comment by CyrusNajmabadi** [comment]
> And we can agree to disagree on what is high priority

Not really :)   it's fairly evident by virtue of it never being done and having no milestone or assigned person.

I wrote 'add using', 'add ref' and 'add nuget package', so i'm pretty familiar with this area.  This area is *literally* far lower in priority.  We judged that based explicitly on the types of errors that we could actually see people were running into.  i.e. we actually measured this.  

The need to add usings/references/etc. from the reference point *far* dominates the need to add it at the `using` decl point.  

> and I do not agree with your POV that it is not critical or important

I'm not sure what to tell you.  We shipped some of these things more than a decade ago.  Since then, we now have had this bug filed once, and it has zero votes on it.  It really doesn't seem critical/important.  It would certainly be 'nice to have' and i would be willing to help you out wrt to creating such a feature if you want! :)

**Comment by sujayvsarma** [comment]
Probably, with the amount of time & effort you would spend 'helping me out' get started and doing this... you could probably just implement it at your end? Unless you're talking about other process challenges that would affect the way you would do it versus if someone from the 'wild' were to submit a PR. 

PS: I am not going to continue the other (disagreements thread) because doing so would detract from the purpose of the 'issue' and would unnecessarily sully more than just screen-text.

**Comment by CyrusNajmabadi** [comment]
> Probably, with the amount of time & effort you would spend 'helping me out' get started and doing this... you could probably just implement it at your end?

It's not a priority for me ;-)   I have lots of other things i submit to Roslyn.

>  versus if someone from the 'wild' were to submit a PR.

Roslyn takes community PRs all the time.  I've submitted around 5 just this week :)

**Comment by sujayvsarma** [comment]
Aha! @CyrusNajmabadi Now I have some context around _you_. So I'll take this forward with you. Let's talk. Do you want to do that over email or here? My email ID is [firstname]@[lastname].in

**Comment by CyrusNajmabadi** [comment]
Here works, or we can do gitter.im/dotnet/Roslyn or discord.gg/csharp in the #roslyn channel. 

Note that it's Xmas in 3 days. I will likely not be available much until the 6th

**Comment by sujayvsarma** [comment]
Looked into both gitter seems better. Also, before you go away for Xmas++, I'd like a dump of the following from you:

NB: I haven't done _any_ Roslyn related work before [other than filing bugs ;-)].

1. What code repos do I need to have local? 
2. Build dependencies? Other tools I need to install?
3. Give me a suitable BVT to check that I have stuff set up to go forward correctly.

If there's a detailed-enough doc to get me started off, 👍

I am running off of VS 2019 Community (RP 16.5 P1 at the moment). And the workloads are set up primarily for Azure-related dev work, pretty much nothing else is installed.

**Comment by CyrusNajmabadi** [comment]
Is a good place to start: https://github.com/dotnet/roslyn/wiki/Contributing-Code
