### ISSUE TITLE
In rule set editor, rename Microsoft.Analyzers.ManagedCodeAnalysis and Microsoft.Analyzers.NativeCodeAnalysis to something else

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn#88]
These are the analyzer IDs for the old-style code analysis rules (i.e., FxCop). For the sake of clarity, we should rename them to something like "FxCop (Managed Code)" and "FxCop (Native Code)".

**Comment by tmeschter** [comment]
Microsoft.Analyzers.ManagedCodeAnalysis will now be referred to as "Managed Binary Analysis".

Microsoft.Analyzers.NativeCodeAnalysis is sticking with the name it has. With the fix for issue #89, C# and VB users generally won't see this analyzer anyway.

**Comment by tmeschter** [comment]
Sending to @mavasani for verification.

**Comment by mavasani** [comment]
@tmeschter I still see Microsoft.Analyzers.ManagedCodeAnalysis as the analyzer ID for FXCop analyzers for a managed project's default ruleset. This is yesterday's VSPro_1 drop.

**Comment by mavasani** [comment]
Re-activating as I still see Microsoft.Analyzers.ManagedCodeAnalysis as the analyzer ID for FXCop analyzers:

![analyzerid_repro](https://cloud.githubusercontent.com/assets/10605811/6811220/9815b8cc-d223-11e4-9e09-27e664197f92.png)

**Comment by tmeschter** [comment]
OK, fixed for real this time. Re-assigning to @mavasani for verification.

**Comment by mavasani** [comment]
Verified fixed.
