### ISSUE TITLE
Compat issue: lambda values passed as parameters to methods are different in Roslyn

### ISSUE THREAD

**Issue by rockfordlhotka** [dotnet/roslyn#8804]
Looks like there’s a bug with Roslyn and the way lambda values are passed as parameters to methods.

Copied from [this issue](https://github.com/MarimerLLC/csla/issues/536#issuecomment-184906441):

The following code, when compiled in VS 2015:

```
    Private Shared ProcessMethod As MethodInfo = RegisterMethod(Function(c) c.Process)
    Public Function Process() As Boolean
```

produces a runtime error because the Lambda method is passed into the `GetMethod` function as:

```
{a0 => Invoke(c => c.Process(), a0)}
```

This results in the statement:  `if (lambda.Body.NodeType != ExpressionType.Call)`  to return `true` causing the method to throw an `ArgumentException Not a method Call`

`lambda.Body.NodeType` in this case is `ExpressionType.Invoke`, not `ExpressionType.Call`.

The following, however, does still work in VS 2015:
```
    Private Shared UnapproveMethod As MethodInfo = RegisterMethod(Sub(c) c.Unapprove())
    Public Sub Unapprove()
```

---

**Vladimir**: At first look it seems like old compiler did some premature optimization here. Perhaps it should not be doing that, but that is mostly irrelevant now. 
 
We are trying to keep expression tree shapes compatible (including various quirks coming from old implementations) precisely because of issues like this. 
So far this should be considered as a compat bug in Roslyn.

**Comment by VSadov** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/11629
