### ISSUE TITLE
IOperation: Contract of IHasArgumentsExpression.GetArgumentMatchingParameter needs clarification.

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#8805]
```
        /// <summary>
        /// Find the argument supplied for a given parameter of the target method.
        /// </summary>
        /// <param name="parameter">Parameter of the target method.</param>
        /// <returns>Argument corresponding to the parameter.</returns>
        IArgument GetArgumentMatchingParameter(IParameterSymbol parameter);
```

It is my understanding that elements of param array are supposed to be exposed as individual IArguments of kind ParamArray corresponding to param array parameter. Given that, there could be multiple IArgument instances corresponding to that parameter. What should be returned from GetArgumentMatchingParameter method for the parameter?

Also, I am not sure it makes sense to have this method as a member of IHasArgumentsExpression interface and force everyone to provide implementation for it. If we think this is a useful helper, we could implement it as an extension method, it looks like all necessary information to do that is available from IArgument.

**Comment by genlu** [comment]
1. We are now returning a single `IArgument` for entire ParamArray (for both normal and expanded form).
2. Per discussion, this is already downgraded to extension method #18658
