### ISSUE TITLE
Add a issue_template.md and pull_request_template.md

### ISSUE THREAD

**Issue by GerjanOnline** [dotnet/roslyn#8806]
Please see

https://github.com/dear-github/dear-github/issues/125
and
https://news.ycombinator.com/item?id=11119411

Maybe an idea for this repo?

**Comment by davkean** [comment]
See: https://github.com/dotnet/roslyn/pull/8842

**Comment by jmarolf** [comment]
We've added the templates that we wanted.  If someone has any other templates they want, feel free to submit a PR.
