### ISSUE TITLE
IOperation: A proposal to change design around IHasArgumentsExpression, IInvocationExpression and IArgument interfaces.

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#8813]
**Exposing the set of arguments**

Currently we have two APIs that are supposed to expose arguments and every implementer has to implement both.
In IHasArgumentsExpression, which is IInvocationExpression inherits from:

```
        /// <summary>
        /// Arguments of the invocation, excluding the instance argument. Arguments are in parameter order,
        /// and params/ParamArray arguments have been collected into arrays. Default values are supplied for
        /// optional arguments missing in source.
        /// </summary>
        ImmutableArray<IArgument> ArgumentsInParameterOrder { get; }
```

In IInvocationExpression 

```
        /// <summary>
        /// Arguments of the invocation, excluding the instance argument. Arguments are in the order specified in source,
        /// and params/ParamArray arguments have been collected into arrays. Arguments are not present
        /// unless supplied in source.
        /// </summary>
        ImmutableArray<IArgument> ArgumentsInSourceOrder { get; }
```

I am not sure if having two these APIs provides much value. I believe that it would be much more useful to have a single API in IHasArgumentsExpression:

```
        /// <summary>
        /// Arguments of the invocation, excluding the instance argument. Arguments are in evaluation order,
        /// and params/ParamArray arguments have been collected into arrays. Default values are supplied for
        /// optional arguments missing in source.
        /// </summary>
        ImmutableArray<IArgument> ArgumentsInEvaluationOrder { get; }
```

If we feel that sometimes consumers would want to traverse arguments in source or parameter order, we can provide helpers like this as extension methods for IHasArgumentsExpression interface because all the relevant information should be available from IArguments.

**IArgument, ArgumentKinds and param arrays**

It is not obvious what value do we get from distinguishing between Positional and Named arguments. I believe Analyzers will be more interested in the order, in which arguments are evaluated (ArgumentsInEvaluationOrder solves that). Knowing whether the argument was named doesn't look that important and can always be discovered from syntax. 

The requirement to create a separate IArgument of ParamArray kind for each element of param array

```
        /// <summary>
        /// Argument becomes an element of an array that matches a trailing C# params or VB ParamArray parameter.
        /// </summary>
        ParamArray = 0x3,
```

means that we will create trees of different shape for situations when param array was created by the compilers and when the array was passed explicitly. Do Analyzers really care that much about param array that they will be willing to be prepared to deal with two different tree shapes for semantically equivalent code?

Another issue with the current design is that it looks like an empty param array created by compilers won't have any representation in the tree at all, because there is no ArgumentKind that could be used for such an argument.

To address all these issues, I propose to change the current set of ArgumentKinds as follows (note, the meaning of ParamArray kind is changed):

```
    /// <summary>
    /// Kinds of arguments.
    /// </summary>
    public enum ArgumentKind
    {
        None = 0x0,

        /// <summary>
        /// Argument value is explicitly supplied.
        /// </summary>
        Explicit = 0x1,

        /// <summary>
        /// Argument is a param array created by compilers for the matching C# params or VB ParamArray parameter. Note, the value is a an array creation expression that encapsulates all the elements, if any.
        /// </summary>
        ParamArray = 0x2,

        /// <summary>
        /// Argument is a default value supplied automatically by the compilers.
        /// </summary>
        DefaultValue = 0x3
    }
```

See related issues: #8805, #8786, #8781, #8773.

**Comment by mavasani** [comment]
I agree these interfaces are very confusing. For example, ArgumentsInParamOrder is available on IHasArgumentsExpression, but is ArgumentsInSourceOrder only available on IInvocationExpression, but not IHasArgumentsExpression?

Something like an OperationWalker/Visitor always needs to visit arguments in source order, but this is not available on all subtypes of IHasArgumentsExpression.

**Comment by mavasani** [comment]
Tagging @CyrusNajmabadi @jinujoseph - we need to iron out the APIs for arguments/invocations asap. These are core APIs and would need lot of bake time and testing.

**Comment by mavasani** [comment]
One other weird behavior that I am seeing is that for overload resolution failures `ArgumentsInSourceOrder != ArgumentsInParamOrder`, because the [DeriveArguments](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/BoundTree/Expression.cs,d9a2381671a53797,references) method doesn't add arguments that do not match a parameter. For example, if you are invoking a method with 0 parameters, but the invocation providers 2 arguments, then ArgumentsInParamOrder is empty, which seems incorrect. Anyone looking at IHasArgumentsExpression will assume the code has no arguments.

If we are exposing both ArgumentsInSourceOrder and ArgumentsInParamOrder, we need to ensure they have the same count.

**Comment by mavasani** [comment]
I completely agree with @AlekseyTs here - we should probably just expose `Arguments` on the IHasArgumentsExpression, which just returns the set of BoundExpression (arguments) that the compiler puts in the BoundCall in evaluation order and then add helper/extension methods to get other custom functionality.

**Comment by jinujoseph** [comment]
**Design Meeting Notes**

Design team agrees with this proposal.
