### ISSUE TITLE
Scope of a pattern variable in an expression-bodied property or method or field initializer

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#8816]
The scope of a pattern variable declared in an expression-bodied property or method should include the whole body. This should be (implemented if necessary and) tested. For example:

```cs
bool M(object o) => o is int i && i == 3;
bool P => SomeObject is int i && i == 3;
bool F = SomeObject is int i && i == 3;
```

In the case of multiple field declarators, pattern variables should encompass the whole field declaration, but we need to ensure that definite assignment prevents using a pattern variable that is not definitely assigned.

**Comment by AlekseyTs** [comment]
@gafter Could you clarify the following statement please:
> In the case of multiple field declarators, pattern variables should encompass the whole field declaration

Are you saying that, given the code below, variables declared in pattern1 are in scope in pattern3, and variables declared in pattern3 are in scope in pattern1?
```
int X = <pattern1>, Y, Z = <pattern3>;
```  

Wouldn't that contradict the following statement from the language spec?
```
A field declaration that declares multiple fields is equivalent to multiple declarations of single fields with the same attributes, modifiers, and type. 
```

**Comment by gafter** [comment]
@AlekseyTs Yes, for example you could write

```cs
bool bx = tuple is (int x, int y, int z) && x==3, by = y==3, bz = z==3;
```

Agreed, it will require some slight rewording in places that assume there is no scope encompassing a field declaration.

Do you think the scopes for each field's initializer should be independent?

**Comment by AlekseyTs** [comment]
I think we should start with independent scopes. Merging scopes for field initializers makes things tricky, especially in SemanticModel. I am not sure it is worth the trouble doing this just for initializers in the same declaration statement vs. all initializers in the given partial type declaration.

**Comment by gafter** [comment]
@AlekseyTs OK, sounds good to me.

**Comment by AlekseyTs** [comment]
All relevant scenarios should be covered now.
