### ISSUE TITLE
Scope of pattern variables declared in statements

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#8817]
We should have tests to ensure correct scoping of pattern variables appearing in statements.

For a `let` statement, variables appearing in the statement's *pattern* are scoped to the enclosing block.

For an `if` statement, variables appearing in the statement's condition are scoped to the condition and the then clause, but not the else clause.

For all other statements, variables appearing in the statement's expression are scoped to just that statement.

Pattern variables may not "conflict" with a local or pattern variable or constant declared in an enclosing scope.

**Comment by AlekseyTs** [comment]
@gafter Please verify.
