### ISSUE TITLE
Subsumption checking for pattern-matching

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#8823]
We should implement subsumption checking for pattern matching, to ensure that any case is not subsumed by previous cases. The trivial cases are `case 3:` followed by `case 3:`, but we also want to include anything following `case var o:`, or anything following the pair of `case null:` and `case object o:`. Similarly, we want to handle the recursive cases.

**Comment by bondsbw** [comment]
What happens when I do `case FirstObject fo:` and `case SecondObject so:` and pass in `null` to be matched?

**Comment by gafter** [comment]
@bondsbw Since `null is FirstObject` is `false` and `null is SecondObject` is also `false`, neither of those cases would match.

**Comment by bondsbw** [comment]
:thumbsup:

**Comment by alrz** [comment]
Why `str is var s` succeeds even if `str` is `null`? shouldn't it be equivalent to `str is string s`? I expect `var` to succeed only when the value is *not* null,

**Comment by gafter** [comment]
The specification defines the `var` case as catching all input values. It is like a wildcard with a name. It is not equivalent to specifying a type.

**Comment by alrz** [comment]
>The specification defines the var case as catching all input values. It is like a wildcard with a name. It is not equivalent to specifying a type.

@gafter Wouldn't it make more sense to use `let` in this context? Because right now `var` is just a *placeholder* for a type and it is semantically the same if you actually specify it.
