### ISSUE TITLE
IOperation: UnaryOperationKind feels unnecessary complicated

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#8834]
Why are we going through the trouble of combining operator kind with type of arguments? Does this really make things easier for consumers? It feels that operator kind is sufficient enough and the type of the operand can be accessed from the Operand.

**Comment by JohnHamby** [comment]
Parallel discussion is in #8835

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/21407
