### ISSUE TITLE
IOperation: BinaryOperationKind feels unnecessary complicated

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#8835]
The enum has more than a hundred members!
Why are we going through the trouble of combining operator kind with type of arguments? Does this really make things easier for consumers? It feels that operator kind is sufficient enough and the type of the operand can be accessed from the Operand.

**Comment by JohnHamby** [comment]
I find it useful to be able to get at the precise operation in one step. When only the untyped kind of operation (e.g. Add or Subtract) is desired, the GetSimpleBinaryOperationKind extension method provides it.

**Comment by AlekseyTs** [comment]
It unnecessary complicates implementation, essentially it mimics what C# compiler has internally. If VB compiler was used as a prototype for IOperation tree, I believe we wouldn't end up with an enum like that. I'd say let's start simple and wait for the feedback. Another option is to add an extension method instead that would glue the values from different enums together, but implementers wouldn't have to do this.

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/21407
