### ISSUE TITLE
Build of ProjectSystem vsix is disabled 

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#8838]
The vsix project for ProjectSystem (in future branch) is removed from the solution, since the content of the vsix is not getting signed and causes build failure as a result. We need to figure out how to sign the binaries in it and enable the build.

Here's the PR that disabled it:
https://github.com/dotnet/roslyn-internal/pull/585

**Comment by davkean** [comment]
This issue was moved to dotnet/roslyn-project-system#93
