### ISSUE TITLE
IOperation: VB - BoundBinaryOperator it looks like implementation of IBinaryOperatorExpression.BinaryOperationKind is not handling all possible scenarios

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#8843]
```
        Private ReadOnly Property IBinaryKind As BinaryOperationKind Implements IBinaryOperatorExpression.BinaryOperationKind
            Get
                Return DeriveBinaryOperationKind(Me.OperatorKind, Me.Left)
            End Get
        End Property
```

Glancing over code in DeriveBinaryOperationKind (the list might be incomplete):
- It looks like operands of Nullable type are not handled;
- It looks like LessThanOrEqual, GreaterThanOrEqual, LessThan, GreaterThan operators for strings aren't handled.

**Comment by AlekseyTs** [comment]
Note that DeriveBinaryOperationKind  is used in several places throughout IOperation implementation, so implementation of other interfaces is likely to be affected as well.

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/21407
