### ISSUE TITLE
IOperation: It looks like some binary operator semantics cannot be represented via IBinaryOperatorExpression

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#8846]
It looks like Nullable lifting isn't explicitly repretesented.
It looks like checked/unchecked semantics cannot be represented.
It looks like Option Compare Text for String or Object comparison cannot be represented.

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/21407
