### ISSUE TITLE
IOperation: VB - BoundUserDefinedBinaryOperator implementation of IBinaryOperatorExpression.BinaryOperationKind doesn't handle some operators

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#8848]
It looks like BinaryOperatorKind.Power is not handled and will cause UnexpectedValue exception.
I didn't confirm that all other operators are handled properly.

**Comment by JohnHamby** [comment]
Power is now handled. Any remaining unhandled operators will not cause crashes. We still need an audit to ensure that all operators are handled.

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/21407
