### ISSUE TITLE
IOperation: VB - BoundUserDefinedBinaryOperator possibly has issues in implementation of IBinaryOperatorExpression for error scenarios

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#8849]
```
        Private ReadOnly Property ILeft As IOperation Implements IBinaryOperatorExpression.Left
            Get
                Return Me.Left
            End Get
        End Property

        Private ReadOnly Property IRight As IOperation Implements IBinaryOperatorExpression.Right
            Get
                Return Me.Right
            End Get
        End Property

        Private ReadOnly Property IOperator As IMethodSymbol Implements IHasOperatorMethodExpression.OperatorMethod
            Get
                Return Me.Call.Method
            End Get
        End Property

        Private ReadOnly Property IUsesOperatorMethod As Boolean Implements IHasOperatorMethodExpression.UsesOperatorMethod
            Get
                Return True
            End Get
        End Property
```

In error scenarios the Call, Left and Right properties are going to throw an InvalidCastException because UnderlyingExpression is not going to be a BoundCall node.

Probably IUsesOperatorMethod should return False and IOperator should return Nothing in this case. ILeft and IRight, however, should still be able to get the operands, which will be children of the node stored in UnderlyingExpression property.

```
        Protected Overrides Function ExpressionKind() As OperationKind
            Select Case Me.OperatorKind And BinaryOperatorKind.OpMask
                Case BinaryOperatorKind.Add, BinaryOperatorKind.Concatenate, BinaryOperatorKind.Subtract, BinaryOperatorKind.Multiply, BinaryOperatorKind.Divide,
                    BinaryOperatorKind.IntegerDivide, BinaryOperatorKind.Modulo, BinaryOperatorKind.Power, BinaryOperatorKind.LeftShift, BinaryOperatorKind.RightShift,
                    BinaryOperatorKind.And, BinaryOperatorKind.Or, BinaryOperatorKind.Xor, BinaryOperatorKind.AndAlso, BinaryOperatorKind.OrElse,
                    BinaryOperatorKind.LessThan, BinaryOperatorKind.LessThanOrEqual, BinaryOperatorKind.Equals, BinaryOperatorKind.NotEquals,
                    BinaryOperatorKind.Is, BinaryOperatorKind.IsNot, BinaryOperatorKind.Like, BinaryOperatorKind.GreaterThanOrEqual, BinaryOperatorKind.GreaterThan

                    Return OperationKind.BinaryOperatorExpression
            End Select

            Throw ExceptionUtilities.UnexpectedValue(Me.OperatorKind And BinaryOperatorKind.OpMask)
        End Function
```

I think ExpressionKind should never throw and should always return OperationKind.BinaryOperatorExpression. Especially that Accept methods always visit node as BinaryOperatorExpression.

**Comment by JohnHamby** [comment]
@AlekseyTs is correct. We need to make IOperation implementations both:
  a) Never throw exceptions due to missing information in the bound trees.
  b) Always return well-formed results, filling in Invalid nodes when necessary.

If we don't do the second step we will just be moving the crashes from the IOperation implementations to analyzers.

**Comment by JohnHamby** [comment]
One might argue that the Left, Right, and Call properties of BoundUserDefinedBinaryOperator should also be made not to throw, but I'll cover this in the IOperation implementation.

**Comment by AlekseyTs** [comment]
@JohnHamby If you feel that it is appropriate to adjust implementation of Left, Right and Call, go for it. IOperation implementation introduced the usage of these API in error scenarios, before that there was no requirement for these API to be resilient to erroneous trees. It is fine to change requirements for the APIs and adjust their implementation accordingly, but it is unreasonable to expect that existing APIs on bound trees magically satisfy IOperation requirements. All assumptions should be verified and tested.
