### ISSUE TITLE
Provide a way to recalculate Roslyn's lightbulb state/contents without solution change

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#885]
Related to bug #540 (with PR #770 & #983)

For RenameTracking, we will clear the rename tracking diagnostic on Escape and trigger DiagnosticsUpdated, which will trigger SuggestedActionsSourceProvider.OnDiagnosticsUpdated. We need some way to trigger OnDiagnosticsUpdated to refresh its lightbulb state/contents without versioning the solution. One suggestion is to use a null value for DiagnosticsUpdatedArgs.Solution to indicate reanalysis, but we could certain add another flag to DiagnosticsUpdatedArgs or find some other approach.

**Comment by CyrusNajmabadi** [comment]
This is no longer necessary with https://github.com/dotnet/roslyn/pull/42246.  We requery for refactorings when the lightbulb is triggered (or the user moves) and we will see hte rename refactoring.
