### ISSUE TITLE
Visual Studio switches over to intellisense window during rebuild 

### ISSUE THREAD

**Issue by paulvanbrenk** [dotnet/roslyn#8850]
Copied from TypeScript issue [7110](https://github.com/Microsoft/TypeScript/issues/7110)

Hi,

**Version**: VS 2015/TS 1.8

We have a project system in a VS solution whereby the projects reference the output of other projects via `<reference>` tags.

In the VS settings I have the option `Show Output window when build starts` checked and I have the option `Always show Error List if build finishes with errors` unchecked.

As of 1.8 when I carry out a rebuild of the solution, VS switches to the output window as expected, but halfway through it switches over to the `IntelliSense` window and prints a bunch of lines similar to the following:

```
[Failure] Could not find file 'C:\foo\bar\abc.d.ts'.
[Failure] Could not find file 'C:\foo\bar\abc.d.ts'.
[Failure] Could not find a part of the path 'C:\foo\baz\xyz.d.ts'.
[Failure] Could not find file 'C:\foo\bazz\aaaaa.d.ts'.
[Failure] Could not find a part of the path 'C:\foo\baz\capture\bbbbbbbbbb.d.ts'.
[Failure] Could not find a part of the path 'C:\foo\bz\ccccccccc.d.ts'.
```

I'm assuming these errors are occurring because as the full solution rebuild progresses, certain directories are cleaned out, causing the projects that reference files in those directories to print these errors.

There is no problem with the temporary errors, but prior to 1.8 there was no switching over to the intellisense window. I am not really interested in the intellisense errors: I want to observe the build output window.

Thanks.

**Edit**: I should say 'IntelliSense' view on the Output tab: there is no separate tab as such.

**Comment by Pilchie** [comment]
@paulvanbrenk not sure what changed on the typescript side, but Roslyn's logic for this hasn't changed since before 1.0 IIRC.

**Comment by paulvanbrenk** [comment]
@vladima could it be that we started reporting these errors, which causes the window to show.. or that we're more aggressive in computing something, causing the same?

**Comment by DustinCampbell** [comment]
@paulvanbrenk, @vladima -- I'm going to resolve this as "external" for now. If you find that this is a Roslyn issue, let us know and we'll re-open. Cool?

**Comment by paulvanbrenk** [comment]
SOunds good

**Comment by NoelAbrahams** [comment]
@paulvanbrenk, has this been fixed? I don't see an open ticket for this.

**Comment by paulvanbrenk** [comment]
@NoelAbrahams this is not a TypeScript issue either, we're working with the shell team however it's not a high priority for them

**Comment by davidsb** [comment]
Why is this issue closed?  The behavior is really quite annoying.  For me it happens EVERY TIME I do "Build -> Clean Solution".  Can IntelliSense "disengage" somehow during a build?
