### ISSUE TITLE
RenameTracking should be a DocumentDiagnosticAnalyzer

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#886]
The RenameTrackingDiagnosticAnalyzer should really be a DocumentDiagnosticAnalyzer instead of a DiagnosticAnalyzer because of the way it breaks out of the expected scope of regular DiagnosticAnalyzers by statically accessing the workspace. Instead of accessing the workspace statically from a regular DiagnosticAnalyzer, we can switch to being a DocumentDiagnosticAnalyzer, and get the workspace from the document.

**Comment by dpoeschl** [comment]
Tagging @heejaechang in case I've omitted any details.

**Comment by Pilchie** [comment]
@heejaechang What are the consequences of not doing this?

**Comment by heejaechang** [comment]
you can't access MEF in normal way (basically you need to create some static thing that hold services you need and access from it). if one's diagnostic analyzer require MEF (something that can't run from command line), then it should use DocumentDiagnosticAnalyzer.

**Comment by mavasani** [comment]
If the intent is just getting to the workspace, you can also do so by casting AnalyzerOptions param to WorkspaceAnalyzerOptions and fetching workspace from it. This will work only for analyzers running in IDE. DocumentDiagnosticAnalyzer might be a better option.

**Comment by heejaechang** [comment]
@mavasani I think casting AnalyzerOptions to WorkspaceAnalyzerOptions is basically conceptually same thing as having static thing.

DocumentDiagnosticAnalyzer is there for this kind of case where one wants to use VS services and tie itself to host.

**Comment by mavasani** [comment]
Yes, that is correct. If the analyzer only ever runs in IDE, document analyzer is correct approach. However, if analyzer wants to be capable of being run on command line builds also, it cannot be a document analyzer, as compiler driver won't execute it.

**Comment by dpoeschl** [comment]
@heejaechang @mavasani Right, we definitely *should* switch to a DocumentDiagnosticAnalyzer because it's the right thing to do, but what are the consequences if we choose not to for the 1.0 Stable milestone? This analyzer will only ever run in VS, so there should be no user-visible consequence, right?

**Comment by dpoeschl** [comment]
I understand that the continued open source existence of this analyzer's code may set a bad example and we wouldn't want this pattern replicated elsewhere. For this milestone, maybe we could add a couple comments instead.

**Comment by mavasani** [comment]
Yes, I agree that is not important for 1.0.

**Comment by CyrusNajmabadi** [comment]
Closing out with https://github.com/dotnet/roslyn/pull/42246

Rename is now just a refactoring, not an analyzer.
