### ISSUE TITLE
IOperation: It looks like there is no way to get conditional access receiver for IConditionalAccessExpression

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#8861]

**Comment by jinujoseph** [comment]
@AlekseyTs (from cyrus) Is that not just "IConditionalAccessExpression.ConditionalInstance"?  http://index/?leftProject=Microsoft.CodeAnalysis&leftSymbol=bkhfeezyxx10&file=Operations%5CIConditionalAccessExpression.cs&line=23

**Comment by AlekseyTs** [comment]
I cannot tell. The comment says "Expresson that is conditionally accessed", but the receiver is accessed unconditionally.

```
    /// <summary>
    /// Represents an expression that includes a ? or ?. conditional access instance expression.
    /// </summary>
    /// <remarks>
    /// This interface is reserved for implementation by its associated APIs. We reserve the right to
    /// change it in the future.
    /// </remarks>
    public interface IConditionalAccessExpression : IOperation
    {
        /// <summary>
        /// Expression to be evaluated if the conditional instance is non null.
        /// </summary>
        IOperation ConditionalValue { get; }
        /// <summary>
        /// Expresson that is conditionally accessed.
        /// </summary>
        IOperation ConditionalInstance { get; }
    }
```

Also it is not quite cleat what is the relationship between ConditionalValue and the receiver. It feels like ConditionalValue should refer to the receiver or have its place marked in some way.

**Comment by 333fred** [comment]
@AlekseyTs is this addressed by https://github.com/dotnet/roslyn/pull/21572, or do you want more doc updates?

**Comment by AlekseyTs** [comment]
@333fred  It looks like #21572 is about Conditional Choice Expression this issue is about Conditional Access Expression. Did you mean to reference a different PR?

**Comment by 333fred** [comment]
@AlekseyTs yes, I meant https://github.com/dotnet/roslyn/pull/21624.

**Comment by AlekseyTs** [comment]
It looks like the #21624 still says:
```
        /// <summary>
        /// Expression that is conditionally accessed.
        /// </summary>
        IOperation Expression { get; }
```

If expression represents the receiver, it is evaluated **unconditionally**. So, perhaps the doc comment should be adjusted.
