### ISSUE TITLE
Should VB character literals stop at linebreaks?

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#8880]
```
Dim str1= "
Dim str2 = "c"
```

As far as I can tell, the incomplete fragment above (I was in the process of typing a string literal on the first line) is parsed as though the value of `str1` is a character literal `\r\nDim str2 = `.  Also, it appears to end up as `SkippedTokensTrivia` rather than an invalid character literal, though that is probably by design.

**Comment by amcasey** [comment]
FYI @AlekseyTs @jaredpar

**Comment by gafter** [comment]
VB string literals can be multi-line, and we cannt tell until the end whether it is a string or character literal. So the answer is "no".
