### ISSUE TITLE
IOperation: VB - It looks like there is no way to represent [TypeOf ... IsNot ...] via IIsExpression

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#8882]
It looks like, given the current implementation, [TypeOf ... **IsNot** ...] and [TypeOf ... **Is** ...] are represented the same way and the consumer is unable to distinguish them.

**Comment by AnthonyDGreen** [comment]
I suggest changing IOperation to represent the union of what VB and C# can do and just having the negative case never appear in C#. The only other possibility is some kind of synthesized negation operation of the current IIsExpression.

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/21794
