### ISSUE TITLE
[Test Failure] Individual TAO Test Failure in prtest/win/vsi/p0 on PR #8864

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#8893]
PR: [#8864](https://github.com/dotnet/roslyn/pull/8864) *Update roslyn semantic version from 1.2 to 1.3* by @jmarolf
Failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p0/282/

**1 Test Failures:**
BasicExpressionEvaluator.Validate Locals Window

**Issue 1: Individual TAO Test Failure**
Failing integration tests: 

BasicExpressionEvaluator.xml

**Comment by davkean** [comment]
@amcasey You fixed this, no?

**Comment by davkean** [comment]
Dupe of: https://github.com/dotnet/roslyn/issues/8725

**Comment by amcasey** [comment]
@davkean No, the fix turned out not to work.  I'm still investigating.
