### ISSUE TITLE
IOperation: VB - It doesn't feel appropriate for BoundDelegateCreationExpression to implement IMethodBindingExpression

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#8897]
```
    /// <summary>
    /// Represents a reference to a method other than as the target of an invocation.
    /// </summary>
    public interface IMethodBindingExpression : IMemberReferenceExpression
    {
        /// <summary>
        /// Referenced method.
        /// </summary>
        IMethodSymbol Method { get; }

        /// <summary>
        /// Indicates whether the reference uses virtual semantics.
        /// </summary>
        bool IsVirtual { get; }
    }
```

BoundDelegateCreationExpression represents a delegate creation and its type is the target delegate,  "a reference to a method other than as the target of an invocation" isn't a value, it doesn't imply a delegate involvement and is not supposed to have a type. If IMethodBindingExpression is supposed to represent a delegate creation, let's rename it and adjust its description. Otherwise, we probably should add a special node to represent a delegate creation, which will have IMethodBindingExpression as its operand.

**Comment by jinujoseph** [comment]
dupe of existing bug?

**Comment by 333fred** [comment]
Dupe of https://github.com/dotnet/roslyn/issues/20095, this issue is being addressed by creating a new node `IDelegateCreationExpression`
