### ISSUE TITLE
Intelligently hide the *.ManagedCodeAnalysis and *.NativeCodeAnalysis analyzers in the rule set editor

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn#89]
The rules in the Microsoft.Analyzers.ManagedCodeAnalysis analyzer only apply to managed code, and the rules in Microsoft.Analyzers.NativeCodeAnalysis only apply to native code. If your solution only contains managed code then we shouldn't show the native rules, and vice-versa.

Also see issue #88.

**Comment by AmadeusW** [comment]
By using a wildcard do you mean that third party analyzer vendors may create a namespace containing  `NativeCodeAnalysis` and these analyzers won't show up for managed code? Or is this solution exclusively for `Microsoft.Analyzers.NativeCodeAnalysis`? If so, how can we extend it to other analyzer packs?

**Comment by tmeschter** [comment]
No, I used a wildcard simply to avoid a really long title for this issue.

This issue is strictly about hiding the "old-style" code analysis rules in the rule set editor when appropriate, which brings them in line with the behavior of "new-style" Roslyn-based analyzers (i.e., by default we only show a rule if the project actually uses that analyzer).

> If so, how can we extend it to other analyzer packs?

I'm not sure what you mean. Can you describe what you are trying to achieve?

**Comment by AmadeusW** [comment]
Thanks, I was wondering about the wildcard.

At first I thought that since we'd show or hide these rules based on runtime, perhaps other rule packages could benefit from this filtering.
On a second thought, the rule sets in question always installed and therefore will benefit from hiding. Third party rule sets can be easily disabled at developer's discretion.

**Comment by tmeschter** [comment]
This has been fixed in the rule set editor.

Assigning to @mavasani  for verification.

**Comment by mavasani** [comment]
@tmeschter  I only see the partial fix for this one latest VSPro_1 drop. 
For managed projects, the ruleset editor correctly hides the native rules, but there seems to be varying behavior for C++ Win32 project.

Repro 1:
1. devenv /resetsettings
2. Create a new C++ Win32 project and open any ruleset from Properties -> Code Analysis tab.

Got:

![defaultruleset_1](https://cloud.githubusercontent.com/assets/10605811/6517547/0aadf516-c351-11e4-8f7f-19ce2321c15e.jpg)

Repro 2:
1. devenv /resetsettings
2. Create a C# console app and open any ruleset from Properties -> Code Analysis tab. As expected, only managed rules show up.
3. Close solution and create a new C++ Win32 project and open any ruleset from Properties -> Code Analysis tab.

Got:

![defaultruleset_2](https://cloud.githubusercontent.com/assets/10605811/6517554/11e79436-c351-11e4-804f-5ebd019bb368.jpg)

**Comment by mavasani** [comment]
Tom pointed out that the filtering is only done for Managed projects to hide native rules, so all is fine here.
