### ISSUE TITLE
[Test Failure] Packages need to be updated in prtest/win/dbg/unit64 on PR #8471

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#8902]
PR: [#8471](https://github.com/dotnet/roslyn/pull/8471) *Add support for adding NuGet references through add-using.* by @CyrusNajmabadi
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/4015/

**Issue 1: Packages need to be updated**
A new package was introduced, but the Azure store of the packages was not updated. Please follow: https://github.com/dotnet/roslyn/blob/master/docs/infrastructure/Updating%20NuGet%20ZIP%20file.

error : The package Microsoft.CodeAnalysis.Elfie with version 0.10.3-rc2 could not be found in C:\Users\dotnet-bot\.nuget\packages. Run a NuGet package restore to download the package. [d:\j\workspace\roslyn_prtest---45fcf4bc\src\VisualStudio\Core\Def\ServicesVisualStudio.csproj]

This is strange.  I did update the nuget zip.  In the logs we can even see this package restored.  Locally cibuild.cmd works properly.

**Comment by Pilchie** [comment]
Tag @dotnet/roslyn-infrastructure @jaredpar Any ideas here?

**Comment by davkean** [comment]
The nuget package that was uploaded is malformed, it's missing a ".nuget" folder.

**Comment by davkean** [comment]
Basically, Cyrus needs to fix the package that he uploaded.

**Comment by Pilchie** [comment]
Sounds like this error is by design then.
