### ISSUE TITLE
IOperation: VB - BoundNullableIsTrueOperator should implement specific interface

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#8912]
This node represents Nulable<Boolean>.GetValueOrDefault() call on the Operand of the node. Either we should add a special OperationKind and an interface for it, or surface it as an IInvocationExpression. Note that this operation is always implicit, i.e. doesn't correspond to any particular syntax.

**Comment by jinujoseph** [comment]
We think this is not necessary for V1

**Comment by jinujoseph** [comment]
Verify and close

**Comment by AlekseyTs** [comment]
Surfaced as an invocation in https://github.com/dotnet/roslyn/pull/26395.
