### ISSUE TITLE
IOperation: VB - BoundMethodGroup should implement specific interface

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#8914]
BoundMethodGroup can survive initial binding in presence of errors. 

Same for BoundPropertyGroup

**Comment by JohnHamby** [comment]
We might get by with having these implement IInvalidExpression.

**Comment by AlekseyTs** [comment]
I think there is a benefit in exposing some information about the group: the name, type arguments, maybe even the set of symbols. Though, semantic model can be used to lookup the symbols based on name and the arity.

**Comment by jinujoseph** [comment]
dupe of https://github.com/dotnet/roslyn/issues/19965
