### ISSUE TITLE
IOperation: VB - BoundLateInvocation should implement specific interface

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#8916]

**Comment by jinujoseph** [comment]
How does this relate to 'dynamic' invocations in C#?  Would we have a single way to represent both?  Or do we need something VB specific?

**Comment by AlekseyTs** [comment]
> How does this relate to 'dynamic' invocations in C#?

It somewhat similar, but different enough to keep them separate, I think.

**Comment by jinujoseph** [comment]
this has been done via https://github.com/dotnet/roslyn/pull/21711
