### ISSUE TITLE
Re-enable InvokeDelegateWithConditionalAccessAnalyzer 

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#8918]
We re-disabled InvokeDelegateWithConditionalAccessAnalyzer due to RPS regressions: https://github.com/dotnet/roslyn/pull/8911/files.

We should reenable it.

**Comment by DustinCampbell** [comment]
It looks like this was re-enabled with #8921.

**Comment by davkean** [comment]
:+1:
