### ISSUE TITLE
VB method block should contain a top-level block statement operation

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#8919]
Currently, methods in VB doesn't yield a top-level block statement operation that includes all the operations in the method body. And `OperationBlockAnalysisContext.OperationBlocks` for VB will returns a list of statements inside method body instead. We should provide a block statement for VB method (synthesize one if necessary).

Related: #11903 #11860

**Comment by 333fred** [comment]
Note that this blocks all attempts to write an analyzer that can target both C# and VB and determine if the method just throws a NotImplementedException. 

Given the following C# code;

```C#
public class C1
{
    public void Method() => throws new InvalidOperationException();
}
```

An OperationBlockEnd analyzer is called back with an `IBlockStatement`, which contains the `IThrowStatement`. The equivalent VB code is;

```VB
Public Class C1
   Public Sub Method()
        Throw New InvalidOperationException()
   End Sub
End Class
```

Here, the OperationBlockEnd analyzer is called back with 2 operations, the `IThrowStatement`, and an `ILabelStatement`.

**Comment by jinujoseph** [comment]
@CyrusNajmabadi  this is done right ?

**Comment by tmat** [comment]
Let's confirm this is fixed.

**Comment by mavasani** [comment]
This is fixed.
