### ISSUE TITLE
(VB) F1 context help for event object qualifier is wrong

### ISSUE THREAD

**Issue by mkleinwaks** [dotnet/roslyn#8922]
Example code:

```
Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click

End Sub
```

Prior to VS2015, if you had the cursor on **Handles *_or *_Button1** and hit F1, you would get the correct help topic on MSDN. However if you hit F1 with the cursor on the **Click** event, you would get the help topic for the sub statement keyword.

In VS2015 this behavior is fixed for Click, but has regressed to now show the sub statement help topic if you hit F1 with the cursor on the object (Button1).

**Comment by CyrusNajmabadi** [comment]
Unlikely to change this behavior now, especially without more customer feedback on this.
