### ISSUE TITLE
In "Navigate To" sort results by type first

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#8924]
Usually when I use ```Ctrl+,```, I'm looking for a type. Let's have a way to either specify I want a type or field or let's sort the results with types at the top.

**Comment by balajikris** [comment]
in addition to the sort, can we allow filters in the search bar as well? 
something like appending `<filter_marking_char><filter_char>+` pattern to the search term..

Haven't completely thought it through, but what I was thinking right now is on the lines of

`semanticmodel :f` filters to field symbols
`semanticmodel :fm` filters to field and method symbols

thoughts?

**Comment by balajikris** [comment]
or does this already exist? I have this vague feeling that the editor made some improvements to the search bar but i never really caught up on those or have used those since.

**Comment by Pilchie** [comment]
Note that the platform team is planning on making changes to make it possible to filter results, so we may not need to do anything explicit on our side.

**Comment by Pilchie** [comment]
Moving to RC, since the platform side changes are not in yet.

**Comment by Pilchie** [comment]
@CyrusNajmabadi did the requisite work on our side.  This is done now.
