### ISSUE TITLE
Refactoring: private field from constructor and vice versa

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#8925]
Let's add these refactorings to help with developer productivity:
- Add private field from constructor argument
- Add constructor argument for private field

**Comment by chborl** [comment]
Both of these are covered in existing refactorings.
* Add private field from constructor argument is covered [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/InitializeParameter/AbstractInitializeMemberFromParameterCodeRefactoringProviderMemberCreation.cs,101)
* Add constructor argument for private field is covered [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/InitializeParameter/AbstractInitializeMemberFromParameterCodeRefactoringProviderMemberCreation.cs,101)

**Comment by ReubenBond** [comment]
What am I doing wrong here?

![image](https://user-images.githubusercontent.com/203839/52762450-87d18580-2fcc-11e9-976e-26ccb63ba4e4.png)

I would like the code fix to suggest adding a parameter to the constructor to initialize the field.

**Comment by chborl** [comment]
@ReubenBond , thank you for the feedback.  I found a couple of issues with the feature that are preventing the scenario you mentioned from working as expected so I"m reopening this issue and hope to have a fix soon.

**Comment by chborl** [comment]
I've opened 3 new issues for tracking improvements to the "Add Parameters to constructor" and "Generate Constructor" refactorings.  

#33601 
#33602 
#33603

**Comment by chborl** [comment]
Closing this issue.  Other tracking issues have been opened.
