### ISSUE TITLE
"Execute in Interactive" has an incorrect shortcut of ALT+ENTER

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#8927]
While this appears to be F# bug in that it's registering ALT+ENTER as a global Text Editor command, I'm filing this to track the issue on our side.

![image](https://cloud.githubusercontent.com/assets/1103906/13182915/12f6433e-d6e9-11e5-950d-60ff5fad66de.png)

**Comment by ManishJayaswal** [comment]
@drognanar FYI
I think we fixed this to be ctrl+E, ctrl+E.
