### ISSUE TITLE
Move 'Navigate To' search bar to center of the screen

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#8929]
I've had several customers say that they work on large monitors and they lose productivity when their eye has to jump to the top-right of the screen to type/view results in Navigate To. They suggest that we move the search bar to where their cursor is, or to the middle of the editor.

**Comment by nikmd23** [comment]
I love this idea, I use a 3rd party extension that does something similar which I really like

**Comment by DustinCampbell** [comment]
Love it. Let's work with the editor team to get it done.

**Comment by balajikris** [comment]
:+1:

**Comment by DustinCampbell** [comment]
Closing this because it's not really an item for our backlog. @kuhlenh, please chat with the editor team about this one.
