### ISSUE TITLE
Help generate boilerplate for immutable and readonly classes

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#8930]
Customer mentioned he would like to see a refactoring to help with Equality interface generation.

**Comment by DustinCampbell** [comment]
Isn't this a code generator scenario?

**Comment by jcouv** [comment]
There is a refactoring to override `Equals` and `GetHashCode`, which also can generate `operator==` and `operator!=`.

So I think this issue can be closed.

![image](https://user-images.githubusercontent.com/12466233/38463624-aa91bef0-3ab3-11e8-891c-893cbd383992.png)

![image](https://user-images.githubusercontent.com/12466233/38463628-b842f10e-3ab3-11e8-8767-94cd7057d06a.png)
