### ISSUE TITLE
Refactoring: Move Class To File

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#8932]
Add 'Move Class to File' refactoring for developers who write all their classes in one file and then extract each class out to a file with the same name.

**Comment by DustinCampbell** [comment]
@balajikris: @Pilchie says you're already working on this aren't you?

**Comment by balajikris** [comment]
yep! forgot to assign it to self, thanks for assigning.

**Comment by balajikris** [comment]
Implemented in https://github.com/dotnet/roslyn/pull/12624
