### ISSUE TITLE
Code Style: Allow a limit on method lengths

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#8934]
Several customers mentioned that they have limits on how large a method can be (this is to help developers think about "properly" decomposing methods). 

Can we add a style setting to enforce a max length for a method?

**Comment by DavidArno** [comment]
:+1:

**Comment by bkoelman** [comment]
How is method size to be measured? Could be lines of code. But then reformat may cause new warnings if existing size is close to the threshold.

My analyzer counts statements, see https://github.com/bkoelman/CSharpGuidelinesAnalyzer/blob/master/src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Rules/Maintainability/AvoidMembersWithMoreThanSevenStatementsAnalyzer.cs.

**Comment by CyrusNajmabadi** [comment]
I don't think we would do this.  However, a user could always write their own analyzer trivially that could encode what ever complexity checks they or their org felt was relevant.
