### ISSUE TITLE
Roslyn.InteractiveWindow tests are still running into EventListener bug

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#8936]
We're still hitting this ~3 or 4 builds a week:

```
xUnit.net Console Runner (32-bit .NET 4.0.30319.42000)
  Discovering: Roslyn.InteractiveWindow.UnitTests
  Discovered:  Roslyn.InteractiveWindow.UnitTests
  Starting:    Roslyn.InteractiveWindow.UnitTests
  Finished:    Roslyn.InteractiveWindow.UnitTests
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at System.Diagnostics.Tracing.EventListener.DisposeOnShutdown(Object sender, EventArgs e)
```

Bounty

**Comment by davkean** [comment]
Maybe try and increase the timeout of the 10 second test that @amcasey added?

**Comment by ManishJayaswal** [comment]
@amcasey I thought we had worked around the EventListner issue? Is this still happening?

**Comment by amcasey** [comment]
@ManishJayaswal We _guessed _that a 10 second delay would work around the problem _most_ of the time.  I believe it's still happening.

**Comment by amcasey** [comment]
@ManishJayaswal According to the comments on https://github.com/dotnet/corefx/issues/3793, it should be fixed in 4.6.2.

**Comment by davkean** [comment]
That doesn't help us.

**Comment by davkean** [comment]
We're also still apparently running into it on open builds again: https://github.com/dotnet/roslyn/issues/9464

**Comment by ManishJayaswal** [comment]
@davkean @amcasey Do we need an exception for this till we move to 4.6.2 or is there a workaround we are looking to implement?

**Comment by davkean** [comment]
No exception - we're hitting this too many times. What's not linked here is all the failures we're hitting the signed builds. 

Either you guys probably to figure out how to run tests without an isolated AppDomain.

**Comment by TyOverby** [comment]
This is happening in at least `stabilization`

**Comment by srivatsn** [comment]
Assigning to Manish to find someone to work on this once @davkean's change is in.

**Comment by ManishJayaswal** [comment]
@davkean please let me know once your change is in and how we can leverage it, if we at all can.

**Comment by davkean** [comment]
I merged my change in: https://github.com/dotnet/roslyn/pull/9782

**Comment by davkean** [comment]
And we hit this again: http://dotnet-ci.cloudapp.net/job/roslyn_future_win_rel_unit32/139/consoleFull#14857372926baeffce-8504-4013-981e-7f26b5265816
