### ISSUE TITLE
Investigate failure of FileShareDeleteCompatibility_ReadOnlyFiles test on Mac

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#8939]
The test works on Windows and Linux, fails on Mac.

Seems like `File.SetAttributes(libDll.Path, FileAttributes.ReadOnly)` doesn't restrict access to the file on Mac.  

Enable the test if possible.

**Comment by jaredpar** [comment]
Closing for now.  Will re-consider this and all other tests when we do the mass enable.
