### ISSUE TITLE
RenameMergedNamespaceAcrossProjects is flaky

### ISSUE THREAD

**Issue by TyOverby** [dotnet/roslyn#8946]
Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameEngineTests.RenameMergedNamespaceAcrossProjects 

http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/4061/consoleFull#-865691239f8aae81d-4bec-45a1-8770-9e05a4fee5ca

**Comment by dpoeschl** [comment]
Closing in favor of main tracking bug #9308.

@jasonmalinowski This is a crosslanguage rename test failure. If you see any reason to keep this separate from the rest, feel free to reopen.
