### ISSUE TITLE
Investigate and implement correct propagation of modopts in byref members

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#8948]
C# does not define modopts, but we could be overriding/implementing an existing byref returning method with modopts. (  long& Foo()  in managed c++ ? )

We need to ensure that the modifiers in the signature are correctly propagated to the overriding/implementing method.

**Comment by VSadov** [comment]
@AlekseyTs - FYI

**Comment by tmat** [comment]
I think we should consider changing the way how we represent modopts and by-ref types internally in Roslyn symbols. I'm not sure if this will be feasible but I'm throwing the idea out there anyways :). 
I propose we have a type symbol that adds byref to another type symbol and a type symbol that adds modifiers to another type symbol. Similarly to ```PointerTypeSymbol``` which makes a pointer out of a type. To maintain API compatibility we can unwrap the target type in the public properties/methods that return the type and expose the wrapped type by new properties (e.g. called ModifiedType). I believe this would simplify decoding types from metadata and symbol manipulation internally. It could also simplify IOperation working on IL level. @nguerrera and I discussed current issues around modified and by-ref types recently.

**Comment by VSadov** [comment]
In C#/VB   byref is a signature constraint and is not a part of a type. 
For example: ```ref int x``` parameter is no different from ```int x``` parameter in vast majority of scenarios like overload resolution, lambda inference, applicability of operators. - ref just specifies the parameter passing convention. The type of the parameter is an int regardless.

Making refness a part of the type will result in massive special cases in many areas.

**Comment by tmat** [comment]
Don't quite get the overload resolution argument. ```F(ref int a)``` is a different overload than ```F(int a)```. But sure I assume there are more places that would need to be special cased then there are places now.

**Comment by VSadov** [comment]
What I mean is that code inside the following methods currently binds exactly the same. 
"ref" on the parameter is irrelevant for the purpose of the binding. For all binding/inferencing/casting/math purposes x is just an int in both cases. 

That would not be a case for pointers since ```int``` and ```int*``` are indeed distinct types.

```C#
        static void Foo(int x)
        {
            x += x++ - x * 123;    // this is a bunch of int math
            OverloadThis(x, AndInferThat(Tuple.Create(x, x + 1, x > 1 ? x: 1 )));
            . . . 
        }

        static void Foo(ref int x)
        {
            x += x++ - x * 123;    // this is a bunch of int math
            OverloadThis(x, AndInferThat(Tuple.Create(x, x + 1, x > 1 ? x: 1 )));
            . . .
        }
```

**Comment by tmat** [comment]
Gotcha. Seems that ByRefs are good to have separately. What about custom modifiers?

**Comment by tmat** [comment]
Never mind - it's the same :)

**Comment by nguerrera** [comment]
This is probably very naive, but I don't understand in the abstract why the "massive special cases" couldn't instead be dealt with via polymorphisn. I.e. Modified symbol behaves like underlying symbol where appropriate.

**Comment by AlekseyTs** [comment]
There is no much benefit in doing this in my opinion.

**Comment by AlekseyTs** [comment]
The nature of the issue is that we are likely not capturing the relative order between ByRef modifier and custom modifiers for return types in metadata signatures (ByRef-ness of return types wasn't supported). So, when we emit the signature at the callsite, we might get the order wrong. This problem is already solved for parameter types. We simply need to make sure the information is captured for return types during metadata import and flows to emit layer in a similar fashion.
