### ISSUE TITLE
[PDB] PDB is missing sequence points when #ExternalSource is used in VB

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#8949]
This problem is illustrated by the `TwoMethodsOnlyOneWithMultipleMappingsAndRewriting` unittest. The first two sequence points of the Main method are hidden, when they should not. 
That unittest has incorrect expectations.

This bug causes poor debugging experience (you can't debug the first statement, which is before `#ExternalSource`). But it only occurs when the method contains `#ExternalSource`.

**Comment by jcouv** [comment]
The code that produces this behavior is commented and this is explicit. Confirmed with @tmat and will close.

See [comment](http://source.roslyn.io/#Microsoft.CodeAnalysis.VisualBasic/Syntax/VisualBasicLineDirectiveMap.vb,1d0841019e540e6c)

**Comment by AlekseyTs** [comment]
@jcouv Did you close this issue because behavior is By Design? Could you add a [Resolution - By Design] label then?
