### ISSUE TITLE
Nameof with open generic types

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#8952]
Currently your code will not compile if you try to use `nameof(TestType<,>)`. Even though the type arguments have absolutely no effect on the name, you are required to choose and type out arguments: `nameof(TestType<object, object>)`.

This is even worse when there are type constraints that `object` does not satisfy. You have to stop and look up how to satisfy them. It's even possible to create type constraints that require you to *create a new type* to satisfy the constraints (implement two random interfaces), just so you can use `nameof` on the type or a member of the type. While this last scenario is unlikely, it drives home the point that closed generics are a completely orthogonal concern to `nameof` expressions.

The type arguments are irrelevant to the name of the type and of the type's immediate members, and likely to all members accessible anywhere from the type. The only exception is this: an argument could be made that the child members of a child member can't be determined without a closed generic type, but in that convoluted scenario you know the type you're after and you should just use that type directly to access the name of its member.

I request that `nameof` be able to get the name of open generic types. Unfortunately it's too late to ban the use of `nameof` with closed generic types but I believe it should be discouraged.

```C#
public class SnarkyTestType<X, Y> where X : IRandomInterface1, IRandomInterface2
{
    public void TestMethod<Z>()
    {        
    }
}

nameof(SnarkyTestType<?, object>.TestMethod) // Gotcha. The only classes that satisfy this are internal to a different assembly.


public class TestType<X, Y> where X : IComparer<Y> where Y : struct
{
    public void TestMethod<Z>()
    {
    }
}

nameof(TestType<IComparer<int>, int>.TestMethod) // Gotcha anyway, wasted your time and made you write terrible code
```

**Comment by alrz** [comment]
#4827
