### ISSUE TITLE
Analyzers and code fixes for converting Loop Family 

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#8953]
[ Revised - 3/8/2018] 
- [x] Release 1 [ Targeted for 15.7]
     - [x] LINQ query to foreach [C#] (PR https://github.com/dotnet/roslyn/pull/25362)
     - [x] for to foreach (PR https://github.com/dotnet/roslyn/pull/25469)
     - [x] foreach to for (PR https://github.com/dotnet/roslyn/pull/25460)

- [ ] Release 2  [ Targeted for 16.0]
     - [x] foreach to linq query (https://github.com/dotnet/roslyn/pull/27130)
     - [x] foreach to LINQ method (https://github.com/dotnet/roslyn/pull/29402)
     - [ ] LINQ method to foreach 
     - [ ] for to LINQ method 

- [ ] Release 3  [ TBD]
LINQ query to foreach [VB]
LINQ query to LINQ method
LINQ method to LINQ query 

[TBD] 
LINQ method to for 
LINQ query to for 
for to LINQ query
do/while to LINQ

**Comment by jasonwilliams200OK** [comment]
Also foreach, while and do-while loops would be nice.

**Comment by alrz** [comment]
Would be nice to also add,

- convert foreach to for (and vice versa)
- convert foreach to linq (and vice versa)
- convert linq to call chain (and vice versa)
- convert foreach to using and while

**Comment by CyrusNajmabadi** [comment]
FYI @jinujoseph the above list seems to be incorrect.   Specifically: 

![image](https://user-images.githubusercontent.com/4564579/47043917-b71dd600-d143-11e8-80f0-a9f2cf6b0357.png)

This does not seem to have been done.

**Comment by jinujoseph** [comment]
@CyrusNajmabadi you are right , was a copy-paste mistake ..fixed it

**Comment by mikadumont** [comment]
Copying direct customer ask below for loop to LINQ refactoring: 

> I’m pretty bad at LINQ, so I do this all the time to swap between foreach and LINQ using ReSharper:
 
![image](https://user-images.githubusercontent.com/46729679/87329002-32fcac00-c4eb-11ea-951b-a44bb9ec1bc1.png)

> Which results in something like this:
 
![image](https://user-images.githubusercontent.com/46729679/87329075-4576e580-c4eb-11ea-8cd2-40584122c39b.png)

> This really helps me learn LINQ better. This is the main benefit of ReSharper for me personally. 

> The instructions you sent say  “Ctrl+. or Alt+Enter to trigger the Quick Actions and Refactoring menu. Select convert to LINQ” – but this does nothing for me, just “reverse ‘for’ statement” in Microsoft Visual Studio Enterprise 2019 Version 16.6.2

![image](https://user-images.githubusercontent.com/46729679/87329110-4f98e400-c4eb-11ea-9973-8d2c333e7679.png)

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
