### ISSUE TITLE
Audit our VS project system shims and put foreground assert that will be only called from VS on UI

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#8954]
our VS Project System code implements a lot of VS interface and none of them have assert for foreground thread. we should add those check to all those.

**Comment by davkean** [comment]
Which code in particular? When I see "VS Project System code", I think CPS: https://github.com/dotnet/roslyn/tree/future/src/VisualStudio/ProjectSystem. But I'm thinking you mean, code that interacts with VS project system code?

**Comment by jasonmalinowski** [comment]
@davkean: I think the rest of us think our existing ball of mud shims. I've updated the title to clarify.

**Comment by jasonmalinowski** [comment]
Current plan would be to make this be more free-threaded.
