### ISSUE TITLE
consider checking whether all metadata reference exist on dll or not for IsCompleteAsync API

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#8956]
right now Project.IsCompleteAsync API doenst check whether all metadata reference exist on disk or not. one of reason we currently doesnt do it is we are not sure where we should do that.

we certainly can't do it on FinalizeCompilation since it require disk IO and that method is really hot path.

**Comment by CyrusNajmabadi** [comment]
Unlikely to do anything here.
