### ISSUE TITLE
Create future-stabilization branch

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#8966]
- [x] Create future-stabilization branch on Roslyn repro
- [x] Create future-stabilization branch on Roslyn-Internal repro
- [x] Create future-stabilization branch on VSO Roslyn repro
- [x] Create future-stabilization branch on VSO Roslyn-Internal repro
- [x] Update pump to sync future-stabilization from Roslyn -> Roslyn-internal
- [x] Update pump to sync future-stabilization from Roslyn ->  VSO
- [x] Update pump to sync future-stabilization from Roslyn-internal ->  VSO
- [x] Update auto-merge tool to merge future-stabilization -> future
- [x] Update auto-merge tool to merge stabilization -> future-stabilization
- [x] Turn off force pushes
- [x] Add commit jobs for Roslyn repro
- [x] Add commit jobs for Roslyn-Internal repro

**Comment by TyOverby** [comment]
The checklist right now: 

## Getting caught up on existing pull requests
* [ ] Roslyn
    * [x]  merge master -> future
    * [ ] merge stabilization -> master
* [ ] Roslyn Internal
    * [ ]  merge master -> future
    * [x] merge stabilization -> master

## Getting up to date another round of automated pull requests
* [ ] Roslyn
    * [ ] merge master -> future
    * [ ] merge stabilization -> master
* [ ] Roslyn Internal
    * [ ]  merge master -> future
    * [ ] merge stabilization -> master
