### ISSUE TITLE
Re-enable VSI/ETA disabled tests

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#8970]
| Disabled test name | BugID | Comments |
| --- | --- | --- |
| CSharpRazor | #6851 | Blocked until Update 1 reaches build machines |
| AddMissingReference | VSO 114072 | Apparently only breaks on community edition. HAsn’t been touched since July 25th last year |
| AnalyzersNode | VSO 129870 | Closed bug that is actually for C# and vb codeactions failure. Apparently they were failing because Roslyn Analyzers were moved to a separate repository |
| BasicDoesntLoadCSharp | TFS 1190467 | Bug was closed fixed back in July |
| BoxSelection.xml | No bug | No bug linked, comment is ‘#prompt not supported’ |
| CodeAnalyisRulesetEditor | VSO 129870 | Closed bug that is actually for C# and vb codeactions failure. Apparently they were failing because Roslyn Analyzers were moved to a separate repository |
| CodeAnalysisRulesetFile | VSO 129870 | Closed bug that is actually for C# and vb codeactions failure. Apparently they were failing because Roslyn Analyzers were moved to a separate repository |
| CSharpAsyncOutput | No bug | No bug linked, comment is ‘#prompt not supported’ |
| CSharpDoesntLoadVB | TFS 1190467 | Bug was closed fixed back in July |
| CSharpInteractiveDirectives | VSO 130166 | Active bug assigned to KevinH. Apparently broken due to https://github.com/dotnet/roslyn/pull/4675 |
| CSharpSendToInteractive | #4688 | I believe 2 of the 3 functions mentioned here were recently added to VSUML. Will likely be blocked until update 2 reaches build machines |
| CSharpSharedProjects | #5343 | Active bug. Things aren’t being updated correctly or closed correctly with shared files. |
| TypeScript | VSO 129987 | Resolved bug. According to bug, these were discussed and decided that this can’t be enabled outside of standalone runs. |
| SolutionExplorer | #8434 | Testhook is unable to expand item inside Solution Explorer |
| BasicSnippets, BasicWPF, CSharpSnippets, CSharpWPF | #8430 | Several standalone integration tests fail to close target correctly |

**Comment by davkean** [comment]
tag @Pilchie @srivatsn for this week.

**Comment by jasonmalinowski** [comment]
We're tracking these in individual bugs now.
