### ISSUE TITLE
Exception should not be thrown on rename conflict

### ISSUE THREAD

**Issue by Wazner** [dotnet/roslyn#8973]
An `InvalidOperationException` is thrown when a method in a partial class is renamed to the name of a type parameter. This exception causes Visual Studio 2015 to **crash**.

Minimal code to reproduce (Can also be reproduced in Visual Studio using the `SourceText` contents):
```C#
var sourceText = SourceText.From(@"
  partial class Cls<T> {
      public void Method(T arg) {}
  }
  partial class Cls<T> {}
");

var workspace = new AdhocWorkspace();
var projectId = ProjectId.CreateNewId();
var documents = new[] { DocumentInfo.Create(DocumentId.CreateNewId(projectId), "TestFile.cs", loader: TextLoader.From(sourceText.Container, VersionStamp.Default)) };
var projects = new[] { ProjectInfo.Create(projectId, VersionStamp.Default, "TestProject", "TestProject", LanguageNames.CSharp, documents: documents) };
var solution = workspace.AddSolution(SolutionInfo.Create(SolutionId.CreateNewId(), VersionStamp.Default, null, projects));
var semantic = solution.GetDocument(documents[0].Id).GetSemanticModelAsync().Result;
var childNodes = semantic.SyntaxTree.GetCompilationUnitRoot().ChildNodes();
var method = semantic.SyntaxTree.GetCompilationUnitRoot().ChildNodes().Cast<ClassDeclarationSyntax>().SelectMany(c => c.Members).Cast<MethodDeclarationSyntax>().First();
var symbol = semantic.GetDeclaredSymbol(method);
var newSolution = Renamer.RenameSymbolAsync(solution, symbol, "T", null).Result;
```

I tracked this `InvalidOperationException` back to `CSharpRenameConflictLanguageService.ComputeDeclarationsAsync`. Here it is assumed that a type parameter only has a single location:
```C#
foreach (var typeParameter in renamedSymbol.ContainingType.TypeParameters)
{
    if (typeParameter.Name == renamedSymbol.Name)
    {
        var typeParameterToken = typeParameter.Locations.Single().FindToken(cancellationToken);
        conflicts.Add(reverseMappedLocations[typeParameterToken.GetLocation()]);
    }
}
```
_src\Workspaces\CSharp\Portable\Rename\CSharpRenameRewriterLanguageService.cs:894_

I think a conflict should be added for either all type parameter locations or just the one of the class containing the method (But what if a partial method is in a diffrent partial class!).

I'm happy to post a pull request after it is clear how to solve this problem.

**Comment by davkean** [comment]
I believe this is known, but I can't find the dup. @dpoeschl?

**Comment by dpoeschl** [comment]
Yep, we're tracking this with https://github.com/dotnet/roslyn/issues/7440

Thanks for letting us know about this, @Wazner!
