### ISSUE TITLE
Create a seed job for Roslyn's ETA/VSI jobs

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#8977]
We generate all of our jobs automatically in our netci.groovy script except for open's ETA/VSI jobs. This causes it to be out of sync with the other jobs as we make changes. 

We should generate these jobs automatically:
http://dotnet-ci.cloudapp.net/view/roslynpr/job/dotnet_roslyn_prtest_win_vsi_p0/
http://dotnet-ci.cloudapp.net/view/roslynpr/job/dotnet_roslyn_prtest_win_vsi_p1/
http://dotnet-ci.cloudapp.net/view/roslynpr/job/dotnet_roslyn_prtest_win_vsi_p2/
http://dotnet-ci.cloudapp.net/view/roslynpr/job/dotnet_roslyn_prtest_win_vsi_p3/

**Comment by jasonmalinowski** [comment]
@jaredpar, this is complete now, correct?

**Comment by jaredpar** [comment]
This is complete now.  Closing.
