### ISSUE TITLE
All Analyzer entry points need to be audited to make sure that every one is wrapped in a catch-all exception handler

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#898]
Analyzer exceptions (even from the analyzer engine) should never propagate exceptions into the compiler  (see #865 for an example) and every entry point into analyer code, including things like hooking assembly load, need to be audited for this.

**Comment by srivatsn** [comment]
#865, #868 and #887 are basically all the entry points from the compiler. However, it will be good to get another pair of eyes on it. Assigning to @tmeschter

**Comment by tmeschter** [comment]
I took a look at this, and the only unprotected entry point I see is a place where our Solution Explorer code calls `SupportedDiagnostics`. I'll fix that and close the bug.

**Comment by tmeschter** [comment]
Since the point of this bug was to verify that we're not leaking exceptions, I'm marking this as verified.
