### ISSUE TITLE
AllInOne file does not cover C# 6.0 features

### ISSUE THREAD

**Issue by KvanTTT** [dotnet/roslyn#8984]
They can be found here: https://gist.github.com/KvanTTT/86b7b92514da9a409524

**Comment by davkean** [comment]
What is "AllInOne"?

**Comment by KvanTTT** [comment]
This file contais "AllInOne": https://github.com/dotnet/roslyn/blob/master/src/Test/Utilities/Desktop/TestResource.resx
This file used by several tests.

**Comment by davkean** [comment]
:+1: Thanks.

**Comment by davkean** [comment]
If you are feeling brave, we'll accept a PR to make the suggested changes.

**Comment by KvanTTT** [comment]
Ok, I will do PR :)

**Comment by gafter** [comment]
There is a community-submitted PR for this at #8999. It is old so possibly obsolete.
