### ISSUE TITLE
Proposal: Splatting

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#8987]
As it is proposed in #347 you might be able to use splatting in method arguments

> ``` cs
> public double Avg(int sum, int count) => count == 0 ? 0 : sum / count;
> Console.WriteLine($"Avg: {Avg(Tally(myValues))}");
> ```

And unsplatting would be like:

> ``` cs
> var list = List<(string name, int age)>();
> list.Add("John Doe", 66); 
> ```

In the first case it's rather too implicit and as discussed, there should be some kind of operator to make it more visible.

``` cs
Console.WriteLine($"Avg: {Avg(...Tally(myValues))}");
```

I want to propose the ability to use this syntax on tuples themselves e.g.

``` cs
var foo = (1,2);
var bar = (...foo, true);

// translates to
var bar = (foo.Item1, foo.Item2, true);
```

In this case the target expression must be of a tuple type (names will be preserved in the resultant tuple).

Same syntax can be used with anonymous types.

``` cs
var foo = new { Name = "foo", Family = "bar" };
var bar = new { ...foo, Age = 0.5 };

// translates to
var bar = new { foo.Name, foo.Family, Age = 0.5 };
```

This is specifically useful in pipeline processing (like LINQ) to compose short-lived tuples with additional information added in each step.

**Comment by DavidArno** [comment]
I'd suggest the syntax for your first two examples would probably need to be:

```cs
public double Avg(int sum, int count) => count == 0 ? 0 : sum / count;
Console.WriteLine($"Avg: {Avg(...Tally(myValues))}"); // ... means map tuple to two params of Avg
```
And 
```cs
    var list = List<(string name, int age)>();
    list.Add(("John Doe", 66)); // inner () needed to denote it's a tuple, not two separate params 
```

**Comment by alrz** [comment]
@DavidArno That's the exact syntax proposed in #347. The rest of examples are my suggestion.

**Comment by DavidArno** [comment]
@alrz,

Thanks. I've cross-referenced my suggestion there too.

**Comment by bondsbw** [comment]
If `...` is used as an actual language syntax, it could completely change the meaning of many of the issues and proposals on in this forum.   :wink:

**Comment by alrz** [comment]
@bondsbw I'm not fond of the syntax here, however, this is what ES, C++ and Java are actually using for various purposes. "it could completely change the meaning of many of the issues and proposals on in this forum" yeah actually it's kind of a breaking change ;).

**Comment by alrz** [comment]
Not sure how this should work with generic constraints, specially with #2206,
```cs
// #2206
T F<T>() where T : new (int, int)
{
  return new T(1, 1);
}

// splatting
var t = (1, 1);
new C(t...); // new C(t.Item1, Item2);

// should this work?
T F<T, TArgs>(TArgs args) where T : new(TArgs)
{
  return new T(args...);
}
```

**Comment by alrz** [comment]
Moved  to https://github.com/dotnet/csharplang/issues/424
