### ISSUE TITLE
[Proposal] Add an API for clients to get at assembly metadata without creating a compilation

### ISSUE THREAD

**Issue by pharring** [dotnet/roslyn#899]
Today you have to create a Compilation and add an assembly reference to that before you can get at the metadata.

We have a number of clients who would like to use Roslyn APIs to read metadata from assemblies that aren't necessarily associated with a compilation. They can do it, but it's a bit long-winded.

When doing this, we should ensure that, if the assembly in question is already loaded via some other compilation, that we just share existing data structures rather than opening up a new view on the metadata.

**Comment by theoy** [comment]
We need to think about this some more - the compilation has some meaningful representation about the context from which the metadata will resolved.

**Comment by gafter** [comment]
To add to the comment by @theoy ...

Because the symbol table is a *language-specific* view of the IL, we need to know which language to view it as. For example, when you write

```cs
INamedTypeSymbol type = ...;
string name = ...;
ImmutableArray<ISymbol> members = type.GetMembers(name);
```

whether or not the name lookup is case-sensitive or not is dependent on which language your compilation is.

**Comment by gafter** [comment]
@theoy can you please "Verify" that this is an appropriate resolution?

**Comment by gafter** [comment]
Verified that we didn't fix this ;(
