### ISSUE TITLE
BasicAnalyzers and CSharpAnalyzers are deploying to the wrong hive

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#8995]
![image](https://cloud.githubusercontent.com/assets/1103906/13205247/eabee914-d898-11e5-88ef-199f2af3a095.png)

This should be 14.0RoslynDev, not 14.0Roslyn.

**Comment by davkean** [comment]
Also, why do they have @mavasani's user name as company?

**Comment by jmarolf** [comment]
Thats the default info that the SDK generates when you create a new project.  We deploy to the `Roslyn` in the SDK and use your username.

**Comment by mavasani** [comment]
Yes, just need to update it.

**Comment by diryboy** [comment]
If a user is writing analyzers themselves, things get deployed to the Roslyn suffix, isn't samples are expected to be deployed to the same suffix?

**Comment by davkean** [comment]
Yeah, perhaps. Either way they should be deployed to "Roslyn" or all deployed to "RoslynDev" - not a mix.

**Comment by jmarolf** [comment]
Issue moved to [dotnet/roslyn-sdk #52](https://github.com/dotnet/roslyn-sdk/issues/52) via [**ZenHub**](https://www.zenhub.com/)
