### ISSUE TITLE
SemanticModel.GetArgumentInfo API needed to retrieve the IParameterSymbol that an ArgumentSyntax binds to

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#9]
This is a missing API. Writing a diagnostic that process an argument requires a fair amount of code to determine what parameter the argument binds to -- checking for named or positional arguments.

**Comment by dbolkensteyn** [comment]
+ the variable-argument (`params`) use case should also be dealt with when positional arguments are used.

**Comment by DustinCampbell** [comment]
@dbolkensteyn, certainly! Here's an example of what I did in C# Essentials, which is how this API might look:

https://github.com/DustinCampbell/CSharpEssentials/blob/master/Source/CSharpEssentials/Extensions.cs#L45-L137

**Comment by Youssef1313** [comment]
Is `IArgumentOperation.Parameter` not enough here?

**Comment by CyrusNajmabadi** [comment]
Yes. I think we can close this now that we have ioperation. Thanks!
