### ISSUE TITLE
Generate Constructor doesn't handle readonly auto-props

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#9022]
``` C#
public struct MethodCoverageResult
{
    public string Method { get; }
}
```

It handles regular auto-props, so there's probably an incorrect accessor check.

**Comment by amcasey** [comment]
FYI @CyrusNajmabadi @rchande

**Comment by jmarolf** [comment]
fixed with https://github.com/dotnet/roslyn/pull/14827
