### ISSUE TITLE
Suggestions for Find Refs

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#903]
Related to #891, I wanted to open an issue that tracks improvements/suggestions to Find references.

Combined list of suggestions:
1. ~~shorten file paths (@DustinCampbell)~~ https://github.com/dotnet/roslyn/commit/3459653f5ecfc7b353f2391b35fa255bcdb352ed
2. allow filters: filter references (@balajikris)
   - ~~by project.~~ https://github.com/dotnet/roslyn/commit/3459653f5ecfc7b353f2391b35fa255bcdb352ed
   - by source (filters out results from metadata and generated `*.i.*.cs` files etc.).
3. collapse all / expand all nodes (@balajikris)
4. ~~allow for searching (@shyamnamboodiripad)~~ https://github.com/dotnet/roslyn/commit/3459653f5ecfc7b353f2391b35fa255bcdb352ed
5. Track result locations in the editor so that navigation after document edits still works (@CyrusNajmabadi)
6. Categorize References by Read/Write (@CyrusNajmabadi)
7. ~~Classify Text (@CyrusNajmabadi)~~ https://github.com/dotnet/roslyn/commit/3459653f5ecfc7b353f2391b35fa255bcdb352ed
8. ~~Potentially show a preview window next to the display (like IntelliJ) (@CyrusNajmabadi)~~ https://github.com/dotnet/roslyn/commit/3459653f5ecfc7b353f2391b35fa255bcdb352ed
9. Potentially align the text snippets. (@CyrusNajmabadi)
10. ~~Potentially categorize by file. (@CyrusNajmabadi)~~ https://github.com/dotnet/roslyn/commit/3459653f5ecfc7b353f2391b35fa255bcdb352ed
11. Mark definitions/references as "generated" if appropriate. (@dpoeschl, split from internal item 531402)
12. Display known kinds of references more explicitly, like derived types should be marked as such, instead of opaque "reference". Same for interface implementations, overridden members, base types, etc. (@KirillOsenkov)
13. ~~Populate asynchronously from multiple background threads (@KirillOsenkov)~~ https://github.com/dotnet/roslyn/commit/3459653f5ecfc7b353f2391b35fa255bcdb352ed
14. Multiple result sets (e.g. multiple tabs for each search) (@KirillOsenkov) (Dependent on Editor)
15. The ability to view previous search results without repeating a search (@rchande)
16. Scope by kind of project (Test versus Shipping, etc.) (@dpoeschl)
17. ~~Put search term in the Find Results title bar (@kuhlenh)~~ https://github.com/dotnet/roslyn/commit/3459653f5ecfc7b353f2391b35fa255bcdb352ed
18. Change default preselection in results window (@kuhlenh)

**Comment by Pilchie** [comment]
Let's use this to track feedback on the new design as people get to use it and see what we want to try and pull in for RTM.

**Comment by shyamnamboodiripad** [comment]
I think adding search would be extremely useful. For example, I am currently working on some changes to the Simplifier API and I often find myself triggering find all references for 'Simplifier.Annotation'. There are ~180 references for this annotation in Roslyn.sln. But I always know which references I am looking for (for example, sometimes I only want to see references that are inside any of the 'reducers' - other times, I am just looking for references in the 'name reducer's). It would be great if I could filter the list by searching for "reducer" or "name reducer" or "csharp reducer" etc. (much like I can do today in navigate to).

**Comment by dpoeschl** [comment]
Adding a comment from internal TFS bug #1027712 (from @CyrusNajmabadi):

```
It is annoying in C# when we do a 'find refs' and then start F8'ing through the results, makes an edit, and subsequent find results are in the wrong location.
 
Heejae recently made a fix for a similar issues with the error list.  When we open a file, we attempt to create tracking spans for the results in the error list.  That way, if you make edits, and hten F8 through the error list, you have a much better chance of going to the right place.  
 
A similar fix wuld be great for Find-refs.  
 
Note: the editor already seems to do this for 'find in files'.  So this would make this one last feature feel much more in line with many other features in VS.
 
Thanks!
```

With the response from Kevin:

```
The problem here is that we don't actually know the lifetime of the results list we return to the editor in this case.
```

**Comment by CyrusNajmabadi** [comment]
Note: we do "shorten file paths" for the TypeScript case:

![image](https://cloud.githubusercontent.com/assets/4564579/7079174/36f37af6-ded6-11e4-939a-b5ebf1646474.png)

It's super nice, and makes the UI seem much more cluttered.

Other things to do:

1) Categorize references by 'Read/Write' usage.
2) Classify the text that is shown.  It's basically a big wall of black text.  
3) Potentially show a preview window next to the display (like IntelliJ)

**Comment by DustinCampbell** [comment]
Great suggestions Cyrus. We're in chats with the Editor team about what we'd like to do here. We'll include you in those.

**Comment by dpoeschl** [comment]
I've updated the list of suggestions in the original post to include all of these suggestions. Thanks!

**Comment by dpoeschl** [comment]
@Pilchie - Are there any of these we would consider for 1.0 (stable)? I'd like to move this tracking bug to 1.1 and make individual issues in 1.0 (stable) for any that we want to actually consider for that milestone. 

The only ones that look feasible to me are 1 (reduce file length) 5 (track locations through edits), and 6 (categorize by read/write):
  * 1) The file length one is already partially done now that we use solution paths instead of file system paths. 
  * 5) The location tracking one is mostly independent of the implementation so we could consider it.
  * 6) The read/write categorization one is doable, but the "Reads" and "Writes" nodes will be collapsed by default and need to be manually expanded.

I'm removing the milestone completely for now to make sure this gets retriaged.

**Comment by Pilchie** [comment]
I'm fine with moving all of these to 1.1 right now, but let's keep an eye on feedback once the next build is released with the changes we've already done.

**Comment by TheGrandUser** [comment]
My suggestion would be to be able to find all references for a property's getter and setter independantly

**Comment by gafter** [comment]
@dpoeschl @Pilchie Does this issue remain useful/actionable, or should it be closed?

**Comment by DustinCampbell** [comment]
@gafter -- yes, it still remains actionable. This is a backlog item that is intentionally long-lived.

**Comment by DustinCampbell** [comment]
Here's another piece of feedback coming through Send a Smile/From in VS:

>Generics are wonderful, and I would like searching for references to be just as handy.   For example, I use Tuple in many places with many different combinations of types and I want to find all occurrences of Item2 on _only_ `Tuple<int, string>`, not on every kind of Tuple.

**Comment by dpoeschl** [comment]
Another suggestion from https://github.com/dotnet/roslyn/issues/7778

**Comment by dpoeschl** [comment]
Another suggestion from https://github.com/dotnet/roslyn/issues/7802 Change default preselection in results window

**Comment by Pilchie** [comment]
I'm actually really happy about how many of these it looks like we're going to get in 2.0, though we'll miss the Preview 4 milestone unfortunately.

**Comment by CyrusNajmabadi** [comment]
@Pilchie how should we track this now?  I think being on my plate doesn't make sense unless we're actually committing to more work items.  Is tehre a general backlog location we can put things?

**Comment by Pilchie** [comment]
Putting back in Unknown - @kuhlenh want to clean this up and list the outstanding suggestions that *aren't* covered by the new FAR window so that we can prioritize?

**Comment by CyrusNajmabadi** [comment]
Closing out.  The entire find-refs stack was rewritten.  If we want future improvements here we shoudl drive them with new issues that we can confirm apply to the new system.  Worth nothing, the following items from the original list are now closed as well:

1. Categorize References by Read/Write
2. Display known kinds of references more explicitly
3. Multiple result sets
4. The ability to view previous search results without repeating a search
