### ISSUE TITLE
CompilationWithAnalyzerOptions ctor must remove breaking change

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#9047]
Consider this commit:  https://github.com/dotnet/roslyn/commit/deeb46ecd3f215564f344f0f42bba90adff255e5

It changed the parameters on `CompilationWithAnalyzerOptions`.  This is a breaking change from update 1.  It needs to be adjusted to maintain the old constructors in addition to the new ones to maintain binary compat.

**Comment by heejaechang** [comment]
changes are both in unshipped.txt, do we still need to maintain bin compact?

**Comment by jaredpar** [comment]
@heejaechang that is an accident of timing.  Those files got updated to the correct values after we shipped but before you made this change.  Hence it only appeared to be unshipped when you made the change.

**Comment by heejaechang** [comment]
@jaredpar can you verify and close?
