### ISSUE TITLE
Does OperatorKind need more members for VB

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#9049]
This concerns `Microsoft.CodeAnalysis.Workspaces.OperatorKind`.  During API review @AnthonyDGreen pointed out this may need additional members to complete the VB experience.  He will be digging in here and recommending changes based on this analysis. 

This bug comes from our API review meeting

**Comment by AnthonyDGreen** [comment]
I believe per my other feedback to @CyrusNajmabadi we're replacing this method with specific methods for each operator. That's consistent with how we've done Binary expressions and would remove the need to add this enum at all.

**Comment by CyrusNajmabadi** [comment]
I think the question was: do you want additional methods for other special VB operators?  And, if you do, does that have to happen in 1.2 or can that wait until people ask for it?

**Comment by AnthonyDGreen** [comment]
So you're saying we still need the enum? Are there similar enums elsewhere in the generator API?

**Comment by CyrusNajmabadi** [comment]
No.  The enum has been removed and replaced with individual methods.  However, there is still the question of: are there *additionanal* methods we'd want to add for VB specific operators.  Or can we wait on that for 1.3 and later.

**Comment by AnthonyDGreen** [comment]
If the enum is gone I consider this issue closed. We can deal with any omissions in 1.3.
