### ISSUE TITLE
Rename completely breaks reference to backing fields of ReadOnly properties

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#905]
*Repro Steps:*

1. Paste in the following code into a project:

    Class C1
        Public ReadOnly Property P As String
    
        Sub M()
            _P = "asdf"
        End Sub
    End Class

2. Choose rename on P.
3. Don't actually type anything
4. Press enter

*Expected:* nothing happened
*Actual:* the _ was deleted and thus breaks the code

**Comment by dpoeschl** [comment]
@jasonmalinowski - can you verify?
