### ISSUE TITLE
Should SyntaxGenerator.OperatorDeclaration be expanded to individual members

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#9051]
`OperatorDeclaration` is a new member added in update 2 which produces `SyntaxNode` values based on the provided `OperatorKind` enum passed to the method.  During the API review this method seemed potentially out of place with the rest of the type where operations / expressions have specific generator methods.  

@AnthonyDGreen and @CyrusNajmabadi have agreed to hash out the proper design here.

**Comment by Pilchie** [comment]
We decided not to fix this due to risk.
