### ISSUE TITLE
ILSpan should not be a public type

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#9052]
API review revealed a new type that has seemingly no reason to be public: `ILSpan`.  This type doesn't appear to be used in any new APIs hence it's unclear why this was made public.  It should be made internal if there is no reason to be public.  

If public then the following concerns need to be addressed:

- `What does `MaxValue` mean for a span type?  None of the other span types have such a member and it feels out of place. 
- The constructor parameter names should be adjusted to match the corresponding properties.

**Comment by tmat** [comment]
My fault. Should be internal.
