### ISSUE TITLE
Naming of SymbolFinder.FindDerivedClassesAsync

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#9053]
Should this member be named `FindDerivedTypesAsync` instead?  If it functions an interface definitions then this seems like a more appropriate name since it can return `struct` and `interface` values. 

This issue came up during API review.

**Comment by jasonmalinowski** [comment]
@jaredpar: per the doc comments of the method:

    /// <summary> 
    /// Finds the derived classes of the given type. Implementations of an interface are not considered "derived", but can be found 
    /// with <see cref="FindImplementationsAsync"/>. 
    /// </summary> 

Let me know if that wasn't clear.

**Comment by jaredpar** [comment]
@jasonmalinowski that's perfect.  Mostly we wanted to clarify this actually meant classes here.  Thanks!

**Comment by jaredpar** [comment]
CC @DustinCampbell for visibility

**Comment by DustinCampbell** [comment]
:+1:
