### ISSUE TITLE
MemberDisplayFormat should have a default / none member

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#9055]
This enum should consider adding a `None / Default` member with the value 0 to meet the BCL enum guidelines. 

This bug comes from our API review

**Comment by tmat** [comment]
The guidelines say:

>
DO provide a value of zero on simple enums. 
Consider calling the value something like “None.” If such a value is not appropriate for this particular enum, the most common default value for the enum should be assigned the underlying value of zero.
```
public enum Compression {
    None = 0,
    GZip,
    Deflate,
}
public enum EventType {
    Error = 0,
    Warning,
    Information,
    ...
}
```

In our case ```MemberDisplayFormat.SingleLine``` is a reasonable default value, so there is no need to introduce another one.
