### ISSUE TITLE
IsCompleteSubmission should not be on SyntaxFactory

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#9057]
The `SyntaxFactory.IsCompleteSubmission` for VB is out of place.  It should be on either on `SyntaxFacts` or possibly `SyntaxTree` (and should line up with C#'s location).

**Comment by tmat** [comment]
We already shipped C# version on SyntaxFactory, so for consistency VB should have it there as well. Should be internal for U2 however.
