### ISSUE TITLE
Dev14CTP5 branch fails to build.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#906]
This is recommended as the base branch for pull requests, but it doesn't even build.

See #824

**Comment by dpoeschl** [comment]
For quicker reference, here's the failed build: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest/640/console

The [Building, Testing, and Debugging](https://github.com/dotnet/roslyn/wiki/Building-Testing-and-Debugging) wiki mentions that pull requests will only be accepted from master. @AdamSpeight2008 Is there conflicting guidance on this elsewhere?

@jaredpar Do we intend for PRs to the CTP5 branch to build & pass tests on the CI machines? I don't think we have CI machines set up with CTP5 to facilitate that. I wonder if we just need to clean up the documentation around this.

**Comment by jaredpar** [comment]
@dpoeschl 

> Do we intend for PRs to the CTP5 branch to build & pass tests on the CI machines? 

We only intend for PRs to be accepted to the master branch.  A PR to any of the release branches, except possibly the most recent, will almost certainly fail.  

> I don't think we have CI machines set up with CTP5 to facilitate that. I wonder if we just need to clean up the documentation around this.

The documentation states that PRs will only be accepted to master.  I'm open to suggestion but I'm not sure how this could be made any clearer.

**Comment by AdamSpeight2008** [comment]
@jaredpar, @dpoeschl  I think you need to reread the wiki

> * Only contributions against the master branch **or the branch that corresponds to the latest Preview release of VS 2015 will be accepted.**

**Comment by jaredpar** [comment]
@AdamSpeight2008 can you point us to that place in the WIKI?  It is in error.

**Comment by jaredpar** [comment]
Additionally could you provide the following information:

- What build of Visual Studio and the SDK are installed on your machine?
- What build errors are you seeing?  Generally a report of a build failure should be accompanied by the actual errors being output.

**Comment by AdamSpeight2008** [comment]
(WIKI location](https://github.com/dotnet/roslyn/wiki/Contributing-Code) 2 item in bullet list.
I'll get back to with the specs, as today I'm not in the same location. *(That's if I haven't deleted that VM)*

**Comment by dpoeschl** [comment]
We've updated that wiki page to remove references to the "lastest Preview release of VS 2015."

**Comment by dpoeschl** [comment]
Marking as Blocked until we know whether the build that was attempted is a supported scenario.

**Comment by jaredpar** [comment]
This branch is only intended to build on a machine with CTP5 enabled on it.  This was tested at the time the branch created and we haven't pushed any changes to it since then.   If this is indeed not building on a machine with CTP5 + the SDK installed please reopen and attach the build errors.

**Comment by AdamSpeight2008** [comment]
Note: The VM no longer accessible.
