### ISSUE TITLE
Async/await method in struct

### ISSUE THREAD

**Issue by bthomp2420** [dotnet/roslyn#9066]
The following snippet written in LinqPad illustrates potentially bad code where the generated closure within the async method is referencing/updating a copy of a struct instead of the original instance.  Obviously this is bad code, however, this is currently compiled without compiler error or warning indicating that the implied, by-ref "this" is being referenced by a closure:

```
public struct Bar
{
       int _value;
       
       public void Increment()
       {
              Interlocked.Increment(ref _value);
       }
       
       public async Task IncrementAsync(Task pendingTask)
       {
              await pendingTask;
              Interlocked.Increment(ref _value);
       }
       
       public int Value { get { return _value; } }
}

public class Foo
{
       Bar _state = default(Bar);

       public async Task UpdateAsync()
       {
              _state.Increment();
              String.Format("After synchronous increment (expected value of 1): {0}", _state.Value).Dump();
              
              var delayTask = Task.Delay(1000);
              await _state.IncrementAsync(delayTask);
              String.Format("After asynchronous increment (expected value of 2): {0}", _state.Value).Dump();
       }
}

void Main()
{
       var foo = new Foo();
       var task = foo.UpdateAsync();
       task.Wait();
}
```

**Comment by svick** [comment]
Interesting, when I try to achieve similar effect using a closure, I get CS1673:

> Anonymous methods, lambda expressions, and query expressions inside structs cannot access instance members of 'this'. Consider copying 'this' to a local variable outside the anonymous method, lambda expression or query expression and using the local instead.

But when I use iterator, I get the same result as you with an `async` method: The modification applies to a copy of the struct.

My *guess* is that the difference exists because with lambdas, you can easily create a copy of `this` in the enclosing function and access that. But with iterators and `async` methods, having similar restriction would make them nigh useless.

My code:

```c#
// CS1673
public void IncrementLambda()
{
	Action a = () => _value++;
	a();
}

// compiles fine
public IEnumerable<int> IncrementIterator()
{
	yield return 0;
	_value++;
}
```

**Comment by bthomp2420** [comment]
You should be able to explicitly capture "this" into a variable that can be referenced by a closure (or continuation/iteration).  Semantically, those are effectively the same and capturing a copy of this should be required to be an explicit operation as follows:

```
public IEnumerable<int> IncrementIterator()
{
    var @this = this;
    yield return 0;
    @this._value++;
}
```

**Comment by svick** [comment]
I think that would be confusing, though possibly less confusing than the current behavior (especially since an error message could explain it, just like it does with lambdas).

In any case, I doubt such a breaking change would be considered.

**Comment by bthomp2420** [comment]
Again, a compiler warning here would probably be sufficient to indicate the hidden behavior.  This may also be something that I request from the JetBrains R# people as well as we use their tools quite a lot.

**Comment by jaredpar** [comment]
Unfortunately this behavior is by design.  I agree it can be confusing that `this` is captured by value in structs.  However it was a deliberate design choice at the time `async` was introduced.  Changing this behavior would be a large back compat breaking change at this point.
