### ISSUE TITLE
Test pattern matching against IDE features

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#9068]
### Testing tags

:white_check_mark: = Tested & Approved (possibly with linked bugs)
:x: = Merge blocking
:construction: = Non-blocking bugs
:ok: = Issue has been fixed
:free: = No expected impact
:question: = Open question
:grey_question: = Answered question

<a name="testfootnote1"><sup>1</sup></a> Feature updated by compiler team, with appropriate unit tests.
<a name="testfootnote2"><sup>2</sup></a> Feature requires more complete testing by IDE team. (?)
## <a name="mergesignoff">Internal Dogfooding Requirements (Merge Signoff)</a>

Critical IDE features in the areas of **Typing**, **Navigating**, and **Viewing** must function as expected. Any non-trivial issues in these areas blocking language feature merging.
_All feature descriptions and testing suggestions are merely examples. Each language feature should be carefully considered independently against each IDE feature to find interesting intersections_

| Category | Feature/Description | C# Signoff/Notes | VB Signoff/Notes |
| --- | --- | --- | --- |
| **Enable/Disable** | **Feature Flag** <br />Completely enables/disables the feature in the compiler & IDE |  |  |
| **Typing** | **General Typing**<br />\- Type and paste new constructs<br />\- Nothing interferes with verbatim typing | Pasting of complex patterns is poor: https://github.com/dotnet/roslyn/issues/9069<br>Typing of complex patterns is poor https://github.com/dotnet/roslyn/issues/9071 |  |
|  | **Completion**<br />\- Typing new keyword/construct names<br />\- Dotting off of new constructs | Pattern variable not in catch block: https://github.com/dotnet/roslyn/issues/9074<br>No completion at start of pattern case block: https://github.com/dotnet/roslyn/issues/9076<br>Pattern variable in negated expression not in else clause: https://github.com/dotnet/roslyn/issues/9082<br> 'let' not suggested: https://github.com/dotnet/roslyn/issues/9083<br>No completion for the type in a 'let' declaration: https://github.com/dotnet/roslyn/issues/9084<br>'let' declaration keywords not offered: https://github.com/dotnet/roslyn/issues/9085 <br>'throw' not offered in expression contexts: https://github.com/dotnet/roslyn/issues/9099 |  |
|  | **Formatting** <br />\- Spacing in and around new constructs<br />\- Spacing options<br />\- Format Document command | Spacing around patterns in switches: https://github.com/dotnet/roslyn/issues/9075 |  |
|  | **Automatic Brace Completion** (_C# only_) <br />\- Auto-insert close brace<br />\- Shift+Enter commit of pending brace completion |  |  |
|  | **Indentation** <br />\- Typing `Enter` in an unfinished statement indents the next line | Indentation not working in complex patterns: https://github.com/dotnet/roslyn/issues/9078<br>Indentation not working with cases clauses with patterns in switch statements: https://github.com/dotnet/roslyn/issues/9097<br>Or match/case expressions: https://github.com/dotnet/roslyn/issues/9098 |  |
| **Navigating** | **Go To Definition** <br />\- F12 from callsites to definition | Does not work on complex pattern members: https://github.com/dotnet/roslyn/issues/9072 |  |
|  | **Go To Implementation** <br />\- Jump from virtual members to their implementations<br />\- Jump from inheritable types to their implementations | :free: (i think) |  |
|  | **Find All References** <br />\- Lists references to a symbol in "Find Symbol Results" window<br />\- Shows results in hierarchy grouped by definition | FAR results missing in complex patterns: https://github.com/dotnet/roslyn/issues/9073<br>Not working for constructors and positional patterns: https://github.com/dotnet/roslyn/issues/9107 |  |
| **Viewing** | **Colorization** <br />\- Keywords, literals, and identifiers colored appropriately in code |  |  |
|  | **Error Squiggles** <br />\- Squiggles appear as expected on reasonable spans |  |  |
## <a name="featuresignoff">IDE Features (Feature Signoff)</a>

For the remaining set of IDE features, only crashes and asserts are considered blocking. However, _all_ issues discovered must be filed and linked here.
_All feature descriptions and testing suggestions are merely examples. Each language feature should be carefully considered independently against each IDE feature to find interesting intersections_
### Code Transformations

| Category | Feature/Description | C# Signoff/Notes | VB Signoff/Notes |
| --- | --- | --- | --- |
| **Refactoring with UI** | **Inline Rename (with UI)**<br />\- Dashboard shows correct information<br />\- Highlighted spans are updated appropriately<br />\- Rename operation updates the correct set of symbols | Rename does not update all references: https://github.com/dotnet/roslyn/issues/9079<br>Rename cannot be triggered from complex parameter: https://github.com/dotnet/roslyn/issues/9080<br>Rename cannot be triggered from 'let' declaration: https://github.com/dotnet/roslyn/issues/9086<br>Unresolvable conflicts when renaming a 'let' variable reference: https://github.com/dotnet/roslyn/issues/9088 |  |
|  | **Change Signature (with UI)**<br />\- Updates all direct & cascaded definitions/callsites<br />\- Shows appropriate signature & parameter previews in UI | Changing constructor does not fix usage in pattern: https://github.com/dotnet/roslyn/issues/9100 |  |
|  | **Extract Interface (with UI)**<br />\- Generated Interface has expected shape<br />\- UI shows appropriate method previews | :free: This is a statement/expression level feature |  |
|  | **Generate Type (with UI)**<br />\- Dialog gives all valid options<br /> | Not offered for complex pattern type: https://github.com/dotnet/roslyn/issues/9089 |  |
| **Refactorings** | **Rename Tracking**<br />\- Tracking span tracks & dismisses as expected |  |  |
|  | **Extract Method**<br />\- Extracted method has the expected signature<br />\- All arguments/return values handled correctly<br />\- Extracted code block is reasonable | Doesn't work properly in match/case expression: https://github.com/dotnet/roslyn/issues/9106 and https://github.com/dotnet/roslyn/issues/9105 |  |
|  | **Introduce Variable**<br />\- Introduced variable has the expected signature and initializer expression<br />\- "Introduce for All" correctly finds dupes |  |  |
|  | **Inline Temporary Variable**<br />\- Inlined values are appropriately expanded/reduced |  |  |
|  | **Organize Usings**<br />\- Honors "Place 'System' namespace first" option |  |  |
|  | **Convert "Get*" Methods to Properties**<br />_Add Description_ |  |  |
|  | **Encapsulate Field**<br />_Add Description_ |  |  |
| **Fixes** | **Add Using**<br />\- Triggers on appropriate constructs |  |  |
|  | **Generate Local**<br />_Add Description_ |  |  |
|  | **Generate Field**<br />_Add Description_ | Not offered in complex pattern member: https://github.com/dotnet/roslyn/issues/9090 |  |
|  | **Generate Method/Constructor**<br />\- Generated method has the expected signature and accessibility | Not offered with positional pattern: https://github.com/dotnet/roslyn/issues/9108 |  |
|  | **Generate Constructor from members**<br />\- Select fields/properties to generate a constructor accepting corresponding arguments<br />\- Generated constructor has the expected signature and accessibility | :free: (i think) |  |
|  | **Implement Interface**<br />\- Only missing methods added<br />\- All added methods have the expected signature and accessibility | :free: (i think) |  |
|  | **Implement IDisposable**<br />_Add Description_ | :free: (i think) |  |
|  | **Implement Abstract Class**<br />_Add Description_ | :free: (i think) |  |
| **Code Gen** | **Snippets**<br />_Add Description_ |  |  |
|  | **Event Hookup on Tab** (_C# only_)<br />\- Type "+=" after an event name and QuickInfo shows<br />\- Invoking should pick good name & launch Inline Rename |  | N/A |
|  | **End Construct Generation** (_VB only_)<br />_Add Description_ | N/A |  |
|  | **Automatic End Construct Update** (_VB only_)<br />_Add Description_ | N/A |  |
### IDE Features

| Feature/Description | C# Signoff/Notes | VB Signoff/Notes |
| --- | --- | --- |
| **Signature Help**<br />\- Overloads shown with appropriate, colorized signature | Sig help not offered on positional patterns: https://github.com/dotnet/roslyn/issues/9101 |  |
| **Quick Info**<br />\- Hover on identifiers<br />\- On completion list items | Not showing on 'let' declarations: https://github.com/dotnet/roslyn/issues/9091<br>Not showing on pattern variable: https://github.com/dotnet/roslyn/issues/9092 |  |
| **Outlining**<br />_Add Description_ | :question: Should we have outlining for complex expressions?  They can be large (so yes?).  But we don't for other constructs like large object initializers |  |
| **Brace Matching** (_C# only_)<br />_Add Description_ |  | N/A |
| **Highlight References**<br />_Add Description_ | Not working on pattern variables: https://github.com/dotnet/roslyn/issues/9110 |  |
| **Peek**<br />_Add Description_ | Not working on pattern variables: https://github.com/dotnet/roslyn/issues/9109 |  |
| **Navigation Bars**<br />_Add Description_ | :free: This is a statement/expression level feature |  |
| **Metadata As Source**<br />_Add Description_ | :free: This is a statement/expression level feature |  |
| **Navigate To**<br />_Add Description_ |  |  |
| **Go to Next/Previous Method**<br />_Add Description_ | :free: This is a statement/expression level feature |  |
| **Solution Explorer Pivots**<br />_Add Description_ |  |  |
| **Call Hierarchy**<br />_Add Description_ |  |  |
| **Code Lens**<br />_Add Description_ |  |  |
| **Project System**<br />_Add Description_ | :free: This is a statement/expression level feature |  |
| **Debugger IntelliSense**<br />_Add Description_ |  |  |
| **Breakpoint spans**<br />_Add Description_ | Not implemented at all: https://github.com/dotnet/roslyn/issues/9095 |  |
| **Code Model / Class Designer**<br />_Add Description_ | :free: This is a statement/expression level feature |  |
| **Object Browser / Class View**<br />_Add Description_ | :free: This is a statement/expression level feature |  |
| **Lightbulb**<br />_Add Description_ |  |  |
| **Line Separators**<br />_Add Description_ | :free: This is a statement/expression level feature |  |
| **Options**<br />_Add Description_ |  |  |
### Project System & External Integration

(Any changes to the runtime will require much more testing in this category)
_All feature descriptions and testing suggestions are merely examples. Each language feature should be carefully considered independently against each IDE feature to find interesting intersections_

| Category | Integration | Signoff/Notes |
| --- | --- | --- |
| **Projection Buffers** | **Razor**<br />\- Verify expression and block contexts<br />\- Test on projection boundaries<br /> - Emphasis on rename and formatting |  |
|  | **Venus**<br />\- Verify expression and block contexts<br />\- Test on projection boundaries<br /> - Emphasis on rename and formatting |  |
| **Designers** | **WPF**<br />\- Event generation from designer to code<br />\- Designer consumption of new types of members<br />\- Cross language features (GTD, FAR) |  |
|  | **WinForms**<br />_Add Description_ |  |
| **Project System Interactions** | **.NET Core "Console Application (Package)"**<br />_Add Description_ |  |
|  | **Linked Files (all flavors)**<br />_Add Description_ |  |
## Interaction with other new language features

Verify IDE handling of the new language feature in conjunction with other new/unreleased language features

| Feature | C# Signoff/Notes | VB Signoff/Notes |
| --- | --- | --- |
| **<New Language Feature 1>** |  |  |
| **<New Language Feature 2>** |  |  |
## <a name="featuresuggestions">New Feature Suggestions</a>

What refactorings, fixes, code transformations, or other in-editor experiences would enhance this language feature?

| Feature Name | Description |
| --- | --- |
| ? | ? |

**Comment by gafter** [comment]
Not sure why @jaredpar assigned this to me; @CyrusNajmabadi is currently working on this.

**Comment by Pilchie** [comment]
@CyrusNajmabadi did you finish with this?
