### ISSUE TITLE
MetadataReferences are not listed (System.Object does not exist and other similar errors instead)

### ISSUE THREAD

**Issue by dee-see** [dotnet/roslyn#9070]
I'm trying to list the references of the projects in a solution. Strangely, `MetadataReferences` is empty for all C# projects yet it appears to work on VB.NET projects.

I created my projects with defaults templates in VS 2015.1.

Running this code on the C# project gives me messages about System.Object that does not exist.
```
var doc = project.Documents.First();
var model = doc.GetSemanticModelAsync().Result;
var diag = model.GetDiagnostics();
```

Issue #5389 looked similar but it doesn't appear to be what's happening here.

Here's my repro code
[RoslynListsOnlyVBMetadataReferences.zip](https://github.com/dotnet/roslyn/files/143359/RoslynListsOnlyVBMetadataReferences.zip)

**Comment by dee-see** [comment]
Update: So I've tried running the same code on another machine and it worked as expected!

Any idea of what could cause this? Any debug trace I could activate on the machine where it's not working?

**Comment by dee-see** [comment]
Interestingly, I came back to this today and it works on my computer now. I still have a few machines with the problem. I'm trying to figure out if there is a Windows/VS update that has an impact on this...

**Comment by dee-see** [comment]
So I figured out the issue. We're using HP machines and during the setup they add a "Platform" environment variable which appears to be picked up by Roslyn as the compilation Platform and the value is invalid so compilation fails.

Solution was to delete that value. I'm going to leave the issue open and let you decide if this needs to be fixed in Roslyn or not.

**Comment by Pilchie** [comment]
*sigh*.  It can't be fixed in Roslyn.  MSBuild inherits environment variables by default.  You would have hit the same issue if you tried to build from the command prompt without explicitly specifying the platform.

See this thread from 2010 for example: https://social.msdn.microsoft.com/Forums/vstudio/en-US/3c4e9c3f-2bf2-436e-80de-e000a7dda8bd/msbuild-and-its-use-of-the-platform-environment-variable?forum=msbuild
