### ISSUE TITLE
Poor typing of complex patterns due to brace completion/formatting.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#9071]
If i try to type:

```if (expr is Plus {```

Then i get: the following code:

```
if (expr is Plus
{
})
```

While brace completion is desirable here, either it or formatting screw things up by making the curlies go on separate lines.  For patterns we should not interfere with how the user was typing them.

**Comment by DustinCampbell** [comment]
We should definitely complete braces here, but it should stay on the same line like string interpolations.
