### ISSUE TITLE
Replace `VerifyDiagnostics` helper with `AssertTheseDiagnostics` in VB operation test

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#9077]
`AssertTheseDiagnostics` is the preferred way for VB tests. As an example, we should replace

``` vb
comp.VerifyDiagnostics(Diagnostic(ERRID.ERR_InaccessibleSymbol2, "C.S").WithArguments("C.S", "Protected").WithLocation(7, 15))
```

with

``` vb
comp.AssertTheseDiagnostics(<errors><![CDATA[
BC30389: 'C.S' is not accessible in this context because it is 'Protected'.
        M(New C.S())
              ~~~
]]></errors>)
```

**Comment by tmat** [comment]
:-1: Corresponding C# and VB tests should be the same. Rewriting a test to a different style of error checking is waste of time.

**Comment by genlu** [comment]
@tmat I agree with you in general. But @AlekseyTs suggests `AssertTheseDiagnostics` is more of a convention for VB tests, in which case I believe it trumps consistency (between languages).

**Comment by AlekseyTs** [comment]
Yes, we (VB people) would like to see diagnostics in a human readable form, with squiggles and such.

**Comment by tmat** [comment]
I disagree it trumps consistency. Consistency is above anything else. I agree that tests that only appear in VB suite should use AssertTheseDiagnostics. But tests that 1:1 match C# tests should use the same helpers. I'd be fine with adding AssertTheseDiagnostics to C# for tests that were written in VB first and translated to C#.

**Comment by tmat** [comment]
I should perhaps clarify - yes, the diagnostics will be specific to each language so there is some work needed when porting tests from one language to another. However such porting should be as streamlined as possible - the same test helpers available on all objects, etc.
