### ISSUE TITLE
Pattern variable not in scope in else branch when expression is negated.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#9082]
Not sure what the spec says about this.  However, if you have:

```c#
        void M4()
        {
            object o = null;
            if (!(o is X x2))
            {
            }
            else
            {
                x2    // expectation is that x2 is available here.
            }
        }
```

x2 seems like it should be in scope there.  After all, we only get into the top branch if 'o' was *not* an X.  So we get into the 'else' when 'o' is an X and thus can be used through 'x2'.

However, 'x2' is not in the completion list there.

**Comment by HaloFour** [comment]
Per #206 and #8817 that wouldn't be the case.  The reasoning for this was to allow the identifier to be reused in a pattern in the `else` clause:

**Comment by gafter** [comment]
This is by design.
