### ISSUE TITLE
Rename of a 'let' variable reference produce 'unresolvable conflicts' at every location.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#9088]
![image](https://cloud.githubusercontent.com/assets/4564579/13267349/b3abd398-da31-11e5-9518-1cc5ed39b2fb.png)

**Comment by gafter** [comment]
let statements are out of scope for the punch-through for build.

**Comment by Delabo** [comment]
Is this something I could assist with?

**Comment by gafter** [comment]
Let statements are no longer part of the pattern-matching design.
