### ISSUE TITLE
Generate field/property not offered for complex pattern member.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#9090]
``` c#
        void M2()
        {
            object o = null;
            if (o is Blah { X: int i })
            {
            }
        }

        class Blah
        {
        }
```

No code action to generate the member X inside Blah.

**Comment by gafter** [comment]
@CyrusNajmabadi I could use your help with this, please.

**Comment by CyrusNajmabadi** [comment]
Recursive patterns were cut.  So closing this out.

**Comment by gafter** [comment]
@CyrusNajmabadi This is labeled Milestone 3.0, when we expect to do it.

**Comment by gafter** [comment]
Hey @CyrusNajmabadi, would love your help on this. The appropriate branch is `features/recursive-patterns`.

**Comment by CyrusNajmabadi** [comment]
Hey @gafter .  Would be happy to help out.  By help were you asking if i could implement htis (if so, i woudl be willing to do that if i can make the time in the evinings).  or did you mean you wanted to know how to make the IDE changes yourself?  

in either case, can you give a handful of examples of what the language feature allows for now?

**Comment by CyrusNajmabadi** [comment]
Note the original PR over here is likely still very suitable for this problem space (modulo adapting to whatever new syntax you've settled on): https://github.com/dotnet/roslyn/pull/10873

I'd be happy to try to pull it forward to whatever you have.  But it would be good to get a handful of representative cases that i could try out to make sure this is working properly!

**Comment by CyrusNajmabadi** [comment]
Ok.  I've moved my PR forward and i've made it support the one case i knwo about.

**Comment by jcouv** [comment]
@CyrusNajmabadi I think we can now close this issue (your fix in PR https://github.com/dotnet/roslyn/pull/26355 was merged, thanks!).
I'll go ahead and close. Let me know if incorrect
