### ISSUE TITLE
QuickInfo on pattern variable shows nothing.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#9092]
```c#
            Class1 c1; 
            if (v is Class1 c2)
            {
            }
```

QuickInfo shown on 'c1' but not on 'c2'.

**Comment by gafter** [comment]
By "QuickInfo" do you mean the popup widow when the mouse cursor hovers over the name?

**Comment by CyrusNajmabadi** [comment]
Yes.

**Comment by gafter** [comment]
OK, this looks fixed today. @CyrusNajmabadi please verify.
