### ISSUE TITLE
Update artifact filters to internal and ETA jobs

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#9093]
We updated https://github.com/dotnet/roslyn/blob/master/netci.groovy to only include specific files such as logs, dumps and other things that are used for debugging purposes. 
However, this also needs to be applied to:
- [x] The open ETA job (make note ETA is [not yet auto-generated](https://github.com/dotnet/roslyn/issues/8977))
- [ ] The open VSI jobs (make note VSI is [not yet auto-generated](https://github.com/dotnet/roslyn/issues/8977))
- [ ] Roslyn internal jobs.
- [ ] We're also accidently including the NuGet ZIP file in the artifacts on Linux/Mac, because in some cases we want to capture a .zip for determinism jobs.

**Comment by davkean** [comment]
@CyrusNajmabadi Can you pick this up?

**Comment by davkean** [comment]
I think our regex is still broken:

1) As mentioned above, it's including the NuGet ZIP file (but we don't want to exclude all ZIP files)
2) It's including all the doc comment XML files (but we don't want to exclude all XML files, for example, those under xUnitResults.

**Comment by CyrusNajmabadi** [comment]
PR for this here: https://github.com/dotnet/roslyn-internal/pull/636

**Comment by tmat** [comment]
The archiving is still broken
https://github.com/dotnet/roslyn/issues/11431
