### ISSUE TITLE
Determine our "exchange type" dependencies on MPF

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#9096]
We need to do analysis on our type dependencies on MPF 14.0 (Microsoft.VisualStudio.Shell.14.0.dll) and ensure that they do not bleed into public APIs, or get up-casted elsewhere in Visual Studio.

MPF is side-by-sided every version of Visual Studio, so any type we have used in v14 version will not be seen as an equivalent type as the v15 version, which will cause upstream casts (such as in Solution Explorer) to fail and other issues.

We need to identity every type that is in this situation and tell the shell team about. @ManishJayaswal has the details.

The easiest way to do this, is use the FxDepends tool from the .NET team to dump all the dependencies of the Roslyn and other repro code that we own.

**Comment by heejaechang** [comment]
this type http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/TableDataSource/Suppression/SuppressionStateColumnFilterDefinition.cs,864e6572d6838d17 require http://index/#Microsoft.VisualStudio.Shell.14.0/TableControl/Internal/EntryFilterDefinition.cs,1ea91d02fdc28ff9 as exchange type.

**Comment by davkean** [comment]
Have we made any progress on this front?

**Comment by AArnott** [comment]
I sure hope so, because @ilyabiryukov is wrapping up his work to solve the problem on our side.

**Comment by davkean** [comment]
Clearly you need to leave room for bugs?

**Comment by ManishJayaswal** [comment]
I believe @ilyabiryukov was working on moving the types we know were causing issues into immutable assembly. This work is to identify all dependencies so that we can evaluate if more types need to be moved or we need to work around the fact that they can not be moved.

**Comment by AArnott** [comment]
Well if you have any more types you need moved please let us know ASAP.

**Comment by davkean** [comment]
Where did we land with this @ManishJayaswal?

**Comment by davkean** [comment]
Is this done?

**Comment by jasonmalinowski** [comment]
We don't think this bug is actionable anymore.
