### ISSUE TITLE
Indentation on colon not working with case clauses in a match/case expression.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#9098]
In a normal switch we align the cases when you type 'colon' in a case clause.  This doesn't with in a case clause in match/case expressions

**Comment by gafter** [comment]
The LDM has no decided on a syntax for the switch expression.

**Comment by gafter** [comment]
This bug does not make sense in the context of the current syntax.

**Comment by CyrusNajmabadi** [comment]
@gafter That's fine with me. HOwever, as part of the "match expressoin" work, can we ensure (and test) that formatting/indentation does do the right thing?  i.e. when you enter, the 'cases' (or whatever we call them) should be aligned.
