### ISSUE TITLE
'throw' not offered in expression contexts.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#9099]
``` c#
        void M(int? a)
        {
            var v = a ?? throw new Exception();   // throw not offered here.
        }
```

Also, more importantly, it's not offered in case clauses in a match/case expression.

**Comment by gafter** [comment]
Throw expressions are not in scope for the build demo.

**Comment by gafter** [comment]
Moving to RC as throw expressions will not be in preview 5.

**Comment by gafter** [comment]
Per #15405, `throw` should, for example, be offered after `=>`
