### ISSUE TITLE
Update compiler error message for expression bodied members

### ISSUE THREAD

**Issue by controlflow** [dotnet/roslyn#91]
```c#
partial class FooBar {
  partial void M() => M();
}

partial class FooBar {
  async partial void M();
}
```
Produces compiler error:

> error CS1994: The 'async' modifier can only be used in methods that have a statement body.

Requirement of "statement body" is no longer valid in C# 6.0, since expression body can be used for `async` methods as well.

**Comment by pdelvo** [comment]
What should the new message be like?

What about 
```The 'async' modifier can only be used in methods that have a statement or expression body.```

Could changing the error message be a breaking change?
