### ISSUE TITLE
Dynamically turn on and off esent

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#910]
esent is there for scalibility. but small solution doesn't actually need esent and we could hold all information in memory without worrying too much about VM.

create some mechanism to track those and dynamically turn on or off esent.

**Comment by tmeschter** [comment]
What is the advantage to turning it off?

**Comment by heejaechang** [comment]
Esent has its own cache, which is about 40-50MB native memory. If solution size is not big enough, just caching in memory will be smaller than the cache.


-          heejae
