### ISSUE TITLE
Reorder parameters does not fix up use sites in patterns.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#9100]
``` c#
    public class Point
    {
        public int X;
        public int Y;

        public Point(int x, int y)
        {
            X = x;
            Y = y;
        }
        void M()
        {
            object o = null;
            if (o is Point(0, 1))
            {

            }
        }
    }
```

If you reorder parameters on Point's constructor, then the pattern use site should be updated as well.

Note: when we add support for doing this with a "GetValues" method (or whatever mechanism we decide on), we'll have to support this relationship as well.

**Comment by gafter** [comment]
Positional patterns are out of scope for the build demo.

**Comment by gafter** [comment]
Positional patterns will not be inferred from constructors.
