### ISSUE TITLE
Proposal:  Property Setters as Methods

### ISSUE THREAD

**Issue by HaloFour** [dotnet/roslyn#9103]
This is a total spaghetti proposal.  :spaghetti: 

I've seen a number of proposals around fluent APIs and how the language should be modified to extend initialization or reuse the target object, often with either messy grammar results or features that have been intentionally declined from the language for years.

What if the C# compiler would permit using property setters on arbitrary types as if they were methods that accepted the proposed value as a parameter and returned the parent instance?

```cs
public class Foo {
    public string Bar { get; set; }
    public int Baz { get; set; }

    public static Foo MakeAFoo() {
        return new Foo();
    }
}

var result = Foo.MakeAFoo()
    .Bar("Hello")
    .Baz(1234)
    .ToString();

// equivalent to
Foo $tmp = Foo.MakeAFoo();
$tmp.Bar = "Hello";
$tmp.Baz = 1234;
string result = $tmp.ToString();
```

It might get a little ugly with indexers or events, though.

**Comment by alrz** [comment]
`Imaginary compiler error - Baz takes an int`

Anyway, this can be an alternative to #133, however, it dictates fluent API style. Not to mention that this is something towards easing mutation which isn't considered as a theme for now, I believe.

**Comment by HaloFour** [comment]
@alrz Oops, I'll fix that.  Yes, #133 is one of the various proposals that all fit under this theme.

**Comment by DerpMcDerp** [comment]
Another problem with this proposal is that properties can return delegates. If your example had been `public Func<string, Foo> Bar { get; set; }`, the call would have been ambiguous.

Also, `Foo` already has setter methods (i.e. `set_Bar` and `set_Baz`), C# just doesn't expose them for some reason. Your proposal would be much simpler if it was just to have C# remove this restriction.

**Comment by HaloFour** [comment]
@DerpMcDerp 

> Another problem with this proposal is that properties can return delegates.

This proposal deals strictly with the setter accessors, and they return `void`, so the type of the property would not be a concern.

**Comment by svick** [comment]
@HaloFour I think that @DerpMcDerp's point was that when you write `foo.Bar("Hello")`, then it's ambiguous whether you're getting `Bar` and then invoking the returned delegate or whether you're calling the setter.

**Comment by HaloFour** [comment]
@svick Ah yes, that is a good point.  Pretty much shuts down this proposal.  Oh well, it was just spaghetti against the wall.

**Comment by manixrock** [comment]
@DerpMcDerp the way method cascading is usually implemented, it's not limited to setters, and uses the usual operators. So the example would be more like this:

```C#
var result = Foo.MakeAFoo()
    ..Bar = "Hello"
    ..Baz = 1234
    .ToString(); // the last one doesn't use ".." as we want the result returned into result
```

**Comment by HaloFour** [comment]
@manixrock 

C# isn't a whitespace sensitive language which makes that syntax quite ambiguous.

```cs
var result = Foo.MakeAFoo()..Bar="Hello"..Baz=1234.ToString();
```

**Comment by manixrock** [comment]
@HaloFour C# isn't really whitespace insensitive. For example `1234.ToString()` is a valid expression, while `1234 .ToString()` is not (notice the space before the dot).

The `..` operator should not be nestable so there's only even one level of it, so any subsequent usages of `..` will apply to the same expression as the previous one, eliminating any ambiguity.

So this:

```C#
var result = Foo.MakeAFoo() ..Bar="Hello" ..Baz=1234 .ToString();
```
is equivalent to
```C#
var foo = Foo.MakeAFoo();
foo.Bar="Hello";
foo.Baz=1234;
var result = foo.ToString();
```

While this:

```C#
var result = Foo.MakeAFoo() ..Bar="Hello" ..Baz=1234.ToString();
```
is equivalent to
```C#
var foo = Foo.MakeAFoo();
foo.Bar="Hello";
foo.Baz=1234.ToString();
var result = foo;
```

You usage is equivalent to the second case above.
