### ISSUE TITLE
Can't extract method on case expression in match/case clause.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#9105]
``` c#
 p match (
            case Student s when s.Gpa > 3.5 :
                $"Honor Student { s.Name } ({ s.Gpa })")
```

Trying to extract out the string literal extracts out the entire match/case expression into a new method.

**Comment by gafter** [comment]
The match expression is not in scope for the current punch-through.

**Comment by CyrusNajmabadi** [comment]
This works fine now.  Closing out:

![image](https://user-images.githubusercontent.com/4564579/198721154-4b344796-c8d5-4a67-827f-1c0f74ff37ae.png)
