### ISSUE TITLE
[Pdb] Methods without sequence points should not emit any debug information

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#9111]
Consider unittest `PDBExternalSourceDirectiveTests.TwoMethodsOnlyOneWithMapping`. 
The PDBs (both native and portable) include debug information for `C1.FooInvisible`, which is a method with only hidden sequence points, but shouldn't.

This is an extension of the fix for #4370. That fix avoids emitting sequence points for a method if they are all hidden.

Note that the portable PDB reader filters such methods when reading out, which masks the problem. See `SymReader.GetMethodByVersion`.
Assigning to tmat per our discussion.

**Comment by ManishJayaswal** [comment]
@tmat can this be moved to 1.1 since PDB reader works around this issue for now?

**Comment by tmat** [comment]
Fixed.
