### ISSUE TITLE
EnC: VS crashes when editing an iterator in a project that targets FX 4.0

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#9119]
```IteratorStateMachineAttribute``` is expected to be emitted by the EnC infrastructure but the attribute is not present in the FX 4.0 mscorlib.

Internal Watson bug 179993.

**Comment by ManishJayaswal** [comment]
@tmat Can we close this issue now?

**Comment by tmat** [comment]
Fixed by https://github.com/dotnet/roslyn/commit/afec3b7f5e94cfc08579f56da39cb46c5ac3a8ac
