### ISSUE TITLE
Remove all Assembly load from the compilers

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#912]
Currently the analyzers use specialized assembly load logic (AnalyzerFileReference) for certain assembly references. This is not compatible with CoreCLR and needs to be removed.

**Comment by srivatsn** [comment]
We need to understand how analyzers would be loaded in coreclr.

**Comment by jaredpar** [comment]
PR #1532 resolves the majority of the issue by moving the loading code out of the core libraries and into the hosts.  The loading code will need to stay in the hosts as is until we make the move to CoreCLR where it can be replaced with the proper library call.  That will be a fairly simple move though, in all but one case it's just changing the API being called.

**Comment by jaredpar** [comment]
This work is now completed with all of @tmeschter recent changes.
