### ISSUE TITLE
Incorrect NullReferenceException

### ISSUE THREAD

**Issue by pavel-zhur** [dotnet/roslyn#9131]
The following code throws a NullReferenceException in a line where it cannot happen:

```
using System;
using System.Collections.Generic;

class Program
{
    private static Dictionary<int, Model> _dictionary = new Dictionary<int, Model> { { 3, new Model { A = 5 } } };

    private static void Main(string[] args)
    {
        Model model1 = null;
        switch (model1?.A)
        {
            case null:
                var model2 = _dictionary[3]; // NullReferenceException here
                Func<Model> f = () => model2;
                break;
        }
    }
}

class Model 
{
    public int A { get; set; }
}
```

I'm using Windows 7 Professional N SP1
.Net Framework 4.5.2 Console application
System.dll runtime version is v4.0.30319

**Comment by leppie** [comment]
Good catch!

Seems like a branching issue:
```
    L_0021: call instance bool [mscorlib]System.Nullable`1<int32>::get_HasValue()
    L_0026: brfalse.s L_003a
    L_0028: newobj instance void Program/<>c__DisplayClass1_0::.ctor()
```

**Comment by mburbea** [comment]
An even more minimal repro:
```csharp
class Program
{
    private static void Main(string[] args)
    {
        switch (new int?())
        {
            case null:
                int s = 0; // null ref exception here
                System.Func<int> func = () => s;
                break;
        }
    }
}
```
It appears the issue happens when you capture a local variable declared inside the switch statement on a `Nullable<T>` for the null case. The exception line makes even less sense here. You can also get it to happen with something like `object o=new object()` as well.

**Comment by leppie** [comment]
This is a scoping issue, the following works fine (and is a workaround for now):
```
static void Main()
{
    switch (new int?())
    {
        default:
        {
            var i = 42;
            Func<int> f = () => i;
            break;
        }
    }
}
```

**Comment by leppie** [comment]
Also seems to emit a whole lot of extra 'nonsense' for `switch` on nullable.

http://tryroslyn.azurewebsites.net/#f:r/K4Zwlgdg5gBAygTxAFwKYFsDcAoADsAIwBswBjGUogQxBBgGEYBvbFK5MmANwHswATGAFkqkABQBKbCxiyYIAO5hkpABYwxEVApiRkAfklS5zbCZP9UAMyrAiyAFxnzsmS/NcqAJ10wAvDAALABMOO7mAGLAEKQAPHoAfDBW/hoS/klgYeFyBF6oVADW2S4Avs6y5aWlQAA=

**Comment by leppie** [comment]
Managed to get the smallest difference.

`switch((int?)null)` fails
`switch((int?)0)` works

**Comment by leppie** [comment]
Looking at the IL:
```
IL_0000: ldloca.s 0
IL_0002: initobj valuetype [mscorlib]System.Nullable`1<int32>
IL_0008: ldloca.s 0
IL_000a: call instance bool valuetype [mscorlib]System.Nullable`1<int32>::get_HasValue()
IL_000f: brfalse.s IL_001f
IL_0011: newobj instance void C/'<>c__DisplayClass0_0'::.ctor()
IL_0016: stloc.1
IL_0017: ldloca.s 0
IL_0019: call instance !0 valuetype [mscorlib]System.Nullable`1<int32>::GetValueOrDefault()
IL_001e: pop
IL_001f: ldloc.1
IL_0020: ldc.i4.s 42
IL_0022: stfld int32 C/'<>c__DisplayClass0_0'::i
IL_0027: ret
```
`IL_0011` and `IL_0016` is in the wrong place. Should either be at `IL_001f` or at the start.

**Comment by jaredpar** [comment]
@cston can you take a look at this?  We fixed a couple of bugs in this area during update 2.
