### ISSUE TITLE
Listening to rename events in Code editor

### ISSUE THREAD

**Issue by Mylan719** [dotnet/roslyn#9135]
Hi,
I am writing visual studio 2015 extension for a framework. Basic idea is that we have viewmodel in C# that is bound to Html martkup. For example:
**code:**
```cs
public class MyViewModel {
     public string MyProperty { get; set; }
}  
```
markup:
```html
@viewmodel MyViewModel 
<div>
{{value: MyProperty}}
</div>
```
What I need to do is I need to be able to be notified when MyViewModel or MyProperty gets renamed in the code editor. This is essential, because I need to update MyViewModel or MyProperty references in my markup file accordingly. Otherwise users will get errors in the markup.

I found out there is IRefactorNotifyService interface in roslyn that seems to do just what I need. It looks well documented too. The problem is, it's internal. Could you please make it public? 
Or could you advise me on how to get the renaming to work correctly without it?

**Comment by exyi** [comment]
Hi, I have run into similar problem with `CompletionListProvider`. It is pretty cool interface and I'd like to extend the completion as is said in the comment. Why is it internal when you say it is extensibility interface?

**Comment by DustinCampbell** [comment]
Making the completion list API public is tracked by #5047. For rename, you likely want to look at `IVsRefactorNotify.OnGlobalSymbolRenamed(...)` in Visual Studio's API here: https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.shell.interop.ivsrefactornotify.onglobalsymbolrenamed(v=vs.110).aspx.
