### ISSUE TITLE
Add using with type rename adds useless using

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#9149]
1. Create a project with the following code:
    ```
    namespace ClassLibrary1
    {
        public class Class1Tests
        {
            public Class1 Blah()
            {
            }
        }
    }
    ```

2. Invoke Ctrl+. on the Class1 return value of Blah, that will have an error.

*Expected:* I get an operation that is "rename Class1 to Class1Tests".
*Actual:* I get an add using which offers to add a using for the namespace I'm already in (!), with no hint this is actually renaming the type to something I didn't expect without me carefully reading the diff.

**Comment by jasonmalinowski** [comment]
cc @CyrusNajmabadi since this might already be a duplicate of something.

**Comment by DustinCampbell** [comment]
Assuming it's *not* a dupe, let's look at this in 1.3. We've got enough for 1.2.

**Comment by CyrusNajmabadi** [comment]
3 issues:

1. We're messing with muscle memory by putting this  'add using' at the top of the list.  This is currently fixed.
2. We shouldn't add a using which is irrelevant. 
3. We should just enable the C# spell checker.

**Comment by CyrusNajmabadi** [comment]
You now get this list:

![image](https://cloud.githubusercontent.com/assets/4564579/14651972/061877dc-0627-11e6-8a9c-279e4ba1ac31.png)

Which seems good to me.
