### ISSUE TITLE
Remove binary serialization from the compiler

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#915]
This is all Serializable types. Incompatible with CoreCLR. Currently the only use is CodeLens.

**Comment by theoy** [comment]
Agree on rc2 for now, but we'd like to understand this better :)

**Comment by jaredpar** [comment]
The high level view here is that types like `ISerializable` and `SerializationInfo` are not supported in CoreCLR.  Yet they are present in code that we want to move to target CoreCLR hence we must move this code into a location which is intended to forever target Desktop.

**Comment by tmat** [comment]
That location should be CodeLens source code.

**Comment by tmat** [comment]
I think the milestone should be 1.0 actually.

**Comment by theoy** [comment]
:+1 on the move to 1.0, and the selection of CodeLens as the final destination of this code.
