### ISSUE TITLE
Provide better error message when setting key file using attributes

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#9150]
For in progress PR #9130

**Comment by agocke** [comment]
Note: This is only for `/publicsign`. For real and delay signing we support using the attribute, so no error should be reported. In addition, the attributes are currently ignored for `/publicsign` if `/keyfile` is set on the command line (the command line option takes precedence over the attributes) and no error is reported, so this must only happen when there is no `CryptoKeyFile` or `CryptoPublicKey` set in the options.

**Comment by jaredpar** [comment]
Did you mean for this to be in update 2?  Seems like an update 3 item.
