### ISSUE TITLE
Provide better error message for a relative path passed to CryptoKeyFile in CompilationOptions

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#9153]
In progress PR: https://github.com/dotnet/roslyn/pull/9130

**Comment by jaredpar** [comment]
Did you mean for this to be in update 2?  Seems like an update 3 issue.

**Comment by agocke** [comment]
Update 3. We can't modify resources, so better error messages aren't really possible.

**Comment by khyperia** [comment]
Fixed by the above PR, github didn't auto-close this. (Probably doesn't detect the second number in the text "Fixes [number] and [number]")
