### ISSUE TITLE
Provide a supported way to expose log file name for intellisense build

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#9158]
right now, there is no official way to get it, but it is good information to provide to users when intellisense build failure happens. (related to https://github.com/dotnet/roslyn/pull/9017)

we need a proper way to get this information (or some other methods to make users to discover logs easily) so that we don't need to use things like reflection to get it.

**Comment by srivatsn** [comment]
This bug is part of PR #9017 which is the bug to fix thousands of issues in error list. This is a change in the VS shell code needed to avoid using reflection in PR #9017 and hence was filed separately. Removing retriage label and keeping in 1.2 since the PR has already been approved for 1.2.
