### ISSUE TITLE
Build failed due to sharing violation

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#9166]
http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/4276/

error MSB3026:  Could not copy "C:\Users\dotnet-bot\.nuget\packages\System.Collections.Immutable\1.1.37\lib\dotnet\System.Collections.Immutable.dll" to "d:\j\workspace\roslyn_prtest---345e02d2\Binaries\Debug\System.Collections.Immutable.dll". Beginning retry 1 in 1000ms. The process cannot access the file 'd:\j\workspace\roslyn_prtest---345e02d2\Binaries\Debug\System.Collections.Immutable.dll' because it is being used by another process. [d:\j\workspace\roslyn_prtest---345e02d2\src\Compilers\CSharp\csc\csc.csproj] ->      9>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(3962,5):

**Comment by davkean** [comment]
Dup'ing this against the work item that we're using to fix this sort of thing: https://github.com/dotnet/roslyn/issues/8975
