### ISSUE TITLE
Suspicious `string.Format` invocation in `IntHashTable` constructor

### ISSUE THREAD

**Issue by SergeyTeplyakov** [dotnet/roslyn#9171]
I'm working on my custom analyzer called [ErrorProne.NET](https://github.com/SergeyTeplyakov/ErrorProne.NET) that helps find issues in C# code. By running it over Roslyn codebase I've found suspicious call to `string.Format` method [here](http://source.roslyn.io/#Roslyn.Test.PdbUtilities/Pdb/Token2SourceLineExporter.cs,b5628dd692e12b08,references):

``` csharp
internal IntHashTable(int capacity, int loadFactorPerc)
{
    if (capacity < 0)
        throw new ArgumentOutOfRangeException(nameof(capacity), "ArgumentOutOfRange_NeedNonNegNum");
    if (!(loadFactorPerc >= 10 && loadFactorPerc <= 100))
        throw new ArgumentOutOfRangeException(nameof(loadFactorPerc), String.Format("ArgumentOutOfRange_IntHashTableLoadFactor", 10, 100));

    // Based on perf work, .72 is the optimal load factor for this table.
    _loadFactorPerc = (loadFactorPerc * 72) / 100;

    int hashsize = GetPrime((int)(capacity / _loadFactorPerc));
    _buckets = new bucket[hashsize];

    _loadsize = (int)(_loadFactorPerc * hashsize) / 100;
    if (_loadsize >= hashsize)
        _loadsize = hashsize - 1;
}
```

Just by looking into second precondition check, I can assume that `string.Format` method is wrong here. I would suspect that instead of using `ArgumentOutOfRange_IntHashTableLoadFactor` string literal directly, appropriate resource string should be taken.

**Comment by AdamSpeight2008** [comment]
I think it should be the text literal. As the format string contains no arg holes, yet has 2 arguments. Those arguments look to be for range exception, giving the the allowed range.

**Comment by SergeyTeplyakov** [comment]
Yep it should be text literal, but current literal is very similar to resource identifier that should be used to retrieve the literal.

**Comment by krk** [comment]
`String.Format` call seems to be removed in commit 0cecbd8452fd241807b41c1ca4c55e85d36712f3

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/11055 thanks.
