### ISSUE TITLE
RenamingCompilerGeneratedDelegateTypeForEventCascadesBackToEvent is flaky

### ISSUE THREAD

**Issue by TyOverby** [dotnet/roslyn#9181]
http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/4234/testReport/junit/Microsoft.CodeAnalysis.Editor.UnitTests.Rename/RenameEngineTests/RenamingCompilerGeneratedDelegateTypeForEventCascadesBackToEvent_1/

**Comment by jasonmalinowski** [comment]
Closing in favor of the master bug.
