### ISSUE TITLE
Determinism Tests failing in Rolling Build for Stabilization

### ISSUE THREAD

**Issue by natidea** [dotnet/roslyn#9184]
Determinism tests started failing as of last night:
http://dotnet-ci.cloudapp.net/job/roslyn_stabil_determinism/29/

```
20:31:54 Determinism failed for the following binaries:
20:31:54 	Microsoft.DiaSymReader.PortablePdb.dll
20:31:54 	Microsoft.DiaSymReader.PortablePdb.UnitTests.dll
20:31:54 	Roslyn.Test.PdbUtilities.dll
```

Other failing builds:
http://dotnet-ci.cloudapp.net/job/roslyn_stabil_determinism/30/
http://dotnet-ci.cloudapp.net/job/roslyn_stabil_determinism/31/
http://dotnet-ci.cloudapp.net/job/roslyn_stabil_determinism/32/
http://dotnet-ci.cloudapp.net/job/roslyn_stabil_determinism/33/
http://dotnet-ci.cloudapp.net/job/roslyn_stabil_determinism/34/

Tag @dotnet/roslyn-compiler @dotnet/roslyn-infrastructure

**Comment by davkean** [comment]
tag @jaredpar 

Bear in mind, these occurred while we temporarily stopped archiving - so there's no logs.

**Comment by jaredpar** [comment]
This looks like a real failure.

**Comment by jaredpar** [comment]
Assigning to @tmat.  The determinism job started failing after this commit was merged and has not passed since. 

https://github.com/dotnet/roslyn/commit/7472f832971c4a1a3c658ce4291c01b665e2595a

**Comment by tmat** [comment]
Could you extract 2 dlls that are supposed to be the same but aren't and share them somewhere?

**Comment by jaredpar** [comment]
http://dotnet-ci.cloudapp.net/job/roslyn_stabil_determinism/35/artifact/Binaries/determinism.zip

The determinism job actually extracts the binaries that changed and puts them, the originals and the deterministic diagnostic file for each of them into a zip when it sees a failure.

**Comment by tmat** [comment]
Thanks

**Comment by jaredpar** [comment]
@tmat please let me know if other information could have been included in the zip that makes it easier to track down this bug.  The idea here is to make it as simple as possible to look into these bugs by putting the relevant data in the zip.

**Comment by tmat** [comment]
Fixed by https://github.com/dotnet/roslyn/commit/7bb0b4ea56dd7cc08f89830bd049e96aaa7e7f89
