### ISSUE TITLE
IOperation: Need to clarify difference between Divide and IntegerDivide in SimpleBinaryOperationKind

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#9188]
SimpleBinaryOperationKind

```
        Divide = 0x4,
        IntegerDivide = 0x5,
```

It is not clear for example when IntegerDivide vs. Divide should be used by C# compiler.

**Comment by jinujoseph** [comment]
This should be resolved once this is resolved https://github.com/dotnet/roslyn/issues/8835
