### ISSUE TITLE
Default BraceMatching errors out if syntax trees are not supported in the document

### ISSUE THREAD

**Issue by otawfik-ms** [dotnet/roslyn#9191]
The implementation of AbstractBraceMatcher.FindBracesAsync() tries to get the syntax root from the document in order to find the matching brace (token). For languages other than C#/VB, it calls Document.GetSyntaxRootAsync() which returns null because Document.SupportsSyntaxTree is false. In turn, FindBracesAsync() throws a null exception and the VS hive shuts down.

Roslyn should:

1. Log the appropriate error (perhaps instruct that either a syntax tree is supported, or the brace matcher implements IBraceMatcher.
2. Handle null values gracefully, and not shut down the hive.

**Comment by CyrusNajmabadi** [comment]
By design :)

The idea is for other languages to implement the IXXXLanguageServices (like IBraceMatcher).  Not to derive from AbstractXXXService.  The abstract types exist just to share similar logic between VB and C#.

**Comment by DustinCampbell** [comment]
This is by design per Cyrus's comment.
