### ISSUE TITLE
Find References and rename should find references in closed .aspx and .cshtml pages

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#9194]
Prior to VS 2015, when Find all references or rename was invoked in a Web Site project, we would find references in .aspx and .cshtml.  However, because of the way the language service interacts with the web project system, doing this was very expensive - we basically had to invisibly open each page in VS before doing the operation.

We never brought that forward to Web Application projects because it was so slow, and moving to Roslyn we ended up dropping it for Web Sites as well.

We should work with the ASP.NET Team resurrect this support, and make it faster.

**Comment by bodinaren** [comment]
We don't just have problem with .aspx files, but also with .aspx.vb files. Basically running a find all references for a function in a class library only returns results in other class library, nothing at all in the website project. I can even do find all references from an .aspx.vb file of a class library function and it doesn't even find the usage I ran the find all references from.

**Comment by Pilchie** [comment]
That's (unfortunately) expected for a Web *site* project, since the compilation for web sites is that the `.aspx` and `.aspx.vb` are compiled into a single assembly.  In contrast, in web *application* projects, all the `.aspx.vb` are compiled together with the `App_Code` folder.

**Comment by mikadumont** [comment]
This works in Razor and we don't have plans to support this in pre .NET Core scenarios as of now.

![FAR_ASP NET](https://user-images.githubusercontent.com/46729679/129767306-27a3624a-25d0-4b41-9db4-de2147f25dc8.gif)
