### ISSUE TITLE
[Test Failure] No identified problem in prtest/win/dbg/eta on PR #9130

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#9195]
PR: [#9130](https://github.com/dotnet/roslyn/pull/9130) *Always use an absolute path for keyfile with public sign* by @agocke
Failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/4337/

It looks like restore is failing?

**Comment by davkean** [comment]
Due of https://github.com/dotnet/roslyn/issues/9159
