### ISSUE TITLE
Should the compiler produce syntax trees for features that are not enabled?

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#9207]
When the language version is set, for example, to version 6, and we encounter the syntax for a language feature not present until version 7, we give an error in the parser. However, the question remains what parse tree should we build? If we build a parse tree that was designed for the new feature, we could possibly "break" analyzers that were not designed to handle them.

@jaredpar @AlekseyTs

**Comment by jaredpar** [comment]
This was resolved in the following way:

1. The compiler will always produce the same syntax trees irrespective of the `/langversion` flag. 
2. In the case a syntax element isn't legal under the given `/langversion` flag the node will be marked with an error.
