### ISSUE TITLE
Merge bot is not automatically running VSI or eta jobs

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#9227]
Our merge bot is not running VSI or ETA jobs. It should.

It looks like it doesn't have permission to run ETA or VSI - I suspect that's because it's not in the Microsoft team.
- [X] Add 'dotnet' to orgWhitelist in groovy scripts: `orgWhitelist(['Microsoft', 'dotnet'])`
- [X] Add 'dotnet' to http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_dbg_eta/ job which doesn't have a groovy script
- [X] Change merge tool to automatically trigger VSI

**Comment by dpoeschl** [comment]
@davkean @jmarolf All three checkboxes are checked. Is there more to do here?

**Comment by jmarolf** [comment]
@dpoeschl in spite of these checkboxes being checked, merges do not have vsi or eta tests running: https://github.com/dotnet/roslyn/pull/10298

**Comment by dpoeschl** [comment]
What is the merge bot, exactly? Should the third checkbox be unchecked?

**Comment by jmarolf** [comment]
@dpoeschl see [here](https://github.com/dotnet/roslyn/blob/master/src/Tools/Github/GitMergeBot/Program.cs#L104).  We should be triggering VSI runs.  Perhaps these conditions are never met?

**Comment by davkean** [comment]
Are we sure this worked? Looks like it's still not triggering VSI.

**Comment by jasonmalinowski** [comment]
Just validated that yes, this is working.
