### ISSUE TITLE
Proposal: this parameter

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#9234]
It's quite common to set class members directly from method parameters specifically to write fluent APIs.`this` parameters would ease that procedure. For example,

``` cs
class Foo {
  public string Name { get; private set; }
  public Foo WithName(this.Name) => this;
}

// translates to
class Foo {
  public string Name { get; private set; }
  public Foo WithName(string Name) {
    this.Name = Name;
    return this;
  }
}
```

All writable fields and properties would be allowed to be used in the parameter place.

Default values also would work just fine by translating them to optional arguments.

``` cs
public Foo WithName(this.Name = "Foo") => this;

public Foo WithName(string Name = "Foo") {
  this.Name = Name;
  return this;
}
```

You could define your `is` operator using `this` params as an alternative  to #8415,

``` cs
public void operator is(out this.Left, out this.Right) {}
```

**Comment by bondsbw** [comment]
I assume the return type `this` works similar to proposal #155 or #311?

I'm not sure what happens here:

```c#
public class A
{
    public string Name { get; set; }
    public this WithName(this.Name);
}
public class B : A {}

// ... then later

B b = new B();
var x = b.WithName("Bob");
```

What is the type of `x`?  Is it `A` or `B`?  I would think `B` is the better interpretation but I haven't thought it through.

**Comment by bondsbw** [comment]
And on that same note, assuming `x` is of type `B` above, it might be nice to be able to return a different base type or interface type (some fluent syntax depends on chaining different interfaces to enforce an order of invocations).

```c#
public (A)this WithName(this.Name);
```

**Comment by alrz** [comment]
@bondsbw Those proposals may be applied for convenience but the focus here is on `this` parameters; however, to my understanding, if it's intended to be `B` in your example, perhaps the method should be defined as `virtual` and use covariant return types (#357)?

Your second example is making it complicated. If any other type other than "self" is desired I think it's better for the method to be defined to explicitly return that type.

**Comment by bondsbw** [comment]
@alrz 
> perhaps the method should be defined as virtual and use covariant return types (#357)?

Under that solution, the `x` above would have been of type `A`, and to make it type `B` would require an override:
```c#
public class A
{
    public string Name { get; set; }
    public virtual this WithName(this.Name);
}
public class B : A 
{
    public override this WithName(this.Name);
    // or perhaps:
    // public override B WithName(this.Name);
}
```
I suppose that's better than not having #357 but it seems a bit redundant anyway.

**Comment by alrz** [comment]
@bondsbw This discussion probably belongs to #311 but making `this` return type automagically work with inheritance is not part of that proposal either.

**Comment by bondsbw** [comment]
>Your second example is making it complicated. If any other type other than "self" is desired I think it's better for the method to be defined to explicitly return that type.

Then the equivalent would be:

```c#
public class B : A 
{
    public A WithName(this.Name) { return this; }
}
```

I like taking advantage of the shorthand.

**Comment by alrz** [comment]
@bondsbw This discussion probably belongs to #311 but making `this` return type automagically work with inheritance is not part of that proposal either. 

PS: Or even `=> this` would just work for that matter.

**Comment by bondsbw** [comment]
@alrz 
> This discussion probably belongs to #311 but making this return type automagically work with inheritance is not part of that proposal either.

Right, that's one reason I didn't discuss it there (yet), seems like it is more concerned with the type being returned than the fact that it is actually returning `this`.

> PS: Or even => this would just work for that matter.

True, although I wonder if there could be any value in the compiler knowing for certain that the returned object is the same object?  Perhaps static analysis and stack management could be improved in some cases?

**Comment by lachbaer** [comment]
I don't think that
```C#
 public this WithName(this.Name);
```
is good, because declarations without a body (only semicolon) should stay declarations, that are defined elsewhere. But in this case you *define* the method `WithName` and therefore a body should be mandatory.

How about declaring it with the property?
```C#
public string Name this WithName { get; set; }
// will create
public string Name { get; set; }
public T WithName(string value) { Name=value; }
```
Access modifiers and visibility will be same for both, property and method. For anything that deviates from this, explicit implimentation should be done.

**Comment by alrz** [comment]
@lachebaer If that is not good I'd rather stick to the first form. Your example make it only useful for fluent APIs and dictates `With*` convention which doesn't apply everywhere. I don't think combining two declarations into one would be preferrable at all. Note that fluent APIs are one of the use cases for this and it might be useful in other situations as well.

**Comment by lachbaer** [comment]
@alrz It does not dictate `With*`, the `WithName` is an arbitrary identifier.

**Comment by lachbaer** [comment]
And if it gets anyhow complexer, isn't it better to have an explicitly defined method for it anyhow?

**Comment by alrz** [comment]
@lachbaer 
>isn't it better to have an explicitly defined method for it anyhow?

This doesn't eliminate the method declaration, you still need to write it, but with `this` parameters you define a parameter that will be initialized with the argument value when the method is called. I should probably remove the last example; I think that's the source of confusion here.

**Comment by lachbaer** [comment]
@alrz So, the only addition you actually propose is the addition of `this.XXX` in the parameters section of a method definition to call the setter of `XXX`? Neat idea, because it would make the expression body syntax possible and you can actually return anything you want.

And also I think that `... => this;` is pretty verbose and unterstandable already. No need for any further abbrevation IMO.

**Comment by gafter** [comment]
I don't understand the relationship between the proposed declaration form and why it is useful either at the declaration site or at the use site. Is this all about saving a line of code?

This is vaguely similar to a feature being considered as part of records; see the attached presentation pages 8-10.

[2016-02-24 Simple Records.pptx](https://github.com/dotnet/roslyn/files/151580/2016-02-24.Simple.Records.pptx)

**Comment by alrz** [comment]
@gafter That feature is about the ability to use `this.XXX` in the default value place for optional arguments, this would allow `this.XXX` *instead* of a parameter; If used for a regular method, yes, it saves a line of code but to be able to use positional deconstruction for non-record types one might define an `is` operator to explicitly specify bounded properties for pattern variables, e.g.
```cs
public void operator is(out this.Left, out this.Right) {}

// instead of
public void operator is(out Expression Left, out Expression Right) {
  Left = this.Left;
  Right = this.Right;
}
```
This can be considered as an alternative to #8415 which depends on accessible constructors. I think allowing it at least for `out` parameters can be useful in that context.

**Comment by lachbaer** [comment]
It doesn't feel right to me to violate the syntax of the method arguments. I somehow expect it to be *ref/out type identifier*.

As far as I understood your PPTX the new records match much of this proposal, except for 3 points:
- "Withers" restrict Name to 'With'
- Immutable, 'With' returns a new instance -> overhead
- Because immutable, no setting of mutable instance properties

For me the question now is whether it is worth to expand the functionality to mutable classes (with new syntax maybe) or if that would lead to an error prone paradigm.

**Comment by alrz** [comment]
I'll note that `With` method facilitates `with` expressions and has nothing to do with this proposal which intends to be used in fluent APIs.

**Comment by lachbaer** [comment]
@alrz A 'wither' is for `with` expressions, but will return a new (immutable) object. To extend this to mutable objects that return itself would be wonderful, in respect to this proposal.

**Comment by alrz** [comment]
On the second thought, `this` parameters can hamper the readability of the method parameters like using in the middle of the parameter list and for fluent API, as @gafter said, it just saves a line of code.

However I think the ability to use `this` parameter with `out` can be helpful to provide positional deconstruction for non-record types.
```cs
public void GetValues(out this.Left, out this.Right) {}
```
Alhough, this woudn't be the case if they chose to utilize tuples for this purpose,
```cs
public (Expression, Expression) GetValues() => (this.Left, this.Right);
```

**Comment by lachbaer** [comment]
@alrz In Python tuples really feel comfortable ;-) What shortcomings do tupels have?

But I don't feel comfortable with having no parameter identifier for the code block. As well, providing `out this.Left` would mean to wrap the body in a kinda `finally` block, so that the out parameters are assigned when leaving the block anywhere.

**Comment by alrz** [comment]
@lachbaer I'm not against tuples overall, I just don't think that they are a good fit in this context. See [#9005 comment](https://github.com/dotnet/roslyn/issues/9005#issuecomment-187211338) and the comment before that.

**Comment by alrz** [comment]
>But I don't feel comfortable with having no parameter identifier for the code block.

This would be useful only if you want to just assign the parameter to a property/field. Otherwise you should consider regular parameters of course.

>As well, providing out this.Left would mean to wrap the body in a kinda finally block, so that the out parameters are assigned when leaving the block anywhere.

Exceptions are the still the case when you use regular parameters, I expect that properties which throw are considered as "not matched" and the pattern would be failed, though, I don't know if this is covered in the draft spec.

**Comment by lachbaer** [comment]
I just saw in the Roslyn future code, that there are some error messages related to passing properties by ref. Haven't inspected it fully yet.
