### ISSUE TITLE
[nuget add using] Don't duplicate suggestions for xproj in U2

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/roslyn#9235]
In U2 WTE bits can not be modified and thus if Roslyn's feature will be on in U2 we would have 2 suggestions for missing packages in xproj projects.

To avoid that roslyn might check for project Capabilities property for xproj  (IVsHierarchy) and see if "SupportsMissingPackageSuggestions" is present. 

If it is not, then DON't show nuget suggestions. 

If it is - show (in this case it would mean that WTE had post U2 bits which already have disabled WTE index and added that capability).

**Comment by davkean** [comment]
That would cause this to light-down for all the projects. No C#/VB project (except xproj) provides that capability.

**Comment by abpiskunov** [comment]
Yes, you would need to check for capability only when project is xproj and ignore for all others.

**Comment by davkean** [comment]
Capabilities need to be agreed upon by all project owners, they are not designed to be have reverse defaults based on your project type.

I would rather see a simple property in the targets file that opts into this for xproj, and then we remove this in the future, and we sniff it via IVsBuildPropertyStorage.

**Comment by Pilchie** [comment]
Too late for U2, and not an issue for Dev15.
