### ISSUE TITLE
CSharp.Scripting...ObjectFormatterTests Failing

### ISSUE THREAD

**Issue by natidea** [dotnet/roslyn#9237]
`Microsoft.CodeAnalysis.CSharp.Scripting.Hosting.UnitTests.ObjectFormatterTests.StackTrace_Dynamic` started failing in X64 Rolling Build (roslyn_stabil_win_rel_unit64) following the merge of this PR:
https://github.com/dotnet/roslyn/pull/9193

http://dotnet-ci.cloudapp.net/job/roslyn_stabil_win_rel_unit64/136/

@tmat @dotnet/roslyn-infrastructure

**Comment by natidea** [comment]
@tmat could you take a look?

**Comment by davkean** [comment]
Dupe of #9221
