### ISSUE TITLE
VS IDE: outlining should collapse expression-bodied members

### ISSUE THREAD

**Issue by jods4** [dotnet/roslyn#9238]
Lambda members are meant to be short like so:

``` csharp
public string FullName => $"{FirstName} {LastName}";
```

But I sometimes see slightly longer ones in our codebases, such as these ones:

``` csharp
// On two lines
public double ComputeTaxes()
  => Orders.Where(o => !o.TaxFree).Sum(o => o.Quantity * o.UnitPrice);

// Sometimes more
public IQueryable<Person> ActiveEmployees
  => from p in db.Person.Include("Manager")
     where p.IsEmployee
        && p.ContractEnd > DateTime.Today
     select p;
```

The problem with those is that VS code editor does not collapse code like it does for members with "normal" bodies.

To navigate or get an overview of a class I like to collapse everything to definitions but with those in the way it now becomes less readable and slightly cluttered.

I suggest that when a lambda property or method spans more than one line, we should be able to collapse it to its definition like a regular method.

Bonus points for doing the same with initializers, such as:

``` csharp
private List<string> DogNames = new List<string> 
{
  "Pluto",
  "Goofy", 
  "Rintintin",
};
```

**Comment by Pilchie** [comment]
Did you do this already?

**Comment by CyrusNajmabadi** [comment]
Good suggestions.  I'll add these.
