### ISSUE TITLE
BasicVenus.xml (BasicVenus.Script Block: Commit and Smart Indent On Moving out of current line) failed

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#9241]
PR: [#9239](https://github.com/dotnet/roslyn/pull/9239) *Upgrade to NuGet to 3.4.0.665 to fix #9159* by @davkean
Failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p1/348/

**1 Test Failures:**
BasicVenus.Script Block: Commit and Smart Indent On Moving out of current line

**Issue 1: Individual TAO Test Failure**
Failing integration tests: 

BasicVenus.xml

**Comment by brettfo** [comment]
Currently tracking via #9671.
