### ISSUE TITLE
InstallDogfood doesn't work with Update 2 installed

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#9242]
After installing Update 2 CTP, trying to run install dogfood results in:

> ---
> ## Install Roslyn Dogfood
> 
> Failed to install:
> 
> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Telemetry, Version=14.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
> 
>    at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InitializeList(CachedInstalledExtensionList cachedExtensionsList, IEnumerable`1 enabledExtensions, Boolean safeMode, Boolean isSdkList, Int64 lastExtensionsChangedTimestamp)
> 
>    at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstalledExtensionListData.<>c__DisplayClass16_0.<CreateExtensionListData>b__2()
> 
>    at System.Threading.Tasks.Task.InnerInvoke()
> 
>    at System.Threading.Tasks.Task.Execute()
> 
>    --- End of inner exception stack trace ---
> 
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
> 
>    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
> 
>    at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.PartitionedInstalledExtensionList.Commit()
> 
>    at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.Close()
> 
>    at InstallDogfood.VsixManager.Uninstall(String vsixIdentifier) in D:\Code\Roslyn\Closed\Tools\Source\InstallDogfood\VsixManager.cs:line 55
> 
>    at InstallDogfood.Utilities.UninstallVsix(VsixInfo vsix, Lazy`1 lazyVsixManager) in D:\Code\Roslyn\Closed\Tools\Source\InstallDogfood\Utilities.cs:line 672
> 
>    at InstallDogfood.Utilities.<>c__DisplayClass37_0.<CreateUninstallVsixStep>b__0() in D:\Code\Roslyn\Closed\Tools\Source\InstallDogfood\Utilities.cs:line 589
> 
>    at InstallDogfood.MainWindow.RunSteps(IEnumerable`1 installSteps, Action`1 onStepStarting) in D:\Code\Roslyn\Closed\Tools\Source\InstallDogfood\MainWindow.xaml.cs:line 375
> 
>    at InstallDogfood.MainWindow.<>c__DisplayClass26_0.<InstallBuild>b__0() in D:\Code\Roslyn\Closed\Tools\Source\InstallDogfood\MainWindow.xaml.cs:line 351
> 
>    at System.Threading.Tasks.Task.InnerInvoke()
> 
>    at System.Threading.Tasks.Task.Execute()
> 
>    --- End of inner exception stack trace ---
> 
> ---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Telemetry, Version=14.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
> 
>    at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InitializeList(CachedInstalledExtensionList cachedExtensionsList, IEnumerable`1 enabledExtensions, Boolean safeMode, Boolean isSdkList, Int64 lastExtensionsChangedTimestamp)
> 
>    at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstalledExtensionListData.<>c__DisplayClass16_0.<CreateExtensionListData>b__2()
> 
>    at System.Threading.Tasks.Task.InnerInvoke()
> 
>    at System.Threading.Tasks.Task.Execute()
> 
>    --- End of inner exception stack trace ---
> 
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
> 
>    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
> 
>    at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.PartitionedInstalledExtensionList.Commit()
> 
>    at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.Close()
> 
>    at InstallDogfood.VsixManager.Uninstall(String vsixIdentifier) in D:\Code\Roslyn\Closed\Tools\Source\InstallDogfood\VsixManager.cs:line 55
> 
>    at InstallDogfood.Utilities.UninstallVsix(VsixInfo vsix, Lazy`1 lazyVsixManager) in D:\Code\Roslyn\Closed\Tools\Source\InstallDogfood\Utilities.cs:line 672
> 
>    at InstallDogfood.Utilities.<>c__DisplayClass37_0.<CreateUninstallVsixStep>b__0() in D:\Code\Roslyn\Closed\Tools\Source\InstallDogfood\Utilities.cs:line 589
> 
>    at InstallDogfood.MainWindow.RunSteps(IEnumerable`1 installSteps, Action`1 onStepStarting) in D:\Code\Roslyn\Closed\Tools\Source\InstallDogfood\MainWindow.xaml.cs:line 375
> 
>    at InstallDogfood.MainWindow.<>c__DisplayClass26_0.<InstallBuild>b__0() in D:\Code\Roslyn\Closed\Tools\Source\InstallDogfood\MainWindow.xaml.cs:line 351
> 
>    at System.Threading.Tasks.Task.InnerInvoke()
> 
>    at System.Threading.Tasks.Task.Execute()
> 
> ---> (Inner Exception #0) System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Telemetry, Version=14.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
> 
> File name: 'Microsoft.VisualStudio.Telemetry, Version=14.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
> 
>    at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InitializeList(CachedInstalledExtensionList cachedExtensionsList, IEnumerable`1 enabledExtensions, Boolean safeMode, Boolean isSdkList, Int64 lastExtensionsChangedTimestamp)
> 
>    at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstalledExtensionListData.<>c__DisplayClass16_0.<CreateExtensionListData>b__2()
> 
>    at System.Threading.Tasks.Task.InnerInvoke()
> 
>    at System.Threading.Tasks.Task.Execute()
> 
> WRN: Assembly binding logging is turned OFF.
> 
> To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog](DWORD) to 1.
> 
> Note: There is some performance penalty associated with assembly bind failure logging.
> 
> To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
> 
> <---
> 
> <---
> ---
> ## OK   

Looks like we need some new binding redirects?

**Comment by Pilchie** [comment]
Tag @davkean

**Comment by jasonmalinowski** [comment]
I think we can safely say this isn't happening anymore.
