### ISSUE TITLE
Consider pattern matching for extract method scenarios

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#9244]
As a part of fixing #9104 for preview pattern matching is being blanket excluded from extract method.  For RTM though we should be looking at this and considering what valid extractions could be done an pattern expressions.

**Comment by Pilchie** [comment]
Can you get some stakeholders together to figure out what the experience should be here?

**Comment by jcouv** [comment]
@jaredpar @gafter Are there some scenarios we could list for this?
If not, I'd suggest closing.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
