### ISSUE TITLE
Produce PDBs with deterministic GUIDs

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#926]
When compiling with debug enabled, both the C# and VB compilers produce PDB files, and reference the PDB's GUID in the main assembly. But our current mechanism for producing PDBs generate random GUIDs, which results in a different compiler output each time the compiler is run. Because we'd like the compiler to be deterministic, the GUID in the PDB should only vary when needed (e.g. when the source files have changed).

This is part of #372, and related to #312.

/cc @tmat

**Comment by jaredpar** [comment]
CC @jaredpar

**Comment by gafter** [comment]
@VladimirReshetnikov pointed me to the possibly relevant http://stackoverflow.com/questions/17799013/what-do-directory-names-like-d0c3bddd4add4e87b2b5e803303b8d772-in-visual-studio/17799377#17799377

**Comment by gafter** [comment]
CC @kirill

**Comment by gafter** [comment]
CC @KirillOsenkov

**Comment by gafter** [comment]
@tmat and I synthesized the following proposed plan from our previous ideas and discussions:

1.	Start with a clean, empty PDB stream with PID=0 (PDB0)
2.	Compile and emit, updating the PDB incrementally, using MVID0=0 and PID0=0 (producing PE0, PDB1)
3.	Compute hash(PE0, source files) to produce a new MVID and PID deterministically
4.	Compute the final PE = PE0 with MVID and PID substituted (and write it)
5.	Compute the final PDB = PDB1 with PID substituted (and write it)

The only source of nondeterminism in this plan would be any nondeterminism introduced in step (2) by the PDB writer implementation. If it is, in practice, deterministic when used in this mode then we are done.

The downsides of this plan is that we might produce the same PID for distinct PDB files where the differences are caused by changes or nondeterminism in the compiler or the PDB writer. For example if we fix bugs in the compiler that improve the quality of the generated PDB file (but generate the same IL), we'd still generate the same PID for the new (different) PDB file. We think that is a reasonable compromise.

**Comment by gafter** [comment]
Should step (3) in this plan compute the hash of PE0 and PDB1 instead of PE0 and the source files?

**Comment by jaredpar** [comment]
Assuming PID = PDB ID 

This plan sounds reasonable to me.  I'm curious about the implementation of steps 4 and 5 though, 5 in particular.  Are we just doing a straight search and replace in the binary of the PID?

**Comment by tmat** [comment]
No. I'm working on creating a clean empty PDB that can be used to seed the PDB writer. The hypothesis is that after PDB writer is done writing there will be a single well-defined place to patch in the resulting stream.

**Comment by gafter** [comment]
This is our latest plan:

1.	Compile and emit normally, tracking the set of calls to the PDB writing library into a LOG
2.	Compute hash(LOG) using a strong hash function to produce a new GUID and timestamp deterministically
3.	Write the PDB with the GUID and timestamp computed above

The only source of nondeterminism in this plan would be that introduced by the implementation of the PDB writing library. If it is, in practice, deterministic when used in this mode then we are done.

The downside of this plan is that we might produce the same PID for distinct PDB files where the differences are caused by changes or nondeterminism in the PDB writer. Such distinct PDB files would have the same GUID and be interchangeable. Because they have the same GUID they would not interfere with the determinism of the PE file (.exe or .dll).

**Comment by gafter** [comment]
@tmat Can you please verify that this works?

**Comment by KirillOsenkov** [comment]
I don't know what's the latest on this but last time I tried there were 6 bytes that weren't deterministic: #2422 

Given that bug is a Won't Fix, @gafter, when you say "verify that this works", what do you mean?

**Comment by KirillOsenkov** [comment]
But then again, as I said before, even without deterministic .pdbs we hope to extract tremendous value from deterministic PE files.

**Comment by gafter** [comment]
I mean please verify that the PDBs have deterministic GUIDs.

**Comment by KirillOsenkov** [comment]
GUIDs seem to be deterministic, at least on a simple console app I tried!

**Comment by gafter** [comment]
Thanks, @KirillOsenkov .

**Comment by gafter** [comment]
The change was fixed and verified. If there is a previously unidentified problem with it please create a new issue.

**Comment by tmat** [comment]
To fix this issue revert commit:
https://github.com/dotnet/roslyn/commit/c4c6acb1036c53b4ad91e2f92609914a29e602cf

**Comment by gafter** [comment]
This is fixed, but only when `/features:deterministic` is used.

**Comment by KirillOsenkov** [comment]
@gafter are you saying that the old .pdb format is now deterministic (under a feature flag) or are we talking about the new .pdb format?

**Comment by tmat** [comment]
@KirillOsenkov No, old PDB is not completely deterministic. But the PDB ID is, which is important since the PE contains it.

**Comment by gafter** [comment]
I am saying that you can use the `/features:deterministic` flag to get deterministic PDB GUIDs (i.e. the subject of this issue), in both the old and new format.
