### ISSUE TITLE
Completion: preselect based on names

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#9260]
This is a logical extension of target type preselection. `y` should be preselected below based on the name. In the current implementation `x` is.

``` C#
class Program
{
    static void GetPoint(int x, int y) { }

    static void Main()
    {
        int x = 2;
        int y = 3;
        GetPoint(x, $$);
    }
}
```

**Comment by rchande** [comment]
FYI @CyrusNajmabadi

**Comment by Pilchie** [comment]
Added to #7056.

**Comment by CyrusNajmabadi** [comment]
Intellicode offers thsi now:

![image](https://user-images.githubusercontent.com/4564579/217126764-549db624-a6dd-4b82-844f-7c6f6803d8c2.png)
