### ISSUE TITLE
default(SymbolInfo) versus SymbolInfo.None in C#'s SemanticModel implementation

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#9261]
In the C# compiler's semantic model implementations, we have a number of places where we return `SymbolInfo.None`, and a number of places where we return `default(SymbolInfo)`. We should probably rationalize these to a single pattern unless there is a reason to be different.

/cc @AlekseyTs

**Comment by jaredpar** [comment]
This seems like it can be moved to 2.1.  Any push back?
