### ISSUE TITLE
Need more IDE tests for pattern-matching scenarios

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#9269]
It would be good to have many more unit tests for IDE scenarios involving the pattern-matching language feature.

**Comment by jaredpar** [comment]
How is this going?  We need to validate this for the upcoming release.

**Comment by gafter** [comment]
@CyrusNajmabadi has been doing testing and IDE fixes under #9068, and I'm working on design changes or bug fixes where needed. I'm currently working on a design change (#9371) needed to simplify the IDE work for #9231 and #9090.

You could ask this at our daily standup :wink:

**Comment by jaredpar** [comment]
Before we make changes we need to lock in the IDE behavior that we've already fixed.  Changing the design before adding tests opens the possibility of regression.

**Comment by gafter** [comment]
I believe there are IDE tests for everything that has been fixed.

**Comment by jaredpar** [comment]
Where are the IDE regression tests for the bugs fixed here?

https://github.com/dotnet/roslyn/pull/9233

**Comment by gafter** [comment]
Closing this as we have separate bugs for each item to be tested.
