### ISSUE TITLE
"No input sources" error in BasicAnalyzers.Vsix project

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#9274]
When I build the master branch with `msbuild /v:m /m BuildAndTest.proj`, I get the following error:

vbc : error BC2008: no input sources specified [d:\repos\roslyn2\src\Samples\VisualBasic\Analyzers\BasicAnalyzers\BasicAnalyzers.Vsix\BasicAnalyzers.Vsix.vbproj]

**Comment by davkean** [comment]
@jcouv Are you still hitting this? I'm not seeing this.

**Comment by jcouv** [comment]
@davkean Yes, I just verified I can still repro.
I have dotnet/roslyn enlistment, checked out on master, restored, cleaned (-xdf), then build Roslyn.sln, then build BuildAndTest.proj (which has this message).

**Comment by AdamSpeight2008** [comment]
I'm getting this issue when try to compile the `Analyser + Code Fix (NuGet)` project for VB

**Comment by davkean** [comment]
@AdamSpeight2008 Please file a new issue for that.

**Comment by tombrown571** [comment]
I get the "no input sources specified" in the Vsix project,  when creating a new VB.NET Extensibility  Analyser + Code Fix project.

The easy workaround is to add a dummy source file to the Vsix project. - Just add a class file "dummy.vb" - and the project compiles and runs OK.
