### ISSUE TITLE
[Test Failure] Test Failures in prtest/win/dbg/unit64 on PR #9259

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#9276]
PR: [#9259](https://github.com/dotnet/roslyn/pull/9259) *Fix devenv /build and devenv /upgrade* by @jmarolf
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/4444/

**1 Test Failures:**
Microsoft.CodeAnalysis.Editor.UnitTests.Rename.VisualBasic.ImplicitReferenceConflictTests.RenameMoveNextInCSCauseConflictInForEach

**Issue 1: Test Failures**
There were test failures, see Test Results above.

Rename test failure

**Comment by DustinCampbell** [comment]
Hmmm... seems like we've already seen this.

**Comment by DustinCampbell** [comment]
Probably related to #9151

**Comment by dpoeschl** [comment]
Closing in favor of main tracking bug #9308.

@jasonmalinowski This is a crosslanguage rename test failure. If you see any reason to keep this separate from the rest, feel free to reopen.
