### ISSUE TITLE
Do not trigger SyntaxDiagnostic analysis in a project for a Metadata Reference change

### ISSUE THREAD

**Issue by basoundr** [dotnet/roslyn#9282]
This is in reference to the Memory Allocation regression issue that we saw in Dev14 Update which was caused by running Syntax Diagnostics on all closed files of a project whose Metadata Reference got modified.

**Comment by mavasani** [comment]
Moving to @heejaechang for consideration in v2 engine.

**Comment by mavasani** [comment]
Actually, in v2 we don't run either syntax or semantic analysis on closed files, so this might have been resolved.

**Comment by heejaechang** [comment]
this doesn't matter anymore in v2.

**Comment by heejaechang** [comment]
related to https://github.com/dotnet/roslyn/pull/10950
