### ISSUE TITLE
SymbolInfo for bad property in a property pattern should contain candidate symbols

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#9284]
The `SymbolInfo` returned when there is a bad property in a property pattern (e.g. because it is ambiguous, inaccessible, `static`, etc) should contain any properties that are (improperly) referenced.

See, for example, the test `AmbiguousNamedProperty` in `PatternMatchingTests`.

**Comment by AlekseyTs** [comment]
The diagnostic should also be adjusted to better reflect the reason for the failure. 
We should consider reusing the code that is used to bind members in object member initializers, I think it makes sure the errors are accurate and all appropriate information is available to SemanticModel.

**Comment by gafter** [comment]
Fixed in the `features/patterns` branch by #10590

**Comment by AlekseyTs** [comment]
@gafter I am not sure how this issue was fixed in #10590. It doesn't look like new test for this specific scenario were added. Note that
> The diagnostic should also be adjusted to better reflect the reason for the failure. 

is also part of this issue.

**Comment by gafter** [comment]
Fixed and tested in https://github.com/dotnet/roslyn/pull/27160
