### ISSUE TITLE
Crash/empty item list in Locals window when quantity of elements inside a collection changes

### ISSUE THREAD

**Issue by adamante** [dotnet/roslyn#9290]
Steps to reproduce:

1. Create any collection (List, Queue, Stack, etc.)
2. Add a few items to it
3. Remove an item from the collection (set a breakpoint on this instruction)
4. Run
5. When you hit a breakpoint, expand the collection in Locals window
6. Take a step over (F10)
7. Collection will collapse in Locals window, try to expand it again.

From that moment, VS either crashes or the collection items are no longer visible in locals window.

OS: Windows 8.1 x64
VS: Enterprise 2015 with Update 1

Code to reproduce:
```
static void Main(string[] args)
{
            var stack = new Stack<int>();

            stack.Push(1);
            stack.Push(2);

            var first = stack.Pop(); // Set a breakpoint here
            Console.ReadKey();
}
```

**Comment by ManishJayaswal** [comment]
@adamante I am not able to reproduce this on update 2 bits of VS 2015. Can you try with update 2 installed?

**Comment by adamante** [comment]
@ManishJayaswal I've tried - can't reproduce it now either with Update 2. Must've been fixed, it was more than two month ago :) Thanks for reaching out :+1: This can be closed
