### ISSUE TITLE
NuGet package dependencies broken in analyzer project template

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn#9292]
Adding packages to a new Analyzer project always fails (see below). Only after updating all Microsoft.\* packages to newest versions, new packages can be added. But that breaks backwards compatibility (running from VS2015 without SP1).

Repro steps:
1. Create new project from template Extensibility > Analyzer with Code Fix (NuGet + VSIX)
2. From Package Manager Console, type: `install-package log4net` and press Enter
3. Error message appears:

```
Attempting to gather dependencies information for package 'log4net.2.0.5' with respect to project 'TempAnalyzer1', targeting '.NETPortable,Version=v4.5,Profile=Profile7'
Attempting to resolve dependencies for package 'log4net.2.0.5' with DependencyBehavior 'Lowest'
install-package : Unable to resolve dependencies. 'Microsoft.CodeAnalysis.Analyzers 1.1.0' is not compatible with 'Microsoft.CodeAnalysis.Common 1.0.0 constraint: Microsof
t.CodeAnalysis.Analyzers (= 1.0.0)'.
At line:1 char:1
+ install-package log4net
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
```

**Comment by bkoelman** [comment]
Repros on Update2 CTP. 
Tagging @jmarolf as we worked on these templates in the past.

**Comment by jmarolf** [comment]
Looks like Microsoft.CodeAnalysis.Common.1.0.0 was authored wrong.  it required the analyzers to match exactly.
```XML
<dependency id="Microsoft.CodeAnalysis.Analyzers" version="[1.0.0]" />
```

A workaround on your side would be to downgrade `Microsoft.CodeAnalysis.Analyzers` to version 1.0.0, though you will still have the problem that log4net is not compatible with Profile7 

@srivatsn could we release  `Microsoft.CodeAnalysis.Common.1.0.1` that was the same except that it allows higher versions of Microsoft.CodeAnalysis.Analyzers?

**Comment by bkoelman** [comment]
@jmarolf Thanks for looking into this. The suggested workaround brings me back to https://github.com/dotnet/roslyn/issues/7276. It breaks the build, so that's not an option.

**Comment by bkoelman** [comment]
Any news on this?

**Comment by bkoelman** [comment]
Thanks! I lost hope for getting this fix out :)
