### ISSUE TITLE
Proposal: Abstract interface

### ISSUE THREAD

**Issue by lachbaer** [dotnet/roslyn#9297]
During discussing #9132 I had the idea to propose `abstract interface`
```C#
public abstract interface IAnimal {
    void Walk();
    int Legs { get; set; }
}
```
When you use an *abstract interface* the compiler can check at compile time if the handed class instance implements all of the methods, events and properties of it. You can then pass any class that fits.
```C#
public class Cat {
    void Walk();
    int Legs { get; set; }
    void Jump();
}

public void Go(IAnimal animal) {
  animal.Walk();
}

public static void Main() {
  var myCat = new Cat(); 
  Go(myCat); // compiler checks if myCat fulfills the IAnimal abstract contract
}
```
In case of a cat that has paws instead of legs I think it would be better to stick with the current standard and define a derived class with an corresponding copy constructor
```C#
public class CatWithLegs : Cat {
  public CatWithLegs(Cat _originalCat) { /* copy */ }
  public int Legs {
    get => base.Paws; // 7881
    set => base.Paws = value;
  }
}
```
It should not be possible to 'derive' from an abstract interface, like with an abstract class definition, just to stay consistent.

**Comment by gafter** [comment]
I think proposing a concrete syntax for a different issue is best done inside that issue's discussion thread. Closing as a dup of #9132.
