### ISSUE TITLE
[Test Failure] Test Failures in prtest/win/dbg/unit32 on PR #9163

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#9298]
PR: [#9163](https://github.com/dotnet/roslyn/pull/9163) *Mark methods as Obsolete.* by @CyrusNajmabadi
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/4473/

**1 Test Failures:**
Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameEngineTests.RenameMergedNamespaceAcrossProjects
Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameEngineTests+VisualBasicConflicts.Bug529989_RenameCSharpIdentifierToInvalidVBIdentifier
Microsoft.CodeAnalysis.Editor.UnitTests.FindReferences.FindReferencesTests.TestField_InDependentProject1

**Issue 1: Test Failures**
There were test failures, see Test Results above.

**Comment by davkean** [comment]
Failure here as well: https://github.com/dotnet/roslyn/issues/9299

**Comment by jasonmalinowski** [comment]
Closing in favor of #9308.
