### ISSUE TITLE
Unless a rule fails, it is difficult (impossible?) to find it's on-line help

### ISSUE THREAD

**Issue by KathleenDollard** [dotnet/roslyn#93]
Scenario:

I am perusing a the Solution Explorer list or the ruleset to see what rules I would like to enable. I cannot find a way to access the help for the rule - like the MSDN help for the FxCop rules. 

Desired outcome:

In a perfect world, the ruleset dialog would not be needed unless non-AnalyzerID sorts were desired. Therefore, it would be best if right clicking in Solution Explorer had an option to go to help, and/or the ID of the analyzer was a hyperlink (like in the error dialog). 

If not in Solution Explorer, this capability in the ruleset dialog.

**Comment by srivatsn** [comment]
We should probably just add a right-click menu item on a rule that navigates to the helpuri.

**Comment by tmeschter** [comment]
FYI, when a rule is selected in Solution Explorer the Properties window has an item for "Help link". Currently you need to copy-and-paste the link text into a browser, however.

That being said, a menu item is probably the way to go.

**Comment by tmeschter** [comment]
Assigning to @jmarolf for verification.
