### ISSUE TITLE
Visual Studio is missing the word completion function

### ISSUE THREAD

**Issue by zoukyle** [dotnet/roslyn#9300]
I have Edit.CompleteWord associated with Alt + /.
Basically I think VS is missing the work completion function in the comment section. http://eclipsebook.in/c-cpp-development/editing-code/code-completion/

For example, if I have a long variable name, ThisIsATestVariable. If I type ThisIs and press Alt + /, it should autocomplete the variable name instead of typing the full name. If there are multiple variables with prefix ThisIs, it should let me choose or just loop through all of them.

**Comment by CyrusNajmabadi** [comment]
This is also what completion just offers with ctrl-space.  Haven't heard any requests for this further.
