### ISSUE TITLE
Cross-language tests are flaky

### ISSUE THREAD

**Issue by TyOverby** [dotnet/roslyn#9308]
This is a master-bug for #9181 and #9151

Rename Engine tests are flaky.

* [RenamingCompilerGeneratedDelegateTypeForEventCascadesBackToEvent](http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/4234/testReport/junit/Microsoft.CodeAnalysis.Editor.UnitTests.Rename/RenameEngineTests/RenamingCompilerGeneratedDelegateTypeForEventCascadesBackToEvent_1/)
* [RenameMoveNextInVBToUpperCaseOnlyCausesConflictInCSForEach](https://github.com/dotnet/roslyn/issues/9151)
* [RenameMoveNextInVBToUpperCaseOnlyCausesConflictInCSForEach](http://dotnet-ci.cloudapp.net/view/Roslyn/job/roslyn_stabil_win_dbg_unit32/147/)
* [Bug529765_CrossLanguageOverrideImplicitPropertyAccessor_2](http://dotnet-ci.cloudapp.net/view/Roslyn/job/roslyn_stabil_win_dbg_unit32/148/)
* [RenameCrefCrossAssembly](http://dotnet-ci.cloudapp.net/view/Roslyn/job/roslyn_stabil_win_dbg_unit32/148/)
* [RenameMoveNextInCSCauseConflictInForEach](http://dotnet-ci.cloudapp.net/view/Roslyn/job/roslyn_stabil_win_dbg_unit32/150/console)

**Comment by TyOverby** [comment]
@davkean @jasonmalinowski

**Comment by jasonmalinowski** [comment]
This was fixed by @TyOverby in #9504.
