### ISSUE TITLE
Should the analyzer template projects use the devDependency property?

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn#9311]
See https://github.com/code-cracker/code-cracker/issues/706 for a scenario where this will be useful. 

The documentation for this property is here  -https://docs.nuget.org/create/nuspec-reference, for your reference?

We should try out this property to see if there's any downside to it and if not, add it to the nuspec for the default analyzer template.

**Comment by jmarolf** [comment]
Closed with https://github.com/dotnet/roslyn-internal/pull/1009

**Comment by srivatsn** [comment]
@mavasani we should add this to all our analyzer packages.

**Comment by giggio** [comment]
@jmarolf I can't see the `roslyn-internal` repo, I guess it is private (what is this repo?).
How was this handled?
