### ISSUE TITLE
Roslyn Insertion Tool needs to mark inserted build as "Keep Indefinitely"

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#9314]
The Roslyn Insertion Tool should keep track of all the PRs that it creates and mark the associated builds as "Keep Indefinitely" if it detects that they have been merged in.

**Comment by genlu** [comment]
Is there a way to know if it's safe to unmark "Keep Indefinitely" for a build?

**Comment by jasonmalinowski** [comment]
I've been tagging milestone builds as "Released to Public" in visual studio. We should also have this tool see that flag and know never to unmark the builds.

**Comment by davkean** [comment]
What's the "Released to Public" tag? Is this a tag? Or something special on the build result?

**Comment by jasonmalinowski** [comment]
Reactivating while a bug exists.

**Comment by jasonmalinowski** [comment]
Yep, it's working.
