### ISSUE TITLE
Visual Studio 2015 MergeTool Crashes VS

### ISSUE THREAD

**Issue by TheOpenDevProject** [dotnet/roslyn#9317]
When trying to use VisualStudio with git as the mergetool visual studio crashes with the following error message.

![image](https://cloud.githubusercontent.com/assets/6072108/13412937/d5e1cc42-df9a-11e5-9810-252b87982c10.png)

Steps to reproduce:

1. Initiate merge of branch (A) -> branch (B) through git bash `git merge master`

2. With Visual Studio 2015 set as the default mergetool for the project run the command `git mergetool -y`

3. Once you run across a cshtml file I get the above crash error.

Looking at the log provided by VS the following exception is found.
```
System.ArgumentNullException: Value cannot be null. Parameter name: key at System.Collections.Generic.Dictionary`2.FindEntry(TKey key) at
Microsoft.VisualStudio.Html.Package.Extensions.ExtensionsManager.OnTextViewCreated(ITextView textView, ITextBuffer textBuffer) at
Microsoft.Web.Editor.Controller.TextViewConnectionListener.OnTextViewGotAggregateFocus(ITextView textView, ITextBuffer textBuffer) at
Microsoft.VisualStudio.Html.Package.Commands.Html.VsHtmlTextViewConnectionListener.OnTextViewGotAggregateFocus(ITextView textView, ITextBuffer textBuffer) at
Microsoft.Web.Editor.Controller.TextViewConnectionListener.<>c__DisplayClass24_0.<OnTextViewConnected>b__0(Object sender, EventArgs eventArgs) at
Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent(Object sender, EventHandler eventHandlers)
```

![image](https://cloud.githubusercontent.com/assets/6072108/13413070/e44f5334-df9b-11e5-91be-e0b4f6ec8ae4.png)

**Comment by TheOpenDevProject** [comment]
@Pilchie sorry about that I was directed to this issue tracker and figured that it was being used for rosyln and everything dotnet related including VS

**Comment by madskristensen** [comment]
@TheOpenDevProject A bug was introduced in the ASP.NET 5 RC1 tooling that caused this. The workaround is simple and is described [here](https://blogs.msdn.microsoft.com/webdev/2016/01/12/visual-studio-keeps-showing-suggested-extensions/). The issue has been fixed and will be in the next update to the ASP.NET 5/Core tooling

**Comment by Pilchie** [comment]
Also - don't worry about the fact that you reported here.  There are a bunch of repos, and it's tough to figure out the boundaries.  We're happy to get things to the right spot.

**Comment by TheOpenDevProject** [comment]
@Pilchie @madskristensen Understood will await for the update to be released. Ill close the issue since it has been fixed in a newer version.
