### ISSUE TITLE
Remove ConditionalWeakTable from the compilers

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#9331]
Conditional weak tables are expensive - they incur a cost at every garbage-collection. But a fair number of them were added to the compilers when IOperation was integrated. They are mostly used to simulate extra fields on bound trees. There is no need to do that, as bound nodes are already transient. Any ConditionalWeakTables used to simulate extra fields on bound nodes can be replaced by ordinary fields on those bound nodes.

**Comment by JohnHamby** [comment]
I had assumed that adding fields to bound nodes was forbidden. If adding real fields is OK, then all of the CWTs added for IOperation can be eliminated.

**Comment by gafter** [comment]
@jaredpar @JohnHamby I didn't mean to unassign this just now... github did that for me. I cannot find a way to fix that.

**Comment by heejaechang** [comment]
I removed ones related to IOperation.

...

here are still ones used in compiler

  Compilers\Core\Portable\DiagnosticAnalyzer\AnalysisState.cs(62):        private readonly ConditionalWeakTable<SyntaxTree, SemanticModel> _semanticModelsMap;
  Compilers\Core\Portable\DiagnosticAnalyzer\AnalysisState.cs(76):            _semanticModelsMap = new ConditionalWeakTable<SyntaxTree, SemanticModel>();
  Compilers\Core\Portable\DiagnosticAnalyzer\AnalysisValueProvider.cs(16):        private readonly ConditionalWeakTable<TKey, WrappedValue> _valueCache;
  Compilers\Core\Portable\DiagnosticAnalyzer\AnalysisValueProvider.cs(17):        private readonly ConditionalWeakTable<TKey, WrappedValue>.CreateValueCallback _valueCacheCallback;
  Compilers\Core\Portable\DiagnosticAnalyzer\AnalysisValueProvider.cs(25):            _valueCache = new ConditionalWeakTable<TKey, WrappedValue>();
  Compilers\Core\Portable\DiagnosticAnalyzer\AnalysisValueProvider.cs(26):            _valueCacheCallback = new ConditionalWeakTable<TKey, WrappedValue>.CreateValueCallback(ComputeValue);
  Compilers\Core\Portable\DiagnosticAnalyzer\AnalyzerManager.AnalyzerExecutionContext.cs(23):            private ConditionalWeakTable<Compilation, Dictionary<AnalyzerOptions, Task<HostCompilationStartAnalysisScope>>> _lazyCompilationScopeCache;
  Compilers\Core\Portable\DiagnosticAnalyzer\AnalyzerManager.AnalyzerExecutionContext.cs(66):                    _lazyCompilationScopeCache = _lazyCompilationScopeCache ?? new ConditionalWeakTable<Compilation, Dictionary<AnalyzerOptions, Task<HostCompilationStartAnalysisScope>>>();
  Compilers\Core\Portable\DiagnosticAnalyzer\AnalyzerManager.cs(28):        private readonly ConditionalWeakTable<DiagnosticAnalyzer, AnalyzerExecutionContext> _analyzerExecutionContextMap =
  Compilers\Core\Portable\DiagnosticAnalyzer\AnalyzerManager.cs(29):            new ConditionalWeakTable<DiagnosticAnalyzer, AnalyzerExecutionContext>();
  Dependencies\PooledObjects\ObjectPool`1.cs(65):        private static readonly ConditionalWeakTable<T, LeakTracker> leakTrackers = new ConditionalWeakTable<T, LeakTracker>();
  Compilers\Core\Portable\Syntax\GreenNode.cs(30):        private static readonly ConditionalWeakTable<GreenNode, DiagnosticInfo[]> s_diagnosticsTable =
  Compilers\Core\Portable\Syntax\GreenNode.cs(31):            new ConditionalWeakTable<GreenNode, DiagnosticInfo[]>();
  Compilers\Core\Portable\Syntax\GreenNode.cs(33):        private static readonly ConditionalWeakTable<GreenNode, SyntaxAnnotation[]> s_annotationsTable =
  Compilers\Core\Portable\Syntax\GreenNode.cs(34):            new ConditionalWeakTable<GreenNode, SyntaxAnnotation[]>();
  Compilers\Core\Portable\Syntax\SyntaxNodeExtensions_Tracking.cs(14):        private static readonly ConditionalWeakTable<SyntaxNode, SyntaxAnnotation> s_nodeToIdMap
  Compilers\Core\Portable\Syntax\SyntaxNodeExtensions_Tracking.cs(15):            = new ConditionalWeakTable<SyntaxNode, SyntaxAnnotation>();
  Compilers\Core\Portable\Syntax\SyntaxNodeExtensions_Tracking.cs(17):        private static readonly ConditionalWeakTable<SyntaxNode, CurrentNodes> s_rootToCurrentNodesMap
  Compilers\Core\Portable\Syntax\SyntaxNodeExtensions_Tracking.cs(18):            = new ConditionalWeakTable<SyntaxNode, CurrentNodes>();
  Compilers\CSharp\Portable\Syntax\InternalSyntax\CSharpSyntaxNode.cs(278):        private static readonly ConditionalWeakTable<SyntaxNode, Dictionary<CodeAnalysis.SyntaxTrivia, SyntaxNode>> s_structuresTable
  Compilers\CSharp\Portable\Syntax\InternalSyntax\CSharpSyntaxNode.cs(279):            = new ConditionalWeakTable<SyntaxNode, Dictionary<CodeAnalysis.SyntaxTrivia, SyntaxNode>>();
  Compilers\VisualBasic\Portable\Syntax\InternalSyntax\SyntaxNode.vb(224):        Private Shared ReadOnly s_structuresTable As New ConditionalWeakTable(Of SyntaxNode, Dictionary(Of Microsoft.CodeAnalysis.SyntaxTrivia, SyntaxNode))

**Comment by gafter** [comment]
The original issue described here has been addressed.
