### ISSUE TITLE
TestImplicitCacheMonitoring failed

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#9335]
http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/4576/testReport/junit/Microsoft.CodeAnalysis.Editor.UnitTests.Workspaces/ProjectCacheHostServiceFactoryTests/TestImplicitCacheMonitoring/

MESSAGE:
Assert.False() Failure\r\nExpected: False\r\nActual: True
+++++++++++++++++++
STACK TRACE:
at Microsoft.CodeAnalysis.Editor.UnitTests.Workspaces.ProjectCacheHostServiceFactoryTests.TestImplicitCacheMonitoring() in d:\j\workspace\roslyn_prtest---45fcf4bc\src\EditorFeatures\Test\Workspaces\ProjectCacheHostServiceFactoryTests.cs:line 139

**Comment by Pilchie** [comment]
Can you take a look at this?

**Comment by rchande** [comment]
This test passes most of the time, so I think the best strategy is probably to take a dump when it fails so we can see what's rooting the object. @jasonmalinowski will have a PR out soon that will let us dump the unit test process.

**Comment by rchande** [comment]
Logging has been added.
