### ISSUE TITLE
Break dependency on System.Runtime.Serialization.Json

### ISSUE THREAD

**Issue by weshaggard** [dotnet/roslyn#9338]
I'm investigating dependencies for .NET Core redist and noticed that the Roslyn libraries depend on System.Runtime.Serialization.Json (https://github.com/dotnet/roslyn/blob/0cee35cc375cf6a9c105b116eed776700b9f138e/src/Interactive/CsiCore/csi.rsp#L16) and the only place I see it used in the Roslyn libraries is at https://github.com/dotnet/roslyn/blob/fbae6b4d879149b42880fa2e7793ac85349f8ba8/src/Compilers/Core/Portable/InternalUtilities/JsonWriter.cs#L22. 

Based on the usage comment at https://github.com/dotnet/roslyn/blob/fbae6b4d879149b42880fa2e7793ac85349f8ba8/src/Compilers/Core/Portable/InternalUtilities/JsonWriter.cs#L97 we should consider removing this and implementing escaping locally. 

We should remove this as it does bring in a large dependency closure including System.Runtime.Serialization.Primitives, System.Runtime.Serialization.Json, System.Private.DataContractSerialization, System.Xml.XmlDocument, and System.Xml.XmlSerializer. About 1.2MB of dead weight for the usage scenario you are doing here.

**Comment by davidfowl** [comment]
+1!

**Comment by davkean** [comment]
What's a replacement in the .NET core redist?

**Comment by davkean** [comment]
Ah, I see, we're only using it for escaping - we're writing our own JSON.

**Comment by nguerrera** [comment]
@mavasani

**Comment by nguerrera** [comment]
I wanted to remove it (hence the comment, which is mine), but I didn't want to do it as part of the refactoring and risk regressing the bug fix that had brought in that dependency. We'll need good tests for escaping including surrogate pairs, etc. etc. 

https://github.com/dotnet/corefx/tree/master/src/System.Text.Encodings.Web might help here, but I suspsect I can't depend on that either though maybe I can borrow some source from there. Or perhaps the least risky thing would be to borrow the escaping logic straing from the JsonDataContractSerializer. 

Any opinions on other approaches or pointers to existing test cases I can reuse would be helpful.

**Comment by weshaggard** [comment]
@jaredpar we need this dependency broken otherwise we have to pull this closure into the shared framework which I would like to avoid.

**Comment by jaredpar** [comment]
@nguerrera this is currently assigned to you.  Will you have time to take care of this soon or do I need to assign it out?

**Comment by nguerrera** [comment]
I'll take a look ASAP.

**Comment by nguerrera** [comment]
@weshaggard @jaredpar Opened PR #9773 but have some TODOs noted before we should merge. What is the timeline for getting this merged. Is end-of-week OK?
