### ISSUE TITLE
Errors inside VB lambda expression in Visual Studio 2015 not recognized

### ISSUE THREAD

**Issue by changbowen** [dotnet/roslyn#9341]
Back in VS2013 the VB compiler seems to be able to recognize errors inside a lambda expression. While in VS2015 it just won't recognize the sub as a valid expression. This makes code writing much harder.
Some screenshots:

In VS2013:
[![Visual Studio 2013][1]][1]

In VS2015:
[![Visual Studio 2015][2]][2]

Looks like the problem only resides in VB compiler.
Feedback on connect.microsoft.com: [https://connect.microsoft.com/VisualStudio/feedback/details/2416478/errors-inside-vb-lambda-expression-in-visual-studio-2015](https://connect.microsoft.com/VisualStudio/feedback/details/2416478/errors-inside-vb-lambda-expression-in-visual-studio-2015)
  [1]: http://i.stack.imgur.com/c3Xgc.png
  [2]: http://i.stack.imgur.com/H4JQb.png

**Comment by changbowen** [comment]
will this be fixed in Update 3? :)

**Comment by heejaechang** [comment]
doesn't repro in dev15.

**Comment by changbowen** [comment]
@heejaechang I just tried on Microsoft Visual Studio Enterprise 2015 Version 14.0.25425.01 Update 3.
Same code as the screenshot above and it was exactly the same behavior as before. ("Invoke" is underlined instead of "some error").

**Comment by heejaechang** [comment]
can you give me repro solution? It tried and it didn’t repro.


-          heejae

**Comment by changbowen** [comment]
@heejaechang 
new project -> Visual Basic -> WPF Application, then create a sub in MainWindow.xaml.vb and insert these in the sub:
```
        Dispatcher.Invoke(
                    Sub()
                        Dim img As New BitmapImage
                        img.BeginInit("error here")
                        'some other codes
                    End Sub)
```
"error here" should be underlined (where the actual error is because BeginInit doesnt take any parameters) instead of "Invoke".
Any other errors inside the "invoke" wont get underlined also.

**Comment by heejaechang** [comment]
@jaredpar @dotnet/roslyn-compiler it looks like VB is binding Invoke to "Invoke(Func(Of TResult))" when sub() ... contains error. and containing about it couldn't infer what TResult is. which is fine I guess, but problem is it stops there and doesn't show error in Sub() ... itself.

I will give the bug to compiler team.

**Comment by heejaechang** [comment]
@changbowen thank you for the repro steps. looks like it didn't repro when I tried since I didn't actually use the Dispatcher but wrote up simple method that accepts delegate without any overloads. it repros with your repro which has multiple overloads for Invoke.

**Comment by changbowen** [comment]
@heejaechang Thanks! Happy to help :)

**Comment by gafter** [comment]
This is related to a category of problems we recently addressed in C#. See #11619.

**Comment by gafter** [comment]
See also #11722.

**Comment by AlekseyTs** [comment]
The Invoke actually takes Func(Of TResult). It is always an error to pass a Sub lambda as a corresponding argument and the type argument inference cannot succeed regardless whether there are errors inside the lambda or not.

**Comment by heejaechang** [comment]
but it also has overload that accepts action.

http://index/#WindowsBase/System/Windows/Threading/Dispatcher.cs,560

without error inside of the sub, it bound to right overload (Invoke with action as parameter).

**Comment by AlekseyTs** [comment]
Thank you, @heejaechang, I missed that because Source From Metadata doesn't put the Action overloads  close to Func overloadas.

**Comment by heejaechang** [comment]
FYI. without func overload, things work as expected (errors inside of sub reported)
