### ISSUE TITLE
Move to simplier method for turning on warning as error

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#9344]
@AArnott has a simpler method for turning on warning as error in builds rather than parsing the entire output, see: https://github.com/AArnott/pinvoke/commit/65f04e9ed8a00d73e40fdd0085d2c1426de78a21.

We should use it.

**Comment by jaredpar** [comment]
I think we still have to parse this file though.  The warnings have to be transformed into a form that Jenkins will flag as an error.

**Comment by davkean** [comment]
:+1:
