### ISSUE TITLE
Unify our CI builds between open and closed

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#9345]
Open and closed have different entry points for build, which leads to changes occuring on one side, but not the other. 

Open has CIBuild.cmd.
Closed has BuildAndTest.cmd.

We should unify the entry points and builds, so when we are doing the same thing (such as building, it's exactly the same on both sides).

**Comment by jcouv** [comment]
Is this still applicable?

**Comment by davkean** [comment]
I think it it isn't but I don't work in the Roslyn tree anymore so I'm not sure.

**Comment by jcouv** [comment]
@jaredpar @jasonmalinowski I'll close this since we don't have Closed repo anymore.
