### ISSUE TITLE
Add Using should work for extension methods even if other methods are in scope.

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#935]
Consider a programming referencing Roslyn binaries:

``` C#
using Microsoft.CodeAnalysis.CSharp;

class Program
{
    static void Main(string[] args)
    {
        var node = Microsoft.CodeAnalysis.CSharp.SyntaxFactory.ParseCompilationUnit("");

        node = node.NormalizeWhitespace();
    }
}
```

Place cursor on the line with the call to `NormalizeWhitespace()`.

*Result*
No lightbulb suggesting to add `using Microsoft.CodeAnalysis;`

*Expected*
There should be.

*Note*
This is happening because the `using Microsoft.CodeAnalysis.CSharp;` is pulling in another extension method named `NormalizeWhitespace()` which doesn't apply to this receiver type.

**Comment by dpoeschl** [comment]
See related internal TFS item #772321 that fixed a couple similar cases.

**Comment by jmarolf** [comment]
@Pilchie please verify.
