### ISSUE TITLE
Generate quick action does not offer to generate local function

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#9352]
In the future branch.

**Comment by Pilchie** [comment]
Didn't @agocke just file this again recently?

**Comment by agocke** [comment]
@Pilchie That was the lack of an extract-local-function-as-method refactoring. I assume this extract-region-as-local-function.

**Comment by CyrusNajmabadi** [comment]
This is def offered now:

![image](https://user-images.githubusercontent.com/4564579/217126945-845d53a1-b309-42f5-acdb-3f2266de81b9.png)
