### ISSUE TITLE
Introduce constants not available for auto prop initializer

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#936]
Ported from TFS WorkItem: **1130497**
<br>originally filed by @jeremymeng

------------------------------

**Repro Steps:**

<br> 1. paste the following code into a C# class<div><br></div><div>int prop4 { get; } = 1 + 2 + 3;</div><div><br></div><div>2. select 1 + 2 + 3</div><div>3. ctrl+[dot]</div><div><br></div><div><div>**Expected**:</div><div><br></div><div>options to generate constants in class</div><div><br></div><div>**Actual**:</div></div><div><br></div><div>no quick action available.</div>

------------------------------

**Revisions:**

1) Created By Jeremy Meng (2/26/2015 4:21:30 PM)

------------------------------

2) Edited By Kevin Pilch-Bisson (2/27/2015 7:52:03 AM)

Please port to github

------------------------------

**Comment by Pilchie** [comment]
We can add this in 1.1.
