### ISSUE TITLE
[Test Failure] Visual Studio Timed Out in prtest/win/vsi/p3 on PR #9353

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#9365]
PR: [#9353](https://github.com/dotnet/roslyn/pull/9353) *Pop up a dialog when we're unable to install/uninstall a nuget package.* by @CyrusNajmabadi
Failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p3/385/

**Issue 1: Visual Studio Timed Out**
Visual Studio Timed Out

Timeout when running CSharpWinforms.

**Comment by brettfo** [comment]
Pre-emptively closing this because we added some logging to the `stabilization` branch which will help diagnose this when it happens in the future and all we can do now is wait.  Fixed in PR dotnet/roslyn-internal#638.
