### ISSUE TITLE
Move Coby from manually configured jobs -> generated jobs

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#9377]
Coby are still using manually configured jobs. We should move them to fully generated jobs via groovy scripts to match the rest of the teams on Jenkins.

**Comment by davkean** [comment]
They are also using build-workflows, which we should figure out why and if can't just move them to normal jobs.

**Comment by davkean** [comment]
@mmitche fixed this.

**Comment by jasonmalinowski** [comment]
Going to close this until we reactivate that project.
