### ISSUE TITLE
NuGet packages have dependencies on packages that aren't on NuGet

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#9381]
[Microsoft.CodeAnalysis.Common](http://www.nuget.org/packages/Microsoft.CodeAnalysis.Common/1.2.0-beta1-20160202-02) has a dependency on package, System.Reflection.Metadata 1.2.0-rc3-23721, that does not exist on NuGet

**Comment by jaredpar** [comment]
@agocke is this an issue that you've already fixed?

**Comment by agocke** [comment]
This has been resolved. M.C.C has a dependency in `-rc` on System.Reflection.Metadata 1.2.0-rc3-23811, which has been uploaded to NuGet.

**Comment by agocke** [comment]
Note: stabilization has a dependency on `-rc2-23826`, which is also on NuGet.
