### ISSUE TITLE
Simplified build optimizes binary when debugging Unit Tests

### ISSUE THREAD

**Issue by Andrew-MSFT** [dotnet/roslyn#9382]
**Version Used**: VS 2015 Update 1

**Steps to Reproduce**:
1. Turn on simplified build (turn off "Show advanced build configurations" in Tools -> Options)
2. Create a VB console application
3. Add a unit test project and put a breakpoint in the generated test
4. Right click on the test in the test explorer and choose debug

**Expected Behavior**:
Breakpoint is hit

**Actual Behavior**:
Breakpoint will not be hit because the test is built with optimizations enabled.  In a normal application the app is built without optimizations for debugging, however this logic isn't translating to unit tests.

Note: There is a separate issue with one default setting in the VB profile that results in silent failure if the user is using the VB profile as reported in https://github.com/dotnet/roslyn/issues/9383

**Comment by Pilchie** [comment]
Can you take a look and help route?  If you "F5", it is supposed to do an implicit config switch back to debug for the build portion.  Maybe the UnitTest code needs to do something similar?

**Comment by 0ndrej** [comment]
This issue is still present in Visual Studio 2017!!! You did not touched this since it was reported more than year ago!

**Comment by dpoeschl** [comment]
@Pilchie @jasonmalinowski Can you help me understand why this is an IDE bug?

**Comment by jasonmalinowski** [comment]
@dpoeschl I don't think it's an IDE bug, @Pilchie just wanted me to route. Could be a test team bug or project system bug...not sure.

**Comment by dpoeschl** [comment]
@davkean Can you help us route this issue? See Jason's comment above. Thanks!

**Comment by 0ndrej** [comment]
You set some option in IDE, you set breakpoint in IDE, no breakpoint is hit in IDE. What category of bug is this? If you need more info I will do whatever is needed to fix that.

**Comment by davkean** [comment]
This issue was moved to dotnet/project-system#2993
