### ISSUE TITLE
Change VB profile to enable "Warn if no user code on launch" by default

### ISSUE THREAD

**Issue by AndrewBrianHall** [dotnet/roslyn#9383]
In VS 2015 the debugger turned off the option to suppress JIT optimizations by default when debugging managed code.  If the user attempts to debug something where any project in their solution is optimized and Just My Code is enabled (meaning symbols won't load) we warn the user if "Warn if no user code on launch" is enabled. 

However, the VB profile has this off by default, meaning users who find themselves in this situation are encountering a silent failure.  The action dialog that appears gives the user the option to turn it off, so VS should have it on by default so they don't get silent failures like with issue https://github.com/dotnet/roslyn/issues/9382

**Comment by AnthonyDGreen** [comment]
Any history on why this setting is off on VB? If we turn this on is there another experience we're breaking? Would any design-time expression evaluator scenarios hit this?

**Comment by CyrusNajmabadi** [comment]
Closing as we are not changing these vb experiences.
