### ISSUE TITLE
Package downgrade warning in master build

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#9387]
http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p2/404/consoleFull

`WARNING: Detected package downgrade: System.Reflection.Metadata from 1.2.0-rc3-23811 to 1.2.0-rc2-23826`

**Comment by amcasey** [comment]
FYI @tmat @davkean

**Comment by tmat** [comment]
We can't find a merge in Open that corresponds to a merge in Internal: https://github.com/dotnet/roslyn-internal/commit/b3033a8465b57236a394366bd1947f0bd389c08d

**Comment by tmat** [comment]
@drognanar

**Comment by tmat** [comment]
Seems like change dotnet/roslyn-internal@b3033a8 should be reverted.

**Comment by davkean** [comment]
Agreed, however, given on Windows we now only use NuGet restore, we should just delete project.lock.json.

**Comment by davkean** [comment]
Hmm, but that commit only touches project.lock.json, restore will overwrite them - so it's project.json that's probably incorrect.

**Comment by tmat** [comment]
There is a change in Closed/EnC/CSharp/Test/project.json as well

**Comment by davkean** [comment]
@tmat Should the tree be build against RC2 or RC3 of metadata?

**Comment by tmat** [comment]
RC2 in stabilization. RC3 was in master. The change to RC2 should be integrated to master in both open and closed at once.

**Comment by davkean** [comment]
How is this supposed to work on the VS insertion side? How are we supposed to know to roll back metadata? Are we supposed to always update it?

**Comment by tmat** [comment]
Let's take it offline. I'll stop by later.

**Comment by davkean** [comment]
This has been resolved
