### ISSUE TITLE
Test Failure: CSharpReplClassification.1) Verify color of some tokens (from (empty))

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#9392]
http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p3/393/

**Comment by amcasey** [comment]
`Command Edit.SelectionCancel was not available after retrying for a timeout of 60000ms`

If the run didn't include https://github.com/dotnet/roslyn/commit/91046030f19a8e8ff5efd5d6b9d768374c6f0023, then this failure is expected.

**Comment by amcasey** [comment]
The PR for my fix was run 39**2**, so 393 almost certainly didn't have the fix.  All subsequent runs have passed (394-397).

**Comment by amcasey** [comment]
FWIW, the original bug was https://github.com/dotnet/roslyn/issues/9354.
