### ISSUE TITLE
[Test Failure] Test Failures in prtest/win/dbg/unit32 on PR #9389

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#9394]
PR: [#9389](https://github.com/dotnet/roslyn/pull/9389) *Fix issue where we weren't offering 'generate variable'* by @CyrusNajmabadi
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/4700/

**1 Test Failures:**
Microsoft.CodeAnalysis.Editor.UnitTests.FindReferences.FindReferencesTests.TestNamedType_CaseSensitivity

**Issue 1: Test Failures**
There were test failures, see Test Results above.

Looks to be another case where something is going wrong in a P2P VB/C# project.

**Comment by CyrusNajmabadi** [comment]
Tagging @jasonmalinowski and @jmarolf who were looking at flakeyness like this.

**Comment by jasonmalinowski** [comment]
Yep, this is another case where cross-language find references didn't work. Duping against parent bug #9308.
