### ISSUE TITLE
Intellisense suggests an overridden property twice when used as attribute argument

### ISSUE THREAD

**Issue by Vannevelj** [dotnet/roslyn#9398]
**Version Used**: 
VS2015 Update 1

**Steps to Reproduce**:

1. Create new solution
2. Add the following attribute definitions:

	```csharp
	class BaseAttribute : Attribute
	{
		public virtual string Name { get; set; }
	}
	
	class DerivedAttribute : BaseAttribute
	{
		public override string Name { get; set; }
	}
	```

3. Add `[Derived()]` attribute to something

4. Place caret inside the empty brackets and press <kbd>ctrl</kbd> + <kbd>space</kbd>

**Expected Behavior**:

The `Name` property shows up once.

**Actual Behavior**:

The `Name` property shows up twice.

![image](https://cloud.githubusercontent.com/assets/2777107/13463401/5aa93a18-e08c-11e5-9200-aa361d3aead8.png)

**Comments**

This was inspired by [a bug report on Stackoverflow](http://stackoverflow.com/q/35532304/1864167) but I wasn't able to reproduce his exact scenario since my hover popup doesn't look the same. I'm not sure if that's something on his or my side.

**Comment by Vannevelj** [comment]
Turns out it was because of Resharper so this is something for them to fix.

**Comment by roydukkey** [comment]
@Vannevelj This is still happening for me as described in the SO post. Here is my [VS environment info](https://gist.github.com/roydukkey/67ef3cc4e65b915a91c14310e828066e).

**Comment by Vannevelj** [comment]
@roydukkey since I couldn't replicate it myself it might be best if you create a new issue with your information
