### ISSUE TITLE
Intellisense shouldn't suggest a property already used as an attribute argument

### ISSUE THREAD

**Issue by Vannevelj** [dotnet/roslyn#9399]
**Version Used**: 
VS2015 Update 1

**Steps to Reproduce**:

1. Create a new solution
2. Add the following attribute definition:

	```csharp
	class MyAttribute : Attribute
	{
	    public string Name { get; set; }
	    public int Age { get; set; }
	}
	```

3. Use the attribute somewhere

	```csharp
	[My(Name = "test")]
	class Program
	```

4. Add a comma behind `"test"` and press <kbd>ctrl</kbd> + <kbd>space</kbd>

**Expected Behavior**:

Only `Age` shows up.

**Actual Behavior**:

Both `Name` and `Age` show up.

![image](https://cloud.githubusercontent.com/assets/2777107/13463710/e6a2fdf0-e08d-11e5-922a-44429e510831.png)

**Comments:**

I don't think `Name` belongs there again since that would just create a compilation error. This issue is related to #9398

**Comment by Pilchie** [comment]
Does this repro without Resharper?  They provide their own CompletionList that replaces ours.

**Comment by Vannevelj** [comment]
Huh. It's been so long since I haven't used Resharper that I thought this was the normal completion list. You're right, without Resharper it works. Then I guess this and my other issue can be discarded.
