### ISSUE TITLE
Easier way to create on-line help for analyzers

### ISSUE THREAD

**Issue by KathleenDollard** [dotnet/roslyn#94]
The MSDN help for FxCop rules is _extremely_ helpful. It should be easier to create similar help for analyzers. See https://msdn.microsoft.com/library/ms182363.aspx

Creating similar pages and keeping them up to date is going to be a real pain for community analyzers. This seems unnecessary since much of the information is available in the analyzer and much of the remainder could be considered valuable to be stored in the analyzer. This would allow a "one stop shop" for creating both analyzers and default documentation for them. 

If there is helplink or no page found, use information from the analyzer to create the following display (possibly through a webservice):
- A block similar to the top of the MSDN pages that includes the basic information from the analyzer
- Include in this block default severity and enabling
- If there are fixes available, at least their names and descriptions listed
- Cause: anticipate new overload for DiagnosticDescriptor constructor or well known custom tags
- Description: from DiagnosticDescriptor constructor)
- How to Fix and When to Suppress: anticipate new overload for DiagnosticDescriptor constructor or well known custom tags
- A standard test format that allows use of test code for Examples - both violating (DiagnosticResult != null) and not-violating (DiagnosticResult == null) inside the test.
- Assuming the preceding test format is one set of sample code per test, an attribute on the test that would allow comments on that particular example
- Do a moderate level of diffing to ensure that multiple tests on the same code (such as to ensure correct location for squiggles) do not result in redundant examples. Probably also have an attribute to skip a test or identify prototypes for examples. 

Note that the above 3 suggestions would result in text/code, text/code

**Comment by CyrusNajmabadi** [comment]
@mavasani do we need to do anything here?  I thought we had pages already for our analyzers.  Can this be closed out?

**Comment by mavasani** [comment]
Yes, we already have well defined templates and documentation on how to create doc pages for our CA and IDE first part analyzers. I believe this feature request is towards adding some support to help third party analyzers, but I am not sure what can/should be done here. They should be able to clone the md file and format for our existing analyzer doc pages.
