### ISSUE TITLE
Remove trailing space after <enter> between arguments (etc.)

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#940]
Inspired by all of the trailing spaces that were removed by the CodeFormatter in #933
1. Paste C#:

``` C#
class C
{
    void M(string a, string b)
    {
        M("Dog", "Cat");
    }
}
```
1. Place the caret before `"Cat"` and press enter

**Expected**: The "Cat" argument is moved to the next line and the previous line's trailing space is removed.
**Actual**: The trailing space is left on the previous line.

Dev12 had the same behavior, so this is _not_ a regression.

**Comment by alexsorokoletov** [comment]
> would be somewhere in Workspaces\CSharpWorkspaces\Formatting\Rules
@Pilchie

**Comment by Pilchie** [comment]
There is an existing .editorconfig rule for this.  We should look at obeying it.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback on this.  We also just have the formatting anlayzer/fixer which can address tehse.
