### ISSUE TITLE
BasicVenus: Command Edit.Undo was not available after retrying for a timeout of 60000ms

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#9409]
http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_vsi_p1/157/artifact/Open/Binaries/Release/VSIntegrationTestLogs/BasicVenus.html

`Scenario: Bug 531271: Line commit shouldn't crash doing undo/redo`

**Comment by brettfo** [comment]
Added logging in dotnet/roslyn-internal#679.
