### ISSUE TITLE
future-stabilization is producing binaries with the wrong version number

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#9414]
Actual: 1.3.0-beta1
Expected: 2.0.0-beta1 (as in future)

**Comment by amcasey** [comment]
FYI @davkean

**Comment by davkean** [comment]
tag @agocke.

**Comment by agocke** [comment]
The NuGet package versions are just based off the Roslyn semantic version. Do the binaries somehow have the right assembly versions?

**Comment by agocke** [comment]
Just checked -- yeah the problem here is much more serious. The binaries are version 1.3. Most likely a bad merge. Re-assigning to infrastructure.

**Comment by tannergooding** [comment]
This ended up being an issue with the signed build definition. It has since been resolved.
