### ISSUE TITLE
Infra: screenshots and test output logs are missing from Integration runs.

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#9415]
crux of the issue is the artifacts directory is missing the following 2 subdirectories:
- Open\Binaries\Debug\Screenshots\
- Open\Binaries\Debug\ETAIntegrationTestLogs\

Both of these are necessary for investigating IDE test failures, as they capture screenshots of the process when the failure occurred and the detailed logs themselves. Per @davkean, we filter files by extension and we might be skipping `.png` and `.txt` et al.

**_Example:_**

See failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/4637/consoleFull#170218456861aefe2b-268e-4e71-8c03-11b4c0acbfbc
talks about finding screenshots and logs in the above mentioned directories.

But also see http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/4637/artifact/Open/Binaries/Debug/ does not have those sub directories.

also note that this is not the, we delete artifacts after a certain period of time issue.

/cc: @davkean @dotnet/roslyn-infrastructure

**Comment by balajikris** [comment]
also note that the corresponding location for VS runs would be `Debug\VSIntegrationTestLogs` or so.

**Comment by CyrusNajmabadi** [comment]
PR for tihs here: 
https://github.com/dotnet/roslyn-internal/pull/636
https://github.com/dotnet/roslyn-internal/pull/632

**Comment by jasonmalinowski** [comment]
This has been working for awhile.
