### ISSUE TITLE
Crash in SimpleCodeStyleOption.FromXElement

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#9418]
```C#
        public static SimpleCodeStyleOption FromXElement(XElement element)
        {
            var isChecked = bool.Parse(element.Attribute(nameof(IsChecked)).Value);
            var severity = (DiagnosticSeverity)Enum.Parse(typeof(DiagnosticSeverity), element.Attribute(nameof(DiagnosticSeverity)).Value);
            NotificationOption notificationOption;

            switch (severity)
            {
                case DiagnosticSeverity.Hidden:
                    notificationOption = NotificationOption.None;
```
There is a bug in the first line when `element.Attribute("IsChecked")` is null; it throws a `NullReferenceException`.

**Comment by balajikris** [comment]
when this would happen. that the xelement retreived from persisted storage does not have the element type i'm looking for? 
theory: when there is nothing from persisted storage.. clean hives and starting VS for the first time ?

**Comment by gafter** [comment]
See dump in `\\mlangfs1\public\ngafter\9418.dmp`

**Comment by balajikris** [comment]
just a fallout from changing serialization format #9337 . won't happen on boxes that didn't have old data. and in the future, we can check serialization version which was encoded in #9337. All said, I'm still putting in a guard, just to protect against possibly corrupt data.

**Comment by Pilchie** [comment]
This was fixed in #9423.

**Comment by balajikris** [comment]
ha, `fixes #id` syntax in a PR didn't seem to close the bug automatically..

**Comment by Pilchie** [comment]
Only if it's merged into master (or in general, the repo's default branch).
