### ISSUE TITLE
Codestyle tools options parent node reads 'An error occurred loading this property page' when opening it.

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#9421]
**Version Used**: 
Latest `future` branch

**Steps to Reproduce**:

1. build locally, open VS
2. open new C# project
3. tools - options - text editor - C# - codestyle
4. The root node for codestyles seems to be busted, whereas its child nodes all seem to be okay..

**Actual Behavior**:

![image](https://cloud.githubusercontent.com/assets/4213867/13478593/981b198a-e086-11e5-84e2-8dc66149f645.png)

![image](https://cloud.githubusercontent.com/assets/4213867/13478619/abc99222-e086-11e5-8c4f-f5d35bd60b7f.png)

**Comment by balajikris** [comment]
@dpoeschl -- I think you'd know something about this, since you restructured this sub-tree?

**Comment by dpoeschl** [comment]
@balajikris Yeah, I suspect this happens when you have Update 1 or prior in Program Files, with future installed into your hive. If we care about this scenario (temporarily), then we should see if it can be remedied with some guid alterations in csharppackage. This could possibly make the "error occurred" messages go away, but you'd still have the duplicate Formatting node. Alternatively I could publish instructions on how to "fix" the programfiles Roslyn to not interfere with the hive's option pages...

**Comment by balajikris** [comment]
> when you have Update 1 or prior in Program Files, with future installed into your hive

ooh that. thanks for clarifying. If that's what is going on here, I don't think I care, personally. However, it may be useful to publish instructions as we may keep running into this while we're also actively working with the options page.

**Comment by DustinCampbell** [comment]
Resolving as won't fix. Could you validate that this works right on a clean machine?

**Comment by dpoeschl** [comment]
@balajikris For testing this out on a machine with VS 2015 Update 1 or prior installed:

1. Navigate to `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\Roslyn\Language Services`
2. Make backup copies of `Microsoft.VisualStudio.LanguageService.CSharp.pkgdef` and `Microsoft.VisualStudio.LanguageServices.VisualBasic.pkgdef`
3. In both of the `Microsoft.VisualStudio.LanguageService.*.pkgdef` files, delete all entries with `EditorToolsOptions` in the path.
    i. All entries in these .pkgdef files are of the form 
    ```
    [path]
    key1=value1
    ...
    keyN=valueN
    ```
    ii. Be careful not to delete extra entries, not all entries have the same number of key/value pairs (in C#, it's easy to accidentally delete the `$RootKey$\Languages\File Extensions\.cs` entry.

4. Run `devenv /updateconfiguration`

**Comment by balajikris** [comment]
verified that the above instructions fix the problem and that the problem resurfaces if the fix is rolled back.
