### ISSUE TITLE
PreciseAbstractFlowPass doesn't override visit for BoundMatchCase and BoundConstantPattern nodes

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#9422]
If the visit methods can be called, they should be overridden and should visit constituent BoundExpressions as appropriate (either as a condition or as an RValue). Failing to properly visit constituent BoundExpressions can result in a NullReferenceExpression because we might run into conditional state when we don't expect to be in a conditional state.

If we don't expect the visit methods to be ever called, I suggest to still override them in this fashion:
```
        public sealed override BoundNode VisitMatchCase(BoundMatchCase node)
        {
            // Should be handled by VisitMatchExpression
            throw ExceptionUtilities.Unreachable;
        }

        public sealed override BoundNode VisitConstantPattern(BoundConstantPattern node)
        {
            // Should be handled by VisitPattern.
            // There is no reason to visit BoundConstantPattern.Value at the moment because it 
            // is supposed to be a constant.
            throw ExceptionUtilities.Unreachable;
        }
```

**Comment by gafter** [comment]
Closed by #12250
