### ISSUE TITLE
Creating an InterpolatedStringTextToken via C# Syntax API

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#9424]
I'm continuing to update Roslyn Quoter (http://roslynquoter.azurewebsites.net) and ran into some difficulties generating code that creates $"" string literals.

What code should Roslyn Quoter generate to produce C# code such as $"a", $@"b", $"c{foo}", etc?

I don't see SyntaxFactory.InterpolatedStringTextToken() for C# (although there seems to be one for VB).

Could it be another case where the parser can create it, but it's impossible to create identical tree using the public Syntax API? Or I'm just missing something?

**Comment by AnthonyDGreen** [comment]
I believe you can just call SyntaxFactory.Token(SyntaxTriviaList, SyntaxKind, String, String, SyntaxTriviaList) method.

**Comment by KirillOsenkov** [comment]
Yes, this seems to work:

    InterpolatedStringExpression(
                                        Token(SyntaxKind.InterpolatedStringStartToken))
                                    .WithContents(
                                        SingletonList<InterpolatedStringContentSyntax>(
                                            InterpolatedStringText()
                                            .WithTextToken(
                                                Token(
                                                    TriviaList(),
                                                    SyntaxKind.InterpolatedStringTextToken,
                                                    "a",
                                                    "a",
                                                    TriviaList()))))

It may or may not be more intuitive to have a more special API for this case though. You decide.
