### ISSUE TITLE
try/catch does not stay on single line

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#9425]
Following #2837, Update 2 CTP (25008).

EDIT: To reproduce, there must be further code after the block.

Settings to reproduce:
C# > Formatting > Wrapping > Leave block on single line `on` (on by default)
C# > Automatic brace completion `off` (newly on by default)

```C#
try { }
catch { continue|

int a;
```
gets wrapped as
```C#
try { }
catch {
    continue;

int a;
```
(the same with `break;` `return;` etc. and finally block)

With _Leave block on single line_ on, expected behaviour is to keep it on single line:
```C#
try { }
catch { continue;|

int a;
```

**Comment by DustinCampbell** [comment]
This looks like more fall out of the change to format in the presence of parse errors in VS 2015.

**Comment by miloush** [comment]
So it is actually relevant to #2837. It's the same for if/else blocks.

**Comment by CyrusNajmabadi** [comment]
I can't repro this: 

![trycatchformatting](https://cloud.githubusercontent.com/assets/4564579/14126451/f63f7e1c-f5c5-11e5-8215-4a8b74e44baa.gif)

**Comment by CyrusNajmabadi** [comment]
I can't repro this:

![trycatchformatting1](https://cloud.githubusercontent.com/assets/4564579/14126604/0348ec00-f5c7-11e5-8e25-08e135db2481.gif)

**Comment by bbarry** [comment]
I think the test case is requiring a statement already on the line after the continue, like pasting this method and formatting as necessary then adding the `;` after continue.

    public void Test(IEnumerable a) {
        foreach (var x in a) {
            try {}
            catch { continue
            x.ToString();
        }
    }

**Comment by CyrusNajmabadi** [comment]
Ah thanks.  That did it.  Investigating now.

**Comment by CyrusNajmabadi** [comment]
Ah.  I think it's clear what the problem likely is.  From the perspective of the parser you have a catch block with *two* statements in it.  After all, "continue;" and "x.ToString();" are both statements in that block.  And hte block is completely closed (since there is a matching "}").  As such, the "leave on single line" rule doesn't apply since your block is not on a single line.

Fixing this may be tricky.  Will see what i can do.
