### ISSUE TITLE
(Pref?) A Rolling Cache.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#943]
Could the Scanner benefit from a "rolling cache" to speed up the looking up characters?

```nemerle
class TinyCache
{
  var cache : new TinyDict();

  GetChar( at : int ) : Char 
  {
    char c;
    if( cache.Has(at,c) ){ return c; }
    c = Peek(at); /* Look up in the actual source */
    cache.Add(at,c);
    return c;
  }
}

class TinyDict
{
  var i = 0;
  var cs[8] : char;
  var at[8] : int; 

  public Add( k : int, v : char)
  {
    var ki = Pos(k);
    if( ki >=0 )
    {
      at[ki] = k; cs[ki] = v;
    }
    else
    { 
      at[i] = k; cs[i] = v;
      i = if(i==7,0,i+1);      
    } 
  }

  private Pos( k : int )
  {
    x = 0;
    while( x< 8)
    {
      if( at[x] == k ) { return x; }
      x+=1
    }
    return -1;
  } 

  public Has( k : int, ref c : char) : boolean
  {
    x = 0;
    while( x < 8 )
    {
      if( at[x] == k )
      {
        c = cs[x];
        return true;
      }
      x+=1;
    }
    return false;
  }
}
```

It could help in the situations where the scanner checks against the same index,
I've choose a size of 8 characters as that (as far as I can tell) is the most that is peek at.

eg [here](https://github.com/dotnet/roslyn/blob/master/src/Compilers/VisualBasic/Portable/Scanner/ScannerXml.vb#L127)

**Comment by gafter** [comment]
@AdamSpeight2008 What is the performance impact of your change? Does is pass the build-and-test?

**Comment by AdamSpeight2008** [comment]
@gafter Don't know yet, as I currently don't have a working installation of VS

**Comment by AdamSpeight2008** [comment]
There is some potential gains as the scanner doesn't need to do multiple lookups of the same indexed / offset character.

**Comment by mikedn** [comment]
But it's not like those lookups involve database or web service calls, the characters are simply retrieved from a character array. What makes you think that a cache that uses linear search will provide any gains over directly accessing the required char element?

Large look ahead cases like the one you link to would probably be better served by something like `PeekAheadString(3, "CDATA[")`, a single method call instead of 7.

**Comment by gafter** [comment]
Closing for now, as we have no plans to act on it. If you have evidence that this works, passes tests, and has some benefit, please reopen and submit a pull request.
