### ISSUE TITLE
All Integration Tests fail with RPC error.

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#9445]
Currently on `dci-win-rbld-6` (currently offline so @dotnet/roslyn-infrastructure can investigate further), attempting to run the integration tests causes all of them to fail with an RPC error.

The issue can be fixed by manually running `devenv.exe /rootSuffix RoslynDev`; however, the issue needs to be further debugged so we understand what is causing `StartTargetAction` to fail.

**Comment by davkean** [comment]
We've had to take RBLD-3 offline as well: http://dotnet-ci.cloudapp.net/computer/dci-win-rbld-3/

**Comment by davkean** [comment]
Ty, when things calm down tomorrow can you take a look?

**Comment by TyOverby** [comment]
do we have any logs for this failure?

**Comment by davkean** [comment]
Look back through the failed VSI runs.

**Comment by davkean** [comment]
How are we going with this? Are we making progress?

**Comment by tannergooding** [comment]
A temporary workaround, which should bring the machines back online (which should be the highest priority). The actual issue appears to be MEF related, but there is not a machine available on which to repro the issue anymore (as opening VS resolves the issue, which is what was done to debug the test... WinDbg will need to be used if the issue occurs again).

However, if the issue is indeed a MEF bug, then even once it is fixed, we will not be able to consume the fix until it is included with a shipped version of Visual Studio.

**Comment by davkean** [comment]
No, MEF cache issues are the one the number reason our package crashes in VS. Do not bring the machines back online until we have figured out the crash. Pull in Alex if you're having trouble figuring it out.

**Comment by davkean** [comment]
I investigated this. Both were caused by Test Impact extension being deployed to the RoslynDev hive with different dependencies. 

Sigh. 

These were supposed to be cleaned @tannergooding, what happened?

**Comment by tannergooding** [comment]
They were cleaned. Its likely that a stale job or PR ended up running on the machine after hand though.
