### ISSUE TITLE
Add a determinism PR job that can be triggered

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#9451]
There's no way to trigger determinism via a PR, we should add one, but not turn it on by default:

- [ ] Add determinism PR job via https://github.com/dotnet/roslyn/blob/master/netci.groovy
- [ ] Update stashpop defaults to list it as a available job

**Comment by jasonmalinowski** [comment]
@jaredpar, wasn't this done?

**Comment by jaredpar** [comment]
The first part was.  You can trigger a determinism check with 

> test determinism please

The latter though was not.

**Comment by jasonmalinowski** [comment]
Closing, although I'm not sure if stashpop was updated. @dpoeschl would know if it was. (Not sure this is worth the backlog entry for just that.)
