### ISSUE TITLE
Allow throw expression on right of && and ||

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#9453]
The LDM requested the following change to `throw-expression` in the [spec](https://github.com/dotnet/roslyn/blob/future/docs/features/patterns.md) and implementation:

Add to the contexts in which it is allowed:
- the right-hand side of `&&` and `||`
- the target of an explicit cast

Note that the current spec *already supports* a throw expression as the body of an expression-bodied lambda or method (and always has). I just forgot about that when we were discussing it recently.

The work for this issue is to fix the spec and prototype.

/cc @jaredpar @MadsTorgersen

**Comment by leppie** [comment]
So will `throw` always be considered a an expression now? Is the 'assumed' type anything?

**Comment by svick** [comment]
Is this just for consistency, or is there actually a situation where you would want to write `|| throw Exception()`?

It sounds very similar to the `or die()` idiom from PHP, but I don't think it would be actually usable that way, since `||` is not allowed as statement expression.

**Comment by gafter** [comment]
The precedence for this doesn't work out very well, so classifying it as a language design issue.

**Comment by alrz** [comment]
I still think that `break`, `return` and `continue` should also be permitted as an expression,
```cs
foreach (var item in list) {
  var result = item match {
    case P1(var value): value,
    case P2(*): break;
    default: continue,
  };
}
```
Otherwise, it hampers usefulness of the `match` expression.

**Comment by gafter** [comment]
The LDM discussed this (initiated with the enclosed emails), and concluded

> We are ok not trying to deal with these code locations for now. We don’t have good scenarios and they are problematic to implement.

> We know that there is value in the original code locations proposed: Ternary operator (`?:`), null-coalescing operator (`??`) and as an expression body (after `=>`). We'll just stick with those. If good scenarios show up later, we can consider extending then. Right now we are in shutdown mode, and this feels like the right kind of thing not to spend our cycles on.

-----------------
From: Neal Gafter 
Sent: Wednesday, September 7, 2016 1:57 PM
To: C# Language Design Team
Cc: Neal Gafter
Subject: e && throw

Back in March the LDM reviewed the specification of the throw expression

https://github.com/dotnet/roslyn/blob/features/throwexpr/docs/features/throwexpr.md

and, for consistency, requested that we also **allow a throw expression on the right-hand-side of && and ||**.

https://github.com/dotnet/roslyn/issues/9453

Now that I’m looking at it, I have a problem expressing this in the language specification (grammar), and corresponding problems in the implementation.

The problem is that `&&` binds tighter than `??`, but `??` is allowed as an argument to a throw expression. Consequently, there would be a precedence inversion, and the following

`A && throw B ?? C`

Would be ambiguous, as it can be parsed either as

1.	`(A && throw B) ?? C`
2.	`A && throw (B ?? C)`

This isn’t fatal; there are a number of approaches we could use to address this ranging from waving our hands in English text surrounding the grammar, to having multiple productions for throw expressions at different precedence levels.

However, I haven’t been able to find any compelling use cases. Every time I thought I had come up with one, it fell apart in details. In all of the cases, using `?:` would have been a better expression in the context of the code than throw on the right-hand-side of `&&` or `||`.

Before investing any more effort in solving this “problem”, do any of you have a compelling use case for this? If not, I’d prefer to reject the proposal and say we just won’t support throw on the right-hand-side of `&&` and `||`.

----------------------------------
From: Neal Gafter 
Sent: Wednesday, September 7, 2016 2:02 PM
To: C# Language Design Team
Cc: Neal Gafter
Subject: RE: `e && throw`

Oh yes, there was also a request to allow throw as the target of a cast. That would require yet another precedence level to address a large category of ambiguities such as

`(Type)throw e ?? e;`

Which could be read as either

1.	`((Type)throw e) ?? e;`
2.	`(Type)throw (e ?? e);`

It would also introduce semantic problems because casts are allowed in many contexts.

`M(e1, (Type)throw e2, e3); // allowed?`

If we have no use cases for this, I’d like to reject it too.

Cheers,
Neal
