### ISSUE TITLE
Analyzer DiagnosticSeverity level for QuickInfo only?

### ISSUE THREAD

**Issue by steffenloesch** [dotnet/roslyn#9458]
Is there are way to set the DiagnosticSeverity level of an Analyzer rule, in a way that in Visual Studio a diagnostic is only shown on the mouse-over QuickInfo, but not with a squiggle and not in the Error List window? I'd like to (ab-) use Analyzers to show some additional information in the QuickInfo for certain language constructs.

DiagnosticSeverity.Info gives Error List information, but no mouse-over QuickInfo. DiagnosticSeverity.Warning gives both, and also a squiggle. What I want is only QuickInfo with no squiggle and no Error List entry. Is there a way to make that work with Analyzers, or do I need to write a separate Visual Studio Extension for that?

**Comment by srivatsn** [comment]
Currently there's no way to do this. We've talked about offering some extensibility to customize the presentation of a diagnostic through an extension and if we had you could mark the diagnostic as Hidden and provide the tooltip. https://github.com/dotnet/roslyn/issues/1224 tracks that work.
