### ISSUE TITLE
 CSharpLinkedFile.xml is failing on the future-stabilization branch

### ISSUE THREAD

**Issue by TyOverby** [dotnet/roslyn#9460]
http://dotnet-ci.cloudapp.net/job/roslyn-internal_future-stabilization_win_vsi_p2/4/console

**Comment by dpoeschl** [comment]
No build artifacts. :crying_cat_face:

**Comment by dpoeschl** [comment]
Please reopen the next time this happens and we have build artifacts. For now I don't see anything actionable in just the log.

**Comment by davkean** [comment]
We hit this again: https://github.com/dotnet/roslyn/issues/9602.

**Comment by davkean** [comment]
Dupe of https://github.com/dotnet/roslyn/issues/9602
