### ISSUE TITLE
Expose IsAssignableTo from SemanticModel

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn#9461]
This is used by two analyzers and about to be used by a third one. Because it is implemented differently in C# and VB, you can't just make a helper method out of it in Analyzer.Utilities. Rather, each analyzer that needs it needs to have a base class that does almost all the work, and then C# and VB derived classes whose only purpose is to copy the implementation of IsAssignableTo from Roslyn.

**Comment by gafter** [comment]
`SemanticModel` doesn't have a method `IsAssignableTo`. I'm not sure what the spec would be for the API you're requesting. What specific problem are you trying to solve? Are you trying to determine if there is an implicit conversion between two types? Do you intend that should include user-defined conversions? Or are you only interested in implicit standard reference conversions (to use the C# terminology) to check for an inheritance relationship?

**Comment by lgolding** [comment]
Here's the problem being solved: Take a look at the following two analyzers in the roslyn-analyzers repo:
* `DefineAccessorsForAttributeArguments`
* `UseGenericEventHandlerInstances`

Both of them need to decide if the type of one symbol is "assignable to" the type of another symbol, where the semantics of "assignable to" are "**has implicit conversion to**". For example, `UseGenericEventHandlerInstances` checks to see if the type argument to an instantiation of  ``System.EventHandler`1`` is assignable to `System.EventArgs`.

As the Roslyn API stands, the only way to find out is to call a language-specific method on the `Compilation` object:

C#:
```C#
((CSharpCompilation)compilation).ClassifyConversion(fromSymbol, toSymbol).IsImplicit
```
VB:
```VB
DirectCast(compilation, VisualBasicCompilation).ClassifyConversion(fromSymbol, toSymbol).IsWidening
```

That means that these two analyzers, which would otherwise be language-independent, must be written as abstract base classes, and their derived classes (for example, `CSharpUseGenericEventHandlerInstances` and `BasicUseGenericEventHandlerInstances`) must implement the language-specific logic.

At the time I opened this issue, I was writing a third analyzer that I thought would need the same logic, but it turned out that I didn't need it for that analyzer.

**Comment by lgolding** [comment]
I don't care if the proposed API is implemented as a method on `SemanticModel` or as a language-independent method on `Compilation`. The problem is that at present, you need to go to the language-depended `CSharpCompilation` and `VisualBasicCompilation` to ask the question.

**Comment by gafter** [comment]
@lgolding I would like to point out that in C#, the type `dynamic` does not have an implicit conversion to the type `string`, even though an *expression* of type `dynamic` can be assigned to a variable of type `string` (because there is a conversion-from-expression from `dynamic` to `string`). If those kinds of corner cases are not going to be a sticking point, then I think an API like this is possible.

**Comment by CyrusNajmabadi** [comment]
> The problem is that at present, you need to go to the language-depended CSharpCompilation and VisualBasicCompilation to ask the question

Note: a lot of thought has been put into conversions (especially during hte IOperation timeframe).  It's an actual hard problem because hte languages actually do view things so distinctly.  I spend a bunch of time trying to reconcile things, only to find out there were *lots* of subtle cases i was getting wrong.

That's why, so far, the information has only been available at each compilation layer.  Because you do need to htink about "what semantics do i want to acutally have?  and how do Vb and C# actually expression those semantics?"

It's annoying, but ultimately it is the most correct way to do things.

**Comment by CyrusNajmabadi** [comment]
Note:

![image](https://user-images.githubusercontent.com/4564579/39732404-ec9264aa-5221-11e8-95a6-7ec547d0eb43.png)

These are not necessarily the same thing.  THey may be acceptable for your specific domain and the questions you are asking, but that doesn't mean they're actually correct to always assume they will be hte same thing.

**Comment by gafter** [comment]
Do you advise against an API of the requested shape?

**Comment by CyrusNajmabadi** [comment]
My main issue is that it's unclear to me if IsImplicit always gives the user what they expect.  I wish i had written down the cases when i was looking at this, but there were definitely some things that seemed strange.  However, if we can make a strong case that IsImplicit/IsWidening always map to 'assignable' then i suppose it's ok.

however, if there a case where something would be considered 'assignable' but is not one of those, or you have one of those, but things are still not assignable, then i would *not* provide this (at least not with that impl).

Note: IOp did an implementation of Conversions that exposed only the concepts they found to be safe to map exactly over both languages.  That list only (currently) has:

```c#
        public bool IsIdentity { get; }
        public bool IsNumeric { get; }
        public bool IsReference { get; }
        public bool IsUserDefined { get; }
```

It would be worth asking why IsImplicit is not in that list if it's felt that this is actually a shared concept between the langauges.

**Comment by gafter** [comment]
Well, you can assign any *expression* of type `dynamic` to a variable of type `string` (conversion from expression) but there is no conversion from the *type* `dynamic` to the type `string‘. Is that the sort of thing you’re talking about?

**Comment by CyrusNajmabadi** [comment]
that may be one example.  I thought there were subtleties with nullable/numeric and potentially type-parameters as well.  i.e. you would not necessarily get an 'Implicit' bit set, even though you could assign across these types.  But if you don't think that's the case, then i'm more amenable to this proposal.

As with the IsAccessible PR, i think this would be good to have a good matrix of tests.  Given that we are only ever comparing two types, it seems like it would actually not be too hard to have an exhaustive matrix here.

**Comment by CyrusNajmabadi** [comment]
> My draft PR adds tests for this API to the tests for the conversions APIs, and therefore has about the same coverage.

i think my problem is that this basically means "this PR is correct if IsImplicit/IsWidening is what you want".  But the primary problem is that i have no idea if that is what is wanted.  For example, i imagine some people want this because of the similarity to Type.IsAssignableFrom.  However, i have *zero* way to know the ven diagram relationship between these two methods.

In one a pure superset/subset of the other?  Or are they overlapping?  Are there things IsAssignableFrom returns 'true' for, but IsImplicit says 'false' for (and vice versa).  You mentioned 'dynamic', but is that it?

**Comment by gafter** [comment]
`Type.IsAssignableFrom` does no include user-defined conversions, numeric conversions, boxing conversions, or anything else that might change the representation. It has little relation to the language notion.

**Comment by CyrusNajmabadi** [comment]
That seems to support teh notion then that we should not use "IsAssignable" or "Assignable" in the name.  It will very much lead people to think it's equivalent to the *extremely* well known .Net method with the similar name.

I really like trying to tie it back more to how our specs talk about things here to make it more clear (and to give us a better intuition in the future) how this should be implemented.

**Comment by CyrusNajmabadi** [comment]
For example, maybe something like CanBeConvertedWithoutExplicitCast.

**Comment by gafter** [comment]
The specs use different names, because they are different concepts in the two languages. That is *the very problem* we were trying to address.

**Comment by CyrusNajmabadi** [comment]
I know.  I am attempting to help come to a resolution on a *good* solution.  I've identified my concerns with using names like "Assignable", and i think there could be better ways to express this concept.

**Comment by gafter** [comment]
I'll try using the C# name (`IsImplicitlyConvertibleTo`) and document what concept it corresponds to in each language.

**Comment by CyrusNajmabadi** [comment]
To be clear: i would like a solutoin here.  But i want something that is clear and makes sense and actually *solves* the cases people need.  for example, it's not good if we add something like "IsAssignableTo" and then someone says "but 'X' is not assignable to 'Y', go look at Type.IsAssignableFrom, it returns false!" :)

**Comment by gafter** [comment]
The latest draft PR https://github.com/dotnet/roslyn/pull/26719 uses the name `HasImplicitConversion`, and clearly documents what that means for each language.
