### ISSUE TITLE
DiagnosticAnalyzerDriverTests.DiagnosticAnalyzerDriverIsSafeAgainstAnalyzerExceptions failing

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#9462]
PR: [#9429#issuecomment-192021694](https://github.com/dotnet/roslyn/pull/9429#issuecomment-192021694) *Only collect archives in the case of aborted or failed runs.* by @CyrusNajmabadi
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/4786/

**1 Test Failures:**
DiagnosticAnalyzerDriverTests.DiagnosticAnalyzerDriverIsSafeAgainstAnalyzerExceptions

**Issue 1: Test Failures**
There were test failures, see Test Results above.

**Comment by davkean** [comment]
cc @mavasani

**Comment by davkean** [comment]
And again: http://dotnet-ci.cloudapp.net/job/roslyn_future-stabilization_win_dbg_unit64/5/testReport/junit/(root)/DiagnosticAnalyzerDriverTests/DiagnosticAnalyzerDriverIsSafeAgainstAnalyzerExceptions/

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/9502
