### ISSUE TITLE
[Test Failure]  Roslyn.InteractiveWindow.UnitTests.dll  Test Failures (+1 more) in prtest/win/dbg/unit32 on PR #9431#issuecomment-191697366

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#9464]
PR: [#9431#issuecomment-191697366](https://github.com/dotnet/roslyn/pull/9431#issuecomment-191697366) *Only log formatting events in telemetry when they are enacted by the …* by @jmarolf
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/4737/

**Issue 1: Test Failures**
There were test failures, see Test Results above.

**Issue 2: xUnit returned error code without errors**
xunit produced no error output but had exit code 1

***18:37:10   Roslyn.InteractiveWindow.UnitTests.dll                                      FAILED 00:00:32.0504962***

**Comment by davkean** [comment]
Dupe: https://github.com/dotnet/roslyn/issues/8936
