### ISSUE TITLE
Future NuGet zip is out of date

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#9469]
PR: [#9465](https://github.com/dotnet/roslyn/pull/9465) *Add InternalsVisibleTo TestImpact in Features...* by @KevinH-MS
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/4758/

**Issue 1: Packages need to be updated**
A new package was introduced, but the Azure store of the packages was not updated. Please follow: https://github.com/dotnet/roslyn/blob/master/docs/infrastructure/Updating%20NuGet%20ZIP%20file.

error : The package System.Dynamic.Runtime with version 4.0.0 could not be found in /home/dotnet-bot/.nuget/packages. Run a NuGet package restore to download the package. [/mnt/j/workspace/roslyn_prtest_lin_dbg_unit32/src/Test/Utilities/Portable/TestUtilities.csproj]

**Comment by davkean** [comment]
@TyOverby  can you pick this up tomorrow too?

**Comment by TyOverby** [comment]
@davkean I've updated the nuget zip, and also rewrote the documentation in #9472

**Comment by davkean** [comment]
What's going on with this?

**Comment by davkean** [comment]
Where did we land with this?

**Comment by TyOverby** [comment]
@heejaechang ?

**Comment by heejaechang** [comment]
now zip version is 18. I just confirmed it and all test passed.
