### ISSUE TITLE
InteractiveFeatures.csproj has a dependency on System.Diagnostics.Process package for no reason

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#9480]
InteractiveFeatures.csproj has a dependency on the System.Diagnostics.Process package for no reason, it's a desktop project, it can use Process from System.dll.

System.Diagnostics.Process package isn't even supported to work on .NET 4.6 or 4.6.1. This was introduced in this commit: https://github.com/dotnet/roslyn/commit/a70cdce693c6ab2497f47d1f64fed27556eb35b1.

This package should be removed, and a reference to System.dll should be added.

**Comment by ManishJayaswal** [comment]
@tannergooding can you take a look at this? This commit,https://github.com/dotnet/roslyn/commit/a70cdce693c6ab2497f47d1f64fed27556eb35b1. looks like a revert.

**Comment by tannergooding** [comment]
@ManishJayaswal, That is a revert of a revert, so it is actually re-adding a commit which was undone due some CI issues we were seeing.

I will resolve the problem for now and double check with @tmat and @agocke, on why this was done in the first place.

**Comment by davkean** [comment]
We need this fix this morning, so that we can kick off a build with it.

Please make it against master, and against future-stabilization. Thankss

**Comment by tannergooding** [comment]
See: https://github.com/dotnet/roslyn/pull/9488

**Comment by agocke** [comment]
You reverted your own change :)

**Comment by tannergooding** [comment]
My local repo is in a weird state, it somehow pushed the change directly to dotnet/future-stabilization, even though the dotnet remote is set to 'no_push' and the tracking branch is origin/future-stabilization

**Comment by tannergooding** [comment]
The PR is mostly just for tracking the actual change.

**Comment by tannergooding** [comment]
Master side change is here: https://github.com/dotnet/roslyn/pull/9495

**Comment by tannergooding** [comment]
This should be fixed now.
