### ISSUE TITLE
Microsoft.CodeAnalysis.Elfie needs setup authoring

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#9481]
We need setup authoring for Microsoft.CodeAnalysis.Elfie, as it has none.

**Comment by ManishJayaswal** [comment]
I think Cyrus added this dependency.

**Comment by tannergooding** [comment]
@davkean, is this just setup authoring on the VS side?

**Comment by Pilchie** [comment]
Yes. @tannergooding and/or @jmarolf can you take a look at why the insertion tool didn't generate the authoring for this?

**Comment by tannergooding** [comment]
I believe I had originally told @jmarolf that SetupAuthoring changes need to be explicilty reviewed and validated that they are correct by a human.

There have been several instances in the past (and at least one that would have been included in this build, #9480) where there was an invalid dependency change.

Additionally, having the insertion tool additionally check setup authoring will make it significantly more complex (as each file needs to have mappings to several locations which need updating, which can additionally vary from branch to branch).

It will indeed be a useful thing to have the changes prepped beforehand for validation, but getting the tooling to that point is not going to happen easily.

**Comment by Pilchie** [comment]
But that's what BuildDevdivInsertionFiles already does - it generates WiX based on the contents of our VSIXes. Why didn't that happen here? (Yes, I agree that insertion PRs should always be reviewed, but that's orthogonal to this question).

**Comment by tannergooding** [comment]
Ah, your right. I was referring to the other setup authoring files we end up touching, that are outside the scope of what DDIF can generate (such as the MSBuild WiX files).

And it looks like DDIF did correctly generate SetupAuthoring for Elfie. I'm going to go look at the insertion tool and the PR to try and find out why it wasn't included.

**Comment by tannergooding** [comment]
@Pilchie, @davkean, @jmarolf. The insertion utility is incorrectly ensuring the `robocopy` always has an exit code of 0, and throwing an exception otherwise.

For robocopy, an exit code of 0-7 (inclusive) indicates success (0 is success with nothing copied, and 1-7 provide additional information on how the operation succeeded) and an error code above 8 indicates failure (8-15 are failure, with additional information on how the operation failed, and 16 is a fatal error).

The code should actually be doing, `if (process.ExitCode >= 8) { throw Exception() }`

**Comment by tannergooding** [comment]
This should now be fixed.

**Comment by tannergooding** [comment]
Or it will be momentarily, #9496 is an issue, so I need to rebuild the insertion utility locally first. There were also several changes made to the utility that have not yet been checked in

**Comment by tannergooding** [comment]
Should be resolved now.

**Comment by DustinCampbell** [comment]
@Pilchie and I believe this is already done, no?
