### ISSUE TITLE
Hardcoded compiler path in Microsoft.CodeDom.Providers.DotNetCompilerPlatform

### ISSUE THREAD

**Issue by MaceWindu** [dotnet/roslyn#9483]
Not sure if this is proper place to report it, but I see some defects related to DotNetCompilerPlatform logged there.

**Version Used**: 
1.0.20820.0 (1.0.1)

**Expected Behavior**:
Path to compiler executable could be configured.

**Actual Behavior**:
Path to compiler is hardcoded and the only way to use library is to put compiler on that way (ugly way to support Roslyn by ASP.NET) or change it using reflection (this is what I do right now).
Most interesting is that both C# and VB code providers have constructors that accept path as one of  options parameter properties. But those constructors made internal and not used (except parameterless constructor and maybe tests).

I've seen this one:
https://www.nuget.org/packages/Microsoft.CodeDom.Providers.DotNetCompilerPlatform.BinFix/
But it just moves compiler files to hardcoded path... Not something I will be happy with.

**Comment by jaredpar** [comment]
This package is owned by the legacy ASP.Net team.  I'm unsure exactly where a bug on this should be filed.  I've contacted the appropriate team though and am going to leave this issue open until they can comment / port it to an area they are looking at.

**Comment by shmao** [comment]
@MaceWindu , thanks for submitting the issue. Can you please explain a little bit on why you need to change the compiler location?

FYI, I've copied this issue to our internal database. For submitting other issues related to this package in the future, you can either report a bug at [Microsoft Connect](https://connect.microsoft.com/VisualStudio/Feedback/LoadSubmitFeedbackForm?FormID=6240) or find 'contact owner' at [the package's homepage](https://www.nuget.org/packages/Microsoft.CodeDom.Providers.DotNetCompilerPlatform).

**Comment by MaceWindu** [comment]
@shmao, your question made me think a lot :)
Well, maybe it will not sound as a good reason, but using default hardcoded path is inconvinient for us. Right now I reset it to empty (current application folder) through reflection and to add compiler to new regular project or test project I just need to add compiler binaries as references.
With default path it will be more work, taking into accound that we:
- use CodeDom as a backend for our higher-level code generation API. Our applications hosted as services, not as ASP.NET applications.
- we don't use nuget and it means we need to manage references manually
- bin (and obj) folders added to ignore list for our SCM

We would drop support CodeDom support happily taking into accont it wasn't changed for ages and really outdated, but unfortunatelly Roslyn is not production-ready for us yet.

**Comment by shmao** [comment]
@MaceWindu, thanks for explaining how you use the new CodeDOM provider. The package was shipped by ASP.Net team to [enable the new Roslyn compiler in ASP.NET applications](https://blogs.msdn.microsoft.com/webdev/2014/05/12/enabling-the-net-compiler-platform-roslyn-in-asp-net-applications/). The scenario where the CodeDOM provider is used in custom code generation was not considered as a main scenario the provider would support. I've copied the info to our internal bug database. We will discuss the issue later this week.

**Comment by shmao** [comment]
As I mentioned above, the package is to enable the new compiler in ASP.Net web applications/websites. The CodeDOM provider inside was designed to be used by ASP.Net code generation. More generic custom code generation is not supported by the provider. Therefore we decided not to make a change in the provider to support the scenario of this issue.

@MaceWindu, thank you again for your submission.

**Comment by niemyjski** [comment]
If you are going to be providing this package publicly then support for other functionality of the codedom provider needs to be supported. We are trying to use this in our app to take advantage of the latest language features and this is currently a pain point.

**Comment by jaredpar** [comment]
@niemyjski note that despite the name we don't own this particular package.  It's produced by the ASP.net team.  The repo for the package is here https://github.com/aspnet/RoslynCodeDomProvider

**Comment by MaceWindu** [comment]
Looks like fix is on the road:
https://github.com/aspnet/RoslynCodeDomProvider/pull/12
