### ISSUE TITLE
String literal do not escape \u2028 (line separator) unicode character

### ISSUE THREAD

**Issue by MaceWindu** [dotnet/roslyn#9484]
**Version Used**: 
1.1.0.51202 (1.1.1)

**Steps to Reproduce**:

```
var literal = SyntaxFactory.LiteralExpression(
    SyntaxKind.StringLiteralExpression,
    SyntaxFactory.Literal("\u2028"));

var code = literal.ToFullString();
```
Literal value will contain unescaped \u2028 character.

**Expected Behavior**:
code == "\"\\\u2028\""

**Actual Behavior**:
code == "\"\u2028\""

In our project we use code generation using CodeDom and Roslyn and there are two unicode characters that requires to apply extra replace-fu now:
- NEXT LINE : **\u0085** escaped properly by Roslyn but not escaped by CodeDom
- LINE SEPARATOR : **\u2028** escaped properly by CodeDom but not escaped by Roslyn

I've checked all characters except surrogate pairs with Roslyn and only this one was problematic. I'm also checking CodeDom, and if there will be any other unescaped characters, I will report it.

BTW, could you forward this issue to CodeDom folks or provide information where I could report it? Connect site lately looks like a last place where you can expect response from developers :(

**Comment by MaceWindu** [comment]
Update:
Executed Roslyn tests with surrogates - it also fails for each pair: SURROGATE+\u2028, but I think this one is not a Roslyn issue, because when I try to save it to file with UTF8 encoding I get following exception from UTF8 encoder class:
```
System.Text.EncoderFallbackException occurred
  Message=Unable to translate Unicode character \uD975 at index 51 to specified code page.
  StackTrace:
 	mscorlib.dll!System.Text.EncoderExceptionFallbackBuffer.Fallback(char charUnknown, int index)	Unknown
 	mscorlib.dll!System.Text.EncoderFallbackBuffer.InternalFallback(char ch, ref char* chars)	Unknown
 	mscorlib.dll!System.Text.UTF8Encoding.GetBytes(char* chars, int charCount, byte* bytes, int byteCount, System.Text.EncoderNLS baseEncoder)	Unknown
 	mscorlib.dll!System.Text.EncoderNLS.GetBytes(char[] chars, int charIndex, int charCount, byte[] bytes, int byteIndex, bool flush)	Unknown
 	mscorlib.dll!System.IO.StreamWriter.Flush(bool flushStream, bool flushEncoder)	Unknown
 	mscorlib.dll!System.IO.StreamWriter.Dispose(bool disposing)	Unknown
 	mscorlib.dll!System.IO.TextWriter.Dispose()	Unknown
 	mscorlib.dll!System.IO.File.InternalWriteAllText(string path, string contents, System.Text.Encoding encoding, bool checkHost)	Unknown
```

**Comment by MaceWindu** [comment]
Update: Tested CodeDom and surrogate pairs - no additional errors.

**Comment by gafter** [comment]
The root cause of this is https://github.com/dotnet/coreclr/issues/3542 . We can work around it in the Roslyn compilers.
