### ISSUE TITLE
Need a way to simulate binding redirects when running under xunit with "AppDomain=denied"

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#9491]
We now by default disable AppDomains under xunit, see https://github.com/dotnet/roslyn/blob/future/build/Defaults/app.config#L6.

Unfortunately, this means that binding redirects no longer work, because we're running inside of xunit's AppDomain 0, and hence inherit its binding context and its app.config.

We need a way to simulate these binding redirects when AppDomains turned off as otherwise, we continually run into issues like https://github.com/dotnet/roslyn/issues/9490.

A couple of approaches:

1) We predeploy the xunit runner, and merge the test's projects app.config with that of xunits.
- This would cause us to have to have a unique copy of xunit for every test assembly.

2) We hook onto AppDomain.AssemblyResolve, read the binding redirects and simulate them.

**Comment by davkean** [comment]
If we go with 2), we should make sure we use one of xunit's extensibility points to run _before_ tests have launched. Such as their test framework, Brad states:

> There are mechanisms for this kind of assembly-wide overriding of behavior: custom test > frameworks. The implementation of ITestFramework and friends can be mostly pass-thru to the existing code.

> We resist the notion of having dozens of these one-off hooks in the framework itself because > everybody's pet "thing I want to override" just bloats the framework. We ensure that our extensibility story allows user to do what they need to do so that the core framework stays leans and focused.

> The ObservationExample does more than you need/want, but should at least set you down the right path.

**Comment by davkean** [comment]
See this PR: https://github.com/dotnet/roslyn/pull/9782 which effectively does it for project system tests. It shouldn't be hard to mimic this for the entire tree.

**Comment by jasonmalinowski** [comment]
@davkean Sounds like you created this when you had issues with the project system tree. Was there a particular pain that this would hit for non-project system stuff, now that you've moved out to your own repository?

**Comment by davkean** [comment]
If you ever get tests running against VS 15, you're going to run into something similar.

**Comment by jasonmalinowski** [comment]
We are using binding redirects again for the desktop side of things.
