### ISSUE TITLE
Insertion script needs to be updated to automatically pull latest sources and build insertion tool

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#9496]
FYI. @jmarolf, @davkean, @dotnet/roslyn-infrastructure 

The insertion script is currently set to just run the pre-built insertion utility.

It should be changed to automatically pull the latest sources, build the insertion utility, and then run (possibly on a per-branch basis).

**Comment by davkean** [comment]
Don't assign these by default to me, I triage them daily.

**Comment by genlu** [comment]
I have an updated script, but trying to fetch/pull from `origin` on the VM failed to authenticate, where can I get the account info?

**Comment by genlu** [comment]
I have updated and tested the insertion script. It doesn't sync/build on a per branch basis since I don't see a point of doing that. 

@jmarolf @heejaechang Can either of you take a look at it and close this issue?

**Comment by jmarolf** [comment]
@genlu where is it?

**Comment by genlu** [comment]
I updated the `PerformInsertion.ps1` in place.

**Comment by davkean** [comment]
Do we check that file in? If not, we should.

**Comment by genlu** [comment]
I think none of the daily tasks related scripts are checked in right now. I talked with @jmarolf about moving al scripts out of their current locations into a centralized folder (that is not in the local repo), but I think checking them in makes sense too.

**Comment by genlu** [comment]
Anyway, this is fixed. let's use #9544 to track the issue of how we deal with all those scripts.

**Comment by davkean** [comment]
:+1:
