### ISSUE TITLE
EnC: OutOfMemoryException thrown by LongestCommonSubsequence.ComputeCostMatrix

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#9497]
When editing large methods (1000s of statements). 

The algorithm is currently allocating N^2 matrix. It can be optimized to N D or O(N).

Repro:

```C#
using System;

class Program
{
    static void Main(string[] args)
    {
        int i = 1;

        if (i == 0)
        {
             Console.WriteLine(0);
             Console.WriteLine(1);
             ...
             Console.WriteLine(10000);
        }
        else 
        {
             Console.WriteLine(0);
             Console.WriteLine(1);
             ...
             Console.WriteLine(10000);
        }
    }
}
```

**Comment by ManishJayaswal** [comment]
internal issue 219899 is duped against this.

**Comment by tmat** [comment]
internal issue 243630 is duped against this

**Comment by suprak** [comment]
Any progress on this? Is there a fix we could try?

**Comment by tmat** [comment]
@suprak Sorry, we don't have a fix yet.

**Comment by jltjohanlindqvist** [comment]
This fix would also be a huge help for us.

**Comment by tmat** [comment]
@HelenaKotas

**Comment by tmat** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/16677

**Comment by jltjohanlindqvist** [comment]
Am I correct in assuming that this fix is in the 15.3 Preview 3 version of VS2017? 

If it is then the fix did not solve our issue. I still crash when doing edit and continue in the problematic parts of our project using 15.3 preview 3.

**Comment by tmat** [comment]
@jltjohanlindqvist Yes, it is in 15.3 P3. Could you please share a crash dump thru VS Feedback (Help menu, Send feedback, Report a problem)?

**Comment by jltjohanlindqvist** [comment]
@tmat I think I succesfully uploaded the crash recording. https://developercommunity.visualstudio.com/content/problem/78097/visual-studio-crashes-when-trying-to-enc-in-a-larg.html

**Comment by tmat** [comment]
@jltjohanlindqvist Thank you, I'll take a look.

**Comment by jltjohanlindqvist** [comment]
Was the dump sufficient or is there something else I could provide that would help?

**Comment by tmat** [comment]
@jltjohanlindqvist Sorry, I have been busy with other stuff and haven't had time to look yet. Wrapping it up now, so hopefully I'll have time to look into this soon. Will keep you posted.

**Comment by jltjohanlindqvist** [comment]
Alright, sounds good.

**Comment by tmat** [comment]
@jltjohanlindqvist Thanks a lot for uploading the crash dump, it helped me to find out the root cause. I identified a possible optimization that could help us reduce memory requirements when editing big method bodies. I'll use the VS feedback item to track the issue.

**Comment by jltjohanlindqvist** [comment]
Awesome to hear!

**Comment by rob-at-phinar** [comment]
We still have this problem with VS 2017 crashing or not working with large methods. It is killing our productivity. Has there been any progress on this?
