### ISSUE TITLE
Seal DiagnosticAnalyzer.Equals, GetHashCode and ToString

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#950]
We use analyzers as keys for various maps.

**Comment by mavasani** [comment]
@heejaechang for your recent change where you invoke Analyzer.GetHashCode, can you instead use GetUniqueId extension in Features layer? That should work right? I am not sure what GetHashCode override on DiagnosticAnalyzer should return.

**Comment by heejaechang** [comment]
Return ReferenceEqualityComparer.Instance.GetHashCode(this); and Equals do same.


-          heejae

**Comment by mavasani** [comment]
@srivatsn @JohnHamby can you please look at this? I think we should fix this for rc2 milestone.

**Comment by srivatsn** [comment]
Makes sense. Let's do it.

**Comment by JohnHamby** [comment]
Yes, this is a good idea.
