### ISSUE TITLE
[Proposal] Preprocessor Directive Culture / Option Culture

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#9509]
The idea of this preprocessor directive is to enforce the culture that is to be used be default.

``` VB.net
#Culture Invariant ' Default
#Culture fr-FR ' Set it to French
```

``` VB.net
Option Culture Invariant ' Default
Option Culture fr-FR ' Set it to French
```

Thus the programmer can override it and specific a specific culture.
So that features like  #9407 would be possible.

**Comment by HaloFour** [comment]
Even if you could specify the culture the user could override some of those settings, which still makes it non-deterministic and not suitable for compile-time evaluation.

**Comment by gafter** [comment]
This "issue" is far from complete. What, precisely, would be your proposed specification for what the culture is at runtime?

**Comment by AdamSpeight2008** [comment]
@gafter If the culture is specified via `#Culture fr-FR` at runtime the culture is `fr-FR` as the programmer dictated what the culture is. This **can not** be overridden. If no culture is specified, then at runtime, it is whatever the local culture is.

**Comment by HaloFour** [comment]
@AdamSpeight2008 How would this actually be implemented?  Would ever single member be required to automatically check the current thread culture and current UI culture and replace them with the specified culture, and then replace them back when the thread exits that member?  What about satellite resource assemblies?  IIRC there are a lot of times and places where you can't just change the culture of an application mid-stream.

**Comment by HaloFour** [comment]
And what would happen in the middle of one of these files/sections if the programmers changes the thread/UI culture?  Or calls a method passing a specific culture?

**Comment by gafter** [comment]
> @gafter If the culture is specified via `#Culture fr-FR` at runtime the culture is `fr-FR` as the programmer dictated what the culture is.

How is this any different than assigning to `CultureInfo.CurrentCulture` (or `Thread.CurrentCulture`) inside `Main`? Why would we add a language feature for something already adequately handled by an API?

> This **can not** be overridden.

So you're suggesting that code that assigns to `CultureInfo.CurrentCulture` (or `Thread.CurrentCulture`) would simply stop working?

I don't see how this helps or enables #9407. How is the compiler, which is run on one platform, supposed to know how a named locale will behave on the execution platform?

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
