### ISSUE TITLE
Test result upload on signed build failures

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#9510]
/publish:https://devdiv.visualstudio.com/defaultcollection,/publishbuild:Roslyn-Stabilization-Signed-Release_20160304.2,/publishresultsfile:F:\Builds\5519\DevDiv\Roslyn-Stabilization-Signed-Release\bin\xUnitResults\Roslyn.Services.Editor.UnitTests2.dll.xml,/teamproject:DevDiv,/platform:Mixed Platforms,/flavor:Release
Publish : https://devdiv.visualstudio.com/defaultcollection,PublishBuild : Roslyn-Stabilization-Signed-Release_20160304.2,PublishResultsFile : F:\Builds\5519\DevDiv\Roslyn-Stabilization-Signed-Release\bin\xUnitResults\Roslyn.Services.Editor.UnitTests2.dll.xml,TeamProject : DevDiv,Platform : Mixed Platforms,Flavor : Release

```
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.TeamFoundation.Client, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.TeamFoundation.Client, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at TestResultUploader.ResultUploader.UploadResults()
   at TestResultUploader.ResultUploader.Main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```

**Comment by jasonmalinowski** [comment]
Closed because this isn't being used anymore. Deletion of the tool is in internal PR 1088.
