### ISSUE TITLE
Null-propagating operator with await still throws NRE

### ISSUE THREAD

**Issue by marek-safar** [dotnet/roslyn#9513]
**Version Used**: Microsoft (R) Visual C# Compiler version 1.2.0.60220

**Steps to Reproduce**:

```
using System;
using System.Threading.Tasks;

class MainClass
{
    public static void Main(string[] args)
    {
        var strings = GetSomeStrings (null).Result;
        Console.WriteLine(strings);
    }

    public static async Task<string> GetSomeStrings (AsyncStringFactory myFactory)
    {
        var res = await myFactory?.GetSomeStringAsync ();
        return res;
    }
}

public class AsyncStringFactory
{
    public async Task<string> GetSomeStringAsync ()
    {
        await Task.Yield();
        return "foo";
    }
}
```
1. compile
2. run produced .exe

**Expected Behavior**:

The behaviour is actually inline with C# 5 spec which in section "Classification of await expressions" uses following description

> The expression await t is classified the same way as the expression (t).GetAwaiter().GetResult().

However, that's C# 5 which does not cover `null-propagating operator` at all. This looks like oversight in C# 6 design where null-propagating operator introduction was not incorporated into await expressions classification.

Probably the most straight forward fix is to rephrase the section with something like

>  The expression await t is classified the same way as the expression (t).GetAwaiter().GetResult() unless t includes null-propagating operator then expression (t)?.GetAwaiter().GetResult() classification is used.

However, that would not cover cases like
```
var t = a?.FooAsync ()
await t
```
and a method which returns null Task and null-operator is used for invocation would stop throwing NRE as well which I think is not desirable.

**Actual Behavior**:

NRE during program execution

System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at MainClass.<GetSomeStrings>d__1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at MainClass.Main(String[] args)

**Workaround**:

Rewriting code to
```
var res = await (myFactory?.GetSomeStringAsync() ?? Task.FromResult<string>(null));
```
actually does what most seasonal C# developers would say the code above does but it's ugly and `?.` operator was introduced to make code more fluent not more obscured.

**Comment by alrz** [comment]
#7556

**Comment by gafter** [comment]
The NRE follows the specification as written.

**Comment by marek-safar** [comment]
@gafter I know that's why I wrote the explanation suggesting this is design bug.

**Comment by JesperTreetop** [comment]
The part you quoted works fine.

> The expression await t is classified the same way as the expression (t).GetAwaiter().GetResult().

The expression "t" has a well-defined type even if it is a null-coalescing operation. 

This is not a design bug for the same reason that:

    object obj = /* ... */;
    var str = obj?.ToString();
    var uppercase = str.ToUpper();

...is not a design bug in invoking the method ToUpper. Null coalescing is to allow that chain of invocations to safely fall back to `null`. Doing something with that value may still result in a NullReferenceException and it's still up to your code to take care of it.

In addition, `await` can't be changed to work differently with `null` without it being a breaking change. Maybe suggesting the introduction of `await? t` which would do something specific when awaiting `null` - maybe the same as `await (t ?? Task.FromResult(default(T)))` - would be better.
