### ISSUE TITLE
Proposal: Regex repetition syntax

### ISSUE THREAD

**Issue by manixrock** [dotnet/roslyn#9514]
# The Issue

If we want to match a list of any kind in regex, we currently have to make certain compromises. For example, say we wanted to match a list of names, such as: `Anna,Bob,Charlie` (a more complex example would be a list of phone numbers, or url's, so imagine the regex is potentially long and complex).

We could try:

```
((Anna|Bob|Charlie),)+
```

However that doesn't match our original text as it requires a final `,` to match.

Text | Should match | Matches
------------ | ------------- | -------------
`"Anna,Bob,Charlie"` | yes | no **(wrong)**
`"AnnaBob,Charlie"` | no | no

We could try:

```
((Anna|Bob|Charlie),?)+
```

But this will wrongly match items without the separator, which is probably not what the user wants:

Text | Should match | Matches
------------ | ------------- | -------------
`"Anna,Bob,Charlie"` | yes | yes
`"AnnaBob,Charlie"` | no | yes **(wrong)**

Currently the only way to achieve this is through the duplication of the list-item regex group:

```
(Anna|Bob|Charlie)(,(Anna|Bob|Charlie))*
```

Which is a pain when the match is long like a phone number or a url, and if you update one part you have to remember to copy the changes to the other one. It also gets tricky if say you wanted it to match from 0 to 20 items, you'd have to do it like this:

```
((Anna|Bob|Charlie)(,(Anna|Bob|Charlie)){0,19})?
```

The only way to somewhat avoid this is to put that regex part into a variable and use the variable twice to construct the regex, but this relies on the host language, still creates a longer than necessary regex, and matches an extra redundant matching group which the user then have to manually group with the first in the host language.

# Proposal

A more useful approach could be to use some repetition separator syntax. Regex already has repetition quantifiers like `+`, `*`, `?` and also `{m,n}`. The last one could be enhanced to specify an optional third parameter as a repetition-separator group:

```
(Anna|Bob|Charlie){0,20,(,)}
```

Since it can contain any valid regex syntax, it should always be enclosed inside a group, and it behaves like any normal group. Just like in normal usage, the quantifier limit values can be missing entirely:

```
(Anna|Bob|Charlie){,,(,)}
```

And if we only wanted to specify the separator:

```
(Anna|Bob|Charlie){(,)}
```

This would allow infinite repetition, equivalent to using the `*` or `{,}` quantifiers.

Text | Should match | Matches
------------ | ------------- | -------------
`"Anna,Bob,Charlie"` | yes | yes
`"AnnaBob,Charlie"` | no | no

We could then easily enhance it to, for example, allow spaces after each comma:

```
(Anna|Bob|Charlie){(, *)}
```

This is much shorter and more readable than any existing alternatives, and produces a match result with all the correct values in the same matching group. The flow would look like this:

![regex separator flow](https://cloud.githubusercontent.com/assets/785247/13548375/98ba6ba2-e2f7-11e5-8396-38e6d0a68265.png)

# Other examples

Description | Regex
------------ | -------------
Phone number lists | `(\(?\d{3}\)?-? *\d{3}-? *-?\d{4}){(, *)}`
Versions names ("3.7.15") | `(\d){(\.)}`
Html class attribute | `class="(?<class>\S+){(\s+)}"`
Mathematical calculations ("7.5 * 2 + 10") | `(\d+(\.\d)?([Ee]\d)?){( *[+-*/] *)}`
Name parts ("Johann Wolfgang von Goethe") | `^(?<part>\S+){( )}$`
Natural language (notice the nested repetitions) | `winners are (?<name>(?<name_part>\S+){1,,( )}){( then )}`
Time matching ("03:15", "23:59:59") | `(\d\d):(\d\d){1,2,(:)}`
Javascript object notation | `[{] *(?<key>[a-zA-Z_]\w*) *: *(?<value>"[^"]*"|\d+(\.\d*)?([Ee]\d*)?|...other.types..){( *, *)} *[}]`

# Special Case

In certain use cases a final optional separator match is also desirable. For example, in C# the collection initializer syntax allows for an optional final `,`:

```C#
var names = new List<string> {
    "Anna Alyson",
    "Bob Borton",
    "Charlie Cob",
};
```

For this we could further enhance the syntax so that if the separator-group has a `+` after it, it can have an optional final match (the separator-group would not allowed to have any other quantifiers, however sub-groups can). The regex would look like this:

```
[{]\s*(?<name>"[^"]*"){(\s*,\s*)+}\s*[}]
```

The new flow would then look like this:

![regex separator flow 2](https://cloud.githubusercontent.com/assets/785247/13548546/8badb2b2-e2fb-11e5-9d74-3860cc64ec2a.png)

**Comment by svick** [comment]
How is this related to the C# language? If you're proposing changes to the `Regex` class, those should go to https://github.com/dotnet/corefx.

**Comment by manixrock** [comment]
@svick Thanks, submitted as an issue there: https://github.com/dotnet/corefx/issues/6685
