### ISSUE TITLE
[Pattern Matching] Should a property-pattern be capable of referencing an event?

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#9515]
In a _property-pattern_ such as `P { X is var x }`, should it be allowed that `X` is an event member of `P`?

**Comment by HaloFour** [comment]
I don't think so.  It's not like event accessors return anything that can be used to match, so there's nothing to be assigned to `x`.

Unrelated, but is the `=` in the pattern a typo or is the syntax for property patterns changing?

**Comment by svick** [comment]
@HaloFour The accessors do not, but the backing field of a field-like event can be read from within the same class.

**Comment by HaloFour** [comment]
@svick This is true, but how many real use cases are there for matching over `this` or your own kind?  Not to mention, exactly what would you be matching?  Or would this simply be shorthand for deconstruction during a self-matching expression?

**Comment by bondsbw** [comment]
@svick Why not then match on the backing field itself, instead of the event?

**Comment by svick** [comment]
@bondsbw If it's a field-like event (e.g. `public event EventHandler X;`), then you access the backing field by writing the name of the event (similar to get-only auto-properties in C# 6).

**Comment by bondsbw** [comment]
@svick Ok, didn't know that's what you were talking about.  I thought you were talking about custom `add`/`remove` mechanism with a separate backing field.

**Comment by axel-habermaier** [comment]
What does it even mean to match a delegate? I don't recall delegate matching to be proposed so far. Did I miss something? Does it match the delegate's invocation list?
