### ISSUE TITLE
Difference in lambda construction/evaluation depending on subsequent usages

### ISSUE THREAD

**Issue by jcchalte** [dotnet/roslyn#9520]
**Version Used**: VS2015 Update 2 RC,  .NET 4.6.1

**Steps to Reproduce**:

We have some code related to Entity Framework which does not execute with the same behaviour at runtime on VS2015 in contrast to the exact same code compiled and executed with VS2013.

Our function is decomposed in 2 calls
The first call executes an Entity Framework query using multiple joins and retrieve relevant data in a list of anonymous objects. The code is somewhat like that :

``` csharp
var results = (from customer in context.Set<Customer>()
                      ...
                      select new {
                               CustomerID = customer.ID,
                                ...
                                Invoices = (from invoice in context.Set<Invoice>()
                                                  where invoice.CustomerID == customer.ID
                                                  select { ... }
                      }).ToList();
```

Notice the `.ToList` at the end (the query is materialized, data must be retrieved from the DB at this point).

Then the second call creates a DTO (a POCO object) using data retrieved in the first call. To do that, it can pass data to other services and so on.

``` csharp
var myDTO = new CustomerDTO(){
    CustomerID = info.CustomerID,
    InvoicesTaxes = taxService.GetTaxesFromInvoicesID(info.Invoices.Select(invoice=>invoice.ID)),
    ...
};
```

and so on.

In VS2015 only, this code crashes at runtime on the first call, saying that the inner "context.Set<Invoice>" method cannot be translated to a store expression. If we comment the second line (the DTO construction), the first line passes as expected and the "results" list contains all our needed values without any issue.

The exception is :

System.NotSupportedException: LINQ to Entities does not recognize the method 'System.Data.Entity.DbSet`1[Domain.Invoice] Set<Invoice>' method, and this method cannot be translated into a store expression.)

This exception is thrown when the lambda to db command tree translator given by EF cannot translate a method call to something it knows. From what I understand, something must have changed the "Set" method call at runtime depending on how it is used later (maybe for optimisation purpose ?). The "modified" set call is not known by EF and thus breaks the query execution.

We first thought that this was an issue with EF but the fact that commenting the second line (which is not related to EF at all) "unbreaks" the bug seems to indicate that it is more of an optimization/compiler issue. Do you guys know something related to this kind of bug ?

Thank you all for you hard work,
Jean-Christophe Chalté

**Comment by HaloFour** [comment]
You sure it's identical code in both places?  The only reason that I can think of that the second statement would result in the EF error trying to process the queryable is that the first statement isn't actually materialized and you're still working with the original `IQueryable<T>` at that point.  Like perhaps there are multiple paths and one of them isn't calling `ToList()`.  Without seeing the actual failing method it's difficult for me to make that determination.  The debug view of the expression tree would probably also help.

**Comment by VSadov** [comment]
It is very hard to guess here what might be going on. 
In theory the subsequent code should not be affecting the shape of the code before. The only thing I can think of is lifting context into an outer closure, because the subsequent code requires that.

That is hard to verify though. I am not even sure context is a local or a parameter. 

If you separate use of context into independent locals and it starts working, then it might be that query translator is confused by the closure.

```cs
{
    var temp1 = context;
    var results = (from customer in temp1.Set<Customer>()    // note temp1
                         . . . 
}

{
    var temp2 = context;
    var myDTO = new CustomerDTO(){                // uses temp2 
      . . . 
}

```

if separation of the context into independent locals works, it would hint that this is caused by differences in closure capturing.
Otherwise it is really hard to tell by the code of what could be the problem.

**Comment by VSadov** [comment]
Can't proceed without more info.

Please reactivate if more info is available.
