### ISSUE TITLE
MSBuildWorkspace run diagnostics only on selected files

### ISSUE THREAD

**Issue by jmecosta** [dotnet/roslyn#9522]
hi,

im creating a diagnostic runner based on MSBuildWorkspace, i would like to tell the analyser when i do

```
analyserMain.GetAnalyzerDiagnosticsAsync().Result
```

to report issues only on selected files. Now when i do

```
let compilation = document.Project.GetCompilationAsync().Result
```

i get issues reported in all files in project.

is there something i can use to achieve this currently.

thanks in advance
jc

**Comment by bkoelman** [comment]
You can filter the results on `diagnostic.Location.SourceTree.FilePath`.

**Comment by jmecosta** [comment]
Yes that what I do, however I would like to avoid the overhead of analysing
all the projects in files in the project

**Comment by srivatsn** [comment]
You can call `GetAnalyzerSyntaxDiagnostics(syntaxTree)` and `GetAnalyzerSemanticDiagnostics(semanticModel) to get the diagnostics for a single file.

**Comment by jmecosta** [comment]
@Sridhar-MS thanks for the hint, i will investigate it and reopen if i need.
