### ISSUE TITLE
Ctrl+Enter should commit IntelliSense

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#9528]
This is a regression from Visual Studio 2013 in both VB and C#.

**Steps to Reproduce**:
1. Create a new Console App.
2. In Main(...), press Ctrl+J to bring up IntelliSense
3. Press Ctrl+Enter

**Expected Behavior**: The currently selected item is committed.

**Actual Behavior**: It's not. Edit.OpenLineAbove is invoked instead.

**Comment by rchande** [comment]
@jasonmalinowski What's the right approach here? Do I handle "Edit.OpenLineAbove", or do I do something (vsct?) to make Roslyn start handling CTRL-enter?

**Comment by jasonmalinowski** [comment]
@rchande: if that's the command it maps to, then yes. Ideally there'd be some concept of contexts where you could say "if the list is up, Ctrl+Enter is just enter" but no such thing exists.

**Comment by rchande** [comment]
@DustinCampbell Do you think this _needs_ to be in `2.0`, or can it wait for an update? I don't think we've seen any other complaints about this.

**Comment by DustinCampbell** [comment]
cc @Pilchie, @kuhlenh

**Comment by CyrusNajmabadi** [comment]
Looks like no one has noticed this since Rolsyn shipped originally.  We can likely close this out as an acceptable change in behavior.
