### ISSUE TITLE
[Test Failure] TestGenerateEventInCSharpFileFromImplementsWithType in prtest/win/dbg/unit32 on PR #649

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#9549]
PR: [#649](https://github.com/dotnet/roslyn-internal/pull/649) *Merge stabilization into master* by @vslsnap
Failure: http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_dbg_unit32/741/

another cross language test failure

**Comment by jasonmalinowski** [comment]
This is a dupe of #9308 since the internal build didn't have the public changes that would fix the flakiness issue.
