### ISSUE TITLE
[Concept] Method Overloads with Specific Arguments.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#955]
This concept is to allow to the programmer to write method overloads that have specific argument values, that is invoked in favour of the less specific method.
It think it be easier to see the idea of the concept with some examples.

Let's start with a simple example. **Fibonacci** 
```
public int Fib ( 0 ) => 0;
public int Fib ( 1 ) => 1;
public int Fib ( int n ) => Fib( n - 1 ) + Fib( n - 2 );
public int Fub ( 0 ) => 1;  /* compile-time error since a Fub( int n ) method doesn't exist.
```

If the method `Fib` is invoked with the argument `0` , then the first overload is used.
If the method `Fib` is invoked with the argument `1` , then the second overload is used.
Otherwise the third overload is used.

**Null**
It would be also possible to have method overloads that are "specialised" for `null`
```c#
public int CountWhitespace ( null ) => 0;
public int CountWhitespace ( string s ) => s.Count( c=> Char.IsWhitespace( c); 
```

**Comment by svick** [comment]
In functional languages that have a similar feature, like F# and Haskell, it's just shorthand for pattern matching (proposed for C# in #206). Should this feature be the same? E.g. allowing code like:

```c#
Expr Simplify(Add(Const(var l), Const(var r))) => Const(l+r);
Expr Simplify(Expr e) => e;
```

If I understand the proposal correctly, it's basically just more succinct way to write a `switch`, where every case returns. E.g.:

```c#
public int Fib(int n)
{
    switch (n)
    {
        case 0: return 0;
        case 1: return 1;
        default: return Fib(n - 1) + Fib(n - 2);
    }
}
```

Wouldn't it be more useful to create a shorthand for such `switch`, e.g. (made up syntax, don't focus on it too much):

```c#
public int Fib(int n) => switch (n)
{
    0: 0;
    1: 1;
    default: Fib(n - 1) + Fib(n - 2);
};
```

**Comment by AdamSpeight2008** [comment]
@svick I was thinking more along the lines of your first example. See [Magpie](http://magpie-lang.org/)

**Comment by gafter** [comment]
In C#, overloading would be syntactically indistinguishable from pattern-matched dispatch on different types, e.g. when you wrote:

```cs
public int Foo(string s) => 2;
public int Foo(int i) => 3;
public int Foo(object o) => 1;
```

yet C# performs overloading at compile-time, and pattern-matched languages perform pattern-matching at runtime. Moreover, this proposal would change the meaning of a set of declarations (such as this) to be dependent on the declaration order. This feature request would therefore be an incompatible language change.
