### ISSUE TITLE
[Test Failure] All WPF access got failed in prtest/win/dbg/eta on PR #648

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#9553]
PR: [#648](https://github.com/dotnet/roslyn-internal/pull/648) *Merge master into future* by @vslsnap
Failure: http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_dbg_eta/744/

exception from all over the places when WPF try to access UIElement from UI thread. it claims elements are already owned by different threads.

**Comment by DustinCampbell** [comment]
@jasonmalinowski, please take a look.

**Comment by balajikris** [comment]
build artifacts are gone already :anger:  I'm guessing this is the same root issue as https://github.com/dotnet/roslyn/issues/9551

**Comment by davkean** [comment]
Agreed
