### ISSUE TITLE
[Build Failure] PGO failed in prtest/win/vsi/p2 on PR #634

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#9555]
PR: [#634](https://github.com/dotnet/roslyn-internal/pull/634) *Only log formatting events in telemetry when they are enacted by the …* by @jmarolf
Failure: http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_vsi_p2/179/

01:16:55 EXEC : error : the following exception was thrown while processing profile data [d:\j\workspace\roslyn-intern---c8b69d52\Open\src\EditorFeatures\Core\3qkrx0rd.tmp_proj]
01:16:55   SigParsingException: *** Failed in GetMethodName() ***
01:16:55      at MDReader.GetMethodName(ModuleId moduleId, UInt32 methodToken, Byte*& genSig, String& returnType)
01:16:55      at MDReader.GetSigMethodInstantiation(Byte* sig, UInt32 size, String& typeInstantiation, String& returnType)
01:16:55      at IBCData.ParamSpecLookupName(MDReader mdr, UInt32 token)
01:16:55      at IBCRead.updateTokenData(String newExecutableName)
01:16:55      at IBCRead.readIncrementalIBCFromFile(String fileName)
01:16:55      at IBCMerge.Merge(String[] args)
01:16:55      at IBCMerge.Main(String[] args)
01:16:55 
d:\j\workspace\roslyn-intern---c8b69d52\Open\build\Targets\VSL.Imports.targets(278,5): error MSB3073: The command ""d:\j\workspace\roslyn-intern---c8b69d52\Closed\Tools\ibcmerge\ibcmerge.exe" -q -f -partialNGEN -minify -mo "d:\j\workspace\roslyn-intern---c8b69d52\Open\Binaries\Obj\EditorFeatures\Release\Microsoft.CodeAnalysis.EditorFeatures.dll" -incremental "d:\j\workspace\roslyn-intern---c8b69d52\Closed\Optimizat

**Comment by dpoeschl** [comment]
Got another hit of this.

**Comment by KevinH-MS** [comment]
@jmarolf is it possible to get the binaries from the output folder of the Jenkins build that failed?  I think it's going to be near impossible to diagnose this without that.  At the point of failure, ibcmerge's metadata reader is trying to look up the signature for a particular token in a particular module.  Those values aren't reproducible across builds, so I can't really reason about what's gone wrong.

**Comment by KevinH-MS** [comment]
I can't find the "artifacts" folder for either of these failures.  Talked with @davkean, and if we can try to fish out binaries for one of these failures, I can take a look, but failing that, I've got nothing to go on.
