### ISSUE TITLE
Please improve the documentation around which proposed features are on which branch

### ISSUE THREAD

**Issue by DavidArno** [dotnet/roslyn#9558]
Currently, we have a `future` branch a collection of `features/*` branches, each of which implement one or more proposed features for C# 7. It's possible to follow the instructions on the [Building Testing and Debugging](https://github.com/dotnet/roslyn/wiki/Building-Testing-and-Debugging) page to download and build one of these branches and then run Visual Studio to test them. However, not all branches appear to incorporate the language features within a test version of Visual Studio and there doesn't appear to be any documentation on what, for example, is available in the `future` branch.

Could someone create an appropriate (presumably community editable) wiki page to detail this info, please?

**Comment by jasonmalinowski** [comment]
Moving to Compiler since they know their branches.

**Comment by gafter** [comment]
The branches are documented at https://github.com/dotnet/roslyn/blob/master/docs/Language%20Feature%20Status.md
