### ISSUE TITLE
Package for Microsoft.CodeAnalysis.CSharp.EditorFeatures.Text

### ISSUE THREAD

**Issue by mynkow** [dotnet/roslyn#956]
Is there any nuget package for Microsoft.CodeAnalysis.CSharp.EditorFeatures.Text.dll?

I am trying to access http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures.Text/Extensions.cs

**Comment by Pilchie** [comment]
Yes - the one for CTP 6 is: http://www.nuget.org/packages/Microsoft.CodeAnalysis.EditorFeatures.Text/1.0.0-rc1
