### ISSUE TITLE
Sharpdevelop XAMl Designer Sample no longer works when compiled with Roslyn

### ISSUE THREAD

**Issue by jogibear9988** [dotnet/roslyn#957]
SD XamlDesigner Sample does not longer work when compiled with roslyn.

Exception:  The Ressource "icsharpcode.wpfdesign.designer;v5.1.0.4987;themes/icsharpcode.wpfdesign.designer;v5.1.0.4987;component/controls/controlstyles.xaml" could not be loaded.

The problam is it uses the Version in the XAML load string: {ICSharpCode.WpfDesign.Designer;v5.1.0.4987;component/Controls/ControlStyles.xaml}, wich worked when compiled with previous Version's, but now with VS2015 CTP6 not any more!

**Comment by jogibear9988** [comment]
Code: https://github.com/icsharpcode/SharpDevelop/tree/master/samples/XamlDesigner

**Comment by jogibear9988** [comment]
It now works.

I need to change the URI in my custom ResourceDictionary from 
       _uriStart = string.Format( @"{0};v{1};component/", nm.Name, nm.Version);
to
      _uriStart = string.Format( @"/{0};v{1};component/", nm.Name, nm.Version);

but I was wondering why it was working with the old compiler?

**Comment by jogibear9988** [comment]
This fixed the error:

https://github.com/jogibear9988/SharpDevelop/commit/25481b6c87dea614104ed40bf81c94509abc28f7

but I don't know why it worked before...

**Comment by theoy** [comment]
This is really surprising that switching to Roslyn would cause this to break - perhaps it there was a switch in the underlying URI library instead (at the same time)?

**Comment by jogibear9988** [comment]
I've SharpDevelop on the same Computer, wich compiles for DotNet 4.5 and there it works!

**Comment by VSadov** [comment]
@jogibear9988 - when you say "does not work", do you mean there are compiler errors or the code has different behavior when it runs?

**Comment by jogibear9988** [comment]
it does not run! compiling works!
it's now fixe in SharpDevelop, I only wanted to know why the Compiler causes this issue!

**Comment by jogibear9988** [comment]
I think it could not be a change in the Library, because 4.6 is a inplace update (or am I wrong). And it works when compiled with SD wich does not use Roslyn on the same machine!

**Comment by VSadov** [comment]
Could it be that the change is compensating for another change somewhere else? Is this string appended to something that is supposed to have / at the end.
It is hard to believe that the old compiler was inserting a / into a string literal, so I think the / came from somewhere else and now it is missing so this literal needs to be changed to compensate. The question is where and why a  / is missing...

**Comment by jogibear9988** [comment]
The only thing I can say, compiled on the same machine with SD it's working, with VS2015 it's not! 
The isusse is solved, but it would be interesting to know why the compilers work differently!
Couldn't you try it on your machine?
The Uri is used inter in the Microsoft Xaml parser, so I can not say if there is smthg. different!

**Comment by jaredpar** [comment]
Hey ​jogibear9988,
 
Thanks for taking the time to file this issue.  Looking at the issue though it doesn't appear to be a bug in the Roslyn compiler.  The code in this case is well tested and I verified the fix in question has the same behavior between the VS 2013 C# compiler and the Roslyn based compiler.  The issue instead appears to be in the XAML infrastructure.

**Comment by jogibear9988** [comment]
Does anyone look at this issue then? If it has nothing todo with rosly, why does it work when we use the unfixed Code and compile with VS2013 compiler?

**Comment by jaredpar** [comment]
@jogibear9988 I did look at this sample and I could find nothing that appeared to be a Roslyn issue in it.  I looked through the code in question, some of the generated outputs and nothing seemed to be amiss.  It appears to be a change in the XAML infrastructure which was causing it.

**Comment by jogibear9988** [comment]
but the error happens not when compiled with 2013, and happens when compiled with 2015 on the same machine with the same dotnet framework installed!

**Comment by VSadov** [comment]
@jogibear9988 - If you are still able to reproduce the scenario on your machine, could you collect IL (using ILDasm or ILSpy  tools) for the unfixed VersionedAssemblyResourceDictionary method in as it is compiled by the 2013 and 2015?

**Comment by jogibear9988** [comment]
Compiled with Roslyn:

![bildschirmfoto 2015-06-01 um 23 52 05](https://cloud.githubusercontent.com/assets/364896/7924216/c50e5132-08b9-11e5-846e-b59796614387.png)

Compiled with VS2013

![bildschirmfoto 2015-06-01 um 23 55 24](https://cloud.githubusercontent.com/assets/364896/7924228/dc50848c-08b9-11e5-98cc-56030b702d3a.png)

**Comment by jogibear9988** [comment]
For me it looks the same...

But I don't see a issue why the Code works when compiled with VS2013...

Maybe you can send the issue to the WPF/XAML Team?

**Comment by jogibear9988** [comment]
Any news to this?
I'm still interested why this happens!
