### ISSUE TITLE
Code Style: Introduce "suggestion" or "hint" classifications

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#9582]
Right now you can classify options with Error, Warning, or Info. Let's introduce a Suggestion or Hint that will help developers learn alternate ways of doing things.

From interviews with developer leads, this is especially helpful for junior developers.

**Comment by kuhlenh** [comment]
From our UX meeting, we landed on calling this a "Suggestion" and using a dotted, faded grey line (that extends up to the first 3 characters).

**Comment by paulomorgado** [comment]
@kuhlenh,

How is this any different from `Info`?

Why isn't this a vaild use for `Info`?

**Comment by Pilchie** [comment]
This is done in VS2017.
