### ISSUE TITLE
RPS and Jenkins should be isolated from Elfie database updates

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#9589]
We download package database in the background inside Visual Studio. This leads to non-deterministic results in test runs and performance runs. We should prevent this.

**Comment by davkean** [comment]
tag @jaredpar @CyrusNajmabadi

**Comment by DustinCampbell** [comment]
Yes, this needs to become deterministic.

**Comment by Pilchie** [comment]
We'll need to figure this out if we enable the feature by default.

**Comment by Pilchie** [comment]
Moving to RC.3 since this isn't enabled by default yet.

**Comment by Pilchie** [comment]
@CyrusNajmabadi if we're going to enable Add Nuget by default, we'll need a solution here.

**Comment by CyrusNajmabadi** [comment]
Haven't heard about this in years.  Closing out.
