### ISSUE TITLE
Please support generic constraint for hasA

### ISSUE THREAD

**Issue by Thaina** [dotnet/roslyn#9595]
Suppose we have a DotProduct function for Vector3

``` C#
public struct Vector3
{
    public float X,Y,Z;
    public float DotProduct(Vector3 a,Vector3 b)
    {
        return (float)Math.Sqrt((a.X * b.X) + (a.Y * b.Y) + (a.Z * b.Z));
    }
}
```

But we have another class which contain float X,Y,Z. 

``` C#
sealed class Position { public float X,Y,Z; }
```

And we just want to reuse DotProduct without the need to create new Vector3

So I think C# should support a function that could take generic and constraint with hasA style not only isA style

I mean normally generic constraint will only use `where T : SomeType`. I think in addition it should allow something like `where T : { float X,Y,Z }`

So for implementation it would be like this

``` C#
public static class VectorExt
{
    public static float DotProduct<V>(V a,V b) where V : {  float X,Y,Z }
    {
        return (float)Math.Sqrt((a.X * b.X) + (a.Y * b.Y) + (a.Z * b.Z));
    }
}
```

This style should also support extension method

``` C#
public static class VectorExt
{
    public static float DotProduct<V>(V a,V b) where V : { float X,Y,Z }
    {
        return (float)Math.Sqrt((a.X * b.X) + (a.Y * b.Y) + (a.Z * b.Z));
    }

    public static float GetLength<V>(this V v) where V : { float X,Y,Z }
    {
        return DotProduct(v,v);
    }

    // This would be great if this kind of constraint also support extension method
    public static int CompareLength<V>(this V l,this V r) where V : { float GetLength() }
    {
        return Math.Sign(l.GetLength() - r.GetLength());
    }
}

public struct Vector3
{
     public float X,Y,Z;
     public Length { get { return this.GetLength(); // Extension method from VectorExt } }
}
```

**Comment by svick** [comment]
This looks like a variant of structural typing (#7844, #2146) and I'm pretty sure it would require CLR support (#420).

**Comment by orthoxerox** [comment]
@svick this feature doesn't necessarily require CLR support to work (F* has dependent types and effects without CLR support), but CLR support is necessary to avoid type erasure.

**Comment by svick** [comment]
@orthoxerox If type erasure was used, how would the generated IL actually access the members? Using  `dynamic`?

**Comment by orthoxerox** [comment]
@svick it could emit specialized methods for each type, for example. Or use `dynamic`, yes.

**Comment by Thaina** [comment]
All along I was thinking that generic is always emit specialize code for each type

When we make a generic class with static array for example
```
class A<T>
{
    public static T[] Items = new T[];
}

A<int>.Items == A<string>.Items; // false
```
we will get difference array for each type we put in, especially for struct because each struct has difference memory size

So I think it would be the same for method. Generic should and could emit specific code for each type we put in, that's why I propose this kind of functionality as generic constraint

And I would love it to be generic constraint because dynamic is not efficient while generic constraint is very efficient
What I know is it would transform the code for each type we put it, if we make generic function with constraint interface and put struct into that function it will be faster than put that struct into another function that take in interface directly

For example
```
public interface IVector
{
    public float X { get; set; }
    public float Y { get; set; }
    public float Z { get; set; }
}
public static class VectorExt
{
    //// This is less efficient, at least it cause a type cast if it take in struct
    public static float DotProduct(IVector a,IVector b)
    {
        return (float)Math.Sqrt((a.X * b.X) + (a.Y * b.Y) + (a.Z * b.Z));
    }

    //// This will be more efficient to any type
    public static float DotProduct<V>(V a,V b) where V : IVector
    {
        return (float)Math.Sqrt((a.X * b.X) + (a.Y * b.Y) + (a.Z * b.Z));
    }
}
```

In my opinion, C# generic is (or should be) a little bit of efficient metaprogramming. To implement it as dynamic defeat the purpose

And while generic will emit specialize code for type. It should be able to handle constraint of everything  include field and static things, we just have no syntax to put it after where clause

**Comment by alrz** [comment]
Related: #154 #8986

**Comment by Thaina** [comment]
@alrz That's right the concept is similar. But I think it would be better to keep it limit in only where clause. If we need to defined trait we need to import new keyword, handle it on all existing method. That would be overkill and confusing with interface

This kind of constraint syntax may limit like constraint class/struct. while we could constraint that it must be struct on the first, this must be on the last constraint. And may be able to shorthand with using

```C#
using TraitVsmall = { float x,y,z };
using TraitVLarge = trait { float X,Y,Z }; // Alternatively, we could have trait as keyword only in scope of using if the above syntax is confuse with something

public static class VectorExt
{
    public static float RefDotProduct<V>(ref V a,ref V b) where V : struct,IComparable<V>,{ float X,Y,Z }
    {
        return (float)Math.Sqrt((a.X * b.X) + (a.Y * b.Y) + (a.Z * b.Z));
    }

    // this will error, trait must be last and only one
    public static float ErrorRefDotProduct<V>(ref V a,ref V b) where V : struct,{ float X,Y,Z },IComparable<V>
    {
        return (float)Math.Sqrt((a.X * b.X) + (a.Y * b.Y) + (a.Z * b.Z));
    }

    // this use a shorthand from using
    public static float RefDotProductSmall<V>(ref V a,ref V b) where V : struct,IComparable<V>,TraitVsmall
    {
        return (float)Math.Sqrt((a.x * b.x) + (a.y * b.y) + (a.z * b.z));
    }
}
```

**Comment by alrz** [comment]
>if we need to defined trait we need to import new keyword, handle it on all existing method. That would be overkill and confusing with interface

So you're avoiding a new keyword? Your example is a hodgepodge of new syntaxes.

**Comment by alrz** [comment]
@orthoxerox `dynamic` is not a workaround for everything that doesn't fit into type system, it just facilitates incorporation with dynamic languages. You, as a programmer, should not use it wherever the type system doesn't sufficiently satisfies your needs, and if the compiler siletly use it I would have a heart attack immediately.

**Comment by Thaina** [comment]
@alrz Yes it is new syntax but it scope in only after where clause. So it limit the place it will break with other things. And no new syntax and keyword in wider scope than that

I am totally agree with your point about dynamic

**Comment by alrz** [comment]
@Thaina You're trying to shove all the member constraints inside of the `where` clause, that doesn't necessarily simplifies the implementation, rather it complicates the readability and parsing outside of simple cases (which I doubt that the proposed syntax is able to represent). All in all, there are numerous proposal for this scenario, I'm not fond of any syntaxes here but the thing is that this definitely needs CLR support to be usable outside of the assembly boundaries, otherwise you will end up with something like #8986 to not infer public contract from usage which will be hard to reason about — I'm assuming that #8986 already dismissed.

**Comment by Thaina** [comment]
@alrz Yes, because most of generic constraint function most likely a simple 2-3 members. It promote modularity and decoupling that a function should not do so much work and should decouple as much as possible. We always just need a little set of member. And then we could reuse other generic function that share the same constraint

So we actually don't need to constraint many things if we build things with this syntax. Vector struct could contain just float X,Y,Z and all other functions could implement with this method. Then the new method could reuse 

Think about less is more, this work like linq that it could chain with another linq with just IEnumerable that need a class to implement only 2 member


And as for larger than that, if it really really needed, I already suggest `using` keyword to make it shorthand for large things and it will work fine

**Comment by orthoxerox** [comment]
@alrz I am not proposing that we *use* `dynamic` for this feature at all, I'd rather get some proper CLR support instead.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
