### ISSUE TITLE
The presence of a Priority Low fix causes ExtensionOrdering amongst Medium Priority fixes to be violated

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#9596]
http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p2/415/artifact/Open/Binaries/Release/VSIntegrationTestLogs/CSharpCodeActions.html

Rename Tracking is still provided, and the ordering between it and Generate Type wrong:
 
![image](https://cloud.githubusercontent.com/assets/235241/13629372/8bc65080-e58d-11e5-9502-93fd59af571f.png)

Original fix ordering based on extension order:

- Fix A, ExtensionOrder 0, Priority Low, for Diagnostic 1
- Fix C, ExtensionOrder 1, Priority Medium, for Diagnostic 2
- Fix B, ExtensionOrder 2, Priority Medium, for Diagnostic 1

Grouped by diagnostic:

- Diagnostic 1
    - Fix A, ExtensionOrder 0, Priority Low
    - Fix B, ExtensionOrder 2, Priority Medium

- Diagnostic 2
    - Fix C, ExtensionOrder 1, Priority Medium

After "Priority Low" Items moved to the bottom:

- Fix B, ExtensionOrder 2, Priority Medium
- Fix C, ExtensionOrder 1, Priority Medium
- Fix A, ExtensionOrder 0, Priority Low

**Comment by dpoeschl** [comment]
Fix rejected for 1.2. Moving to 1.3 (FYI @DustinCampbell @CyrusNajmabadi)

**Comment by Pilchie** [comment]
We pulled this back into 1.2 and merged the PR (#9572)
