### ISSUE TITLE
Conditional Compilation in XML Comments

### ISSUE THREAD

**Issue by RxDave** [dotnet/roslyn#96]
Please support conditional compilation within XML documentation comments. This has been a source of pain since portable libraries came on the scene a while ago. Often linked code files are used to share source between different target platforms of the same API; however, as a result often times the documentation comments must change conditionally as well. As of now, there's no good way around this limitation - you have to duplicate the entire XML comments conditionally, rather than just each section or line.

For example, I'd like to do this: 

``` C#
  /// <summary>
  /// Summary for Foo.
  /// </summary>
  /// <remarks>
  /// <para>Foo is great.</para>
#if !PORTABLE_403
  /// <para>Foo works well with <see cref="INotifyCollectionChanged"/>.<para>
#endif
  /// <para>Did I mention Foo is great?</para>
  /// </remarks>
  public void Foo() { ... }
```

`INotifyCollectionChanged` is not defined in .NET 4.0.3, so when targeting .NET 4.0.3 with a portable library the paragraph referencing it must be elided from the documentation.

**Comment by RxDave** [comment]
(Copied from https://roslyn.codeplex.com/workitem/492)

**Comment by sharwell** [comment]
:dancers: :+1:

**Comment by sharwell** [comment]
Another related issue is XML documentation comments cannot be applied to a `#if` directive. For example:

```csharp
/// <summary>Things</summary>
#if NET40PLUS
public interface IFoo<out T>
#else
public interface Foo<T>
#endif
{
}
```

**Comment by DustinCampbell** [comment]
:+1:

**Comment by RxDave** [comment]
@sharwell Yea, that's another source of pain for me too. But I wonder if it's mostly because I'm trying to workaround the stated limitation. :-)

**Comment by dotMorten** [comment]
Just casting my vote on this as well. We have to do the #if-def on the entire code-summary, which is a significant duplication of XML code comments.

**Comment by sharwell** [comment]
@dotMorten There are a few different ways to work around this. Of particular note is the `<token>` extension provided by Sandcastle Help File Builder (SHFB), which allows you to define parts of the comment separately from the comment in code. The latest release of SHFB introduces editor support for tokens which appear in code (hover tips + go to definition).

**Comment by dotMorten** [comment]
@sharwell Yes other tools have more functionality, or you could write your own buildtask that performs some XML operations. However the generated xml is also used for intellisense, and should be generated correctly and not having to be post-processed through a 3rdparty tool afterwards. We can work around a lot of stuff, or we can improve the compiler so we don't have to rely on multiple follow-on steps. As other people describe above, you can work around all of this, so no this isn't a showstopper, but it's really ugly and inefficient.

**Comment by sharwell** [comment]
@dotMorten Agreed, just trying to save you some time in the meantime :+1:

**Comment by NickCraver** [comment]
So, we have a use for this in Dapper as well, same situation since some members we `<see cref />` aren't in .NET Core. For example:

```xml
        /// <summary>
        /// Execute parameterized SQL and return an <see cref="IDataReader"/>
        /// </summary>
        /// <returns>An <see cref="IDataReader"/> that can be used to iterate over the results of the SQL query.</returns>
        /// <remarks>
        /// This is typically used when the results of a query are not processed by Dapper, for example, used to fill a <see cref="DataTable"/>
#if !COREFX
        /// or <see cref="DataSet"/>.
#endif
        /// </remarks>
        /// <example>
        /// <code>
        /// <![CDATA[
        /// DataTable table = new DataTable("MyTable");
        /// using (var reader = ExecuteReader(cnn, sql, param))
        /// {
        ///     table.Load(reader);
        /// }
        /// ]]>
        /// </code>
        /// </example>
        public static IDataReader ExecuteReader(
```

...which of course won't compile. Can we get some love here?

**Comment by terrajobst** [comment]
I assume that's a limitation in the C# parser? I don't see why conditional compilation inside of doc comments wouldn't work.

**Comment by dotMorten** [comment]
@terrajobst I can't say why it wouldn't work. All I can say is that it doesn't and never did :)

**Comment by NickCraver** [comment]
For others finding this: my *specific* case is solved by `<see cref="T:DataSet"/>` (thanks @davkean), but the issue for comments that should vary across platforms (e.g. different examples) is still valid.

**Comment by dotMorten** [comment]
Just adding my example here (from the duplicate issue above):

**Steps to Reproduce**:

1. Create the following property with doc in a class:
```csharp
        /// <summary>
        /// Turns the GPS on or off
        /// </summary>
        /// <remarks>
        /// <para>Will turn on the system location service.</para>
#if NETFX_CORE
        /// <para>Make sure you have enabled the location capability in your appx manifest.
        /// See https://msdn.microsoft.com/en-us/library/windows/apps/br211423.aspx
        /// for more information
        /// </para>
#elif __ANDROID__
        /// <para>
        /// Make sure you have enabled location in your app manifest. 
        /// See http://developer.android.com/guide/topics/manifest/manifest-intro.html 
        /// for more information.
        /// </para>
#endif
        /// </remarks>
        public bool IsGpsEnabled { get; set; }
```
2. Enable XML documentation generation 
3. Build

**Expected Behavior**:
No build warnings. XML is generated with platform specific remarks. This allows me to add a couple of platform specific remarks. Currently you have to if-def the entire code summary section, causing a lot of documentation to be duplicated. 

**Actual Behavior**:
Several build warnings
```
warning CS1570: XML comment has badly formed XML -- 'Expected an end tag for element 'remarks'.'
1>\Class1.cs(25,13,25,14): warning CS1570: XML comment has badly formed XML -- 'End tag was not expected at this location.'
1>\Class1.cs(9,18,9,24): warning CS1591: Missing XML comment for publicly visible type or member 'Class1'
1>\Class1.cs(11,9,11,10): warning CS1587: XML comment is not placed on a valid language element
```
And the generated XML:

```xml
<?xml version="1.0"?>
<doc>
    <assembly>
        <name>ClassLibrary1</name>
    </assembly>
    <members>
        <!-- Badly formed XML comment ignored for member "P:ClassLibrary1.Class1.IsGpsEnabled" -->
    </members>
</doc>
```

**Comment by MadsTorgersen** [comment]
This seems worthwhile, but we are unsure how deep the impact would be on the Roslyn compiler. The easier the fix, the sooner we'd be likely to do it!

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.

**Comment by dotMorten** [comment]
@sharwell @RxDave @airbreather @DustinCampbell @nhaslam11 I've logged a new issue in the new repo (link above this comment) for you to thumbs up there instead.
Not sure why the Roslyn team are closing these issues left and right, and leave them to die, and I especially don't get why this is a language design issue when it's the conditionals that aren't handled right ?

**Comment by NickCraver** [comment]
I have no idea about the closing either, it's very off-putting to the community in the worst way. I just got an inbox full of "we don't care about this anymore, see ya".

I appreciate the re-filing @dotMorten; added my upvote. I just hit this again in MiniProfiler and have duplicated XML instead, rather than just the 1 param that's TFM specific.

**Comment by gafter** [comment]
Conditionals and preprocessor directives are [specified as part of the lexical structure of the language](https://github.com/dotnet/csharplang/blob/master/spec/documentation-comments.md#introduction). Consecutive doc-comment lines (the spec's "the next line") are merged to construct the XML. But because of the presence of the preprocessor directives, they are not consecutive any longer (it is not continued onto the next line).

So the compiler just obeys the spec here. If we want a change, we need to change the spec (and then the compiler).

**Comment by gafter** [comment]
I have not moved this feature request to the csharplang repo because I don't believe it would ever rise in priority over other requests to be something we would ever do in any particular release. However, you are welcome to move discussion to the new repo if this still interests you.

**Comment by dotMorten** [comment]
I think the spec leaves plenty of room for interpretation.

> The conditional compilation directives are used to conditionally include or exclude portions of a source file.

If the section is excluded, that means the doc comments in fact does become consecutive.

> The selected conditional_section, if any, is processed as a normal input_section: the source code contained in the section must adhere to the lexical grammar; tokens are generated from the source code in the section; and pre-processing directives in the section have the prescribed effects.

and

> The remaining conditional_sections, if any, are processed as skipped_sections: except for pre-processing directives, the source code in the section need not adhere to the lexical grammar; 

After excluding/including the section, the source code now adheres to the lexical grammar.

These directives are called _pre_ processing for a reason. If you pre-process the code, then the documentation is in fact following the spec.

**Comment by gafter** [comment]
@dotMorten Preprocessing occurs as part of lexical analysis. It changes what tokens proceed to syntactic analysis, but it cannot change what text is on the "next line" _during lexical analysis_, which is when doc comments are identified.

**Comment by FransBouma** [comment]
@gafter 
> Preprocessing occurs as part of lexical analysis. It changes what tokens proceed to syntactic analysis, but it cannot change what text is on the "next line" during lexical analysis, which is when doc comments are identified.

I don't follow why that blocks this problem from fixing it: the lines with `#ifdef` and #endif` are not lines containing any tokens for syntactic analysis. So if I have:

```cs
/// blabla1
#ifdef FOO
/// blabla2
#endif
/// blabla3
```
this will result in:
with FOO defined:
```cs
/// blabla1
/// blabla2
/// blabla3
```
with FOO undefined
```cs
/// blabla1
/// blabla3
```
It doesn't change anything, it simply doesn't pass the lines with the preprocessor directives and the lines in between on to syntactic analysis. This can work as the EOL non-terminals in the pre-processor directive lines are mandatory and part of the pre-processor statements. 

Or am I overlooking something?

**Comment by sharwell** [comment]
@gafter Do you still have the automated tool for moving these over? Depending on the role/scope I play in moving some of the documentation comment requests forward, I could certainly see this as one of the relevant ones.
