### ISSUE TITLE
Huge memory leak when creating types with Roslyn

### ISSUE THREAD

**Issue by gsantopaolo** [dotnet/roslyn#9600]
**Version Used**:  Microsoft.CodeAnalysis.CSharp 1.1.1  (  Install-Package Microsoft.CodeAnalysis.CSharp -Version 1.1.1 ) 
.Net Framework 4.5.2
Visual Studio 2015 UP1

**Steps to Reproduce**: execute method at the following link: [http://pastebin.com/gSVzZV1E](http://pastebin.com/gSVzZV1E)

by calling it like that way [http://pastebin.com/5YD8Me4m](http://pastebin.com/5YD8Me4m)

**Expected Behavior**: No leak
**Actual Behavior**: 20+Mb memory used and not released each time invoked

Do you have any solution to this?

**Comment by leppie** [comment]
`dynamicReferences` is static, and you keep adding to it.

**Comment by KevinH-MS** [comment]
:+1: to @leppie 's analysis.  I think the issue here is just the static "cache".  I'm not sure what the overall goals for your API are, but perhaps this cache could somehow be attached to the ```TypeGenerationResult``` and explicitly passed to subsequent calls to ```TypeGenerator.GenerateType``` (to avoid the static)?
