### ISSUE TITLE
[Test Failure] Individual TAO Test (CSharpLinkedFile.xml) Failure in prtest/win/vsi/p2 on PR #9601

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#9602]
PR: [#9601](https://github.com/dotnet/roslyn/pull/9601) _Fixed race in diagnostic tagger_ by @heejaechang
Failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p2/438/

**5 Test Failures:**
CSharpLinkedFile.Verify if projects have been set up correctly with conditional compilation symbols
CSharpLinkedFile.Verify adding a linked file to another project when the file is open in the editor from the original host project
CSharpLinkedFile.Verify union intellisense Intellisense: Intellisense Tooltip
CSharpLinkedFile.Verify Union Intellisense: Signature Help
CSharpLinkedFile.Verify Union Intellisense: Quickinfo

**Issue 1: Individual TAO Test Failure**
Failing integration tests: 

CSharpLinkedFile.xml

....

it locally passes on my dev box

Bounty

**Comment by davkean** [comment]
Hit this again: http://dotnet-ci.cloudapp.net/job/roslyn-internal_future-stabilization_win_vsi_p2/26/

**Comment by Pilchie** [comment]
Can you look at this since @dpoeschl is out this week?

**Comment by jasonmalinowski** [comment]
Roger.

**Comment by davkean** [comment]
I'm marking this as blocked as you're waiting on it to fail with the extra logging, right?

**Comment by jasonmalinowski** [comment]
Indeed, just waiting for any repro now.

**Comment by jasonmalinowski** [comment]
Haven't a repro recently, so we'll close this until we see one again and then look at the logs.

**Comment by jasonmalinowski** [comment]
And sure enough, by saying that one triggers in #11318:

http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_vsi2/99/consoleFull

**Comment by jasonmalinowski** [comment]
@balajikris: let's continue the conversation hon #11318's failure here. So, in hindsight, perhaps I should have logged the expected/actual text...?

**Comment by balajikris** [comment]
I don't have any previous context on the failure and the logs don't tell me anything substantial. Did the screenshots have anything useful ?

**Comment by balajikris** [comment]
New instance of this failure: http://dotnet-ci.cloudapp.net/job/roslyn-internal_master_win_vsi_p2/1298/

**Comment by tmat** [comment]
One more:
http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_vsi_p2/620/

**Comment by jasonmalinowski** [comment]
This test system was deprecated months ago.
