### ISSUE TITLE
Idea: Simplify null check syntax

### ISSUE THREAD

**Issue by christianarg** [dotnet/roslyn#9606]
**Context**
C#6 incorporated the very handy ?. operator. This way I can change this

`if(someClass != null && someClass.someField == "someValue)
{
  ..
}
`

into this:

`if(someClass?.someField == "someValue)
{
  ..
}
`

That's pretty nice.

**Idea**

When I have to check if a variable is null, I have to do this:

`if(someVariable == null)
{
..
}`

Wouldn't it be nice if we could do something like this:

`
if(someValue?)
{
..
}
`

The counter part is, if I want to check if a variable is NOT null, what would be do? this?:

`
if(!someValue?)
{
..
}
`

Kinda ugly.

What about this?:

`
if(someValue!?)
{
..
}
`

Bit weird. Probably something better but you get the idea.

Thoughts? Handy or perhaps too much syntax sugar?

**Comment by HaloFour** [comment]
You'll get this with pattern matching:

```cs
if (someValue is SomeClass { SomeField is "SomeValue" }) { ... }
```

Are you otherwise proposing a new Boolean operator to detect whether or not a value is `null`?

**Comment by svick** [comment]
I *think* this syntax would be ambiguous with the ternary operator: if you have two `?` before a single `:`, how is the compiler (and the programmer) supposed to figure out which one is for the ternary operator and which one is for your proposed null check operator?

I'm unable to come up with a reasonably simple compiling example. But my problem is mostly to get the types right and the parser doesn't take types into account, so I think it's still an issue.

**Comment by alrz** [comment]
```cs
r = e??e:e;
```
this is not ambiguous but needs look ahead to figure out it's not a null coalescing operator.

**Comment by alrz** [comment]
```cs
e?.M();
```
But this is ambiguous, however compiler could parse it as a null conditional when you dot off a "null check expression".

**Comment by svick** [comment]
@alrz I meant something like `a? +a? +a : a`, which could be either interpreted as `(a != null) + a ? (+a) : a` or as `a ? ((+a) != null) + a : a` (both interpretations can actually compile, if the type of `a` is crazy enough to overload the necessary operators).

**Comment by alrz** [comment]
@svick I see. If it was a *prefix operator*, then it woudn't be ambiguous in this example at least,
```cs
?a ?+a +a : a
(a != null) ? +a+a : a
```
But still parsing is a little tricky. Also, just like `throw` expression, it could be restricted to some specific contexts such as first operand of the ternary operator, conditional expression of the if statement and so on.

**Comment by HaloFour** [comment]
Outside of the simplest of cases this "operator" produces some really confusing looking code.  I don't think it's worth it just to avoid typing a few extra characters.  Null propagation and pattern matching should eliminate most of the "need" of something like this anyway.

**Comment by alrz** [comment]
>Outside of the simplest of cases

@HaloFour That was my point, if the context is restricted the it woudn't be possible to use it out of the simplest of cases, just directly inside `if` and other *conditional-expression*s.

**Comment by Unknown6656** [comment]
and what about the character 'backtick-character' (`` ` ``)? As far as I know, it does not have a great usage inside C#....
One could use it like this:

    int? a = null;
    if (`a) ....   // true
    int b = `a ? 1 : 2;

alternatively, I like the syntax of angled brackets, but it would be confusing:

    int? a = null;
    if ([a]) .... // true
    int b = [a] ? 1 : 2;

**Comment by Miista** [comment]
Let's not add syntactic sugar for the sake of adding syntactic sugar.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.

**Comment by MillKaDe** [comment]
There are two similar proposals / discussions:

A newer one in [C#Lang](https://github.com/dotnet/csharplang) : [#196](https://github.com/dotnet/csharplang/issues/196) : **Discussion: `null` evaluation operator to boolean**

An older one in [Roslyn](https://github.com/dotnet/roslyn) : [#11577](https://github.com/dotnet/roslyn/issues/11577) : **[Proposal] Simplify boolean test of null with objects**
