### ISSUE TITLE
nameof operator and ambiguity

### ISSUE THREAD

**Issue by marek-safar** [dotnet/roslyn#9607]
**Version Used**:  1.2.0.60220

**Steps to Reproduce**:

Compile following

```
interface IA
{
	void M (int arg);
	int Prop { get; set; }
}

interface IB
{
	void M (string arg);
	void M (int arg);
	void M<T> (T arg);
	int Prop { get; set; }
}

interface I : IA, IB
{
	void Extra (string method = nameof (M), string prop = nameof (Prop));
}
```

**Expected Behavior**:

No compilation error.

**Actual Behavior**:

error CS0229: Ambiguity between 'IA.Prop' and 'IB.Prop'

`nameof` operator cares only about name not actual types which compiler does in method `M` case but it does not for `Prop` property.

**Comment by gafter** [comment]
I will investigate but I believe this is by design. `nameof()` can work on a method group after name lookup, but here the error arises during name lookup.

**Comment by marek-safar** [comment]
I understand this is probably not spec covered but we should still aim for sensible behaviour and there is nothing ambiguous about Prop name in this context

**Comment by gafter** [comment]
@marek-safar The problem is that this *is* spec-covered, as the spec specifies that `nameof` begins with a name lookup, which in this case results in an ambiguity.
