### ISSUE TITLE
Compiler crash with pattern-matching

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#9626]
The attached project crashes the compiler prototype for pattern-matching:

![image](https://cloud.githubusercontent.com/assets/3804346/13650669/9d0ad40e-e5f8-11e5-98e6-8ef0855dc9a1.png)

[PatternSample.zip](https://github.com/dotnet/roslyn/files/166103/PatternSample.zip)

**Comment by AlekseyTs** [comment]
I can compile successfully using csc.exe, but the executable crashes at runtime:
```
Unhandled Exception: System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Program.<Main>g__Derivative0_3(Expression expr)
   at Program.<Main>g__Derivative0_3(Expression expr)
   at Program.<Main>g__Derivative0_3(Expression expr)
   at Program.<Main>g__Derivative0_3(Expression expr)
   at Program.Main(String[] args)
```

**Comment by markhurd** [comment]
I assume the runtime "crash" is expected as there's no match case for X yet.

**Comment by gafter** [comment]
@AlekseyTs That is a different problem from the compiler crash. It is possible the compiler crash has been fixed.

**Comment by gafter** [comment]
This is not reproducible on the `features/patterns` branch.
