### ISSUE TITLE
[Test Failure] <description> in prtest/win/vsi/p1 on PR #9588

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#9629]
PR: [#9588](https://github.com/dotnet/roslyn/pull/9588) *Revert "Revert "Merge pull request #6636 from CyrusNajmabadi/asyncLazy""* by @CyrusNajmabadi
Failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p1/422/

No Console Session

Tao cannot take screenshots, so we're probably not running in a console session. Halting the test run because this can cause unexpected test failures. No tests were run because the test runner was unable to take screenshots. If this happens on a CI machine, make sure all user sessions are properly disconnected. Please notify @dotnet/roslyn-infrastructure if you see this error.

**Comment by davkean** [comment]
This has been fixed.
