### ISSUE TITLE
VB - Optimized compilation of async method skips disposal if enumeration happened last

### ISSUE THREAD

**Issue by brandondahler** [dotnet/roslyn#9639]
**Version Used**: 
VS 2015 Update 1 Enterprise
.NET Framework 4.6
Visual Basic Compiler version 1.1.0.51204

**Steps to Reproduce**:
1. Compile VB Console Application below with optimizations on.
2. Execute program

**Expected Behavior**:
Console should output "Disposed".

**Actual Behavior**:
Console outputs "Finaiized".

**Work Arounds**:
- Compile without optimizations on; or
- Uncomment GC.KeepAline(...) line; or
- Use C# (bug not exhibited using equivalent code)

**Code**:
```
Module Module1
    Private Class Disposable
        Implements IDisposable

        Protected Overrides Sub Finalize()
            Console.WriteLine("Finalized")
        End Sub


        Public Sub Dispose() Implements IDisposable.Dispose
            Console.WriteLine("Disposed")
            GC.SuppressFinalize(Me)
        End Sub
    End Class

    Sub Main()
        Test().Wait()
    End Sub

    Private Async Function Test() As Task
        Using disposable = New Disposable()
            For Each p In System.Linq.Enumerable.Range(0, 10)
                Await Task.Yield()
            Next

            'GC.KeepAlive(disposable)
        End Using
    End Function

End Module
```

PS:
Sorry if this isn't the correct place for this type of bug report.  If it is not, can someone point me in a better direction?

Brandon Dahler

**Comment by HaloFour** [comment]
It also works if you add another member to `Disposable` and then call it explicitly after the `Await` loop.  I'm thinking that the VB.NET compiler is optimizing away lifting the `disposable` local to a field on the state machine which is resulting in the local remaining `Nothing` after the continuation resumes.  You get the same behavior if you write that expansion yourself.  I don't know what 2013 does but this definitely sounds like a regression/bug.

**Comment by HaloFour** [comment]
Also seems to affect simple cases like this:

```cs
Dim s As String = "Hello"
Try
    For i As Integer = 1 To 2
        Await Task.Yield()
    Next i
Finally
    Console.WriteLine(s) ' oops, s is Nothing now
End Try
```

Removing the loop does make this work.

**Comment by jaredpar** [comment]
Thanks for reporting this issue.  It appears to be a dupe of #7669.  @VSadov can you verify that is the case?

**Comment by brandondahler** [comment]
This appears to have been fixed with Microsoft (R) Visual Basic Compiler version 1.2.0.60317 that was released via Visual Studio 2015 Update 2.  

Thanks all involved :+1:
