### ISSUE TITLE
Portable C# targets reference targets file with incorrect casing.

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#9641]
The `Microsoft.Portable.CSharp.targets` file in both the `v4.5` and `v5.0` directories reference the `Microsoft.CSharp.Targets` file. The file is actually named `Microsoft.CSharp.targets`. On case-sensitive file systems this presents an issue.

See build_toolset.ps1 in https://github.com/dotnet/roslyn/pull/9635

**Comment by rchande** [comment]
This has been fixed.
