### ISSUE TITLE
Analyzer in csproj.user file is not properly picked up

### ISSUE THREAD

**Issue by tvsonar** [dotnet/roslyn#9644]
When putting an `Analyzer` item in the `csproj.user` file, the analyzers are not properly loaded. The analyzer references show up in the `References/Analyzers` in the Solution Explorer, and even the underlines, fadings work in the code editor windows, but the issues (error/warning/info) don't show up in the Error Window.

**Version Used**: Visual Studio 2015 Update 1

**Steps to Reproduce**:

1. Create a project and add a NuGet analyzer package.
2. Create a user file for the project
3. Copy the Analyzer references from the csproj to the csproj.user
4. Close Visual Studio
4. Open the solution again

**Expected Behavior**: everything should work as before

**Actual Behavior**: the issues don't show up in the Error Window.

If I do a build or a project unload and reload, then the issues start to show up.

**Comment by mavasani** [comment]
This doesn't seem to be repro with the latest Roslyn bits - can you please try again on VS2015 Update3 RC?

**Comment by tvsonar** [comment]
Sorry for not coming back earlier on this. I can confirm that it's working in VS2015 Update3.
