### ISSUE TITLE
GenerateNullCoalescingBadBinaryOpsError crashes

### ISSUE THREAD

**Issue by lachbaer** [dotnet/roslyn#9645]
**Version Used**: current future branch

**Steps to Reproduce**:

`StringBuilder sb = null ?? throw new ArgumentNullException();`

**Actual Behavior**: (BoundThrowException)rightOperand.Display == null in GenerateNullCoalescingBadBinaryOpsError raises Debug.Assert in AssertMessageSerializable

**Comment by gafter** [comment]
This would be fixed in the pending #9935

**Comment by gafter** [comment]
Fixed in branch `features/patterns`.
