### ISSUE TITLE
[Test Failure] Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameEngineTests.LocationsIssue

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#9652]
PR: [#667#issuecomment-194956663](https://github.com/dotnet/roslyn-internal/pull/667#issuecomment-194956663) *Update InstallDogfood app.manifest to no longer require admin.* by @tannergooding
Failure: http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_dbg_unit32/772/

**1 Test Failures:**
Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameEngineTests.LocationsIssue

**Issue 1: No identified problem**
No problems were identified. If you know why this problem occurred, please add a suitable Cause for it.

**Comment by dpoeschl** [comment]
Another repro of #9308 (cc: @davkean @jasonmalinowski)
