### ISSUE TITLE
Microsoft.VisualStudio.LanguageServices.UnitTests.Progression.InheritsGraphQueryTests.TestSolutionWithMultipleProjects (from Roslyn.VisualStudio.Services.UnitTests)

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#9653]
http://dotnet-ci.cloudapp.net/job/roslyn_future-stabilization_win_dbg_unit64/lastCompletedBuild/testReport/Microsoft.VisualStudio.LanguageServices.UnitTests.Progression/InheritsGraphQueryTests/TestSolutionWithMultipleProjects/

_Edit by @brettfo:_
[Direct link to failing test](http://dotnet-ci.cloudapp.net/job/roslyn_future-stabilization_win_dbg_unit64/14/testReport/junit/Microsoft.VisualStudio.LanguageServices.UnitTests.Progression/InheritsGraphQueryTests/TestSolutionWithMultipleProjects/)
_End edit_

Microsoft.VisualStudio.LanguageServices.UnitTests.Progression.InheritsGraphQueryTests.TestSolutionWithMultipleProjects (from Roslyn.VisualStudio.Services.UnitTests)

Failing for the past 1 build (Since Failed#14 )
Took 0.79 sec.
add description
Stacktrace

MESSAGE:
Assert.Equal() Failure\r\n ↓ (pos 101)\r\nExpected: ··· <Node Id="(@1 Type=A)" Category="CodeSchema_Class" CodeSchem···\r\nActual: ··· <Node Id="(@1 Type=B)" Category="CodeSchema_Class" CodeSchem···\r\n ↑ (pos 101)
+++++++++++++++++++
STACK TRACE:
at Microsoft.VisualStudio.LanguageServices.UnitTests.Progression.ProgressionTestHelpers.AssertSimplifiedGraphIs(Graph graph, XElement xml) in d:\j\workspace\roslyn_future---1b3baacd\src\VisualStudio\Core\Test\Progression\ProgressionTestHelpers.vb:line 42 at Microsoft.VisualStudio.LanguageServices.UnitTests.Progression.InheritsGraphQueryTests.VB$StateMachine_3_TestSolutionWithMultipleProjects.MoveNext() in d:\j\workspace\roslyn_future---1b3baacd\src\VisualStudio\Core\Test\Progression\InheritsFromGraphQueryTests.vb:line 94 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by davkean** [comment]
This failed lots more times:
http://dotnet-ci.cloudapp.net/job/roslyn_master_win_dbg_unit64/1011/testReport/Microsoft.VisualStudio.LanguageServices.UnitTests.Progression/InheritsGraphQueryTests/TestSolutionWithMultipleProjects/
http://dotnet-ci.cloudapp.net/job/roslyn_master_win_dbg_unit64/1010/testReport/Microsoft.VisualStudio.LanguageServices.UnitTests.Progression/InheritsGraphQueryTests/TestSolutionWithMultipleProjects/
http://dotnet-ci.cloudapp.net/job/roslyn_master_win_dbg_unit64/1009/testReport/Microsoft.VisualStudio.LanguageServices.UnitTests.Progression/InheritsGraphQueryTests/TestSolutionWithMultipleProjects/
http://dotnet-ci.cloudapp.net/job/roslyn_master_win_dbg_unit64/1008/testReport/junit/Microsoft.VisualStudio.LanguageServices.UnitTests.Progression/InheritsGraphQueryTests/TestSolutionWithMultipleProjects/

**Comment by brettfo** [comment]
None of those failures have the changes I made in #9944 that will make diagnosing this easier.  `git branch --contains` shows that `master` has the appropriate changes, but it doesn't look like they were there by the time these failures occurred.

**Comment by davkean** [comment]
Here another failure: https://github.com/dotnet/roslyn/issues/10196.

**Comment by brettfo** [comment]
According to the failure [here](http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/5685/) there was an error creating the graph.  Investigating further.

Expected:

``` XML
<DirectedGraph xmlns="http://schemas.microsoft.com/vs/2009/dgml">
  <Nodes>
    <Node Id="(@1 Type=A)" Category="CodeSchema_Class" CodeSchemaProperty_IsPublic="True" CommonLabel="A" Icon="Microsoft.VisualStudio.Class.Public" Label="A" />
    <Node Id="(@2 Type=B)" Category="CodeSchema_Class" CodeSchemaProperty_IsPublic="True" CommonLabel="B" Icon="Microsoft.VisualStudio.Class.Public" Label="B" />
  </Nodes>
  <Links>
    <Link Source="(@2 Type=B)" Target="(@1 Type=A)" Category="InheritsFrom" />
  </Links>
  <IdentifierAliases>
    <Alias n="1" Uri="Assembly=file:///Z:/ProjectA.dll" />
    <Alias n="2" Uri="Assembly=file:///Z:/ProjectB.dll" />
  </IdentifierAliases>
</DirectedGraph>
```

Actual:

``` XML
<DirectedGraph xmlns="http://schemas.microsoft.com/vs/2009/dgml">
  <Nodes>
    <Node Id="(@1 Type=B)" Category="CodeSchema_Class" CodeSchemaProperty_IsPublic="True" CommonLabel="B" Icon="Microsoft.VisualStudio.Class.Public" Label="B" />
    <Node Id="Type=A" Category="CodeSchema_Type" CommonLabel="A" Icon="Microsoft.VisualStudio.Error.Public" Label="A" />
  </Nodes>
  <Links>
    <Link Source="(@1 Type=B)" Target="Type=A" Category="InheritsFrom" />
  </Links>
  <IdentifierAliases>
    <Alias n="1" Uri="Assembly=file:///Z:/ProjectB.dll" />
  </IdentifierAliases>
</DirectedGraph>
```

**Comment by davkean** [comment]
Here's another failure: http://dotnet-ci.cloudapp.net/job/roslyn_master_win_dbg_unit64/lastCompletedBuild/testReport/Microsoft.VisualStudio.LanguageServices.UnitTests.Progression/InheritsGraphQueryTests/TestSolutionWithMultipleProjects/

**Comment by Pilchie** [comment]
Moving to 2.1 - we wouldn't take a fix here at this point without an understood customer impact.

**Comment by CyrusNajmabadi** [comment]
Closing out as we haven't had failures here in years.
