### ISSUE TITLE
Add support for 3rd party result providers for Language Services such as Find All References, GoToDefinition, etc.

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#9655]
Currently, Find all references, GoToDefinition, NavigateTo, etc. language services are strongly coupled to VS workspace and do not have extensibility points for third parties to plugin their results for improved semantic search experience. We should provide these extensibility points in all the appropriate language services for semantic search.

**Work items**:
1. Refactor the core language services to be provider based so that the service acts as a driver for internal and external result providers, which compute the results and then the service handles the aggregation of the results and display.
2. Public API design for result providers.
3. Hardening the IDE code against exceptions and incorrect/incomplete results from 3rd party providers.
4. Add samples and tests.

**Open questions:**
1. API shape: Should the public APIs all be based on document/position or we should also include overloads with symbol context?
2. Concurrent execution: Should the service executing the providers run them in parallel or not? Can this cause deadlocks if the provider needs UI thread access?
3. Background execution: Is it ok to invoke the providers on main thread or should they be invoked on background threads?
4. Ordering/Priority of execution/results from providers: How do we guarantee that execution and results from the providers can be ordered correctly? Should this be configurable by the providers themselves?
5. Merging results: How do we merge results for FAR, GTD, etc. from different providers (merge results from Rosyln provider and external provider and also merge results from 2 external providers)
6. Workspace configuration: Most providers would prefer to execute only in context of specific workspace, either just the Roslyn VS workspace OR just their own workspace. We probably want to allow the providers to configure workspace kinds of interest.

**Comment by mavasani** [comment]
Tagging @srivatsn

**Comment by CyrusNajmabadi** [comment]
Not plannig on doing this without a partner request.  Would need an api proposal here on all of these.
