### ISSUE TITLE
[Interactive] Alt+Enter incorrectly triggers C# Interactive

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#9657]
**Version Used**: 
VS2015 Update 2 RC 

**Steps to Reproduce**:
Please see https://github.com/aspnet/Tooling/issues/420 for more information.

**Expected Behavior**:
Alt+Enter shouldn't trigger C# Interactive.

**Actual Behavior**:
Alt+Enter triggers C# Interactive depending where cursor is

**Comment by Pilchie** [comment]
Didn't we make changes to Alt+Enter post-RC.  If so, can we get someone to install the latest U2/Roslyn builds together with R# and see if this is still a problem?

**Comment by amcasey** [comment]
@tannergooding Made an intriguing guess:

My suspicion is that ReSharper, when it is installed and the user selects the binding overrides, will preserve whatever command the binding is currently assigned to and will fall back to that command in certain scenarios and that uninstalling ReSharper would cause the binding to be reassigned to whatever command had ownership originally.

I believe this would result in the behavior being seen if the user:
•	Installed Update 1
•	Installed ReSharper
•	Installed Update 2
•	Attempted to use Alt+Enter

**Comment by Pilchie** [comment]
R# doesn't generally do that, @kuhlenh says that if you disable/uninstall, you lose the normal VS keybindings until you reset.

**Comment by Tasteful** [comment]
I tested to disable R# and then the C# Interactive is not triggered any more with the Alt+Enter command. When I enabled R# again the strange behavior start showing up again.

**Comment by Tasteful** [comment]
Also opened a bug at Jetbrains that is tracked here https://youtrack.jetbrains.com/issue/RSRP-455790

**Comment by Denis-Korneev** [comment]
The EditorContextMenus.CodeWindow.ExecuteInInteractive command was bound to Alt-Enter since VS 2010. Depending on its availability ReSharper_AltEnter executes it or shows Go to action menu. Until 2015 Update 2 RC, the command was available for F# only. Now it's also available for C#.
For the status of the issue please refer https://youtrack.jetbrains.com/issue/RSRP-455790.

**Comment by ManishJayaswal** [comment]
This should not be an issue in U2 onwards.
