### ISSUE TITLE
Emitted assembly is emtpy (custom mscorlib)

### ISSUE THREAD

**Issue by erik-kallen** [dotnet/roslyn#966]
When running this project: https://dl.dropboxusercontent.com/u/34113139/BugWithCustomMscorlib.zip, it prints an error message. I guess the custom mscorlib which is used has some issue with it, but everything was fine with Roslyn beta1-20141031-01. IMO, it shouldn't be a silent error anyway.

Here is the program text (also in the attached archive):

```
using System;
using System.IO;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace RoslynTest {
	class Program {
		static void Main(string[] args) {
			var syntaxTree = CSharpSyntaxTree.ParseText(@"using System.Collections; public class C1 { public void M() { var o = new { someValue = 1 }; } }");

			var compilation = CSharpCompilation.Create("Test", new[] { syntaxTree }, new[] { MetadataReference.CreateFromFile("mscorlib.dll") }, new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
			foreach (var d in compilation.GetDiagnostics().Where(d => d.Severity == DiagnosticSeverity.Error))
				Console.WriteLine("Bad test, error in compilation: " + d.GetMessage());

			using (var s = new MemoryStream()) {
				compilation.Emit(s);

				if (s.Length == 0)
					Console.WriteLine("ERROR: Emitted assembly was empty");
				else
					Console.WriteLine("Everything was OK");
			}
		}
	}
}
```

If the program being compiled is changed to not contain an anonymous type, the output assembly is emitted as expected.

**Comment by gafter** [comment]
I think we need your mscorlib.dll to repro the problem.

**Comment by VladimirReshetnikov** [comment]
@gafter the mscorlib.dll in the ZIP archive linked from the first comment.

**Comment by gafter** [comment]
Oh. [Never mind](https://www.youtube.com/watch?v=V3FnpaWQJO0).

**Comment by erik-kallen** [comment]
I think this should have the "Bug" label; even if there is a problem with the mscorlib, there should be either a diagnostic or an exception, silently producing invalid code is not a good behaviour.

**Comment by theoy** [comment]
We should not be emitting here, we should instead give a compiler error or ICE.

**Comment by gafter** [comment]
`compilation.Emit` returns a value of type `EmitResult`:

```cs
        public EmitResult Emit(
            Stream peStream,
            Stream pdbStream = null,
            Stream xmlDocumentationStream = null,
            Stream win32Resources = null,
            IEnumerable<ResourceDescription> manifestResources = null,
            EmitOptions options = null,
            CancellationToken cancellationToken = default(CancellationToken))
        {
```

You need to check the `EmitResult` for success and any error messages. In your case it does contain an error message (the compiler-generated code for an anonymous type uses `string.Format`, but your mscorlib does not provide it).

`error CS0656: Missing compiler required member 'System.String.Format'`

**Comment by erik-kallen** [comment]
Oops, sorry. Thank you for taking your time to look into this.
