### ISSUE TITLE
[Test Failure] MSBuild Error in prtest/win/dbg/unit64 on PR #9665

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#9666]
PR: [#9665](https://github.com/dotnet/roslyn/pull/9665) ** by @
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/5062/

**Issue 1: MSBuild Error**
error MSB3026:  Could not copy "C:\Users\dotnet-bot\.nuget\packages\System.Collections.Immutable\1.1.37\lib\dotnet\System.Collections.Immutable.dll" to "d:\j\workspace\roslyn_prtest---45fcf4bc\Binaries\Debug\System.Collections.Immutable.dll". Beginning retry 1 in 1000ms. The process cannot access the file 'd:\j\workspace\roslyn_prtest---45fcf4bc\Binaries\Debug\System.Collections.Immutable.dll' because it is being used by another process. [d:\j\workspace\roslyn_prtest---45fcf4bc\src\Compilers\VisualBasic\vbc\vbc.csproj] -&gt;     12&gt;C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(3962,5):

**Comment by davkean** [comment]
https://github.com/dotnet/roslyn/issues/8975
