### ISSUE TITLE
BasicWinForms.Change control property in code

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#9668]
PR: [#9650](https://github.com/dotnet/roslyn/pull/9650) ** by @
Failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p1/464/

**1 Test Failures:**
BasicWinForms.Change control property in code

**Issue 1: Individual TAO Test Failure**
Failing integration tests: 

BasicWinForms.xml

**Comment by davkean** [comment]
Dup of https://github.com/dotnet/roslyn/issues/7643
