### ISSUE TITLE
[Test Failure] xUnit returned error code without errors in prtest/win/dbg/unit32 on PR #9648

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#9672]
PR: [#9648](https://github.com/dotnet/roslyn/pull/9648) ** by @
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/5082/

**Issue 1: xUnit returned error code without errors**
xunit produced no error output but had exit code 1

**Comment by davkean** [comment]
Dupe of https://github.com/dotnet/roslyn/issues/9490

**Comment by jinujoseph** [comment]
PR: [#10127](https://github.com/dotnet/roslyn/pull/10127) *Merge master into future* by @vslsnap
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/5630/


**Issue 1: xUnit returned error code without errors**
xunit produced no error output but had exit code -2146233082

**Comment by davkean** [comment]
@jinujoseph This is a different issue, affecting a different assembly. This was originally ProjectSystem, the build you are looking at is
```
08:17:02   Roslyn.VisualStudio.CSharp.UnitTests.dll                                    FAILED 00:00:24.3729999
```

**Comment by jinujoseph** [comment]
ah , my bad.
I will close this and look for the right issue
