### ISSUE TITLE
Editor Crash on Renaming Type Parameter

### ISSUE THREAD

**Issue by natidea** [dotnet/roslyn#9673]
**Version Used**: 
VS2015 Update 2 RC 14.0.25029

**Steps to Reproduce**:

Given following code fragment:
```CSharp
public partial class Foo<ObjT> {}
partial class Foo<ObjT> {}
```
Attempting to rename `ObjT` causes a crash

**Comment by Pilchie** [comment]
Dupe of #7440,  fixed by @dpoeschl.
