### ISSUE TITLE
[PR Available] Missing localization in new Code Style UX

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#9674]
**Version Used**: Current code from 2.0 Milestone

![image](https://cloud.githubusercontent.com/assets/235241/13687249/075307ce-e6cf-11e5-86ab-05b8e60b74a2.png)

Not positive about 2, maybe those terms don't normally get loc'd? Need to check...

**Comment by dpoeschl** [comment]
FYI @balajikris @jinujoseph

**Comment by dpoeschl** [comment]
FYI @nguerrera

**Comment by Pilchie** [comment]
What's the current state here?

**Comment by dpoeschl** [comment]
@nguerrera Have we missed the loc freeze? If so, this will have to be punted along with some other loc bugs.

**Comment by nguerrera** [comment]
@dpoeschl Yes, it passed on Oct 23. Please do work to make this localizable ASAP and I will check with loc team about this getting fixed for RC.2.

**Comment by dpoeschl** [comment]
Fixed by #15257, #14945, and #14973
