### ISSUE TITLE
NavigationBarController asserts when workspace registration changed event is raised from a background thread

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#9688]
See [line 89] (http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/NavigationBar/NavigationBarController.cs,89) in method `NavigationBarController.OnWorkspaceRegistrationChanged`. `ConnectToWorkspace` asserts that it is invoked from the foreground thread, but it seems RegisterText raises workspace registration changed events from a scheduled task [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Workspace_Registration.cs,45).

**Comment by mavasani** [comment]
I am hitting this:

> >	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception exception, System.Action<System.Exception> handler) Line 151	C#
 	Microsoft.CodeAnalysis.Workspaces.dll!Roslyn.Utilities.TaskExtensions.SafeContinueWith.AnonymousMethod__0(System.Threading.Tasks.Task t) Line 150	C#
 	[Native to Managed Transition]	
 	Microsoft.CodeAnalysis.Workspaces.dll!Roslyn.Utilities.Contract.ThrowIfFalse(bool condition, string message) Line 86	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Shared.Utilities.ForegroundThreadAffinitizedObject.AssertIsForeground() Line 124	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.NavigationBar.NavigationBarController.ConnectToWorkspace(Microsoft.CodeAnalysis.Workspace workspace) Line 95	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.NavigationBar.NavigationBarController.OnWorkspaceRegistrationChanged(object sender, System.EventArgs e) Line 89	C#
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.WorkspaceRegistration.RaiseEvents() Line 31	C#
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Workspace.RegisterText.AnonymousMethod__0() Line 45	C#
 	Microsoft.CodeAnalysis.Workspaces.dll!Roslyn.Utilities.TaskExtensions.ContinueWithAfterDelay.AnonymousMethod__1(System.Threading.Tasks.Task _) Line 241	C#
 	Microsoft.CodeAnalysis.Workspaces.dll!Roslyn.Utilities.TaskExtensions.SafeContinueWith.AnonymousMethod__0(System.Threading.Tasks.Task antecedent) Line 80	C#
 	Microsoft.CodeAnalysis.Workspaces.dll!Roslyn.Utilities.TaskExtensions.SafeContinueWith.AnonymousMethod__0(System.Threading.Tasks.Task t) Line 148	C#
 	mscorlib.dll!System.Threading.Tasks.ContinuationResultTaskFromTask<bool>.InnerInvoke()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.Execute()	Unknown

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi and @mattwar , this is an interesting one. If you recall, we ensured that the Visual Studio workspace raised all change events on the UI thread so bugs like this didn't happen. Except that puts the onus on the Workspace implementer to do that, since we use the scheduler of the workspace you registered your text with. Nobody would know to do that. We're either going to have to strengthen our code everywhere, or figure out some alternate pattern where we don't use the workspace's scheduler for this.

**Comment by mattwar** [comment]
I don't know anything about any workspace raising workspace events on the UI thread.

**Comment by CyrusNajmabadi** [comment]
Strengthening our code would be pretty hard.  Many features depend on events being synchronised on some context for correctness.

Are we saying workspace events can happen on any BG thread?  or will they at elast all happen on the same BG thread?  If hte former, then that's going to take some serious work to strengthen across all our features.

**Comment by mattwar** [comment]
Without any scheduler hack/magic, workspace events are always on thread pool, so any background thread.

**Comment by CyrusNajmabadi** [comment]
This seems concerning.  If that's the case, then you could get events in any sort of order.  For example, you might hear about the removal of a document/project *before* a modification event for that same entity.  It seems like this could get clients into all sorts of trouble.

**Comment by Pilchie** [comment]
It's not the case.  We create a [WorkspaceTaskScheduler](http://source.roslyn.io/Microsoft.CodeAnalysis.Workspaces/Workspace/Host/TaskScheduler/WorkspaceTaskSchedulerFactory.cs.html#12) that uses the current synchronization context, which will force the tasks to run on the UI thread in VS.

**Comment by mattwar** [comment]
Correct.  I was wrong before.  The workspace inherits the thread context it was created on.  Either way, it uses a task queue, so events won't arrive out of order.

**Comment by CyrusNajmabadi** [comment]
Ok, that makes a lot more sense. Thank goodness :)

**Comment by mavasani** [comment]
So I am not sure how this got resolved as by design as no one answered @jasonmalinowski original question: How can an external workspace which gets created on a background thread ensure that it's task queue/scheduler uses the UI context and not the current context? [This](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Workspace.cs,65) line in Workspace's ctor forces the created task queue to use the current synchronization context (see [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Host/TaskScheduler/WorkspaceTaskSchedulerFactory.cs,29)). 

As a workaround, is there any way to force my external Workspace, which I am MEF exporting by the way, to be created on the UI thread?

Also, regardless of the workaround, shouldn't we allow workspace created on a non-UI thread to specify/create a task queue that uses the UI context? I am re-opening this for reconsideration/proper guidance on this scenario.

**Comment by jasonmalinowski** [comment]
@mavasani: I think you got the answer you were looking for internally?

**Comment by mavasani** [comment]
Yes, thank you! Please feel free to close this one.
