### ISSUE TITLE
Add language support for Composition

### ISSUE THREAD

**Issue by jsphadetula** [dotnet/roslyn#97]
Since multiple inheritance is not allowed in C#, syntax for supporting composition where all or part of a field's interface is automatically generated by the compiler will very useful 
Possible syntax:

class MyClass
{
   using TypeName m_field = { /* list of public members to be generated by compiler */ } 
}

**Comment by gafter** [comment]
Closing, as I cannot imagine anyone on the extended design team championing this over other work. @MadsTorgersen please reopen if you disagree.
