### ISSUE TITLE
The type 'Object' is defined in an assembly that is not referenced.

### ISSUE THREAD

**Issue by aviatrix** [dotnet/roslyn#970]
I'm  running the syntax parser [sample provided](https://github.com/dotnet/roslyn/blob/master/docs/samples/csharp-syntax.pdf) and i keep getting this exception ( and couple of other similar to this one)

```
error CS0012: The type 'Object' is defined in an assembly that is not referenced.
You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral,
PublicKeyToken=b03f5f7f11d50a3a'.
```
However this only shows up in the VS debugger when i'm debugging in VS 2015 ctp 6, with the VS ctp 5 SDK (not sure if it matters)

![octo cat](https://i.imgur.com/7DpjfBJ.png)

I'm not entirely sure if this is an issue with roslyn itself or just a bug with VS debugger integration, let me know if it's the latter and iil do my best to report it to the VS team.

**Comment by theoy** [comment]
Tentatively for RC2 until we understand it more.

**Comment by bdfranson** [comment]
Having a similar problem with a xamarin project.  (https://github.com/xamarin/VervetaCRM).  If you load the main project, do a restore in nuget, you'll see it right away.

**Comment by AlekseyTs** [comment]
@amcasey, can you comment on the debugger issue?

**Comment by amcasey** [comment]
If the (debugger) issue is that System.Runtime hasn't been loaded yet (i.e. doesn't appear in the Modules list), then this may be fixed by c3ba4e02d59c4f62840e6812a709d5509fe57816.

**Comment by AlekseyTs** [comment]
Assigning to Kevin (@Pilchie) per our offline discussion with him.

**Comment by Pilchie** [comment]
I expect that this is the same issue as #560 and #1373.

**Comment by Pilchie** [comment]
Rather than leaving this open, now that I've confirmed that the same thing fixes it, I'm just going to close this as a duplicate of #560.

**Comment by dpoeschl** [comment]
Reopening to track some potential ongoing work here.

**Comment by dpoeschl** [comment]
Tracking the Xamarin scenario with internal bug 1135756 and re-closing/verifying this one.

**Comment by pooran** [comment]
how did you actually fixed it? please provide steps. It is not just for Roslyn.. but it is pretty common in all new projects created using vs 2015

**Comment by Pilchie** [comment]
There was a bug in the msbuild targets files if you referenced a project that was a portable class library from a project that wasn't.  It should be fixed in the RTM version of VS2015 that was released today.

**Comment by terzano** [comment]
I am experiencing this same issue with the RTM release. 

![rtmver](https://cloud.githubusercontent.com/assets/343932/8818715/be0fd556-3012-11e5-8fdc-3ab2cc1cf02c.JPG)
Error: 
![rtm](https://cloud.githubusercontent.com/assets/343932/8818721/c89005be-3012-11e5-930a-3993e903d1c0.JPG)

**Comment by Pilchie** [comment]
Hmm - we talked about this issue with Xamarin folks, and they were following up to fix their targets as well.  I'll make sure they know about this.

**Comment by Pilchie** [comment]
I followed up - it turns out that the fix they made didn't make their RTM installer, but should be part of an update soonish.

**Comment by terzano** [comment]
@Pilchie Thank you very much for the quick follow up. Very much appreciated it has been noticed and action is being taken. Again, thank you for your time!

**Comment by tofutim** [comment]
Has this been fixed in VS yet?

**Comment by tofutim** [comment]
I found https://bugzilla.xamarin.com/show_bug.cgi?id=32622 which suggests that the next version of the VS Xamarin will fix this
