### ISSUE TITLE
When analyzer or codefix throws, give file and span that were passed to analyzer or codefix

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#9706]

**Comment by tmeschter** [comment]
File and span may not be the best option. For example, if the analyzer throws an exception in one of the compilation actions, there isn't really a file and/or span associated with that.

Presumably we could say what kind of action was being invoked (compilation, symbol, syntax, etc.) when the exception occurred. If it's a symbol action, specify what symbol was involved. If syntax, what syntax kind, and the file and span.

**Comment by srivatsn** [comment]
For the analyzers we give all this information now. Not for the code fixers.

**Comment by paul1956** [comment]
@srivatsn where do you give it? I have never seen it through Update 2.

**Comment by srivatsn** [comment]
In the error list, there is a AD0001 warning when an analyzer crashes. Expanding the warning will show this information. See https://github.com/dotnet/roslyn/issues/6710
