### ISSUE TITLE
Naming style: Should start with default settings for public types/members/etc matching Fx Design Guidelines

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#9713]
Even if we don't do "schemes" like "Roslyn team", etc, we should ship with some default set of rules that suggest names according to the Framework Design Guidelines.

**Comment by dpoeschl** [comment]
Some hopefully uncontentious defaults (but feel free to discuss):

1. Members (except fields) should be PascalCase
2. Types should be PascalCase
3. Interfaces start with 'I'
4. Async methods end with 'Async'
5. Type parameters start with T

**Comment by paulomorgado** [comment]
Public fields should also be PascalCase.

**Comment by Pilchie** [comment]
This is checked in now, right?  At least an initial set?

**Comment by dpoeschl** [comment]
Yes, an initial set is checked in. If the initial set is deemed insufficient then we can reopen this.
