### ISSUE TITLE
Consider publishing CSharpAllInOne.cs and CSharpAllInOneCompilable.cs and update for latest language features

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#9718]
We still have CSharpAllInOne.cs and friends in the old closed repo. There is a lot of value in having a single file to quickly test out language feature support and a lot of people have been asking for it. I have a very old version published on my blog, however the latest source of truth has never been published on GitHub.

We should

- [ ] add CSharpAllInOne.cs and friends in the public Roslyn repo (for example under \src\Compilers\Test\Resources\Core)
- [ ] add the latest language features to the file (string interpolation, properties, etc.)

**Comment by gafter** [comment]
It is already in open now, and there is a separate issue and PR for updating it now open.
