### ISSUE TITLE
Mac build reporting wrong number of tests

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#9750]
Our Mac builds are misreporting the number of tests in Jenkins.  Claiming that ony 9 tests ran vs. the hundreds that actually ran.  Need to look into this.

**Comment by agocke** [comment]
This looks like it was an infrastructure issue. The builds have been properly reporting that thousands of tests ran: https://ci.dot.net/job/dotnet_roslyn/job/master/job/mac_debug/833/testReport/
