### ISSUE TITLE
IDE0006 is defined twice in future

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#9758]
See: https://github.com/dotnet/roslyn/blob/future-stabilization/src/Features/Core/Portable/Diagnostics/Analyzers/IDEDiagnosticIds.cs

Not sure whether this will actually break anything, but running fixers against unexpected diagnostics (from an unrelated analyzer) can certainly cause failures.

**Comment by Pilchie** [comment]
Didn't @dpoeschl merge something to fix this?

**Comment by brettfo** [comment]
Yes, this was fixed in #10057.
