### ISSUE TITLE
Extract Local on interpolated string should not produce constant

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#976]
Extract the argument to WriteLine as a local:

    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine($"{DateTime.Now.ToString()}.{args[0]}");
        }
    }

Expected: variable
Actual: constant

**Comment by balajikris** [comment]
From the discussion at #2236 , we feel this is a compiler issue. SemanticModel.GetConstantValue() returns a value for InterpolatedStringExpression while it should not.

Once fixed, Please assign back the issue to me, so that the IDE can add some tests for Introduce Variable Feature.

**Comment by gafter** [comment]
The compiler side is now fixed.

**Comment by Pilchie** [comment]
Let's verify that this works and add a couple of tests for it.
