### ISSUE TITLE
Our Dispose pattern is too noisy

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#9760]
When implementing an interface that implements IDisposable, we implement the following:

``` C#
        #region IDisposable Support
        private bool disposedValue = false; // To detect redundant calls

        protected virtual void Dispose(bool disposing)
        {
            if (!disposedValue)
            {
                if (disposing)
                {
                    // TODO: dispose managed state (managed objects).
                }

                // TODO: free unmanaged resources (unmanaged objects) and override a finalizer below.
                // TODO: set large fields to null.

                disposedValue = true;
            }
        }

        // TODO: override a finalizer only if Dispose(bool disposing) above has code to free unmanaged resources.
        // ~ResolveLocallyTestFramework() {
        //   // Do not change this code. Put cleanup code in Dispose(bool disposing) above.
        //   Dispose(false);
        // }

        // This code added to correctly implement the disposable pattern.
        public void Dispose()
        {
            // Do not change this code. Put cleanup code in Dispose(bool disposing) above.
            Dispose(true);
            // TODO: uncomment the following line if the finalizer is overridden above.
            // GC.SuppressFinalize(this);
        }
        #endregion
```

This is waay too much noise, can we simplify this and have it respect preferences (I want underscores prefix for fields, and no regions)?

**Comment by bkoelman** [comment]
I would prefer to have two fixers here: one for "Managed and unmanaged" and one for "Managed only". Then they should generate code without commented-out code blocks, but call into partial methods such as `DisposeManaged` and `DisposeUnmanaged` that compile away when left as-is.

Depending on the type of project, I never have a need to dispose unmanaged resources. For example, ASP.NET sites or services.

**Comment by sharwell** [comment]
The following code is incorrect:

```csharp
// TODO: uncomment the following line if the finalizer is overridden above.
// GC.SuppressFinalize(this);
```

Specifically, the call to `GC.SuppressFinalize(this)` should *always* be present. Otherwise, a derived type which adds unmanaged resources to a class implementing `IDisposable` might fail to call `GC.SuppressFinalize(this)`. The only exception to this (at least in user code) is cases where the type is sealed, the dispose logic is placed directly in `Dispose()` (as opposed to `Dispose(bool)`), and the type does not have a user-defined finalizer.
