### ISSUE TITLE
automatically detect missing metadata reference being available

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#9761]
**Version Used**: 
Dev14 update 2

**Steps to Reproduce**:

1. Open a solution with a project that has missing metadata reference (reference exist in project but actual dll is missing from disk)
2. once solution is opened and shows many errors due to missing reference, copy dll to right location where project is expecting.

**Expected Behavior**:
Roslyn/project system recognize the dll being available, automatically update roslyn/project and errors starts go away.

**Actual Behavior**:
Roslyn/Project system doesn't recognize until user do explicit action such as build (on project that is missing metadata dll) or click reference node in project.

...

I am opening this bug so that we don't lose this issue when we finally spend time on improving project system. we backed off fixing this issue on our current native project system due to complexity in update 2.

**Comment by Pilchie** [comment]
Is this just a dupe of #9067?

**Comment by jasonmalinowski** [comment]
Looks like it to me. @heejaechang?

**Comment by heejaechang** [comment]
yep

**Comment by heejaechang** [comment]
close it as it is dup.
