### ISSUE TITLE
What happened to "Process" in VB?

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#9762]
**Version Used**: 
14.0.24720.00 Update 1, ,NET 4.6.01038
Microsoft Visual Studio Enterprise 2015
Version 14.0.24720.00 Update 1
Microsoft .NET Framework
Version 4.6.01038

Installed Version: Enterprise
Architecture and Modeling Tools   00322-80000-00000-AA013
Microsoft Architecture and Modeling Tools
UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.

LightSwitch for Visual Studio 2015   00322-80000-00000-AA013
Microsoft LightSwitch for Visual Studio 2015

Visual Basic 2015   00322-80000-00000-AA013
Microsoft Visual Basic 2015

Visual C# 2015   00322-80000-00000-AA013
Microsoft Visual C# 2015

Visual C++ 2015   00322-80000-00000-AA013
Microsoft Visual C++ 2015

Visual F# 2015   00322-80000-00000-AA013
Microsoft Visual F# 2015

Windows Phone SDK 8.0 - ENU   00322-80000-00000-AA013
Windows Phone SDK 8.0 - ENU

Application Insights Tools for Visual Studio Package   4.3.60226.3
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015 (RC1 Update 1)   14.1.20203.0
ASP.NET and Web Tools 2015 (RC1 Update 1)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40204.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.8.2   14.0.20201.0
Azure App Service Tools v2.8.2

Common Azure Tools   1.7
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

DataFactoryProject   1.0
Microsoft Data Factory Package

Developer Assistant   1.0
Developer Assistant puts millions of code snippets and code sample projects at your fingertips while you are coding in Visual Studio.

File Nesting   1.0
Automatically nest files based on file name and enables developers to nest and unnest any file manually

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

Microsoft Azure Data Factory Node Node   1.0
Azure Data Factory extension for Visual Studio Server Explorer.

Microsoft Azure HDInsight HQL Service   2.0.2900.0
Language service for Hive query

Microsoft Azure HDInsight Tools for Visual Studio   2.0.2900.0
An integrated development environment for HDInsight application development.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.7
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.7.30818.1601

Microsoft Azure Tools   2.8
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.8.40211.2

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

NuGet Package Manager   3.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

NuGetReferenceSwitcher   1.0
Information about my package

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

PureVisualBasic Extension   1.0
PureVisualBasic Visual Studio Extension Detailed Info

RegexTester   1.0
This is regular extension tester.

SQL Server Data Tools   14.0.50730.0
Microsoft SQL Server Data Tools

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

TypeScript   1.7.6.0
TypeScript for Microsoft Visual Studio

Visual C++ for Cross Platform Mobile Development   1.0
Visual C++ for Cross Platform Mobile Development

Visual C++ for Cross Platform Mobile Development   1.0
Visual C++ for Cross Platform Mobile Development

Visual F# Power Tools   2.2.0
A collection of additional commands for F# in Visual Studio

Visual Studio Spell Checker   VSSpellChecker
An editor extension that checks the spelling of comments, strings, and plain text as you type.

Visual Studio Tools for Apache Cordova   Update 7
Visual Studio Tools for Apache Cordova

Visual Studio Tools for Universal Windows Apps   14.0.24720.00
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

Web Essentials 2015   1.0.198
Adds many useful features to Visual Studio for web developers.

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

Xamarin   3.11.837.0 (f10676f)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android   5.1.5.3 (f98871a95a479f6d71b3067b7e5834d41fcb2118)
Visual Studio plugin to enable development for Xamarin.Android.

Xamarin.iOS   8.10.4.0 (6db87c53c073f4af2f5247fb738a27ea08c094fd)
Visual Studio extension to enable development for Xamarin.iOS.

Xamarin.iOS Unified Migration   1.0
Automated migration for Xamarin iOS Classic projects to Unified

Xamarin.TestCloud.Integration   1.0
Early preview of Xamarin Test Cloud integration
**Steps to Reproduce**:

1. Create new project based on CodeRefactoring template called CodeRefactoring2.sln
2. Insert the next line anywhere its valid
```
Dim currentProcess As Process = Process.GetCurrentProcess
```
**Expected Behavior**:
No error, this worked 4 weeks ago prior to many updates (I have need away for a month), now Process seems to have disappeared.
**Actual Behavior**:
```
Error BC30451 'Process' is not declared. It may be inaccessible due to its protection level.
Error BC30002 Type 'Process' is not defined.	CodeRefactoring2
```

**Comment by HaloFour** [comment]
It's in the assembly `System.dll` in the namespace `System.Diagnostics`, where it's been since .NET 1.1.

You don't mention what kind of project you're trying to create but I would imagine it's one where either `System.dll` isn't referenced by default or one where `Process` is not accessible.  I don't believe that you are permitted to access that class from Universal applications.

**Comment by paul1956** [comment]
@HaloFour It's a VSIX project that has been working since Roslyn 1.0 and when I went back to it today (after being gone a month) it no longer compiles. The application has not changed but I did lots of updates to Visual Studio that happened since 2/16/2016, I assume one of them changed something to do with system.dll

**Comment by paul1956** [comment]
@HaloFour My question is what broke and how to I fix it? Below is what is referenced, System.DLL was never directly referenced but the App worked.

![image](https://cloud.githubusercontent.com/assets/12789369/13802406/ad017f7a-eaf8-11e5-895a-3f398bb0604f.png)

**Comment by paul1956** [comment]
@DustinCampbell  do I understand from the milestone that this is a bug and I can't access Type Process from a VSIX application again until Update 3? This worked in Update 1.

**Comment by jmarolf** [comment]
@paul1956 I'm sorry I haven't gotten around to looking at this yet.  Hopefully I will be able to soon.  Can you show me some of the xml of your vbproj/csproj file, or ideally the project itself?

**Comment by paul1956** [comment]
@jmarolf Complete Solution Zipped. Let me know when I can delete it from OneDrive. This also demonstrates Visual Studio running out of memory trying to apply a code fix to a project or Solution if you run AddAsClauseCodeFixProvider to any VB project in Roslyn.

https://onedrive.live.com/redir?resid=5BF2F69E9B9FA722!14603&authkey=!AKtABPOihrKVXpg&ithint=file%2czip

**Comment by paul1956** [comment]
@jmarolf Do you have what you need. With Process the CodeFix will about before it runs out of memory. If you use the Default FixAllProvder it demonstrates running out of memory on fixing a Project or Solution, I have not seen it run out of memory with a single document.

**Comment by paul1956** [comment]
@jmarolf this missing "Process" issue still schedule for update 3. I have not found any workaround.

**Comment by heejaechang** [comment]
@paul1956 I am not sure how this is related to #4068

**Comment by paul1956** [comment]
I assumed the VXIS you posted is all of update 3 as I said in my comment and this bug was targeted at Update 3

**Comment by jmarolf** [comment]
Looks like this is the line throwing the error due to the type `Process` not being  found.

```VB
Dim currentProcess As Process = Process.GetCurrentProcess
```

There is a process type in EnvDTE, specifically [`EnvDTE.Process`](https://msdn.microsoft.com/en-us/library/envdte.process.aspx) however, there has [never](https://stackoverflow.com/questions/11845828/missing-reference-to-system-diagnostics-process) been a version of [System.Diagnostics.Process](https://msdn.microsoft.com/en-us/library/system.diagnostics.process.getcurrentprocess(v=vs.110).aspx) that is available in portable.

Your project file mentions that it is portable:
![image](https://cloud.githubusercontent.com/assets/9797472/15597760/29cf2a8a-2388-11e6-9674-aec0b6f504e2.png)

And looking at your vbproj file, it also says that it is supposed to be portable.
```XML
    <TargetFrameworkProfile>Profile44</TargetFrameworkProfile>
    <TargetFrameworkVersion>v4.6</TargetFrameworkVersion>
```

What you want to do is make this project non-portable byt removing `ProjectTypeGuids` and `TargetFrameworkProfile` and replacing the portable targets with `<Import Project="$(MSBuildToolsPath)\Microsoft.VisualBasic.targets" />`


It is unclear to me how this ever worked.  Did you make changes to this project file? By default the `Process` type should never have been available if you were using the Roslyn SDK to create this project.

**Comment by paul1956** [comment]
I works up to update 2. But I can make this change.
