### ISSUE TITLE
Default constructors C#

### ISSUE THREAD

**Issue by josejmoran** [dotnet/roslyn#9770]
**Version Used**: C# 6

**Steps to Reproduce**: The code below is part of the code we get when we create a project for MVC 5 in ManageController.cs  

The code for the controller should be a default controller.  All classes that we create should inherit a default controller that initialize all instance variables.

        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IEmailSender _emailSender;
        private readonly ISmsSender _smsSender;
        private readonly ILogger _logger;

// The controller below code will be unnecessary with the implementation of default controllers.
making our classes easier to the eyes and less code to browse over.

        public ManageController(
        UserManager<ApplicationUser> userManager,
        SignInManager<ApplicationUser> signInManager,
        IEmailSender emailSender,
        ISmsSender smsSender,
        ILoggerFactory loggerFactory)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _emailSender = emailSender;
            _smsSender = smsSender;
            _logger = loggerFactory.CreateLogger<ManageController>();
        }
...
}

1. 
2. 
3. 

**Expected Behavior**:

**Actual Behavior**:

**Comment by vcsjones** [comment]
C# 6 doesn't have default constructors. Are you proposing this should be the default once C# 7 ships (even if it does ship with default constructors)?

**Comment by josejmoran** [comment]
Yes, I think it will be a good idea to add it to C# 7

On Tue, Mar 15, 2016 at 5:59 PM, Kevin Jones <notifications@github.com>
wrote:

> C# 6 doesn't have default constructors. Are you proposing this should be
> the default once C# 7 ships (even if it does ship with default
> constructors)?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/dotnet/roslyn/issues/9770#issuecomment-197044010>
>



-- 
Regards,

Jose J. Moran
336-347-8688

**Comment by josejmoran** [comment]
I mean if we create a class with 3 fields I should get a default constructor for free so I don't have to add code for it unless I need to add some custom logic.  So I can call that default constructor and that constructor will have the logic to set the instance variables.

**Comment by josejmoran** [comment]
I made a mistake in the initial
