### ISSUE TITLE
Tool that generates RoslynLanguageServices.wxs need to include KeyPath="Yes" for pkgdef files

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#9777]
see this.
https://microsoft.sharepoint.com/teams/DD_Tenets/Acquisition/_layouts/15/WopiFrame2.aspx?sourcedoc={7d98ff50-19aa-4406-b9ca-000e7ea56073}&action=edit&wd=target%28Authoring%2Eone%7C11C4B80B%2D57B1%2D4DC0%2D982F%2DDBDF7A7231C1%2FWhat%20is%20KeyPath%3F%7C8D490882%2DBD45%2D4C98%2DA6CA%2D51E38F2860B6%2F%29

and comment from Raja from this PR.
https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/VS/pullrequest/16460?view=discussion

we need to update our tool to include KeyPath="Yes"

**Comment by davkean** [comment]
Resolved by https://github.com/dotnet/roslyn-internal/pull/711
