### ISSUE TITLE
Proposal: Type extension methods

### ISSUE THREAD

**Issue by jamesqo** [dotnet/roslyn#9784]
It's common to wish there was a static method defined in one of the built-in classes. For example, let's say you wanted to write your own `Array.IsNullOrEmpty`. You would most likely define an `Arrays` (a la Java) or `ArrayUtilities` class like this:

```csharp
class ArrayUtilities
{
    public static bool IsNullOrEmpty(Array array) =>
        array == null || array.Length == 0;
}
```

While this works, it would be nicer to have the illusion that this is part of the `Array` class itself. We should add some type of 'extension method' for types that would give the illusion it was a static member of the `Array` class, like (disclaimer: rough sketch)

```csharp
class ArrayTypeExtensions
{
    public static bool IsNullOrEmpty(Array array) : Array =>
        array == null || array.Length == 0;
}
```

It could then be called from other code like:

```csharp
Array.IsNullOrEmpty(array);
```

Thoughts?

---

**edit:** For reference, [Swift](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/Extensions.html) is one such language that has type extension methods in addition to instance ones.

**Comment by DavidArno** [comment]
Step 1: rename your method to `IsArrayNullOrEmpty()`
Step 2: add `using static ArrayUtilities` to the head of any class/struct using this method and then you can just use it as:
```cs
if (IsArrayNullOrEmpty(array)
{
    ...
```

That covers both your desire for clarity and removes the need for a language change.

**Comment by alrz** [comment]
Dup of #996
