### ISSUE TITLE
BasicEditAndContinue.xml timeout

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#9788]
PR: [#9751](https://github.com/dotnet/roslyn/pull/9751) *Merge stabilization into master* by @vslsnap
Failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p0/483/

**Issue 1: Build Timed Out**
The build timed out, or was forcibly aborted after reaching the maximum length. View the log right before the flagged timeout message to see what was happening.

Bounty

**Comment by davkean** [comment]
This is the screen that was showing on the timeout: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p0/483/artifact/Open/Binaries/Release/Screenshots/2016-03-16_02-14-46_11%20-%20Modal%20Dialog.png.

**Comment by ManishJayaswal** [comment]
@drognanar is this related to the change you were making to save to temp folder?

**Comment by drognanar** [comment]
I don't think so. The change that creates files in the temp folder was meant to resolve issues with the repl tests (which originally created files in the user directory).

**Comment by drognanar** [comment]
I did not find this issue happening again on Jenkins nor on my local machine.

**Comment by ManishJayaswal** [comment]
@drognanar Should we close this issue then? It does not look like it is actionable.

**Comment by ManishJayaswal** [comment]
closing this out as we are not seeing this issue anymore.
