### ISSUE TITLE
[Test Failure] CSharpEditAndContinue failed

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#9789]
PR: [#693](https://github.com/dotnet/roslyn-internal/pull/693) *Merge stabilization into master* by @vslsnap
Failure: http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_dbg_eta/855/

**Comment by davkean** [comment]
@srivatsn Was this the same one you ran into?

**Comment by davkean** [comment]
That link is wrong - that's not an EnC failure:

> Tao cannot take screenshots, so we're probably not running in a console session. Halting the test run because this can cause unexpected test failures. No tests were run because the test runner was unable to take screenshots. If this happens on a CI machine, make sure all user sessions are properly disconnected. Please notify @dotnet/roslyn-infrastructure if you see this error.

**Comment by davkean** [comment]
I can't find the issue you referring to, open it if you find it.

**Comment by mavasani** [comment]
Re-activating: This test is failing in http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_vsi1/132/

**Comment by jasonmalinowski** [comment]
Let's use #11846 to track.
