### ISSUE TITLE
Is there any publicly available way to reach the CSharpMetadataAsSourceService?

### ISSUE THREAD

**Issue by dee-see** [dotnet/roslyn#9792]
This is a question, not an issue.

I'm trying to figure out how to reach the `CSharpMetadataAsSourceService` class from non-Roslyn code but it seems like all the factories and interfaces around it are internal.

Is this code publicly unreachable by design or is there a public facing class wrapping all of this somewhere?

**Comment by srivatsn** [comment]
Currently it's not exposed publicly.
