### ISSUE TITLE
Inline Rename Dialog - mouse cursor needs to be arrow on the Apply button

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#981]
If you hover over the Apply button in the Inline Rename Dashboard, the mouse cursor is set to Beam (like the rest of the editor). We should probably set the cursor to Arrow on the entire dashboard.

**Comment by alexsorokoletov** [comment]
@KirillOsenkov I'm able to fix that issue, however, I am unable to test it. When I debug RoslynLight.sln/Roslyn.sln, debugged instance of VS 2015 is loading Microsoft.CodeAnalysis.CSharp.EditorFeatures.dll from C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\PrivateAssemblies thus ignoring freshly compiled DLL.


Any advice how to test the code or debug it is greatly appreciated.

**Comment by KirillOsenkov** [comment]
Adding @rchande @dpoeschl

**Comment by dpoeschl** [comment]
Discussed this with @alexsorokoletov on gitter. Unfortunately, there's no supported way to see changes at this layer reflected in VS. This is discussed in more detail in #1041.

**Comment by rchande** [comment]
@alexsorokoletov You can always submit a PR for us try out :smile:

**Comment by alexsorokoletov** [comment]
I just don't want to waste your time. If you have time, you would fix this issue. Isn't that the idea behind up and grab. Btw, I was able to test my changes using Live Tree/Live Property features from CTP 6. All my changes are in XAML.

**Comment by KirillOsenkov** [comment]
On the contrary, you can save us time by submitting a PR. Thanks!

**Comment by alexsorokoletov** [comment]
Here is a pull request https://github.com/dotnet/roslyn/pull/1320

**Comment by DickvdBrink** [comment]
That PR is merged so this can be closed right?

**Comment by dpoeschl** [comment]
@DickvdBrink Correct. The commit that was merged didn't use one of github's recognized "Fixes ###" phrases, but that was their intent. I've additionally verified the behavior on my machine. Closing & marking as Verified now.
