### ISSUE TITLE
Deterministic builds need a mechanism to control PDB path in PE

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#9813]
Today the full path of the emitted PDB is embedded into the PE file.  This particular path is intentionally excluded from our standard path mapping code.  Hence this makes it impossible to create identical builds unless:
1. All builds are sourced from identical directory names.
2. Builds do not emit a PDB.

Neither of these is a palatable option.  Not having this capability means we can't easily share build artifacts deterministically between various machines.

**Comment by gafter** [comment]
Note that there is a "temporary" solution in Roslyn due to #9814 : /features:pdb-path-determinism causes the PDB path emitted into the PE file to omit the path prefix.
