### ISSUE TITLE
Proposal: supply a new string suffix that mixes the functionality of @ and $

### ISSUE THREAD

**Issue by DavidArno** [dotnet/roslyn#9816]
Currently, with C# 6, if I want to construct a relative path using a variable, I have two choices:

```cs
var path = @"..\..\someDir\" + directory;

var path = $"..\\.\\someDir\\{directory}";
```

It would be useful to have a third option that acts like `@".."` save for string interpolation, so that I could write something like:

```cs
var path = $$"..\..\someDir\{directory}";
```

**Comment by bbarry** [comment]
`$@"..\..\someDir\{directory}"`

?

**Comment by DavidArno** [comment]
In my head at least, `$@` seems ugly compared with `$$`. I'm really not fussed over the syntax though: it's the functionality that matters to me. So I'd be happy with `$@`. :grin:

**Comment by svick** [comment]
@DavidArno Then you're in luck, `$@` already works (I assume that's what @bbarry was implying).

**Comment by DavidArno** [comment]
@svick,

Wow, I'm impressed: the language team implemented that one fast! :smile: 

That's really weird though: I've seen absolutely no documentation of this feature anywhere. Not complaining though, as it's perfect...

Anyway, thanks for the info. Time to close...
