### ISSUE TITLE
Integrate dynamic analysis instrumentation with lowering

### ISSUE THREAD

**Issue by JohnHamby** [dotnet/roslyn#9819]

**Comment by gafter** [comment]
I suggest it should go in the existing _local_ lowering pass.

**Comment by JohnHamby** [comment]
@AlekseyTs has a great idea for treating sequence point generation and all flavors of dynamic analysis instrumentation in a common fashion during local lowering. This approach will avoid issues with instrumentation and sequence point generation fighting with each other, and should work for all the kinds of instrumentation we are envisioning.

**Comment by nil4** [comment]
Which the comment box is too narrow to contain? :smile_cat:

**Comment by JohnHamby** [comment]
This was completed some time ago.
