### ISSUE TITLE
Samples.sln is cannot locate Microsoft.CodeAnalysis dll

### ISSUE THREAD

**Issue by zanqi** [dotnet/roslyn#9824]
**Version Used**: Code Pulled on Mar 16th, 2016

**Steps to Reproduce**:
1. Clone https://github.com/dotnet/roslyn
2. Run the "Developer Command Prompt for VS2015" from your start menu.
3. Navigate to the directory of your Git clone.
4. Run Restore.cmd in the command prompt to restore NuGet packages.
5. Run msbuild /v:m /m Roslyn.sln
6. Open src/Samples/Samples.sln

**Expected Behavior**:Samples.sln can be opened without reference warnings

**Actual Behavior**: Step 5 built fine, but when Samples.sln is opened, all references to Microsoft.CodeAnalysis have warnings stating the dll can not be located. If there's a step needed to install these dll, please provide it on [Samples and Walkthroughs](https://github.com/dotnet/roslyn/wiki/Samples-and-Walkthroughs)

**Comment by jmarolf** [comment]
Issue moved to [dotnet/roslyn-sdk #53](https://github.com/dotnet/roslyn-sdk/issues/53) via [**ZenHub**](https://www.zenhub.com/)
