### ISSUE TITLE
Proposal: Null test syntax for indexers

### ISSUE THREAD

**Issue by ckpearson** [dotnet/roslyn#9829]
Currently the null test syntax allows you to do the rather lovely:

```csharp
var result = someItem?.SomeProperty?.ToString();
```

and get a null back if anything in the chain is null.

It would be great if this could be extended to types supporting indexers (where valid indexes are known):

```csharp
var result = someArray[3?];
```

Which would roughly be the equivalent of:

```csharp
var result = someArray.Length > 3 ? someArray[3] : default(ArrayType);
```

Obviously this would only work for types with indexers that can be tested for validity (perhaps introduce an interface types can implement to support this?).

**Comment by HaloFour** [comment]
I know that your proposed syntax is only illustrative but it would seem to be affecting the index itself and not the operation of the indexer.  I'm not sure that conflating the syntax and concept of null propagation with "safe out-of-bound checks" is a good idea.  The operations are inherently different, and I would seriously hope that the latter is a significantly less common scenario.

There's also the question of thread safety.  In the case of a local variable of an array the operation you described is safe, however if you were dealing with an `IList<T>` or a mutable field it's very possible that the contents would change right in the middle of this check.

**Comment by svick** [comment]
1. I think using `?` might be confusing, because this has nothing to do with `null`.
2. The syntax is weird: Is `?` a postfix operator, that can only be used directly inside `[]`? Or is `[?]` a separate operator?
3. For reference types and nullable value types, you can already use `ElementAtOrDefault()`.
