### ISSUE TITLE
[Test Failure] VisualBasic.UnitTests.Diagnostics.RemoveUnnecessaryImports.RemoveUnnecessaryImportsTests.TestFixAllInDocument failed in prtest/win/dbg/unit64 on PR #714

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#9835]
PR: [#714](https://github.com/dotnet/roslyn-internal/pull/714) *Merge future-stabilization into future* by @vslsnap
Failure: http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_dbg_unit64/881/

**Comment by davkean** [comment]
Dupe of https://github.com/dotnet/roslyn/issues/9759. It has been fixed.
