### ISSUE TITLE
Intermittent hang while running tests

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#9838]
http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/5274/

Could be Roslyn.Compilers.CSharp.Semantic.UnitTests,Roslyn.Services.Editor.UnitTests,Roslyn.Services.Editor.CSharp.UnitTests.dll or Roslyn.VisualStudio.Services.UnitTests.dll

**Comment by srivatsn** [comment]
Likely a dupe of #7825. /cc @lgolding

**Comment by Pilchie** [comment]
Moving to Area-Analyzers, since that's where #7825 is.

**Comment by srivatsn** [comment]
Closing as dupe of #7825.
