### ISSUE TITLE
Local Enums.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#9839]
As we (Roslyn) are looking at Local Inner Functions. 
When writing a state machine, we have put the state (indicator) enum outside of the function.

```VB
  Enum State
    Begining
    Middle
    [End]
  End Enum

Function Foo()
  Dim current = state.Begining

End Function

```

**Proposed**
If that state (indicator) enum has no meaning outside of that function, then we could _in theory_ include it inside of the function.

```VB
Function Foo()
  Enum State
    Begining
    Middle
    [End]
  End Enum

  Dim current = state.Begining

End Function

```

**Comment by alrz** [comment]
And practically you cannot return or pass a variable of that type anywhere, right? if so, what is the point of a local enum? a real world example would be nice.

**Comment by AdamSpeight2008** [comment]
@alrz  
For example in parsing.
In this [Example](https://gist.github.com/AdamSpeight2008/ca808eeff0fdcdd846d7#file-parse-L51) it is used to track at what the current parsing stage. Useful when I need to resync the parsing. 
_I still need to refactor the code, but it works._

**Comment by gafter** [comment]
Dup of #9523
