### ISSUE TITLE
Automatic removal of unnecessary using statements

### ISSUE THREAD

**Issue by josejmoran** [dotnet/roslyn#9843]
**Version Used**: C# 7 feature request

**Steps to Reproduce**:
Right now the IDE inform me of the using statements that are not necessary and gray them out.
It will be awesome if instead of graying them out it will delete the lines automatically so I don't have to.

1. 
2. 
3. 

**Expected Behavior**:

**Actual Behavior**:

**Comment by SLaks** [comment]
This feature already exists; just use the smart action.

Doing that automatically is a horrible idea, because there is no point in which it's safe to do so.

You're asking to make it impossible to write a `using` statement before the code that uses it.

**Comment by agocke** [comment]
This isn't a language proposal.

**Comment by davkean** [comment]
@josejmoran I'm not sure I understand the proposal - at what point would you like us to remove them?

**Comment by mgravell** [comment]
Looks to be a troll having some fun; see all suggested issues: https://github.com/josejmoran

**Comment by markrendle** [comment]
GitHub Feature Request: Automatic removal of this guy.

**Comment by DustinCampbell** [comment]
You should check out the VS Power Commands extension, which allows you to invoke Remove Unnecessary Usings on save of a file.
