### ISSUE TITLE
Breaking change: Limit the total size of all user strings within an assembly to 2^24B

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#9852]
The `#UserStrings` metadata heap is addressable by 24bit index. That means that all user strings   (i.e. arguments to ldstr instructions) in the assembly have to fit into 2^24 bytes after they are serialized to the heap, except for the last string which has to start below 2^24 but can span further. 

The order of strings is pretty much determined by the location of the string constant in source and the ordering of source files. In extreme cases, when a user project has a lot of strings and they happen to be ordered such that the last string is quite long, one may just switch the order of method definitions and get a compilation error since the heap index of the string that's now last doesn't fit into 24 bits.

The native compiler is using native IMetaDataEmit metadata writer. Experiments show that the writer has a rather arbitrary limit on the total size of encoded #UserStrings (something around 0x0E000000). Seems like an implementation detail.

I propose we cap the _total_ encoded length of all user strings emitted into an assembly by 2^24 bytes to avoid surprises. It would be a breaking change, however it would only affect projects that are already on the very edge of what we can compile today and are very fragile.

The enforcement would be implemented in System.Reflection.Metadata.

Unfortunately the ECMA spec doesn't say anything about total size of heaps. In our errata https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Metadata/specs/Ecma-335-Issues.md#heap-sizes we limit the sizes of #Blob, #Guid and #String heaps to 2^29. The limit on #UserString heap would be added. It should also be clarified that blobs, strings and guids can't span beyond the heap size even though their index is within the limit.

**Comment by tmat** [comment]
@AlekseyTs @nguerrera @gafter @dotnet/roslyn-compiler

**Comment by nguerrera** [comment]
Seems reasonable to me.

**Comment by AnthonyDGreen** [comment]
If I understand, you're saying there's already a runtime limit on strings but a loophole where the last string can bleed above that and you want to close this loophole so that the error is more predictable? If so, sounds reasonable to me too.

**Comment by tmat** [comment]
@AnthonyDGreen Correct.

**Comment by leppie** [comment]
I pity the fool that has a codebase creating this... resources are there for a reason.

**Comment by VSadov** [comment]
seems reasonable.
relying on a particular string being last in index is uselessly fragile

**Comment by AlekseyTs** [comment]
@leppie This has nothing to do with resources.

**Comment by leppie** [comment]
@AlekseyTs Is #UserString heap not used for string constants? If not, I was mistaken and ignore my comment :D

**Comment by AlekseyTs** [comment]
constants aren't resources

**Comment by leppie** [comment]
Yes, but creating 16MB of string constants in your project is friggen insane! You should use embedded resources instead then.

**Comment by Suchiman** [comment]
@leppie i'm not sure but doesn't razor exactly create string constants for all the text in cshtml? that way you could hit the limit waaay faster.

**Comment by leppie** [comment]
@Suchiman: Fair point, for both dynamic and precompiled scenarios :+1: Still easily avoidable by the user.

**Comment by tmat** [comment]
Note that if you have a lot of strings in your assembly and not hitting the limit already (or about to hit it soon) is when you have one huge string (>16MB) in the last ldstr instruction of the last method of the last file of your project. In that case you can fit the huge string and not hit the existing limit on index. You can even add more small things moving that huge string further and further in the heap and still not hit the current limit. But once you make a change that adds another string after that huge string you'll get an error.
