### ISSUE TITLE
Proposal: replace single lambda parameter with 'it' or '_'

### ISSUE THREAD

**Issue by hmemcpy** [dotnet/roslyn#9857]
Pretty sure this was proposed already, but I can't find it.

The proposal is to omit a single parameter declaration in Lambda expressions in favor of a literal `it` (similar to Kotlin) or an underscore (similar to Scala).

This would allow using the syntax like this:

`collection.Where(it.Name == "Bob")`

etc.

Pre-emptive: haven't thought this thru, or considered any of the corner cases at all.

**Comment by chaliy** [comment]
Drop it or _ entirely, make it sound:

`collection.Where(Name == "Bob") `

**Comment by AdamSpeight2008** [comment]
@hmemcpy I think it was within one of the proposal for pattern matching (or related)

**Comment by daveaglick** [comment]
@chaliy But then how to disambiguate?

**Comment by svick** [comment]
Both `it.Name == "Bob"` and `_.Name == "Bob"` are already valid expressions (assuming the variables `it` or `_` are declared. And it's possible that a method has overloads for both `T` and `Func<U, T>` (so both the existing interpretation and your proposed interpretation could be valid).

So I don't think this syntax is a good idea.

**Comment by alrz** [comment]
Dup of #3561

**Comment by alrz** [comment]
Actually no one proposed trailing closures so far, I think that is what #3561 entails,
```cs
colleciton.Where{ <sigil>.Name == "Bob" };
```

**Comment by hmemcpy** [comment]
@alrz yes, this would make it into Kotlin https://kotlinlang.org/docs/reference/lambdas.html :)

**Comment by HaloFour** [comment]
C-Omega: :smile: 

```cs
collection[Name == "Bob"].{ Console.WriteLine(it.Name); };
```
