### ISSUE TITLE
Proposal: New IntelliSense suggestions for 'get' and 'set' presence in property declaration

### ISSUE THREAD

**Issue by ikopylov** [dotnet/roslyn#9863]
Currently when one declare a new property there is no any IntelliSense suggestions for `get` and `set` presence. 

It would be great to see some very common patterns on the list of suggestions: `get;`, `get; set;`, `get; private set;` and so on. Also it is possible to find a backing fields for that property and suggest getter and setter with them too.

**How it can work**
The suggestions would be shown on `{` right after the property declaration:

```
private string _name;
public string Name {
                    ^ Here the following suggestions can be displayed:
                      get;
                      get; set;
                      get; private set;
                      get { return _name; }
                      get { return _name; } set { _name = value; }
```

**Comment by lachbaer** [comment]
@ikopylov There are some code snippets that all start with `prop...` namely `prop`, `propg` and `propfull`. Try those.

**Comment by DustinCampbell** [comment]
Triggering on space here is an interesting idea. Anyone interested in taking a look?

**Comment by miloush** [comment]
Looks like another scenario that could benefit from using Roslyn for code snippets...

**Comment by CyrusNajmabadi** [comment]
Unlikely to do this given lack of feedback.
