### ISSUE TITLE
Fully Document the Integration Test Framework

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#9865]
The new Integration Test Framework is fairly complicated (with a lot of IPC and marshalling of data). It needs a higher level of documentation (equal to its complexity).

The documentation should:
- Make it easy for new users to ramp up on the internals of the framework and to extend the existing functionality or write new tests
- Clearly define where and how each object is created and how each object interacts between the host and test process
- Ensure the existing code is straightforward to use, has a logical object hierarchy, and is easily extended to handle changes that occur as new versions of the host process are released

**Comment by tannergooding** [comment]
FYI. @jaredpar, @jasonmalinowski

**Comment by jasonmalinowski** [comment]
Documentation no longer needed since we're converting away from it.
