### ISSUE TITLE
DryDock Effort: Skipped test which are broken and have no associated workitem.

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#9873]
<WpfFact(Skip:="xunit wait")>
Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.ModelTests.ChainingTaskStartsAsyncOperation

<WpfFact(Skip:="true")>
Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.ModelTests.ControllerIsNotUpdatedIfComputationIsCancelled

[WpfFact(Skip = "TODO")]
Microsoft.CodeAnalysis.CSharp.EditAndContinue.UnitTests.RudeEditStatementTests.Lambdas_Update_Signature_CustomModifiers1

**Comment by DustinCampbell** [comment]
Could we separate this into two bugs? The IntelliSense issues and the ENC issue are owned by different teams?

**Comment by Pilchie** [comment]
IDE issues fixed in #10175.  Please triage and fix the E&C test.
