### ISSUE TITLE
Type disguise memory block

### ISSUE THREAD

**Issue by Thaina** [dotnet/roslyn#9879]
I'm not sure what to call this feature but I want something like pointer of type to a memory to fake object

Consider we have types like these

``` C#
public struct Vector2
{
    public float X,Y;
    public static DotProduct(ref Vector2 vl,ref Vector2 vr);
}

public struct Point
{
    public float x,y;
}

public struct GeoLocation
{
    public float Latitude,Longitude;
}
```

It actually the same memory layout. It should interchangeable

In C we could just use pointer

``` C
Point p;
Vector2 v1;
Vector2* v2 = (Vector2*)&p;
float dot = DotProduct(&v1,&v2);
```

Not only that, it could mock up a type on array or even bytearray

``` C
float* f = (float*)malloc(sizeof(float) * 8);
Vector2 v1;
float dot = Vector2.DotProduct(&v1,(Vector2&)&p[4]);
```

I would like C# to have this kind of feature that could mock a reference of struct on memory with the same layout

It could be limit to only type with the same layout in CLR. At least for struct which has no inheritance header, also include Tuple and anonymous struct

Something like this

``` C#
Vector2 v;

Point p;
Vector2.DotProduct(ref v,(ref Vector2)ref p);

float[] f;
Vector2.DotProduct(ref v,(ref Vector2)ref f[5]);

Tuple<float,float> t;
Vector2.DotProduct(ref v,(ref Vector2)ref t);

var s = { float x , float y };
Vector2.DotProduct(ref v,(ref Vector2)ref t);

/// Also we should be able to mock existing type to anonymous struct if it is same layout if ref local is possible
ref var sv = (ref { float x , float y })(ref v);
```

**Comment by leppie** [comment]
As far as I know, you can do this with unsafe already.

**Comment by orthoxerox** [comment]
You can make a wrapper type with explicit layout that contains all three types at offset 0, plus implicit conversions to and from your types. This is a reasonable workaround, in my opinion.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
