### ISSUE TITLE
Request: Analyzer for named arguments

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#9883]
Named arguments are a great feature to write self-documented code, but if the original author didn't write them you should write every argument by hand which is kinda cumbersome. Also, when you write named arguments you might write them in a random order that makes the compiler to introduce locals to preserve side-effects in order. It would be nice to (1) have an analyzer add all named arguments for a method call (2) and suggest correction if they are not in the same order as method parameters.

**Comment by alrz** [comment]
By the way, it was rather trivial to write such an analyzer.

**Comment by gafter** [comment]
Perhaps you'd like to contribute it to Roslyn?

**Comment by alrz** [comment]
@gafter Definitely! I will try to make it into a PR.
