### ISSUE TITLE
CType/CBool/etc throwing invalid cast exception depending on the declared variable type although the actual type is the same

### ISSUE THREAD

**Issue by Epicycle23** [dotnet/roslyn#9887]
**Version Used**: 

vb.net visual studio 2015 update 1

**Steps to Reproduce**:

1. Create a test method

``` vb
<TestMethod>
Public Sub TestCBoolWithIComparableDouble()
    Dim value As **IComparable** = 1R
    Assert.IsTrue(CBool(value))
End Sub
```

**Expected Behavior**:

Test passes.

**Actual Behavior**:

Test fails with an invalid cast exception

**In Contrast (it actually does pass the test and does not throw)**

``` vb
<TestMethod>
Public Sub TestCBoolWithDouble()
    Dim value As **Object** = 1R
    Assert.IsTrue(CBool(value))
End Sub
```

On a side note: I wasnt even able to decompile the first method, whereas the second one could be decompiled without any problem (.net reflector 9)

**Comment by gafter** [comment]
@AnthonyDGreen Do you have any idea what's going on here?

**Comment by AnthonyDGreen** [comment]
Makes no sense. Must be a bug.
