### ISSUE TITLE
Git branch for CTP6

### ISSUE THREAD

**Issue by petr-k** [dotnet/roslyn#989]
Since the instructions on how to install and build Roslyn indicate that one should checkout the branch matching the downloaded VS preview, a branch for the current CTP6 is needed.

**Comment by jaredpar** [comment]
Where do you see this instruction?   I tried to remove that from the WIKI because it is no longer accurate.

**Comment by petr-k** [comment]
Main repo page, section **Source code**, link "Building, testing and debugging the sources", section [Install and build Roslyn](https://github.com/dotnet/roslyn/wiki/Building%20Testing%20and%20Debugging#install-and-build-roslyn).

I tried to run via OpenSourceDebug, but it threw an error saying the package could not be loaded. VS ActivityLog.xml indicated that the package assembly manifest did not match, so I just kind of assumed it might something to do with the branch I was targeting (master) - the same issue as #928.

**Comment by DavidKarlas** [comment]
Looks like this branch was finally pushed: https://github.com/dotnet/roslyn/tree/releases/Dev14CTP6

This issue can be closed
