### ISSUE TITLE
Add .NETStandard support to our packages

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#9891]
We need to add .NETStandard support to our packages.

**Comment by davkean** [comment]
tag @agocke @jaredpar

**Comment by jaredpar** [comment]
What TFM of netstandard do we need to use?

**Comment by davkean** [comment]
¯\(°_o)/¯ but its going to different based on each packages currently supported platforms.

Sent from my Windows Phone
________________________________

**Comment by jaredpar** [comment]
CC @weshaggard to get clarity on the TFM here.

**Comment by agocke** [comment]
Also which packages? CodeAnalysis*? The .Net.Compilers package? The .Net.Compilers.netcore package?

**Comment by weshaggard** [comment]
cc @ericstj 
As @davkean said it will be different based on what you plan to target and what your dependencies target.  See https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md#mapping-the-net-platform-standard-to-platforms for the targets of the different netstandard versions.

@agocke for .NET Core CLI purposes it should at least be Microsoft.CodeAnalysis.Common/CSharp/VisualBasic  as those are going to be include in the shared framework. However it is probably useful for the other ones as well.

**Comment by tmat** [comment]
Scripting nugets should target "netstandard1.4" and "net45"

**Comment by tmat** [comment]
I think compiler should target "netstandard1.1"

**Comment by agocke** [comment]
@weshaggard This implies there are no changes to dnxcore50, is that correct?

**Comment by weshaggard** [comment]
@agocke the document is a little behind some of the current thinking as dnxcore50 will be getting renamed to netcoreapp10 but I don't believe that should impact any of your packages. However if there are any please point them out to me and I can suggest how to change them.

**Comment by agocke** [comment]
@weshaggard The Microsoft.Net.Compilers.netcore package consumed by CLI is dnxcore50.

**Comment by agocke** [comment]
(Technically, it's just a package with runtimes/any/native/*.exe, where those exes are IL-only, though)

**Comment by agocke** [comment]
The references are all dnxcore50.

**Comment by weshaggard** [comment]
I'm not entirely sure how Microsoft.Net.Compilers.netcore is being consumed so I would need to better understand who is consuming to suggest whether or not any updates are needed for it. However if everything is in "runtimes/any/native" that means any target can resolve it and if the dependencies are dnxcore50 they can actually be changed to be non-TFM specific as well, it all depends on the plans for how people will consume this package.
