### ISSUE TITLE
Breaking change: C# can no longer assign to static readonly field of another instantiation

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#990]
The following code compiled and ran on previous versions of C#. In Roslyn this does not compile:

```cs
public static class Foo<T>
{
    static Foo()
    {
        if (typeof(T) == typeof(int))
        {
            Foo<int>.compute = x => (int)x;
        }
    }
 
    public static readonly System.Func<double, T> compute;
}
```

**Comment by gafter** [comment]
The native compiler allowed this code, and the code passes the verifier and runs “correctly”. However, it is certainly not allowed by the intent of the language specification, the code almost certainly contains an error, and the generated code violates the CLI specification (for the init-only constraint). It is a verifier bug that this code passes the verifier.

I propose we allow this code in Roslyn now, and add a diagnostic in the very first warning wave once we implement warning waves (under /feature:strict for now).

**Comment by gafter** [comment]
@VSadov pointed out to me that we should decide whether we want to expand this relaxation to getter-only autoprops. I think we should not, as that is a new feature.

/cc @theoy @VSadov

**Comment by VladimirReshetnikov** [comment]
AFAIK, PEVerify.exe always gave an error for this code:
```
`Foo`1[T]::.cctor][offset 0x00000041] Cannot change initonly field outside its .ctor.
```

Related MS Connect bugs:
* https://connect.microsoft.com/VisualStudio/feedback/details/1133185/static-constructor-of-generic-class-cannot-set-readonly-field
* https://connect.microsoft.com/VisualStudio/feedback/details/1144959/compile-error-setting-readonly-static-field-from-cctor

**Comment by gafter** [comment]
@VladimirReshetnikov I see I was testing the verifier on the wrong executable. Yes, the verifier rejects the code. I updated the bug description.

**Comment by gafter** [comment]
@VladimirReshetnikov Can you please "Verify" that this is "fixed"?
