### ISSUE TITLE
Proposal: multiple using statements

### ISSUE THREAD

**Issue by EgorBo** [dotnet/roslyn#9903]
The proposal is about to have an ability to declare needed namespaces via short one-line format:

How we declare usings now:

```
using System;
using System.Runtime;
using System.Runtime.InteropServices;
```

How it can be:

```
using System, System.Runtime, System.Runtime.InteropServices;
```

And to reduce self-repeating by using some special character like '*':

```
using System, *.Runtime, *.InteropServices;
```

to let the compiler search Runtime and InteropServices in one of the previously defined namespaces (if there are more than one - to include all of them or to show a compilation error).

As an alternative, a new keyword, for example "all":

```
using all System.Runtime.InteropServices;
```

it indicates that compiler should include all intermediate namespaces as well (System and System.Runtime)

**Comment by gafter** [comment]
Why would this be a desirable language change?

**Comment by EgorBo** [comment]
@gafter For short scripts/one-liners/REPL where the "using" section can be bigger than the actual code. Also sometimes 'using' section is so big so it occupies the whole screen and 80% of text is a copy-paste.

**Comment by yufeih** [comment]
> using System, *.Runtime, *.InteropServices;

How about just introducing `*` to the using statement:

- `using System.Runtime.*;`   Imports all descendant namespaces under `System.Runtime`
- `using System.*;`  Imports all descendant namespaces under `System`, including `System.Runtime`, `System.Runtime.InteropServices`, etc
- `using *;`  Imports all namespaces from all referenced assemblies.

I tend to restrict `*` to only appear at last, but if `using *.InteropServices` has good use case, this constraint can be relaxed.

Related to https://github.com/dotnet/roslyn/issues/2044, but seems like a better option.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
