### ISSUE TITLE
[Proposal] Common interface for classes with Identifier property.

### ISSUE THREAD

**Issue by UnoSD** [dotnet/roslyn#9908]
Can you please consider adding an interface to all the syntax nodes with an Identifier?

I had to rewrite the same code for various types just because they didn't have a common base (and I didn't want to use reflection).

E.G.
**Microsoft.CodeAnalysis.CSharp.Syntax.MethodDeclarationSyntax**
and
**Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax**

**Comment by jaredpar** [comment]
Seems pretty similar to #10455.  Going to let that one be the tracker.

**Comment by CyrusNajmabadi** [comment]
We've discussed this before, and we have no intent/desire to introduce interfaces for this purpose.  If this is still desired, please raise an API request (fully fleshing out the proposal).  We can discuss again, but i do not anticipate anything would change here @amine-aboufirass .

**Comment by CyrusNajmabadi** [comment]
There is no goal in allowing for generality here.  If you want, you can just write extension methods like `GetIdentifierToken(this ...)` that would allow you to process these nodes.

The reason for this is that from our perspective there truly is no generality here at this layer.  They are not related in this fashoin.  Any view that makes them related is a domain-specific/feature-specific view.  As such, the helpers that make things uniform should be defined in that domain/feature layer.

**Comment by CyrusNajmabadi** [comment]
@amine-aboufirass whatever makes sense in your domain.  I don't know which nodes you'd want this to apply (or not apply) to.  :)
