### ISSUE TITLE
Refactoring encapsulate field - degraded, compared with VS 2013

### ISSUE THREAD

**Issue by SergeyZhurikhin** [dotnet/roslyn#9927]
**Version Used**:  VS2015Esp1

**Steps to Reproduce**:
There are two classes:

``` C#
class C
{
    public int p = 10;
    public void M()
    {
        p = 5;
    }
}
class D
{
    public void M()
    {
        var c = new C();
        c.p = 7;
    }
}
```

**Expected Behavior**:
Requires encapsulate field p, so that the external appeal was to the property, and if the internal to the left as it was:

``` C#
class C
{
    private int p = 10;

    public int P
    {
        get
        {
            return p;
        }

        set
        {
            p = value;
        }
    }

    public void M()
    {
        p = 5;                //<---
    }
}
class D
{
    public void M()
    {
        var c = new C();
        c.P = 7;                  //<---
    }
}
```

This is a common case, and he was supported in VS2013.

**Actual Behavior**:
The VS2015 offers two types of refactoring, and both options are missing this common case:
1:
![refactoringprop1](https://cloud.githubusercontent.com/assets/16261478/13905681/49437786-eee0-11e5-8eaa-2d594de009e4.png)
2:
![refactoringprop2](https://cloud.githubusercontent.com/assets/16261478/13905682/4e5060b8-eee0-11e5-8f77-f4c32b96da85.png)

**Comment by SergeyZhurikhin** [comment]
@DustinCampbell I do not agree with the label **Feature Request**, it is rather an **Bug**. 
When applying refactoring No. 2 **Encapsulate the field: "p" (but continue to use the field)**, we get the code with an error, when this error did not occur in VS 2013.
```C#
class C
{
    private int p = 10;             //<---   private!

    public int P
    {
        get
        {
            return p;
        }

        set
        {
            p = value;
        }
    }

    public void M()
    {
        p = 5;               
    }
}
class D
{
    public void M()
    {
        var c = new C();
        c.p = 7;                  //<--- private fild!
    }
}
```
### This is a bug and not a new feature.

**Comment by CyrusNajmabadi** [comment]
Closing out.  It's been 7 years and we've heard nothing on this design change from any other users.  The code is operating as we intended it to, so this is def a feature request.  Given no other requests for this, going to keep as is.
