### ISSUE TITLE
"One or more errors occurred" while deleting characters in Immediate Window

### ISSUE THREAD

**Issue by chlowell** [dotnet/roslyn#994]
1. In the Immediate window, invoke a function which returns a collection. Here are a few which reliably repro the bug for me in a new console application:

    
        Enumerable.Range(0, 37).ToList()
        new System.Collections.Generic.HashSet<int>(Enumerable.Range(0, 37))
        System.Diagnostics.Process.GetProcesses()

2. Press your up key to re-enter the same expression.
3. Hold down backspace.

A modal dialog will probably appear:
![image](https://cloud.githubusercontent.com/assets/10964656/6470764/d9397fee-c19a-11e4-8961-c25670e89678.png)
 If the dialog doesn't appear, repeat from step 2.

**Comment by Pilchie** [comment]
I think @rchande just checked in a fix for this.

**Comment by ManishJayaswal** [comment]
Assigning to @rchande to validate this is the same issue the @Pilchie mentioned and if it is then close it out.

**Comment by rchande** [comment]
Yep, this is fixed with #834 .
