### ISSUE TITLE
Micro Tasks to make Perf Code clean

### ISSUE THREAD

**Issue by basoundr** [dotnet/roslyn#9951]
- [x] Remove redundant helpers (For Eg: ShellOut)
- [x] Store the final ConsumptionTempResults in the %SYSTEMDRIVE%\CPC\
- [x] Store the trace in %SYSTEMDRIVE%\CPC\
- [x] Move the traces to a path in \\\\mlangfs1
- [x] Run `DownloadCPC()` in `automation.csx`
- [x] Copy consumptionTempResults.xml, consumptionTempResults_ElapsedTime.csv and Roslyn-{Hash}json file to share after the test completion

Will add more tasks as I remember more. This is opened in reference to #9948

**Comment by KevinH-MS** [comment]
For the last task ("Run DownloadCPC() in runner.csx optional"), I think it would be better to have this logic in some setup step (called by automation.csx).  bootstrap.bat and fetch_build.csx are likely candidates.  Logically, updating the copy of CPC on the box is orthogonal to the running of tests.

**Comment by basoundr** [comment]
All the tasks have been address in #9948. Once the PR gets merged, I will check the tasks

**Comment by basoundr** [comment]
I have addressed all the tasks mentioned here. Closing this issue
