### ISSUE TITLE
[Test Failure] Unit Test failed on https://github.com/dotnet/roslyn/pull/9831

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#9952]
Link to build 
http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/5419/console 

output of the actual failure 
xUnit returned error code without errors

 xunit produced no error output but had exit code -1073740972
Indication 1 

....

I don't see any test failure

**Comment by davkean** [comment]
This is the VisualBasic.Scripting.Desktop tests - as to why they failed I can't see because Jenkins is playing up.

**Comment by davkean** [comment]
Microsoft.CodeAnalysis.VisualBasic.Scripting.Desktop.UnitTests to be exact

**Comment by ManishJayaswal** [comment]
@tmat - can you take a look at this issue

**Comment by tmat** [comment]
@davkean By Jenkins is playing up you mean artifacts not available?

**Comment by davkean** [comment]
No it wouldn't show the build page. If artifacts are showing up, it's because we've already deleted them. 

It's on our backlog to fix this: https://github.com/dotnet/roslyn/issues/8458.

**Comment by tmat** [comment]
I'm not sure what I can do about this without artifacts being available.
