### ISSUE TITLE
Unlocalized strings in the rename dashboard

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#9956]
![image](https://cloud.githubusercontent.com/assets/235241/13957859/31c4430c-f00b-11e5-9925-c33568cc8bc5.png)

Using the following `1.2` builds: ENU 25115.00 Enterprise + FRA 25115.00 LP

**Comment by dpoeschl** [comment]
Found on a somewhat older build... maybe it's better now?

The strings in question do come from resources, so it might be a loc pipeline problem?

FYI @jinujoseph

**Comment by jinujoseph** [comment]
Let me test this on latest build.

**Comment by jinujoseph** [comment]
Tested this on latest build and seems to be localized. 

![vsversion](https://cloud.githubusercontent.com/assets/12449387/14434091/ef926520-ffc5-11e5-818d-0c5cc702d8e4.JPG)

![renameui](https://cloud.githubusercontent.com/assets/12449387/14434095/f77cddc4-ffc5-11e5-9b4d-d798dccc05e2.JPG)

**Comment by jinujoseph** [comment]
![update2](https://cloud.githubusercontent.com/assets/12449387/14477809/4671bfa8-00c5-11e6-8374-cc080d783d12.JPG)
