### ISSUE TITLE
Inline Rename unusable under Narrator

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#9960]
1. No indication that Inline Rename has started
2. No indication that Inline Rename has been cancelled or completed
3. No way to focus the Dashboard & read options

**Comment by Pilchie** [comment]
Leaving in RC for the tenet issue.

**Comment by Pilchie** [comment]
Tagging @MattGertz this is an issue that we shipped in VS2015, and @dpoeschl assures me it's quite difficult to fix.  Should we seek a tenet exception for it?

**Comment by MattGertz** [comment]
@Pilchie Would be really great to fix ASAP, since this essentially hides the inline rename feature for many of our customers, but we are also going to be doing a lot more of this sort of work in post-RTW timeframe (we really need to!) and maybe this would dovetail.  Can you give me a costing offline (& ideally what the tricky/risky parts are), and then we can discuss exceptions.

**Comment by dpoeschl** [comment]
Three main parts:
1. Having Narrator announce that Inline Rename has started turned out to be way easier than anticipated (though it involved a fair amount of luck regarding the way that focus contention between the Dashboard and the editor worked out). This part is covered by https://github.com/dotnet/roslyn/pull/16381 (thanks to @matthejo for the help).
2. Having Narrator announce that Inline Rename has been committed or cancelled is trickier (because the UI is gone and we have nothing to attach an AutomationPeer to), and we're not sure how to handle it yet...
3. We'll additionally need a command to move actual keyboard focus to the dashboard so that the checkboxes can be toggled (and a way to move keyboard focus back to the editor).

**Comment by dpoeschl** [comment]
None of these issues were identified as MAS violations, but I'm sure they'll come up as "Usable" violations for our next push. I'm just going to close this and let our accessibility testers drive this, since they may have a better way of communicating the problems or may identify more problems. I've included these scenarios in our scenarios document.
