### ISSUE TITLE
langversion does not affect overload resolution

### ISSUE THREAD

**Issue by vcsjones** [dotnet/roslyn#9965]
**Version Used**: `csc 1.1.0.51109`

**Steps to Reproduce**:

1. Compile the below snippet using `csc /out:foo.exe /target:exe /langversion:5 foo.cs`

```csharp
using System;
using System.Threading.Tasks;

namespace Blarg
{
    class Program
    {
        static void Main(string[] args)
        {
            Create<string>(async blah =>
            {
                while (true)
                {
                    Console.WriteLine("foo.");
                }
            });
        }

        public static void Create<TResult>(Func<IObserver<TResult>, Task> subscribeAsync)
        {
        }

        public static void Create<TResult>(Func<IObserver<TResult>, Task<Action>> subscribeAsync)
        {
        }
    }
}
```

**Expected Behavior**: Compilation fails with an overload ambiguity error. It appears that the `langversion` does not affect the improvements to overload resolution that were introduced in C# 6.

**Actual Behavior**: Compilation succeeds.

**Comment by gafter** [comment]
This is intentional. The language version switch affects the syntax supported by the compiler.

**Comment by vcsjones** [comment]
It feels a bit inconsistent with #2725, since that didn't really introduce any new syntax either, just where the syntax could be used.

Regardless, thanks for clarifying this is intentional.
