### ISSUE TITLE
Proposal: Generic parameter constructor parameter constraints

### ISSUE THREAD

**Issue by smdrager** [dotnet/roslyn#9968]
I propose to allow the definition of constructor parameter constraints for generics. Currently the `new()` constraint is permitted, but parameters cannot be specified.

**Proposed syntax examples**

```
public class Example<TThing> where TThing : ThingBase, new(string, bool)
{
	public void DoWork(string a, bool b)
	{
		TThing t = new TThing(a, b);
		
		t.Run();
	}
} 
```

A more practical example, which is useful when following a pattern of having a model filled by a data object.

```
public class Example2<TThing, TThingData> where TThing : new(TThingData)
{
	public TThing DoWork(int id)
	{
		var thingData = DataAccess.GetThingData(id);
		
		return new TThing(thingData);
	}
}
```

**Comment by vcsjones** [comment]
I think this has been discussed before and determined that it would require support from the CLR before C# could support it. Currently CLR only supports `new()`.

**Comment by alrz** [comment]
Dup of #2206
