### ISSUE TITLE
[Proposal] Make `this` optional for extension methods used within the current class

### ISSUE THREAD

**Issue by ashmind** [dotnet/roslyn#998]
#### Problem

I wouldn't say this is a common problem, but it is pretty noticeable in some cases.
One example is ASP.NET MVC/WebApi.

Currently `Controller` and `ApiController` provide quite a few useful helper methods to the descendant classes. However it is not possible to add new helper methods in the same fashion without introducing an intermediate base class.

E.g. consider this controller action body:

``` csharp
if (!something.IsValid)
    return this.UnprocessableEntity(...);

return Ok(...);
```

Here `Ok()` is provided by the base class, but `UnprocessableEntity()` is an extension -- and so it requires `this` -- which looks weird and inconsistent.
#### Design

I propose considering extension methods of class `X`  if unqualified `M()` call within this class can't be resolved otherwise.
#### Pros
1. Makes extension methods more consistent with instance methods
2. Allows transparent polyfilling of base classes when provided by external library/framework
3. May open some new opportunities for DSLs, as DSL could grab current instance automatically
#### Cons
1. Makes method resolution more complex
   (though `using static` already introduced some complexity)
2. When reading code, it is unclear where the method comes from
   (no more than with `using static` and inherited methods?)
3. When reading code, it is unclear that the method can grab `this`
   (no more than with inherited methods?)
#### Community
1. StackOverflow: [Why is the 'this' keyword required to call an extension method from within the extended class](http://stackoverflow.com/questions/3510964/why-is-the-this-keyword-required-to-call-an-extension-method-from-within-the-e): 42 votes, 3 :star: (with [answer by Eric Lippert](http://stackoverflow.com/questions/3510964/why-is-the-this-keyword-required-to-call-an-extension-method-from-within-the-e#3513036) worth reading)

**Comment by paulomorgado** [comment]
I always qualify access to instance members with `this.`. So, this wouldn't be for me.

But, as @ashmind states, the confusion is already set with static imports...

**Comment by AnthonyDGreen** [comment]
@gafter, the existing VB rules allow this so there wouldn't be any work to do or design changes to consider so I cleared the VB tag.

I seem to remember us discussing this as a possible change for C# 6 and decided against it, though I can't recall why.

**Comment by mirhagk** [comment]
I want to point out that this is one of those "wait, what? Why doesn't that work?" kind of features. One of those that break the flow of coding because things don't work like you thought they would.

The really big problem here though isn't that you have to use `this`, which certainly is a bit odd (since `this` otherwise is really only used to disambiguate, and so occurs infrequently in a lot of code). The big problem is really the lack of intellisense.

I filed a suggestion for intellisense (#1526) and I feel like this is one of those things that would be unnecessary for the language to support if the tooling helped out more.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
