### ISSUE TITLE
(Proposal) Shorten Some Commonly Used Method Names.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#999]
I propose that we rename a few commonly used methods to be shorter which will aid in the readability of the scanner source. Making spotting common usage pattern a little easier.

Currently | Proposed
------------ | -------------
[CanGetCharAtOffset](https://github.com/dotnet/roslyn/blob/master/src/Compilers/VisualBasic/Portable/Scanner/Scanner.vb#L396) | `CanGet( at As Integer ) As Boolean` 
[PeekAheadChar](https://github.com/dotnet/roslyn/blob/master/src/Compilers/VisualBasic/Portable/Scanner/ScannerBuffer.vb#L99)  | `Peek( at As Integer ) As Char`  
[PeekAheadChar](https://github.com/dotnet/roslyn/blob/master/src/Compilers/VisualBasic/Portable/Scanner/ScannerBuffer.vb#L121) | `Peek() As Char`

### Example
**Before**
```vb
' check for '''(~')
Private Function StartsXmlDoc(Here As Integer) As Boolean
  Return ( _options.DocumentationMode >= DocumentationMode.Parse ) AndAlso
         CanGetCharAtOffset(Here + 3) AndAlso
      IsSingleQuote( PeekAheadChar(Here) ) AndAlso
      IsSingleQuote( PeekAheadChar(Here + 1) ) AndAlso
      IsSingleQuote( PeekAheadChar(Here + 2) ) AndAlso
  Not IsSingleQuote( PeekAheadChar(Here + 3) )
End Function
```
**After**
```vb
' check for '''(~')
Private Function StartsXmlDoc(Here As Integer) As Boolean
  Return ( _options.DocumentationMode >= DocumentationMode.Parse ) AndAlso
          CanGet(Here + 3) AndAlso IsSingleQuote( Peek(Here    ) ) AndAlso
                                   IsSingleQuote( Peek(Here + 1) ) AndAlso
                                   IsSingleQuote( Peek(Here + 2) ) AndAlso
                               Not IsSingleQuote( Peek(Here + 3) )
End Function
```
-------
**Before**
```vb
' // Check AM/PM

If CanGetCharAtOffset(Here) Then
    If PeekAheadChar(Here) = "A"c OrElse PeekAheadChar(Here) = FULLWIDTH_LATIN_CAPITAL_LETTER_A OrElse
       PeekAheadChar(Here) = "a"c OrElse PeekAheadChar(Here) = FULLWIDTH_LATIN_SMALL_LETTER_A Then

       HaveAM = True
       Here += 1

    ElseIf PeekAheadChar(Here) = "P"c OrElse PeekAheadChar(Here) = FULLWIDTH_LATIN_CAPITAL_LETTER_P OrElse
           PeekAheadChar(Here) = "p"c OrElse PeekAheadChar(Here) = FULLWIDTH_LATIN_SMALL_LETTER_P Then

           HavePM = True
           Here += 1

    End If

    If CanGetCharAtOffset(Here) AndAlso (HaveAM OrElse HavePM) Then
        If PeekAheadChar(Here) = "M"c OrElse PeekAheadChar(Here) = FULLWIDTH_LATIN_CAPITAL_LETTER_M OrElse
           PeekAheadChar(Here) = "m"c OrElse PeekAheadChar(Here) = FULLWIDTH_LATIN_SMALL_LETTER_M Then

           Here = GetWhitespaceLength(Here + 1)

        Else
            GoTo baddate
        End If
    End If
End If
```
**After**
```vb
' // Check AM/PM

If CanGet(Here) Then
    If Peek(Here) = "A"c OrElse Peek(Here) = FULLWIDTH_LATIN_CAPITAL_LETTER_A OrElse
       Peek(Here) = "a"c OrElse Peek(Here) = FULLWIDTH_LATIN_SMALL_LETTER_A Then

       HaveAM = True
       Here += 1

    ElseIf Peek(Here) = "P"c OrElse Peek(Here) = FULLWIDTH_LATIN_CAPITAL_LETTER_P OrElse
           Peek(Here) = "p"c OrElse Peek(Here) = FULLWIDTH_LATIN_SMALL_LETTER_P Then

           HavePM = True
           Here += 1

    End If

    If CanGet(Here) AndAlso (HaveAM OrElse HavePM) Then
        If Peek(Here) = "M"c OrElse Peek(Here) = FULLWIDTH_LATIN_CAPITAL_LETTER_M OrElse
           Peek(Here) = "m"c OrElse Peek(Here) = FULLWIDTH_LATIN_SMALL_LETTER_M Then

           Here = GetWhitespaceLength(Here + 1)

        Else
            GoTo baddate
        End If
    End If
End If
```

*Note: These `If`s are the target of the previous failed `TryPeek` pull requests.*

**Comment by gafter** [comment]
I can imagine accepting a pull request that does this, but it is hard to imagine the Roslyn team doing this themselves.

**Comment by AdamSpeight2008** [comment]
@gafter It would a big diff to do in one PR.
My plan was to do a branch for each and see if they build and test separately 
Then merge.

**Comment by AdamSpeight2008** [comment]
Just running the build + test for `Peek`

**Comment by theoy** [comment]
Nice to have.

**Comment by gafter** [comment]
The submitter has withdrawn his offer to do this.

**Comment by AdamSpeight2008** [comment]
@gafter I'm work on a version with the formatting changes.

**Comment by gafter** [comment]
Awesome! Please reopen when done. I can squash the commits when I merge your PR if you need to do it as a sequence of git commits.

**Comment by AdamSpeight2008** [comment]
@gafter I didn't think I can reopen the PR. (The changes are in 24c780edb36533a89f10692bae9ed46361c88dd9)

**Comment by gafter** [comment]
@AdamSpeight2008 Is there no "Reopen" button at the bottom of the PR?

**Comment by AdamSpeight2008** [comment]
@gafter Nope, I think that if one of the "main" contributor close a PR only one them can reopen.

**Comment by AdamSpeight2008** [comment]
@gafter Should I submit a new PR? From the new fork [SimpleNames](https://github.com/AdamSpeight2008/roslyn-AdamSpeight2008/tree/SimpleNames)

**Comment by AdamSpeight2008** [comment]
@gafter #1627
