### ISSUE TITLE
Project System: Simplified Add Item

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#9998]
This is tracking simplified add item - ie choose Add Item, such as Add Windows Form, should add to the tree and automatically enter rename mode instead of opening the dialog.

**Comment by NoneGiven** [comment]
To avoid the dialog, it would also be great if a few common items were always present. This is done somewhat in various project types (ex. "add new... typescript file/javascript file" dropdown items in web projects), but not consistently.

**Comment by davkean** [comment]
This issue was moved to dotnet/roslyn-project-system#77
